"""Unit tests for codegen"""

from physika.codegen import from_ast_to_torch
from pathlib import Path
import subprocess
import os
import pytest

from tests.conftest import load_expected_ast, parse_source_to_ast

from physika.core.elab.elab import Elab
from physika.core.inductive import mk_builtin_env

HEADER = "import torch\nimport torch.nn as nn\nimport torch.optim as optim\n"
EXAMPLES_DIR = Path(__file__).parent.parent / "examples"
PHYK_FILES = sorted(EXAMPLES_DIR.glob("*.phyk"))
PHYK_IDS = [f.stem for f in PHYK_FILES]
AST_DIR = EXAMPLES_DIR / "ast"
TORCH_CODE_DIR = EXAMPLES_DIR / "torch_code"


# Tests
def test_header_has_required_imports():
    """Generated code must contain the standard import header."""
    ast = {"functions": {}, "classes": {}, "program": []}
    code = from_ast_to_torch(ast, print_code=False)
    assert HEADER in code
    assert "\n# === Program ===" in code


@pytest.mark.parametrize("phyk_file", PHYK_FILES, ids=PHYK_IDS)
def test_from_ast_to_torch(phyk_file):
    """
    Code generated from the expected AST dict equals code generated by
    parsing the .phyk source.
    """
    ast = load_expected_ast(phyk_file.stem)
    code_ast = from_ast_to_torch(ast, print_code=False)
    src = phyk_file.read_text()
    code_phyk = from_ast_to_torch(parse_source_to_ast(src,
                                                      phyk_file.resolve()),
                                  print_code=False)

    assert HEADER in code_ast
    assert HEADER in code_phyk
    assert code_ast == code_phyk


@pytest.mark.parametrize("phyk_file", PHYK_FILES, ids=PHYK_IDS)
def test_codegen_matches_reference(phyk_file):
    """
    Code generated from each .phyk file must exactly match its reference
    python file in torch_code dir
    """
    src = phyk_file.read_text()

    unified_ast = parse_source_to_ast(
        src,
        phyk_file.resolve(),
    )
    cic_elab = Elab(mk_builtin_env())
    cic_result = cic_elab.elaborate(unified_ast)

    code_phyk = from_ast_to_torch(
        unified_ast,
        print_code=False,
        resolved_bodies=cic_result.get("resolved_bodies"),
        resolved_methods=cic_result.get("resolved_methods"),
        resolved_program=cic_result.get("resolved_program"),
        resolved_program_fvar_names=cic_result.get(
            "resolved_program_fvar_names"),
        cic_env=cic_elab.state.env,
    )
    code_torch = (TORCH_CODE_DIR / f"{phyk_file.stem}.py").read_text()

    assert HEADER in code_phyk
    assert HEADER in code_torch
    assert code_phyk == code_torch


@pytest.mark.parametrize("phyk_file", PHYK_FILES)
def test_physika_cli(phyk_file):
    """Test to runs all example physika files through subprocess"""

    # run matplotlib code in non-interactive mode
    env = os.environ.copy()
    env["MPLBACKEND"] = "Agg"

    result = subprocess.run(
        ["physika", str(phyk_file)],
        capture_output=True,
        text=True,
        env=env,
    )

    assert result.returncode == 0


@pytest.mark.parametrize("phyk_file", PHYK_FILES)
def test_physika_cli_print_ast(phyk_file):
    """
    Test to runs all example physika files with
    ``--print-ast`` flag through subprocess
    """

    # run matplotlib code in non-interactive mode
    env = os.environ.copy()
    env["MPLBACKEND"] = "Agg"

    result = subprocess.run(
        ["physika", str(phyk_file), "--print-ast"],
        capture_output=True,
        text=True,
        env=env,
    )

    assert result.returncode == 0


@pytest.mark.parametrize("phyk_file", PHYK_FILES)
def test_physika_cli_print_code(phyk_file):
    """
    Test to runs all example physika files with
    ``--print-code`` flag through subprocess
    """

    # run matplotlib code in non-interactive mode
    env = os.environ.copy()
    env["MPLBACKEND"] = "Agg"

    result = subprocess.run(
        ["physika", str(phyk_file), "--print-code"],
        capture_output=True,
        text=True,
        env=env,
    )

    assert result.returncode == 0
