"""Unit tests for codegen"""

from physika.codegen import from_ast_to_torch
from physika.utils.ast_utils import build_unified_ast
from physika.parser import parser, symbol_table
from physika.lexer import lexer
from pathlib import Path
import pytest

HEADER = "import torch\nimport torch.nn as nn\nimport torch.optim as optim\n"
EXAMPLES_DIR = Path(__file__).parent.parent / "examples"
PHYK_FILES = sorted(EXAMPLES_DIR.glob("*.phyk"))
PHYK_IDS = [f.stem for f in PHYK_FILES]
AST_DIR = EXAMPLES_DIR / "ast"
TORCH_CODE_DIR = EXAMPLES_DIR / "torch_code"


# Helper functions
def load_expected_ast(stem: str) -> dict:
    """Load the expected AST dict from ``examples/ast/<stem>.py``."""
    ns = {}
    exec((AST_DIR / f"{stem}.py").read_text(), ns)
    return ns["EXPECTED"]

def parse_source_to_ast(source: str) -> dict:
    """Run lexer/parser and build_unified_ast on a Physika source string."""
    symbol_table.clear()
    lexer.lexer.lineno = 1          # reset PLY line counter for deterministic output
    program_ast = parser.parse(source, lexer=lexer)
    return build_unified_ast(program_ast, symbol_table)


# Tests
def test_header_has_required_imports():
    """Generated code must contain the standard import header."""
    ast = {"functions": {}, "classes": {}, "program": []}
    code = from_ast_to_torch(ast, print_code=False)
    assert HEADER in code
    assert "\n# === Program ===" in code


@pytest.mark.parametrize("phyk_file", PHYK_FILES, ids=PHYK_IDS)
def test_from_ast_to_torch(phyk_file):
    """Code generated from the expected AST dict equals code generated by parsing the .phyk source."""
    ast = load_expected_ast(phyk_file.stem)
    code_ast = from_ast_to_torch(ast, print_code=False)
    src = phyk_file.read_text()
    code_phyk = from_ast_to_torch(parse_source_to_ast(src), print_code=False)

    assert HEADER in code_ast
    assert HEADER in code_phyk
    assert code_ast == code_phyk


@pytest.mark.parametrize("phyk_file", PHYK_FILES, ids=PHYK_IDS)
def test_codegen_matches_reference(phyk_file):
    """Code generated from each .phyk file must exactly match its reference python file in torch_code dir"""
    src = phyk_file.read_text()
    code_phyk = from_ast_to_torch(parse_source_to_ast(src), print_code=False)
    code_torch = (TORCH_CODE_DIR / f"{phyk_file.stem}.py").read_text()

    assert HEADER in code_phyk
    assert HEADER in code_torch
    assert code_phyk == code_torch


def test_grad_calls_in_function_statements():
    """compute_grad must be imported when grad is used in function statements"""
    src = """
def f(x: ℝ) : ℝ:
    g = grad(x, x)
    return g

v: R = 3.0
f(v)
"""
    code_phyk = from_ast_to_torch(parse_source_to_ast(src), print_code=False)
    assert "from runtime import compute_grad" in code_phyk