import torch
import torch.nn as nn
import torch.optim as optim

from physika.runtime import physika_print
from physika.runtime import compute_grad

# === Program ===
x = torch.stack([torch.as_tensor((1 + 2j), dtype=torch.complex64), torch.as_tensor((3 + 1j), dtype=torch.complex64), torch.as_tensor((0 + 4j), dtype=torch.complex64), torch.as_tensor((2 + 0j), dtype=torch.complex64)])
X = torch.fft.fft(x)
physika_print(X)
physika_print(torch.fft.ifft(X))
x2 = torch.tensor([[2.0, 0.0, 1.0, 3.0], [4.0, 1.0, 0.0, 2.0]])
X2 = torch.fft.fft2(x2)
physika_print(X2)
physika_print(torch.fft.ifft2(X2))
x3 = torch.tensor([[[1.0, 2.0, 3.0, 4.0], [5.0, 6.0, 7.0, 8.0]], [[9.0, 10.0, 11.0, 12.0], [13.0, 14.0, 15.0, 16.0]]])
X3 = torch.fft.fftn(x3)
physika_print(X3)
physika_print(torch.fft.ifftn(X3))
xr = torch.tensor([3.0, 1.0, 4.0, 1.0, 5.0, 9.0, 2.0, 6.0])
Xr = torch.fft.rfft(xr)
physika_print(Xr)
physika_print(torch.fft.irfft(Xr))
xr2 = torch.tensor([[1.0, 0.0, 2.0, 1.0], [3.0, 1.0, 0.0, 2.0]])
Xr2 = torch.fft.rfft2(xr2)
physika_print(Xr2)
physika_print(torch.fft.irfft2(Xr2))
xr3 = torch.tensor([[[2.0, 1.0, 0.0, 3.0], [1.0, 2.0, 1.0, 0.0]], [[0.0, 1.0, 2.0, 1.0], [3.0, 0.0, 1.0, 2.0]]])
Xr3 = torch.fft.rfftn(xr3)
physika_print(Xr3)
physika_print(torch.fft.irfftn(Xr3))
s = torch.as_tensor(torch.tensor([1.0, 2.0, 0.0, 3.0])).float().requires_grad_(True)
t = torch.stack([torch.as_tensor((4 + 0j), dtype=torch.complex64), torch.as_tensor((0 + 1j), dtype=torch.complex64), torch.as_tensor((2 + 3j), dtype=torch.complex64), torch.as_tensor((0 + 0j), dtype=torch.complex64)])
spec = torch.fft.fft(s)
diff = (spec - t)
loss = torch.sum((torch.abs(diff if isinstance(diff, torch.Tensor) else torch.tensor(float(diff))) * torch.abs(diff if isinstance(diff, torch.Tensor) else torch.tensor(float(diff)))) if isinstance((torch.abs(diff if isinstance(diff, torch.Tensor) else torch.tensor(float(diff))) * torch.abs(diff if isinstance(diff, torch.Tensor) else torch.tensor(float(diff)))), torch.Tensor) else torch.tensor(float((torch.abs(diff if isinstance(diff, torch.Tensor) else torch.tensor(float(diff))) * torch.abs(diff if isinstance(diff, torch.Tensor) else torch.tensor(float(diff)))))))
g = compute_grad(loss, s)
s2 = (s - (0.05 * g))
spec2 = torch.fft.fft(s2)
diff2 = (spec2 - t)
loss2 = torch.sum((torch.abs(diff2 if isinstance(diff2, torch.Tensor) else torch.tensor(float(diff2))) * torch.abs(diff2 if isinstance(diff2, torch.Tensor) else torch.tensor(float(diff2)))) if isinstance((torch.abs(diff2 if isinstance(diff2, torch.Tensor) else torch.tensor(float(diff2))) * torch.abs(diff2 if isinstance(diff2, torch.Tensor) else torch.tensor(float(diff2)))), torch.Tensor) else torch.tensor(float((torch.abs(diff2 if isinstance(diff2, torch.Tensor) else torch.tensor(float(diff2))) * torch.abs(diff2 if isinstance(diff2, torch.Tensor) else torch.tensor(float(diff2)))))))
physika_print(g)
physika_print(loss)
physika_print(loss2)