EXPECTED = {'classes': {'Atom': {'class_params': [('atoms', ('struct_type', 'Atoms')),
                                       ('index', 'ℝ')],
                      'fields': [],
                      'methods': [{'body': ('field_access',
                                            ('var', 'this'),
                                            'index'),
                                   'name': 'idx',
                                   'params': [],
                                   'return_type': 'ℝ',
                                   'statements': []},
                                  {'body': ('method_call',
                                            ('field_access',
                                             ('var', 'this'),
                                             'atoms'),
                                            'atomic_number',
                                            [('field_access',
                                              ('var', 'this'),
                                              'index')]),
                                   'name': 'number',
                                   'params': [],
                                   'return_type': 'ℝ',
                                   'statements': []},
                                  {'body': ('method_call',
                                            ('field_access',
                                             ('var', 'this'),
                                             'atoms'),
                                            'mass',
                                            [('field_access',
                                              ('var', 'this'),
                                              'index')]),
                                   'name': 'mass',
                                   'params': [],
                                   'return_type': 'ℝ',
                                   'statements': []},
                                  {'body': ('method_call',
                                            ('field_access',
                                             ('var', 'this'),
                                             'atoms'),
                                            'position',
                                            [('field_access',
                                              ('var', 'this'),
                                              'index')]),
                                   'name': 'position',
                                   'params': [],
                                   'return_type': ('tensor',
                                                   [(3, 'invariant')]),
                                   'statements': []},
                                  {'body': ('index', 'p', ('num', 0)),
                                   'name': 'x',
                                   'params': [],
                                   'return_type': 'ℝ',
                                   'statements': [('body_decl',
                                                   'p',
                                                   ('tensor',
                                                    [(3, 'invariant')]),
                                                   ('method_call',
                                                    ('field_access',
                                                     ('var', 'this'),
                                                     'atoms'),
                                                    'position',
                                                    [('field_access',
                                                      ('var', 'this'),
                                                      'index')]))]},
                                  {'body': ('index', 'p', ('num', 1)),
                                   'name': 'y',
                                   'params': [],
                                   'return_type': 'ℝ',
                                   'statements': [('body_decl',
                                                   'p',
                                                   ('tensor',
                                                    [(3, 'invariant')]),
                                                   ('method_call',
                                                    ('field_access',
                                                     ('var', 'this'),
                                                     'atoms'),
                                                    'position',
                                                    [('field_access',
                                                      ('var', 'this'),
                                                      'index')]))]},
                                  {'body': ('index', 'p', ('num', 2)),
                                   'name': 'z',
                                   'params': [],
                                   'return_type': 'ℝ',
                                   'statements': [('body_decl',
                                                   'p',
                                                   ('tensor',
                                                    [(3, 'invariant')]),
                                                   ('method_call',
                                                    ('field_access',
                                                     ('var', 'this'),
                                                     'atoms'),
                                                    'position',
                                                    [('field_access',
                                                      ('var', 'this'),
                                                      'index')]))]},
                                  {'body': ('method_call',
                                            ('field_access',
                                             ('var', 'this'),
                                             'atoms'),
                                            'momentum',
                                            [('field_access',
                                              ('var', 'this'),
                                              'index')]),
                                   'name': 'momentum',
                                   'params': [],
                                   'return_type': ('tensor',
                                                   [(3, 'invariant')]),
                                   'statements': []},
                                  {'body': ('method_call',
                                            ('field_access',
                                             ('var', 'this'),
                                             'atoms'),
                                            'tag',
                                            [('field_access',
                                              ('var', 'this'),
                                              'index')]),
                                   'name': 'tag',
                                   'params': [],
                                   'return_type': 'ℝ',
                                   'statements': []},
                                  {'body': ('method_call',
                                            ('field_access',
                                             ('var', 'this'),
                                             'atoms'),
                                            'magmom',
                                            [('field_access',
                                              ('var', 'this'),
                                              'index')]),
                                   'name': 'magmom',
                                   'params': [],
                                   'return_type': 'ℝ',
                                   'statements': []},
                                  {'body': ('method_call',
                                            ('field_access',
                                             ('var', 'this'),
                                             'atoms'),
                                            'charge',
                                            [('field_access',
                                              ('var', 'this'),
                                              'index')]),
                                   'name': 'charge',
                                   'params': [],
                                   'return_type': 'ℝ',
                                   'statements': []},
                                  {'body': ('method_call',
                                            ('field_access',
                                             ('var', 'this'),
                                             'atoms'),
                                            'distance',
                                            [('field_access',
                                              ('var', 'this'),
                                              'index'),
                                             ('var', 'b')]),
                                   'name': 'distance_to',
                                   'params': [('b', 'ℝ')],
                                   'return_type': 'ℝ',
                                   'statements': []}]},
             'Atoms': {'class_params': [('numbers',
                                         ('tensor', [('n', 'invariant')])),
                                        ('positions',
                                         ('tensor',
                                          [('n', 'invariant'),
                                           (3, 'invariant')])),
                                        ('masses',
                                         ('tensor', [('n', 'invariant')])),
                                        ('tags',
                                         ('tensor', [('n', 'invariant')])),
                                        ('momenta',
                                         ('tensor',
                                          [('n', 'invariant'),
                                           (3, 'invariant')])),
                                        ('magmoms',
                                         ('tensor', [('n', 'invariant')])),
                                        ('charges',
                                         ('tensor', [('n', 'invariant')])),
                                        ('cell',
                                         ('tensor',
                                          [(3, 'invariant'),
                                           (3, 'invariant')]))],
                       'fields': [],
                       'methods': [{'body': ('mul',
                                             ('call',
                                              'len',
                                              [('field_access',
                                                ('var', 'this'),
                                                'numbers')]),
                                             ('num', 1.0)),
                                    'name': 'count',
                                    'params': [],
                                    'return_type': 'ℝ',
                                    'statements': []},
                                   {'body': ('index', 'nums', ('var', 'a')),
                                    'name': 'atomic_number',
                                    'params': [('a', 'ℝ')],
                                    'return_type': 'ℝ',
                                    'statements': [('body_decl',
                                                    'nums',
                                                    ('tensor',
                                                     [('n', 'invariant')]),
                                                    ('field_access',
                                                     ('var', 'this'),
                                                     'numbers'))]},
                                   {'body': ('index', 'm', ('var', 'a')),
                                    'name': 'mass',
                                    'params': [('a', 'ℝ')],
                                    'return_type': 'ℝ',
                                    'statements': [('body_decl',
                                                    'm',
                                                    ('tensor',
                                                     [('n', 'invariant')]),
                                                    ('field_access',
                                                     ('var', 'this'),
                                                     'masses'))]},
                                   {'body': ('index', 'pos', ('var', 'a')),
                                    'name': 'position',
                                    'params': [('a', 'ℝ')],
                                    'return_type': ('tensor',
                                                    [(3, 'invariant')]),
                                    'statements': [('body_decl',
                                                    'pos',
                                                    ('tensor',
                                                     [('n', 'invariant'),
                                                      (3, 'invariant')]),
                                                    ('field_access',
                                                     ('var', 'this'),
                                                     'positions'))]},
                                   {'body': ('index', 'mom', ('var', 'a')),
                                    'name': 'momentum',
                                    'params': [('a', 'ℝ')],
                                    'return_type': ('tensor',
                                                    [(3, 'invariant')]),
                                    'statements': [('body_decl',
                                                    'mom',
                                                    ('tensor',
                                                     [('n', 'invariant'),
                                                      (3, 'invariant')]),
                                                    ('field_access',
                                                     ('var', 'this'),
                                                     'momenta'))]},
                                   {'body': ('index', 't', ('var', 'a')),
                                    'name': 'tag',
                                    'params': [('a', 'ℝ')],
                                    'return_type': 'ℝ',
                                    'statements': [('body_decl',
                                                    't',
                                                    ('tensor',
                                                     [('n', 'invariant')]),
                                                    ('field_access',
                                                     ('var', 'this'),
                                                     'tags'))]},
                                   {'body': ('index', 'mm', ('var', 'a')),
                                    'name': 'magmom',
                                    'params': [('a', 'ℝ')],
                                    'return_type': 'ℝ',
                                    'statements': [('body_decl',
                                                    'mm',
                                                    ('tensor',
                                                     [('n', 'invariant')]),
                                                    ('field_access',
                                                     ('var', 'this'),
                                                     'magmoms'))]},
                                   {'body': ('index', 'q', ('var', 'a')),
                                    'name': 'charge',
                                    'params': [('a', 'ℝ')],
                                    'return_type': 'ℝ',
                                    'statements': [('body_decl',
                                                    'q',
                                                    ('tensor',
                                                     [('n', 'invariant')]),
                                                    ('field_access',
                                                     ('var', 'this'),
                                                     'charges'))]},
                                   {'body': ('call',
                                             'Atom',
                                             [('var', 'this'), ('var', 'idx')]),
                                    'name': 'atom',
                                    'params': [('idx', 'ℝ')],
                                    'return_type': ('struct_type', 'Atom'),
                                    'statements': []},
                                   {'body': ('call', 'sum', [('var', 'm')]),
                                    'name': 'total_mass',
                                    'params': [],
                                    'return_type': 'ℝ',
                                    'statements': [('body_decl',
                                                    'm',
                                                    ('tensor',
                                                     [('n', 'invariant')]),
                                                    ('field_access',
                                                     ('var', 'this'),
                                                     'masses'))]},
                                   {'body': ('call', 'sum', [('var', 'q')]),
                                    'name': 'total_charge',
                                    'params': [],
                                    'return_type': 'ℝ',
                                    'statements': [('body_decl',
                                                    'q',
                                                    ('tensor',
                                                     [('n', 'invariant')]),
                                                    ('field_access',
                                                     ('var', 'this'),
                                                     'charges'))]},
                                   {'body': ('var', 'total'),
                                    'name': 'kinetic_energy',
                                    'params': [],
                                    'return_type': 'ℝ',
                                    'statements': [('body_decl',
                                                    'mom',
                                                    ('tensor',
                                                     [('n', 'invariant'),
                                                      (3, 'invariant')]),
                                                    ('field_access',
                                                     ('var', 'this'),
                                                     'momenta')),
                                                   ('body_decl',
                                                    'mass',
                                                    ('tensor',
                                                     [('n', 'invariant')]),
                                                    ('field_access',
                                                     ('var', 'this'),
                                                     'masses')),
                                                   ('body_decl',
                                                    'k',
                                                    'ℕ',
                                                    ('call',
                                                     'len',
                                                     [('var', 'mass')])),
                                                   ('body_decl',
                                                    'total',
                                                    'ℝ',
                                                    ('num', 0.0)),
                                                   ('body_for_range',
                                                    'a',
                                                    ('num', 0),
                                                    ('var', 'k'),
                                                    [('loop_pluseq',
                                                      'total',
                                                      ('div',
                                                       ('call',
                                                        'sum',
                                                        [('mul',
                                                          ('index',
                                                           'mom',
                                                           ('var', 'a')),
                                                          ('index',
                                                           'mom',
                                                           ('var', 'a')))]),
                                                       ('mul',
                                                        ('num', 2.0),
                                                        ('index',
                                                         'mass',
                                                         ('var', 'a')))))])]},
                                   {'body': ('mul',
                                             ('var', 'acc'),
                                             ('div',
                                              ('num', 1.0),
                                              ('call',
                                               'sum',
                                               [('var', 'mass')]))),
                                    'name': 'center_of_mass',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [(3, 'invariant')]),
                                    'statements': [('body_decl',
                                                    'pos',
                                                    ('tensor',
                                                     [('n', 'invariant'),
                                                      (3, 'invariant')]),
                                                    ('field_access',
                                                     ('var', 'this'),
                                                     'positions')),
                                                   ('body_decl',
                                                    'mass',
                                                    ('tensor',
                                                     [('n', 'invariant')]),
                                                    ('field_access',
                                                     ('var', 'this'),
                                                     'masses')),
                                                   ('body_decl',
                                                    'k',
                                                    'ℕ',
                                                    ('call',
                                                     'len',
                                                     [('var', 'pos')])),
                                                   ('body_decl',
                                                    'acc',
                                                    ('tensor',
                                                     [(3, 'invariant')]),
                                                    ('for_expr',
                                                     'c',
                                                     ('num', 3),
                                                     ('mul',
                                                      ('var', 'c'),
                                                      ('num', 0.0)))),
                                                   ('body_for_range',
                                                    'a',
                                                    ('num', 0),
                                                    ('var', 'k'),
                                                    [('loop_assign',
                                                      'acc',
                                                      ('add',
                                                       ('var', 'acc'),
                                                       ('mul',
                                                        ('index',
                                                         'pos',
                                                         ('var', 'a')),
                                                        ('index',
                                                         'mass',
                                                         ('var', 'a')))))])]},
                                   {'body': ('call',
                                             'sqrt',
                                             [('call',
                                               'sum',
                                               [('mul',
                                                 ('var', 'd'),
                                                 ('var', 'd'))])]),
                                    'name': 'distance',
                                    'params': [('a', 'ℝ'), ('b', 'ℝ')],
                                    'return_type': 'ℝ',
                                    'statements': [('body_decl',
                                                    'pos',
                                                    ('tensor',
                                                     [('n', 'invariant'),
                                                      (3, 'invariant')]),
                                                    ('field_access',
                                                     ('var', 'this'),
                                                     'positions')),
                                                   ('body_decl',
                                                    'd',
                                                    ('tensor',
                                                     [(3, 'invariant')]),
                                                    ('sub',
                                                     ('index',
                                                      'pos',
                                                      ('var', 'a')),
                                                     ('index',
                                                      'pos',
                                                      ('var', 'b'))))]},
                                   {'body': ('var', 'result'),
                                    'name': 'all_distances',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('n', 'invariant'),
                                                     ('n', 'invariant')]),
                                    'statements': [('body_decl',
                                                    'pos',
                                                    ('tensor',
                                                     [('n', 'invariant'),
                                                      (3, 'invariant')]),
                                                    ('field_access',
                                                     ('var', 'this'),
                                                     'positions')),
                                                   ('body_decl',
                                                    'k',
                                                    'ℕ',
                                                    ('call',
                                                     'len',
                                                     [('var', 'pos')])),
                                                   ('body_decl',
                                                    'result',
                                                    ('tensor',
                                                     [('n', 'invariant'),
                                                      ('n', 'invariant')]),
                                                    ('for_expr',
                                                     'a',
                                                     ('var', 'k'),
                                                     ('for_expr',
                                                      'b',
                                                      ('var', 'k'),
                                                      ('mul',
                                                       ('add',
                                                        ('var', 'a'),
                                                        ('var', 'b')),
                                                       ('num', 0.0))))),
                                                   ('body_for_range',
                                                    'a',
                                                    ('num', 0),
                                                    ('var', 'k'),
                                                    [('loop_for_range',
                                                      'b',
                                                      ('num', 0),
                                                      ('var', 'k'),
                                                      [('loop_tuple_unpack',
                                                        [('d',
                                                          ('tensor',
                                                           [(3,
                                                             'invariant')]))],
                                                        ('sub',
                                                         ('index',
                                                          'pos',
                                                          ('var', 'a')),
                                                         ('index',
                                                          'pos',
                                                          ('var', 'b')))),
                                                       ('loop_index_assign_nd',
                                                        'result',
                                                        [('index_item',
                                                          ('var', 'a')),
                                                         ('index_item',
                                                          ('var', 'b'))],
                                                        ('call',
                                                         'sqrt',
                                                         [('call',
                                                           'sum',
                                                           [('mul',
                                                             ('var', 'd'),
                                                             ('var',
                                                              'd'))])]))])])]},
                                   {'body': ('var', 'total'),
                                    'name': 'count_species',
                                    'params': [('z', 'ℝ')],
                                    'return_type': 'ℝ',
                                    'statements': [('body_decl',
                                                    'nums',
                                                    ('tensor',
                                                     [('n', 'invariant')]),
                                                    ('field_access',
                                                     ('var', 'this'),
                                                     'numbers')),
                                                   ('body_decl',
                                                    'k',
                                                    'ℕ',
                                                    ('call',
                                                     'len',
                                                     [('var', 'nums')])),
                                                   ('body_decl',
                                                    'total',
                                                    'ℝ',
                                                    ('num', 0.0)),
                                                   ('body_for_range',
                                                    'a',
                                                    ('num', 0),
                                                    ('var', 'k'),
                                                    [('loop_if',
                                                      ('cond_eq',
                                                       ('index',
                                                        'nums',
                                                        ('var', 'a')),
                                                       ('var', 'z')),
                                                      [('loop_pluseq',
                                                        'total',
                                                        ('num', 1.0))])])]},
                                   {'body': ('call', 'abs', [('var', 'det')]),
                                    'name': 'volume',
                                    'params': [],
                                    'return_type': 'ℝ',
                                    'statements': [('body_decl',
                                                    'c',
                                                    ('tensor',
                                                     [(3, 'invariant'),
                                                      (3, 'invariant')]),
                                                    ('field_access',
                                                     ('var', 'this'),
                                                     'cell')),
                                                   ('body_decl',
                                                    'm0',
                                                    'ℝ',
                                                    ('sub',
                                                     ('mul',
                                                      ('indexN',
                                                       'c',
                                                       [('index_item',
                                                         ('num', 1)),
                                                        ('index_item',
                                                         ('num', 1))]),
                                                      ('indexN',
                                                       'c',
                                                       [('index_item',
                                                         ('num', 2)),
                                                        ('index_item',
                                                         ('num', 2))])),
                                                     ('mul',
                                                      ('indexN',
                                                       'c',
                                                       [('index_item',
                                                         ('num', 1)),
                                                        ('index_item',
                                                         ('num', 2))]),
                                                      ('indexN',
                                                       'c',
                                                       [('index_item',
                                                         ('num', 2)),
                                                        ('index_item',
                                                         ('num', 1))])))),
                                                   ('body_decl',
                                                    'm1',
                                                    'ℝ',
                                                    ('sub',
                                                     ('mul',
                                                      ('indexN',
                                                       'c',
                                                       [('index_item',
                                                         ('num', 1)),
                                                        ('index_item',
                                                         ('num', 0))]),
                                                      ('indexN',
                                                       'c',
                                                       [('index_item',
                                                         ('num', 2)),
                                                        ('index_item',
                                                         ('num', 2))])),
                                                     ('mul',
                                                      ('indexN',
                                                       'c',
                                                       [('index_item',
                                                         ('num', 1)),
                                                        ('index_item',
                                                         ('num', 2))]),
                                                      ('indexN',
                                                       'c',
                                                       [('index_item',
                                                         ('num', 2)),
                                                        ('index_item',
                                                         ('num', 0))])))),
                                                   ('body_decl',
                                                    'm2',
                                                    'ℝ',
                                                    ('sub',
                                                     ('mul',
                                                      ('indexN',
                                                       'c',
                                                       [('index_item',
                                                         ('num', 1)),
                                                        ('index_item',
                                                         ('num', 0))]),
                                                      ('indexN',
                                                       'c',
                                                       [('index_item',
                                                         ('num', 2)),
                                                        ('index_item',
                                                         ('num', 1))])),
                                                     ('mul',
                                                      ('indexN',
                                                       'c',
                                                       [('index_item',
                                                         ('num', 1)),
                                                        ('index_item',
                                                         ('num', 1))]),
                                                      ('indexN',
                                                       'c',
                                                       [('index_item',
                                                         ('num', 2)),
                                                        ('index_item',
                                                         ('num', 0))])))),
                                                   ('body_decl',
                                                    'det',
                                                    'ℝ',
                                                    ('add',
                                                     ('sub',
                                                      ('mul',
                                                       ('indexN',
                                                        'c',
                                                        [('index_item',
                                                          ('num', 0)),
                                                         ('index_item',
                                                          ('num', 0))]),
                                                       ('var', 'm0')),
                                                      ('mul',
                                                       ('indexN',
                                                        'c',
                                                        [('index_item',
                                                          ('num', 0)),
                                                         ('index_item',
                                                          ('num', 1))]),
                                                       ('var', 'm1'))),
                                                     ('mul',
                                                      ('indexN',
                                                       'c',
                                                       [('index_item',
                                                         ('num', 0)),
                                                        ('index_item',
                                                         ('num', 2))]),
                                                      ('var', 'm2'))))]},
                                   {'body': ('call',
                                             'Atoms',
                                             [('field_access',
                                               ('var', 'this'),
                                               'numbers'),
                                              ('var', 'moved'),
                                              ('field_access',
                                               ('var', 'this'),
                                               'masses'),
                                              ('field_access',
                                               ('var', 'this'),
                                               'tags'),
                                              ('field_access',
                                               ('var', 'this'),
                                               'momenta'),
                                              ('field_access',
                                               ('var', 'this'),
                                               'magmoms'),
                                              ('field_access',
                                               ('var', 'this'),
                                               'charges'),
                                              ('field_access',
                                               ('var', 'this'),
                                               'cell')]),
                                    'name': 'translate',
                                    'params': [('shift',
                                                ('tensor',
                                                 [(3, 'invariant')]))],
                                    'return_type': ('struct_type', 'Atoms'),
                                    'statements': [('body_decl',
                                                    'pos',
                                                    ('tensor',
                                                     [('n', 'invariant'),
                                                      (3, 'invariant')]),
                                                    ('field_access',
                                                     ('var', 'this'),
                                                     'positions')),
                                                   ('body_decl',
                                                    'k',
                                                    'ℕ',
                                                    ('call',
                                                     'len',
                                                     [('var', 'pos')])),
                                                   ('body_decl',
                                                    'moved',
                                                    ('tensor',
                                                     [('n', 'invariant'),
                                                      (3, 'invariant')]),
                                                    ('for_expr',
                                                     'a',
                                                     ('var', 'k'),
                                                     ('for_expr',
                                                      'c',
                                                      ('num', 3),
                                                      ('add',
                                                       ('indexN',
                                                        'pos',
                                                        [('index_item',
                                                          ('var', 'a')),
                                                         ('index_item',
                                                          ('var', 'c'))]),
                                                       ('index',
                                                        'shift',
                                                        ('var', 'c'))))))]},
                                   {'body': ('method_call',
                                             ('var', 'this'),
                                             'translate',
                                             [('mul',
                                               ('var', 'com'),
                                               ('neg', ('num', 1.0)))]),
                                    'name': 'centered',
                                    'params': [],
                                    'return_type': ('struct_type', 'Atoms'),
                                    'statements': [('body_decl',
                                                    'com',
                                                    ('tensor',
                                                     [(3, 'invariant')]),
                                                    ('method_call',
                                                     ('var', 'this'),
                                                     'center_of_mass',
                                                     []))]}]}},
 'functions': {'molecule': {'body': ('call',
                                     'Atoms',
                                     [('var', 'numbers'),
                                      ('var', 'positions'),
                                      ('var', 'masses'),
                                      ('var', 'zeros1'),
                                      ('var', 'zeros3'),
                                      ('var', 'zeros1'),
                                      ('var', 'zeros1'),
                                      ('var', 'cell')]),
                            'has_loop': False,
                            'params': [('numbers',
                                        ('tensor', [('p', 'invariant')])),
                                       ('positions',
                                        ('tensor',
                                         [('p', 'invariant'),
                                          (3, 'invariant')])),
                                       ('masses',
                                        ('tensor', [('p', 'invariant')])),
                                       ('box', 'ℝ')],
                            'return_type': ('struct_type', 'Atoms'),
                            'statements': [('body_decl',
                                            'k',
                                            'ℕ',
                                            ('call',
                                             'len',
                                             [('var', 'numbers')])),
                                           ('body_decl',
                                            'zeros1',
                                            ('tensor', [('p', 'invariant')]),
                                            ('for_expr',
                                             'a',
                                             ('var', 'k'),
                                             ('mul',
                                              ('index',
                                               'numbers',
                                               ('var', 'a')),
                                              ('num', 0.0)))),
                                           ('body_decl',
                                            'zeros3',
                                            ('tensor',
                                             [('p', 'invariant'),
                                              (3, 'invariant')]),
                                            ('for_expr',
                                             'a',
                                             ('var', 'k'),
                                             ('for_expr',
                                              'c',
                                              ('num', 3),
                                              ('mul',
                                               ('indexN',
                                                'positions',
                                                [('index_item', ('var', 'a')),
                                                 ('index_item', ('var', 'c'))]),
                                               ('num', 0.0))))),
                                           ('body_decl',
                                            'cell',
                                            ('tensor',
                                             [(3, 'invariant'),
                                              (3, 'invariant')]),
                                            ('array',
                                             [('array',
                                               [('var', 'box'),
                                                ('num', 0.0),
                                                ('num', 0.0)]),
                                              ('array',
                                               [('num', 0.0),
                                                ('var', 'box'),
                                                ('num', 0.0)]),
                                              ('array',
                                               [('num', 0.0),
                                                ('num', 0.0),
                                                ('var', 'box')])]))]}},
 'program': [('class_def', 'Atom'),
             ('class_def', 'Atoms'),
             ('func_def', 'molecule'),
             ('decl',
              'w_numbers',
              ('tensor', [(3, 'invariant')]),
              ('array', [('num', 8.0), ('num', 1.0), ('num', 1.0)]),
              210),
             ('decl',
              'w_positions',
              ('tensor', [(3, 'invariant'), (3, 'invariant')]),
              ('array',
               [('array', [('num', 0.0), ('num', 0.0), ('num', 0.0)]),
                ('array', [('num', 0.9584), ('num', 0.0), ('num', 0.0)]),
                ('array',
                 [('neg', ('num', 0.2399)), ('num', 0.9279), ('num', 0.0)])]),
              211),
             ('decl',
              'w_masses',
              ('tensor', [(3, 'invariant')]),
              ('array', [('num', 15.999), ('num', 1.008), ('num', 1.008)]),
              216),
             ('decl',
              'w_tags',
              ('tensor', [(3, 'invariant')]),
              ('array', [('num', 0.0), ('num', 1.0), ('num', 1.0)]),
              217),
             ('decl',
              'w_momenta',
              ('tensor', [(3, 'invariant'), (3, 'invariant')]),
              ('array',
               [('array', [('num', 0.0), ('num', 0.0), ('num', 0.0)]),
                ('array', [('num', 0.2), ('num', 0.0), ('num', 0.0)]),
                ('array',
                 [('neg', ('num', 0.2)), ('num', 0.0), ('num', 0.0)])]),
              218),
             ('decl',
              'w_magmoms',
              ('tensor', [(3, 'invariant')]),
              ('array', [('num', 0.0), ('num', 0.0), ('num', 0.0)]),
              223),
             ('decl',
              'w_charges',
              ('tensor', [(3, 'invariant')]),
              ('array',
               [('neg', ('num', 0.834)), ('num', 0.417), ('num', 0.417)]),
              224),
             ('decl',
              'w_cell',
              ('tensor', [(3, 'invariant'), (3, 'invariant')]),
              ('array',
               [('array', [('num', 10.0), ('num', 0.0), ('num', 0.0)]),
                ('array', [('num', 0.0), ('num', 10.0), ('num', 0.0)]),
                ('array', [('num', 0.0), ('num', 0.0), ('num', 10.0)])]),
              225),
             ('assign',
              'water',
              ('call',
               'Atoms',
               [('var', 'w_numbers'),
                ('var', 'w_positions'),
                ('var', 'w_masses'),
                ('var', 'w_tags'),
                ('var', 'w_momenta'),
                ('var', 'w_magmoms'),
                ('var', 'w_charges'),
                ('var', 'w_cell')]),
              230),
             ('expr', ('method_call', ('var', 'water'), 'count', []), 0),
             ('expr', ('method_call', ('var', 'water'), 'total_mass', []), 0),
             ('expr', ('method_call', ('var', 'water'), 'total_charge', []), 0),
             ('expr',
              ('method_call', ('var', 'water'), 'kinetic_energy', []),
              0),
             ('expr',
              ('method_call', ('var', 'water'), 'center_of_mass', []),
              0),
             ('expr',
              ('method_call',
               ('var', 'water'),
               'distance',
               [('num', 0.0), ('num', 1.0)]),
              0),
             ('expr',
              ('method_call', ('var', 'water'), 'all_distances', []),
              0),
             ('assign',
              'o',
              ('method_call', ('var', 'water'), 'atom', [('num', 0.0)]),
              243),
             ('expr', ('method_call', ('var', 'o'), 'idx', []), 0),
             ('expr', ('method_call', ('var', 'o'), 'number', []), 0),
             ('expr', ('method_call', ('var', 'o'), 'mass', []), 0),
             ('expr', ('method_call', ('var', 'o'), 'position', []), 0),
             ('expr', ('method_call', ('var', 'o'), 'charge', []), 0),
             ('assign',
              'h1',
              ('method_call', ('var', 'water'), 'atom', [('num', 1.0)]),
              249),
             ('expr', ('method_call', ('var', 'h1'), 'number', []), 0),
             ('expr', ('method_call', ('var', 'h1'), 'x', []), 0),
             ('expr', ('method_call', ('var', 'h1'), 'momentum', []), 0),
             ('expr', ('method_call', ('var', 'h1'), 'tag', []), 0),
             ('expr', ('method_call', ('var', 'h1'), 'magmom', []), 0),
             ('expr', ('method_call', ('var', 'h1'), 'charge', []), 0),
             ('expr',
              ('method_call', ('var', 'h1'), 'distance_to', [('num', 2.0)]),
              0),
             ('decl',
              'shift',
              ('tensor', [(3, 'invariant')]),
              ('array', [('num', 1.0), ('num', 2.0), ('num', 3.0)]),
              260),
             ('assign',
              'moved',
              ('method_call',
               ('var', 'water'),
               'translate',
               [('var', 'shift')]),
              261),
             ('expr',
              ('method_call', ('var', 'moved'), 'center_of_mass', []),
              0),
             ('assign',
              'centred',
              ('method_call', ('var', 'water'), 'centered', []),
              263),
             ('expr',
              ('method_call', ('var', 'centred'), 'center_of_mass', []),
              0),
             ('decl',
              'co_numbers',
              ('tensor', [(2, 'invariant')]),
              ('array', [('num', 6.0), ('num', 8.0)]),
              267),
             ('decl',
              'co_positions',
              ('tensor', [(2, 'invariant'), (3, 'invariant')]),
              ('array',
               [('array', [('num', 0.0), ('num', 0.0), ('num', 0.0)]),
                ('array', [('num', 1.128), ('num', 0.0), ('num', 0.0)])]),
              268),
             ('decl',
              'co_masses',
              ('tensor', [(2, 'invariant')]),
              ('array', [('num', 12.011), ('num', 15.999)]),
              272),
             ('assign',
              'co',
              ('call',
               'molecule',
               [('var', 'co_numbers'),
                ('var', 'co_positions'),
                ('var', 'co_masses'),
                ('num', 8.0)]),
              273),
             ('expr',
              ('method_call',
               ('method_call', ('var', 'co'), 'atom', [('num', 0.0)]),
               'charge',
               []),
              0),
             ('expr',
              ('method_call',
               ('method_call', ('var', 'co'), 'atom', [('num', 1.0)]),
               'tag',
               []),
              0),
             ('decl',
              'nacl_numbers',
              ('tensor', [(2, 'invariant')]),
              ('array', [('num', 11.0), ('num', 17.0)]),
              279),
             ('decl',
              'nacl_positions',
              ('tensor', [(2, 'invariant'), (3, 'invariant')]),
              ('array',
               [('array', [('num', 0.0), ('num', 0.0), ('num', 0.0)]),
                ('array', [('num', 2.82), ('num', 2.82), ('num', 2.82)])]),
              280),
             ('decl',
              'nacl_masses',
              ('tensor', [(2, 'invariant')]),
              ('array', [('num', 22.99), ('num', 35.45)]),
              284),
             ('decl',
              'nacl_tags',
              ('tensor', [(2, 'invariant')]),
              ('array', [('num', 0.0), ('num', 0.0)]),
              285),
             ('decl',
              'nacl_momenta',
              ('tensor', [(2, 'invariant'), (3, 'invariant')]),
              ('array',
               [('array', [('num', 0.0), ('num', 0.0), ('num', 0.0)]),
                ('array', [('num', 0.0), ('num', 0.0), ('num', 0.0)])]),
              286),
             ('decl',
              'nacl_magmoms',
              ('tensor', [(2, 'invariant')]),
              ('array', [('num', 0.0), ('num', 0.0)]),
              290),
             ('decl',
              'nacl_charges',
              ('tensor', [(2, 'invariant')]),
              ('array', [('num', 1.0), ('neg', ('num', 1.0))]),
              291),
             ('decl',
              'nacl_cell',
              ('tensor', [(3, 'invariant'), (3, 'invariant')]),
              ('array',
               [('array', [('num', 0.0), ('num', 2.82), ('num', 2.82)]),
                ('array', [('num', 2.82), ('num', 0.0), ('num', 2.82)]),
                ('array', [('num', 2.82), ('num', 2.82), ('num', 0.0)])]),
              292),
             ('assign',
              'nacl',
              ('call',
               'Atoms',
               [('var', 'nacl_numbers'),
                ('var', 'nacl_positions'),
                ('var', 'nacl_masses'),
                ('var', 'nacl_tags'),
                ('var', 'nacl_momenta'),
                ('var', 'nacl_magmoms'),
                ('var', 'nacl_charges'),
                ('var', 'nacl_cell')]),
              297),
             ('expr',
              ('method_call',
               ('var', 'nacl'),
               'count_species',
               [('num', 11.0)]),
              0),
             ('expr',
              ('method_call',
               ('var', 'nacl'),
               'count_species',
               [('num', 17.0)]),
              0),
             ('expr', ('method_call', ('var', 'nacl'), 'total_charge', []), 0),
             ('expr',
              ('method_call',
               ('var', 'nacl'),
               'distance',
               [('num', 0.0), ('num', 1.0)]),
              0),
             ('expr', ('method_call', ('var', 'nacl'), 'volume', []), 0)]}
