EXPECTED = {'functions': {'flat_index': {'params': [('k', 'ℕ')],
                              'return_type': ('tensor', [('k', 'invariant')]),
                              'body': ('call', 'arange', [('var', 'k')]),
                              'has_loop': False,
                              'statements': []},
               'axis_index': {'params': [('ms',
                                          ('tensor', [('k', 'invariant')])),
                                         ('axis_stride', 'ℕ'),
                                         ('axis_length', 'ℕ')],
                              'return_type': ('tensor', [('k', 'invariant')]),
                              'body': ('call',
                                       'mod',
                                       [('call',
                                         'floor',
                                         [('div',
                                           ('var', 'ms'),
                                           ('var', 'axis_stride'))]),
                                        ('var', 'axis_length')]),
                              'has_loop': False,
                              'statements': []},
               'fold_freq': {'params': [('m',
                                         ('tensor', [('k', 'invariant')])),
                                        ('axis_length', 'ℕ')],
                             'return_type': ('tensor', [('k', 'invariant')]),
                             'body': ('sub',
                                      ('var', 'm'),
                                      ('mul',
                                       ('call',
                                        'gt',
                                        [('var', 'm'),
                                         ('div',
                                          ('var', 'axis_length'),
                                          ('num', 2))]),
                                       ('var', 'axis_length'))),
                             'has_loop': False,
                             'statements': []},
               'cell_volume': {'params': [('a', 'ℝ')],
                               'return_type': 'ℝ',
                               'body': ('mul',
                                        ('mul', ('var', 'a'), ('var', 'a')),
                                        ('var', 'a')),
                               'has_loop': False,
                               'statements': []},
               'sample_coord': {'params': [('m',
                                            ('tensor', [('k', 'invariant')])),
                                           ('a', 'ℝ'),
                                           ('s', 'ℕ')],
                                'return_type': ('tensor',
                                                [('k', 'invariant')]),
                                'body': ('mul',
                                         ('var', 'm'),
                                         ('div', ('var', 'a'), ('var', 's'))),
                                'has_loop': False,
                                'statements': []},
               'recip_scale': {'params': [('a', 'ℝ')],
                               'return_type': 'ℝ',
                               'body': ('div',
                                        ('mul', ('num', 2), ('var', 'π')),
                                        ('var', 'a')),
                               'has_loop': False,
                               'statements': []},
               'g_squared': {'params': [('n1',
                                         ('tensor', [('k', 'invariant')])),
                                        ('n2',
                                         ('tensor', [('k', 'invariant')])),
                                        ('n3',
                                         ('tensor', [('k', 'invariant')])),
                                        ('c', 'ℝ')],
                             'return_type': ('tensor', [('k', 'invariant')]),
                             'body': ('mul',
                                      ('mul', ('var', 'c'), ('var', 'c')),
                                      ('add',
                                       ('add',
                                        ('mul', ('var', 'n1'), ('var', 'n1')),
                                        ('mul', ('var', 'n2'), ('var', 'n2'))),
                                       ('mul', ('var', 'n3'), ('var', 'n3')))),
                             'has_loop': False,
                             'statements': []},
               'active_mask': {'params': [('G2',
                                           ('tensor', [('k', 'invariant')])),
                                          ('ecut', 'ℝ')],
                               'return_type': ('tensor', [('k', 'invariant')]),
                               'body': ('call',
                                        'le',
                                        [('var', 'G2'),
                                         ('mul',
                                          ('num', 2),
                                          ('var', 'ecut'))]),
                               'has_loop': False,
                               'statements': []},
               'active_subset': {'params': [('G2',
                                             ('tensor', [('k', 'invariant')])),
                                            ('active',
                                             ('tensor',
                                              [('k', 'invariant')]))],
                                 'return_type': ('tensor',
                                                 [('p', 'invariant')]),
                                 'body': ('call',
                                          'mask_select',
                                          [('var', 'G2'), ('var', 'active')]),
                                 'has_loop': False,
                                 'statements': []},
               'structure_factor': {'params': [('n1',
                                                ('tensor',
                                                 [('k', 'invariant')])),
                                               ('n2',
                                                ('tensor',
                                                 [('k', 'invariant')])),
                                               ('n3',
                                                ('tensor',
                                                 [('k', 'invariant')])),
                                               ('c', 'ℝ'),
                                               ('px', 'ℝ'),
                                               ('py', 'ℝ'),
                                               ('pz', 'ℝ')],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'body': ('call',
                                             'exp',
                                             [('mul',
                                               ('neg', ('imaginary',)),
                                               ('var', 'phase'))]),
                                    'has_loop': False,
                                    'statements': [('body_decl',
                                                    'phase',
                                                    ('tensor',
                                                     [('k', 'invariant')]),
                                                    ('mul',
                                                     ('var', 'c'),
                                                     ('add',
                                                      ('add',
                                                       ('mul',
                                                        ('var', 'n1'),
                                                        ('var', 'px')),
                                                       ('mul',
                                                        ('var', 'n2'),
                                                        ('var', 'py'))),
                                                      ('mul',
                                                       ('var', 'n3'),
                                                       ('var', 'pz')))))]}},
 'classes': {'Atoms': {'class_params': [('a', 'ℝ'),
                                        ('ecut', 'ℝ'),
                                        ('s1', 'ℕ'),
                                        ('s2', 'ℕ'),
                                        ('s3', 'ℕ'),
                                        ('px', 'ℝ'),
                                        ('py', 'ℝ'),
                                        ('pz', 'ℝ'),
                                        ('Natoms', 'ℕ'),
                                        ('Nstate', 'ℕ'),
                                        ('Z_nuc',
                                         ('tensor',
                                          [('Natoms', 'invariant')])),
                                        ('f',
                                         ('tensor',
                                          [('Nstate', 'invariant')]))],
                       'fields': [],
                       'methods': [{'name': 'volume',
                                    'params': [],
                                    'return_type': 'ℝ',
                                    'statements': [],
                                    'body': ('call',
                                             'cell_volume',
                                             [('field_access',
                                               ('var', 'this'),
                                               'a')])},
                                   {'name': 'freq_x',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [('body_decl',
                                                    'ms',
                                                    ('tensor',
                                                     [('k', 'invariant')]),
                                                    ('call',
                                                     'flat_index',
                                                     [('mul',
                                                       ('mul',
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         's1'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         's2')),
                                                       ('field_access',
                                                        ('var', 'this'),
                                                        's3'))]))],
                                    'body': ('call',
                                             'fold_freq',
                                             [('call',
                                               'axis_index',
                                               [('var', 'ms'),
                                                ('mul',
                                                 ('field_access',
                                                  ('var', 'this'),
                                                  's3'),
                                                 ('field_access',
                                                  ('var', 'this'),
                                                  's2')),
                                                ('field_access',
                                                 ('var', 'this'),
                                                 's1')]),
                                              ('field_access',
                                               ('var', 'this'),
                                               's1')])},
                                   {'name': 'freq_y',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [('body_decl',
                                                    'ms',
                                                    ('tensor',
                                                     [('k', 'invariant')]),
                                                    ('call',
                                                     'flat_index',
                                                     [('mul',
                                                       ('mul',
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         's1'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         's2')),
                                                       ('field_access',
                                                        ('var', 'this'),
                                                        's3'))]))],
                                    'body': ('call',
                                             'fold_freq',
                                             [('call',
                                               'axis_index',
                                               [('var', 'ms'),
                                                ('field_access',
                                                 ('var', 'this'),
                                                 's3'),
                                                ('field_access',
                                                 ('var', 'this'),
                                                 's2')]),
                                              ('field_access',
                                               ('var', 'this'),
                                               's2')])},
                                   {'name': 'freq_z',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [('body_decl',
                                                    'ms',
                                                    ('tensor',
                                                     [('k', 'invariant')]),
                                                    ('call',
                                                     'flat_index',
                                                     [('mul',
                                                       ('mul',
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         's1'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         's2')),
                                                       ('field_access',
                                                        ('var', 'this'),
                                                        's3'))]))],
                                    'body': ('call',
                                             'fold_freq',
                                             [('call',
                                               'axis_index',
                                               [('var', 'ms'),
                                                ('num', 1),
                                                ('field_access',
                                                 ('var', 'this'),
                                                 's3')]),
                                              ('field_access',
                                               ('var', 'this'),
                                               's3')])},
                                   {'name': 'coord_x',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [('body_decl',
                                                    'ms',
                                                    ('tensor',
                                                     [('k', 'invariant')]),
                                                    ('call',
                                                     'flat_index',
                                                     [('mul',
                                                       ('mul',
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         's1'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         's2')),
                                                       ('field_access',
                                                        ('var', 'this'),
                                                        's3'))]))],
                                    'body': ('call',
                                             'sample_coord',
                                             [('call',
                                               'axis_index',
                                               [('var', 'ms'),
                                                ('mul',
                                                 ('field_access',
                                                  ('var', 'this'),
                                                  's3'),
                                                 ('field_access',
                                                  ('var', 'this'),
                                                  's2')),
                                                ('field_access',
                                                 ('var', 'this'),
                                                 's1')]),
                                              ('field_access',
                                               ('var', 'this'),
                                               'a'),
                                              ('field_access',
                                               ('var', 'this'),
                                               's1')])},
                                   {'name': 'coord_y',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [('body_decl',
                                                    'ms',
                                                    ('tensor',
                                                     [('k', 'invariant')]),
                                                    ('call',
                                                     'flat_index',
                                                     [('mul',
                                                       ('mul',
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         's1'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         's2')),
                                                       ('field_access',
                                                        ('var', 'this'),
                                                        's3'))]))],
                                    'body': ('call',
                                             'sample_coord',
                                             [('call',
                                               'axis_index',
                                               [('var', 'ms'),
                                                ('field_access',
                                                 ('var', 'this'),
                                                 's3'),
                                                ('field_access',
                                                 ('var', 'this'),
                                                 's2')]),
                                              ('field_access',
                                               ('var', 'this'),
                                               'a'),
                                              ('field_access',
                                               ('var', 'this'),
                                               's2')])},
                                   {'name': 'coord_z',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [('body_decl',
                                                    'ms',
                                                    ('tensor',
                                                     [('k', 'invariant')]),
                                                    ('call',
                                                     'flat_index',
                                                     [('mul',
                                                       ('mul',
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         's1'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         's2')),
                                                       ('field_access',
                                                        ('var', 'this'),
                                                        's3'))]))],
                                    'body': ('call',
                                             'sample_coord',
                                             [('call',
                                               'axis_index',
                                               [('var', 'ms'),
                                                ('num', 1),
                                                ('field_access',
                                                 ('var', 'this'),
                                                 's3')]),
                                              ('field_access',
                                               ('var', 'this'),
                                               'a'),
                                              ('field_access',
                                               ('var', 'this'),
                                               's3')])},
                                   {'name': 'gx',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [],
                                    'body': ('mul',
                                             ('call',
                                              'recip_scale',
                                              [('field_access',
                                                ('var', 'this'),
                                                'a')]),
                                             ('method_call',
                                              ('var', 'this'),
                                              'freq_x',
                                              []))},
                                   {'name': 'gy',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [],
                                    'body': ('mul',
                                             ('call',
                                              'recip_scale',
                                              [('field_access',
                                                ('var', 'this'),
                                                'a')]),
                                             ('method_call',
                                              ('var', 'this'),
                                              'freq_y',
                                              []))},
                                   {'name': 'gz',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [],
                                    'body': ('mul',
                                             ('call',
                                              'recip_scale',
                                              [('field_access',
                                                ('var', 'this'),
                                                'a')]),
                                             ('method_call',
                                              ('var', 'this'),
                                              'freq_z',
                                              []))},
                                   {'name': 'g2',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [],
                                    'body': ('call',
                                             'g_squared',
                                             [('method_call',
                                               ('var', 'this'),
                                               'freq_x',
                                               []),
                                              ('method_call',
                                               ('var', 'this'),
                                               'freq_y',
                                               []),
                                              ('method_call',
                                               ('var', 'this'),
                                               'freq_z',
                                               []),
                                              ('call',
                                               'recip_scale',
                                               [('field_access',
                                                 ('var', 'this'),
                                                 'a')])])},
                                   {'name': 'active',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [],
                                    'body': ('call',
                                             'active_mask',
                                             [('method_call',
                                               ('var', 'this'),
                                               'g2',
                                               []),
                                              ('field_access',
                                               ('var', 'this'),
                                               'ecut')])},
                                   {'name': 'g2c',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('p', 'invariant')]),
                                    'statements': [],
                                    'body': ('call',
                                             'active_subset',
                                             [('method_call',
                                               ('var', 'this'),
                                               'g2',
                                               []),
                                              ('method_call',
                                               ('var', 'this'),
                                               'active',
                                               [])])},
                                   {'name': 'sf',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [],
                                    'body': ('call',
                                             'structure_factor',
                                             [('method_call',
                                               ('var', 'this'),
                                               'freq_x',
                                               []),
                                              ('method_call',
                                               ('var', 'this'),
                                               'freq_y',
                                               []),
                                              ('method_call',
                                               ('var', 'this'),
                                               'freq_z',
                                               []),
                                              ('call',
                                               'recip_scale',
                                               [('field_access',
                                                 ('var', 'this'),
                                                 'a')]),
                                              ('field_access',
                                               ('var', 'this'),
                                               'px'),
                                              ('field_access',
                                               ('var', 'this'),
                                               'py'),
                                              ('field_access',
                                               ('var', 'this'),
                                               'pz')])}]}},
 'program': [('assign', 'π', ('num', 3.141592653589793), 28),
             ('func_def', 'flat_index'),
             ('func_def', 'axis_index'),
             ('func_def', 'fold_freq'),
             ('func_def', 'cell_volume'),
             ('func_def', 'sample_coord'),
             ('func_def', 'recip_scale'),
             ('func_def', 'g_squared'),
             ('func_def', 'active_mask'),
             ('func_def', 'active_subset'),
             ('func_def', 'structure_factor'),
             ('class_def', 'Atoms'),
             ('decl', 'a', 'ℝ', ('num', 16.0), 146),
             ('decl', 'ecut', 'ℝ', ('num', 16.0), 147),
             ('decl', 's', 'ℕ', ('num', 60), 148),
             ('decl', 'px', 'ℝ', ('num', 0.0), 151),
             ('decl', 'py', 'ℝ', ('num', 0.0), 152),
             ('decl', 'pz', 'ℝ', ('num', 0.0), 153),
             ('decl', 'Natoms', 'ℕ', ('num', 1), 155),
             ('decl', 'Nstate', 'ℕ', ('num', 1), 156),
             ('decl',
              'Z_nuc',
              ('tensor', [(1, 'invariant')]),
              ('array', [('num', 1.0)]),
              158),
             ('decl',
              'f',
              ('tensor', [(1, 'invariant')]),
              ('array', [('num', 1.0)]),
              159),
             ('decl',
              'H_atom',
              ('struct_type', 'Atoms'),
              ('call',
               'Atoms',
               [('var', 'a'),
                ('var', 'ecut'),
                ('var', 's'),
                ('var', 's'),
                ('var', 's'),
                ('var', 'px'),
                ('var', 'py'),
                ('var', 'pz'),
                ('var', 'Natoms'),
                ('var', 'Nstate'),
                ('var', 'Z_nuc'),
                ('var', 'f')]),
              161),
             ('expr', ('method_call', ('var', 'H_atom'), 'volume', []), 0),
             ('decl',
              'fx',
              ('tensor', [('k', 'invariant')]),
              ('method_call', ('var', 'H_atom'), 'freq_x', []),
              167),
             ('decl',
              'fy',
              ('tensor', [('k', 'invariant')]),
              ('method_call', ('var', 'H_atom'), 'freq_y', []),
              168),
             ('decl',
              'fz',
              ('tensor', [('k', 'invariant')]),
              ('method_call', ('var', 'H_atom'), 'freq_z', []),
              169),
             ('decl',
              'x',
              ('tensor', [('k', 'invariant')]),
              ('method_call', ('var', 'H_atom'), 'coord_x', []),
              172),
             ('decl',
              'y',
              ('tensor', [('k', 'invariant')]),
              ('method_call', ('var', 'H_atom'), 'coord_y', []),
              173),
             ('decl',
              'z',
              ('tensor', [('k', 'invariant')]),
              ('method_call', ('var', 'H_atom'), 'coord_z', []),
              174),
             ('decl',
              'gx',
              ('tensor', [('k', 'invariant')]),
              ('method_call', ('var', 'H_atom'), 'gx', []),
              177),
             ('decl',
              'gy',
              ('tensor', [('k', 'invariant')]),
              ('method_call', ('var', 'H_atom'), 'gy', []),
              178),
             ('decl',
              'gz',
              ('tensor', [('k', 'invariant')]),
              ('method_call', ('var', 'H_atom'), 'gz', []),
              179),
             ('decl',
              'G2',
              ('tensor', [('k', 'invariant')]),
              ('method_call', ('var', 'H_atom'), 'g2', []),
              182),
             ('decl',
              'active',
              ('tensor', [('k', 'invariant')]),
              ('method_call', ('var', 'H_atom'), 'active', []),
              183),
             ('decl',
              'G2c',
              ('tensor', [('p', 'invariant')]),
              ('method_call', ('var', 'H_atom'), 'g2c', []),
              184),
             ('expr', ('call', 'len', [('var', 'G2c')]), 0),
             ('decl',
              'Sf',
              ('tensor', [('k', 'invariant')]),
              ('method_call', ('var', 'H_atom'), 'sf', []),
              189),
             ('expr', ('index', 'Sf', ('num', 0)), 0),
             ('decl',
              'He_atom',
              ('struct_type', 'Atoms'),
              ('call',
               'Atoms',
               [('num', 16.0),
                ('num', 16.0),
                ('num', 60),
                ('num', 60),
                ('num', 60),
                ('num', 0.0),
                ('num', 0.0),
                ('num', 0.0),
                ('num', 1),
                ('num', 1),
                ('array', [('num', 2.0)]),
                ('array', [('num', 2.0)])]),
              193),
             ('expr',
              ('call',
               'len',
               [('method_call', ('var', 'He_atom'), 'g2c', [])]),
              0)]}
