EXPECTED = {'functions': {'op_O': {'params': [('W', ('tensor', [('k', 'invariant')])),
                                   ('Ω', 'ℝ')],
                        'return_type': ('tensor', [('k', 'invariant')]),
                        'body': ('mul', ('var', 'Ω'), ('var', 'W')),
                        'has_loop': False,
                        'statements': []},
               'op_O_mat': {'params': [('W',
                                        ('tensor',
                                         [('m', 'invariant'),
                                          ('k', 'invariant')])),
                                       ('Ω', 'ℝ')],
                            'return_type': ('tensor',
                                            [('m', 'invariant'),
                                             ('k', 'invariant')]),
                            'body': ('mul', ('var', 'Ω'), ('var', 'W')),
                            'has_loop': False,
                            'statements': []},
               'op_L': {'params': [('W', ('tensor', [('p', 'invariant')])),
                                   ('G2c', ('tensor', [('p', 'invariant')])),
                                   ('Ω', 'ℝ')],
                        'return_type': ('tensor', [('p', 'invariant')]),
                        'body': ('mul',
                                 ('mul',
                                  ('neg', ('var', 'Ω')),
                                  ('var', 'G2c')),
                                 ('var', 'W')),
                        'has_loop': False,
                        'statements': []},
               'op_L_mat': {'params': [('W',
                                        ('tensor',
                                         [('m', 'invariant'),
                                          ('p', 'invariant')])),
                                       ('G2c',
                                        ('tensor', [('p', 'invariant')])),
                                       ('Ω', 'ℝ')],
                            'return_type': ('tensor',
                                            [('m', 'invariant'),
                                             ('p', 'invariant')]),
                            'body': ('var', 'out'),
                            'has_loop': False,
                            'statements': [('body_decl',
                                            'Ns',
                                            'ℝ',
                                            ('call', 'len', [('var', 'W')])),
                                           ('body_decl',
                                            'out',
                                            ('tensor',
                                             [('Ns', 'invariant'),
                                              ('p', 'invariant')]),
                                            ('for_expr',
                                             'i',
                                             ('var', 'Ns'),
                                             ('call',
                                              'op_L',
                                              [('index', 'W', ('imaginary',)),
                                               ('var', 'G2c'),
                                               ('var', 'Ω')])))]},
               'op_Linv': {'params': [('W', ('tensor', [('k', 'invariant')])),
                                      ('G2', ('tensor', [('k', 'invariant')])),
                                      ('Ω', 'ℝ')],
                           'return_type': ('tensor', [('k', 'invariant')]),
                           'body': ('mul',
                                    ('div',
                                     ('div', ('var', 'W'), ('var', 'safe_G2')),
                                     ('neg', ('var', 'Ω'))),
                                    ('var', 'nonzero')),
                           'has_loop': False,
                           'statements': [('body_decl',
                                           'nonzero',
                                           ('tensor', [('k', 'invariant')]),
                                           ('mul',
                                            ('call',
                                             'gt',
                                             [('var', 'G2'), ('num', 0.0)]),
                                            ('num', 1.0))),
                                          ('body_decl',
                                           'safe_G2',
                                           ('tensor', [('k', 'invariant')]),
                                           ('add',
                                            ('var', 'G2'),
                                            ('sub',
                                             ('num', 1.0),
                                             ('var', 'nonzero'))))]},
               'op_Linv_mat': {'params': [('W',
                                           ('tensor',
                                            [('m', 'invariant'),
                                             ('k', 'invariant')])),
                                          ('G2',
                                           ('tensor', [('k', 'invariant')])),
                                          ('Ω', 'ℝ')],
                               'return_type': ('tensor',
                                               [('m', 'invariant'),
                                                ('k', 'invariant')]),
                               'body': ('var', 'out'),
                               'has_loop': False,
                               'statements': [('body_decl',
                                               'Ns',
                                               'ℝ',
                                               ('call',
                                                'len',
                                                [('var', 'W')])),
                                              ('body_decl',
                                               'out',
                                               ('tensor',
                                                [('Ns', 'invariant'),
                                                 ('k', 'invariant')]),
                                               ('for_expr',
                                                'i',
                                                ('var', 'Ns'),
                                                ('call',
                                                 'op_Linv',
                                                 [('index',
                                                   'W',
                                                   ('imaginary',)),
                                                  ('var', 'G2'),
                                                  ('var', 'Ω')])))]},
               'op_J': {'params': [('W', ('tensor', [('k', 'invariant')])),
                                   ('s1', 'ℕ'),
                                   ('s2', 'ℕ'),
                                   ('s3', 'ℕ')],
                        'return_type': ('tensor', [('k', 'invariant')]),
                        'body': ('div',
                                 ('call',
                                  'reshape',
                                  [('var', 'spec'), ('var', 'n')]),
                                 ('var', 'n')),
                        'has_loop': False,
                        'statements': [('body_decl',
                                        'n',
                                        'ℕ',
                                        ('mul',
                                         ('mul', ('var', 's1'), ('var', 's2')),
                                         ('var', 's3'))),
                                       ('body_decl',
                                        'cube',
                                        ('tensor',
                                         [('s1', 'invariant'),
                                          ('s2', 'invariant'),
                                          ('s3', 'invariant')]),
                                        ('call',
                                         'reshape',
                                         [('var', 'W'),
                                          ('var', 's1'),
                                          ('var', 's2'),
                                          ('var', 's3')])),
                                       ('body_decl',
                                        'spec',
                                        ('tensor',
                                         [('s1', 'invariant'),
                                          ('s2', 'invariant'),
                                          ('s3', 'invariant')]),
                                        ('call', 'fftn', [('var', 'cube')]))]},
               'op_J_mat': {'params': [('W',
                                        ('tensor',
                                         [('m', 'invariant'),
                                          ('k', 'invariant')])),
                                       ('s1', 'ℕ'),
                                       ('s2', 'ℕ'),
                                       ('s3', 'ℕ')],
                            'return_type': ('tensor',
                                            [('m', 'invariant'),
                                             ('k', 'invariant')]),
                            'body': ('var', 'out'),
                            'has_loop': False,
                            'statements': [('body_decl',
                                            'Ns',
                                            'ℝ',
                                            ('call', 'len', [('var', 'W')])),
                                           ('body_decl',
                                            'out',
                                            ('tensor',
                                             [('Ns', 'invariant'),
                                              ('k', 'invariant')]),
                                            ('for_expr',
                                             'i',
                                             ('var', 'Ns'),
                                             ('call',
                                              'op_J',
                                              [('index', 'W', ('imaginary',)),
                                               ('var', 's1'),
                                               ('var', 's2'),
                                               ('var', 's3')])))]},
               'op_I': {'params': [('W', ('tensor', [('k', 'invariant')])),
                                   ('s1', 'ℕ'),
                                   ('s2', 'ℕ'),
                                   ('s3', 'ℕ')],
                        'return_type': ('tensor', [('k', 'invariant')]),
                        'body': ('mul',
                                 ('call',
                                  'reshape',
                                  [('var', 'field'), ('var', 'n')]),
                                 ('var', 'n')),
                        'has_loop': False,
                        'statements': [('body_decl',
                                        'n',
                                        'ℕ',
                                        ('mul',
                                         ('mul', ('var', 's1'), ('var', 's2')),
                                         ('var', 's3'))),
                                       ('body_decl',
                                        'cube',
                                        ('tensor',
                                         [('s1', 'invariant'),
                                          ('s2', 'invariant'),
                                          ('s3', 'invariant')]),
                                        ('call',
                                         'reshape',
                                         [('var', 'W'),
                                          ('var', 's1'),
                                          ('var', 's2'),
                                          ('var', 's3')])),
                                       ('body_decl',
                                        'field',
                                        ('tensor',
                                         [('s1', 'invariant'),
                                          ('s2', 'invariant'),
                                          ('s3', 'invariant')]),
                                        ('call',
                                         'ifftn',
                                         [('var', 'cube')]))]},
               'op_I_mat': {'params': [('W',
                                        ('tensor',
                                         [('m', 'invariant'),
                                          ('k', 'invariant')])),
                                       ('s1', 'ℕ'),
                                       ('s2', 'ℕ'),
                                       ('s3', 'ℕ')],
                            'return_type': ('tensor',
                                            [('m', 'invariant'),
                                             ('k', 'invariant')]),
                            'body': ('var', 'out'),
                            'has_loop': False,
                            'statements': [('body_decl',
                                            'Ns',
                                            'ℝ',
                                            ('call', 'len', [('var', 'W')])),
                                           ('body_decl',
                                            'out',
                                            ('tensor',
                                             [('Ns', 'invariant'),
                                              ('k', 'invariant')]),
                                            ('for_expr',
                                             'i',
                                             ('var', 'Ns'),
                                             ('call',
                                              'op_I',
                                              [('index', 'W', ('imaginary',)),
                                               ('var', 's1'),
                                               ('var', 's2'),
                                               ('var', 's3')])))]},
               'op_Idag': {'params': [('W', ('tensor', [('k', 'invariant')])),
                                      ('active',
                                       ('tensor', [('k', 'invariant')])),
                                      ('s1', 'ℕ'),
                                      ('s2', 'ℕ'),
                                      ('s3', 'ℕ')],
                           'return_type': ('tensor', [('p', 'invariant')]),
                           'body': ('mul',
                                    ('call',
                                     'mask_select',
                                     [('var', 'F'), ('var', 'active')]),
                                    ('var', 'n')),
                           'has_loop': False,
                           'statements': [('body_decl',
                                           'n',
                                           'ℕ',
                                           ('mul',
                                            ('mul',
                                             ('var', 's1'),
                                             ('var', 's2')),
                                            ('var', 's3'))),
                                          ('body_decl',
                                           'F',
                                           ('tensor', [('k', 'invariant')]),
                                           ('call',
                                            'op_J',
                                            [('var', 'W'),
                                             ('var', 's1'),
                                             ('var', 's2'),
                                             ('var', 's3')]))]},
               'op_Idag_mat': {'params': [('W',
                                           ('tensor',
                                            [('m', 'invariant'),
                                             ('k', 'invariant')])),
                                          ('active',
                                           ('tensor', [('k', 'invariant')])),
                                          ('s1', 'ℕ'),
                                          ('s2', 'ℕ'),
                                          ('s3', 'ℕ')],
                               'return_type': ('tensor',
                                               [('m', 'invariant'),
                                                ('p', 'invariant')]),
                               'body': ('var', 'out'),
                               'has_loop': False,
                               'statements': [('body_decl',
                                               'Ns',
                                               'ℝ',
                                               ('call',
                                                'len',
                                                [('var', 'W')])),
                                              ('body_decl',
                                               'out',
                                               ('tensor',
                                                [('Ns', 'invariant'),
                                                 ('p', 'invariant')]),
                                               ('for_expr',
                                                'i',
                                                ('var', 'Ns'),
                                                ('call',
                                                 'op_Idag',
                                                 [('index',
                                                   'W',
                                                   ('imaginary',)),
                                                  ('var', 'active'),
                                                  ('var', 's1'),
                                                  ('var', 's2'),
                                                  ('var', 's3')])))]},
               'op_Jdag': {'params': [('W', ('tensor', [('k', 'invariant')])),
                                      ('s1', 'ℕ'),
                                      ('s2', 'ℕ'),
                                      ('s3', 'ℕ')],
                           'return_type': ('tensor', [('k', 'invariant')]),
                           'body': ('div',
                                    ('call',
                                     'op_I',
                                     [('var', 'W'),
                                      ('var', 's1'),
                                      ('var', 's2'),
                                      ('var', 's3')]),
                                    ('var', 'n')),
                           'has_loop': False,
                           'statements': [('body_decl',
                                           'n',
                                           'ℕ',
                                           ('mul',
                                            ('mul',
                                             ('var', 's1'),
                                             ('var', 's2')),
                                            ('var', 's3')))]},
               'op_Jdag_mat': {'params': [('W',
                                           ('tensor',
                                            [('m', 'invariant'),
                                             ('k', 'invariant')])),
                                          ('s1', 'ℕ'),
                                          ('s2', 'ℕ'),
                                          ('s3', 'ℕ')],
                               'return_type': ('tensor',
                                               [('m', 'invariant'),
                                                ('k', 'invariant')]),
                               'body': ('div',
                                        ('call',
                                         'op_I_mat',
                                         [('var', 'W'),
                                          ('var', 's1'),
                                          ('var', 's2'),
                                          ('var', 's3')]),
                                        ('var', 'n')),
                               'has_loop': False,
                               'statements': [('body_decl',
                                               'n',
                                               'ℕ',
                                               ('mul',
                                                ('mul',
                                                 ('var', 's1'),
                                                 ('var', 's2')),
                                                ('var', 's3')))]}},
 'classes': {},
 'program': [('func_def', 'op_O'),
             ('func_def', 'op_O_mat'),
             ('func_def', 'op_L'),
             ('func_def', 'op_L_mat'),
             ('func_def', 'op_Linv'),
             ('func_def', 'op_Linv_mat'),
             ('func_def', 'op_J'),
             ('func_def', 'op_J_mat'),
             ('func_def', 'op_I'),
             ('func_def', 'op_I_mat'),
             ('func_def', 'op_Idag'),
             ('func_def', 'op_Idag_mat'),
             ('func_def', 'op_Jdag'),
             ('func_def', 'op_Jdag_mat')]}
