EXPECTED = {'functions': {'mask_embed': {'params': [('values',
                                          ('tensor', [('p', 'invariant')])),
                                         ('active',
                                          ('tensor', [('k', 'invariant')])),
                                         ('n', 'ℕ')],
                              'return_type': ('tensor', [('k', 'invariant')]),
                              'body': ('call',
                                       'masked_scatter',
                                       [('var', 'out'),
                                        ('var', 'active'),
                                        ('var', 'values')]),
                              'has_loop': False,
                              'statements': [('body_decl',
                                              'out',
                                              ('tensor', [('k', 'invariant')]),
                                              ('mul',
                                               ('mul',
                                                ('num', 0.0),
                                                ('call',
                                                 'arange',
                                                 [('var', 'n')])),
                                               ('add',
                                                ('num', 1.0),
                                                ('complex', 0j))))]},
               'orth': {'params': [('atoms', ('struct_type', 'Atoms')),
                                   ('W', ('tensor', [('p', 'invariant')]))],
                        'return_type': ('tensor', [('p', 'invariant')]),
                        'body': ('div', ('var', 'W'), ('var', 'norm')),
                        'has_loop': False,
                        'statements': [('body_decl',
                                        'norm',
                                        'ℝ',
                                        ('call',
                                         'sqrt',
                                         [('mul',
                                           ('method_call',
                                            ('var', 'atoms'),
                                            'volume',
                                            []),
                                           ('call',
                                            'sum',
                                            [('pow',
                                              ('call', 'abs', [('var', 'W')]),
                                              ('num', 2.0))]))]))]},
               'get_n_total': {'params': [('atoms', ('struct_type', 'Atoms')),
                                          ('Y',
                                           ('tensor', [('p', 'invariant')]))],
                               'return_type': ('tensor', [('k', 'invariant')]),
                               'body': ('mul',
                                        ('var', 'f0'),
                                        ('pow',
                                         ('call', 'abs', [('var', 'Yrs')]),
                                         ('num', 2.0))),
                               'has_loop': False,
                               'statements': [('body_decl',
                                               'n_full',
                                               'ℕ',
                                               ('mul',
                                                ('mul',
                                                 ('field_access',
                                                  ('var', 'atoms'),
                                                  's1'),
                                                 ('field_access',
                                                  ('var', 'atoms'),
                                                  's2')),
                                                ('field_access',
                                                 ('var', 'atoms'),
                                                 's3'))),
                                              ('body_decl',
                                               'Y_full',
                                               ('tensor',
                                                [('k', 'invariant')]),
                                               ('call',
                                                'mask_embed',
                                                [('var', 'Y'),
                                                 ('method_call',
                                                  ('var', 'atoms'),
                                                  'active',
                                                  []),
                                                 ('var', 'n_full')])),
                                              ('body_decl',
                                               'Yrs',
                                               ('tensor',
                                                [('k', 'invariant')]),
                                               ('call',
                                                'op_I',
                                                [('var', 'atoms'),
                                                 ('var', 'Y_full')])),
                                              ('body_decl',
                                               'f0',
                                               'ℝ',
                                               ('chain_index',
                                                ('field_access',
                                                 ('var', 'atoms'),
                                                 'f'),
                                                ('num', 0)))]},
               'get_phi': {'params': [('atoms', ('struct_type', 'Atoms')),
                                      ('n', ('tensor', [('k', 'invariant')]))],
                           'return_type': ('tensor', [('k', 'invariant')]),
                           'body': ('mul',
                                    ('mul',
                                     ('neg', ('num', 4.0)),
                                     ('var', 'π')),
                                    ('call',
                                     'op_Linv',
                                     [('var', 'atoms'),
                                      ('call',
                                       'op_O',
                                       [('var', 'atoms'),
                                        ('var', 'n_recip')])])),
                           'has_loop': False,
                           'statements': [('body_decl',
                                           'n_c',
                                           ('tensor', [('k', 'invariant')]),
                                           ('mul',
                                            ('var', 'n'),
                                            ('add',
                                             ('num', 1.0),
                                             ('complex', 0j)))),
                                          ('body_decl',
                                           'n_recip',
                                           ('tensor', [('k', 'invariant')]),
                                           ('call',
                                            'op_J',
                                            [('var', 'atoms'),
                                             ('var', 'n_c')]))]},
               'flat_index': {'params': [('k', 'ℕ')],
                              'return_type': ('tensor', [('k', 'invariant')]),
                              'body': ('call', 'arange', [('var', 'k')]),
                              'has_loop': False,
                              'statements': []},
               'axis_index': {'params': [('ms',
                                          ('tensor', [('k', 'invariant')])),
                                         ('axis_stride', 'ℕ'),
                                         ('axis_length', 'ℕ')],
                              'return_type': ('tensor', [('k', 'invariant')]),
                              'body': ('call',
                                       'mod',
                                       [('call',
                                         'floor',
                                         [('div',
                                           ('var', 'ms'),
                                           ('var', 'axis_stride'))]),
                                        ('var', 'axis_length')]),
                              'has_loop': False,
                              'statements': []},
               'fold_freq': {'params': [('m',
                                         ('tensor', [('k', 'invariant')])),
                                        ('axis_length', 'ℕ')],
                             'return_type': ('tensor', [('k', 'invariant')]),
                             'body': ('sub',
                                      ('var', 'm'),
                                      ('mul',
                                       ('call',
                                        'gt',
                                        [('var', 'm'),
                                         ('div',
                                          ('var', 'axis_length'),
                                          ('num', 2))]),
                                       ('var', 'axis_length'))),
                             'has_loop': False,
                             'statements': []},
               'cell_volume': {'params': [('a', 'ℝ')],
                               'return_type': 'ℝ',
                               'body': ('mul',
                                        ('mul', ('var', 'a'), ('var', 'a')),
                                        ('var', 'a')),
                               'has_loop': False,
                               'statements': []},
               'sample_coord': {'params': [('m',
                                            ('tensor', [('k', 'invariant')])),
                                           ('a', 'ℝ'),
                                           ('s', 'ℕ')],
                                'return_type': ('tensor',
                                                [('k', 'invariant')]),
                                'body': ('mul',
                                         ('var', 'm'),
                                         ('div', ('var', 'a'), ('var', 's'))),
                                'has_loop': False,
                                'statements': []},
               'recip_scale': {'params': [('a', 'ℝ')],
                               'return_type': 'ℝ',
                               'body': ('div',
                                        ('mul', ('num', 2), ('var', 'π')),
                                        ('var', 'a')),
                               'has_loop': False,
                               'statements': []},
               'g_squared': {'params': [('n1',
                                         ('tensor', [('k', 'invariant')])),
                                        ('n2',
                                         ('tensor', [('k', 'invariant')])),
                                        ('n3',
                                         ('tensor', [('k', 'invariant')])),
                                        ('c', 'ℝ')],
                             'return_type': ('tensor', [('k', 'invariant')]),
                             'body': ('mul',
                                      ('mul', ('var', 'c'), ('var', 'c')),
                                      ('add',
                                       ('add',
                                        ('mul', ('var', 'n1'), ('var', 'n1')),
                                        ('mul', ('var', 'n2'), ('var', 'n2'))),
                                       ('mul', ('var', 'n3'), ('var', 'n3')))),
                             'has_loop': False,
                             'statements': []},
               'active_mask': {'params': [('G2',
                                           ('tensor', [('k', 'invariant')])),
                                          ('ecut', 'ℝ')],
                               'return_type': ('tensor', [('k', 'invariant')]),
                               'body': ('call',
                                        'le',
                                        [('var', 'G2'),
                                         ('mul',
                                          ('num', 2),
                                          ('var', 'ecut'))]),
                               'has_loop': False,
                               'statements': []},
               'active_subset': {'params': [('G2',
                                             ('tensor', [('k', 'invariant')])),
                                            ('active',
                                             ('tensor',
                                              [('k', 'invariant')]))],
                                 'return_type': ('tensor',
                                                 [('p', 'invariant')]),
                                 'body': ('call',
                                          'mask_select',
                                          [('var', 'G2'), ('var', 'active')]),
                                 'has_loop': False,
                                 'statements': []},
               'structure_factor': {'params': [('n1',
                                                ('tensor',
                                                 [('k', 'invariant')])),
                                               ('n2',
                                                ('tensor',
                                                 [('k', 'invariant')])),
                                               ('n3',
                                                ('tensor',
                                                 [('k', 'invariant')])),
                                               ('c', 'ℝ'),
                                               ('px', 'ℝ'),
                                               ('py', 'ℝ'),
                                               ('pz', 'ℝ')],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'body': ('call',
                                             'exp',
                                             [('mul',
                                               ('neg', ('imaginary',)),
                                               ('var', 'phase'))]),
                                    'has_loop': False,
                                    'statements': [('body_decl',
                                                    'phase',
                                                    ('tensor',
                                                     [('k', 'invariant')]),
                                                    ('mul',
                                                     ('var', 'c'),
                                                     ('add',
                                                      ('add',
                                                       ('mul',
                                                        ('var', 'n1'),
                                                        ('var', 'px')),
                                                       ('mul',
                                                        ('var', 'n2'),
                                                        ('var', 'py'))),
                                                      ('mul',
                                                       ('var', 'n3'),
                                                       ('var', 'pz')))))]},
               'op_I': {'params': [('atoms', ('struct_type', 'Atoms')),
                                   ('W', ('tensor', [('k', 'invariant')]))],
                        'return_type': ('tensor', [('k', 'invariant')]),
                        'body': ('mul',
                                 ('call',
                                  'reshape',
                                  [('var', 'real_grid'), ('var', 'Ngrid')]),
                                 ('var', 'Ngrid')),
                        'has_loop': False,
                        'statements': [('body_decl',
                                        's1',
                                        'ℕ',
                                        ('field_access',
                                         ('var', 'atoms'),
                                         's1')),
                                       ('body_decl',
                                        's2',
                                        'ℕ',
                                        ('field_access',
                                         ('var', 'atoms'),
                                         's2')),
                                       ('body_decl',
                                        's3',
                                        'ℕ',
                                        ('field_access',
                                         ('var', 'atoms'),
                                         's3')),
                                       ('body_decl',
                                        'Ngrid',
                                        'ℕ',
                                        ('mul',
                                         ('mul', ('var', 's1'), ('var', 's2')),
                                         ('var', 's3'))),
                                       ('body_decl',
                                        'active',
                                        ('tensor', [('k', 'invariant')]),
                                        ('method_call',
                                         ('var', 'atoms'),
                                         'active',
                                         [])),
                                       ('body_if_else',
                                        ('cond_eq',
                                         ('call', 'len', [('var', 'W')]),
                                         ('call', 'len', [('var', 'active')])),
                                        [('body_decl',
                                          'reciprocal_grid',
                                          ('tensor', [('k', 'invariant')]),
                                          ('var', 'W'))],
                                        [('body_decl',
                                          'reciprocal_grid',
                                          ('tensor', [('k', 'invariant')]),
                                          ('call',
                                           'mask_embed',
                                           [('var', 'W'),
                                            ('var', 'active'),
                                            ('var', 'Ngrid')]))]),
                                       ('body_decl',
                                        'reciprocal_grid3d',
                                        ('tensor',
                                         [('s1', 'invariant'),
                                          ('s2', 'invariant'),
                                          ('s3', 'invariant')]),
                                        ('call',
                                         'reshape',
                                         [('var', 'reciprocal_grid'),
                                          ('var', 's1'),
                                          ('var', 's2'),
                                          ('var', 's3')])),
                                       ('body_decl',
                                        'real_grid',
                                        ('tensor',
                                         [('s1', 'invariant'),
                                          ('s2', 'invariant'),
                                          ('s3', 'invariant')]),
                                        ('call',
                                         'ifftn',
                                         [('var', 'reciprocal_grid3d')]))]},
               'op_J': {'params': [('atoms', ('struct_type', 'Atoms')),
                                   ('W', ('tensor', [('k', 'invariant')]))],
                        'return_type': ('tensor', [('k', 'invariant')]),
                        'body': ('div',
                                 ('call',
                                  'reshape',
                                  [('var', 'reciprocal_grid'),
                                   ('var', 'Ngrid')]),
                                 ('var', 'Ngrid')),
                        'has_loop': False,
                        'statements': [('body_decl',
                                        's1',
                                        'ℕ',
                                        ('field_access',
                                         ('var', 'atoms'),
                                         's1')),
                                       ('body_decl',
                                        's2',
                                        'ℕ',
                                        ('field_access',
                                         ('var', 'atoms'),
                                         's2')),
                                       ('body_decl',
                                        's3',
                                        'ℕ',
                                        ('field_access',
                                         ('var', 'atoms'),
                                         's3')),
                                       ('body_decl',
                                        'Ngrid',
                                        'ℕ',
                                        ('mul',
                                         ('mul', ('var', 's1'), ('var', 's2')),
                                         ('var', 's3'))),
                                       ('body_decl',
                                        'real_grid',
                                        ('tensor',
                                         [('s1', 'invariant'),
                                          ('s2', 'invariant'),
                                          ('s3', 'invariant')]),
                                        ('call',
                                         'reshape',
                                         [('var', 'W'),
                                          ('var', 's1'),
                                          ('var', 's2'),
                                          ('var', 's3')])),
                                       ('body_decl',
                                        'reciprocal_grid',
                                        ('tensor',
                                         [('s1', 'invariant'),
                                          ('s2', 'invariant'),
                                          ('s3', 'invariant')]),
                                        ('call',
                                         'fftn',
                                         [('var', 'real_grid')]))]},
               'op_O': {'params': [('atoms', ('struct_type', 'Atoms')),
                                   ('W', ('tensor', [('k', 'invariant')]))],
                        'return_type': ('tensor', [('k', 'invariant')]),
                        'body': ('mul',
                                 ('method_call',
                                  ('var', 'atoms'),
                                  'volume',
                                  []),
                                 ('var', 'W')),
                        'has_loop': False,
                        'statements': []},
               'op_Linv': {'params': [('atoms', ('struct_type', 'Atoms')),
                                      ('W', ('tensor', [('k', 'invariant')]))],
                           'return_type': ('tensor', [('k', 'invariant')]),
                           'body': ('mul',
                                    ('div',
                                     ('div', ('var', 'W'), ('var', 'safe_G2')),
                                     ('neg',
                                      ('method_call',
                                       ('var', 'atoms'),
                                       'volume',
                                       []))),
                                    ('var', 'nonzero')),
                           'has_loop': False,
                           'statements': [('body_decl',
                                           'G2',
                                           ('tensor', [('k', 'invariant')]),
                                           ('method_call',
                                            ('var', 'atoms'),
                                            'g2',
                                            [])),
                                          ('body_decl',
                                           'nonzero',
                                           ('tensor', [('k', 'invariant')]),
                                           ('mul',
                                            ('call',
                                             'gt',
                                             [('var', 'G2'), ('num', 0.0)]),
                                            ('num', 1.0))),
                                          ('body_decl',
                                           'safe_G2',
                                           ('tensor', [('k', 'invariant')]),
                                           ('add',
                                            ('var', 'G2'),
                                            ('sub',
                                             ('num', 1.0),
                                             ('var', 'nonzero'))))]}},
 'classes': {'Atoms': {'class_params': [('a', 'ℝ'),
                                        ('ecut', 'ℝ'),
                                        ('s1', 'ℕ'),
                                        ('s2', 'ℕ'),
                                        ('s3', 'ℕ'),
                                        ('Natoms', 'ℕ'),
                                        ('px',
                                         ('tensor',
                                          [('Natoms', 'invariant')])),
                                        ('py',
                                         ('tensor',
                                          [('Natoms', 'invariant')])),
                                        ('pz',
                                         ('tensor',
                                          [('Natoms', 'invariant')])),
                                        ('Nstate', 'ℕ'),
                                        ('Z_nuc',
                                         ('tensor',
                                          [('Natoms', 'invariant')])),
                                        ('f',
                                         ('tensor',
                                          [('Nstate', 'invariant')]))],
                       'fields': [],
                       'methods': [{'name': 'volume',
                                    'params': [],
                                    'return_type': 'ℝ',
                                    'statements': [],
                                    'body': ('call',
                                             'cell_volume',
                                             [('field_access',
                                               ('var', 'this'),
                                               'a')])},
                                   {'name': 'freq_x',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [('body_decl',
                                                    'ms',
                                                    ('tensor',
                                                     [('k', 'invariant')]),
                                                    ('call',
                                                     'flat_index',
                                                     [('mul',
                                                       ('mul',
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         's1'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         's2')),
                                                       ('field_access',
                                                        ('var', 'this'),
                                                        's3'))]))],
                                    'body': ('call',
                                             'fold_freq',
                                             [('call',
                                               'axis_index',
                                               [('var', 'ms'),
                                                ('mul',
                                                 ('field_access',
                                                  ('var', 'this'),
                                                  's3'),
                                                 ('field_access',
                                                  ('var', 'this'),
                                                  's2')),
                                                ('field_access',
                                                 ('var', 'this'),
                                                 's1')]),
                                              ('field_access',
                                               ('var', 'this'),
                                               's1')])},
                                   {'name': 'freq_y',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [('body_decl',
                                                    'ms',
                                                    ('tensor',
                                                     [('k', 'invariant')]),
                                                    ('call',
                                                     'flat_index',
                                                     [('mul',
                                                       ('mul',
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         's1'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         's2')),
                                                       ('field_access',
                                                        ('var', 'this'),
                                                        's3'))]))],
                                    'body': ('call',
                                             'fold_freq',
                                             [('call',
                                               'axis_index',
                                               [('var', 'ms'),
                                                ('field_access',
                                                 ('var', 'this'),
                                                 's3'),
                                                ('field_access',
                                                 ('var', 'this'),
                                                 's2')]),
                                              ('field_access',
                                               ('var', 'this'),
                                               's2')])},
                                   {'name': 'freq_z',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [('body_decl',
                                                    'ms',
                                                    ('tensor',
                                                     [('k', 'invariant')]),
                                                    ('call',
                                                     'flat_index',
                                                     [('mul',
                                                       ('mul',
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         's1'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         's2')),
                                                       ('field_access',
                                                        ('var', 'this'),
                                                        's3'))]))],
                                    'body': ('call',
                                             'fold_freq',
                                             [('call',
                                               'axis_index',
                                               [('var', 'ms'),
                                                ('num', 1),
                                                ('field_access',
                                                 ('var', 'this'),
                                                 's3')]),
                                              ('field_access',
                                               ('var', 'this'),
                                               's3')])},
                                   {'name': 'coord_x',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [('body_decl',
                                                    'ms',
                                                    ('tensor',
                                                     [('k', 'invariant')]),
                                                    ('call',
                                                     'flat_index',
                                                     [('mul',
                                                       ('mul',
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         's1'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         's2')),
                                                       ('field_access',
                                                        ('var', 'this'),
                                                        's3'))]))],
                                    'body': ('call',
                                             'sample_coord',
                                             [('call',
                                               'axis_index',
                                               [('var', 'ms'),
                                                ('mul',
                                                 ('field_access',
                                                  ('var', 'this'),
                                                  's3'),
                                                 ('field_access',
                                                  ('var', 'this'),
                                                  's2')),
                                                ('field_access',
                                                 ('var', 'this'),
                                                 's1')]),
                                              ('field_access',
                                               ('var', 'this'),
                                               'a'),
                                              ('field_access',
                                               ('var', 'this'),
                                               's1')])},
                                   {'name': 'coord_y',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [('body_decl',
                                                    'ms',
                                                    ('tensor',
                                                     [('k', 'invariant')]),
                                                    ('call',
                                                     'flat_index',
                                                     [('mul',
                                                       ('mul',
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         's1'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         's2')),
                                                       ('field_access',
                                                        ('var', 'this'),
                                                        's3'))]))],
                                    'body': ('call',
                                             'sample_coord',
                                             [('call',
                                               'axis_index',
                                               [('var', 'ms'),
                                                ('field_access',
                                                 ('var', 'this'),
                                                 's3'),
                                                ('field_access',
                                                 ('var', 'this'),
                                                 's2')]),
                                              ('field_access',
                                               ('var', 'this'),
                                               'a'),
                                              ('field_access',
                                               ('var', 'this'),
                                               's2')])},
                                   {'name': 'coord_z',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [('body_decl',
                                                    'ms',
                                                    ('tensor',
                                                     [('k', 'invariant')]),
                                                    ('call',
                                                     'flat_index',
                                                     [('mul',
                                                       ('mul',
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         's1'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         's2')),
                                                       ('field_access',
                                                        ('var', 'this'),
                                                        's3'))]))],
                                    'body': ('call',
                                             'sample_coord',
                                             [('call',
                                               'axis_index',
                                               [('var', 'ms'),
                                                ('num', 1),
                                                ('field_access',
                                                 ('var', 'this'),
                                                 's3')]),
                                              ('field_access',
                                               ('var', 'this'),
                                               'a'),
                                              ('field_access',
                                               ('var', 'this'),
                                               's3')])},
                                   {'name': 'gx',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [],
                                    'body': ('mul',
                                             ('call',
                                              'recip_scale',
                                              [('field_access',
                                                ('var', 'this'),
                                                'a')]),
                                             ('method_call',
                                              ('var', 'this'),
                                              'freq_x',
                                              []))},
                                   {'name': 'gy',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [],
                                    'body': ('mul',
                                             ('call',
                                              'recip_scale',
                                              [('field_access',
                                                ('var', 'this'),
                                                'a')]),
                                             ('method_call',
                                              ('var', 'this'),
                                              'freq_y',
                                              []))},
                                   {'name': 'gz',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [],
                                    'body': ('mul',
                                             ('call',
                                              'recip_scale',
                                              [('field_access',
                                                ('var', 'this'),
                                                'a')]),
                                             ('method_call',
                                              ('var', 'this'),
                                              'freq_z',
                                              []))},
                                   {'name': 'g2',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [],
                                    'body': ('call',
                                             'g_squared',
                                             [('method_call',
                                               ('var', 'this'),
                                               'freq_x',
                                               []),
                                              ('method_call',
                                               ('var', 'this'),
                                               'freq_y',
                                               []),
                                              ('method_call',
                                               ('var', 'this'),
                                               'freq_z',
                                               []),
                                              ('call',
                                               'recip_scale',
                                               [('field_access',
                                                 ('var', 'this'),
                                                 'a')])])},
                                   {'name': 'active',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [],
                                    'body': ('call',
                                             'active_mask',
                                             [('method_call',
                                               ('var', 'this'),
                                               'g2',
                                               []),
                                              ('field_access',
                                               ('var', 'this'),
                                               'ecut')])},
                                   {'name': 'g2c',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('p', 'invariant')]),
                                    'statements': [],
                                    'body': ('call',
                                             'active_subset',
                                             [('method_call',
                                               ('var', 'this'),
                                               'g2',
                                               []),
                                              ('method_call',
                                               ('var', 'this'),
                                               'active',
                                               [])])},
                                   {'name': 'sf',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [('body_decl',
                                                    'n1',
                                                    ('tensor',
                                                     [('k', 'invariant')]),
                                                    ('method_call',
                                                     ('var', 'this'),
                                                     'freq_x',
                                                     [])),
                                                   ('body_decl',
                                                    'n2',
                                                    ('tensor',
                                                     [('k', 'invariant')]),
                                                    ('method_call',
                                                     ('var', 'this'),
                                                     'freq_y',
                                                     [])),
                                                   ('body_decl',
                                                    'n3',
                                                    ('tensor',
                                                     [('k', 'invariant')]),
                                                    ('method_call',
                                                     ('var', 'this'),
                                                     'freq_z',
                                                     [])),
                                                   ('body_decl',
                                                    'c',
                                                    'ℝ',
                                                    ('call',
                                                     'recip_scale',
                                                     [('field_access',
                                                       ('var', 'this'),
                                                       'a')])),
                                                   ('body_decl',
                                                    'natoms',
                                                    'ℕ',
                                                    ('field_access',
                                                     ('var', 'this'),
                                                     'Natoms')),
                                                   ('body_decl',
                                                    'Sf',
                                                    ('tensor',
                                                     [('k', 'invariant')]),
                                                    ('mul',
                                                     ('call',
                                                      'structure_factor',
                                                      [('var', 'n1'),
                                                       ('var', 'n2'),
                                                       ('var', 'n3'),
                                                       ('var', 'c'),
                                                       ('chain_index',
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'px'),
                                                        ('num', 0)),
                                                       ('chain_index',
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'py'),
                                                        ('num', 0)),
                                                       ('chain_index',
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'pz'),
                                                        ('num', 0))]),
                                                     ('num', 0.0))),
                                                   ('body_for_range',
                                                    'a',
                                                    ('num', 0),
                                                    ('var', 'natoms'),
                                                    [('loop_assign',
                                                      'Sf',
                                                      ('add',
                                                       ('var', 'Sf'),
                                                       ('call',
                                                        'structure_factor',
                                                        [('var', 'n1'),
                                                         ('var', 'n2'),
                                                         ('var', 'n3'),
                                                         ('var', 'c'),
                                                         ('chain_index',
                                                          ('field_access',
                                                           ('var', 'this'),
                                                           'px'),
                                                          ('var', 'a')),
                                                         ('chain_index',
                                                          ('field_access',
                                                           ('var', 'this'),
                                                           'py'),
                                                          ('var', 'a')),
                                                         ('chain_index',
                                                          ('field_access',
                                                           ('var', 'this'),
                                                           'pz'),
                                                          ('var', 'a'))])))])],
                                    'body': ('var', 'Sf')}]}},
 'program': [('class_def', 'Atoms'),
             ('func_def', 'flat_index'),
             ('func_def', 'axis_index'),
             ('func_def', 'fold_freq'),
             ('func_def', 'cell_volume'),
             ('func_def', 'sample_coord'),
             ('func_def', 'recip_scale'),
             ('func_def', 'g_squared'),
             ('func_def', 'active_mask'),
             ('func_def', 'active_subset'),
             ('func_def', 'structure_factor'),
             ('func_def', 'op_I'),
             ('func_def', 'op_J'),
             ('func_def', 'op_O'),
             ('func_def', 'op_Linv'),
             ('func_def', 'mask_embed'),
             ('assign', 'π', ('num', 3.141592653589793), 22),
             ('func_def', 'orth'),
             ('func_def', 'get_n_total'),
             ('func_def', 'get_phi'),
             ('decl', 'a', 'ℝ', ('num', 16.0), 85),
             ('decl', 'ecut', 'ℝ', ('num', 16.0), 86),
             ('decl', 's', 'ℕ', ('num', 60), 87),
             ('decl', 'Natoms', 'ℕ', ('num', 1), 89),
             ('decl', 'Nstate', 'ℕ', ('num', 1), 90),
             ('decl',
              'px',
              ('tensor', [(1, 'invariant')]),
              ('array', [('num', 0.0)]),
              92),
             ('decl',
              'py',
              ('tensor', [(1, 'invariant')]),
              ('array', [('num', 0.0)]),
              93),
             ('decl',
              'pz',
              ('tensor', [(1, 'invariant')]),
              ('array', [('num', 0.0)]),
              94),
             ('decl',
              'Z_nuc',
              ('tensor', [(1, 'invariant')]),
              ('array', [('num', 1.0)]),
              96),
             ('decl',
              'f',
              ('tensor', [(1, 'invariant')]),
              ('array', [('num', 1.0)]),
              97),
             ('decl',
              'H_atom',
              ('struct_type', 'Atoms'),
              ('call',
               'Atoms',
               [('var', 'a'),
                ('var', 'ecut'),
                ('var', 's'),
                ('var', 's'),
                ('var', 's'),
                ('var', 'Natoms'),
                ('var', 'px'),
                ('var', 'py'),
                ('var', 'pz'),
                ('var', 'Nstate'),
                ('var', 'Z_nuc'),
                ('var', 'f')]),
              99),
             ('decl',
              'W0',
              ('tensor', [('p', 'invariant')]),
              ('mul',
               ('call',
                'exp',
                [('mul',
                  ('neg', ('num', 0.5)),
                  ('method_call', ('var', 'H_atom'), 'g2c', []))]),
               ('add', ('num', 1.0), ('complex', 0j))),
              104),
             ('decl',
              'Y0',
              ('tensor', [('p', 'invariant')]),
              ('call', 'orth', [('var', 'H_atom'), ('var', 'W0')]),
              107),
             ('decl',
              'norm_check',
              'ℝ',
              ('mul',
               ('method_call', ('var', 'H_atom'), 'volume', []),
               ('call',
                'sum',
                [('pow', ('call', 'abs', [('var', 'Y0')]), ('num', 2.0))])),
              108),
             ('expr', ('var', 'norm_check'), 0),
             ('decl',
              'n0',
              ('tensor', [('k', 'invariant')]),
              ('call', 'get_n_total', [('var', 'H_atom'), ('var', 'Y0')]),
              113),
             ('decl',
              'dV',
              'ℝ',
              ('div',
               ('method_call', ('var', 'H_atom'), 'volume', []),
               ('mul', ('mul', ('var', 's'), ('var', 's')), ('var', 's'))),
              114),
             ('decl',
              'density_check',
              'ℝ',
              ('mul', ('call', 'sum', [('var', 'n0')]), ('var', 'dV')),
              115),
             ('expr', ('var', 'density_check'), 0),
             ('decl',
              'phi0',
              ('tensor', [('k', 'invariant')]),
              ('call', 'get_phi', [('var', 'H_atom'), ('var', 'n0')]),
              119),
             ('expr', ('index', 'phi0', ('num', 0)), 0),
             ('expr', ('index', 'phi0', ('num', 1)), 0)]}
