EXPECTED = {'functions': {'coulomb': {'params': [('atoms', ('struct_type', 'Atoms'))],
                           'return_type': ('tensor', [('k', 'invariant')]),
                           'body': ('call',
                                    'op_J',
                                    [('var', 'atoms'),
                                     ('mul',
                                      ('var', 'Vcoul'),
                                      ('method_call',
                                       ('var', 'atoms'),
                                       'sf',
                                       []))]),
                           'has_loop': False,
                           'statements': [('body_decl',
                                           'G2',
                                           ('tensor', [('k', 'invariant')]),
                                           ('method_call',
                                            ('var', 'atoms'),
                                            'g2',
                                            [])),
                                          ('body_decl',
                                           'nonzero',
                                           ('tensor', [('k', 'invariant')]),
                                           ('mul',
                                            ('call',
                                             'gt',
                                             [('var', 'G2'), ('num', 0.0)]),
                                            ('num', 1.0))),
                                          ('body_decl',
                                           'safe_G2',
                                           ('tensor', [('k', 'invariant')]),
                                           ('add',
                                            ('var', 'G2'),
                                            ('sub',
                                             ('num', 1.0),
                                             ('var', 'nonzero')))),
                                          ('body_decl',
                                           'Vcoul',
                                           ('tensor', [('k', 'invariant')]),
                                           ('mul',
                                            ('div',
                                             ('mul',
                                              ('mul',
                                               ('neg', ('num', 4.0)),
                                               ('var', 'π')),
                                              ('chain_index',
                                               ('field_access',
                                                ('var', 'atoms'),
                                                'Z_nuc'),
                                               ('num', 0))),
                                             ('var', 'safe_G2')),
                                            ('var', 'nonzero')))]},
               'flat_index': {'params': [('k', 'ℕ')],
                              'return_type': ('tensor', [('k', 'invariant')]),
                              'body': ('call', 'arange', [('var', 'k')]),
                              'has_loop': False,
                              'statements': []},
               'axis_index': {'params': [('ms',
                                          ('tensor', [('k', 'invariant')])),
                                         ('axis_stride', 'ℕ'),
                                         ('axis_length', 'ℕ')],
                              'return_type': ('tensor', [('k', 'invariant')]),
                              'body': ('call',
                                       'mod',
                                       [('call',
                                         'floor',
                                         [('div',
                                           ('var', 'ms'),
                                           ('var', 'axis_stride'))]),
                                        ('var', 'axis_length')]),
                              'has_loop': False,
                              'statements': []},
               'fold_freq': {'params': [('m',
                                         ('tensor', [('k', 'invariant')])),
                                        ('axis_length', 'ℕ')],
                             'return_type': ('tensor', [('k', 'invariant')]),
                             'body': ('sub',
                                      ('var', 'm'),
                                      ('mul',
                                       ('call',
                                        'gt',
                                        [('var', 'm'),
                                         ('div',
                                          ('var', 'axis_length'),
                                          ('num', 2))]),
                                       ('var', 'axis_length'))),
                             'has_loop': False,
                             'statements': []},
               'cell_volume': {'params': [('a', 'ℝ')],
                               'return_type': 'ℝ',
                               'body': ('mul',
                                        ('mul', ('var', 'a'), ('var', 'a')),
                                        ('var', 'a')),
                               'has_loop': False,
                               'statements': []},
               'sample_coord': {'params': [('m',
                                            ('tensor', [('k', 'invariant')])),
                                           ('a', 'ℝ'),
                                           ('s', 'ℕ')],
                                'return_type': ('tensor',
                                                [('k', 'invariant')]),
                                'body': ('mul',
                                         ('var', 'm'),
                                         ('div', ('var', 'a'), ('var', 's'))),
                                'has_loop': False,
                                'statements': []},
               'recip_scale': {'params': [('a', 'ℝ')],
                               'return_type': 'ℝ',
                               'body': ('div',
                                        ('mul', ('num', 2), ('var', 'π')),
                                        ('var', 'a')),
                               'has_loop': False,
                               'statements': []},
               'g_squared': {'params': [('n1',
                                         ('tensor', [('k', 'invariant')])),
                                        ('n2',
                                         ('tensor', [('k', 'invariant')])),
                                        ('n3',
                                         ('tensor', [('k', 'invariant')])),
                                        ('c', 'ℝ')],
                             'return_type': ('tensor', [('k', 'invariant')]),
                             'body': ('mul',
                                      ('mul', ('var', 'c'), ('var', 'c')),
                                      ('add',
                                       ('add',
                                        ('mul', ('var', 'n1'), ('var', 'n1')),
                                        ('mul', ('var', 'n2'), ('var', 'n2'))),
                                       ('mul', ('var', 'n3'), ('var', 'n3')))),
                             'has_loop': False,
                             'statements': []},
               'active_mask': {'params': [('G2',
                                           ('tensor', [('k', 'invariant')])),
                                          ('ecut', 'ℝ')],
                               'return_type': ('tensor', [('k', 'invariant')]),
                               'body': ('call',
                                        'le',
                                        [('var', 'G2'),
                                         ('mul',
                                          ('num', 2),
                                          ('var', 'ecut'))]),
                               'has_loop': False,
                               'statements': []},
               'active_subset': {'params': [('G2',
                                             ('tensor', [('k', 'invariant')])),
                                            ('active',
                                             ('tensor',
                                              [('k', 'invariant')]))],
                                 'return_type': ('tensor',
                                                 [('p', 'invariant')]),
                                 'body': ('call',
                                          'mask_select',
                                          [('var', 'G2'), ('var', 'active')]),
                                 'has_loop': False,
                                 'statements': []},
               'structure_factor': {'params': [('n1',
                                                ('tensor',
                                                 [('k', 'invariant')])),
                                               ('n2',
                                                ('tensor',
                                                 [('k', 'invariant')])),
                                               ('n3',
                                                ('tensor',
                                                 [('k', 'invariant')])),
                                               ('c', 'ℝ'),
                                               ('px', 'ℝ'),
                                               ('py', 'ℝ'),
                                               ('pz', 'ℝ')],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'body': ('call',
                                             'exp',
                                             [('mul',
                                               ('neg', ('imaginary',)),
                                               ('var', 'phase'))]),
                                    'has_loop': False,
                                    'statements': [('body_decl',
                                                    'phase',
                                                    ('tensor',
                                                     [('k', 'invariant')]),
                                                    ('mul',
                                                     ('var', 'c'),
                                                     ('add',
                                                      ('add',
                                                       ('mul',
                                                        ('var', 'n1'),
                                                        ('var', 'px')),
                                                       ('mul',
                                                        ('var', 'n2'),
                                                        ('var', 'py'))),
                                                      ('mul',
                                                       ('var', 'n3'),
                                                       ('var', 'pz')))))]},
               'op_J': {'params': [('atoms', ('struct_type', 'Atoms')),
                                   ('W', ('tensor', [('k', 'invariant')]))],
                        'return_type': ('tensor', [('k', 'invariant')]),
                        'body': ('div',
                                 ('call',
                                  'reshape',
                                  [('var', 'reciprocal_grid'),
                                   ('var', 'Ngrid')]),
                                 ('var', 'Ngrid')),
                        'has_loop': False,
                        'statements': [('body_decl',
                                        's1',
                                        'ℕ',
                                        ('field_access',
                                         ('var', 'atoms'),
                                         's1')),
                                       ('body_decl',
                                        's2',
                                        'ℕ',
                                        ('field_access',
                                         ('var', 'atoms'),
                                         's2')),
                                       ('body_decl',
                                        's3',
                                        'ℕ',
                                        ('field_access',
                                         ('var', 'atoms'),
                                         's3')),
                                       ('body_decl',
                                        'Ngrid',
                                        'ℕ',
                                        ('mul',
                                         ('mul', ('var', 's1'), ('var', 's2')),
                                         ('var', 's3'))),
                                       ('body_decl',
                                        'real_grid',
                                        ('tensor',
                                         [('s1', 'invariant'),
                                          ('s2', 'invariant'),
                                          ('s3', 'invariant')]),
                                        ('call',
                                         'reshape',
                                         [('var', 'W'),
                                          ('var', 's1'),
                                          ('var', 's2'),
                                          ('var', 's3')])),
                                       ('body_decl',
                                        'reciprocal_grid',
                                        ('tensor',
                                         [('s1', 'invariant'),
                                          ('s2', 'invariant'),
                                          ('s3', 'invariant')]),
                                        ('call',
                                         'fftn',
                                         [('var', 'real_grid')]))]}},
 'classes': {'Atoms': {'class_params': [('a', 'ℝ'),
                                        ('ecut', 'ℝ'),
                                        ('s1', 'ℕ'),
                                        ('s2', 'ℕ'),
                                        ('s3', 'ℕ'),
                                        ('px', 'ℝ'),
                                        ('py', 'ℝ'),
                                        ('pz', 'ℝ'),
                                        ('Natoms', 'ℕ'),
                                        ('Nstate', 'ℕ'),
                                        ('Z_nuc',
                                         ('tensor',
                                          [('Natoms', 'invariant')])),
                                        ('f',
                                         ('tensor',
                                          [('Nstate', 'invariant')]))],
                       'fields': [],
                       'methods': [{'name': 'volume',
                                    'params': [],
                                    'return_type': 'ℝ',
                                    'statements': [],
                                    'body': ('call',
                                             'cell_volume',
                                             [('field_access',
                                               ('var', 'this'),
                                               'a')])},
                                   {'name': 'freq_x',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [('body_decl',
                                                    'ms',
                                                    ('tensor',
                                                     [('k', 'invariant')]),
                                                    ('call',
                                                     'flat_index',
                                                     [('mul',
                                                       ('mul',
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         's1'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         's2')),
                                                       ('field_access',
                                                        ('var', 'this'),
                                                        's3'))]))],
                                    'body': ('call',
                                             'fold_freq',
                                             [('call',
                                               'axis_index',
                                               [('var', 'ms'),
                                                ('mul',
                                                 ('field_access',
                                                  ('var', 'this'),
                                                  's3'),
                                                 ('field_access',
                                                  ('var', 'this'),
                                                  's2')),
                                                ('field_access',
                                                 ('var', 'this'),
                                                 's1')]),
                                              ('field_access',
                                               ('var', 'this'),
                                               's1')])},
                                   {'name': 'freq_y',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [('body_decl',
                                                    'ms',
                                                    ('tensor',
                                                     [('k', 'invariant')]),
                                                    ('call',
                                                     'flat_index',
                                                     [('mul',
                                                       ('mul',
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         's1'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         's2')),
                                                       ('field_access',
                                                        ('var', 'this'),
                                                        's3'))]))],
                                    'body': ('call',
                                             'fold_freq',
                                             [('call',
                                               'axis_index',
                                               [('var', 'ms'),
                                                ('field_access',
                                                 ('var', 'this'),
                                                 's3'),
                                                ('field_access',
                                                 ('var', 'this'),
                                                 's2')]),
                                              ('field_access',
                                               ('var', 'this'),
                                               's2')])},
                                   {'name': 'freq_z',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [('body_decl',
                                                    'ms',
                                                    ('tensor',
                                                     [('k', 'invariant')]),
                                                    ('call',
                                                     'flat_index',
                                                     [('mul',
                                                       ('mul',
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         's1'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         's2')),
                                                       ('field_access',
                                                        ('var', 'this'),
                                                        's3'))]))],
                                    'body': ('call',
                                             'fold_freq',
                                             [('call',
                                               'axis_index',
                                               [('var', 'ms'),
                                                ('num', 1),
                                                ('field_access',
                                                 ('var', 'this'),
                                                 's3')]),
                                              ('field_access',
                                               ('var', 'this'),
                                               's3')])},
                                   {'name': 'coord_x',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [('body_decl',
                                                    'ms',
                                                    ('tensor',
                                                     [('k', 'invariant')]),
                                                    ('call',
                                                     'flat_index',
                                                     [('mul',
                                                       ('mul',
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         's1'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         's2')),
                                                       ('field_access',
                                                        ('var', 'this'),
                                                        's3'))]))],
                                    'body': ('call',
                                             'sample_coord',
                                             [('call',
                                               'axis_index',
                                               [('var', 'ms'),
                                                ('mul',
                                                 ('field_access',
                                                  ('var', 'this'),
                                                  's3'),
                                                 ('field_access',
                                                  ('var', 'this'),
                                                  's2')),
                                                ('field_access',
                                                 ('var', 'this'),
                                                 's1')]),
                                              ('field_access',
                                               ('var', 'this'),
                                               'a'),
                                              ('field_access',
                                               ('var', 'this'),
                                               's1')])},
                                   {'name': 'coord_y',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [('body_decl',
                                                    'ms',
                                                    ('tensor',
                                                     [('k', 'invariant')]),
                                                    ('call',
                                                     'flat_index',
                                                     [('mul',
                                                       ('mul',
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         's1'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         's2')),
                                                       ('field_access',
                                                        ('var', 'this'),
                                                        's3'))]))],
                                    'body': ('call',
                                             'sample_coord',
                                             [('call',
                                               'axis_index',
                                               [('var', 'ms'),
                                                ('field_access',
                                                 ('var', 'this'),
                                                 's3'),
                                                ('field_access',
                                                 ('var', 'this'),
                                                 's2')]),
                                              ('field_access',
                                               ('var', 'this'),
                                               'a'),
                                              ('field_access',
                                               ('var', 'this'),
                                               's2')])},
                                   {'name': 'coord_z',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [('body_decl',
                                                    'ms',
                                                    ('tensor',
                                                     [('k', 'invariant')]),
                                                    ('call',
                                                     'flat_index',
                                                     [('mul',
                                                       ('mul',
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         's1'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         's2')),
                                                       ('field_access',
                                                        ('var', 'this'),
                                                        's3'))]))],
                                    'body': ('call',
                                             'sample_coord',
                                             [('call',
                                               'axis_index',
                                               [('var', 'ms'),
                                                ('num', 1),
                                                ('field_access',
                                                 ('var', 'this'),
                                                 's3')]),
                                              ('field_access',
                                               ('var', 'this'),
                                               'a'),
                                              ('field_access',
                                               ('var', 'this'),
                                               's3')])},
                                   {'name': 'gx',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [],
                                    'body': ('mul',
                                             ('call',
                                              'recip_scale',
                                              [('field_access',
                                                ('var', 'this'),
                                                'a')]),
                                             ('method_call',
                                              ('var', 'this'),
                                              'freq_x',
                                              []))},
                                   {'name': 'gy',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [],
                                    'body': ('mul',
                                             ('call',
                                              'recip_scale',
                                              [('field_access',
                                                ('var', 'this'),
                                                'a')]),
                                             ('method_call',
                                              ('var', 'this'),
                                              'freq_y',
                                              []))},
                                   {'name': 'gz',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [],
                                    'body': ('mul',
                                             ('call',
                                              'recip_scale',
                                              [('field_access',
                                                ('var', 'this'),
                                                'a')]),
                                             ('method_call',
                                              ('var', 'this'),
                                              'freq_z',
                                              []))},
                                   {'name': 'g2',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [],
                                    'body': ('call',
                                             'g_squared',
                                             [('method_call',
                                               ('var', 'this'),
                                               'freq_x',
                                               []),
                                              ('method_call',
                                               ('var', 'this'),
                                               'freq_y',
                                               []),
                                              ('method_call',
                                               ('var', 'this'),
                                               'freq_z',
                                               []),
                                              ('call',
                                               'recip_scale',
                                               [('field_access',
                                                 ('var', 'this'),
                                                 'a')])])},
                                   {'name': 'active',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [],
                                    'body': ('call',
                                             'active_mask',
                                             [('method_call',
                                               ('var', 'this'),
                                               'g2',
                                               []),
                                              ('field_access',
                                               ('var', 'this'),
                                               'ecut')])},
                                   {'name': 'g2c',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('p', 'invariant')]),
                                    'statements': [],
                                    'body': ('call',
                                             'active_subset',
                                             [('method_call',
                                               ('var', 'this'),
                                               'g2',
                                               []),
                                              ('method_call',
                                               ('var', 'this'),
                                               'active',
                                               [])])},
                                   {'name': 'sf',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [],
                                    'body': ('call',
                                             'structure_factor',
                                             [('method_call',
                                               ('var', 'this'),
                                               'freq_x',
                                               []),
                                              ('method_call',
                                               ('var', 'this'),
                                               'freq_y',
                                               []),
                                              ('method_call',
                                               ('var', 'this'),
                                               'freq_z',
                                               []),
                                              ('call',
                                               'recip_scale',
                                               [('field_access',
                                                 ('var', 'this'),
                                                 'a')]),
                                              ('field_access',
                                               ('var', 'this'),
                                               'px'),
                                              ('field_access',
                                               ('var', 'this'),
                                               'py'),
                                              ('field_access',
                                               ('var', 'this'),
                                               'pz')])}]}},
 'program': [('class_def', 'Atoms'),
             ('func_def', 'flat_index'),
             ('func_def', 'axis_index'),
             ('func_def', 'fold_freq'),
             ('func_def', 'cell_volume'),
             ('func_def', 'sample_coord'),
             ('func_def', 'recip_scale'),
             ('func_def', 'g_squared'),
             ('func_def', 'active_mask'),
             ('func_def', 'active_subset'),
             ('func_def', 'structure_factor'),
             ('func_def', 'op_J'),
             ('assign', 'π', ('num', 3.141592653589793), 8),
             ('func_def', 'coulomb'),
             ('decl', 'a', 'ℝ', ('num', 16.0), 42),
             ('decl', 'ecut', 'ℝ', ('num', 16.0), 43),
             ('decl', 's', 'ℕ', ('num', 60), 44),
             ('decl', 'px', 'ℝ', ('num', 0.0), 47),
             ('decl', 'py', 'ℝ', ('num', 0.0), 48),
             ('decl', 'pz', 'ℝ', ('num', 0.0), 49),
             ('decl', 'Natoms', 'ℕ', ('num', 1), 51),
             ('decl', 'Nstate', 'ℕ', ('num', 1), 52),
             ('decl',
              'Z_nuc',
              ('tensor', [(1, 'invariant')]),
              ('array', [('num', 1.0)]),
              53),
             ('decl',
              'f',
              ('tensor', [(1, 'invariant')]),
              ('array', [('num', 1.0)]),
              54),
             ('decl',
              'H_atom',
              ('struct_type', 'Atoms'),
              ('call',
               'Atoms',
               [('var', 'a'),
                ('var', 'ecut'),
                ('var', 's'),
                ('var', 's'),
                ('var', 's'),
                ('var', 'px'),
                ('var', 'py'),
                ('var', 'pz'),
                ('var', 'Natoms'),
                ('var', 'Nstate'),
                ('var', 'Z_nuc'),
                ('var', 'f')]),
              56),
             ('decl',
              'Vext',
              ('tensor', [('k', 'invariant')]),
              ('call', 'coulomb', [('var', 'H_atom')]),
              59),
             ('expr', ('index', 'Vext', ('num', 0)), 0),
             ('expr', ('index', 'Vext', ('num', 1)), 0)]}
