EXPECTED = {'functions': {'lda_x': {'params': [('n', ('tensor', [('k', 'invariant')]))],
                         'return_type': ('tensor',
                                         [(2, 'invariant'),
                                          ('k', 'invariant')]),
                         'body': ('array', [('var', 'ex'), ('var', 'vx')]),
                         'has_loop': False,
                         'statements': [('body_decl',
                                         'cx',
                                         'ℝ',
                                         ('mul',
                                          ('div',
                                           ('neg', ('num', 3.0)),
                                           ('num', 4.0)),
                                          ('pow',
                                           ('div',
                                            ('num', 3.0),
                                            ('mul',
                                             ('num', 2.0),
                                             ('var', 'π'))),
                                           ('div',
                                            ('num', 2.0),
                                            ('num', 3.0))))),
                                        ('body_decl',
                                         'rs',
                                         ('tensor', [('k', 'invariant')]),
                                         ('pow',
                                          ('div',
                                           ('num', 3.0),
                                           ('mul',
                                            ('mul',
                                             ('num', 4.0),
                                             ('var', 'π')),
                                            ('var', 'n'))),
                                          ('div',
                                           ('num', 1.0),
                                           ('num', 3.0)))),
                                        ('body_decl',
                                         'ex',
                                         ('tensor', [('k', 'invariant')]),
                                         ('div',
                                          ('var', 'cx'),
                                          ('var', 'rs'))),
                                        ('body_decl',
                                         'vx',
                                         ('tensor', [('k', 'invariant')]),
                                         ('mul',
                                          ('div', ('num', 4.0), ('num', 3.0)),
                                          ('var', 'ex')))]},
               'lda_c_chachiyo': {'params': [('n',
                                              ('tensor',
                                               [('k', 'invariant')]))],
                                  'return_type': ('tensor',
                                                  [(2, 'invariant'),
                                                   ('k', 'invariant')]),
                                  'body': ('array',
                                           [('var', 'ec'), ('var', 'vc')]),
                                  'has_loop': False,
                                  'statements': [('body_decl',
                                                  'a',
                                                  'ℝ',
                                                  ('neg',
                                                   ('num', 0.01554535))),
                                                 ('body_decl',
                                                  'b',
                                                  'ℝ',
                                                  ('num', 20.4562557)),
                                                 ('body_decl',
                                                  'rs',
                                                  ('tensor',
                                                   [('k', 'invariant')]),
                                                  ('pow',
                                                   ('div',
                                                    ('num', 3.0),
                                                    ('mul',
                                                     ('mul',
                                                      ('num', 4.0),
                                                      ('var', 'π')),
                                                     ('var', 'n'))),
                                                   ('div',
                                                    ('num', 1.0),
                                                    ('num', 3.0)))),
                                                 ('body_decl',
                                                  'ec',
                                                  ('tensor',
                                                   [('k', 'invariant')]),
                                                  ('mul',
                                                   ('var', 'a'),
                                                   ('call',
                                                    'log',
                                                    [('add',
                                                      ('add',
                                                       ('num', 1.0),
                                                       ('div',
                                                        ('var', 'b'),
                                                        ('var', 'rs'))),
                                                      ('div',
                                                       ('var', 'b'),
                                                       ('pow',
                                                        ('var', 'rs'),
                                                        ('num', 2.0))))]))),
                                                 ('body_decl',
                                                  'vc',
                                                  ('tensor',
                                                   [('k', 'invariant')]),
                                                  ('add',
                                                   ('var', 'ec'),
                                                   ('div',
                                                    ('mul',
                                                     ('mul',
                                                      ('var', 'a'),
                                                      ('var', 'b')),
                                                     ('add',
                                                      ('num', 2.0),
                                                      ('var', 'rs'))),
                                                    ('mul',
                                                     ('num', 3.0),
                                                     ('add',
                                                      ('add',
                                                       ('var', 'b'),
                                                       ('mul',
                                                        ('var', 'b'),
                                                        ('var', 'rs'))),
                                                      ('pow',
                                                       ('var', 'rs'),
                                                       ('num', 2.0)))))))]}},
 'classes': {},
 'program': [('assign', 'π', ('num', 3.141592653589793), 9),
             ('func_def', 'lda_x'),
             ('func_def', 'lda_c_chachiyo'),
             ('decl', 'n0', 'ℝ', ('div', ('num', 1.0), ('num', 4096.0)), 66),
             ('decl',
              'n',
              ('tensor', [(4, 'invariant')]),
              ('array',
               [('var', 'n0'), ('var', 'n0'), ('var', 'n0'), ('var', 'n0')]),
              72),
             ('decl',
              'ex_vx',
              ('tensor', [(2, 'invariant'), (4, 'invariant')]),
              ('call', 'lda_x', [('var', 'n')]),
              75),
             ('decl',
              'ex',
              ('tensor', [(4, 'invariant')]),
              ('index', 'ex_vx', ('num', 0)),
              76),
             ('decl',
              'vx',
              ('tensor', [(4, 'invariant')]),
              ('index', 'ex_vx', ('num', 1)),
              77),
             ('expr', ('index', 'ex', ('num', 0)), 0),
             ('expr', ('index', 'vx', ('num', 0)), 0),
             ('expr', ('index', 'ex', ('num', 1)), 0),
             ('expr', ('index', 'vx', ('num', 1)), 0),
             ('decl',
              'ec_vc',
              ('tensor', [(2, 'invariant'), (4, 'invariant')]),
              ('call', 'lda_c_chachiyo', [('var', 'n')]),
              85),
             ('decl',
              'ec',
              ('tensor', [(4, 'invariant')]),
              ('index', 'ec_vc', ('num', 0)),
              86),
             ('decl',
              'vc',
              ('tensor', [(4, 'invariant')]),
              ('index', 'ec_vc', ('num', 1)),
              87),
             ('expr', ('index', 'ec', ('num', 0)), 0),
             ('expr', ('index', 'vc', ('num', 0)), 0),
             ('expr', ('index', 'ec', ('num', 1)), 0),
             ('expr', ('index', 'vc', ('num', 1)), 0),
             ('decl',
              'exc',
              ('tensor', [(4, 'invariant')]),
              ('add', ('var', 'ex'), ('var', 'ec')),
              95),
             ('decl',
              'vxc',
              ('tensor', [(4, 'invariant')]),
              ('add', ('var', 'vx'), ('var', 'vc')),
              96),
             ('expr', ('index', 'exc', ('num', 0)), 0),
             ('expr', ('index', 'vxc', ('num', 0)), 0)]}
