EXPECTED = {'functions': {'coulomb': {'params': [('atoms', ('struct_type', 'Atoms'))],
                           'return_type': ('tensor', [('k', 'invariant')]),
                           'body': ('call',
                                    'op_J',
                                    [('var', 'atoms'),
                                     ('mul',
                                      ('var', 'Vcoul'),
                                      ('method_call',
                                       ('var', 'atoms'),
                                       'sf',
                                       []))]),
                           'has_loop': False,
                           'statements': [('body_decl',
                                           'G2',
                                           ('tensor', [('k', 'invariant')]),
                                           ('method_call',
                                            ('var', 'atoms'),
                                            'g2',
                                            [])),
                                          ('body_decl',
                                           'nonzero',
                                           ('tensor', [('k', 'invariant')]),
                                           ('mul',
                                            ('call',
                                             'gt',
                                             [('var', 'G2'), ('num', 0.0)]),
                                            ('num', 1.0))),
                                          ('body_decl',
                                           'safe_G2',
                                           ('tensor', [('k', 'invariant')]),
                                           ('add',
                                            ('var', 'G2'),
                                            ('sub',
                                             ('num', 1.0),
                                             ('var', 'nonzero')))),
                                          ('body_decl',
                                           'Vcoul',
                                           ('tensor', [('k', 'invariant')]),
                                           ('mul',
                                            ('div',
                                             ('mul',
                                              ('mul',
                                               ('neg', ('num', 4.0)),
                                               ('var', 'π')),
                                              ('chain_index',
                                               ('field_access',
                                                ('var', 'atoms'),
                                                'Z_nuc'),
                                               ('num', 0))),
                                             ('var', 'safe_G2')),
                                            ('var', 'nonzero')))]},
               'op_J': {'params': [('atoms', ('struct_type', 'Atoms')),
                                   ('W', ('tensor', [('k', 'invariant')]))],
                        'return_type': ('tensor', [('k', 'invariant')]),
                        'body': ('div',
                                 ('call',
                                  'reshape',
                                  [('var', 'reciprocal_grid'),
                                   ('var', 'Ngrid')]),
                                 ('var', 'Ngrid')),
                        'has_loop': False,
                        'statements': [('body_decl',
                                        's1',
                                        'ℕ',
                                        ('field_access',
                                         ('var', 'atoms'),
                                         's1')),
                                       ('body_decl',
                                        's2',
                                        'ℕ',
                                        ('field_access',
                                         ('var', 'atoms'),
                                         's2')),
                                       ('body_decl',
                                        's3',
                                        'ℕ',
                                        ('field_access',
                                         ('var', 'atoms'),
                                         's3')),
                                       ('body_decl',
                                        'Ngrid',
                                        'ℕ',
                                        ('mul',
                                         ('mul', ('var', 's1'), ('var', 's2')),
                                         ('var', 's3'))),
                                       ('body_decl',
                                        'real_grid',
                                        ('tensor',
                                         [('s1', 'invariant'),
                                          ('s2', 'invariant'),
                                          ('s3', 'invariant')]),
                                        ('call',
                                         'reshape',
                                         [('var', 'W'),
                                          ('var', 's1'),
                                          ('var', 's2'),
                                          ('var', 's3')])),
                                       ('body_decl',
                                        'reciprocal_grid',
                                        ('tensor',
                                         [('s1', 'invariant'),
                                          ('s2', 'invariant'),
                                          ('s3', 'invariant')]),
                                        ('call',
                                         'fftn',
                                         [('var', 'real_grid')]))]}},
 'classes': {'Atoms': {'class_params': [('a', 'ℝ'),
                                        ('ecut', 'ℝ'),
                                        ('s1', 'ℕ'),
                                        ('s2', 'ℕ'),
                                        ('s3', 'ℕ'),
                                        ('Natoms', 'ℕ'),
                                        ('px',
                                         ('tensor',
                                          [('Natoms', 'invariant')])),
                                        ('py',
                                         ('tensor',
                                          [('Natoms', 'invariant')])),
                                        ('pz',
                                         ('tensor',
                                          [('Natoms', 'invariant')])),
                                        ('Nstate', 'ℕ'),
                                        ('Z_nuc',
                                         ('tensor',
                                          [('Natoms', 'invariant')])),
                                        ('f',
                                         ('tensor',
                                          [('Nstate', 'invariant')]))],
                       'fields': [],
                       'methods': [{'name': 'volume',
                                    'params': [],
                                    'return_type': 'ℝ',
                                    'statements': [],
                                    'body': ('mul',
                                             ('mul',
                                              ('field_access',
                                               ('var', 'this'),
                                               'a'),
                                              ('field_access',
                                               ('var', 'this'),
                                               'a')),
                                             ('field_access',
                                              ('var', 'this'),
                                              'a'))},
                                   {'name': 'flat_index',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [],
                                    'body': ('call',
                                             'arange',
                                             [('mul',
                                               ('mul',
                                                ('field_access',
                                                 ('var', 'this'),
                                                 's1'),
                                                ('field_access',
                                                 ('var', 'this'),
                                                 's2')),
                                               ('field_access',
                                                ('var', 'this'),
                                                's3'))])},
                                   {'name': 'm1',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [],
                                    'body': ('call',
                                             'mod',
                                             [('call',
                                               'floor',
                                               [('div',
                                                 ('method_call',
                                                  ('var', 'this'),
                                                  'flat_index',
                                                  []),
                                                 ('mul',
                                                  ('field_access',
                                                   ('var', 'this'),
                                                   's3'),
                                                  ('field_access',
                                                   ('var', 'this'),
                                                   's2')))]),
                                              ('field_access',
                                               ('var', 'this'),
                                               's1')])},
                                   {'name': 'm2',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [],
                                    'body': ('call',
                                             'mod',
                                             [('call',
                                               'floor',
                                               [('div',
                                                 ('method_call',
                                                  ('var', 'this'),
                                                  'flat_index',
                                                  []),
                                                 ('field_access',
                                                  ('var', 'this'),
                                                  's3'))]),
                                              ('field_access',
                                               ('var', 'this'),
                                               's2')])},
                                   {'name': 'm3',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [],
                                    'body': ('call',
                                             'mod',
                                             [('method_call',
                                               ('var', 'this'),
                                               'flat_index',
                                               []),
                                              ('field_access',
                                               ('var', 'this'),
                                               's3')])},
                                   {'name': 'fold_freq',
                                    'params': [('m',
                                                ('tensor',
                                                 [('k', 'invariant')])),
                                               ('axis_length', 'ℕ')],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [],
                                    'body': ('sub',
                                             ('var', 'm'),
                                             ('mul',
                                              ('call',
                                               'gt',
                                               [('var', 'm'),
                                                ('div',
                                                 ('var', 'axis_length'),
                                                 ('num', 2))]),
                                              ('var', 'axis_length')))},
                                   {'name': 'sample_coord',
                                    'params': [('m',
                                                ('tensor',
                                                 [('k', 'invariant')])),
                                               ('s', 'ℕ')],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [],
                                    'body': ('mul',
                                             ('var', 'm'),
                                             ('div',
                                              ('field_access',
                                               ('var', 'this'),
                                               'a'),
                                              ('var', 's')))},
                                   {'name': 'recip_scale',
                                    'params': [],
                                    'return_type': 'ℝ',
                                    'statements': [],
                                    'body': ('div',
                                             ('mul', ('num', 2), ('var', 'π')),
                                             ('field_access',
                                              ('var', 'this'),
                                              'a'))},
                                   {'name': 'structure_factor',
                                    'params': [('n1',
                                                ('tensor',
                                                 [('k', 'invariant')])),
                                               ('n2',
                                                ('tensor',
                                                 [('k', 'invariant')])),
                                               ('n3',
                                                ('tensor',
                                                 [('k', 'invariant')])),
                                               ('c', 'ℝ'),
                                               ('px', 'ℝ'),
                                               ('py', 'ℝ'),
                                               ('pz', 'ℝ')],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [('body_decl',
                                                    'phase',
                                                    ('tensor',
                                                     [('k', 'invariant')]),
                                                    ('mul',
                                                     ('var', 'c'),
                                                     ('add',
                                                      ('add',
                                                       ('mul',
                                                        ('var', 'n1'),
                                                        ('var', 'px')),
                                                       ('mul',
                                                        ('var', 'n2'),
                                                        ('var', 'py'))),
                                                      ('mul',
                                                       ('var', 'n3'),
                                                       ('var', 'pz')))))],
                                    'body': ('call',
                                             'exp',
                                             [('mul',
                                               ('neg', ('imaginary',)),
                                               ('var', 'phase'))])},
                                   {'name': 'freq_x',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [],
                                    'body': ('method_call',
                                             ('var', 'this'),
                                             'fold_freq',
                                             [('method_call',
                                               ('var', 'this'),
                                               'm1',
                                               []),
                                              ('field_access',
                                               ('var', 'this'),
                                               's1')])},
                                   {'name': 'freq_y',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [],
                                    'body': ('method_call',
                                             ('var', 'this'),
                                             'fold_freq',
                                             [('method_call',
                                               ('var', 'this'),
                                               'm2',
                                               []),
                                              ('field_access',
                                               ('var', 'this'),
                                               's2')])},
                                   {'name': 'freq_z',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [],
                                    'body': ('method_call',
                                             ('var', 'this'),
                                             'fold_freq',
                                             [('method_call',
                                               ('var', 'this'),
                                               'm3',
                                               []),
                                              ('field_access',
                                               ('var', 'this'),
                                               's3')])},
                                   {'name': 'coord_x',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [],
                                    'body': ('method_call',
                                             ('var', 'this'),
                                             'sample_coord',
                                             [('method_call',
                                               ('var', 'this'),
                                               'm1',
                                               []),
                                              ('field_access',
                                               ('var', 'this'),
                                               's1')])},
                                   {'name': 'coord_y',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [],
                                    'body': ('method_call',
                                             ('var', 'this'),
                                             'sample_coord',
                                             [('method_call',
                                               ('var', 'this'),
                                               'm2',
                                               []),
                                              ('field_access',
                                               ('var', 'this'),
                                               's2')])},
                                   {'name': 'coord_z',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [],
                                    'body': ('method_call',
                                             ('var', 'this'),
                                             'sample_coord',
                                             [('method_call',
                                               ('var', 'this'),
                                               'm3',
                                               []),
                                              ('field_access',
                                               ('var', 'this'),
                                               's3')])},
                                   {'name': 'gx',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [],
                                    'body': ('mul',
                                             ('method_call',
                                              ('var', 'this'),
                                              'recip_scale',
                                              []),
                                             ('method_call',
                                              ('var', 'this'),
                                              'freq_x',
                                              []))},
                                   {'name': 'gy',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [],
                                    'body': ('mul',
                                             ('method_call',
                                              ('var', 'this'),
                                              'recip_scale',
                                              []),
                                             ('method_call',
                                              ('var', 'this'),
                                              'freq_y',
                                              []))},
                                   {'name': 'gz',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [],
                                    'body': ('mul',
                                             ('method_call',
                                              ('var', 'this'),
                                              'recip_scale',
                                              []),
                                             ('method_call',
                                              ('var', 'this'),
                                              'freq_z',
                                              []))},
                                   {'name': 'g2',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [('body_decl',
                                                    'c',
                                                    'ℝ',
                                                    ('method_call',
                                                     ('var', 'this'),
                                                     'recip_scale',
                                                     [])),
                                                   ('body_decl',
                                                    'n1',
                                                    ('tensor',
                                                     [('k', 'invariant')]),
                                                    ('method_call',
                                                     ('var', 'this'),
                                                     'freq_x',
                                                     [])),
                                                   ('body_decl',
                                                    'n2',
                                                    ('tensor',
                                                     [('k', 'invariant')]),
                                                    ('method_call',
                                                     ('var', 'this'),
                                                     'freq_y',
                                                     [])),
                                                   ('body_decl',
                                                    'n3',
                                                    ('tensor',
                                                     [('k', 'invariant')]),
                                                    ('method_call',
                                                     ('var', 'this'),
                                                     'freq_z',
                                                     []))],
                                    'body': ('mul',
                                             ('mul',
                                              ('var', 'c'),
                                              ('var', 'c')),
                                             ('add',
                                              ('add',
                                               ('mul',
                                                ('var', 'n1'),
                                                ('var', 'n1')),
                                               ('mul',
                                                ('var', 'n2'),
                                                ('var', 'n2'))),
                                              ('mul',
                                               ('var', 'n3'),
                                               ('var', 'n3'))))},
                                   {'name': 'active',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [],
                                    'body': ('call',
                                             'le',
                                             [('method_call',
                                               ('var', 'this'),
                                               'g2',
                                               []),
                                              ('mul',
                                               ('num', 2),
                                               ('field_access',
                                                ('var', 'this'),
                                                'ecut'))])},
                                   {'name': 'g2c',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('p', 'invariant')]),
                                    'statements': [],
                                    'body': ('call',
                                             'mask_select',
                                             [('method_call',
                                               ('var', 'this'),
                                               'g2',
                                               []),
                                              ('method_call',
                                               ('var', 'this'),
                                               'active',
                                               [])])},
                                   {'name': 'sf',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [('body_decl',
                                                    'n1',
                                                    ('tensor',
                                                     [('k', 'invariant')]),
                                                    ('method_call',
                                                     ('var', 'this'),
                                                     'freq_x',
                                                     [])),
                                                   ('body_decl',
                                                    'n2',
                                                    ('tensor',
                                                     [('k', 'invariant')]),
                                                    ('method_call',
                                                     ('var', 'this'),
                                                     'freq_y',
                                                     [])),
                                                   ('body_decl',
                                                    'n3',
                                                    ('tensor',
                                                     [('k', 'invariant')]),
                                                    ('method_call',
                                                     ('var', 'this'),
                                                     'freq_z',
                                                     [])),
                                                   ('body_decl',
                                                    'c',
                                                    'ℝ',
                                                    ('method_call',
                                                     ('var', 'this'),
                                                     'recip_scale',
                                                     [])),
                                                   ('body_decl',
                                                    'natoms',
                                                    'ℕ',
                                                    ('field_access',
                                                     ('var', 'this'),
                                                     'Natoms')),
                                                   ('body_decl',
                                                    'Sf',
                                                    ('tensor',
                                                     [('k', 'invariant')]),
                                                    ('mul',
                                                     ('method_call',
                                                      ('var', 'this'),
                                                      'structure_factor',
                                                      [('var', 'n1'),
                                                       ('var', 'n2'),
                                                       ('var', 'n3'),
                                                       ('var', 'c'),
                                                       ('chain_index',
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'px'),
                                                        ('num', 0)),
                                                       ('chain_index',
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'py'),
                                                        ('num', 0)),
                                                       ('chain_index',
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'pz'),
                                                        ('num', 0))]),
                                                     ('num', 0.0))),
                                                   ('body_for_range',
                                                    'a',
                                                    ('num', 0),
                                                    ('var', 'natoms'),
                                                    [('loop_pluseq',
                                                      'Sf',
                                                      ('method_call',
                                                       ('var', 'this'),
                                                       'structure_factor',
                                                       [('var', 'n1'),
                                                        ('var', 'n2'),
                                                        ('var', 'n3'),
                                                        ('var', 'c'),
                                                        ('chain_index',
                                                         ('field_access',
                                                          ('var', 'this'),
                                                          'px'),
                                                         ('var', 'a')),
                                                        ('chain_index',
                                                         ('field_access',
                                                          ('var', 'this'),
                                                          'py'),
                                                         ('var', 'a')),
                                                        ('chain_index',
                                                         ('field_access',
                                                          ('var', 'this'),
                                                          'pz'),
                                                         ('var', 'a'))]))])],
                                    'body': ('var', 'Sf')}]}},
 'program': [('class_def', 'Atoms'),
             ('func_def', 'op_J'),
             ('decl', 'π', 'ℝ', ('num', 3.141592653589793), 8),
             ('func_def', 'coulomb'),
             ('decl', 'a', 'ℝ', ('num', 16.0), 42),
             ('decl', 'ecut', 'ℝ', ('num', 16.0), 43),
             ('decl', 's', 'ℕ', ('num', 60), 44),
             ('decl', 'Natoms', 'ℕ', ('num', 1), 47),
             ('decl', 'Nstate', 'ℕ', ('num', 1), 48),
             ('decl',
              'px',
              ('tensor', [(1, 'invariant')]),
              ('array', [('num', 0.0)]),
              50),
             ('decl',
              'py',
              ('tensor', [(1, 'invariant')]),
              ('array', [('num', 0.0)]),
              51),
             ('decl',
              'pz',
              ('tensor', [(1, 'invariant')]),
              ('array', [('num', 0.0)]),
              52),
             ('decl',
              'Z_nuc',
              ('tensor', [(1, 'invariant')]),
              ('array', [('num', 1.0)]),
              54),
             ('decl',
              'f',
              ('tensor', [(1, 'invariant')]),
              ('array', [('num', 1.0)]),
              55),
             ('decl',
              'H_atom',
              ('struct_type', 'Atoms'),
              ('call',
               'Atoms',
               [('var', 'a'),
                ('var', 'ecut'),
                ('var', 's'),
                ('var', 's'),
                ('var', 's'),
                ('var', 'Natoms'),
                ('var', 'px'),
                ('var', 'py'),
                ('var', 'pz'),
                ('var', 'Nstate'),
                ('var', 'Z_nuc'),
                ('var', 'f')]),
              57),
             ('decl',
              'Vext',
              ('tensor', [('k', 'invariant')]),
              ('call', 'coulomb', [('var', 'H_atom')]),
              60),
             ('expr', ('index', 'Vext', ('num', 0)), 0),
             ('expr', ('index', 'Vext', ('num', 1)), 0)]}
