EXPECTED = {'functions': {'lda_x': {'params': [('n',
                                     ('tensor',
                                      [('m', 'invariant'),
                                       ('k', 'invariant')]))],
                         'return_type': ('tensor',
                                         [(2, 'invariant'),
                                          ('m', 'invariant'),
                                          ('k', 'invariant')]),
                         'body': ('array', [('var', 'ex'), ('var', 'vx')]),
                         'has_loop': False,
                         'statements': [('body_decl',
                                         'cx',
                                         'ℝ',
                                         ('mul',
                                          ('div',
                                           ('neg', ('num', 3.0)),
                                           ('num', 4.0)),
                                          ('pow',
                                           ('div',
                                            ('num', 3.0),
                                            ('mul',
                                             ('num', 2.0),
                                             ('var', 'π'))),
                                           ('div',
                                            ('num', 2.0),
                                            ('num', 3.0))))),
                                        ('body_decl',
                                         'rs',
                                         ('tensor',
                                          [('m', 'invariant'),
                                           ('k', 'invariant')]),
                                         ('pow',
                                          ('div',
                                           ('num', 3.0),
                                           ('mul',
                                            ('mul',
                                             ('num', 4.0),
                                             ('var', 'π')),
                                            ('var', 'n'))),
                                          ('div',
                                           ('num', 1.0),
                                           ('num', 3.0)))),
                                        ('body_decl',
                                         'ex',
                                         ('tensor',
                                          [('m', 'invariant'),
                                           ('k', 'invariant')]),
                                         ('div',
                                          ('var', 'cx'),
                                          ('var', 'rs'))),
                                        ('body_decl',
                                         'vx',
                                         ('tensor',
                                          [('m', 'invariant'),
                                           ('k', 'invariant')]),
                                         ('mul',
                                          ('div', ('num', 4.0), ('num', 3.0)),
                                          ('var', 'ex')))]},
               'lda_c_chachiyo': {'params': [('n',
                                              ('tensor',
                                               [('m', 'invariant'),
                                                ('k', 'invariant')]))],
                                  'return_type': ('tensor',
                                                  [(2, 'invariant'),
                                                   ('m', 'invariant'),
                                                   ('k', 'invariant')]),
                                  'body': ('array',
                                           [('var', 'ec'), ('var', 'vc')]),
                                  'has_loop': False,
                                  'statements': [('body_decl',
                                                  'a',
                                                  'ℝ',
                                                  ('neg',
                                                   ('num', 0.01554535))),
                                                 ('body_decl',
                                                  'b',
                                                  'ℝ',
                                                  ('num', 20.4562557)),
                                                 ('body_decl',
                                                  'rs',
                                                  ('tensor',
                                                   [('m', 'invariant'),
                                                    ('k', 'invariant')]),
                                                  ('pow',
                                                   ('div',
                                                    ('num', 3.0),
                                                    ('mul',
                                                     ('mul',
                                                      ('num', 4.0),
                                                      ('var', 'π')),
                                                     ('var', 'n'))),
                                                   ('div',
                                                    ('num', 1.0),
                                                    ('num', 3.0)))),
                                                 ('body_decl',
                                                  'ec',
                                                  ('tensor',
                                                   [('m', 'invariant'),
                                                    ('k', 'invariant')]),
                                                  ('mul',
                                                   ('var', 'a'),
                                                   ('call',
                                                    'log',
                                                    [('add',
                                                      ('add',
                                                       ('num', 1.0),
                                                       ('div',
                                                        ('var', 'b'),
                                                        ('var', 'rs'))),
                                                      ('div',
                                                       ('var', 'b'),
                                                       ('pow',
                                                        ('var', 'rs'),
                                                        ('num', 2.0))))]))),
                                                 ('body_decl',
                                                  'vc',
                                                  ('tensor',
                                                   [('m', 'invariant'),
                                                    ('k', 'invariant')]),
                                                  ('add',
                                                   ('var', 'ec'),
                                                   ('div',
                                                    ('mul',
                                                     ('mul',
                                                      ('var', 'a'),
                                                      ('var', 'b')),
                                                     ('add',
                                                      ('num', 2.0),
                                                      ('var', 'rs'))),
                                                    ('mul',
                                                     ('num', 3.0),
                                                     ('add',
                                                      ('add',
                                                       ('var', 'b'),
                                                       ('mul',
                                                        ('var', 'b'),
                                                        ('var', 'rs'))),
                                                      ('pow',
                                                       ('var', 'rs'),
                                                       ('num', 2.0)))))))]}},
 'classes': {},
 'program': [('assign', 'π', ('num', 3.141592653589793), 9),
             ('func_def', 'lda_x'),
             ('func_def', 'lda_c_chachiyo')]}
