EXPECTED = {'functions': {'sum_for_expr': {'params': [('s', 'ℝ')],
                                'return_type': 'ℝ',
                                'body': ('call',
                                         'sum',
                                         [('for_expr',
                                           'i',
                                           ('num', 4.0),
                                           ('mul',
                                            ('var', 's'),
                                            ('imaginary',)))]),
                                'has_loop': False,
                                'statements': []},
               'dot_with_arr': {'params': [('s', 'ℝ')],
                                'return_type': 'ℝ',
                                'body': ('var', 'result'),
                                'has_loop': False,
                                'statements': [('body_decl',
                                                'a3',
                                                ('tensor', [(4, 'invariant')]),
                                                ('array',
                                                 [('num', 1.0),
                                                  ('num', 2.0),
                                                  ('num', 3.0),
                                                  ('num', 4.0)])),
                                               ('body_decl',
                                                'result',
                                                'ℝ',
                                                ('num', 0.0)),
                                               ('body_for',
                                                'i',
                                                [('loop_pluseq',
                                                  'result',
                                                  ('mul',
                                                   ('var', 's'),
                                                   ('index',
                                                    'a3',
                                                    ('imaginary',))))],
                                                ['a3'])]},
               'matmul_scale': {'params': [('s', 'ℝ')],
                                'return_type': 'ℝ',
                                'body': ('call', 'sum', [('var', 'C3')]),
                                'has_loop': False,
                                'statements': [('body_decl',
                                                'A3',
                                                ('tensor',
                                                 [(2, 'invariant'),
                                                  (2, 'invariant')]),
                                                ('array',
                                                 [('array',
                                                   [('num', 1.0),
                                                    ('num', 2.0)]),
                                                  ('array',
                                                   [('num', 3.0),
                                                    ('num', 4.0)])])),
                                               ('body_decl',
                                                'I',
                                                ('tensor',
                                                 [(2, 'invariant'),
                                                  (2, 'invariant')]),
                                                ('array',
                                                 [('array',
                                                   [('num', 1.0),
                                                    ('num', 0.0)]),
                                                  ('array',
                                                   [('num', 0.0),
                                                    ('num', 1.0)])])),
                                               ('body_zeros_decl',
                                                'C3',
                                                ('tensor',
                                                 [(2, 'invariant'),
                                                  (2, 'invariant')])),
                                               ('body_for_accum',
                                                ['i', 'j', 'k'],
                                                [('loop_index_pluseq',
                                                  'C3',
                                                  [('imaginary',),
                                                   ('var', 'j')],
                                                  ('mul',
                                                   ('mul',
                                                    ('var', 's'),
                                                    ('indexN',
                                                     'A3',
                                                     [('imaginary',),
                                                      ('var', 'k')])),
                                                   ('indexN',
                                                    'I',
                                                    [('var', 'k'),
                                                     ('var', 'j')])))])]},
               'nested_sum': {'params': [('s', 'ℝ')],
                              'return_type': 'ℝ',
                              'body': ('var', 'result'),
                              'has_loop': False,
                              'statements': [('body_decl',
                                              'result',
                                              'ℝ',
                                              ('num', 0.0)),
                                             ('body_for_range',
                                              'i',
                                              ('num', 0),
                                              ('num', 10.0),
                                              [('loop_for_range',
                                                'j',
                                                ('imaginary',),
                                                ('num', 10.0),
                                                [('loop_pluseq',
                                                  'result',
                                                  ('add',
                                                   ('mul',
                                                    ('mul',
                                                     ('var', 's'),
                                                     ('imaginary',)),
                                                    ('num', 1.0)),
                                                   ('mul',
                                                    ('mul',
                                                     ('var', 's'),
                                                     ('var', 'j')),
                                                    ('num', 1.0))))])])]},
               'scale_vec': {'params': [('x', 'ℝ')],
                             'return_type': ('tensor', [(3, 'invariant')]),
                             'body': ('for_expr',
                                      'i',
                                      ('num', 3.0),
                                      ('mul',
                                       ('var', 'x'),
                                       ('add', ('imaginary',), ('num', 1.0)))),
                             'has_loop': False,
                             'statements': []},
               'sq_vec': {'params': [('x', 'ℝ')],
                          'return_type': ('tensor', [(4, 'invariant')]),
                          'body': ('for_expr',
                                   'i',
                                   ('num', 4.0),
                                   ('mul',
                                    ('pow', ('var', 'x'), ('num', 2.0)),
                                    ('add', ('imaginary',), ('num', 1.0)))),
                          'has_loop': False,
                          'statements': []},
               'cos_freqs': {'params': [('x', 'ℝ')],
                             'return_type': ('tensor', [(4, 'invariant')]),
                             'body': ('for_expr',
                                      'i',
                                      ('num', 4.0),
                                      ('call',
                                       'cos',
                                       [('mul',
                                         ('var', 'x'),
                                         ('add',
                                          ('imaginary',),
                                          ('num', 1.0)))])),
                             'has_loop': False,
                             'statements': []},
               'elementwise_sq': {'params': [('x',
                                              ('tensor',
                                               [('n', 'invariant')]))],
                                  'return_type': ('tensor',
                                                  [('n', 'invariant')]),
                                  'body': ('for_expr',
                                           'i',
                                           ('call', 'len', [('var', 'x')]),
                                           ('pow',
                                            ('index', 'x', ('imaginary',)),
                                            ('num', 2.0))),
                                  'has_loop': False,
                                  'statements': []}},
 'classes': {},
 'program': [('func_def', 'sum_for_expr'),
             ('decl', 's0', 'ℝ', ('num', 2.0), 7),
             ('expr', ('call', 'sum_for_expr', [('var', 's0')]), 0),
             ('expr',
              ('call',
               'grad',
               [('call', 'sum_for_expr', [('var', 's0')]), ('var', 's0')]),
              0),
             ('func_def', 'dot_with_arr'),
             ('decl', 's1', 'ℝ', ('num', 1.0), 20),
             ('expr', ('call', 'dot_with_arr', [('var', 's1')]), 0),
             ('expr',
              ('call',
               'grad',
               [('call', 'dot_with_arr', [('var', 's1')]), ('var', 's1')]),
              0),
             ('func_def', 'matmul_scale'),
             ('decl', 's2', 'ℝ', ('num', 1.0), 34),
             ('expr', ('call', 'matmul_scale', [('var', 's2')]), 0),
             ('expr',
              ('call',
               'grad',
               [('call', 'matmul_scale', [('var', 's2')]), ('var', 's2')]),
              0),
             ('func_def', 'nested_sum'),
             ('decl', 's3', 'ℝ', ('num', 1.0), 47),
             ('expr', ('call', 'nested_sum', [('var', 's3')]), 0),
             ('expr',
              ('call',
               'grad',
               [('call', 'nested_sum', [('var', 's3')]), ('var', 's3')]),
              0),
             ('func_def', 'scale_vec'),
             ('decl', 's', 'ℝ', ('num', 2.0), 57),
             ('expr', ('call', 'scale_vec', [('var', 's')]), 0),
             ('expr',
              ('call',
               'grad',
               [('call', 'scale_vec', [('var', 's')]), ('var', 's')]),
              0),
             ('func_def', 'sq_vec'),
             ('decl', 'sv', 'ℝ', ('num', 3.0), 65),
             ('expr', ('call', 'sq_vec', [('var', 'sv')]), 0),
             ('expr',
              ('call',
               'grad',
               [('call', 'sq_vec', [('var', 'sv')]), ('var', 'sv')]),
              0),
             ('func_def', 'cos_freqs'),
             ('decl', 'x', 'ℝ', ('num', 0.5), 73),
             ('expr', ('call', 'cos_freqs', [('var', 'x')]), 0),
             ('expr',
              ('call',
               'grad',
               [('call', 'cos_freqs', [('var', 'x')]), ('var', 'x')]),
              0),
             ('func_def', 'elementwise_sq'),
             ('decl',
              'ev',
              ('tensor', [(3, 'invariant')]),
              ('array', [('num', 1.0), ('num', 2.0), ('num', 3.0)]),
              82),
             ('expr', ('call', 'elementwise_sq', [('var', 'ev')]), 0),
             ('expr',
              ('call',
               'grad',
               [('call', 'elementwise_sq', [('var', 'ev')]), ('var', 'ev')]),
              0)]}