EXPECTED = {'functions': {'torch_funcs_with_scalar_R': {'params': [('x', 'ℝ')],
                                             'return_type': ('tensor',
                                                             'ℝ',
                                                             [('m',
                                                               'invariant')]),
                                             'body': ('array',
                                                      [('var', 'result_sin'),
                                                       ('var', 'result_cos'),
                                                       ('var', 'result_exp'),
                                                       ('var', 'result_sqrt'),
                                                       ('var', 'result_log'),
                                                       ('var', 'result_abs')]),
                                             'has_loop': False,
                                             'statements': [('body_decl',
                                                             'result_sin',
                                                             'ℝ',
                                                             ('call',
                                                              'sin',
                                                              [('var', 'x')])),
                                                            ('body_decl',
                                                             'result_cos',
                                                             'ℝ',
                                                             ('call',
                                                              'cos',
                                                              [('var', 'x')])),
                                                            ('body_decl',
                                                             'result_exp',
                                                             'ℝ',
                                                             ('call',
                                                              'exp',
                                                              [('var', 'x')])),
                                                            ('body_decl',
                                                             'result_sqrt',
                                                             'ℝ',
                                                             ('call',
                                                              'sqrt',
                                                              [('var', 'x')])),
                                                            ('body_decl',
                                                             'result_log',
                                                             'ℝ',
                                                             ('call',
                                                              'log',
                                                              [('var', 'x')])),
                                                            ('body_decl',
                                                             'result_abs',
                                                             'ℝ',
                                                             ('call',
                                                              'abs',
                                                              [('var',
                                                                'x')]))]},
               'check_diff_torch_funcs': {'params': [('x', 'ℝ')],
                                          'return_type': 'ℝ',
                                          'body': ('var', 'results'),
                                          'has_loop': False,
                                          'statements': [('body_assign',
                                                          'results',
                                                          ('call',
                                                           'grad',
                                                           [('var',
                                                             'torch_funcs_with_scalar_R'),
                                                            ('var', 'x')]))]},
               'f': {'params': [('x', 'ℝ')],
                     'return_type': 'ℝ',
                     'body': None,
                     'has_loop': False,
                     'statements': [('body_if_else_return',
                                     ('cond_gt', ('var', 'x'), ('num', 0)),
                                     ('call', 'cos', [('var', 'x')]),
                                     ('call', 'sin', [('var', 'x')]))]}},
 'classes': {},
 'program': [('func_def', 'torch_funcs_with_scalar_R'),
             ('func_def', 'check_diff_torch_funcs'),
             ('decl', 'x', 'ℝ', ('num', 1.0), 18),
             ('expr', ('call', 'torch_funcs_with_scalar_R', [('var', 'x')]), 0),
             ('expr', ('call', 'check_diff_torch_funcs', [('num', 5.0)]), 0),
             ('decl',
              'x_matrix',
              ('tensor', 'ℝ', [(3, 'invariant'), (3, 'invariant')]),
              ('array',
               [('array', [('num', 1), ('neg', ('num', 1)), ('num', 0)]),
                ('array', [('neg', ('num', 1)), ('num', 0), ('num', 0)]),
                ('array', [('num', 0), ('num', 0), ('num', 0)])]),
              27),
             ('decl',
              'rolled_neg',
              ('tensor', 'ℝ', [(3, 'invariant'), (3, 'invariant')]),
              ('call', 'roll', [('var', 'x_matrix'), ('neg', ('num', 1))]),
              32),
             ('decl',
              'rolled_pos',
              ('tensor', 'ℝ', [(3, 'invariant'), (3, 'invariant')]),
              ('call', 'roll', [('var', 'x_matrix'), ('num', 1)]),
              33),
             ('expr', ('var', 'rolled_neg'), 0),
             ('expr', ('var', 'rolled_pos'), 0),
             ('func_def', 'f'),
             ('decl', 'x0', 'ℝ', ('neg', ('num', 1.5)), 54),
             ('expr', ('call', 'f', [('var', 'x0')]), 0),
             ('expr',
              ('call', 'grad', [('call', 'f', [('var', 'x0')]), ('var', 'x0')]),
              0),
             ('decl', 'x1', 'ℝ', ('neg', ('num', 0.5)), 58),
             ('expr', ('call', 'f', [('var', 'x1')]), 0),
             ('expr',
              ('call', 'grad', [('call', 'f', [('var', 'x1')]), ('var', 'x1')]),
              0),
             ('decl', 'x2', 'ℝ', ('num', 0.5), 62),
             ('expr', ('call', 'f', [('var', 'x2')]), 0),
             ('expr',
              ('call', 'grad', [('call', 'f', [('var', 'x2')]), ('var', 'x2')]),
              0),
             ('decl', 'x3', 'ℝ', ('num', 1.5), 66),
             ('expr', ('call', 'f', [('var', 'x3')]), 0),
             ('expr',
              ('call', 'grad', [('call', 'f', [('var', 'x3')]), ('var', 'x3')]),
              0),
             ('decl', 'x4', 'ℝ', ('num', 3.14), 70),
             ('expr', ('call', 'f', [('var', 'x4')]), 0),
             ('expr',
              ('call', 'grad', [('call', 'f', [('var', 'x4')]), ('var', 'x4')]),
              0)]}
