EXPECTED = {'functions': {'L': {'params': [('t', 'ℝ')],
                     'return_type': 'ℝ',
                     'body': None,
                     'has_loop': False,
                     'statements': [('body_if_else_return',
                                     ('cond_gt', ('var', 't'), ('num', 0.5)),
                                     ('add',
                                      ('mul',
                                       ('mul',
                                        ('num', 3.0),
                                        ('sub', ('var', 't'), ('num', 0.75))),
                                       ('sub', ('var', 't'), ('num', 0.75))),
                                      ('num', 0.1)),
                                     ('add',
                                      ('mul', ('var', 't'), ('var', 't')),
                                      ('num', 2.0)))]}},
 'classes': {},
 'program': [('func_def', 'L'),
             ('decl', 't0', 'ℝ', ('num', 0.9), 16),
             ('expr', ('call', 'L', [('var', 't0')]), 0),
             ('expr',
              ('call', 'grad', [('call', 'L', [('var', 't0')]), ('var', 't0')]),
              0),
             ('decl',
              't1',
              'ℝ',
              ('sub',
               ('var', 't0'),
               ('mul',
                ('num', 0.2),
                ('call',
                 'grad',
                 [('call', 'L', [('var', 't0')]), ('var', 't0')]))),
              20),
             ('expr', ('call', 'L', [('var', 't1')]), 0),
             ('expr',
              ('call', 'grad', [('call', 'L', [('var', 't1')]), ('var', 't1')]),
              0),
             ('decl',
              't2',
              'ℝ',
              ('sub',
               ('var', 't1'),
               ('mul',
                ('num', 0.2),
                ('call',
                 'grad',
                 [('call', 'L', [('var', 't1')]), ('var', 't1')]))),
              24),
             ('expr', ('call', 'L', [('var', 't2')]), 0),
             ('expr',
              ('call', 'grad', [('call', 'L', [('var', 't2')]), ('var', 't2')]),
              0),
             ('decl',
              't3',
              'ℝ',
              ('sub',
               ('var', 't2'),
               ('mul',
                ('num', 0.2),
                ('call',
                 'grad',
                 [('call', 'L', [('var', 't2')]), ('var', 't2')]))),
              28),
             ('expr', ('call', 'L', [('var', 't3')]), 0),
             ('decl', 's0', 'ℝ', ('num', 0.3), 32),
             ('expr', ('call', 'L', [('var', 's0')]), 0),
             ('expr',
              ('call', 'grad', [('call', 'L', [('var', 's0')]), ('var', 's0')]),
              0),
             ('decl',
              's1',
              'ℝ',
              ('sub',
               ('var', 's0'),
               ('mul',
                ('num', 0.2),
                ('call',
                 'grad',
                 [('call', 'L', [('var', 's0')]), ('var', 's0')]))),
              36),
             ('expr', ('call', 'L', [('var', 's1')]), 0),
             ('expr',
              ('call', 'grad', [('call', 'L', [('var', 's1')]), ('var', 's1')]),
              0),
             ('decl',
              's2',
              'ℝ',
              ('sub',
               ('var', 's1'),
               ('mul',
                ('num', 0.2),
                ('call',
                 'grad',
                 [('call', 'L', [('var', 's1')]), ('var', 's1')]))),
              40),
             ('expr', ('call', 'L', [('var', 's2')]), 0)]}
