EXPECTED = {'functions': {'f': {'params': [('x', 'ℝ')],
                     'return_type': 'ℝ',
                     'body': None,
                     'has_loop': False,
                     'statements': [('body_if_else_return',
                                     ('cond_gt', ('var', 'x'), ('num', 0.0)),
                                     ('mul', ('var', 'x'), ('var', 'x')),
                                     ('sub', ('num', 0.0), ('var', 'x')))]}},
 'classes': {},
 'program': [('func_def', 'f'),
             ('decl', 'a', 'ℝ', ('num', 3.0), 12),
             ('expr', ('call', 'f', [('var', 'a')]), 0),
             ('expr',
              ('call', 'grad', [('call', 'f', [('var', 'a')]), ('var', 'a')]),
              0),
             ('decl', 'b', 'ℝ', ('neg', ('num', 2.0)), 17),
             ('expr', ('call', 'f', [('var', 'b')]), 0),
             ('expr',
              ('call', 'grad', [('call', 'f', [('var', 'b')]), ('var', 'b')]),
              0)]}
