EXPECTED = {'functions': {'fact': {'params': [('n', 'ℝ')],
                        'return_type': 'ℝ',
                        'body': None,
                        'has_loop': False,
                        'statements': [('body_if_else_return',
                                        ('cond_eq', ('var', 'n'), ('num', 0.0)),
                                        ('num', 1.0),
                                        ('mul',
                                         ('var', 'n'),
                                         ('call',
                                          'fact',
                                          [('sub',
                                            ('var', 'n'),
                                            ('num', 1.0))])))]},
               'f': {'params': [('x', 'ℝ')],
                     'return_type': 'ℝ',
                     'body': None,
                     'has_loop': False,
                     'statements': [('body_if_else_return',
                                     ('cond_gt', ('var', 'x'), ('num', 0)),
                                     ('call', 'cos', [('var', 'x')]),
                                     ('call', 'sin', [('var', 'x')]))]},
               'torch_funcs_with_scalar_R': {'params': [('x', 'ℝ')],
                                             'return_type': ('tensor',
                                                             [('m',
                                                               'invariant')]),
                                             'body': ('array',
                                                      [('var', 'result_sin'),
                                                       ('var', 'result_cos'),
                                                       ('var', 'result_exp'),
                                                       ('var', 'result_sqrt'),
                                                       ('var', 'result_log'),
                                                       ('var', 'result_abs')]),
                                             'has_loop': False,
                                             'statements': [('body_decl',
                                                             'result_sin',
                                                             'ℝ',
                                                             ('call',
                                                              'sin',
                                                              [('var', 'x')])),
                                                            ('body_decl',
                                                             'result_cos',
                                                             'ℝ',
                                                             ('call',
                                                              'cos',
                                                              [('var', 'x')])),
                                                            ('body_decl',
                                                             'result_exp',
                                                             'ℝ',
                                                             ('call',
                                                              'exp',
                                                              [('var', 'x')])),
                                                            ('body_decl',
                                                             'result_sqrt',
                                                             'ℝ',
                                                             ('call',
                                                              'sqrt',
                                                              [('var', 'x')])),
                                                            ('body_decl',
                                                             'result_log',
                                                             'ℝ',
                                                             ('call',
                                                              'log',
                                                              [('var', 'x')])),
                                                            ('body_decl',
                                                             'result_abs',
                                                             'ℝ',
                                                             ('call',
                                                              'abs',
                                                              [('var',
                                                                'x')]))]}},
 'classes': {},
 'program': [('func_def', 'fact'),
             ('decl', 'x', 'ℝ', ('num', 1.0), 8),
             ('decl', 'fact_results', 'ℝ', ('call', 'fact', [('var', 'x')]), 9),
             ('expr', ('var', 'fact_results'), 0),
             ('func_def', 'f'),
             ('func_def', 'torch_funcs_with_scalar_R'),
             ('decl',
              'torch_funcs_results',
              ('tensor', [(6, 'invariant')]),
              ('call', 'torch_funcs_with_scalar_R', [('var', 'x')]),
              18),
             ('expr', ('var', 'torch_funcs_results'), 0),
             ('decl', 'f_results', 'ℝ', ('call', 'f', [('var', 'x')]), 21),
             ('expr', ('var', 'f_results'), 0)]}
