EXPECTED = {'classes': {},
 'functions': {},
 'program': [('symbol_decl_multi', ['x', 'y']),
             ('function_decl', 'u'),
             ('expr', ('var', 'x'), 0),
             ('assign',
              'f',
              ('add',
               ('pow', ('var', 'x'), ('num', 2.0)),
               ('pow', ('var', 'y'), ('num', 2.0))),
              11),
             ('expr', ('var', 'f'), 0),
             ('assign',
              'expr',
              ('call', 'u', [('var', 'x'), ('var', 'y')]),
              15),
             ('expr', ('var', 'expr'), 0),
             ('expr',
              ('call',
               'subs',
               [('var', 'f'),
                ('var', 'x'),
                ('num', 3.0),
                ('var', 'y'),
                ('num', 4.0)]),
              0),
             ('assign',
              'f',
              ('add',
               ('add',
                ('pow', ('var', 'x'), ('num', 3.0)),
                ('pow', ('mul', ('num', 2.0), ('var', 'x')), ('num', 2.0))),
               ('var', 'x')),
              22),
             ('expr', ('call', 'diff', [('var', 'f'), ('var', 'x')]), 0),
             ('assign',
              'expr',
              ('add',
               ('pow', ('var', 'x'), ('num', 2.0)),
               ('pow', ('var', 'y'), ('num', 2.0))),
              27),
             ('assign',
              'f',
              ('call',
               'lambdify',
               [('array', [('var', 'x'), ('var', 'y')]), ('var', 'expr')]),
              28),
             ('expr', ('call', 'f', [('num', 3.0), ('num', 4.0)]), 0),
             ('equation_decl',
              'eq',
              ('add', ('mul', ('num', 2.0), ('var', 'x')), ('num', 3.0)),
              ('num', 7.0)),
             ('expr',
              ('call', 'symbolic_solve', [('var', 'eq'), ('var', 'x')]),
              0)]}