EXPECTED = {'functions': {'update_1d_array': {'params': [('x',
                                               ('tensor',
                                                'ℝ',
                                                [('m', 'invariant')]))],
                                   'return_type': ('tensor',
                                                   'ℝ',
                                                   [('m', 'invariant')]),
                                   'body': ('var', 'x'),
                                   'has_loop': False,
                                   'statements': [('body_index_assign',
                                                   'x',
                                                   ('num', 1),
                                                   ('num', 3))]},
               'update_3d_array': {'params': [('x',
                                               ('tensor',
                                                'ℝ',
                                                [('m', 'invariant'),
                                                 ('n', 'invariant'),
                                                 ('o', 'invariant')]))],
                                   'return_type': ('tensor',
                                                   'ℝ',
                                                   [('m', 'invariant'),
                                                    ('n', 'invariant'),
                                                    ('o', 'invariant')]),
                                   'body': ('var', 'x'),
                                   'has_loop': False,
                                   'statements': [('body_index_assign_nd',
                                                   'x',
                                                   [('num', 1),
                                                    ('num', 1),
                                                    ('num', 1)],
                                                   ('num', 3))]},
               'update_2d_array': {'params': [('x',
                                               ('tensor',
                                                'ℝ',
                                                [('m', 'invariant'),
                                                 ('n', 'invariant')]))],
                                   'return_type': ('tensor',
                                                   'ℝ',
                                                   [('m', 'invariant'),
                                                    ('n', 'invariant')]),
                                   'body': ('var', 'x'),
                                   'has_loop': False,
                                   'statements': [('body_index_assign_nd',
                                                   'x',
                                                   [('num', 1), ('num', 1)],
                                                   ('num', 3))]}},
 'classes': {},
 'program': [('decl',
              'x',
              ('tensor', 'ℝ', [(6, 'invariant')]),
              ('array',
               [('num', 1),
                ('num', 2),
                ('num', 3),
                ('num', 5),
                ('num', 6),
                ('num', 7)]),
              1),
             ('decl',
              'y',
              ('tensor', 'ℝ', [(3, 'invariant')]),
              ('add',
               ('slice', 'x', ('num', 0), ('num', 3)),
               ('slice', 'x', ('num', 0), ('num', 3))),
              2),
             ('decl',
              'z',
              ('tensor', 'ℝ', [(3, 'invariant')]),
              ('add',
               ('var', 'y'),
               ('array', [('num', 1), ('num', 3), ('num', 4)])),
              3),
             ('expr', ('var', 'x'), 0),
             ('expr', ('var', 'y'), 0),
             ('expr', ('var', 'z'), 0),
             ('decl',
              'u0',
              ('tensor', 'ℝ', [(4, 'invariant'), (4, 'invariant')]),
              ('array',
               [('array',
                 [('num', 0.0), ('num', 0.0), ('num', 0.0), ('num', 0.0)]),
                ('array',
                 [('num', 0.0), ('num', 0.75), ('num', 0.75), ('num', 0.0)]),
                ('array',
                 [('num', 0.0), ('num', 0.75), ('num', 0.75), ('num', 10.0)]),
                ('array',
                 [('num', 0.0), ('num', 0.0), ('num', 0.0), ('num', 0.0)])]),
              9),
             ('decl',
              'u00',
              'ℝ',
              ('indexN', 'u0', [('num', 0), ('num', 0)]),
              16),
             ('decl',
              'u01',
              'ℝ',
              ('indexN', 'u0', [('num', 0), ('num', 1)]),
              17),
             ('decl',
              'u02',
              'ℝ',
              ('indexN', 'u0', [('num', 0), ('num', 2)]),
              18),
             ('decl',
              'u03',
              'ℝ',
              ('indexN', 'u0', [('num', 0), ('num', 3)]),
              19),
             ('decl',
              'u10',
              'ℝ',
              ('indexN', 'u0', [('num', 1), ('num', 0)]),
              21),
             ('decl',
              'u11',
              'ℝ',
              ('indexN', 'u0', [('num', 1), ('num', 1)]),
              22),
             ('decl',
              'u12',
              'ℝ',
              ('indexN', 'u0', [('num', 1), ('num', 2)]),
              23),
             ('decl',
              'u13',
              'ℝ',
              ('indexN', 'u0', [('num', 1), ('num', 3)]),
              24),
             ('decl',
              'u20',
              'ℝ',
              ('indexN', 'u0', [('num', 2), ('num', 0)]),
              26),
             ('decl',
              'u21',
              'ℝ',
              ('indexN', 'u0', [('num', 2), ('num', 1)]),
              27),
             ('decl',
              'u22',
              'ℝ',
              ('indexN', 'u0', [('num', 2), ('num', 2)]),
              28),
             ('decl',
              'u23',
              'ℝ',
              ('indexN', 'u0', [('num', 2), ('num', 3)]),
              29),
             ('decl',
              'u30',
              'ℝ',
              ('indexN', 'u0', [('num', 3), ('num', 0)]),
              31),
             ('decl',
              'u31',
              'ℝ',
              ('indexN', 'u0', [('num', 3), ('num', 1)]),
              32),
             ('decl',
              'u32',
              'ℝ',
              ('indexN', 'u0', [('num', 3), ('num', 2)]),
              33),
             ('decl',
              'u33',
              'ℝ',
              ('indexN', 'u0', [('num', 3), ('num', 3)]),
              34),
             ('decl',
              'A',
              ('tensor', 'ℝ', [(3, 'invariant'), (3, 'invariant')]),
              ('array',
               [('array', [('num', 1), ('num', 0), ('num', 0)]),
                ('array', [('num', 0), ('num', 2), ('num', 0)]),
                ('array', [('num', 0), ('num', 0), ('num', 3)])]),
              36),
             ('decl',
              'A00',
              'ℝ',
              ('indexN', 'A', [('num', 0), ('num', 0)]),
              42),
             ('decl',
              'A11',
              'ℝ',
              ('indexN', 'A', [('num', 1), ('num', 1)]),
              43),
             ('decl',
              'A22',
              'ℝ',
              ('indexN', 'A', [('num', 2), ('num', 2)]),
              44),
             ('decl',
              'T',
              ('tensor',
               'ℝ',
               [(2, 'invariant'), (3, 'invariant'), (4, 'invariant')]),
              ('array',
               [('array',
                 [('array', [('num', 1), ('num', 2), ('num', 3), ('num', 4)]),
                  ('array', [('num', 5), ('num', 6), ('num', 7), ('num', 8)]),
                  ('array',
                   [('num', 9), ('num', 10), ('num', 11), ('num', 12)])]),
                ('array',
                 [('array',
                   [('num', 13), ('num', 14), ('num', 15), ('num', 16)]),
                  ('array',
                   [('num', 17), ('num', 18), ('num', 19), ('num', 20)]),
                  ('array',
                   [('num', 21), ('num', 22), ('num', 23), ('num', 24)])])]),
              46),
             ('decl',
              'T0',
              ('tensor', 'ℝ', [(3, 'invariant'), (4, 'invariant')]),
              ('index', 'T', ('num', 0)),
              51),
             ('decl',
              'T12',
              ('tensor', 'ℝ', [(4, 'invariant')]),
              ('indexN', 'T', [('num', 1), ('num', 2)]),
              52),
             ('decl',
              'T000',
              'ℝ',
              ('indexN', 'T', [('num', 0), ('num', 0), ('num', 0)]),
              53),
             ('decl',
              'T123',
              'ℝ',
              ('indexN', 'T', [('num', 1), ('num', 2), ('num', 3)]),
              54),
             ('decl',
              'T012',
              'ℝ',
              ('indexN', 'T', [('num', 0), ('num', 1), ('num', 2)]),
              55),
             ('decl',
              'prog_1d',
              ('tensor', 'ℝ', [(2, 'invariant')]),
              ('array', [('num', 1.0), ('num', 1.0)]),
              66),
             ('decl',
              'prog_2d',
              ('tensor', 'ℝ', [(2, 'invariant'), (2, 'invariant')]),
              ('array',
               [('array', [('num', 1.0), ('num', 1.0)]),
                ('array', [('num', 1.0), ('num', 1.0)])]),
              67),
             ('decl',
              'prog_3d',
              ('tensor',
               'ℝ',
               [(2, 'invariant'), (2, 'invariant'), (2, 'invariant')]),
              ('array',
               [('array',
                 [('array', [('num', 1.0), ('num', 1.0)]),
                  ('array', [('num', 1.0), ('num', 1.0)])]),
                ('array',
                 [('array', [('num', 1.0), ('num', 1.0)]),
                  ('array', [('num', 1.0), ('num', 1.0)])])]),
              68),
             ('index_assign', 'prog_1d', 1, ('num', 2), 70),
             ('index_assign_nd',
              'prog_2d',
              [('num', 1), ('num', 1)],
              ('num', 2),
              71),
             ('index_assign_nd',
              'prog_3d',
              [('num', 1), ('num', 1), ('num', 1)],
              ('num', 2),
              72),
             ('expr', ('var', 'prog_1d'), 0),
             ('expr', ('var', 'prog_2d'), 0),
             ('expr', ('var', 'prog_3d'), 0),
             ('decl',
              'func_1d',
              ('tensor', 'ℝ', [(2, 'invariant')]),
              ('array', [('num', 1.0), ('num', 1.0)]),
              83),
             ('decl',
              'func_2d',
              ('tensor', 'ℝ', [(2, 'invariant'), (2, 'invariant')]),
              ('array',
               [('array', [('num', 1.0), ('num', 1.0)]),
                ('array', [('num', 1.0), ('num', 1.0)])]),
              84),
             ('decl',
              'func_3d',
              ('tensor',
               'ℝ',
               [(2, 'invariant'), (2, 'invariant'), (2, 'invariant')]),
              ('array',
               [('array',
                 [('array', [('num', 1.0), ('num', 1.0)]),
                  ('array', [('num', 1.0), ('num', 1.0)])]),
                ('array',
                 [('array', [('num', 1.0), ('num', 1.0)]),
                  ('array', [('num', 1.0), ('num', 1.0)])])]),
              85),
             ('func_def', 'update_1d_array'),
             ('func_def', 'update_3d_array'),
             ('func_def', 'update_2d_array'),
             ('expr', ('call', 'update_1d_array', [('var', 'func_1d')]), 0),
             ('expr', ('call', 'update_2d_array', [('var', 'func_2d')]), 0),
             ('expr', ('call', 'update_3d_array', [('var', 'func_3d')]), 0)]}
