EXPECTED = {'functions': {},
 'classes': {},
 'program': [('decl',
              'v',
              ('tensor', 'ℝ', [(3, 'contravariant')]),
              ('array', [('num', 1.0), ('num', 2.0), ('num', 3.0)]),
              2),
             ('expr', ('var', 'v'), 0),
             ('decl',
              'omega',
              ('tensor', 'ℝ', [(3, 'covariant')]),
              ('array', [('num', 1.0), ('num', 2.0), ('num', 3.0)]),
              6),
             ('expr', ('var', 'omega'), 0),
             ('decl',
              'T',
              ('tensor', 'ℝ', [(3, 'contravariant'), (3, 'covariant')]),
              ('array',
               [('array', [('num', 2.0), ('num', 0.0), ('num', 0.0)]),
                ('array', [('num', 0.0), ('num', 3.0), ('num', 0.0)]),
                ('array', [('num', 0.0), ('num', 0.0), ('num', 4.0)])]),
              10),
             ('decl',
              'v',
              ('tensor', 'ℝ', [(3, 'contravariant'), (1, 'contravariant')]),
              ('array',
               [('array', [('num', 1.0)]),
                ('array', [('num', 2.0)]),
                ('array', [('num', 3.0)])]),
              14),
             ('decl',
              'w',
              ('tensor', 'ℝ', [(3, 'contravariant'), (1, 'contravariant')]),
              ('matmul', ('var', 'T'), ('var', 'v')),
              17),
             ('expr', ('var', 'w'), 0),
             ('decl',
              'T',
              ('tensor', 'ℝ', [(3, 'contravariant'), (3, 'covariant')]),
              ('array',
               [('array', [('num', 2.0), ('num', 0.0), ('num', 0.0)]),
                ('array', [('num', 0.0), ('num', 3.0), ('num', 0.0)]),
                ('array', [('num', 0.0), ('num', 0.0), ('num', 4.0)])]),
              39),
             ('decl',
              'v',
              ('tensor', 'ℝ', [(3, 'contravariant'), (1, 'contravariant')]),
              ('array',
               [('array', [('num', 1.0)]),
                ('array', [('num', 2.0)]),
                ('array', [('num', 3.0)])]),
              43),
             ('decl',
              'w',
              ('tensor', 'ℝ', [(3, 'contravariant'), (1, 'contravariant')]),
              ('matmul', ('var', 'T'), ('var', 'v')),
              46),
             ('expr', ('var', 'w'), 0),
             ('expr', ('var', 'T'), 0)]}
