EXPECTED = {'functions': {'update': {'params': [('y',
                                      ('tensor',
                                       [('m', 'invariant'),
                                        ('n', 'invariant')]))],
                          'return_type': ('tensor',
                                          [('m', 'invariant'),
                                           ('n', 'invariant')]),
                          'body': ('var', 'y'),
                          'has_loop': False,
                          'statements': [('body_assign',
                                          'z',
                                          ('indexN',
                                           'y',
                                           [('slice_item', None, None),
                                            ('index_item', ('num', 2))]))]}},
 'classes': {'A': {'class_params': [('x', 'ℝ')],
                   'fields': [],
                   'methods': [{'name': 'abe',
                                'params': [('x',
                                            ('tensor',
                                             [('m', 'invariant'),
                                              ('n', 'invariant')]))],
                                'return_type': ('tensor',
                                                [('m', 'invariant'),
                                                 ('n', 'invariant')]),
                                'statements': [('body_assign',
                                                'z',
                                                ('indexN',
                                                 'x',
                                                 [('slice_item', None, None),
                                                  ('index_item',
                                                   ('num', 2))]))],
                                'body': ('var', 'z')}]}},
 'program': [('decl',
              'x',
              ('tensor', [(8, 'invariant')]),
              ('array',
               [('num', 10),
                ('num', 20),
                ('num', 30),
                ('num', 40),
                ('num', 50),
                ('num', 60),
                ('num', 70),
                ('num', 80)]),
              1),
             ('expr',
              ('indexN', 'x', [('slice_item', ('num', 1), ('num', 5))]),
              0),
             ('expr', ('indexN', 'x', [('slice_item', None, ('num', 4))]), 0),
             ('expr', ('indexN', 'x', [('slice_item', None, None)]), 0),
             ('expr', ('indexN', 'x', [('slice_item', ('num', 2), None)]), 0),
             ('expr',
              ('indexN', 'x', [('index_item', ('neg', ('num', 1)))]),
              0),
             ('decl',
              'y',
              ('tensor', [(4, 'invariant'), (4, 'invariant')]),
              ('array',
               [('array', [('num', 1), ('num', 2), ('num', 3), ('num', 4)]),
                ('array', [('num', 5), ('num', 6), ('num', 7), ('num', 8)]),
                ('array', [('num', 9), ('num', 10), ('num', 11), ('num', 12)]),
                ('array',
                 [('num', 13), ('num', 14), ('num', 15), ('num', 16)])]),
              11),
             ('expr',
              ('indexN',
               'y',
               [('slice_item', None, ('num', 1)),
                ('slice_item', None, ('num', 2))]),
              0),
             ('expr',
              ('indexN',
               'y',
               [('slice_item', ('num', 1), ('num', 3)),
                ('slice_item', ('num', 1), ('num', 3))]),
              0),
             ('expr',
              ('indexN',
               'y',
               [('slice_item', None, None), ('index_item', ('num', 2))]),
              0),
             ('expr',
              ('indexN',
               'y',
               [('index_item', ('num', 1)), ('slice_item', None, None)]),
              0),
             ('expr',
              ('indexN',
               'y',
               [('slice_item', ('num', 1), None),
                ('slice_item', ('num', 1), ('num', 3))]),
              0),
             ('expr',
              ('indexN',
               'y',
               [('slice_item', None, None), ('slice_item', None, None)]),
              0),
             ('decl',
              'z',
              ('tensor',
               [(2, 'invariant'), (2, 'invariant'), (3, 'invariant')]),
              ('array',
               [('array',
                 [('array', [('num', 1), ('num', 2), ('num', 3)]),
                  ('array', [('num', 4), ('num', 5), ('num', 6)])]),
                ('array',
                 [('array', [('num', 7), ('num', 8), ('num', 9)]),
                  ('array', [('num', 10), ('num', 11), ('num', 12)])])]),
              27),
             ('expr',
              ('indexN',
               'z',
               [('index_item', ('num', 0)),
                ('slice_item', None, None),
                ('slice_item', None, None)]),
              0),
             ('expr',
              ('indexN',
               'z',
               [('slice_item', None, None),
                ('index_item', ('num', 1)),
                ('slice_item', None, None)]),
              0),
             ('expr',
              ('indexN',
               'z',
               [('slice_item', None, None),
                ('slice_item', None, None),
                ('index_item', ('num', 1))]),
              0),
             ('expr',
              ('indexN',
               'z',
               [('index_item', ('num', 1)),
                ('slice_item', None, None),
                ('slice_item', ('num', 1), None)]),
              0),
             ('expr',
              ('indexN',
               'z',
               [('slice_item', None, None),
                ('slice_item', None, None),
                ('slice_item', None, None)]),
              0),
             ('func_def', 'update'),
             ('expr', ('call', 'update', [('var', 'y')]), 0),
             ('class_def', 'A'),
             ('assign', 'obj', ('call', 'A', [('num', 1.0)]), 63),
             ('expr',
              ('method_call', ('var', 'obj'), 'abe', [('var', 'y')]),
              0)]}
