EXPECTED = {'functions': {},
 'classes': {},
 'program': [('decl',
              'x',
              ('tensor', [(6, 'invariant')]),
              ('array',
               [('num', 1.0),
                ('num', 2.0),
                ('num', 3.0),
                ('num', 5.0),
                ('num', 6.0),
                ('num', 7.0)]),
              1),
             ('decl',
              'y',
              ('tensor', [(3, 'invariant')]),
              ('add',
               ('slice', 'x', ('num', 0.0), ('num', 2.0)),
               ('slice', 'x', ('num', 0.0), ('num', 2.0))),
              2),
             ('decl',
              'z',
              ('tensor', [(3, 'invariant')]),
              ('add',
               ('var', 'y'),
               ('array', [('num', 1.0), ('num', 3.0), ('num', 4.0)])),
              3),
             ('expr', ('var', 'x'), 0),
             ('expr', ('var', 'y'), 0),
             ('expr', ('var', 'z'), 0),
             ('decl',
              'u0',
              ('tensor', [(4, 'invariant'), (4, 'invariant')]),
              ('array',
               [('array',
                 [('num', 0.0), ('num', 0.0), ('num', 0.0), ('num', 0.0)]),
                ('array',
                 [('num', 0.0), ('num', 0.75), ('num', 0.75), ('num', 0.0)]),
                ('array',
                 [('num', 0.0), ('num', 0.75), ('num', 0.75), ('num', 10.0)]),
                ('array',
                 [('num', 0.0), ('num', 0.0), ('num', 0.0), ('num', 0.0)])]),
              9),
             ('decl',
              'u00',
              'ℝ',
              ('indexN', 'u0', [('num', 0.0), ('num', 0.0)]),
              16),
             ('decl',
              'u01',
              'ℝ',
              ('indexN', 'u0', [('num', 0.0), ('num', 1.0)]),
              17),
             ('decl',
              'u02',
              'ℝ',
              ('indexN', 'u0', [('num', 0.0), ('num', 2.0)]),
              18),
             ('decl',
              'u03',
              'ℝ',
              ('indexN', 'u0', [('num', 0.0), ('num', 3.0)]),
              19),
             ('decl',
              'u10',
              'ℝ',
              ('indexN', 'u0', [('num', 1.0), ('num', 0.0)]),
              21),
             ('decl',
              'u11',
              'ℝ',
              ('indexN', 'u0', [('num', 1.0), ('num', 1.0)]),
              22),
             ('decl',
              'u12',
              'ℝ',
              ('indexN', 'u0', [('num', 1.0), ('num', 2.0)]),
              23),
             ('decl',
              'u13',
              'ℝ',
              ('indexN', 'u0', [('num', 1.0), ('num', 3.0)]),
              24),
             ('decl',
              'u20',
              'ℝ',
              ('indexN', 'u0', [('num', 2.0), ('num', 0.0)]),
              26),
             ('decl',
              'u21',
              'ℝ',
              ('indexN', 'u0', [('num', 2.0), ('num', 1.0)]),
              27),
             ('decl',
              'u22',
              'ℝ',
              ('indexN', 'u0', [('num', 2.0), ('num', 2.0)]),
              28),
             ('decl',
              'u23',
              'ℝ',
              ('indexN', 'u0', [('num', 2.0), ('num', 3.0)]),
              29),
             ('decl',
              'u30',
              'ℝ',
              ('indexN', 'u0', [('num', 3.0), ('num', 0.0)]),
              31),
             ('decl',
              'u31',
              'ℝ',
              ('indexN', 'u0', [('num', 3.0), ('num', 1.0)]),
              32),
             ('decl',
              'u32',
              'ℝ',
              ('indexN', 'u0', [('num', 3.0), ('num', 2.0)]),
              33),
             ('decl',
              'u33',
              'ℝ',
              ('indexN', 'u0', [('num', 3.0), ('num', 3.0)]),
              34),
             ('decl',
              'A',
              ('tensor', [(3, 'invariant'), (3, 'invariant')]),
              ('array',
               [('array', [('num', 1.0), ('num', 0.0), ('num', 0.0)]),
                ('array', [('num', 0.0), ('num', 2.0), ('num', 0.0)]),
                ('array', [('num', 0.0), ('num', 0.0), ('num', 3.0)])]),
              36),
             ('decl',
              'A00',
              'ℝ',
              ('indexN', 'A', [('num', 0.0), ('num', 0.0)]),
              42),
             ('decl',
              'A11',
              'ℝ',
              ('indexN', 'A', [('num', 1.0), ('num', 1.0)]),
              43),
             ('decl',
              'A22',
              'ℝ',
              ('indexN', 'A', [('num', 2.0), ('num', 2.0)]),
              44),
             ('decl',
              'T',
              ('tensor',
               [(2, 'invariant'), (3, 'invariant'), (4, 'invariant')]),
              ('array',
               [('array',
                 [('array',
                   [('num', 1.0), ('num', 2.0), ('num', 3.0), ('num', 4.0)]),
                  ('array',
                   [('num', 5.0), ('num', 6.0), ('num', 7.0), ('num', 8.0)]),
                  ('array',
                   [('num', 9.0),
                    ('num', 10.0),
                    ('num', 11.0),
                    ('num', 12.0)])]),
                ('array',
                 [('array',
                   [('num', 13.0),
                    ('num', 14.0),
                    ('num', 15.0),
                    ('num', 16.0)]),
                  ('array',
                   [('num', 17.0),
                    ('num', 18.0),
                    ('num', 19.0),
                    ('num', 20.0)]),
                  ('array',
                   [('num', 21.0),
                    ('num', 22.0),
                    ('num', 23.0),
                    ('num', 24.0)])])]),
              46),
             ('decl',
              'T0',
              ('tensor', [(3, 'invariant'), (4, 'invariant')]),
              ('index', 'T', ('num', 0.0)),
              51),
             ('decl',
              'T12',
              ('tensor', [(4, 'invariant')]),
              ('indexN', 'T', [('num', 1.0), ('num', 2.0)]),
              52),
             ('decl',
              'T000',
              'ℝ',
              ('indexN', 'T', [('num', 0.0), ('num', 0.0), ('num', 0.0)]),
              53),
             ('decl',
              'T123',
              'ℝ',
              ('indexN', 'T', [('num', 1.0), ('num', 2.0), ('num', 3.0)]),
              54),
             ('decl',
              'T012',
              'ℝ',
              ('indexN', 'T', [('num', 0.0), ('num', 1.0), ('num', 2.0)]),
              55)]}
