EXPECTED = {'classes': {},
 'functions': {'f_with_grad': {'body': ('var', 'g'),
                               'has_loop': False,
                               'params': [('x', 'ℝ')],
                               'return_type': 'ℝ',
                               'statements': [('body_assign',
                                               'g',
                                               ('call',
                                                'grad',
                                                [('var', 'x'),
                                                 ('var', 'x')]))]}},
 'program': [('func_def', 'f_with_grad'),
             ('decl', 'v', 'ℝ', ('num', 3.0), 5),
             ('expr', ('call', 'f_with_grad', [('var', 'v')]), 0)]}