EXPECTED = {'functions': {'return_diff_list': {'params': [('x', 'ℝ')],
                                    'return_type': 'list',
                                    'body': ('var', 'results'),
                                    'has_loop': False,
                                    'statements': [('body_decl',
                                                    'A',
                                                    ('tensor',
                                                     [(2, 'invariant'),
                                                      (2, 'invariant')]),
                                                    ('array',
                                                     [('array',
                                                       [('num', 1),
                                                        ('num', 2)]),
                                                      ('array',
                                                       [('num', 3),
                                                        ('num', 4)])])),
                                                   ('body_decl',
                                                    'b',
                                                    ('tensor',
                                                     [(2, 'invariant')]),
                                                    ('array',
                                                     [('num', 5), ('num', 6)])),
                                                   ('body_decl',
                                                    'results',
                                                    'list',
                                                    ('array',
                                                     [('var', 'A'),
                                                      ('var', 'b')]))]},
               'f_scalar': {'params': [('x', 'ℝ')],
                            'return_type': 'ℝ',
                            'body': ('pow', ('var', 'x'), ('num', 2)),
                            'has_loop': False,
                            'statements': []},
               'f_tensor': {'params': [('x', ('tensor', [('m', 'invariant')]))],
                            'return_type': 'ℝ',
                            'body': ('call',
                                     'sum',
                                     [('pow', ('var', 'x'), ('num', 2))]),
                            'has_loop': False,
                            'statements': []},
               'get_1d_list_length': {'params': [('x', 'list')],
                                      'return_type': 'ℝ',
                                      'body': ('var', 'total'),
                                      'has_loop': False,
                                      'statements': [('body_decl',
                                                      'total',
                                                      'ℝ',
                                                      ('num', 0)),
                                                     ('body_decl',
                                                      'temp',
                                                      'ℝ',
                                                      ('num', 0)),
                                                     ('body_for',
                                                      'i',
                                                      [('loop_assign',
                                                        'temp',
                                                        ('index',
                                                         'x',
                                                         ('imaginary',))),
                                                       ('loop_pluseq',
                                                        'total',
                                                        ('num', 1))],
                                                      ['x'])]},
               'square_list': {'params': [('values', 'list')],
                               'return_type': ('tensor', [(3, 'invariant')]),
                               'body': ('var', 'results'),
                               'has_loop': False,
                               'statements': [('body_decl',
                                               'len_list',
                                               'ℝ',
                                               ('call',
                                                'get_1d_list_length',
                                                [('var', 'values')])),
                                              ('body_decl',
                                               'results',
                                               ('tensor', [(3, 'invariant')]),
                                               ('for_expr',
                                                'i',
                                                ('var', 'len_list'),
                                                ('pow',
                                                 ('index',
                                                  'values',
                                                  ('imaginary',)),
                                                 ('num', 2))))]},
               'f_return_list': {'params': [('x', 'ℝ'), ('y', 'ℝ'), ('z', 'ℝ')],
                                 'return_type': 'list',
                                 'body': ('var', 'results'),
                                 'has_loop': False,
                                 'statements': [('body_decl',
                                                 'results',
                                                 'list',
                                                 ('array',
                                                  [('var', 'x'),
                                                   ('var', 'y'),
                                                   ('var', 'z')]))]}},
 'classes': {'A': {'class_params': [('x', 'list')],
                   'fields': [],
                   'methods': [{'name': 'get_list',
                                'params': [],
                                'return_type': 'list',
                                'statements': [],
                                'body': ('field_access', ('var', 'this'), 'x')},
                               {'name': 'get_value_list',
                                'params': [('value1', 'ℝ'), ('value2', 'ℝ')],
                                'return_type': 'list',
                                'statements': [('body_decl',
                                                'results',
                                                'list',
                                                ('array',
                                                 [('var', 'value1'),
                                                  ('var', 'value2')]))],
                                'body': ('var', 'results')}]}},
 'program': [('decl',
              'x',
              'list',
              ('array', [('num', 1.0), ('num', 2.0), ('num', 3.0)]),
              17),
             ('decl',
              'y',
              'list',
              ('array',
               [('num', 9.0),
                ('num', 3.0),
                ('num', 5.0),
                ('num', 1.0),
                ('num', 4.0)]),
              18),
             ('decl',
              'complex_list',
              'list',
              ('array', [('complex', 1j), ('complex', 2j), ('complex', 3j)]),
              19),
             ('decl',
              'simple_nested_list',
              'list',
              ('array', [('var', 'x'), ('var', 'y')]),
              22),
             ('decl',
              'nested_list',
              'list',
              ('array',
               [('num', 1),
                ('num', 2),
                ('var', 'x'),
                ('array', [('var', 'x'), ('var', 'y')])]),
              23),
             ('decl',
              'mixed_list',
              'list',
              ('array',
               [('num', 1),
                ('var', 'x'),
                ('var', 'complex_list'),
                ('array', [('var', 'y'), ('var', 'complex_list')])]),
              24),
             ('expr', ('var', 'x'), 0),
             ('expr', ('var', 'y'), 0),
             ('expr', ('var', 'complex_list'), 0),
             ('expr', ('var', 'simple_nested_list'), 0),
             ('expr', ('var', 'nested_list'), 0),
             ('expr', ('var', 'mixed_list'), 0),
             ('decl', 'simple_index_x', 'ℝ', ('index', 'x', ('num', 0)), 38),
             ('decl',
              'simple_complex_index',
              'ℂ',
              ('index', 'complex_list', ('num', 1)),
              39),
             ('decl',
              'index_simple_nested_list',
              'list',
              ('index', 'simple_nested_list', ('num', 0)),
              41),
             ('decl',
              'index_nested_list',
              'list',
              ('index', 'nested_list', ('num', 3)),
              42),
             ('decl',
              'index_mixed_list',
              'list',
              ('index', 'mixed_list', ('num', 3)),
              43),
             ('expr', ('var', 'simple_index_x'), 0),
             ('expr', ('var', 'simple_complex_index'), 0),
             ('expr', ('var', 'index_simple_nested_list'), 0),
             ('expr', ('var', 'index_nested_list'), 0),
             ('expr', ('var', 'index_mixed_list'), 0),
             ('func_def', 'return_diff_list'),
             ('decl',
              'diff_list_results',
              'list',
              ('call', 'return_diff_list', [('num', 1.0)]),
              60),
             ('decl',
              'diff_list_first_index',
              ('tensor', [(2, 'invariant'), (2, 'invariant')]),
              ('index', 'diff_list_results', ('num', 0)),
              61),
             ('decl',
              'diff_list_second_index',
              ('tensor', [(2, 'invariant')]),
              ('index', 'diff_list_results', ('num', 1)),
              62),
             ('expr', ('var', 'diff_list_first_index'), 0),
             ('expr', ('var', 'diff_list_second_index'), 0),
             ('func_def', 'f_scalar'),
             ('func_def', 'f_tensor'),
             ('decl',
              'scalar_grad',
              'ℝ',
              ('call',
               'grad',
               [('var', 'f_scalar'), ('index', 'x', ('num', 0))]),
              79),
             ('decl',
              'tensor_grad',
              'list',
              ('call', 'grad', [('var', 'f_tensor'), ('var', 'y')]),
              80),
             ('decl',
              'nested_grad',
              'list',
              ('call',
               'grad',
               [('var', 'f_tensor'), ('index', 'mixed_list', ('num', 1))]),
              81),
             ('expr', ('var', 'scalar_grad'), 0),
             ('expr', ('var', 'tensor_grad'), 0),
             ('expr', ('var', 'nested_grad'), 0),
             ('func_def', 'get_1d_list_length'),
             ('func_def', 'square_list'),
             ('decl',
              'squared_tensor',
              ('tensor', [(3, 'invariant')]),
              ('call', 'square_list', [('var', 'x')]),
              106),
             ('expr', ('var', 'squared_tensor'), 0),
             ('func_def', 'f_return_list'),
             ('decl',
              'f_results',
              'list',
              ('call', 'f_return_list', [('num', 1), ('num', 2), ('num', 3)]),
              115),
             ('expr', ('var', 'f_results'), 0),
             ('class_def', 'A'),
             ('decl',
              'obj',
              ('struct_type', 'A'),
              ('call', 'A', [('var', 'nested_list')]),
              131),
             ('decl',
              'obj_list',
              'list',
              ('method_call', ('var', 'obj'), 'get_list', []),
              132),
             ('expr', ('var', 'obj_list'), 0),
             ('decl',
              'obj_value_results',
              'list',
              ('method_call',
               ('var', 'obj'),
               'get_value_list',
               [('num', 1), ('num', 2)]),
              135),
             ('expr', ('var', 'obj_value_results'), 0)]}
