EXPECTED = {'functions': {'single_arg_jacobian': {'params': [('x',
                                                   ('tensor',
                                                    [('m', 'invariant')]))],
                                       'return_type': ('tensor',
                                                       [('n', 'invariant')]),
                                       'body': ('array',
                                                [('mul',
                                                  ('var', 'a'),
                                                  ('var', 'b')),
                                                 ('add',
                                                  ('var', 'a'),
                                                  ('var', 'b'))]),
                                       'has_loop': False,
                                       'statements': [('body_decl',
                                                       'a',
                                                       'ℝ',
                                                       ('index',
                                                        'x',
                                                        ('num', 0))),
                                                      ('body_decl',
                                                       'b',
                                                       'ℝ',
                                                       ('index',
                                                        'x',
                                                        ('num', 1)))]},
               'double_arg_jacobians': {'params': [('state',
                                                    ('tensor',
                                                     [(2, 'invariant')])),
                                                   ('theta',
                                                    ('tensor',
                                                     [(4, 'invariant')]))],
                                        'return_type': ('tensor',
                                                        [(2, 'invariant')]),
                                        'body': ('array',
                                                 [('var', 'dx'),
                                                  ('var', 'dy')]),
                                        'has_loop': False,
                                        'statements': [('body_decl',
                                                        'x',
                                                        'ℝ',
                                                        ('index',
                                                         'state',
                                                         ('num', 0))),
                                                       ('body_decl',
                                                        'y',
                                                        'ℝ',
                                                        ('index',
                                                         'state',
                                                         ('num', 1))),
                                                       ('body_decl',
                                                        'α',
                                                        'ℝ',
                                                        ('index',
                                                         'theta',
                                                         ('num', 0))),
                                                       ('body_decl',
                                                        'β',
                                                        'ℝ',
                                                        ('index',
                                                         'theta',
                                                         ('num', 1))),
                                                       ('body_decl',
                                                        'γ',
                                                        'ℝ',
                                                        ('index',
                                                         'theta',
                                                         ('num', 2))),
                                                       ('body_decl',
                                                        'δ',
                                                        'ℝ',
                                                        ('index',
                                                         'theta',
                                                         ('num', 3))),
                                                       ('body_decl',
                                                        'dx',
                                                        'ℝ',
                                                        ('sub',
                                                         ('mul',
                                                          ('var', 'α'),
                                                          ('var', 'x')),
                                                         ('mul',
                                                          ('mul',
                                                           ('var', 'β'),
                                                           ('var', 'x')),
                                                          ('var', 'y')))),
                                                       ('body_decl',
                                                        'dy',
                                                        'ℝ',
                                                        ('sub',
                                                         ('mul',
                                                          ('mul',
                                                           ('var', 'δ'),
                                                           ('var', 'x')),
                                                          ('var', 'y')),
                                                         ('mul',
                                                          ('var', 'γ'),
                                                          ('var', 'y'))))]},
               'three_arg_jacobians': {'params': [('a',
                                                   ('tensor',
                                                    [('m', 'invariant')])),
                                                  ('b',
                                                   ('tensor',
                                                    [('n', 'invariant')])),
                                                  ('c',
                                                   ('tensor',
                                                    [('o', 'invariant')]))],
                                       'return_type': ('tensor',
                                                       [('p', 'invariant')]),
                                       'body': ('array',
                                                [('var', 'y1'), ('var', 'y2')]),
                                       'has_loop': False,
                                       'statements': [('body_decl',
                                                       'x1',
                                                       'ℝ',
                                                       ('index',
                                                        'a',
                                                        ('num', 0))),
                                                      ('body_decl',
                                                       'x2',
                                                       'ℝ',
                                                       ('index',
                                                        'b',
                                                        ('num', 0))),
                                                      ('body_decl',
                                                       'x3',
                                                       'ℝ',
                                                       ('index',
                                                        'c',
                                                        ('num', 0))),
                                                      ('body_decl',
                                                       'y1',
                                                       'ℝ',
                                                       ('add',
                                                        ('mul',
                                                         ('var', 'x1'),
                                                         ('var', 'x2')),
                                                        ('var', 'x3'))),
                                                      ('body_decl',
                                                       'y2',
                                                       'ℝ',
                                                       ('add',
                                                        ('var', 'x1'),
                                                        ('mul',
                                                         ('var', 'x2'),
                                                         ('var', 'x3'))))]}},
 'classes': {},
 'program': [('func_def', 'single_arg_jacobian'),
             ('decl',
              'x',
              ('tensor', [(2, 'invariant')]),
              ('array', [('num', 2.0), ('num', 3.0)]),
              10),
             ('assign',
              'J',
              ('call', 'grad', [('var', 'single_arg_jacobian'), ('var', 'x')]),
              11),
             ('expr', ('var', 'J'), 0),
             ('func_def', 'double_arg_jacobians'),
             ('decl',
              'state',
              ('tensor', [(2, 'invariant')]),
              ('array', [('num', 1.0), ('num', 2.0)]),
              31),
             ('decl',
              'θ',
              ('tensor', [(4, 'invariant')]),
              ('array',
               [('num', 1.0), ('num', 0.3), ('num', 1.3), ('num', 0.5)]),
              32),
             ('assign',
              'J_state',
              ('call',
               'grad',
               [('call',
                 'double_arg_jacobians',
                 [('var', 'state'), ('var', 'θ')]),
                ('var', 'state')]),
              34),
             ('assign',
              'J_theta',
              ('call',
               'grad',
               [('call',
                 'double_arg_jacobians',
                 [('var', 'state'), ('var', 'θ')]),
                ('var', 'θ')]),
              35),
             ('expr', ('var', 'J_state'), 0),
             ('expr', ('var', 'J_theta'), 0),
             ('func_def', 'three_arg_jacobians'),
             ('decl',
              'a',
              ('tensor', [(2, 'invariant')]),
              ('array', [('num', 1.0), ('num', 2.0)]),
              53),
             ('decl',
              'b',
              ('tensor', [(2, 'invariant')]),
              ('array', [('num', 3.0), ('num', 4.0)]),
              54),
             ('decl',
              'c',
              ('tensor', [(2, 'invariant')]),
              ('array', [('num', 5.0), ('num', 6.0)]),
              55),
             ('assign',
              'J_a',
              ('call',
               'grad',
               [('call',
                 'three_arg_jacobians',
                 [('var', 'a'), ('var', 'b'), ('var', 'c')]),
                ('var', 'a')]),
              57),
             ('assign',
              'J_b',
              ('call',
               'grad',
               [('call',
                 'three_arg_jacobians',
                 [('var', 'a'), ('var', 'b'), ('var', 'c')]),
                ('var', 'b')]),
              58),
             ('assign',
              'J_c',
              ('call',
               'grad',
               [('call',
                 'three_arg_jacobians',
                 [('var', 'a'), ('var', 'b'), ('var', 'c')]),
                ('var', 'c')]),
              59),
             ('expr', ('var', 'J_a'), 0),
             ('expr', ('var', 'J_b'), 0),
             ('expr', ('var', 'J_c'), 0)]}
