EXPECTED = {'functions': {},
 'classes': {},
 'program': [('decl',
              'x',
              ('tensor', [(4, 'invariant')]),
              ('array',
               [('add', ('num', 1), ('complex', 2j)),
                ('add', ('num', 3), ('complex', 1j)),
                ('add', ('num', 0), ('complex', 4j)),
                ('add', ('num', 2), ('complex', 0j))]),
              7),
             ('assign', 'X', ('call', 'fft', [('var', 'x')]), 8),
             ('expr', ('var', 'X'), 0),
             ('expr', ('call', 'ifft', [('var', 'X')]), 0),
             ('decl',
              'x2',
              ('tensor', [(2, 'invariant'), (4, 'invariant')]),
              ('array',
               [('array',
                 [('num', 2.0), ('num', 0.0), ('num', 1.0), ('num', 3.0)]),
                ('array',
                 [('num', 4.0), ('num', 1.0), ('num', 0.0), ('num', 2.0)])]),
              13),
             ('assign', 'X2', ('call', 'fft2', [('var', 'x2')]), 17),
             ('expr', ('var', 'X2'), 0),
             ('expr', ('call', 'ifft2', [('var', 'X2')]), 0),
             ('decl',
              'x3',
              ('tensor',
               [(2, 'invariant'), (2, 'invariant'), (4, 'invariant')]),
              ('array',
               [('array',
                 [('array',
                   [('num', 1.0), ('num', 2.0), ('num', 3.0), ('num', 4.0)]),
                  ('array',
                   [('num', 5.0), ('num', 6.0), ('num', 7.0), ('num', 8.0)])]),
                ('array',
                 [('array',
                   [('num', 9.0), ('num', 10.0), ('num', 11.0), ('num', 12.0)]),
                  ('array',
                   [('num', 13.0),
                    ('num', 14.0),
                    ('num', 15.0),
                    ('num', 16.0)])])]),
              22),
             ('assign', 'X3', ('call', 'fftn', [('var', 'x3')]), 26),
             ('expr', ('var', 'X3'), 0),
             ('expr', ('call', 'ifftn', [('var', 'X3')]), 0),
             ('decl',
              'xr',
              ('tensor', [(8, 'invariant')]),
              ('array',
               [('num', 3.0),
                ('num', 1.0),
                ('num', 4.0),
                ('num', 1.0),
                ('num', 5.0),
                ('num', 9.0),
                ('num', 2.0),
                ('num', 6.0)]),
              36),
             ('assign', 'Xr', ('call', 'rfft', [('var', 'xr')]), 37),
             ('expr', ('var', 'Xr'), 0),
             ('expr', ('call', 'irfft', [('var', 'Xr')]), 0),
             ('decl',
              'xr2',
              ('tensor', [(2, 'invariant'), (4, 'invariant')]),
              ('array',
               [('array',
                 [('num', 1.0), ('num', 0.0), ('num', 2.0), ('num', 1.0)]),
                ('array',
                 [('num', 3.0), ('num', 1.0), ('num', 0.0), ('num', 2.0)])]),
              42),
             ('assign', 'Xr2', ('call', 'rfft2', [('var', 'xr2')]), 46),
             ('expr', ('var', 'Xr2'), 0),
             ('expr', ('call', 'irfft2', [('var', 'Xr2')]), 0),
             ('decl',
              'xr3',
              ('tensor',
               [(2, 'invariant'), (2, 'invariant'), (4, 'invariant')]),
              ('array',
               [('array',
                 [('array',
                   [('num', 2.0), ('num', 1.0), ('num', 0.0), ('num', 3.0)]),
                  ('array',
                   [('num', 1.0), ('num', 2.0), ('num', 1.0), ('num', 0.0)])]),
                ('array',
                 [('array',
                   [('num', 0.0), ('num', 1.0), ('num', 2.0), ('num', 1.0)]),
                  ('array',
                   [('num', 3.0),
                    ('num', 0.0),
                    ('num', 1.0),
                    ('num', 2.0)])])]),
              51),
             ('assign', 'Xr3', ('call', 'rfftn', [('var', 'xr3')]), 55),
             ('expr', ('var', 'Xr3'), 0),
             ('expr', ('call', 'irfftn', [('var', 'Xr3')]), 0),
             ('decl',
              's',
              ('tensor', [(4, 'invariant')]),
              ('array',
               [('num', 1.0), ('num', 2.0), ('num', 0.0), ('num', 3.0)]),
              65),
             ('decl',
              't',
              ('tensor', [(4, 'invariant')]),
              ('array',
               [('add', ('num', 4), ('complex', 0j)),
                ('add', ('num', 0), ('complex', 1j)),
                ('add', ('num', 2), ('complex', 3j)),
                ('add', ('num', 0), ('complex', 0j))]),
              66),
             ('assign', 'spec', ('call', 'fft', [('var', 's')]), 68),
             ('decl',
              'diff',
              ('tensor', [(4, 'invariant')]),
              ('sub', ('var', 'spec'), ('var', 't')),
              69),
             ('assign',
              'loss',
              ('call',
               'sum',
               [('mul',
                 ('call', 'abs', [('var', 'diff')]),
                 ('call', 'abs', [('var', 'diff')]))]),
              70),
             ('assign',
              'g',
              ('call', 'grad', [('var', 'loss'), ('var', 's')]),
              71),
             ('decl',
              's2',
              ('tensor', [(4, 'invariant')]),
              ('sub', ('var', 's'), ('mul', ('num', 0.05), ('var', 'g'))),
              74),
             ('assign', 'spec2', ('call', 'fft', [('var', 's2')]), 75),
             ('decl',
              'diff2',
              ('tensor', [(4, 'invariant')]),
              ('sub', ('var', 'spec2'), ('var', 't')),
              76),
             ('assign',
              'loss2',
              ('call',
               'sum',
               [('mul',
                 ('call', 'abs', [('var', 'diff2')]),
                 ('call', 'abs', [('var', 'diff2')]))]),
              77),
             ('expr', ('var', 'g'), 0),
             ('expr', ('var', 'loss'), 0),
             ('expr', ('var', 'loss2'), 0)]}
