EXPECTED = {'functions': {'transform': {'params': [('M',
                                         ('tensor',
                                          'ℝ',
                                          [(2, 'invariant'),
                                           (2, 'invariant')]))],
                             'return_type': ('tensor',
                                             'ℝ',
                                             [(2, 'invariant'),
                                              (2, 'invariant')]),
                             'body': ('add',
                                      ('mul', ('var', 'M'), ('var', 'scale')),
                                      ('num', 1.0)),
                             'has_loop': False,
                             'statements': []}},
 'classes': {},
 'program': [('decl',
              'A',
              ('tensor', 'ℝ', [(2, 'invariant'), (3, 'invariant')]),
              ('array',
               [('array', [('num', 1.0), ('num', 2.0), ('num', 3.0)]),
                ('array', [('num', 4.0), ('num', 5.0), ('num', 6.0)])]),
              2),
             ('expr', ('var', 'A'), 0),
             ('decl',
              'B',
              ('tensor', 'ℝ', [(2, 'invariant'), (3, 'invariant')]),
              ('mul', ('num', 2.0), ('var', 'A')),
              6),
             ('expr', ('var', 'B'), 0),
             ('decl',
              'C',
              ('tensor', 'ℝ', [(2, 'invariant'), (3, 'invariant')]),
              ('add', ('var', 'A'), ('var', 'B')),
              10),
             ('expr', ('var', 'C'), 0),
             ('decl', 'scale', 'ℝ', ('num', 2.0), 13),
             ('func_def', 'transform'),
             ('decl',
              'X',
              ('tensor', 'ℝ', [(2, 'invariant'), (2, 'invariant')]),
              ('array',
               [('array', [('num', 1.0), ('num', 2.0)]),
                ('array', [('num', 3.0), ('num', 4.0)])]),
              18),
             ('decl',
              'result',
              ('tensor', 'ℝ', [(2, 'invariant'), (2, 'invariant')]),
              ('call', 'transform', [('var', 'X')]),
              19),
             ('expr', ('var', 'result'), 0),
             ('decl',
              'a',
              ('tensor', 'ℝ', [(3, 'invariant')]),
              ('array', [('num', 1.0), ('num', 2.0), ('num', 3.0)]),
              23),
             ('decl',
              'b',
              ('tensor', 'ℝ', [(3, 'invariant')]),
              ('array', [('num', 4.0), ('num', 5.0), ('num', 6.0)]),
              24),
             ('decl',
              'result',
              'ℝ',
              ('matmul', ('var', 'a'), ('var', 'b')),
              26),
             ('expr', ('var', 'result'), 0),
             ('decl',
              'A',
              ('tensor', 'ℝ', [(2, 'invariant'), (3, 'invariant')]),
              ('array',
               [('array', [('num', 1.0), ('num', 2.0), ('num', 3.0)]),
                ('array', [('num', 4.0), ('num', 5.0), ('num', 6.0)])]),
              30),
             ('decl',
              'x',
              ('tensor', 'ℝ', [(3, 'invariant')]),
              ('array', [('num', 1.0), ('num', 2.0), ('num', 3.0)]),
              31),
             ('decl',
              'result',
              ('tensor', 'ℝ', [(2, 'invariant')]),
              ('matmul', ('var', 'A'), ('var', 'x')),
              33),
             ('expr', ('var', 'result'), 0)]}
