EXPECTED = {'functions': {'magnitude': {'params': [('z', 'ℂ')],
                             'return_type': 'ℂ',
                             'body': ('call', 'abs', [('var', 'z')]),
                             'has_loop': False,
                             'statements': []}},
 'classes': {},
 'program': [('decl', 'x', 'ℂ', ('add', ('num', 3), ('complex', 1j)), 4),
             ('decl', 'y', 'ℂ', ('add', ('num', 5), ('complex', 3j)), 5),
             ('expr', ('var', 'x'), 0),
             ('expr', ('var', 'y'), 0),
             ('decl',
              'complex_add',
              'ℂ',
              ('add', ('var', 'x'), ('var', 'y')),
              12),
             ('expr', ('var', 'complex_add'), 0),
             ('expr', ('sub', ('var', 'x'), ('var', 'y')), 0),
             ('decl',
              'complex_mul',
              'ℂ',
              ('mul', ('var', 'x'), ('var', 'y')),
              31),
             ('expr', ('var', 'complex_mul'), 0),
             ('func_def', 'magnitude'),
             ('expr', ('call', 'magnitude', [('var', 'x')]), 0),
             ('decl',
              'array_imag',
              ('tensor', 'ℂ', [(3, 'invariant')]),
              ('array', [('complex', 1j), ('complex', 2j), ('complex', 3j)]),
              58),
             ('decl',
              'array_complex',
              ('tensor', 'ℂ', [(3, 'invariant')]),
              ('array',
               [('add', ('num', 1), ('complex', 9j)),
                ('add', ('num', 7), ('complex', 2j)),
                ('add', ('num', 3), ('complex', 5j))]),
              60),
             ('decl',
              'nested_complex',
              ('tensor', 'ℂ', [(2, 'invariant'), (2, 'invariant')]),
              ('array',
               [('array',
                 [('add', ('num', 1), ('complex', 2j)),
                  ('add', ('num', 3), ('complex', 4j))]),
                ('array',
                 [('add', ('num', 4), ('complex', 9j)),
                  ('add', ('num', 7), ('complex', 2j))])]),
              62),
             ('expr', ('var', 'array_imag'), 0),
             ('expr', ('var', 'array_complex'), 0),
             ('expr', ('var', 'nested_complex'), 0)]}
