EXPECTED = {'functions': {'f_x': {'params': [('x', 'ℝ')],
                       'return_type': 'ℝ',
                       'body': ('pow', ('var', 'x'), ('num', 2)),
                       'has_loop': False,
                       'statements': []},
               'fact': {'params': [('n', 'ℝ')],
                        'return_type': 'ℝ',
                        'body': None,
                        'has_loop': False,
                        'statements': [('body_if_else_return',
                                        ('cond_eq', ('var', 'n'), ('num', 0.0)),
                                        ('num', 1.0),
                                        ('mul',
                                         ('var', 'n'),
                                         ('call',
                                          'fact',
                                          [('sub',
                                            ('var', 'n'),
                                            ('num', 1.0))])))]},
               'f': {'params': [('x', 'ℝ')],
                     'return_type': 'ℝ',
                     'body': None,
                     'has_loop': False,
                     'statements': [('body_if_else_return',
                                     ('cond_gt', ('var', 'x'), ('num', 0)),
                                     ('call', 'cos', [('var', 'x')]),
                                     ('call', 'sin', [('var', 'x')]))]},
               'torch_funcs_with_scalar_R': {'params': [('x', 'ℝ')],
                                             'return_type': ('tensor',
                                                             [('m',
                                                               'invariant')]),
                                             'body': ('array',
                                                      [('var', 'result_sin'),
                                                       ('var', 'result_cos'),
                                                       ('var', 'result_exp'),
                                                       ('var', 'result_sqrt'),
                                                       ('var', 'result_log'),
                                                       ('var', 'result_abs')]),
                                             'has_loop': False,
                                             'statements': [('body_decl',
                                                             'result_sin',
                                                             'ℝ',
                                                             ('call',
                                                              'sin',
                                                              [('var', 'x')])),
                                                            ('body_decl',
                                                             'result_cos',
                                                             'ℝ',
                                                             ('call',
                                                              'cos',
                                                              [('var', 'x')])),
                                                            ('body_decl',
                                                             'result_exp',
                                                             'ℝ',
                                                             ('call',
                                                              'exp',
                                                              [('var', 'x')])),
                                                            ('body_decl',
                                                             'result_sqrt',
                                                             'ℝ',
                                                             ('call',
                                                              'sqrt',
                                                              [('var', 'x')])),
                                                            ('body_decl',
                                                             'result_log',
                                                             'ℝ',
                                                             ('call',
                                                              'log',
                                                              [('var', 'x')])),
                                                            ('body_decl',
                                                             'result_abs',
                                                             'ℝ',
                                                             ('call',
                                                              'abs',
                                                              [('var',
                                                                'x')]))]},
               'superbee': {'params': [('r', ('tensor', [('m', 'invariant')]))],
                            'return_type': ('tensor', [('m', 'invariant')]),
                            'body': ('var', 'phi'),
                            'has_loop': False,
                            'statements': [('body_assign',
                                            's1',
                                            ('mul',
                                             ('num', 0.5),
                                             ('sub',
                                              ('add',
                                               ('mul',
                                                ('num', 2.0),
                                                ('var', 'r')),
                                               ('num', 1.0)),
                                              ('call',
                                               'abs',
                                               [('sub',
                                                 ('mul',
                                                  ('num', 2.0),
                                                  ('var', 'r')),
                                                 ('num', 1.0))])))),
                                           ('body_assign',
                                            's2',
                                            ('mul',
                                             ('num', 0.5),
                                             ('sub',
                                              ('add',
                                               ('var', 'r'),
                                               ('num', 2.0)),
                                              ('call',
                                               'abs',
                                               [('sub',
                                                 ('var', 'r'),
                                                 ('num', 2.0))])))),
                                           ('body_assign',
                                            's3',
                                            ('mul',
                                             ('num', 0.5),
                                             ('add',
                                              ('add',
                                               ('var', 's1'),
                                               ('var', 's2')),
                                              ('call',
                                               'abs',
                                               [('sub',
                                                 ('var', 's1'),
                                                 ('var', 's2'))])))),
                                           ('body_assign',
                                            'phi',
                                            ('mul',
                                             ('num', 0.5),
                                             ('add',
                                              ('var', 's3'),
                                              ('call',
                                               'abs',
                                               [('var', 's3')]))))]},
               'gaussian_solve': {'params': [('A',
                                              ('tensor',
                                               [('m', 'invariant'),
                                                ('n', 'invariant')])),
                                             ('b',
                                              ('tensor',
                                               [('n', 'invariant')]))],
                                  'return_type': ('tensor',
                                                  [('m', 'invariant')]),
                                  'body': ('var', 'x'),
                                  'has_loop': False,
                                  'statements': [('body_decl',
                                                  'a_row',
                                                  'ℝ',
                                                  ('call',
                                                   'get_2d_array_num_rows',
                                                   [('var', 'A')])),
                                                 ('body_decl',
                                                  'a_col',
                                                  'ℝ',
                                                  ('call',
                                                   'get_2d_array_num_cols',
                                                   [('var', 'A')])),
                                                 ('body_decl',
                                                  'new_col',
                                                  'ℝ',
                                                  ('add',
                                                   ('var', 'a_col'),
                                                   ('num', 1))),
                                                 ('body_decl',
                                                  'aug',
                                                  ('tensor',
                                                   [('a_row', 'invariant'),
                                                    ('new_col', 'invariant')]),
                                                  ('call',
                                                   'zero_2d_array',
                                                   [('var', 'a_row'),
                                                    ('var', 'new_col')])),
                                                 ('body_for_range',
                                                  'i',
                                                  ('num', 0),
                                                  ('var', 'a_row'),
                                                  [('loop_for_range',
                                                    'c',
                                                    ('num', 0),
                                                    ('var', 'a_col'),
                                                    [('loop_index_assign_nd',
                                                      'aug',
                                                      [('index_item',
                                                        ('imaginary',)),
                                                       ('index_item',
                                                        ('var', 'c'))],
                                                      ('indexN',
                                                       'A',
                                                       [('index_item',
                                                         ('imaginary',)),
                                                        ('index_item',
                                                         ('var', 'c'))]))]),
                                                   ('loop_index_assign_nd',
                                                    'aug',
                                                    [('index_item',
                                                      ('imaginary',)),
                                                     ('index_item',
                                                      ('var', 'a_col'))],
                                                    ('index',
                                                     'b',
                                                     ('imaginary',)))]),
                                                 ('body_for_range',
                                                  'i',
                                                  ('num', 0),
                                                  ('var', 'a_row'),
                                                  [('loop_assign',
                                                    'max_row',
                                                    ('imaginary',)),
                                                   ('loop_for_range',
                                                    'k',
                                                    ('add',
                                                     ('imaginary',),
                                                     ('num', 1)),
                                                    ('var', 'a_row'),
                                                    [('loop_if',
                                                      ('cond_gt',
                                                       ('call',
                                                        'abs',
                                                        [('indexN',
                                                          'aug',
                                                          [('index_item',
                                                            ('var', 'k')),
                                                           ('index_item',
                                                            ('imaginary',))])]),
                                                       ('call',
                                                        'abs',
                                                        [('indexN',
                                                          'aug',
                                                          [('index_item',
                                                            ('var', 'max_row')),
                                                           ('index_item',
                                                            ('imaginary',))])])),
                                                      [('loop_assign',
                                                        'max_row',
                                                        ('var', 'k'))])]),
                                                   ('loop_assign',
                                                    'pivot_row',
                                                    ('call',
                                                     'zero_1d_array',
                                                     [('var', 'new_col')])),
                                                   ('loop_assign',
                                                    'displaced_row',
                                                    ('call',
                                                     'zero_1d_array',
                                                     [('var', 'new_col')])),
                                                   ('loop_for_range',
                                                    'c',
                                                    ('num', 0),
                                                    ('var', 'new_col'),
                                                    [('loop_index_assign_nd',
                                                      'pivot_row',
                                                      [('index_item',
                                                        ('var', 'c'))],
                                                      ('indexN',
                                                       'aug',
                                                       [('index_item',
                                                         ('var', 'max_row')),
                                                        ('index_item',
                                                         ('var', 'c'))])),
                                                     ('loop_index_assign_nd',
                                                      'displaced_row',
                                                      [('index_item',
                                                        ('var', 'c'))],
                                                      ('indexN',
                                                       'aug',
                                                       [('index_item',
                                                         ('imaginary',)),
                                                        ('index_item',
                                                         ('var', 'c'))]))]),
                                                   ('loop_assign',
                                                    'aug_next',
                                                    ('call',
                                                     'zero_2d_array',
                                                     [('var', 'a_row'),
                                                      ('var', 'new_col')])),
                                                   ('loop_for_range',
                                                    'row_idx',
                                                    ('num', 0),
                                                    ('var', 'a_row'),
                                                    [('loop_if_else',
                                                      ('cond_lt',
                                                       ('var', 'row_idx'),
                                                       ('imaginary',)),
                                                      [('loop_for_range',
                                                        'c',
                                                        ('num', 0),
                                                        ('var', 'new_col'),
                                                        [('loop_index_assign_nd',
                                                          'aug_next',
                                                          [('index_item',
                                                            ('var', 'row_idx')),
                                                           ('index_item',
                                                            ('var', 'c'))],
                                                          ('indexN',
                                                           'aug',
                                                           [('index_item',
                                                             ('var',
                                                              'row_idx')),
                                                            ('index_item',
                                                             ('var',
                                                              'c'))]))])],
                                                      [('loop_if_else',
                                                        ('cond_eq',
                                                         ('var', 'row_idx'),
                                                         ('imaginary',)),
                                                        [('loop_for_range',
                                                          'c',
                                                          ('num', 0),
                                                          ('var', 'new_col'),
                                                          [('loop_index_assign_nd',
                                                            'aug_next',
                                                            [('index_item',
                                                              ('var',
                                                               'row_idx')),
                                                             ('index_item',
                                                              ('var', 'c'))],
                                                            ('index',
                                                             'pivot_row',
                                                             ('var', 'c')))])],
                                                        [('loop_assign',
                                                          'source_row',
                                                          ('call',
                                                           'zero_1d_array',
                                                           [('var',
                                                             'new_col')])),
                                                         ('loop_if_else',
                                                          ('cond_eq',
                                                           ('var', 'row_idx'),
                                                           ('var', 'max_row')),
                                                          [('loop_for_range',
                                                            'c',
                                                            ('num', 0),
                                                            ('var', 'new_col'),
                                                            [('loop_index_assign_nd',
                                                              'source_row',
                                                              [('index_item',
                                                                ('var', 'c'))],
                                                              ('index',
                                                               'displaced_row',
                                                               ('var',
                                                                'c')))])],
                                                          [('loop_for_range',
                                                            'c',
                                                            ('num', 0),
                                                            ('var', 'new_col'),
                                                            [('loop_index_assign_nd',
                                                              'source_row',
                                                              [('index_item',
                                                                ('var', 'c'))],
                                                              ('indexN',
                                                               'aug',
                                                               [('index_item',
                                                                 ('var',
                                                                  'row_idx')),
                                                                ('index_item',
                                                                 ('var',
                                                                  'c'))]))])]),
                                                         ('loop_assign',
                                                          'factor',
                                                          ('div',
                                                           ('index',
                                                            'source_row',
                                                            ('imaginary',)),
                                                           ('index',
                                                            'pivot_row',
                                                            ('imaginary',)))),
                                                         ('loop_for_range',
                                                          'c',
                                                          ('num', 0),
                                                          ('var', 'new_col'),
                                                          [('loop_index_assign_nd',
                                                            'aug_next',
                                                            [('index_item',
                                                              ('var',
                                                               'row_idx')),
                                                             ('index_item',
                                                              ('var', 'c'))],
                                                            ('sub',
                                                             ('index',
                                                              'source_row',
                                                              ('var', 'c')),
                                                             ('mul',
                                                              ('var', 'factor'),
                                                              ('index',
                                                               'pivot_row',
                                                               ('var',
                                                                'c')))))])])])]),
                                                   ('loop_assign',
                                                    'aug',
                                                    ('var', 'aug_next'))]),
                                                 ('body_decl',
                                                  'x',
                                                  ('tensor',
                                                   [('a_col', 'invariant')]),
                                                  ('call',
                                                   'zero_1d_array',
                                                   [('var', 'a_col')])),
                                                 ('body_for_range',
                                                  'i',
                                                  ('num', 0),
                                                  ('var', 'a_col'),
                                                  [('loop_assign',
                                                    'idx',
                                                    ('sub',
                                                     ('sub',
                                                      ('var', 'a_col'),
                                                      ('num', 1)),
                                                     ('imaginary',))),
                                                   ('loop_assign',
                                                    'total',
                                                    ('indexN',
                                                     'aug',
                                                     [('index_item',
                                                       ('var', 'idx')),
                                                      ('index_item',
                                                       ('var', 'a_col'))])),
                                                   ('loop_for_range',
                                                    'j',
                                                    ('add',
                                                     ('var', 'idx'),
                                                     ('num', 1)),
                                                    ('var', 'a_row'),
                                                    [('loop_assign',
                                                      'total',
                                                      ('sub',
                                                       ('var', 'total'),
                                                       ('mul',
                                                        ('indexN',
                                                         'aug',
                                                         [('index_item',
                                                           ('var', 'idx')),
                                                          ('index_item',
                                                           ('var', 'j'))]),
                                                        ('index',
                                                         'x',
                                                         ('var', 'j')))))]),
                                                   ('loop_assign',
                                                    'solved_val',
                                                    ('div',
                                                     ('var', 'total'),
                                                     ('indexN',
                                                      'aug',
                                                      [('index_item',
                                                        ('var', 'idx')),
                                                       ('index_item',
                                                        ('var', 'idx'))]))),
                                                   ('loop_assign',
                                                    'x_next',
                                                    ('call',
                                                     'zero_1d_array',
                                                     [('var', 'a_col')])),
                                                   ('loop_for_range',
                                                    'c',
                                                    ('num', 0),
                                                    ('var', 'a_col'),
                                                    [('loop_if_else',
                                                      ('cond_eq',
                                                       ('var', 'c'),
                                                       ('var', 'idx')),
                                                      [('loop_index_assign_nd',
                                                        'x_next',
                                                        [('index_item',
                                                          ('var', 'c'))],
                                                        ('var', 'solved_val'))],
                                                      [('loop_index_assign_nd',
                                                        'x_next',
                                                        [('index_item',
                                                          ('var', 'c'))],
                                                        ('index',
                                                         'x',
                                                         ('var', 'c')))])]),
                                                   ('loop_assign',
                                                    'x',
                                                    ('var', 'x_next'))])]},
               'get_2d_array_num_cols': {'params': [('x',
                                                     ('tensor',
                                                      [('m', 'invariant'),
                                                       ('n', 'invariant')]))],
                                         'return_type': 'ℝ',
                                         'body': ('call',
                                                  'get_1d_array_length',
                                                  [('index', 'x', ('num', 0))]),
                                         'has_loop': False,
                                         'statements': []},
               'get_2d_array_num_rows': {'params': [('x',
                                                     ('tensor',
                                                      [('m', 'invariant'),
                                                       ('n', 'invariant')]))],
                                         'return_type': 'ℝ',
                                         'body': ('var', 'total'),
                                         'has_loop': False,
                                         'statements': [('body_decl',
                                                         'total',
                                                         'ℝ',
                                                         ('num', 0)),
                                                        ('body_decl',
                                                         'temp',
                                                         'ℝ',
                                                         ('num', 0)),
                                                        ('body_for',
                                                         'i',
                                                         [('loop_assign',
                                                           'temp',
                                                           ('index',
                                                            'x',
                                                            ('imaginary',))),
                                                          ('loop_pluseq',
                                                           'total',
                                                           ('num', 1))],
                                                         ['x'])]},
               'get_1d_array_length': {'params': [('x',
                                                   ('tensor',
                                                    [('m', 'invariant')]))],
                                       'return_type': 'ℝ',
                                       'body': ('var', 'total'),
                                       'has_loop': False,
                                       'statements': [('body_decl',
                                                       'total',
                                                       'ℝ',
                                                       ('num', 0)),
                                                      ('body_decl',
                                                       'temp',
                                                       'ℝ',
                                                       ('num', 0)),
                                                      ('body_for',
                                                       'i',
                                                       [('loop_assign',
                                                         'temp',
                                                         ('index',
                                                          'x',
                                                          ('imaginary',))),
                                                        ('loop_pluseq',
                                                         'total',
                                                         ('num', 1))],
                                                       ['x'])]},
               'zero_2d_array': {'params': [('rows', 'ℝ'), ('cols', 'ℝ')],
                                 'return_type': ('tensor',
                                                 [('m', 'invariant'),
                                                  ('n', 'invariant')]),
                                 'body': ('var', 'results'),
                                 'has_loop': False,
                                 'statements': [('body_decl',
                                                 'results',
                                                 ('tensor',
                                                  [('rows', 'invariant'),
                                                   ('cols', 'invariant')]),
                                                 ('for_expr',
                                                  'i',
                                                  ('var', 'rows'),
                                                  ('for_expr',
                                                   'j',
                                                   ('var', 'cols'),
                                                   ('mul',
                                                    ('var', 'j'),
                                                    ('num', 0)))))]},
               'zero_1d_array': {'params': [('len', 'ℝ')],
                                 'return_type': ('tensor',
                                                 [('m', 'invariant')]),
                                 'body': ('var', 'results'),
                                 'has_loop': False,
                                 'statements': [('body_decl',
                                                 'results',
                                                 ('tensor',
                                                  [('len', 'invariant')]),
                                                 ('for_expr',
                                                  'i',
                                                  ('var', 'len'),
                                                  ('mul',
                                                   ('imaginary',),
                                                   ('num', 0))))]}},
 'classes': {'ExampleClass': {'class_params': [],
                              'fields': [],
                              'methods': [{'name': 'class_method',
                                           'params': [],
                                           'return_type': 'ℝ',
                                           'statements': [],
                                           'body': ('num', 1)}]}},
 'program': [('func_def', 'fact'),
             ('decl', 'x', 'ℝ', ('num', 1.0), 7),
             ('decl', 'fact_results', 'ℝ', ('call', 'fact', [('var', 'x')]), 8),
             ('expr', ('var', 'fact_results'), 0),
             ('func_def', 'f'),
             ('func_def', 'torch_funcs_with_scalar_R'),
             ('decl',
              'torch_funcs_results',
              ('tensor', [(6, 'invariant')]),
              ('call', 'torch_funcs_with_scalar_R', [('var', 'x')]),
              17),
             ('expr', ('var', 'torch_funcs_results'), 0),
             ('decl', 'f_results', 'ℝ', ('call', 'f', [('var', 'x')]), 20),
             ('expr', ('var', 'f_results'), 0),
             ('class_def', 'ExampleClass'),
             ('decl',
              'obj_example_class',
              ('struct_type', 'ExampleClass'),
              ('call', 'ExampleClass', []),
              30),
             ('decl',
              'class_value',
              'ℝ',
              ('method_call', ('var', 'obj_example_class'), 'class_method', []),
              31),
             ('expr', ('var', 'class_value'), 0),
             ('decl',
              'v',
              ('tensor', [(3, 'contravariant')]),
              ('array', [('num', 1.0), ('num', 2.0), ('num', 3.0)]),
              312),
             ('for_loop_range',
              'i',
              ('num', 0),
              ('num', 3),
              [('for_if',
                ('cond_gt', ('index', 'v', ('imaginary',)), ('num', 2)),
                [('for_index_assign_nd',
                  'v',
                  [('index_item', ('imaginary',))],
                  ('mul', ('index', 'v', ('imaginary',)), ('num', 2)))])],
              42),
             ('expr', ('var', 'v'), 0),
             ('func_def', 'f_x'),
             ('decl',
              'grad_f_x',
              'ℝ',
              ('call', 'grad', [('var', 'f_x'), ('index', 'v', ('num', 2))]),
              51),
             ('expr', ('var', 'grad_f_x'), 0),
             ('func_def', 'superbee'),
             ('decl',
              'r',
              ('tensor', [(5, 'invariant')]),
              ('array',
               [('neg', ('num', 1.0)),
                ('num', 0.0),
                ('num', 0.5),
                ('num', 1.0),
                ('num', 2.0)]),
              62),
             ('decl',
              'φ',
              ('tensor', [(5, 'invariant')]),
              ('call', 'superbee', [('var', 'r')]),
              63),
             ('expr', ('var', 'φ'), 0),
             ('func_def', 'gaussian_solve'),
             ('func_def', 'get_2d_array_num_cols'),
             ('func_def', 'get_2d_array_num_rows'),
             ('func_def', 'get_1d_array_length'),
             ('func_def', 'zero_2d_array'),
             ('func_def', 'zero_1d_array'),
             ('decl',
              'A',
              ('tensor', [(3, 'invariant'), (3, 'invariant')]),
              ('array',
               [('array', [('num', 1), ('num', 2), ('num', 1)]),
                ('array', [('num', 3), ('num', 1), ('neg', ('num', 1))]),
                ('array', [('num', 2), ('neg', ('num', 1)), ('num', 1)])]),
              73),
             ('decl',
              'b',
              ('tensor', [(3, 'invariant')]),
              ('array', [('num', 8), ('num', 2), ('num', 3)]),
              78),
             ('decl',
              'gaussian_results',
              ('tensor', [(3, 'invariant')]),
              ('call', 'gaussian_solve', [('var', 'A'), ('var', 'b')]),
              80),
             ('expr', ('var', 'gaussian_results'), 0)]}
