EXPECTED = {'functions': {},
 'classes': {},
 'program': [('decl', 'a', 'ℤ', ('num', 10), 4),
             ('decl', 'b', 'ℤ', ('num', 3), 5),
             ('assign', 'z_add', ('add', ('var', 'a'), ('var', 'b')), 6),
             ('decl',
              'z_array',
              ('tensor', 'ℤ', [(2, 'invariant')]),
              ('array', [('num', 1), ('num', 2)]),
              7),
             ('expr', ('var', 'a'), 0),
             ('expr', ('var', 'b'), 0),
             ('expr', ('var', 'z_add'), 0),
             ('expr', ('var', 'z_array'), 0),
             ('decl', 'x', 'ℝ', ('num', 3.14), 18),
             ('decl', 'y', 'ℝ', ('num', 2), 19),
             ('decl', 'r_mul', 'ℝ', ('mul', ('var', 'x'), ('var', 'y')), 20),
             ('expr', ('var', 'x'), 0),
             ('expr', ('var', 'y'), 0),
             ('expr', ('var', 'r_mul'), 0),
             ('decl', 'z_number', 'ℤ', ('num', 1), 30),
             ('decl', 'r_number', 'ℝ', ('num', 2.0), 31),
             ('assign',
              'result',
              ('mul', ('var', 'z_number'), ('var', 'r_number')),
              32),
             ('expr', ('var', 'result'), 0),
             ('decl', 'neg_int', 'ℤ', ('neg', ('num', 7)), 39),
             ('decl', 'neg_float', 'ℝ', ('neg', ('num', 3.14)), 40),
             ('decl',
              'neg_array',
              ('tensor', 'ℝ', [(3, 'invariant')]),
              ('array',
               [('neg', ('num', 1)),
                ('neg', ('num', 2.0)),
                ('neg', ('num', 3))]),
              41),
             ('expr', ('var', 'neg_int'), 0),
             ('expr', ('var', 'neg_float'), 0),
             ('expr', ('var', 'neg_array'), 0)]}
