EXPECTED = {'functions': {},
 'classes': {},
 'program': [('decl', 'empty_string', 'String', ('string', ''), 21),
             ('decl', 'name', 'String', ('string', 'Physika'), 22),
             ('decl', 'msg', 'String', ('string', 'Hello, World!'), 23),
             ('expr', ('call', 'print', [('var', 'empty_string')]), 0),
             ('expr', ('call', 'print', [('var', 'name')]), 0),
             ('expr', ('call', 'print', [('var', 'msg')]), 0),
             ('decl', 'first_name', 'String', ('string', 'Physika'), 34),
             ('decl', 'last_name', 'String', ('string', 'Language'), 35),
             ('decl',
              'full_name',
              'String',
              ('add',
               ('add', ('var', 'first_name'), ('string', ' ')),
               ('var', 'last_name')),
              37),
             ('expr', ('call', 'print', [('var', 'full_name')]), 0),
             ('decl',
              'first_character',
              'String',
              ('index', 'name', ('num', 0)),
              47),
             ('decl',
              'third_character',
              'String',
              ('index', 'name', ('num', 2)),
              48),
             ('expr', ('call', 'print', [('var', 'first_character')]), 0),
             ('expr', ('call', 'print', [('var', 'third_character')]), 0),
             ('decl',
              'first_part',
              'String',
              ('indexN', 'full_name', [('slice_item', None, ('num', 7))]),
              58),
             ('decl',
              'last_part',
              'String',
              ('indexN', 'full_name', [('slice_item', ('num', 8), None)]),
              59),
             ('expr', ('call', 'print', [('var', 'first_part')]), 0),
             ('expr', ('call', 'print', [('var', 'last_part')]), 0)]}
