EXPECTED = {'functions': {},
 'classes': {},
 'program': [('decl',
              'xc',
              ('tensor', [(4, 'invariant')]),
              ('array',
               [('add', ('num', 1), ('complex', 2j)),
                ('add', ('num', 3), ('complex', 1j)),
                ('add', ('num', 0), ('complex', 4j)),
                ('add', ('num', 2), ('complex', 0j))]),
              20),
             ('assign', 'Xc', ('call', 'fft', [('var', 'xc')]), 21),
             ('expr', ('var', 'Xc'), 0),
             ('assign', 'xc_rec', ('call', 'ifft', [('var', 'Xc')]), 24),
             ('expr', ('var', 'xc_rec'), 0),
             ('decl',
              'x2',
              ('tensor', [(2, 'invariant'), (4, 'invariant')]),
              ('array',
               [('array',
                 [('num', 2.0), ('num', 0.0), ('num', 1.0), ('num', 3.0)]),
                ('array',
                 [('num', 4.0), ('num', 1.0), ('num', 0.0), ('num', 2.0)])]),
              27),
             ('assign', 'X2', ('call', 'fft2', [('var', 'x2')]), 31),
             ('expr', ('var', 'X2'), 0),
             ('assign', 'x2_rec', ('call', 'ifft2', [('var', 'X2')]), 34),
             ('expr', ('var', 'x2_rec'), 0),
             ('decl',
              'x3',
              ('tensor',
               [(2, 'invariant'), (2, 'invariant'), (4, 'invariant')]),
              ('array',
               [('array',
                 [('array',
                   [('num', 1.0), ('num', 2.0), ('num', 3.0), ('num', 4.0)]),
                  ('array',
                   [('num', 5.0), ('num', 6.0), ('num', 7.0), ('num', 8.0)])]),
                ('array',
                 [('array',
                   [('num', 9.0), ('num', 10.0), ('num', 11.0), ('num', 12.0)]),
                  ('array',
                   [('num', 13.0),
                    ('num', 14.0),
                    ('num', 15.0),
                    ('num', 16.0)])])]),
              37),
             ('assign', 'X3', ('call', 'fftn', [('var', 'x3')]), 41),
             ('expr', ('var', 'X3'), 0),
             ('assign', 'x3_rec', ('call', 'ifftn', [('var', 'X3')]), 44),
             ('expr', ('var', 'x3_rec'), 0),
             ('decl',
              'xr',
              ('tensor', [(8, 'invariant')]),
              ('array',
               [('num', 3.0),
                ('num', 1.0),
                ('num', 4.0),
                ('num', 1.0),
                ('num', 5.0),
                ('num', 9.0),
                ('num', 2.0),
                ('num', 6.0)]),
              54),
             ('assign', 'Xr', ('call', 'rfft', [('var', 'xr')]), 55),
             ('expr', ('var', 'Xr'), 0),
             ('assign', 'xr_rec', ('call', 'irfft', [('var', 'Xr')]), 58),
             ('expr', ('var', 'xr_rec'), 0),
             ('decl',
              'xr2',
              ('tensor', [(2, 'invariant'), (4, 'invariant')]),
              ('array',
               [('array',
                 [('num', 1.0), ('num', 0.0), ('num', 2.0), ('num', 1.0)]),
                ('array',
                 [('num', 3.0), ('num', 1.0), ('num', 0.0), ('num', 2.0)])]),
              61),
             ('assign', 'Xr2', ('call', 'rfft2', [('var', 'xr2')]), 65),
             ('expr', ('var', 'Xr2'), 0),
             ('assign', 'xr2_rec', ('call', 'irfft2', [('var', 'Xr2')]), 68),
             ('expr', ('var', 'xr2_rec'), 0),
             ('decl',
              'xr3',
              ('tensor',
               [(2, 'invariant'), (2, 'invariant'), (4, 'invariant')]),
              ('array',
               [('array',
                 [('array',
                   [('num', 2.0), ('num', 1.0), ('num', 0.0), ('num', 3.0)]),
                  ('array',
                   [('num', 1.0), ('num', 2.0), ('num', 1.0), ('num', 0.0)])]),
                ('array',
                 [('array',
                   [('num', 0.0), ('num', 1.0), ('num', 2.0), ('num', 1.0)]),
                  ('array',
                   [('num', 3.0),
                    ('num', 0.0),
                    ('num', 1.0),
                    ('num', 2.0)])])]),
              71),
             ('assign', 'Xr3', ('call', 'rfftn', [('var', 'xr3')]), 75),
             ('expr', ('var', 'Xr3'), 0),
             ('assign', 'xr3_rec', ('call', 'irfftn', [('var', 'Xr3')]), 78),
             ('expr', ('var', 'xr3_rec'), 0)]}
