EXPECTED = {'functions': {'slice_demo_1d': {'params': [('a',
                                             ('tensor', [('m', 'invariant')]))],
                                 'return_type': ('tensor',
                                                 [('n', 'invariant')]),
                                 'body': ('indexN',
                                          'a',
                                          [('slice_item', None, ('num', 2))]),
                                 'has_loop': False,
                                 'statements': []},
               'slice_demo_2d': {'params': [('a',
                                             ('tensor',
                                              [('m', 'invariant'),
                                               ('n', 'invariant')]))],
                                 'return_type': ('tensor',
                                                 [('o', 'invariant')]),
                                 'body': ('indexN',
                                          'a',
                                          [('slice_item', None, None),
                                           ('index_item', ('num', 0))]),
                                 'has_loop': False,
                                 'statements': []},
               'slice_demo_3d': {'params': [('a',
                                             ('tensor',
                                              [('m', 'invariant'),
                                               ('n', 'invariant'),
                                               ('o', 'invariant')]))],
                                 'return_type': ('tensor',
                                                 [('p', 'invariant')]),
                                 'body': ('indexN',
                                          'a',
                                          [('slice_item', None, None),
                                           ('index_item', ('num', 0)),
                                           ('index_item', ('num', 0))]),
                                 'has_loop': False,
                                 'statements': []}},
 'classes': {'SliceDemo': {'class_params': [],
                           'fields': [],
                           'methods': [{'name': 'return_x',
                                        'params': [('x',
                                                    ('tensor',
                                                     [(8, 'invariant')]))],
                                        'return_type': ('tensor',
                                                        [('m', 'invariant')]),
                                        'statements': [],
                                        'body': ('indexN',
                                                 'x',
                                                 [('slice_item',
                                                   None,
                                                   ('num', 4))])},
                                       {'name': 'return_y',
                                        'params': [('y',
                                                    ('tensor',
                                                     [(4, 'invariant'),
                                                      (4, 'invariant')]))],
                                        'return_type': ('tensor',
                                                        [('n', 'invariant')]),
                                        'statements': [],
                                        'body': ('indexN',
                                                 'y',
                                                 [('slice_item', None, None),
                                                  ('index_item', ('num', 1))])},
                                       {'name': 'return_z',
                                        'params': [('z',
                                                    ('tensor',
                                                     [(2, 'invariant'),
                                                      (2, 'invariant'),
                                                      (2, 'invariant')]))],
                                        'return_type': ('tensor',
                                                        [('m', 'invariant')]),
                                        'statements': [],
                                        'body': ('indexN',
                                                 'z',
                                                 [('slice_item', None, None),
                                                  ('index_item', ('num', 1)),
                                                  ('index_item',
                                                   ('num', 0))])}]}},
 'program': [('decl',
              'x',
              ('tensor', [(8, 'invariant')]),
              ('array',
               [('num', 1),
                ('num', 2),
                ('num', 3),
                ('num', 4),
                ('num', 5),
                ('num', 6),
                ('num', 7),
                ('num', 8)]),
              16),
             ('decl',
              'y',
              ('tensor', [(4, 'invariant'), (4, 'invariant')]),
              ('array',
               [('array', [('num', 1), ('num', 2), ('num', 3), ('num', 4)]),
                ('array', [('num', 5), ('num', 6), ('num', 7), ('num', 8)]),
                ('array', [('num', 9), ('num', 10), ('num', 11), ('num', 12)]),
                ('array',
                 [('num', 13), ('num', 14), ('num', 15), ('num', 16)])]),
              18),
             ('decl',
              'z',
              ('tensor',
               [(2, 'invariant'), (2, 'invariant'), (2, 'invariant')]),
              ('array',
               [('array',
                 [('array', [('num', 1), ('num', 2)]),
                  ('array', [('num', 3), ('num', 4)])]),
                ('array',
                 [('array', [('num', 5), ('num', 6)]),
                  ('array', [('num', 7), ('num', 8)])])]),
              25),
             ('expr',
              ('indexN', 'x', [('slice_item', ('num', 1), ('num', 3))]),
              0),
             ('expr', ('indexN', 'x', [('slice_item', None, ('num', 4))]), 0),
             ('expr',
              ('indexN',
               'y',
               [('slice_item', ('num', 1), ('num', 3)),
                ('slice_item', None, None)]),
              0),
             ('expr',
              ('indexN',
               'y',
               [('slice_item', None, None), ('index_item', ('num', 2))]),
              0),
             ('expr',
              ('indexN',
               'z',
               [('index_item', ('num', 1)),
                ('slice_item', None, None),
                ('slice_item', None, None)]),
              0),
             ('expr',
              ('indexN',
               'z',
               [('slice_item', None, None),
                ('index_item', ('num', 0)),
                ('index_item', ('num', 0))]),
              0),
             ('func_def', 'slice_demo_1d'),
             ('func_def', 'slice_demo_2d'),
             ('func_def', 'slice_demo_3d'),
             ('expr', ('call', 'slice_demo_1d', [('var', 'x')]), 0),
             ('expr', ('call', 'slice_demo_2d', [('var', 'y')]), 0),
             ('expr', ('call', 'slice_demo_3d', [('var', 'z')]), 0),
             ('class_def', 'SliceDemo'),
             ('decl',
              'obj_slice_demo',
              ('struct_type', 'SliceDemo'),
              ('call', 'SliceDemo', []),
              85),
             ('expr',
              ('method_call',
               ('var', 'obj_slice_demo'),
               'return_x',
               [('var', 'x')]),
              0),
             ('expr',
              ('method_call',
               ('var', 'obj_slice_demo'),
               'return_y',
               [('var', 'y')]),
              0),
             ('expr',
              ('method_call',
               ('var', 'obj_slice_demo'),
               'return_z',
               [('var', 'z')]),
              0),
             ('index_assign_nd',
              'x',
              [('slice_item', ('num', 1), ('num', 3))],
              ('array', [('num', 10), ('num', 20)]),
              96),
             ('index_assign_nd',
              'y',
              [('slice_item', None, None), ('index_item', ('num', 0))],
              ('array', [('num', 10), ('num', 20), ('num', 30), ('num', 40)]),
              97),
             ('index_assign_nd',
              'z',
              [('slice_item', None, None),
               ('slice_item', None, None),
               ('index_item', ('num', 0))],
              ('array', [('num', 10), ('num', 20)]),
              98),
             ('expr', ('var', 'x'), 0),
             ('expr', ('var', 'y'), 0),
             ('expr', ('var', 'z'), 0)]}
