EXPECTED = {'functions': {'op_J': {'params': [('W', ('tensor', [('m', 'invariant')])),
                                   ('s1', 'ℕ'),
                                   ('s2', 'ℕ'),
                                   ('s3', 'ℕ')],
                        'return_type': ('tensor', [('k', 'invariant')]),
                        'body': ('div', ('var', 'flat'), ('var', 'n')),
                        'has_loop': False,
                        'statements': [('body_assign',
                                        'n',
                                        ('mul',
                                         ('mul', ('var', 's1'), ('var', 's2')),
                                         ('var', 's3'))),
                                       ('body_assign',
                                        'cube',
                                        ('call',
                                         'reshape',
                                         [('var', 'W'),
                                          ('var', 's1'),
                                          ('var', 's2'),
                                          ('var', 's3')])),
                                       ('body_assign',
                                        'spec',
                                        ('call', 'fft', [('var', 'cube')])),
                                       ('body_assign',
                                        'flat',
                                        ('call',
                                         'reshape',
                                         [('var', 'spec'), ('var', 'n')]))]},
               'op_I': {'params': [('W', ('tensor', [('m', 'invariant')])),
                                   ('s1', 'ℕ'),
                                   ('s2', 'ℕ'),
                                   ('s3', 'ℕ')],
                        'return_type': ('tensor', [('k', 'invariant')]),
                        'body': ('mul', ('var', 'flat'), ('var', 'n')),
                        'has_loop': False,
                        'statements': [('body_assign',
                                        'n',
                                        ('mul',
                                         ('mul', ('var', 's1'), ('var', 's2')),
                                         ('var', 's3'))),
                                       ('body_assign',
                                        'cube',
                                        ('call',
                                         'reshape',
                                         [('var', 'W'),
                                          ('var', 's1'),
                                          ('var', 's2'),
                                          ('var', 's3')])),
                                       ('body_assign',
                                        'field',
                                        ('call', 'ifft', [('var', 'cube')])),
                                       ('body_assign',
                                        'flat',
                                        ('call',
                                         'reshape',
                                         [('var', 'field'), ('var', 'n')]))]}},
 'classes': {},
 'program': [('func_def', 'op_J'),
             ('func_def', 'op_I'),
             ('decl',
              'field',
              ('tensor', [(8, 'invariant')]),
              ('array',
               [('add', ('num', 1), ('complex', 0j)),
                ('add', ('num', 2), ('complex', 1j)),
                ('add', ('num', 0), ('complex', 3j)),
                ('add', ('neg', ('num', 1)), ('complex', 0j)),
                ('add', ('num', 2), ('complex', 0j)),
                ('sub', ('num', 1), ('complex', 1j)),
                ('add', ('num', 0), ('complex', 0j)),
                ('add', ('num', 3), ('complex', 2j))]),
              38),
             ('decl',
              'spectrum',
              ('tensor', [(8, 'invariant')]),
              ('call',
               'op_J',
               [('var', 'field'), ('num', 2), ('num', 2), ('num', 2)]),
              40),
             ('decl',
              'recovered',
              ('tensor', [(8, 'invariant')]),
              ('call',
               'op_I',
               [('var', 'spectrum'), ('num', 2), ('num', 2), ('num', 2)]),
              41),
             ('expr', ('var', 'field'), 0),
             ('expr', ('var', 'spectrum'), 0),
             ('expr', ('var', 'recovered'), 0)]}