EXPECTED = {'functions': {'outer_product': {'params': [('u',
                                             ('tensor', [('n', 'invariant')])),
                                            ('v',
                                             ('tensor', [('m', 'invariant')]))],
                                 'return_type': ('tensor',
                                                 [('n', 'invariant'),
                                                  ('m', 'invariant')]),
                                 'body': ('for_expr',
                                          'i',
                                          ('call', 'len', [('var', 'u')]),
                                          ('for_expr',
                                           'j',
                                           ('call', 'len', [('var', 'v')]),
                                           ('mul',
                                            ('index', 'u', ('imaginary',)),
                                            ('index', 'v', ('var', 'j'))))),
                                 'has_loop': False,
                                 'statements': []},
               'get_last': {'params': [('arr',
                                        ('tensor', [('n', 'invariant')]))],
                            'return_type': 'ℝ',
                            'body': ('var', 'cur'),
                            'has_loop': False,
                            'statements': [('body_decl',
                                            'cur',
                                            'ℝ',
                                            ('num', 0)),
                                           ('body_for',
                                            'i',
                                            [('loop_assign',
                                              'cur',
                                              ('index',
                                               'arr',
                                               ('imaginary',)))],
                                            ['arr'])]},
               'iter_prod': {'params': [('n', 'ℝ')],
                             'return_type': 'ℝ',
                             'body': ('var', 'total'),
                             'has_loop': False,
                             'statements': [('body_decl',
                                             'total',
                                             'ℝ',
                                             ('num', 0)),
                                            ('body_for_range',
                                             'i',
                                             ('num', 0),
                                             ('var', 'n'),
                                             [('loop_pluseq',
                                               'total',
                                               ('mul',
                                                ('imaginary',),
                                                ('num', 1)))])]},
               'partial_sum': {'params': [('arr',
                                           ('tensor', [('n', 'invariant')])),
                                          ('low', 'ℝ'),
                                          ('high', 'ℝ')],
                               'return_type': 'ℝ',
                               'body': ('var', 'total'),
                               'has_loop': False,
                               'statements': [('body_decl',
                                               'total',
                                               'ℝ',
                                               ('num', 0)),
                                              ('body_for_range',
                                               'i',
                                               ('var', 'low'),
                                               ('var', 'high'),
                                               [('loop_pluseq',
                                                 'total',
                                                 ('index',
                                                  'arr',
                                                  ('imaginary',)))])]},
               'outer_accum': {'params': [('u',
                                           ('tensor', [('n', 'invariant')])),
                                          ('v',
                                           ('tensor', [('m', 'invariant')]))],
                               'return_type': ('tensor',
                                               [('n', 'invariant'),
                                                ('m', 'invariant')]),
                               'body': ('var', 'C'),
                               'has_loop': False,
                               'statements': [('body_zeros_decl',
                                               'C',
                                               ('tensor',
                                                [('n', 'invariant'),
                                                 ('m', 'invariant')])),
                                              ('body_for_accum',
                                               ['i', 'j'],
                                               [('loop_index_pluseq',
                                                 'C',
                                                 [('imaginary',), ('var', 'j')],
                                                 ('mul',
                                                  ('index',
                                                   'u',
                                                   ('imaginary',)),
                                                  ('index',
                                                   'v',
                                                   ('var', 'j'))))])]},
               'matmul_physika': {'params': [('A',
                                              ('tensor',
                                               [('n', 'invariant'),
                                                ('m', 'invariant')])),
                                             ('B',
                                              ('tensor',
                                               [('m', 'invariant'),
                                                ('o', 'invariant')]))],
                                  'return_type': ('tensor',
                                                  [('n', 'invariant'),
                                                   ('o', 'invariant')]),
                                  'body': ('var', 'C'),
                                  'has_loop': False,
                                  'statements': [('body_zeros_decl',
                                                  'C',
                                                  ('tensor',
                                                   [('n', 'invariant'),
                                                    ('o', 'invariant')])),
                                                 ('body_for_accum',
                                                  ['i', 'j', 'k'],
                                                  [('loop_index_pluseq',
                                                    'C',
                                                    [('imaginary',),
                                                     ('var', 'j')],
                                                    ('mul',
                                                     ('indexN',
                                                      'A',
                                                      [('imaginary',),
                                                       ('var', 'k')]),
                                                     ('indexN',
                                                      'B',
                                                      [('var', 'k'),
                                                       ('var', 'j')])))])]},
               'chain_mm': {'params': [('A',
                                        ('tensor',
                                         [('m', 'invariant'),
                                          ('n', 'invariant')])),
                                       ('B',
                                        ('tensor',
                                         [('n', 'invariant'),
                                          ('o', 'invariant')]))],
                            'return_type': ('tensor',
                                            [('m', 'invariant'),
                                             ('o', 'invariant')]),
                            'body': ('var', 'D'),
                            'has_loop': False,
                            'statements': [('body_zeros_decl',
                                            'C',
                                            ('tensor',
                                             [(2, 'invariant'),
                                              (2, 'invariant')])),
                                           ('body_for_accum',
                                            ['i', 'j', 'k'],
                                            [('loop_index_pluseq',
                                              'C',
                                              [('imaginary',), ('var', 'j')],
                                              ('mul',
                                               ('indexN',
                                                'A',
                                                [('imaginary',), ('var', 'k')]),
                                               ('indexN',
                                                'B',
                                                [('var', 'k'),
                                                 ('var', 'j')])))]),
                                           ('body_zeros_decl',
                                            'D',
                                            ('tensor',
                                             [(2, 'invariant'),
                                              (2, 'invariant')])),
                                           ('body_for_accum',
                                            ['i', 'j', 'k'],
                                            [('loop_index_pluseq',
                                              'D',
                                              [('imaginary',), ('var', 'j')],
                                              ('mul',
                                               ('indexN',
                                                'C',
                                                [('imaginary',), ('var', 'k')]),
                                               ('indexN',
                                                'A',
                                                [('var', 'k'),
                                                 ('var', 'j')])))])]},
               'tensor_contraction': {'params': [('A',
                                                  ('tensor',
                                                   [('m', 'invariant'),
                                                    ('n', 'invariant')])),
                                                 ('B',
                                                  ('tensor',
                                                   [('n', 'invariant'),
                                                    ('o', 'invariant')])),
                                                 ('C',
                                                  ('tensor',
                                                   [('n', 'invariant'),
                                                    ('r', 'invariant')]))],
                                      'return_type': ('tensor',
                                                      [('m', 'invariant'),
                                                       ('o', 'invariant'),
                                                       ('r', 'invariant')]),
                                      'body': ('var', 'T'),
                                      'has_loop': False,
                                      'statements': [('body_zeros_decl',
                                                      'T',
                                                      ('tensor',
                                                       [('m', 'invariant'),
                                                        ('o', 'invariant'),
                                                        ('r', 'invariant')])),
                                                     ('body_for_accum',
                                                      ['i', 'j', 'l', 'k'],
                                                      [('loop_index_pluseq',
                                                        'T',
                                                        [('imaginary',),
                                                         ('var', 'j'),
                                                         ('var', 'l')],
                                                        ('mul',
                                                         ('mul',
                                                          ('indexN',
                                                           'A',
                                                           [('imaginary',),
                                                            ('var', 'k')]),
                                                          ('indexN',
                                                           'B',
                                                           [('var', 'k'),
                                                            ('var', 'j')])),
                                                         ('indexN',
                                                          'C',
                                                          [('var', 'k'),
                                                           ('var', 'l')])))])]},
               'sum_or_sum_sq': {'params': [('arr',
                                             ('tensor', [('n', 'invariant')])),
                                            ('sq', 'ℝ')],
                                 'return_type': 'ℝ',
                                 'body': None,
                                 'has_loop': False,
                                 'statements': [('body_if_else_return',
                                                 ('cond_gt',
                                                  ('var', 'sq'),
                                                  ('num', 0.0)),
                                                 ('call',
                                                  'sum',
                                                  [('for_expr',
                                                    'i',
                                                    ('call',
                                                     'len',
                                                     [('var', 'arr')]),
                                                    ('pow',
                                                     ('index',
                                                      'arr',
                                                      ('imaginary',)),
                                                     ('num', 2)))]),
                                                 ('call',
                                                  'sum',
                                                  [('for_expr',
                                                    'i',
                                                    ('call',
                                                     'len',
                                                     [('var', 'arr')]),
                                                    ('index',
                                                     'arr',
                                                     ('imaginary',)))]))]},
               'abs_sum': {'params': [('arr',
                                       ('tensor', [('n', 'invariant')]))],
                           'return_type': 'ℝ',
                           'body': None,
                           'has_loop': False,
                           'statements': [('body_decl',
                                           'total',
                                           'ℝ',
                                           ('num', 0.0)),
                                          ('body_for',
                                           'i',
                                           [('loop_pluseq',
                                             'total',
                                             ('index', 'arr', ('imaginary',)))],
                                           ['arr']),
                                          ('body_if_else_return',
                                           ('cond_gt',
                                            ('var', 'total'),
                                            ('num', 0.0)),
                                           ('var', 'total'),
                                           ('sub',
                                            ('num', 0.0),
                                            ('var', 'total')))]},
               'sum_positive': {'params': [('arr',
                                            ('tensor', [('n', 'invariant')]))],
                                'return_type': 'ℝ',
                                'body': ('var', 'total'),
                                'has_loop': False,
                                'statements': [('body_decl',
                                                'total',
                                                'ℝ',
                                                ('num', 0.0)),
                                               ('body_for',
                                                'i',
                                                [('loop_if',
                                                  ('cond_gt',
                                                   ('index',
                                                    'arr',
                                                    ('imaginary',)),
                                                   ('num', 0.0)),
                                                  [('loop_pluseq',
                                                    'total',
                                                    ('index',
                                                     'arr',
                                                     ('imaginary',)))])],
                                                ['arr', 'arr'])]},
               'sum_abs': {'params': [('arr',
                                       ('tensor', [('n', 'invariant')]))],
                           'return_type': 'ℝ',
                           'body': ('var', 'total'),
                           'has_loop': False,
                           'statements': [('body_decl',
                                           'total',
                                           'ℝ',
                                           ('num', 0.0)),
                                          ('body_for',
                                           'i',
                                           [('loop_if_else',
                                             ('cond_gt',
                                              ('index', 'arr', ('imaginary',)),
                                              ('num', 0.0)),
                                             [('loop_pluseq',
                                               'total',
                                               ('index',
                                                'arr',
                                                ('imaginary',)))],
                                             [('loop_pluseq',
                                               'total',
                                               ('sub',
                                                ('num', 0.0),
                                                ('index',
                                                 'arr',
                                                 ('imaginary',))))])],
                                           ['arr', 'arr', 'arr'])]},
               'count_above': {'params': [('arr',
                                           ('tensor', [('n', 'invariant')])),
                                          ('thresh', 'ℝ')],
                               'return_type': 'ℝ',
                               'body': ('var', 'count'),
                               'has_loop': False,
                               'statements': [('body_decl',
                                               'count',
                                               'ℝ',
                                               ('num', 0.0)),
                                              ('body_for',
                                               'i',
                                               [('loop_if',
                                                 ('cond_gt',
                                                  ('index',
                                                   'arr',
                                                   ('imaginary',)),
                                                  ('var', 'thresh')),
                                                 [('loop_pluseq',
                                                   'count',
                                                   ('num', 1))])],
                                               ['arr'])]},
               'count_above_range': {'params': [('arr',
                                                 ('tensor',
                                                  [('n', 'invariant')])),
                                                ('lo', 'ℝ'),
                                                ('hi', 'ℝ'),
                                                ('thresh', 'ℝ')],
                                     'return_type': 'ℝ',
                                     'body': ('var', 'count'),
                                     'has_loop': False,
                                     'statements': [('body_decl',
                                                     'count',
                                                     'ℝ',
                                                     ('num', 0.0)),
                                                    ('body_for_range',
                                                     'i',
                                                     ('var', 'lo'),
                                                     ('var', 'hi'),
                                                     [('loop_if',
                                                       ('cond_gt',
                                                        ('index',
                                                         'arr',
                                                         ('imaginary',)),
                                                        ('var', 'thresh')),
                                                       [('loop_pluseq',
                                                         'count',
                                                         ('num', 1))])])]},
               'deep_nest': {'params': [('arr',
                                         ('tensor', [('n', 'invariant')]))],
                             'return_type': 'ℝ',
                             'body': ('var', 'a'),
                             'has_loop': False,
                             'statements': [('body_decl', 'n', 'ℝ', ('num', 3)),
                                            ('body_decl', 'a', 'ℝ', ('num', 0)),
                                            ('body_if_else',
                                             ('cond_gt',
                                              ('var', 'a'),
                                              ('neg', ('num', 1))),
                                             [('body_for_range',
                                               'i',
                                               ('num', 0),
                                               ('num', 2),
                                               [('loop_if_else',
                                                 ('cond_gt',
                                                  ('index',
                                                   'arr',
                                                   ('imaginary',)),
                                                  ('num', 0)),
                                                 [('loop_for_range',
                                                   'j',
                                                   ('num', 0),
                                                   ('num', 2),
                                                   [('loop_if_else',
                                                     ('cond_lt',
                                                      ('index',
                                                       'arr',
                                                       ('var', 'j')),
                                                      ('num', 100)),
                                                     [('loop_for_range',
                                                       'k',
                                                       ('num', 0),
                                                       ('num', 2),
                                                       [('loop_if_else',
                                                         ('cond_neq',
                                                          ('index',
                                                           'arr',
                                                           ('var', 'k')),
                                                          ('num', 0)),
                                                         [('loop_for_range',
                                                           'l',
                                                           ('num', 0),
                                                           ('num', 2),
                                                           [('loop_if_else',
                                                             ('cond_lt',
                                                              ('var', 'a'),
                                                              ('num', 10)),
                                                             [('loop_pluseq',
                                                               'a',
                                                               ('num', 1))],
                                                             [('loop_pluseq',
                                                               'a',
                                                               ('num', 2))])])],
                                                         [('loop_assign',
                                                           'a',
                                                           ('add',
                                                            ('var', 'a'),
                                                            ('num', 3)))])])],
                                                     [('loop_assign',
                                                       'a',
                                                       ('add',
                                                        ('var', 'a'),
                                                        ('num', 4)))])])],
                                                 [('loop_assign',
                                                   'a',
                                                   ('add',
                                                    ('var', 'a'),
                                                    ('num', 5)))])])],
                                             [('body_assign',
                                               'a',
                                               ('neg', ('num', 1)))])]},
               'get_array_length': {'params': [('x',
                                                ('tensor',
                                                 [('m', 'invariant')]))],
                                    'return_type': 'ℝ',
                                    'body': ('var', 'total'),
                                    'has_loop': False,
                                    'statements': [('body_decl',
                                                    'total',
                                                    'ℝ',
                                                    ('num', 0)),
                                                   ('body_for',
                                                    'i',
                                                    [('loop_assign',
                                                      'curr',
                                                      ('index',
                                                       'x',
                                                       ('imaginary',))),
                                                     ('loop_pluseq',
                                                      'total',
                                                      ('num', 1))],
                                                    ['x'])]},
               'manipulate_1d_array': {'params': [('x',
                                                   ('tensor',
                                                    [('m', 'invariant')]))],
                                       'return_type': ('tensor',
                                                       [('n', 'invariant')]),
                                       'body': ('var', 'x'),
                                       'has_loop': False,
                                       'statements': [('body_assign',
                                                       'm',
                                                       ('call',
                                                        'get_array_length',
                                                        [('var', 'x')])),
                                                      ('body_for_range',
                                                       'i',
                                                       ('num', 0),
                                                       ('var', 'm'),
                                                       [('loop_index_assign_nd',
                                                         'x',
                                                         [('imaginary',)],
                                                         ('mul',
                                                          ('imaginary',),
                                                          ('num', 2)))])]},
               'manipulate_2d_array': {'params': [('x',
                                                   ('tensor',
                                                    [('m', 'invariant'),
                                                     ('n', 'invariant')]))],
                                       'return_type': ('tensor',
                                                       [('m', 'invariant'),
                                                        ('n', 'invariant')]),
                                       'body': ('var', 'x'),
                                       'has_loop': False,
                                       'statements': [('body_assign',
                                                       'rows',
                                                       ('call',
                                                        'get_array_length',
                                                        [('var', 'x')])),
                                                      ('body_assign',
                                                       'cols',
                                                       ('call',
                                                        'get_array_length',
                                                        [('index',
                                                          'x',
                                                          ('num', 0))])),
                                                      ('body_for_range',
                                                       'i',
                                                       ('num', 0),
                                                       ('var', 'rows'),
                                                       [('loop_for_range',
                                                         'j',
                                                         ('num', 0),
                                                         ('var', 'cols'),
                                                         [('loop_index_assign_nd',
                                                           'x',
                                                           [('imaginary',),
                                                            ('var', 'j')],
                                                           ('mul',
                                                            ('var', 'j'),
                                                            ('num', 2)))])])]}},
 'classes': {},
 'program': [('decl',
              'arr',
              ('tensor', [(5, 'invariant')]),
              ('array',
               [('num', 1), ('num', 2), ('num', 3), ('num', 4), ('num', 5)]),
              8),
             ('decl', 'total', 'ℝ', ('num', 0), 9),
             ('for_loop',
              'i',
              [('for_pluseq', 'total', ('index', 'arr', ('imaginary',)))],
              ['arr'],
              10),
             ('expr', ('var', 'total'), 0),
             ('decl',
              'X',
              ('tensor', [(4, 'invariant')]),
              ('array', [('num', 1), ('num', 2), ('num', 3), ('num', 4)]),
              15),
             ('decl', 'sum_sq', 'ℝ', ('num', 0), 16),
             ('for_loop',
              'i',
              [('for_pluseq',
                'sum_sq',
                ('pow', ('index', 'X', ('imaginary',)), ('num', 2)))],
              ['X'],
              17),
             ('expr', ('var', 'sum_sq'), 0),
             ('decl',
              'y',
              ('tensor', [(4, 'invariant')]),
              ('array', [('num', 2), ('num', 4), ('num', 6), ('num', 8)]),
              22),
             ('decl', 'mse', 'ℝ', ('num', 0), 23),
             ('for_loop',
              'i',
              [('for_pluseq',
                'mse',
                ('pow',
                 ('sub',
                  ('index', 'X', ('imaginary',)),
                  ('index', 'y', ('imaginary',))),
                 ('num', 2)))],
              ['X', 'y'],
              24),
             ('expr', ('var', 'mse'), 0),
             ('decl',
              'src',
              ('tensor', [(5, 'invariant')]),
              ('array',
               [('num', 1), ('num', 2), ('num', 3), ('num', 4), ('num', 5)]),
              29),
             ('decl',
              'dst',
              ('tensor', [(5, 'invariant')]),
              ('array',
               [('num', 0), ('num', 0), ('num', 0), ('num', 0), ('num', 0)]),
              30),
             ('for_loop',
              'i',
              [('for_index_assign_nd',
                'dst',
                [('imaginary',)],
                ('mul',
                 ('index', 'src', ('imaginary',)),
                 ('index', 'src', ('imaginary',))))],
              ['src', 'src'],
              31),
             ('expr', ('var', 'dst'), 0),
             ('decl', 'start', 'ℝ', ('num', 10), 39),
             ('decl', 'end', 'ℝ', ('num', 20), 40),
             ('decl', 'total', 'ℝ', ('num', 0), 41),
             ('for_loop_range',
              'i',
              ('var', 'start'),
              ('var', 'end'),
              [('for_pluseq', 'total', ('imaginary',))],
              42),
             ('expr', ('var', 'total'), 0),
             ('decl', 'n', 'ℝ', ('num', 10), 48),
             ('for_loop_range',
              'i',
              ('num', 0),
              ('var', 'n'),
              [('for_loop_range',
                'j',
                ('imaginary',),
                ('num', 10),
                [('for_pluseq', 'total', ('imaginary',)),
                 ('for_pluseq', 'total', ('var', 'j'))],
                50)],
              49),
             ('expr', ('var', 'total'), 0),
             ('decl',
              'a',
              ('tensor', [(5, 'invariant')]),
              ('for_expr',
               'i',
               ('num', 5),
               ('mul', ('imaginary',), ('num', 1))),
              58),
             ('expr', ('var', 'a'), 0),
             ('decl',
              'cos_wave',
              ('tensor', [(6, 'invariant')]),
              ('for_expr',
               'i',
               ('num', 6),
               ('call', 'cos', [('mul', ('imaginary',), ('num', 0.5))])),
              62),
             ('expr', ('var', 'cos_wave'), 0),
             ('decl',
              'add',
              ('tensor', [(3, 'invariant'), (4, 'invariant')]),
              ('for_expr',
               'i',
               ('num', 3),
               ('for_expr',
                'j',
                ('num', 4),
                ('add', ('imaginary',), ('var', 'j')))),
              67),
             ('expr', ('var', 'add'), 0),
             ('decl',
              't',
              ('tensor',
               [(2, 'invariant'), (3, 'invariant'), (4, 'invariant')]),
              ('for_expr',
               'i',
               ('num', 2),
               ('for_expr',
                'j',
                ('num', 3),
                ('for_expr',
                 'k',
                 ('num', 4),
                 ('add',
                  ('add', ('imaginary',), ('var', 'j')),
                  ('var', 'k'))))),
              71),
             ('expr', ('var', 't'), 0),
             ('decl',
              'arr',
              ('tensor', [(5, 'invariant')]),
              ('array',
               [('num', 1.0),
                ('num', 2.0),
                ('num', 3.0),
                ('num', 4.0),
                ('num', 5.0)]),
              76),
             ('decl',
              'doubled',
              ('tensor', [(5, 'invariant')]),
              ('for_expr',
               'i',
               ('call', 'len', [('var', 'arr')]),
               ('mul', ('index', 'arr', ('imaginary',)), ('num', 2.0))),
              77),
             ('expr', ('var', 'doubled'), 0),
             ('decl',
              'u',
              ('tensor', [(4, 'invariant')]),
              ('array',
               [('num', 1.0), ('num', 2.0), ('num', 3.0), ('num', 4.0)]),
              81),
             ('decl',
              'v',
              ('tensor', [(4, 'invariant')]),
              ('array',
               [('num', 4.0), ('num', 3.0), ('num', 2.0), ('num', 1.0)]),
              82),
             ('decl',
              'dot_elems',
              ('tensor', [(4, 'invariant')]),
              ('for_expr',
               'i',
               ('call', 'len', [('var', 'u')]),
               ('mul',
                ('index', 'u', ('imaginary',)),
                ('index', 'v', ('imaginary',)))),
              83),
             ('expr', ('var', 'dot_elems'), 0),
             ('func_def', 'outer_product'),
             ('decl',
              'p',
              ('tensor', [(3, 'invariant')]),
              ('array', [('num', 1), ('num', 2), ('num', 3)]),
              92),
             ('decl',
              'q',
              ('tensor', [(4, 'invariant')]),
              ('array', [('num', 10), ('num', 20), ('num', 30), ('num', 40)]),
              93),
             ('expr',
              ('call', 'outer_product', [('var', 'p'), ('var', 'q')]),
              0),
             ('decl',
              'x',
              ('tensor', [(4, 'invariant')]),
              ('array', [('num', 1), ('num', 0), ('num', 0), ('num', 0)]),
              97),
             ('decl',
              'y',
              ('tensor', [(4, 'invariant')]),
              ('array', [('num', 0), ('num', 1), ('num', 0), ('num', 0)]),
              98),
             ('decl',
              'dot',
              'ℝ',
              ('call',
               'sum',
               [('for_expr',
                 'i',
                 ('call', 'len', [('var', 'x')]),
                 ('mul',
                  ('index', 'x', ('imaginary',)),
                  ('index', 'y', ('imaginary',))))]),
              99),
             ('expr', ('var', 'dot'), 0),
             ('func_def', 'get_last'),
             ('decl',
              'vals',
              ('tensor', [(5, 'invariant')]),
              ('array',
               [('num', 3), ('num', 1), ('num', 4), ('num', 1), ('num', 5)]),
              109),
             ('expr', ('call', 'get_last', [('var', 'vals')]), 0),
             ('func_def', 'iter_prod'),
             ('expr', ('call', 'iter_prod', [('num', 10)]), 0),
             ('func_def', 'partial_sum'),
             ('decl',
              'data',
              ('tensor', [(6, 'invariant')]),
              ('array',
               [('num', 1),
                ('num', 2),
                ('num', 3),
                ('num', 4),
                ('num', 5),
                ('num', 6)]),
              127),
             ('expr',
              ('call',
               'partial_sum',
               [('var', 'data'), ('num', 2), ('num', 5)]),
              0),
             ('func_def', 'outer_accum'),
             ('expr', ('call', 'outer_accum', [('var', 'p'), ('var', 'q')]), 0),
             ('func_def', 'matmul_physika'),
             ('decl',
              'A',
              ('tensor', [(2, 'invariant'), (4, 'invariant')]),
              ('array',
               [('array', [('num', 1), ('num', 2), ('num', 3), ('num', 4)]),
                ('array', [('num', 0), ('num', 1), ('num', 1), ('num', 2)])]),
              146),
             ('decl',
              'B',
              ('tensor', [(4, 'invariant'), (1, 'invariant')]),
              ('array',
               [('array', [('num', 1)]),
                ('array', [('num', 0)]),
                ('array', [('num', 0)]),
                ('array', [('num', 2)])]),
              147),
             ('expr',
              ('call', 'matmul_physika', [('var', 'A'), ('var', 'B')]),
              0),
             ('decl',
              'A2',
              ('tensor', [(2, 'invariant'), (2, 'invariant')]),
              ('array',
               [('array', [('num', 1), ('num', 2)]),
                ('array', [('num', 0), ('num', 1)])]),
              152),
             ('decl',
              'B2',
              ('tensor', [(2, 'invariant'), (2, 'invariant')]),
              ('array',
               [('array', [('num', 1), ('num', 0)]),
                ('array', [('num', 0), ('num', 2)])]),
              153),
             ('func_def', 'chain_mm'),
             ('expr', ('call', 'chain_mm', [('var', 'A2'), ('var', 'B2')]), 0),
             ('decl',
              'C_mat',
              ('tensor', [(2, 'invariant'), (3, 'invariant')]),
              ('array',
               [('array', [('num', 1.0), ('num', 0.0), ('num', 0.0)]),
                ('array', [('num', 0.0), ('num', 1.0), ('num', 0.0)])]),
              168),
             ('func_def', 'tensor_contraction'),
             ('expr',
              ('call',
               'tensor_contraction',
               [('var', 'A2'), ('var', 'B2'), ('var', 'C_mat')]),
              0),
             ('func_def', 'sum_or_sum_sq'),
             ('decl',
              'w',
              ('tensor', [(4, 'invariant')]),
              ('array',
               [('num', 1.0), ('num', 2.0), ('num', 3.0), ('num', 4.0)]),
              185),
             ('expr',
              ('call', 'sum_or_sum_sq', [('var', 'w'), ('num', 1.0)]),
              0),
             ('expr',
              ('call',
               'sum_or_sum_sq',
               [('var', 'w'), ('sub', ('num', 0.0), ('num', 1.0))]),
              0),
             ('func_def', 'abs_sum'),
             ('decl',
              'pos',
              ('tensor', [(4, 'invariant')]),
              ('array',
               [('num', 1.0), ('num', 2.0), ('num', 3.0), ('num', 4.0)]),
              198),
             ('decl',
              'neg',
              ('tensor', [(4, 'invariant')]),
              ('array',
               [('sub', ('num', 0.0), ('num', 1.0)),
                ('sub', ('num', 0.0), ('num', 2.0)),
                ('sub', ('num', 0.0), ('num', 3.0)),
                ('sub', ('num', 0.0), ('num', 4.0))]),
              199),
             ('expr', ('call', 'abs_sum', [('var', 'pos')]), 0),
             ('expr', ('call', 'abs_sum', [('var', 'neg')]), 0),
             ('func_def', 'sum_positive'),
             ('decl',
              'mixed',
              ('tensor', [(5, 'invariant')]),
              ('array',
               [('num', 1.0),
                ('sub', ('num', 0.0), ('num', 2.0)),
                ('num', 3.0),
                ('sub', ('num', 0.0), ('num', 4.0)),
                ('num', 5.0)]),
              211),
             ('expr', ('call', 'sum_positive', [('var', 'mixed')]), 0),
             ('func_def', 'sum_abs'),
             ('expr', ('call', 'sum_abs', [('var', 'mixed')]), 0),
             ('func_def', 'count_above'),
             ('decl',
              'data',
              ('tensor', [(6, 'invariant')]),
              ('array',
               [('num', 1),
                ('num', 5),
                ('num', 2),
                ('num', 8),
                ('num', 3),
                ('num', 7)]),
              234),
             ('expr',
              ('call', 'count_above', [('var', 'data'), ('num', 3)]),
              0),
             ('func_def', 'count_above_range'),
             ('decl',
              'data',
              ('tensor', [(6, 'invariant')]),
              ('array',
               [('num', 1),
                ('num', 5),
                ('num', 2),
                ('num', 8),
                ('num', 3),
                ('num', 7)]),
              245),
             ('expr',
              ('call',
               'count_above_range',
               [('var', 'data'), ('num', 1), ('num', 5), ('num', 3)]),
              0),
             ('func_def', 'deep_nest'),
             ('decl',
              'arr2',
              ('tensor', [(3, 'invariant')]),
              ('array', [('num', 1), ('num', 2), ('num', 4)]),
              274),
             ('expr', ('call', 'deep_nest', [('var', 'arr2')]), 0),
             ('decl',
              'arr3',
              ('tensor', [(5, 'invariant')]),
              ('array',
               [('num', 1),
                ('neg', ('num', 2)),
                ('num', 3),
                ('neg', ('num', 4)),
                ('num', 5)]),
              281),
             ('decl', 'pos_sum', 'ℝ', ('num', 0), 282),
             ('for_loop_range',
              'i',
              ('num', 0),
              ('num', 5),
              [('for_if',
                ('cond_gt', ('index', 'arr3', ('imaginary',)), ('num', 0)),
                [('for_pluseq',
                  'pos_sum',
                  ('index', 'arr3', ('imaginary',)))])],
              283),
             ('expr', ('var', 'pos_sum'), 0),
             ('decl', 'abs_total', 'ℝ', ('num', 0.0), 289),
             ('for_loop_range',
              'i',
              ('num', 0),
              ('num', 5),
              [('for_if_else',
                ('cond_gt', ('index', 'arr3', ('imaginary',)), ('num', 0.0)),
                [('for_pluseq',
                  'abs_total',
                  ('index', 'arr3', ('imaginary',)))],
                [('for_pluseq',
                  'abs_total',
                  ('sub', ('num', 0.0), ('index', 'arr3', ('imaginary',))))])],
              290),
             ('expr', ('var', 'abs_total'), 0),
             ('decl', 'pos_sum2', 'ℝ', ('num', 0.0), 298),
             ('for_loop',
              'i',
              [('for_if',
                ('cond_gt', ('index', 'arr3', ('imaginary',)), ('num', 0.0)),
                [('for_pluseq',
                  'pos_sum2',
                  ('index', 'arr3', ('imaginary',)))])],
              ['arr3', 'arr3'],
              299),
             ('expr', ('var', 'pos_sum2'), 0),
             ('decl',
              'mat',
              ('tensor', [(3, 'invariant')]),
              ('array', [('num', 1.0), ('num', 2.0), ('num', 3.0)]),
              305),
             ('decl',
              'vec',
              ('tensor', [(3, 'invariant')]),
              ('array', [('num', 4.0), ('num', 5.0), ('num', 6.0)]),
              306),
             ('decl', 'dot2', 'ℝ', ('num', 0.0), 307),
             ('for_loop_range',
              'i',
              ('num', 0),
              ('num', 3),
              [('for_if',
                ('cond_gt', ('index', 'mat', ('imaginary',)), ('num', 0.0)),
                [('for_pluseq',
                  'dot2',
                  ('mul',
                   ('index', 'mat', ('imaginary',)),
                   ('index', 'vec', ('imaginary',))))])],
              308),
             ('expr', ('var', 'dot2'), 0),
             ('decl',
              'arr4',
              ('tensor', [(2, 'invariant')]),
              ('array', [('num', 1.0), ('num', 4.0)]),
              314),
             ('decl', 'a', 'ℝ', ('num', 0.0), 315),
             ('for_loop_range',
              'i',
              ('num', 0),
              ('num', 2),
              [('for_if_else',
                ('cond_gt', ('index', 'arr4', ('imaginary',)), ('num', 0.0)),
                [('for_loop_range',
                  'j',
                  ('num', 0),
                  ('num', 2),
                  [('for_if_else',
                    ('cond_lt',
                     ('index', 'arr4', ('var', 'j')),
                     ('num', 100.0)),
                    [('for_loop_range',
                      'k',
                      ('num', 0),
                      ('num', 2),
                      [('for_if_else',
                        ('cond_neq',
                         ('index', 'arr4', ('var', 'k')),
                         ('num', 0.0)),
                        [('for_if_else',
                          ('cond_lt', ('var', 'a'), ('num', 10.0)),
                          [('for_pluseq', 'a', ('num', 1))],
                          [('for_pluseq', 'a', ('num', 2))])],
                        [('for_pluseq', 'a', ('num', 3))])],
                      320)],
                    [('for_pluseq', 'a', ('num', 4))])],
                  318)],
                [('for_pluseq', 'a', ('num', 5))])],
              316),
             ('expr', ('var', 'a'), 0),
             ('decl',
              'vals',
              ('tensor', [(5, 'invariant')]),
              ('array',
               [('num', 1),
                ('neg', ('num', 2)),
                ('num', 3),
                ('num', 4),
                ('num', 5)]),
              338),
             ('decl', 'flag', 'ℝ', ('num', 1), 339),
             ('decl',
              'res',
              ('tensor', [(5, 'invariant')]),
              ('for_expr',
               'i',
               ('call', 'len', [('var', 'vals')]),
               ('index', 'vals', ('imaginary',))),
              340),
             ('if_else',
              ('cond_gt', ('var', 'flag'), ('num', 0)),
              [('for_assign',
                'res',
                ('for_expr',
                 'i',
                 ('num', 5),
                 ('pow', ('index', 'vals', ('imaginary',)), ('num', 3))))],
              [('for_assign',
                'res',
                ('for_expr',
                 'i',
                 ('num', 5),
                 ('index', 'vals', ('imaginary',))))]),
             ('expr', ('var', 'res'), 0),
             ('decl',
              'total_c',
              'ℝ',
              ('call',
               'sum',
               [('for_expr',
                 'i',
                 ('call', 'len', [('var', 'res')]),
                 ('index', 'res', ('imaginary',)))]),
              347),
             ('expr', ('var', 'total_c'), 0),
             ('decl', 'scale', 'ℝ', ('num', 2), 354),
             ('decl',
              'W',
              ('tensor', [(3, 'invariant'), (4, 'invariant')]),
              ('for_expr',
               'i',
               ('num', 3),
               ('for_expr',
                'j',
                ('num', 4),
                ('add', ('imaginary',), ('var', 'j')))),
              355),
             ('if_else',
              ('cond_gt', ('var', 'scale'), ('num', 1)),
              [('for_assign',
                'W',
                ('for_expr',
                 'i',
                 ('num', 3),
                 ('for_expr',
                  'j',
                  ('num', 4),
                  ('mul',
                   ('add', ('imaginary',), ('var', 'j')),
                   ('var', 'scale')))))],
              [('for_assign',
                'W',
                ('for_expr',
                 'i',
                 ('num', 3),
                 ('for_expr',
                  'j',
                  ('num', 4),
                  ('add', ('imaginary',), ('var', 'j')))))]),
             ('expr', ('var', 'W'), 0),
             ('decl',
              'u2',
              ('tensor', [(3, 'invariant')]),
              ('array', [('num', 1), ('num', 2), ('num', 3)]),
              366),
             ('decl',
              'v2',
              ('tensor', [(3, 'invariant')]),
              ('array', [('num', 4), ('num', 5), ('num', 6)]),
              367),
             ('decl',
              'row_sums',
              ('tensor', [(3, 'invariant')]),
              ('for_expr',
               'i',
               ('call', 'len', [('var', 'u2')]),
               ('call',
                'sum',
                [('for_expr',
                  'j',
                  ('call', 'len', [('var', 'v2')]),
                  ('mul',
                   ('index', 'u2', ('imaginary',)),
                   ('index', 'v2', ('var', 'j'))))])),
              368),
             ('expr', ('var', 'row_sums'), 0),
             ('decl',
              'data2',
              ('tensor', [(4, 'invariant')]),
              ('array', [('num', 10), ('num', 20), ('num', 30), ('num', 40)]),
              372),
             ('decl', 'norm_flag', 'ℝ', ('num', 1), 373),
             ('decl',
              'normed',
              ('tensor', [(4, 'invariant')]),
              ('for_expr',
               'i',
               ('call', 'len', [('var', 'data2')]),
               ('index', 'data2', ('imaginary',))),
              374),
             ('if_else',
              ('cond_gt', ('var', 'norm_flag'), ('num', 0)),
              [('for_assign',
                'normed',
                ('for_expr',
                 'i',
                 ('num', 4),
                 ('mul',
                  ('index', 'data2', ('imaginary',)),
                  ('div', ('num', 1), ('add', ('imaginary',), ('num', 1))))))],
              [('for_assign',
                'normed',
                ('for_expr',
                 'i',
                 ('num', 4),
                 ('index', 'data2', ('imaginary',))))]),
             ('expr', ('var', 'normed'), 0),
             ('func_def', 'get_array_length'),
             ('decl',
              'sample_1d_array',
              ('tensor', [(3, 'invariant')]),
              ('array', [('num', 1), ('num', 2), ('num', 3)]),
              392),
             ('decl',
              'length_array',
              'ℝ',
              ('call', 'get_array_length', [('var', 'sample_1d_array')]),
              393),
             ('for_loop_range',
              'i',
              ('num', 0),
              ('var', 'length_array'),
              [('for_index_assign_nd',
                'sample_1d_array',
                [('imaginary',)],
                ('mul', ('imaginary',), ('num', 2)))],
              394),
             ('expr', ('var', 'sample_1d_array'), 0),
             ('decl',
              'sample_2d_array',
              ('tensor', [(2, 'invariant'), (2, 'invariant')]),
              ('array',
               [('array', [('num', 1), ('num', 1)]),
                ('array', [('num', 1), ('num', 1)])]),
              399),
             ('decl',
              'rows',
              'ℝ',
              ('call', 'get_array_length', [('var', 'sample_2d_array')]),
              403),
             ('decl',
              'cols',
              'ℝ',
              ('call',
               'get_array_length',
               [('index', 'sample_2d_array', ('num', 0))]),
              404),
             ('for_loop_range',
              'i',
              ('num', 0),
              ('var', 'rows'),
              [('for_loop_range',
                'j',
                ('num', 0),
                ('var', 'cols'),
                [('for_index_assign_nd',
                  'sample_2d_array',
                  [('imaginary',), ('var', 'j')],
                  ('mul', ('var', 'j'), ('num', 2)))],
                406)],
              405),
             ('expr', ('var', 'sample_2d_array'), 0),
             ('func_def', 'manipulate_1d_array'),
             ('decl',
              'arr1d',
              ('tensor', [(3, 'invariant')]),
              ('array', [('num', 1), ('num', 2), ('num', 3)]),
              416),
             ('expr', ('call', 'manipulate_1d_array', [('var', 'arr1d')]), 0),
             ('func_def', 'manipulate_2d_array'),
             ('decl',
              'arr2d',
              ('tensor', [(2, 'invariant'), (2, 'invariant')]),
              ('array',
               [('array', [('num', 1), ('num', 1)]),
                ('array', [('num', 1), ('num', 1)])]),
              427),
             ('expr', ('call', 'manipulate_2d_array', [('var', 'arr2d')]), 0)]}
