EXPECTED = {'functions': {'outer_product': {'params': [('u', ('tensor', [('n', 'invariant')])),
                                            ('v', ('tensor', [('m', 'invariant')]))],
                                 'return_type': ('tensor', [('n', 'invariant'), ('m', 'invariant')]),
                                 'body': ('for_expr',
                                          'i',
                                          ('call', 'len', [('var', 'u')]),
                                          ('for_expr',
                                           'j',
                                           ('call', 'len', [('var', 'v')]),
                                           ('mul', ('index', 'u', ('imaginary',)), ('index', 'v', ('var', 'j'))))),
                                 'has_loop': False,
                                 'statements': []},
               'matmul_physika': {'params': [('A', ('tensor', [('n', 'invariant'), ('m', 'invariant')])),
                                             ('B', ('tensor', [('m', 'invariant'), ('o', 'invariant')]))],
                                  'return_type': ('tensor', [('n', 'invariant'), ('o', 'invariant')]),
                                  'body': ('var', 'C'),
                                  'has_loop': False,
                                  'statements': [('body_zeros_decl',
                                                  'C',
                                                  ('tensor', [('n', 'invariant'), ('o', 'invariant')])),
                                                 ('body_for_accum',
                                                  ['i', 'j', 'k'],
                                                  [('loop_index_pluseq',
                                                    'C',
                                                    [('imaginary',), ('var', 'j')],
                                                    ('mul',
                                                     ('indexN', 'A', [('imaginary',), ('var', 'k')]),
                                                     ('indexN', 'B', [('var', 'k'), ('var', 'j')])))])]},
               'chain_mm': {'params': [('A', ('tensor', [('m', 'invariant'), ('n', 'invariant')])),
                                       ('B', ('tensor', [('n', 'invariant'), ('o', 'invariant')]))],
                            'return_type': ('tensor', [('m', 'invariant'), ('o', 'invariant')]),
                            'body': ('var', 'D'),
                            'has_loop': False,
                            'statements': [('body_zeros_decl', 'C', ('tensor', [(2, 'invariant'), (2, 'invariant')])),
                                           ('body_for_accum',
                                            ['i', 'j', 'k'],
                                            [('loop_index_pluseq',
                                              'C',
                                              [('imaginary',), ('var', 'j')],
                                              ('mul',
                                               ('indexN', 'A', [('imaginary',), ('var', 'k')]),
                                               ('indexN', 'B', [('var', 'k'), ('var', 'j')])))]),
                                           ('body_zeros_decl', 'D', ('tensor', [(2, 'invariant'), (2, 'invariant')])),
                                           ('body_for_accum',
                                            ['i', 'j', 'k'],
                                            [('loop_index_pluseq',
                                              'D',
                                              [('imaginary',), ('var', 'j')],
                                              ('mul',
                                               ('indexN', 'C', [('imaginary',), ('var', 'k')]),
                                               ('indexN', 'A', [('var', 'k'), ('var', 'j')])))])]},
               'both_matmuls': {'params': [('A', ('tensor', [('m', 'invariant'), ('n', 'invariant')])),
                                           ('B', ('tensor', [('n', 'invariant'), ('o', 'invariant')]))],
                                'return_type': ('tensor', [('m', 'invariant'), ('o', 'invariant')]),
                                'body': ('add', ('var', 'AB'), ('var', 'BA')),
                                'has_loop': False,
                                'statements': [('body_zeros_decl',
                                                'AB',
                                                ('tensor', [('m', 'invariant'), ('n', 'invariant')])),
                                               ('body_zeros_decl',
                                                'BA',
                                                ('tensor', [('n', 'invariant'), ('o', 'invariant')])),
                                               ('body_for_accum',
                                                ['i', 'j', 'k'],
                                                [('loop_index_pluseq',
                                                  'AB',
                                                  [('imaginary',), ('var', 'j')],
                                                  ('mul',
                                                   ('indexN', 'A', [('imaginary',), ('var', 'k')]),
                                                   ('indexN', 'B', [('var', 'k'), ('var', 'j')]))),
                                                 ('loop_index_pluseq',
                                                  'BA',
                                                  [('imaginary',), ('var', 'j')],
                                                  ('mul',
                                                   ('indexN', 'B', [('imaginary',), ('var', 'k')]),
                                                   ('indexN', 'A', [('var', 'k'), ('var', 'j')])))])]},
               'tensor_contraction': {'params': [('A', ('tensor', [(2, 'invariant'), (2, 'invariant')])),
                                                 ('B', ('tensor', [(2, 'invariant'), (2, 'invariant')])),
                                                 ('C', ('tensor', [(2, 'invariant'), (3, 'invariant')]))],
                                      'return_type': ('tensor', [(2, 'invariant'), (2, 'invariant'), (3, 'invariant')]),
                                      'body': ('var', 'T'),
                                      'has_loop': False,
                                      'statements': [('body_zeros_decl',
                                                      'T',
                                                      ('tensor',
                                                       [(2, 'invariant'), (2, 'invariant'), (3, 'invariant')])),
                                                     ('body_for_accum',
                                                      ['i', 'j', 'l', 'k'],
                                                      [('loop_index_pluseq',
                                                        'T',
                                                        [('imaginary',), ('var', 'j'), ('var', 'l')],
                                                        ('mul',
                                                         ('mul',
                                                          ('indexN', 'A', [('imaginary',), ('var', 'k')]),
                                                          ('indexN', 'B', [('var', 'k'), ('var', 'j')])),
                                                         ('indexN', 'C', [('var', 'k'), ('var', 'l')])))])]}},
 'classes': {},
 'program': [('decl',
              'arr',
              ('tensor', [(5, 'invariant')]),
              ('array', [('num', 1.0), ('num', 2.0), ('num', 3.0), ('num', 4.0), ('num', 5.0)]),
              7),
             ('decl', 'total', 'ℝ', ('num', 0.0), 8),
             ('for_loop', 'i', [('for_pluseq', 'total', ('index', 'arr', ('imaginary',)))], ['arr'], 9),
             ('expr', ('var', 'total'), 0),
             ('decl',
              'X',
              ('tensor', [(4, 'invariant')]),
              ('array', [('num', 1.0), ('num', 2.0), ('num', 3.0), ('num', 4.0)]),
              15),
             ('decl', 'sum_sq', 'ℝ', ('num', 0.0), 16),
             ('for_loop',
              'i',
              [('for_pluseq', 'sum_sq', ('pow', ('index', 'X', ('imaginary',)), ('num', 2.0)))],
              ['X'],
              17),
             ('expr', ('var', 'sum_sq'), 0),
             ('decl',
              'y',
              ('tensor', [(4, 'invariant')]),
              ('array', [('num', 2.0), ('num', 4.0), ('num', 6.0), ('num', 8.0)]),
              22),
             ('decl', 'mse', 'ℝ', ('num', 0.0), 23),
             ('for_loop',
              'i',
              [('for_pluseq',
                'mse',
                ('pow', ('sub', ('index', 'X', ('imaginary',)), ('index', 'y', ('imaginary',))), ('num', 2.0)))],
              ['X', 'y'],
              24),
             ('expr', ('var', 'mse'), 0),
             ('decl',
              'a',
              ('tensor', [(5, 'invariant')]),
              ('for_expr', 'i', ('num', 5.0), ('mul', ('imaginary',), ('num', 1.0))),
              31),
             ('expr', ('var', 'a'), 0),
             ('decl',
              'cos_wave',
              ('tensor', [(6, 'invariant')]),
              ('for_expr', 'i', ('num', 6.0), ('call', 'cos', [('mul', ('imaginary',), ('num', 0.5))])),
              35),
             ('expr', ('var', 'cos_wave'), 0),
             ('decl',
              'add',
              ('tensor', [(3, 'invariant'), (4, 'invariant')]),
              ('for_expr', 'i', ('num', 3.0), ('for_expr', 'j', ('num', 4.0), ('add', ('imaginary',), ('var', 'j')))),
              39),
             ('expr', ('var', 'add'), 0),
             ('decl',
              'outer',
              ('tensor', [(4, 'invariant'), (4, 'invariant')]),
              ('for_expr', 'i', ('num', 4.0), ('for_expr', 'j', ('num', 4.0), ('mul', ('imaginary',), ('var', 'j')))),
              42),
             ('expr', ('var', 'outer'), 0),
             ('decl',
              't',
              ('tensor', [(2, 'invariant'), (3, 'invariant'), (4, 'invariant')]),
              ('for_expr',
               'i',
               ('num', 2.0),
               ('for_expr',
                'j',
                ('num', 3.0),
                ('for_expr', 'k', ('num', 4.0), ('add', ('add', ('imaginary',), ('var', 'j')), ('var', 'k'))))),
              46),
             ('expr', ('var', 't'), 0),
             ('decl',
              'arr',
              ('tensor', [(5, 'invariant')]),
              ('array', [('num', 1.0), ('num', 2.0), ('num', 3.0), ('num', 4.0), ('num', 5.0)]),
              51),
             ('decl',
              'doubled',
              ('tensor', [(5, 'invariant')]),
              ('for_expr',
               'i',
               ('call', 'len', [('var', 'arr')]),
               ('mul', ('index', 'arr', ('imaginary',)), ('num', 2.0))),
              52),
             ('expr', ('var', 'doubled'), 0),
             ('decl',
              'u',
              ('tensor', [(4, 'invariant')]),
              ('array', [('num', 1.0), ('num', 2.0), ('num', 3.0), ('num', 4.0)]),
              56),
             ('decl',
              'v',
              ('tensor', [(4, 'invariant')]),
              ('array', [('num', 4.0), ('num', 3.0), ('num', 2.0), ('num', 1.0)]),
              57),
             ('decl',
              'dot_elems',
              ('tensor', [(4, 'invariant')]),
              ('for_expr',
               'i',
               ('call', 'len', [('var', 'u')]),
               ('mul', ('index', 'u', ('imaginary',)), ('index', 'v', ('imaginary',)))),
              58),
             ('expr', ('var', 'dot_elems'), 0),
             ('func_def', 'outer_product'),
             ('decl', 'p', ('tensor', [(3, 'invariant')]), ('array', [('num', 1.0), ('num', 2.0), ('num', 3.0)]), 67),
             ('decl',
              'q',
              ('tensor', [(4, 'invariant')]),
              ('array', [('num', 10.0), ('num', 20.0), ('num', 30.0), ('num', 40.0)]),
              68),
             ('expr', ('call', 'outer_product', [('var', 'p'), ('var', 'q')]), 0),
             ('decl',
              'x',
              ('tensor', [(4, 'invariant')]),
              ('array', [('num', 1.0), ('num', 0.0), ('num', 0.0), ('num', 0.0)]),
              72),
             ('decl',
              'y',
              ('tensor', [(4, 'invariant')]),
              ('array', [('num', 0.0), ('num', 1.0), ('num', 0.0), ('num', 0.0)]),
              73),
             ('decl',
              'dot',
              'ℝ',
              ('call',
               'sum',
               [('for_expr',
                 'i',
                 ('call', 'len', [('var', 'x')]),
                 ('mul', ('index', 'x', ('imaginary',)), ('index', 'y', ('imaginary',))))]),
              74),
             ('expr', ('var', 'dot'), 0),
             ('func_def', 'matmul_physika'),
             ('decl',
              'A',
              ('tensor', [(2, 'invariant'), (4, 'invariant')]),
              ('array',
               [('array', [('num', 1.0), ('num', 2.0), ('num', 3.0), ('num', 4.0)]),
                ('array', [('num', 0.0), ('num', 1.0), ('num', 1.0), ('num', 2.0)])]),
              85),
             ('decl',
              'B',
              ('tensor', [(4, 'invariant'), (1, 'invariant')]),
              ('array',
               [('array', [('num', 1.0)]),
                ('array', [('num', 0.0)]),
                ('array', [('num', 0.0)]),
                ('array', [('num', 2.0)])]),
              86),
             ('expr', ('call', 'matmul_physika', [('var', 'A'), ('var', 'B')]), 0),
             ('decl',
              'A2',
              ('tensor', [(2, 'invariant'), (2, 'invariant')]),
              ('array', [('array', [('num', 1.0), ('num', 2.0)]), ('array', [('num', 0.0), ('num', 1.0)])]),
              92),
             ('decl',
              'B2',
              ('tensor', [(2, 'invariant'), (2, 'invariant')]),
              ('array', [('array', [('num', 1.0), ('num', 0.0)]), ('array', [('num', 0.0), ('num', 2.0)])]),
              93),
             ('func_def', 'chain_mm'),
             ('expr', ('call', 'chain_mm', [('var', 'A2'), ('var', 'B2')]), 0),
             ('func_def', 'both_matmuls'),
             ('decl',
              'A2',
              ('tensor', [(2, 'invariant'), (2, 'invariant')]),
              ('array', [('array', [('num', 1.0), ('num', 2.0)]), ('array', [('num', 0.0), ('num', 1.0)])]),
              114),
             ('decl',
              'B2',
              ('tensor', [(2, 'invariant'), (2, 'invariant')]),
              ('array', [('array', [('num', 1.0), ('num', 0.0)]), ('array', [('num', 0.0), ('num', 2.0)])]),
              115),
             ('expr', ('call', 'both_matmuls', [('var', 'A2'), ('var', 'B2')]), 0),
             ('decl',
              'C_mat',
              ('tensor', [(2, 'invariant'), (3, 'invariant')]),
              ('array',
               [('array', [('num', 1.0), ('num', 0.0), ('num', 0.0)]),
                ('array', [('num', 0.0), ('num', 1.0), ('num', 0.0)])]),
              120),
             ('func_def', 'tensor_contraction'),
             ('expr', ('call', 'tensor_contraction', [('var', 'A2'), ('var', 'B2'), ('var', 'C_mat')]), 0)]}
