EXPECTED = {'classes': {'SumArray': {'body': ('var', 'total'),
                          'class_params': [('w',
                                            ('tensor', [('n', 'invariant')]))],
                          'has_loop': False,
                          'has_loss': False,
                          'lambda_params': [('x',
                                             ('tensor', [('n', 'invariant')]))],
                          'return_type': 'ℝ',
                          'statements': [('body_decl',
                                          'total',
                                          'ℝ',
                                          ('num', 0.0)),
                                         ('body_for',
                                          'i',
                                          [('loop_assign',
                                            'total',
                                            ('add',
                                             ('var', 'total'),
                                             ('index', 'x', ('imaginary',))))],
                                          ['x'])]}},
 'functions': {},
 'program': [('class_def', 'SumArray'),
             ('decl',
              'arr',
              ('tensor', [(4, 'invariant')]),
              ('array',
               [('num', 1.0), ('num', 2.0), ('num', 3.0), ('num', 4.0)]),
              8),
             ('assign', 'model', ('call', 'SumArray', [('var', 'arr')]), 9),
             ('expr',
              ('call',
               'model',
               [('array',
                 [('num', 1.0), ('num', 2.0), ('num', 3.0), ('num', 4.0)])]),
              0)]}