EXPECTED = {'classes': {'Graph': {'class_params': [('node_values',
                                         ('tensor', [('k', 'invariant')])),
                                        ('degrees',
                                         ('tensor', [('k', 'invariant')])),
                                        ('adjacency',
                                         ('tensor',
                                          [('k', 'invariant'),
                                           ('m', 'invariant')])),
                                        ('edge_weights',
                                         ('tensor',
                                          [('k', 'invariant'),
                                           ('m', 'invariant')]))],
                       'fields': [],
                       'methods': [{'body': ('mul',
                                             ('call',
                                              'len',
                                              [('field_access',
                                                ('var', 'this'),
                                                'node_values')]),
                                             ('num', 1.0)),
                                    'name': 'order',
                                    'params': [],
                                    'return_type': 'ℝ',
                                    'statements': []},
                                   {'body': ('index', 'vals', ('var', 'id')),
                                    'name': 'value_at',
                                    'params': [('id', 'ℝ')],
                                    'return_type': 'ℝ',
                                    'statements': [('body_decl',
                                                    'vals',
                                                    ('tensor',
                                                     [('k', 'invariant')]),
                                                    ('field_access',
                                                     ('var', 'this'),
                                                     'node_values'))]},
                                   {'body': ('index', 'degs', ('var', 'id')),
                                    'name': 'degree_of',
                                    'params': [('id', 'ℝ')],
                                    'return_type': 'ℝ',
                                    'statements': [('body_decl',
                                                    'degs',
                                                    ('tensor',
                                                     [('k', 'invariant')]),
                                                    ('field_access',
                                                     ('var', 'this'),
                                                     'degrees'))]},
                                   {'body': ('div',
                                             ('call', 'sum', [('var', 'degs')]),
                                             ('num', 2.0)),
                                    'name': 'size',
                                    'params': [],
                                    'return_type': 'ℝ',
                                    'statements': [('body_decl',
                                                    'degs',
                                                    ('tensor',
                                                     [('k', 'invariant')]),
                                                    ('field_access',
                                                     ('var', 'this'),
                                                     'degrees'))]},
                                   {'body': ('var', 'result'),
                                    'name': 'has_edge',
                                    'params': [('a', 'ℝ'), ('b', 'ℝ')],
                                    'return_type': 'ℝ',
                                    'statements': [('body_decl',
                                                    'adj',
                                                    ('tensor',
                                                     [('k', 'invariant'),
                                                      ('m', 'invariant')]),
                                                    ('field_access',
                                                     ('var', 'this'),
                                                     'adjacency')),
                                                   ('body_decl',
                                                    'row',
                                                    ('tensor',
                                                     [('m', 'invariant')]),
                                                    ('index',
                                                     'adj',
                                                     ('var', 'a'))),
                                                   ('body_decl',
                                                    'w',
                                                    'ℕ',
                                                    ('call',
                                                     'len',
                                                     [('var', 'row')])),
                                                   ('body_decl',
                                                    'result',
                                                    'ℝ',
                                                    ('num', 0.0)),
                                                   ('body_for_range',
                                                    'c',
                                                    ('num', 0),
                                                    ('var', 'w'),
                                                    [('loop_if',
                                                      ('cond_eq',
                                                       ('index',
                                                        'row',
                                                        ('var', 'c')),
                                                       ('var', 'b')),
                                                      [('loop_assign',
                                                        'result',
                                                        ('num', 1.0))])])]},
                                   {'body': ('var', 'result'),
                                    'name': 'weight_between',
                                    'params': [('a', 'ℝ'), ('b', 'ℝ')],
                                    'return_type': 'ℝ',
                                    'statements': [('body_decl',
                                                    'adj',
                                                    ('tensor',
                                                     [('k', 'invariant'),
                                                      ('m', 'invariant')]),
                                                    ('field_access',
                                                     ('var', 'this'),
                                                     'adjacency')),
                                                   ('body_decl',
                                                    'wts',
                                                    ('tensor',
                                                     [('k', 'invariant'),
                                                      ('m', 'invariant')]),
                                                    ('field_access',
                                                     ('var', 'this'),
                                                     'edge_weights')),
                                                   ('body_decl',
                                                    'row',
                                                    ('tensor',
                                                     [('m', 'invariant')]),
                                                    ('index',
                                                     'adj',
                                                     ('var', 'a'))),
                                                   ('body_decl',
                                                    'wrow',
                                                    ('tensor',
                                                     [('m', 'invariant')]),
                                                    ('index',
                                                     'wts',
                                                     ('var', 'a'))),
                                                   ('body_decl',
                                                    'w',
                                                    'ℕ',
                                                    ('call',
                                                     'len',
                                                     [('var', 'row')])),
                                                   ('body_decl',
                                                    'result',
                                                    'ℝ',
                                                    ('num', 0.0)),
                                                   ('body_for_range',
                                                    'c',
                                                    ('num', 0),
                                                    ('var', 'w'),
                                                    [('loop_if',
                                                      ('cond_eq',
                                                       ('index',
                                                        'row',
                                                        ('var', 'c')),
                                                       ('var', 'b')),
                                                      [('loop_assign',
                                                        'result',
                                                        ('index',
                                                         'wrow',
                                                         ('var', 'c')))])])]},
                                   {'body': ('call',
                                             'Node',
                                             [('var', 'this'),
                                              ('var', 'id'),
                                              ('index', 'degs', ('var', 'id')),
                                              ('var', 'arow'),
                                              ('var', 'wrow')]),
                                    'name': 'node',
                                    'params': [('id', 'ℝ')],
                                    'return_type': ('struct_type', 'Node'),
                                    'statements': [('body_decl',
                                                    'degs',
                                                    ('tensor',
                                                     [('k', 'invariant')]),
                                                    ('field_access',
                                                     ('var', 'this'),
                                                     'degrees')),
                                                   ('body_decl',
                                                    'adj',
                                                    ('tensor',
                                                     [('k', 'invariant'),
                                                      ('m', 'invariant')]),
                                                    ('field_access',
                                                     ('var', 'this'),
                                                     'adjacency')),
                                                   ('body_decl',
                                                    'wts',
                                                    ('tensor',
                                                     [('k', 'invariant'),
                                                      ('m', 'invariant')]),
                                                    ('field_access',
                                                     ('var', 'this'),
                                                     'edge_weights')),
                                                   ('body_decl',
                                                    'arow',
                                                    ('tensor',
                                                     [('m', 'invariant')]),
                                                    ('index',
                                                     'adj',
                                                     ('var', 'id'))),
                                                   ('body_decl',
                                                    'wrow',
                                                    ('tensor',
                                                     [('m', 'invariant')]),
                                                    ('index',
                                                     'wts',
                                                     ('var', 'id')))]},
                                   {'body': ('var', 'result'),
                                    'name': 'adjacency_matrix',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant'),
                                                     ('k', 'invariant')]),
                                    'statements': [('body_decl',
                                                    'adj',
                                                    ('tensor',
                                                     [('k', 'invariant'),
                                                      ('m', 'invariant')]),
                                                    ('field_access',
                                                     ('var', 'this'),
                                                     'adjacency')),
                                                   ('body_decl',
                                                    'n',
                                                    'ℕ',
                                                    ('call',
                                                     'len',
                                                     [('var', 'adj')])),
                                                   ('body_decl',
                                                    'row0',
                                                    ('tensor',
                                                     [('m', 'invariant')]),
                                                    ('index',
                                                     'adj',
                                                     ('num', 0))),
                                                   ('body_decl',
                                                    'w',
                                                    'ℕ',
                                                    ('call',
                                                     'len',
                                                     [('var', 'row0')])),
                                                   ('body_decl',
                                                    'result',
                                                    ('tensor',
                                                     [('k', 'invariant'),
                                                      ('k', 'invariant')]),
                                                    ('for_expr',
                                                     'a',
                                                     ('var', 'n'),
                                                     ('for_expr',
                                                      'b',
                                                      ('var', 'n'),
                                                      ('mul',
                                                       ('add',
                                                        ('var', 'a'),
                                                        ('var', 'b')),
                                                       ('num', 0.0))))),
                                                   ('body_for_range',
                                                    'a',
                                                    ('num', 0),
                                                    ('var', 'n'),
                                                    [('loop_for_range',
                                                      'c',
                                                      ('num', 0),
                                                      ('var', 'w'),
                                                      [('loop_assign',
                                                        'nb',
                                                        ('indexN',
                                                         'adj',
                                                         [('index_item',
                                                           ('var', 'a')),
                                                          ('index_item',
                                                           ('var', 'c'))])),
                                                       ('loop_if',
                                                        ('cond_geq',
                                                         ('var', 'nb'),
                                                         ('num', 0.0)),
                                                        [('loop_index_assign_nd',
                                                          'result',
                                                          [('index_item',
                                                            ('var', 'a')),
                                                           ('index_item',
                                                            ('var', 'nb'))],
                                                          ('num', 1.0))])])])]},
                                   {'body': ('var', 'result'),
                                    'name': 'weight_matrix',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant'),
                                                     ('k', 'invariant')]),
                                    'statements': [('body_decl',
                                                    'adj',
                                                    ('tensor',
                                                     [('k', 'invariant'),
                                                      ('m', 'invariant')]),
                                                    ('field_access',
                                                     ('var', 'this'),
                                                     'adjacency')),
                                                   ('body_decl',
                                                    'wts',
                                                    ('tensor',
                                                     [('k', 'invariant'),
                                                      ('m', 'invariant')]),
                                                    ('field_access',
                                                     ('var', 'this'),
                                                     'edge_weights')),
                                                   ('body_decl',
                                                    'n',
                                                    'ℕ',
                                                    ('call',
                                                     'len',
                                                     [('var', 'adj')])),
                                                   ('body_decl',
                                                    'row0',
                                                    ('tensor',
                                                     [('m', 'invariant')]),
                                                    ('index',
                                                     'adj',
                                                     ('num', 0))),
                                                   ('body_decl',
                                                    'w',
                                                    'ℕ',
                                                    ('call',
                                                     'len',
                                                     [('var', 'row0')])),
                                                   ('body_decl',
                                                    'result',
                                                    ('tensor',
                                                     [('k', 'invariant'),
                                                      ('k', 'invariant')]),
                                                    ('for_expr',
                                                     'a',
                                                     ('var', 'n'),
                                                     ('for_expr',
                                                      'b',
                                                      ('var', 'n'),
                                                      ('mul',
                                                       ('add',
                                                        ('var', 'a'),
                                                        ('var', 'b')),
                                                       ('num', 0.0))))),
                                                   ('body_for_range',
                                                    'a',
                                                    ('num', 0),
                                                    ('var', 'n'),
                                                    [('loop_for_range',
                                                      'c',
                                                      ('num', 0),
                                                      ('var', 'w'),
                                                      [('loop_assign',
                                                        'nb',
                                                        ('indexN',
                                                         'adj',
                                                         [('index_item',
                                                           ('var', 'a')),
                                                          ('index_item',
                                                           ('var', 'c'))])),
                                                       ('loop_if',
                                                        ('cond_geq',
                                                         ('var', 'nb'),
                                                         ('num', 0.0)),
                                                        [('loop_index_assign_nd',
                                                          'result',
                                                          [('index_item',
                                                            ('var', 'a')),
                                                           ('index_item',
                                                            ('var', 'nb'))],
                                                          ('indexN',
                                                           'wts',
                                                           [('index_item',
                                                             ('var', 'a')),
                                                            ('index_item',
                                                             ('var',
                                                              'c'))]))])])])]},
                                   {'body': ('var', 'out'),
                                    'name': 'degree_vector',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant')]),
                                    'statements': [('body_decl',
                                                    'degs',
                                                    ('tensor',
                                                     [('k', 'invariant')]),
                                                    ('field_access',
                                                     ('var', 'this'),
                                                     'degrees')),
                                                   ('body_decl',
                                                    'n',
                                                    'ℕ',
                                                    ('call',
                                                     'len',
                                                     [('var', 'degs')])),
                                                   ('body_decl',
                                                    'out',
                                                    ('tensor',
                                                     [('k', 'invariant')]),
                                                    ('for_expr',
                                                     'a',
                                                     ('var', 'n'),
                                                     ('add',
                                                      ('index',
                                                       'degs',
                                                       ('var', 'a')),
                                                      ('mul',
                                                       ('var', 'a'),
                                                       ('num', 0.0)))))]},
                                   {'body': ('var', 'result'),
                                    'name': 'laplacian',
                                    'params': [],
                                    'return_type': ('tensor',
                                                    [('k', 'invariant'),
                                                     ('k', 'invariant')]),
                                    'statements': [('body_decl',
                                                    'adj',
                                                    ('tensor',
                                                     [('k', 'invariant'),
                                                      ('m', 'invariant')]),
                                                    ('field_access',
                                                     ('var', 'this'),
                                                     'adjacency')),
                                                   ('body_decl',
                                                    'degs',
                                                    ('tensor',
                                                     [('k', 'invariant')]),
                                                    ('field_access',
                                                     ('var', 'this'),
                                                     'degrees')),
                                                   ('body_decl',
                                                    'n',
                                                    'ℕ',
                                                    ('call',
                                                     'len',
                                                     [('var', 'adj')])),
                                                   ('body_decl',
                                                    'row0',
                                                    ('tensor',
                                                     [('m', 'invariant')]),
                                                    ('index',
                                                     'adj',
                                                     ('num', 0))),
                                                   ('body_decl',
                                                    'w',
                                                    'ℕ',
                                                    ('call',
                                                     'len',
                                                     [('var', 'row0')])),
                                                   ('body_decl',
                                                    'result',
                                                    ('tensor',
                                                     [('k', 'invariant'),
                                                      ('k', 'invariant')]),
                                                    ('for_expr',
                                                     'a',
                                                     ('var', 'n'),
                                                     ('for_expr',
                                                      'b',
                                                      ('var', 'n'),
                                                      ('mul',
                                                       ('add',
                                                        ('var', 'a'),
                                                        ('var', 'b')),
                                                       ('num', 0.0))))),
                                                   ('body_for_range',
                                                    'a',
                                                    ('num', 0),
                                                    ('var', 'n'),
                                                    [('loop_index_assign_nd',
                                                      'result',
                                                      [('index_item',
                                                        ('var', 'a')),
                                                       ('index_item',
                                                        ('var', 'a'))],
                                                      ('index',
                                                       'degs',
                                                       ('var', 'a')))]),
                                                   ('body_for_range',
                                                    'a',
                                                    ('num', 0),
                                                    ('var', 'n'),
                                                    [('loop_for_range',
                                                      'c',
                                                      ('num', 0),
                                                      ('var', 'w'),
                                                      [('loop_assign',
                                                        'nb',
                                                        ('indexN',
                                                         'adj',
                                                         [('index_item',
                                                           ('var', 'a')),
                                                          ('index_item',
                                                           ('var', 'c'))])),
                                                       ('loop_if',
                                                        ('cond_geq',
                                                         ('var', 'nb'),
                                                         ('num', 0.0)),
                                                        [('loop_index_assign_nd',
                                                          'result',
                                                          [('index_item',
                                                            ('var', 'a')),
                                                           ('index_item',
                                                            ('var', 'nb'))],
                                                          ('sub',
                                                           ('indexN',
                                                            'result',
                                                            [('index_item',
                                                              ('var', 'a')),
                                                             ('index_item',
                                                              ('var', 'nb'))]),
                                                           ('num',
                                                            1.0)))])])])]}]},
             'Node': {'class_params': [('graph', ('struct_type', 'Graph')),
                                       ('id', 'ℝ'),
                                       ('degree', 'ℝ'),
                                       ('neighbors',
                                        ('tensor', [('m', 'invariant')])),
                                       ('weights',
                                        ('tensor', [('m', 'invariant')]))],
                      'fields': [],
                      'methods': [{'body': ('method_call',
                                            ('field_access',
                                             ('var', 'this'),
                                             'graph'),
                                            'value_at',
                                            [('field_access',
                                              ('var', 'this'),
                                              'id')]),
                                   'name': 'value',
                                   'params': [],
                                   'return_type': 'ℝ',
                                   'statements': []},
                                  {'body': ('field_access',
                                            ('var', 'this'),
                                            'degree'),
                                   'name': 'deg',
                                   'params': [],
                                   'return_type': 'ℝ',
                                   'statements': []},
                                  {'body': ('index', 'nbrs', ('var', 'slot')),
                                   'name': 'neighbor',
                                   'params': [('slot', 'ℝ')],
                                   'return_type': 'ℝ',
                                   'statements': [('body_decl',
                                                   'nbrs',
                                                   ('tensor',
                                                    [('m', 'invariant')]),
                                                   ('field_access',
                                                    ('var', 'this'),
                                                    'neighbors'))]},
                                  {'body': ('index', 'w', ('var', 'slot')),
                                   'name': 'edge_weight',
                                   'params': [('slot', 'ℝ')],
                                   'return_type': 'ℝ',
                                   'statements': [('body_decl',
                                                   'w',
                                                   ('tensor',
                                                    [('m', 'invariant')]),
                                                   ('field_access',
                                                    ('var', 'this'),
                                                    'weights'))]},
                                  {'body': ('var', 'total'),
                                   'name': 'weighted_degree',
                                   'params': [],
                                   'return_type': 'ℝ',
                                   'statements': [('body_decl',
                                                   'nbrs',
                                                   ('tensor',
                                                    [('m', 'invariant')]),
                                                   ('field_access',
                                                    ('var', 'this'),
                                                    'neighbors')),
                                                  ('body_decl',
                                                   'w',
                                                   ('tensor',
                                                    [('m', 'invariant')]),
                                                   ('field_access',
                                                    ('var', 'this'),
                                                    'weights')),
                                                  ('body_decl',
                                                   'k',
                                                   'ℕ',
                                                   ('call',
                                                    'len',
                                                    [('var', 'nbrs')])),
                                                  ('body_decl',
                                                   'total',
                                                   'ℝ',
                                                   ('num', 0.0)),
                                                  ('body_for_range',
                                                   'c',
                                                   ('num', 0),
                                                   ('var', 'k'),
                                                   [('loop_if',
                                                     ('cond_geq',
                                                      ('index',
                                                       'nbrs',
                                                       ('var', 'c')),
                                                      ('num', 0.0)),
                                                     [('loop_pluseq',
                                                       'total',
                                                       ('index',
                                                        'w',
                                                        ('var', 'c')))])])]},
                                  {'body': ('var', 'result'),
                                   'name': 'is_isolated',
                                   'params': [],
                                   'return_type': 'ℝ',
                                   'statements': [('body_decl',
                                                   'result',
                                                   'ℝ',
                                                   ('num', 0.0)),
                                                  ('body_if',
                                                   ('cond_eq',
                                                    ('field_access',
                                                     ('var', 'this'),
                                                     'degree'),
                                                    ('num', 0.0)),
                                                   [('body_assign',
                                                     'result',
                                                     ('num', 1.0))])]},
                                  {'body': ('var', 'result'),
                                   'name': 'is_adjacent_to',
                                   'params': [('b', 'ℝ')],
                                   'return_type': 'ℝ',
                                   'statements': [('body_decl',
                                                   'nbrs',
                                                   ('tensor',
                                                    [('m', 'invariant')]),
                                                   ('field_access',
                                                    ('var', 'this'),
                                                    'neighbors')),
                                                  ('body_decl',
                                                   'k',
                                                   'ℕ',
                                                   ('call',
                                                    'len',
                                                    [('var', 'nbrs')])),
                                                  ('body_decl',
                                                   'result',
                                                   'ℝ',
                                                   ('num', 0.0)),
                                                  ('body_for_range',
                                                   'c',
                                                   ('num', 0),
                                                   ('var', 'k'),
                                                   [('loop_if',
                                                     ('cond_eq',
                                                      ('index',
                                                       'nbrs',
                                                       ('var', 'c')),
                                                      ('var', 'b')),
                                                     [('loop_assign',
                                                       'result',
                                                       ('num', 1.0))])])]}]}},
 'functions': {'cycle_graph': {'body': ('call',
                                        'Graph',
                                        [('var', 'values'),
                                         ('var', 'degrees'),
                                         ('var', 'adjacency'),
                                         ('var', 'weights')]),
                               'has_loop': False,
                               'params': [('n_nodes', 'ℝ'), ('w', 'ℝ')],
                               'return_type': ('struct_type', 'Graph'),
                               'statements': [('body_decl',
                                               'values',
                                               ('tensor', [('k', 'invariant')]),
                                               ('for_expr',
                                                'a',
                                                ('var', 'n_nodes'),
                                                ('mul',
                                                 ('var', 'a'),
                                                 ('num', 1.0)))),
                                              ('body_decl',
                                               'adjacency',
                                               ('tensor',
                                                [('k', 'invariant'),
                                                 (2, 'invariant')]),
                                               ('for_expr',
                                                'a',
                                                ('var', 'n_nodes'),
                                                ('for_expr',
                                                 'c',
                                                 ('num', 2),
                                                 ('sub',
                                                  ('mul',
                                                   ('add',
                                                    ('var', 'a'),
                                                    ('var', 'c')),
                                                   ('num', 0.0)),
                                                  ('num', 1.0))))),
                                              ('body_decl',
                                               'weights',
                                               ('tensor',
                                                [('k', 'invariant'),
                                                 (2, 'invariant')]),
                                               ('for_expr',
                                                'a',
                                                ('var', 'n_nodes'),
                                                ('for_expr',
                                                 'c',
                                                 ('num', 2),
                                                 ('mul',
                                                  ('add',
                                                   ('var', 'a'),
                                                   ('var', 'c')),
                                                  ('num', 0.0))))),
                                              ('body_for_range',
                                               'a',
                                               ('num', 0),
                                               ('var', 'n_nodes'),
                                               [('loop_for_range',
                                                 's',
                                                 ('num', 0),
                                                 ('num', 2),
                                                 [('loop_assign',
                                                   'nb',
                                                   ('sub',
                                                    ('var', 'a'),
                                                    ('num', 1.0))),
                                                  ('loop_if',
                                                   ('cond_gt',
                                                    ('var', 's'),
                                                    ('num', 0.5)),
                                                   [('loop_assign',
                                                     'nb',
                                                     ('add',
                                                      ('var', 'a'),
                                                      ('num', 1.0)))]),
                                                  ('loop_if',
                                                   ('cond_lt',
                                                    ('var', 'nb'),
                                                    ('num', 0.0)),
                                                   [('loop_assign',
                                                     'nb',
                                                     ('sub',
                                                      ('var', 'n_nodes'),
                                                      ('num', 1.0)))]),
                                                  ('loop_if',
                                                   ('cond_gt',
                                                    ('var', 'nb'),
                                                    ('sub',
                                                     ('var', 'n_nodes'),
                                                     ('num', 0.5))),
                                                   [('loop_assign',
                                                     'nb',
                                                     ('num', 0.0))]),
                                                  ('loop_index_assign_nd',
                                                   'adjacency',
                                                   [('index_item',
                                                     ('var', 'a')),
                                                    ('index_item',
                                                     ('var', 's'))],
                                                   ('var', 'nb')),
                                                  ('loop_index_assign_nd',
                                                   'weights',
                                                   [('index_item',
                                                     ('var', 'a')),
                                                    ('index_item',
                                                     ('var', 's'))],
                                                   ('var', 'w'))])]),
                                              ('body_decl',
                                               'degrees',
                                               ('tensor', [('k', 'invariant')]),
                                               ('for_expr',
                                                'a',
                                                ('var', 'n_nodes'),
                                                ('add',
                                                 ('num', 2.0),
                                                 ('mul',
                                                  ('var', 'a'),
                                                  ('num', 0.0)))))]},
               'grid_graph': {'body': ('call',
                                       'Graph',
                                       [('var', 'values'),
                                        ('var', 'degrees'),
                                        ('var', 'adjacency'),
                                        ('var', 'weights')]),
                              'has_loop': False,
                              'params': [('rows', 'ℝ'), ('cols', 'ℝ')],
                              'return_type': ('struct_type', 'Graph'),
                              'statements': [('body_decl',
                                              'n_nodes',
                                              'ℝ',
                                              ('mul',
                                               ('var', 'rows'),
                                               ('var', 'cols'))),
                                             ('body_decl',
                                              'values',
                                              ('tensor', [('k', 'invariant')]),
                                              ('for_expr',
                                               'a',
                                               ('var', 'n_nodes'),
                                               ('mul',
                                                ('var', 'a'),
                                                ('num', 1.0)))),
                                             ('body_decl',
                                              'adjacency',
                                              ('tensor',
                                               [('k', 'invariant'),
                                                (4, 'invariant')]),
                                              ('for_expr',
                                               'a',
                                               ('var', 'n_nodes'),
                                               ('for_expr',
                                                'c',
                                                ('num', 4),
                                                ('sub',
                                                 ('mul',
                                                  ('add',
                                                   ('var', 'a'),
                                                   ('var', 'c')),
                                                  ('num', 0.0)),
                                                 ('num', 1.0))))),
                                             ('body_decl',
                                              'weights',
                                              ('tensor',
                                               [('k', 'invariant'),
                                                (4, 'invariant')]),
                                              ('for_expr',
                                               'a',
                                               ('var', 'n_nodes'),
                                               ('for_expr',
                                                'c',
                                                ('num', 4),
                                                ('mul',
                                                 ('add',
                                                  ('var', 'a'),
                                                  ('var', 'c')),
                                                 ('num', 0.0))))),
                                             ('body_for_range',
                                              'r',
                                              ('num', 0),
                                              ('var', 'rows'),
                                              [('loop_for_range',
                                                'c',
                                                ('num', 0),
                                                ('var', 'cols'),
                                                [('loop_assign',
                                                  'idx',
                                                  ('add',
                                                   ('mul',
                                                    ('var', 'r'),
                                                    ('var', 'cols')),
                                                   ('var', 'c'))),
                                                 ('loop_if',
                                                  ('cond_gt',
                                                   ('var', 'r'),
                                                   ('num', 0)),
                                                  [('loop_index_assign_nd',
                                                    'adjacency',
                                                    [('index_item',
                                                      ('var', 'idx')),
                                                     ('index_item',
                                                      ('num', 0))],
                                                    ('sub',
                                                     ('var', 'idx'),
                                                     ('var', 'cols'))),
                                                   ('loop_index_assign_nd',
                                                    'weights',
                                                    [('index_item',
                                                      ('var', 'idx')),
                                                     ('index_item',
                                                      ('num', 0))],
                                                    ('num', 1.0))]),
                                                 ('loop_if',
                                                  ('cond_lt',
                                                   ('var', 'r'),
                                                   ('sub',
                                                    ('var', 'rows'),
                                                    ('num', 1))),
                                                  [('loop_index_assign_nd',
                                                    'adjacency',
                                                    [('index_item',
                                                      ('var', 'idx')),
                                                     ('index_item',
                                                      ('num', 1))],
                                                    ('add',
                                                     ('var', 'idx'),
                                                     ('var', 'cols'))),
                                                   ('loop_index_assign_nd',
                                                    'weights',
                                                    [('index_item',
                                                      ('var', 'idx')),
                                                     ('index_item',
                                                      ('num', 1))],
                                                    ('num', 1.0))]),
                                                 ('loop_if',
                                                  ('cond_gt',
                                                   ('var', 'c'),
                                                   ('num', 0)),
                                                  [('loop_index_assign_nd',
                                                    'adjacency',
                                                    [('index_item',
                                                      ('var', 'idx')),
                                                     ('index_item',
                                                      ('num', 2))],
                                                    ('sub',
                                                     ('var', 'idx'),
                                                     ('num', 1.0))),
                                                   ('loop_index_assign_nd',
                                                    'weights',
                                                    [('index_item',
                                                      ('var', 'idx')),
                                                     ('index_item',
                                                      ('num', 2))],
                                                    ('num', 1.0))]),
                                                 ('loop_if',
                                                  ('cond_lt',
                                                   ('var', 'c'),
                                                   ('sub',
                                                    ('var', 'cols'),
                                                    ('num', 1))),
                                                  [('loop_index_assign_nd',
                                                    'adjacency',
                                                    [('index_item',
                                                      ('var', 'idx')),
                                                     ('index_item',
                                                      ('num', 3))],
                                                    ('add',
                                                     ('var', 'idx'),
                                                     ('num', 1.0))),
                                                   ('loop_index_assign_nd',
                                                    'weights',
                                                    [('index_item',
                                                      ('var', 'idx')),
                                                     ('index_item',
                                                      ('num', 3))],
                                                    ('num', 1.0))])])]),
                                             ('body_decl',
                                              'degrees',
                                              ('tensor', [('k', 'invariant')]),
                                              ('for_expr',
                                               'a',
                                               ('var', 'n_nodes'),
                                               ('mul',
                                                ('var', 'a'),
                                                ('num', 0.0)))),
                                             ('body_for_range',
                                              'a',
                                              ('num', 0),
                                              ('var', 'n_nodes'),
                                              [('loop_for_range',
                                                'c',
                                                ('num', 0),
                                                ('num', 4),
                                                [('loop_if',
                                                  ('cond_geq',
                                                   ('indexN',
                                                    'adjacency',
                                                    [('index_item',
                                                      ('var', 'a')),
                                                     ('index_item',
                                                      ('var', 'c'))]),
                                                   ('num', 0.0)),
                                                  [('loop_index_pluseq',
                                                    'degrees',
                                                    [('index_item',
                                                      ('var', 'a'))],
                                                    ('num', 1.0))])])])]}},
 'program': [('class_def', 'Graph'),
             ('class_def', 'Node'),
             ('func_def', 'cycle_graph'),
             ('func_def', 'grid_graph'),
             ('assign',
              'c4',
              ('call', 'cycle_graph', [('num', 4.0), ('num', 1.0)]),
              234),
             ('expr', ('method_call', ('var', 'c4'), 'order', []), 0),
             ('expr', ('method_call', ('var', 'c4'), 'size', []), 0),
             ('expr',
              ('method_call', ('var', 'c4'), 'degree_of', [('num', 0.0)]),
              0),
             ('expr',
              ('method_call',
               ('var', 'c4'),
               'has_edge',
               [('num', 0.0), ('num', 1.0)]),
              0),
             ('expr',
              ('method_call',
               ('var', 'c4'),
               'has_edge',
               [('num', 0.0), ('num', 2.0)]),
              0),
             ('expr',
              ('method_call', ('var', 'c4'), 'adjacency_matrix', []),
              0),
             ('expr', ('method_call', ('var', 'c4'), 'laplacian', []), 0),
             ('assign',
              'v0',
              ('method_call', ('var', 'c4'), 'node', [('num', 0.0)]),
              244),
             ('expr', ('method_call', ('var', 'v0'), 'value', []), 0),
             ('expr', ('method_call', ('var', 'v0'), 'deg', []), 0),
             ('expr',
              ('method_call', ('var', 'v0'), 'neighbor', [('num', 0.0)]),
              0),
             ('expr',
              ('method_call', ('var', 'v0'), 'neighbor', [('num', 1.0)]),
              0),
             ('expr', ('method_call', ('var', 'v0'), 'weighted_degree', []), 0),
             ('expr', ('method_call', ('var', 'v0'), 'is_isolated', []), 0),
             ('expr',
              ('method_call', ('var', 'v0'), 'is_adjacent_to', [('num', 3.0)]),
              0),
             ('expr',
              ('method_call', ('var', 'v0'), 'is_adjacent_to', [('num', 2.0)]),
              0),
             ('assign',
              'g',
              ('call', 'grid_graph', [('num', 2.0), ('num', 3.0)]),
              256),
             ('expr', ('method_call', ('var', 'g'), 'order', []), 0),
             ('expr', ('method_call', ('var', 'g'), 'size', []), 0),
             ('expr',
              ('method_call', ('var', 'g'), 'degree_of', [('num', 1.0)]),
              0),
             ('expr',
              ('method_call', ('var', 'g'), 'degree_of', [('num', 0.0)]),
              0),
             ('expr',
              ('method_call',
               ('var', 'g'),
               'weight_between',
               [('num', 0.0), ('num', 1.0)]),
              0),
             ('expr',
              ('method_call',
               ('var', 'g'),
               'weight_between',
               [('num', 0.0), ('num', 5.0)]),
              0),
             ('expr', ('method_call', ('var', 'g'), 'degree_vector', []), 0),
             ('expr', ('method_call', ('var', 'g'), 'weight_matrix', []), 0),
             ('expr', ('method_call', ('var', 'g'), 'laplacian', []), 0)]}
