EXPECTED = {'classes': {},
 'functions': {},
 'program': [('decl', 'α', 'ℝ', ('num', 1.0), 2),
             ('decl', 'β', 'ℝ', ('num', 2.0), 3),
             ('decl', 'x', 'ℝ', ('num', 100000.0), 4),
             ('decl', 'y', 'ℝ', ('num', 300000.0), 5),
             ('assign', 'results', ('add', ('var', 'α'), ('var', 'β')), 9),
             ('expr', ('var', 'results'), 0),
             ('assign', 'z', ('add', ('var', 'x'), ('var', 'y')), 11),
             ('expr', ('var', 'z'), 0),
             ('assign',
              'greek_letters_array',
              ('array', [('var', 'α'), ('var', 'β')]),
              15),
             ('expr', ('var', 'greek_letters_array'), 0)]}