EXPECTED = {'functions': {'f': {'params': [('x', ('tensor', [('m', 'invariant')]))],
                     'return_type': ('tensor', [('m', 'invariant')]),
                     'body': ('add',
                              ('pow', ('var', 'x'), ('num', 2)),
                              ('num', 1)),
                     'has_loop': False,
                     'statements': []}},
 'classes': {},
 'program': [('decl', 'α', 'ℝ', ('num', 1.0), 2),
             ('decl', 'β', 'ℝ', ('num', 2.0), 3),
             ('decl', 'x', 'ℝ', ('num', 100000.0), 4),
             ('decl', 'y', 'ℝ', ('num', 300000.0), 5),
             ('decl', 'results', 'ℝ', ('add', ('var', 'α'), ('var', 'β')), 9),
             ('expr', ('var', 'results'), 0),
             ('decl', 'z', 'ℝ', ('add', ('var', 'x'), ('var', 'y')), 11),
             ('expr', ('var', 'z'), 0),
             ('decl',
              'greek_letters_array',
              ('tensor', [(2, 'invariant')]),
              ('array', [('var', 'α'), ('var', 'β')]),
              16),
             ('expr', ('var', 'greek_letters_array'), 0),
             ('func_def', 'f'),
             ('decl',
              'μ',
              ('tensor', [(1, 'invariant')]),
              ('array', [('num', 2)]),
              24),
             ('assign',
              'grad_μ',
              ('call', 'grad', [('var', 'f'), ('var', 'μ')]),
              25),
             ('expr', ('var', 'grad_μ'), 0),
             ('decl', 'ℏ', 'ℝ', ('num', 1.0546e-34), 31),
             ('decl', 'σ', 'ℝ', ('num', 5.6704e-08), 32),
             ('decl', 'ψ', 'ℝ', ('num', 0.5), 33),
             ('decl', 'threshold', 'ℝ', ('num', 1.5), 37),
             ('if_else',
              ('cond_lt', ('var', 'α'), ('var', 'threshold')),
              [('for_assign',
                'result_if',
                ('mul', ('var', 'α'), ('var', 'β')))],
              [('for_assign',
                'result_if',
                ('add', ('var', 'α'), ('var', 'β')))]),
             ('expr', ('var', 'result_if'), 0),
             ('decl',
              'Ω',
              ('tensor', [(5, 'invariant')]),
              ('array',
               [('num', 0.1),
                ('num', 0.2),
                ('num', 0.3),
                ('num', 0.4),
                ('num', 0.5)]),
              46),
             ('decl', 'sum_Ω', 'ℝ', ('num', 0), 47),
             ('for_loop',
              'i',
              [('for_pluseq', 'sum_Ω', ('index', 'Ω', ('imaginary',)))],
              ['Ω'],
              49),
             ('expr', ('var', 'sum_Ω'), 0)]}
