EXPECTED = {'functions': {'get_1d_array_length': {'params': [('x',
                                                   ('tensor',
                                                    [('m', 'invariant')]))],
                                       'return_type': 'ℝ',
                                       'body': ('var', 'total'),
                                       'has_loop': False,
                                       'statements': [('body_decl',
                                                       'total',
                                                       'ℝ',
                                                       ('num', 0)),
                                                      ('body_decl',
                                                       'temp',
                                                       'ℝ',
                                                       ('num', 0)),
                                                      ('body_for',
                                                       'i',
                                                       [('loop_assign',
                                                         'temp',
                                                         ('index',
                                                          'x',
                                                          ('imaginary',))),
                                                        ('loop_pluseq',
                                                         'total',
                                                         ('num', 1))],
                                                       ['x'])]},
               'zero_1d_array': {'params': [('len', 'ℝ')],
                                 'return_type': ('tensor',
                                                 [('m', 'invariant')]),
                                 'body': ('var', 'results'),
                                 'has_loop': False,
                                 'statements': [('body_decl',
                                                 'results',
                                                 ('tensor',
                                                  [('len', 'invariant')]),
                                                 ('for_expr',
                                                  'i',
                                                  ('var', 'len'),
                                                  ('mul',
                                                   ('imaginary',),
                                                   ('num', 0))))]},
               'zero_2d_array': {'params': [('rows', 'ℝ'), ('cols', 'ℝ')],
                                 'return_type': ('tensor',
                                                 [('m', 'invariant'),
                                                  ('n', 'invariant')]),
                                 'body': ('var', 'results'),
                                 'has_loop': False,
                                 'statements': [('body_decl',
                                                 'results',
                                                 ('tensor',
                                                  [('rows', 'invariant'),
                                                   ('cols', 'invariant')]),
                                                 ('for_expr',
                                                  'i',
                                                  ('var', 'rows'),
                                                  ('for_expr',
                                                   'j',
                                                   ('var', 'cols'),
                                                   ('mul',
                                                    ('var', 'j'),
                                                    ('num', 0)))))]},
               'solve': {'params': [('A',
                                     ('tensor',
                                      [('m', 'invariant'),
                                       ('m', 'invariant')])),
                                    ('b', ('tensor', [('m', 'invariant')]))],
                         'return_type': ('tensor', [('m', 'invariant')]),
                         'body': ('var', 'result'),
                         'has_loop': False,
                         'statements': [('body_decl',
                                         'n',
                                         'ℝ',
                                         ('call',
                                          'get_1d_array_length',
                                          [('var', 'b')])),
                                        ('body_decl',
                                         'Aug',
                                         ('tensor',
                                          [('m', 'invariant'),
                                           ('m', 'invariant')]),
                                         ('call',
                                          'zero_2d_array',
                                          [('var', 'n'),
                                           ('add', ('var', 'n'), ('num', 1))])),
                                        ('body_decl',
                                         'result',
                                         ('tensor', [('m', 'invariant')]),
                                         ('call',
                                          'zero_1d_array',
                                          [('var', 'n')])),
                                        ('body_for_range',
                                         'i',
                                         ('num', 0),
                                         ('var', 'n'),
                                         [('loop_for_range',
                                           'j',
                                           ('num', 0),
                                           ('var', 'n'),
                                           [('loop_index_assign_nd',
                                             'Aug',
                                             [('imaginary',), ('var', 'j')],
                                             ('indexN',
                                              'A',
                                              [('imaginary',),
                                               ('var', 'j')]))]),
                                          ('loop_index_assign_nd',
                                           'Aug',
                                           [('imaginary',), ('var', 'n')],
                                           ('index', 'b', ('imaginary',)))]),
                                        ('body_for_range',
                                         'pivot',
                                         ('num', 0),
                                         ('var', 'n'),
                                         [('loop_for_range',
                                           'i',
                                           ('add',
                                            ('var', 'pivot'),
                                            ('num', 1)),
                                           ('var', 'n'),
                                           [('loop_assign',
                                             'factor',
                                             ('div',
                                              ('indexN',
                                               'Aug',
                                               [('imaginary',),
                                                ('var', 'pivot')]),
                                              ('indexN',
                                               'Aug',
                                               [('var', 'pivot'),
                                                ('var', 'pivot')]))),
                                            ('loop_for_range',
                                             'j',
                                             ('var', 'pivot'),
                                             ('add', ('var', 'n'), ('num', 1)),
                                             [('loop_index_assign_nd',
                                               'Aug',
                                               [('imaginary',), ('var', 'j')],
                                               ('sub',
                                                ('indexN',
                                                 'Aug',
                                                 [('imaginary',),
                                                  ('var', 'j')]),
                                                ('mul',
                                                 ('var', 'factor'),
                                                 ('indexN',
                                                  'Aug',
                                                  [('var', 'pivot'),
                                                   ('var', 'j')]))))])])]),
                                        ('body_for_range',
                                         'i',
                                         ('num', 0),
                                         ('var', 'n'),
                                         [('loop_assign',
                                           'ri',
                                           ('sub',
                                            ('sub', ('var', 'n'), ('num', 1)),
                                            ('imaginary',))),
                                          ('loop_index_assign_nd',
                                           'result',
                                           [('var', 'ri')],
                                           ('indexN',
                                            'Aug',
                                            [('var', 'ri'), ('var', 'n')])),
                                          ('loop_for_range',
                                           'j',
                                           ('add', ('var', 'ri'), ('num', 1)),
                                           ('var', 'n'),
                                           [('loop_index_assign_nd',
                                             'result',
                                             [('var', 'ri')],
                                             ('sub',
                                              ('index',
                                               'result',
                                               ('var', 'ri')),
                                              ('mul',
                                               ('indexN',
                                                'Aug',
                                                [('var', 'ri'), ('var', 'j')]),
                                               ('index',
                                                'result',
                                                ('var', 'j')))))]),
                                          ('loop_index_assign_nd',
                                           'result',
                                           [('var', 'ri')],
                                           ('div',
                                            ('index', 'result', ('var', 'ri')),
                                            ('indexN',
                                             'Aug',
                                             [('var', 'ri'),
                                              ('var', 'ri')])))])]},
               'U': {'params': [('k', 'ℝ'),
                                ('m', 'ℝ'),
                                ('t', 'ℝ'),
                                ('x0', 'ℝ'),
                                ('v0', 'ℝ')],
                     'return_type': 'ℝ',
                     'body': ('add',
                              ('mul',
                               ('var', 'a'),
                               ('call',
                                'cos',
                                [('mul', ('var', 'omega'), ('var', 't'))])),
                              ('mul',
                               ('var', 'b'),
                               ('call',
                                'sin',
                                [('mul', ('var', 'omega'), ('var', 't'))]))),
                     'has_loop': False,
                     'statements': [('body_decl',
                                     'omega',
                                     'ℝ',
                                     ('pow',
                                      ('div', ('var', 'k'), ('var', 'm')),
                                      ('num', 0.5))),
                                    ('body_decl',
                                     'A',
                                     ('tensor',
                                      [(2, 'invariant'), (2, 'invariant')]),
                                     ('array',
                                      [('array', [('num', 1.0), ('num', 0.0)]),
                                       ('array',
                                        [('num', 0.0), ('var', 'omega')])])),
                                    ('body_decl',
                                     'B',
                                     ('tensor', [(2, 'invariant')]),
                                     ('array', [('var', 'x0'), ('var', 'v0')])),
                                    ('body_decl',
                                     'coeffs',
                                     ('tensor', [(2, 'invariant')]),
                                     ('call',
                                      'solve',
                                      [('var', 'A'), ('var', 'B')])),
                                    ('body_decl',
                                     'a',
                                     'ℝ',
                                     ('index', 'coeffs', ('num', 0))),
                                    ('body_decl',
                                     'b',
                                     'ℝ',
                                     ('index', 'coeffs', ('num', 1)))]}},
 'classes': {},
 'program': [('func_def', 'get_1d_array_length'),
             ('func_def', 'zero_1d_array'),
             ('func_def', 'zero_2d_array'),
             ('func_def', 'solve'),
             ('func_def', 'U'),
             ('decl', 'k', 'ℝ', ('num', 1.0), 93),
             ('decl', 'm', 'ℝ', ('num', 1.0), 94),
             ('decl', 'x0', 'ℝ', ('num', 1.0), 97),
             ('decl', 'v0', 'ℝ', ('num', 0.0), 98),
             ('expr',
              ('call',
               'U',
               [('var', 'k'),
                ('var', 'm'),
                ('num', 0.0),
                ('var', 'x0'),
                ('var', 'v0')]),
              0),
             ('expr',
              ('call',
               'U',
               [('var', 'k'),
                ('var', 'm'),
                ('num', 1.5708),
                ('var', 'x0'),
                ('var', 'v0')]),
              0),
             ('expr',
              ('call',
               'U',
               [('var', 'k'),
                ('var', 'm'),
                ('num', 3.1416),
                ('var', 'x0'),
                ('var', 'v0')]),
              0),
             ('expr',
              ('call',
               'U',
               [('var', 'k'),
                ('var', 'm'),
                ('num', 4.7124),
                ('var', 'x0'),
                ('var', 'v0')]),
              0),
             ('expr',
              ('call',
               'U',
               [('var', 'k'),
                ('var', 'm'),
                ('num', 6.2832),
                ('var', 'x0'),
                ('var', 'v0')]),
              0),
             ('expr',
              ('call',
               'U',
               [('var', 'k'),
                ('var', 'm'),
                ('num', 0.0),
                ('num', 0.0),
                ('num', 1.0)]),
              0),
             ('expr',
              ('call',
               'U',
               [('var', 'k'),
                ('var', 'm'),
                ('num', 1.5708),
                ('num', 0.0),
                ('num', 1.0)]),
              0),
             ('expr',
              ('call',
               'U',
               [('var', 'k'),
                ('var', 'm'),
                ('num', 3.1416),
                ('num', 0.0),
                ('num', 1.0)]),
              0),
             ('expr',
              ('call',
               'animate',
               [('var', 'U'),
                ('var', 'k'),
                ('var', 'm'),
                ('var', 'x0'),
                ('var', 'v0'),
                ('num', 0.0),
                ('num', 31.1416)]),
              0),
             ('decl', 't0', 'ℝ', ('num', 0.0), 135),
             ('expr',
              ('call',
               'grad',
               [('call',
                 'U',
                 [('var', 'k'),
                  ('var', 'm'),
                  ('var', 't0'),
                  ('var', 'x0'),
                  ('var', 'v0')]),
                ('var', 't0')]),
              0),
             ('decl', 't1', 'ℝ', ('num', 1.5708), 138),
             ('expr',
              ('call',
               'grad',
               [('call',
                 'U',
                 [('var', 'k'),
                  ('var', 'm'),
                  ('var', 't1'),
                  ('var', 'x0'),
                  ('var', 'v0')]),
                ('var', 't1')]),
              0),
             ('decl', 't2', 'ℝ', ('num', 3.1416), 141),
             ('expr',
              ('call',
               'grad',
               [('call',
                 'U',
                 [('var', 'k'),
                  ('var', 'm'),
                  ('var', 't2'),
                  ('var', 'x0'),
                  ('var', 'v0')]),
                ('var', 't2')]),
              0)]}
