EXPECTED = {'functions': {'tanh': {'params': [('x', 'ℝ')],
                        'return_type': 'ℝ',
                        'body': ('div',
                                 ('sub',
                                  ('call', 'exp', [('var', 'x')]),
                                  ('call',
                                   'exp',
                                   [('sub', ('num', 0.0), ('var', 'x'))])),
                                 ('add',
                                  ('call', 'exp', [('var', 'x')]),
                                  ('call',
                                   'exp',
                                   [('sub', ('num', 0.0), ('var', 'x'))]))),
                        'has_loop': False,
                        'statements': []}},
 'classes': {'HamiltonianNet': {'class_params': [('W1',
                                                  ('tensor',
                                                   [('M', 'invariant'),
                                                    ('N', 'invariant')])),
                                                 ('b1',
                                                  ('tensor',
                                                   [('M', 'invariant')])),
                                                 ('w2',
                                                  ('tensor',
                                                   [('M', 'invariant')])),
                                                 ('b2', 'ℝ')],
                                'lambda_params': [('x',
                                                   ('tensor',
                                                    [('m', 'invariant')]))],
                                'return_type': ('tensor', [('n', 'invariant')]),
                                'body': ('array',
                                         [('var', 'dh_dp'), ('var', 'dh_dq')]),
                                'statements': [('body_decl',
                                                'h',
                                                'ℝ',
                                                ('add',
                                                 ('matmul',
                                                  ('var', 'w2'),
                                                  ('call',
                                                   'tanh',
                                                   [('add',
                                                     ('matmul',
                                                      ('var', 'W1'),
                                                      ('var', 'x')),
                                                     ('var', 'b1'))])),
                                                 ('var', 'b2'))),
                                               ('body_decl',
                                                'dh_dp',
                                                'ℝ',
                                                ('call_index',
                                                 'grad',
                                                 [('var', 'h'), ('var', 'x')],
                                                 ('num', 1.0))),
                                               ('body_decl',
                                                'dh_dq',
                                                'ℝ',
                                                ('neg',
                                                 ('call_index',
                                                  'grad',
                                                  [('var', 'h'), ('var', 'x')],
                                                  ('num', 0.0))))],
                                'has_loop': False,
                                'has_loss': True,
                                'loss_params': [('symplectic_gradient',
                                                 ('tensor',
                                                  [(2, 'invariant')])),
                                                ('target',
                                                 ('tensor',
                                                  [('N', 'invariant')]))],
                                'loss_statements': [('body_decl',
                                                     'lo',
                                                     'ℝ',
                                                     ('add',
                                                      ('pow',
                                                       ('sub',
                                                        ('index',
                                                         'symplectic_gradient',
                                                         ('num', 0.0)),
                                                        ('index',
                                                         'target',
                                                         ('num', 0.0))),
                                                       ('num', 2.0)),
                                                      ('pow',
                                                       ('sub',
                                                        ('index',
                                                         'symplectic_gradient',
                                                         ('num', 1.0)),
                                                        ('index',
                                                         'target',
                                                         ('num', 1.0))),
                                                       ('num', 2.0))))],
                                'loss_body': ('var', 'lo')}},
 'program': [('func_def', 'tanh'),
             ('class_def', 'HamiltonianNet'),
             ('decl',
              'X',
              ('tensor', [(8, 'invariant'), (2, 'invariant')]),
              ('array',
               [('array', [('num', 0.0), ('num', 1.0)]),
                ('array', [('num', 1.0), ('num', 0.0)]),
                ('array', [('num', 0.0), ('neg', ('num', 1.0))]),
                ('array', [('neg', ('num', 1.0)), ('num', 0.0)]),
                ('array', [('num', 0.5), ('num', 0.5)]),
                ('array', [('neg', ('num', 0.5)), ('neg', ('num', 0.5))]),
                ('array', [('num', 0.7), ('neg', ('num', 0.7))]),
                ('array', [('neg', ('num', 0.7)), ('num', 0.7)])]),
              33),
             ('decl',
              'y',
              ('tensor', [(8, 'invariant'), (2, 'invariant')]),
              ('array',
               [('array', [('num', 1.0), ('num', 0.0)]),
                ('array', [('num', 0.0), ('neg', ('num', 1.0))]),
                ('array', [('neg', ('num', 1.0)), ('num', 0.0)]),
                ('array', [('num', 0.0), ('num', 1.0)]),
                ('array', [('num', 0.5), ('neg', ('num', 0.5))]),
                ('array', [('neg', ('num', 0.5)), ('num', 0.5)]),
                ('array', [('neg', ('num', 0.7)), ('neg', ('num', 0.7))]),
                ('array', [('num', 0.7), ('num', 0.7)])]),
              35),
             ('decl',
              'W1',
              ('tensor', [(16, 'invariant'), (2, 'invariant')]),
              ('array',
               [('array', [('num', 0.5), ('num', 0.1)]),
                ('array', [('num', 0.1), ('num', 0.5)]),
                ('array', [('num', 0.3), ('num', 0.3)]),
                ('array', [('num', 0.4), ('num', 0.2)]),
                ('array', [('num', 0.2), ('num', 0.4)]),
                ('array', [('num', 0.1), ('num', 0.1)]),
                ('array', [('num', 0.3), ('num', 0.1)]),
                ('array', [('num', 0.1), ('num', 0.3)]),
                ('array', [('num', 0.2), ('num', 0.2)]),
                ('array', [('num', 0.4), ('num', 0.4)]),
                ('array', [('num', 0.5), ('num', 0.3)]),
                ('array', [('num', 0.3), ('num', 0.5)]),
                ('array', [('num', 0.2), ('num', 0.1)]),
                ('array', [('num', 0.1), ('num', 0.2)]),
                ('array', [('num', 0.4), ('num', 0.1)]),
                ('array', [('num', 0.1), ('num', 0.4)])]),
              41),
             ('decl',
              'b1',
              ('tensor', [(16, 'invariant')]),
              ('array',
               [('num', 0.0),
                ('num', 0.0),
                ('num', 0.0),
                ('num', 0.0),
                ('num', 0.0),
                ('num', 0.0),
                ('num', 0.0),
                ('num', 0.0),
                ('num', 0.0),
                ('num', 0.0),
                ('num', 0.0),
                ('num', 0.0),
                ('num', 0.0),
                ('num', 0.0),
                ('num', 0.0),
                ('num', 0.0)]),
              45),
             ('decl',
              'w2',
              ('tensor', [(16, 'invariant')]),
              ('array',
               [('num', 0.1),
                ('num', 0.1),
                ('num', 0.1),
                ('num', 0.1),
                ('num', 0.1),
                ('num', 0.1),
                ('num', 0.1),
                ('num', 0.1),
                ('num', 0.1),
                ('num', 0.1),
                ('num', 0.1),
                ('num', 0.1),
                ('num', 0.1),
                ('num', 0.1),
                ('num', 0.1),
                ('num', 0.1)]),
              47),
             ('decl', 'b2', 'ℝ', ('num', 0.0), 49),
             ('assign',
              'H_net',
              ('call',
               'HamiltonianNet',
               [('var', 'W1'), ('var', 'b1'), ('var', 'w2'), ('var', 'b2')]),
              51),
             ('assign',
              'loss_before',
              ('call',
               'evaluate',
               [('var', 'H_net'), ('var', 'X'), ('var', 'y')]),
              56),
             ('expr', ('var', 'loss_before'), 0),
             ('decl', 'epochs', 'ℕ', ('num', 500.0), 63),
             ('decl', 'lr', 'ℝ', ('num', 0.01), 64),
             ('assign',
              'H_trained',
              ('call',
               'train',
               [('var', 'H_net'),
                ('var', 'X'),
                ('var', 'y'),
                ('var', 'epochs'),
                ('var', 'lr')]),
              65),
             ('assign',
              'loss_after',
              ('call',
               'evaluate',
               [('var', 'H_trained'), ('var', 'X'), ('var', 'y')]),
              70),
             ('expr', ('var', 'loss_after'), 0)]}
