EXPECTED = {'functions': {'tanh': {'params': [('x', 'ℝ')],
                        'return_type': 'ℝ',
                        'body': ('div',
                                 ('sub',
                                  ('call', 'exp', [('var', 'x')]),
                                  ('call',
                                   'exp',
                                   [('sub', ('num', 0.0), ('var', 'x'))])),
                                 ('add',
                                  ('call', 'exp', [('var', 'x')]),
                                  ('call',
                                   'exp',
                                   [('sub', ('num', 0.0), ('var', 'x'))]))),
                        'has_loop': False,
                        'statements': []}},
 'classes': {'HamiltonianNet': {'class_params': [('W1',
                                                  ('tensor',
                                                   'ℝ',
                                                   [('M', 'invariant'),
                                                    ('N', 'invariant')])),
                                                 ('b1',
                                                  ('tensor',
                                                   'ℝ',
                                                   [('M', 'invariant'),
                                                    (1, 'invariant')])),
                                                 ('w2',
                                                  ('tensor',
                                                   'ℝ',
                                                   [(1, 'invariant'),
                                                    ('M', 'invariant')])),
                                                 ('b2', 'ℝ')],
                                'fields': [],
                                'methods': [{'name': 'λ',
                                             'params': [('x',
                                                         ('tensor',
                                                          'ℝ',
                                                          [('N', 'invariant'),
                                                           (1, 'invariant')]))],
                                             'return_type': ('tensor',
                                                             'ℝ',
                                                             [(2, 'invariant'),
                                                              (1,
                                                               'invariant')]),
                                             'statements': [('body_decl',
                                                             'h',
                                                             ('tensor',
                                                              'ℝ',
                                                              [(1, 'invariant'),
                                                               (1,
                                                                'invariant')]),
                                                             ('add',
                                                              ('matmul',
                                                               ('var', 'w2'),
                                                               ('call',
                                                                'tanh',
                                                                [('add',
                                                                  ('matmul',
                                                                   ('var',
                                                                    'W1'),
                                                                   ('var',
                                                                    'x')),
                                                                  ('var',
                                                                   'b1'))])),
                                                              ('var', 'b2'))),
                                                            ('body_assign',
                                                             'dh_grad',
                                                             ('call',
                                                              'grad',
                                                              [('var', 'h'),
                                                               ('var', 'x')])),
                                                            ('body_decl',
                                                             'dh_dp',
                                                             'ℝ',
                                                             ('indexN',
                                                              'dh_grad',
                                                              [('num', 1),
                                                               ('num', 0)])),
                                                            ('body_decl',
                                                             'dh_dq',
                                                             'ℝ',
                                                             ('neg',
                                                              ('indexN',
                                                               'dh_grad',
                                                               [('num', 0),
                                                                ('num', 0)])))],
                                             'body': ('array',
                                                      [('array',
                                                        [('var', 'dh_dp')]),
                                                       ('array',
                                                        [('var', 'dh_dq')])])},
                                            {'name': 'loss',
                                             'params': [('symplectic_gradient',
                                                         ('tensor',
                                                          'ℝ',
                                                          [(2, 'invariant')])),
                                                        ('target',
                                                         ('tensor',
                                                          'ℝ',
                                                          [('N',
                                                            'invariant')]))],
                                             'return_type': 'ℝ',
                                             'statements': [('body_decl',
                                                             'lo',
                                                             'ℝ',
                                                             ('add',
                                                              ('pow',
                                                               ('sub',
                                                                ('index',
                                                                 'symplectic_gradient',
                                                                 ('num', 0)),
                                                                ('index',
                                                                 'target',
                                                                 ('num', 0))),
                                                               ('num', 2.0)),
                                                              ('pow',
                                                               ('sub',
                                                                ('index',
                                                                 'symplectic_gradient',
                                                                 ('num', 1)),
                                                                ('index',
                                                                 'target',
                                                                 ('num', 1))),
                                                               ('num', 2.0))))],
                                             'body': ('var', 'lo')}]}},
 'program': [('func_def', 'tanh'),
             ('class_def', 'HamiltonianNet'),
             ('decl',
              'X',
              ('tensor',
               'ℝ',
               [(8, 'invariant'), (2, 'invariant'), (1, 'invariant')]),
              ('array',
               [('array',
                 [('array', [('num', 0.0)]), ('array', [('num', 1.0)])]),
                ('array',
                 [('array', [('num', 1.0)]), ('array', [('num', 0.0)])]),
                ('array',
                 [('array', [('num', 0.0)]),
                  ('array', [('neg', ('num', 1.0))])]),
                ('array',
                 [('array', [('neg', ('num', 1.0))]),
                  ('array', [('num', 0.0)])]),
                ('array',
                 [('array', [('num', 0.5)]), ('array', [('num', 0.5)])]),
                ('array',
                 [('array', [('neg', ('num', 0.5))]),
                  ('array', [('neg', ('num', 0.5))])]),
                ('array',
                 [('array', [('num', 0.7)]),
                  ('array', [('neg', ('num', 0.7))])]),
                ('array',
                 [('array', [('neg', ('num', 0.7))]),
                  ('array', [('num', 0.7)])])]),
              40),
             ('decl',
              'y',
              ('tensor',
               'ℝ',
               [(8, 'invariant'), (2, 'invariant'), (1, 'invariant')]),
              ('array',
               [('array',
                 [('array', [('num', 1.0)]), ('array', [('num', 0.0)])]),
                ('array',
                 [('array', [('num', 0.0)]),
                  ('array', [('neg', ('num', 1.0))])]),
                ('array',
                 [('array', [('neg', ('num', 1.0))]),
                  ('array', [('num', 0.0)])]),
                ('array',
                 [('array', [('num', 0.0)]), ('array', [('num', 1.0)])]),
                ('array',
                 [('array', [('num', 0.5)]),
                  ('array', [('neg', ('num', 0.5))])]),
                ('array',
                 [('array', [('neg', ('num', 0.5))]),
                  ('array', [('num', 0.5)])]),
                ('array',
                 [('array', [('neg', ('num', 0.7))]),
                  ('array', [('neg', ('num', 0.7))])]),
                ('array',
                 [('array', [('num', 0.7)]), ('array', [('num', 0.7)])])]),
              51),
             ('decl',
              'W1',
              ('tensor', 'ℝ', [(16, 'invariant'), (2, 'invariant')]),
              ('array',
               [('array', [('num', 0.5), ('num', 0.1)]),
                ('array', [('num', 0.1), ('num', 0.5)]),
                ('array', [('num', 0.3), ('num', 0.3)]),
                ('array', [('num', 0.4), ('num', 0.2)]),
                ('array', [('num', 0.2), ('num', 0.4)]),
                ('array', [('num', 0.1), ('num', 0.1)]),
                ('array', [('num', 0.3), ('num', 0.1)]),
                ('array', [('num', 0.1), ('num', 0.3)]),
                ('array', [('num', 0.2), ('num', 0.2)]),
                ('array', [('num', 0.4), ('num', 0.4)]),
                ('array', [('num', 0.5), ('num', 0.3)]),
                ('array', [('num', 0.3), ('num', 0.5)]),
                ('array', [('num', 0.2), ('num', 0.1)]),
                ('array', [('num', 0.1), ('num', 0.2)]),
                ('array', [('num', 0.4), ('num', 0.1)]),
                ('array', [('num', 0.1), ('num', 0.4)])]),
              65),
             ('decl',
              'b1',
              ('tensor', 'ℝ', [(16, 'invariant'), (1, 'invariant')]),
              ('array',
               [('array', [('num', 0.0)]),
                ('array', [('num', 0.0)]),
                ('array', [('num', 0.0)]),
                ('array', [('num', 0.0)]),
                ('array', [('num', 0.0)]),
                ('array', [('num', 0.0)]),
                ('array', [('num', 0.0)]),
                ('array', [('num', 0.0)]),
                ('array', [('num', 0.0)]),
                ('array', [('num', 0.0)]),
                ('array', [('num', 0.0)]),
                ('array', [('num', 0.0)]),
                ('array', [('num', 0.0)]),
                ('array', [('num', 0.0)]),
                ('array', [('num', 0.0)]),
                ('array', [('num', 0.0)])]),
              69),
             ('decl',
              'w2',
              ('tensor', 'ℝ', [(1, 'invariant'), (16, 'invariant')]),
              ('array',
               [('array',
                 [('num', 0.1),
                  ('num', 0.1),
                  ('num', 0.1),
                  ('num', 0.1),
                  ('num', 0.1),
                  ('num', 0.1),
                  ('num', 0.1),
                  ('num', 0.1),
                  ('num', 0.1),
                  ('num', 0.1),
                  ('num', 0.1),
                  ('num', 0.1),
                  ('num', 0.1),
                  ('num', 0.1),
                  ('num', 0.1),
                  ('num', 0.1)])]),
              76),
             ('decl', 'b2', 'ℝ', ('num', 0.0), 82),
             ('assign',
              'H_net',
              ('call',
               'HamiltonianNet',
               [('var', 'W1'), ('var', 'b1'), ('var', 'w2'), ('var', 'b2')]),
              84),
             ('assign',
              'loss_before',
              ('call',
               'evaluate',
               [('var', 'H_net'), ('var', 'X'), ('var', 'y')]),
              89),
             ('expr', ('var', 'loss_before'), 0),
             ('decl', 'epochs', 'ℕ', ('num', 500), 96),
             ('decl', 'lr', 'ℝ', ('num', 0.01), 97),
             ('assign',
              'H_trained',
              ('call',
               'train',
               [('var', 'H_net'),
                ('var', 'X'),
                ('var', 'y'),
                ('var', 'epochs'),
                ('var', 'lr')]),
              98),
             ('assign',
              'loss_after',
              ('call',
               'evaluate',
               [('var', 'H_trained'), ('var', 'X'), ('var', 'y')]),
              103),
             ('expr', ('var', 'loss_after'), 0)]}
