EXPECTED = {'functions': {'f': {'params': [('x', 'ℝ')],
                     'return_type': 'ℝ',
                     'body': None,
                     'has_loop': False,
                     'statements': [('body_if_else_return',
                                     ('cond_gt', ('var', 'x'), ('num', 0)),
                                     ('mul', ('var', 'x'), ('var', 'x')),
                                     ('neg', ('var', 'x')))]},
               'clamp': {'params': [('x', 'ℝ')],
                         'return_type': 'ℝ',
                         'body': ('var', 'y'),
                         'has_loop': False,
                         'statements': [('body_if_else',
                                         ('cond_gt', ('var', 'x'), ('num', 1)),
                                         [('body_assign', 'y', ('num', 1))],
                                         [('body_assign', 'y', ('var', 'x'))]),
                                        ('body_if',
                                         ('cond_lt',
                                          ('var', 'y'),
                                          ('neg', ('num', 1))),
                                         [('body_assign',
                                           'y',
                                           ('neg', ('num', 1)))])]},
               'classify': {'params': [('x', 'ℝ')],
                            'return_type': 'ℝ',
                            'body': None,
                            'has_loop': False,
                            'statements': [('body_if_else',
                                            ('cond_gt',
                                             ('var', 'x'),
                                             ('num', 0.5)),
                                            [('body_if_else_return',
                                              ('cond_gt',
                                               ('var', 'x'),
                                               ('num', 1.5)),
                                              ('num', 2),
                                              ('num', 1))],
                                            [('body_if_else_return',
                                              ('cond_lt',
                                               ('var', 'x'),
                                               ('neg', ('num', 0.5))),
                                              ('neg', ('num', 1)),
                                              ('num', 0))])]}},
 'classes': {'PiecewiseNet': {'class_params': [('threshold', 'ℝ')],
                              'fields': [],
                              'methods': [{'name': 'λ',
                                           'params': [('x', 'ℝ')],
                                           'return_type': 'ℝ',
                                           'statements': [('body_if_else',
                                                           ('cond_gt',
                                                            ('var', 'x'),
                                                            ('var',
                                                             'threshold')),
                                                           [('body_assign',
                                                             'y',
                                                             ('mul',
                                                              ('var', 'x'),
                                                              ('var', 'x')))],
                                                           [('body_assign',
                                                             'y',
                                                             ('neg',
                                                              ('var', 'x')))])],
                                           'body': ('var', 'y')},
                                          {'name': 'loss',
                                           'params': [('pred', 'ℝ'),
                                                      ('target', 'ℝ')],
                                           'return_type': 'ℝ',
                                           'statements': [],
                                           'body': ('pow',
                                                    ('sub',
                                                     ('var', 'pred'),
                                                     ('var', 'target')),
                                                    ('num', 2))}]}},
 'program': [('func_def', 'f'),
             ('decl', 'a', 'ℝ', ('num', 2.0), 14),
             ('decl', 'b', 'ℝ', ('neg', ('num', 1.5)), 15),
             ('expr', ('call', 'f', [('var', 'a')]), 0),
             ('expr',
              ('call', 'grad', [('call', 'f', [('var', 'a')]), ('var', 'a')]),
              0),
             ('expr', ('call', 'f', [('var', 'b')]), 0),
             ('expr',
              ('call', 'grad', [('call', 'f', [('var', 'b')]), ('var', 'b')]),
              0),
             ('func_def', 'clamp'),
             ('expr', ('call', 'clamp', [('num', 3)]), 0),
             ('expr', ('call', 'clamp', [('num', 0.5)]), 0),
             ('expr', ('call', 'clamp', [('neg', ('num', 5))]), 0),
             ('func_def', 'classify'),
             ('expr', ('call', 'classify', [('num', 2)]), 0),
             ('expr', ('call', 'classify', [('num', 0)]), 0),
             ('expr', ('call', 'classify', [('neg', ('num', 1))]), 0),
             ('class_def', 'PiecewiseNet'),
             ('assign', 'net', ('call', 'PiecewiseNet', [('num', 0)]), 66),
             ('decl', 'a', 'ℝ', ('num', 2.0), 67),
             ('expr', ('call', 'net', [('var', 'a')]), 0),
             ('expr',
              ('call', 'grad', [('call', 'net', [('var', 'a')]), ('var', 'a')]),
              0),
             ('decl', 'b', 'ℝ', ('neg', ('num', 1.5)), 70),
             ('expr', ('call', 'net', [('var', 'b')]), 0),
             ('expr',
              ('call', 'grad', [('call', 'net', [('var', 'b')]), ('var', 'b')]),
              0),
             ('decl', 'x', 'ℝ', ('num', 0.3), 76),
             ('if_else',
              ('cond_gt', ('var', 'x'), ('num', 0.5)),
              [('for_assign',
                'y',
                ('mul',
                 ('num', 3),
                 ('pow', ('sub', ('var', 'x'), ('num', 0.75)), ('num', 2))))],
              [('for_assign',
                'y',
                ('add', ('pow', ('var', 'x'), ('num', 2)), ('num', 2)))]),
             ('expr', ('var', 'y'), 0)]}
