EXPECTED = {'functions': {'f': {'params': [('x', 'ℝ')],
                     'return_type': 'ℝ',
                     'body': None,
                     'has_loop': False,
                     'statements': [('body_if_else_return',
                                     ('cond_gt', ('var', 'x'), ('num', 0.0)),
                                     ('mul', ('var', 'x'), ('var', 'x')),
                                     ('neg', ('var', 'x')))]},
               'clamp': {'params': [('x', 'ℝ')],
                         'return_type': 'ℝ',
                         'body': ('var', 'y'),
                         'has_loop': False,
                         'statements': [('body_if_else',
                                         ('cond_gt',
                                          ('var', 'x'),
                                          ('num', 1.0)),
                                         [('body_assign', 'y', ('num', 1.0))],
                                         [('body_assign', 'y', ('var', 'x'))]),
                                        ('body_if',
                                         ('cond_lt',
                                          ('var', 'y'),
                                          ('neg', ('num', 1.0))),
                                         [('body_assign',
                                           'y',
                                           ('neg', ('num', 1.0)))])]},
               'classify': {'params': [('x', 'ℝ')],
                            'return_type': 'ℝ',
                            'body': None,
                            'has_loop': False,
                            'statements': [('body_if_else',
                                            ('cond_gt',
                                             ('var', 'x'),
                                             ('num', 0.5)),
                                            [('body_if_else_return',
                                              ('cond_gt',
                                               ('var', 'x'),
                                               ('num', 1.5)),
                                              ('num', 2.0),
                                              ('num', 1.0))],
                                            [('body_if_else_return',
                                              ('cond_lt',
                                               ('var', 'x'),
                                               ('neg', ('num', 0.5))),
                                              ('neg', ('num', 1.0)),
                                              ('num', 0.0))])]}},
 'classes': {'PiecewiseNet': {'class_params': [('threshold', 'ℝ')],
                              'lambda_params': [('x', 'ℝ')],
                              'return_type': 'ℝ',
                              'body': ('var', 'y'),
                              'statements': [('body_if_else',
                                              ('cond_gt',
                                               ('var', 'x'),
                                               ('var', 'threshold')),
                                              [('body_assign',
                                                'y',
                                                ('mul',
                                                 ('var', 'x'),
                                                 ('var', 'x')))],
                                              [('body_assign',
                                                'y',
                                                ('neg', ('var', 'x')))])],
                              'has_loop': False,
                              'has_loss': True,
                              'loss_params': [('pred', 'ℝ'), ('target', 'ℝ')],
                              'loss_body': ('pow',
                                            ('sub',
                                             ('var', 'pred'),
                                             ('var', 'target')),
                                            ('num', 2.0))}},
 'program': [('func_def', 'f'),
             ('decl', 'a', 'ℝ', ('num', 2.0), 14),
             ('decl', 'b', 'ℝ', ('neg', ('num', 1.5)), 15),
             ('expr', ('call', 'f', [('var', 'a')]), 0),
             ('expr',
              ('call', 'grad', [('call', 'f', [('var', 'a')]), ('var', 'a')]),
              0),
             ('expr', ('call', 'f', [('var', 'b')]), 0),
             ('expr',
              ('call', 'grad', [('call', 'f', [('var', 'b')]), ('var', 'b')]),
              0),
             ('func_def', 'clamp'),
             ('expr', ('call', 'clamp', [('num', 3.0)]), 0),
             ('expr', ('call', 'clamp', [('num', 0.5)]), 0),
             ('expr', ('call', 'clamp', [('neg', ('num', 5.0))]), 0),
             ('func_def', 'classify'),
             ('expr', ('call', 'classify', [('num', 2.0)]), 0),
             ('expr', ('call', 'classify', [('num', 0.0)]), 0),
             ('expr', ('call', 'classify', [('neg', ('num', 1.0))]), 0),
             ('class_def', 'PiecewiseNet'),
             ('assign', 'net', ('call', 'PiecewiseNet', [('num', 0.0)]), 66),
             ('decl', 'a', 'ℝ', ('num', 2.0), 67),
             ('expr', ('call', 'net', [('var', 'a')]), 0),
             ('expr',
              ('call', 'grad', [('call', 'net', [('var', 'a')]), ('var', 'a')]),
              0),
             ('decl', 'b', 'ℝ', ('neg', ('num', 1.5)), 70),
             ('expr', ('call', 'net', [('var', 'b')]), 0),
             ('expr',
              ('call', 'grad', [('call', 'net', [('var', 'b')]), ('var', 'b')]),
              0),
             ('decl', 'x', 'ℝ', ('num', 0.3), 76),
             ('if_else',
              ('cond_gt', ('var', 'x'), ('num', 0.5)),
              [('for_assign',
                'y',
                ('mul',
                 ('num', 3.0),
                 ('pow', ('sub', ('var', 'x'), ('num', 0.75)), ('num', 2.0))))],
              [('for_assign',
                'y',
                ('add', ('pow', ('var', 'x'), ('num', 2.0)), ('num', 2.0)))]),
             ('expr', ('var', 'y'), 0)]}
