EXPECTED = {'functions': {},
 'classes': {},
 'program': [('decl', 'a', 'ℤ2', ('num', 1), 1),
             ('decl', 'b', 'ℤ2', ('num', 0), 2),
             ('assign', 'xor_opposite', ('add', ('var', 'a'), ('var', 'b')), 7),
             ('assign', 'xor_same', ('add', ('var', 'a'), ('var', 'a')), 8),
             ('expr', ('var', 'xor_opposite'), 0),
             ('expr', ('var', 'xor_same'), 0),
             ('assign', 'and_mixed', ('mul', ('var', 'a'), ('var', 'b')), 16),
             ('assign',
              'and_both_ones',
              ('mul', ('var', 'a'), ('var', 'a')),
              17),
             ('expr', ('var', 'and_mixed'), 0),
             ('expr', ('var', 'and_both_ones'), 0),
             ('decl', 'flag', 'ℤ2', ('num', 0), 26),
             ('if_else',
              ('cond_eq', ('var', 'flag'), ('num', 0)),
              [('for_assign', 'results', ('num', 0.0))],
              [('for_assign', 'results', ('num', 1.0))]),
             ('expr', ('var', 'results'), 0)]}
