EXPECTED = {'functions': {},
 'classes': {},
 'program': [('decl', 'a', 'ℤ2', ('num', 1), 1),
             ('decl', 'b', 'ℤ2', ('num', 0), 2),
             ('assign', 'c', ('add', ('var', 'a'), ('var', 'b')), 7),
             ('expr', ('var', 'c'), 0),
             ('expr', ('add', ('var', 'a'), ('var', 'a')), 0),
             ('assign', 'd', ('mul', ('var', 'a'), ('var', 'b')), 14),
             ('expr', ('var', 'a'), 0),
             ('decl', 'flag', 'ℤ2', ('num', 0), 21),
             ('if_else',
              ('cond_eq', ('var', 'flag'), ('num', 0)),
              [('for_assign', 'results', ('num', 0.0))],
              [('for_assign', 'results', ('num', 1.0))]),
             ('expr', ('var', 'results'), 0)]}
