EXPECTED = {'functions': {'pendulum': {'params': [('x',
                                        ('tensor', 'ℝ', [(2, 'invariant')]))],
                            'return_type': ('tensor', 'ℝ', [(2, 'invariant')]),
                            'body': ('array',
                                     [('index', 'x', ('num', 1)),
                                      ('sub',
                                       ('num', 0.0),
                                       ('mul',
                                        ('div', ('num', 9.81), ('num', 1.0)),
                                        ('call',
                                         'sin',
                                         [('index', 'x', ('num', 0))])))]),
                            'has_loop': False,
                            'statements': []}},
 'classes': {'RK4': {'class_params': [('dt', 'ℝ')],
                     'fields': [],
                     'methods': [{'name': 'λ',
                                  'params': [('x',
                                              ('tensor',
                                               'ℝ',
                                               [(2, 'invariant')]))],
                                  'return_type': ('tensor',
                                                  'ℝ',
                                                  [(2, 'invariant')]),
                                  'statements': [('body_assign',
                                                  'k1',
                                                  ('call',
                                                   'pendulum',
                                                   [('var', 'x')])),
                                                 ('body_assign',
                                                  'k2',
                                                  ('call',
                                                   'pendulum',
                                                   [('add',
                                                     ('var', 'x'),
                                                     ('mul',
                                                      ('mul',
                                                       ('num', 0.5),
                                                       ('var', 'dt')),
                                                      ('var', 'k1')))])),
                                                 ('body_assign',
                                                  'k3',
                                                  ('call',
                                                   'pendulum',
                                                   [('add',
                                                     ('var', 'x'),
                                                     ('mul',
                                                      ('mul',
                                                       ('num', 0.5),
                                                       ('var', 'dt')),
                                                      ('var', 'k2')))])),
                                                 ('body_assign',
                                                  'k4',
                                                  ('call',
                                                   'pendulum',
                                                   [('add',
                                                     ('var', 'x'),
                                                     ('mul',
                                                      ('var', 'dt'),
                                                      ('var', 'k3')))])),
                                                 ('body_assign',
                                                  'x',
                                                  ('add',
                                                   ('var', 'x'),
                                                   ('mul',
                                                    ('div',
                                                     ('var', 'dt'),
                                                     ('num', 6.0)),
                                                    ('add',
                                                     ('add',
                                                      ('add',
                                                       ('var', 'k1'),
                                                       ('mul',
                                                        ('num', 2.0),
                                                        ('var', 'k2'))),
                                                      ('mul',
                                                       ('num', 2.0),
                                                       ('var', 'k3'))),
                                                     ('var', 'k4')))))],
                                  'body': ('var', 'x')}]}},
 'program': [('func_def', 'pendulum'),
             ('class_def', 'RK4'),
             ('decl', 'dt', 'ℝ', ('num', 0.01), 28),
             ('assign', 'solver', ('call', 'RK4', [('var', 'dt')]), 33),
             ('expr',
              ('call', 'solver', [('array', [('num', 0.5), ('num', 0.0)])]),
              0),
             ('expr',
              ('call', 'solver', [('array', [('num', 1.0), ('num', 0.0)])]),
              0),
             ('assign', 'step', ('call', 'RK4', [('var', 'dt')]), 42),
             ('expr',
              ('call',
               'simulate',
               [('var', 'step'),
                ('array', [('num', 0.5), ('num', 0.0)]),
                ('num', 1000),
                ('var', 'dt')]),
              0)]}
