EXPECTED = {'functions': {'ke_wrt_vel': {'params': [('vel',
                                          ('tensor', [(2, 'invariant')]))],
                              'return_type': 'ℝ',
                              'body': ('method_call',
                                       ('var', 'particle'),
                                       'kinetic_energy',
                                       []),
                              'has_loop': False,
                              'statements': [('body_decl',
                                              'particle',
                                              ('struct_type', 'Particle'),
                                              ('call',
                                               'Particle',
                                               [('var', 'pos0'),
                                                ('var', 'vel'),
                                                ('num', 1.0)]))]},
               'ke_vy': {'params': [('vy', 'ℝ')],
                         'return_type': 'ℝ',
                         'body': ('method_call',
                                  ('var', 'p'),
                                  'kinetic_energy',
                                  []),
                         'has_loop': False,
                         'statements': [('body_decl',
                                         'p',
                                         ('struct_type', 'Particle'),
                                         ('call',
                                          'Particle',
                                          [('var', 'pos0'),
                                           ('array',
                                            [('num', 1.0), ('var', 'vy')]),
                                           ('num', 2.0)]))]},
               'norm_sq_wrt_x': {'params': [('x', 'ℝ')],
                                 'return_type': 'ℝ',
                                 'body': ('method_call',
                                          ('var', 'vec'),
                                          'norm_sq',
                                          []),
                                 'has_loop': False,
                                 'statements': [('body_decl',
                                                 'vec',
                                                 ('struct_type', 'Vec'),
                                                 ('call',
                                                  'Vec',
                                                  [('var', 'x'),
                                                   ('num', 4.0)]))]}},
 'classes': {'Vec': {'class_params': [('x', 'ℝ'), ('y', 'ℝ')],
                     'fields': [],
                     'methods': [{'name': 'dot',
                                  'params': [('other', ('struct_type', 'Vec'))],
                                  'return_type': 'ℝ',
                                  'statements': [],
                                  'body': ('add',
                                           ('mul',
                                            ('field_access',
                                             ('var', 'this'),
                                             'x'),
                                            ('field_access',
                                             ('var', 'other'),
                                             'x')),
                                           ('mul',
                                            ('field_access',
                                             ('var', 'this'),
                                             'y'),
                                            ('field_access',
                                             ('var', 'other'),
                                             'y')))},
                                 {'name': 'scale',
                                  'params': [('s', 'ℝ')],
                                  'return_type': ('struct_type', 'Vec'),
                                  'statements': [],
                                  'body': ('call',
                                           'Vec',
                                           [('mul',
                                             ('field_access',
                                              ('var', 'this'),
                                              'x'),
                                             ('var', 's')),
                                            ('mul',
                                             ('field_access',
                                              ('var', 'this'),
                                              'y'),
                                             ('var', 's'))])},
                                 {'name': 'norm_sq',
                                  'params': [],
                                  'return_type': 'ℝ',
                                  'statements': [],
                                  'body': ('add',
                                           ('mul',
                                            ('field_access',
                                             ('var', 'this'),
                                             'x'),
                                            ('field_access',
                                             ('var', 'this'),
                                             'x')),
                                           ('mul',
                                            ('field_access',
                                             ('var', 'this'),
                                             'y'),
                                            ('field_access',
                                             ('var', 'this'),
                                             'y')))}]},
             'Particle': {'class_params': [('pos',
                                            ('tensor', [(2, 'invariant')])),
                                           ('vel',
                                            ('tensor', [(2, 'invariant')])),
                                           ('mass', 'ℝ')],
                          'fields': [],
                          'methods': [{'name': 'kinetic_energy',
                                       'params': [],
                                       'return_type': 'ℝ',
                                       'statements': [],
                                       'body': ('mul',
                                                ('mul',
                                                 ('num', 0.5),
                                                 ('field_access',
                                                  ('var', 'this'),
                                                  'mass')),
                                                ('call',
                                                 'sum',
                                                 [('mul',
                                                   ('field_access',
                                                    ('var', 'this'),
                                                    'vel'),
                                                   ('field_access',
                                                    ('var', 'this'),
                                                    'vel'))]))},
                                      {'name': 'step',
                                       'params': [('force',
                                                   ('tensor',
                                                    [(2, 'invariant')])),
                                                  ('dt', 'ℝ')],
                                       'return_type': ('struct_type',
                                                       'Particle'),
                                       'statements': [('body_decl',
                                                       'acc',
                                                       ('tensor',
                                                        [(2, 'invariant')]),
                                                       ('mul',
                                                        ('var', 'force'),
                                                        ('div',
                                                         ('num', 1.0),
                                                         ('field_access',
                                                          ('var', 'this'),
                                                          'mass')))),
                                                      ('body_decl',
                                                       'new_vel',
                                                       ('tensor',
                                                        [(2, 'invariant')]),
                                                       ('add',
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'vel'),
                                                        ('mul',
                                                         ('var', 'acc'),
                                                         ('var', 'dt')))),
                                                      ('body_decl',
                                                       'new_pos',
                                                       ('tensor',
                                                        [(2, 'invariant')]),
                                                       ('add',
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'pos'),
                                                        ('mul',
                                                         ('field_access',
                                                          ('var', 'this'),
                                                          'vel'),
                                                         ('var', 'dt'))))],
                                       'body': ('call',
                                                'Particle',
                                                [('var', 'new_pos'),
                                                 ('var', 'new_vel'),
                                                 ('field_access',
                                                  ('var', 'this'),
                                                  'mass')])}]},
             'A': {'class_params': [('x', 'ℝ')], 'fields': [], 'methods': []},
             'B': {'class_params': [('objA', ('struct_type', 'A'))],
                   'fields': [],
                   'methods': [{'name': 'access_member',
                                'params': [],
                                'return_type': 'ℝ',
                                'statements': [('body_field_assign',
                                                ('field_access',
                                                 ('var', 'this'),
                                                 'objA'),
                                                'x',
                                                ('num', 2.0))],
                                'body': ('field_access',
                                         ('field_access',
                                          ('var', 'this'),
                                          'objA'),
                                         'x')},
                               {'name': 'access_memeber_in_loop',
                                'params': [],
                                'return_type': 'ℝ',
                                'statements': [('body_for_range',
                                                'i',
                                                ('num', 0),
                                                ('num', 1),
                                                [('body_field_assign',
                                                  ('field_access',
                                                   ('var', 'this'),
                                                   'objA'),
                                                  'x',
                                                  ('num', 3.0))])],
                                'body': ('field_access',
                                         ('field_access',
                                          ('var', 'this'),
                                          'objA'),
                                         'x')}]}},
 'program': [('class_def', 'Vec'),
             ('class_def', 'Particle'),
             ('assign', 'a', ('call', 'Vec', [('num', 3.0), ('num', 4.0)]), 26),
             ('assign', 'b', ('call', 'Vec', [('num', 1.0), ('num', 0.0)]), 27),
             ('expr', ('field_access', ('var', 'a'), 'x'), 0),
             ('expr', ('field_access', ('var', 'a'), 'y'), 0),
             ('decl',
              'dot_ab',
              'ℝ',
              ('method_call', ('var', 'a'), 'dot', [('var', 'b')]),
              30),
             ('expr', ('var', 'dot_ab'), 0),
             ('assign',
              'c',
              ('method_call', ('var', 'a'), 'scale', [('num', 4)]),
              32),
             ('expr', ('field_access', ('var', 'c'), 'x'), 0),
             ('expr', ('field_access', ('var', 'c'), 'y'), 0),
             ('decl',
              'pos0',
              ('tensor', [(2, 'invariant')]),
              ('array', [('num', 0.0), ('num', 10.0)]),
              38),
             ('decl',
              'vel0',
              ('tensor', [(2, 'invariant')]),
              ('array', [('num', 1.0), ('num', 0.0)]),
              39),
             ('decl',
              'gravity',
              ('tensor', [(2, 'invariant')]),
              ('array', [('num', 0.0), ('neg', ('num', 9.81))]),
              40),
             ('assign',
              'p',
              ('call',
               'Particle',
               [('var', 'pos0'), ('var', 'vel0'), ('num', 9.0)]),
              41),
             ('decl',
              'ke0',
              'ℝ',
              ('method_call', ('var', 'p'), 'kinetic_energy', []),
              42),
             ('expr', ('var', 'ke0'), 0),
             ('assign',
              'p1',
              ('method_call',
               ('var', 'p'),
               'step',
               [('var', 'gravity'), ('num', 0.5)]),
              44),
             ('expr', ('field_access', ('var', 'p1'), 'pos'), 0),
             ('assign',
              'p2',
              ('method_call',
               ('var', 'p1'),
               'step',
               [('var', 'gravity'), ('num', 0.5)]),
              46),
             ('expr', ('field_access', ('var', 'p2'), 'pos'), 0),
             ('func_def', 'ke_wrt_vel'),
             ('decl',
              'v',
              ('tensor', [(2, 'invariant')]),
              ('array', [('num', 2.0), ('num', 3.4)]),
              55),
             ('decl', 'ke0_v', 'ℝ', ('call', 'ke_wrt_vel', [('var', 'v')]), 56),
             ('expr', ('var', 'ke0_v'), 0),
             ('decl',
              'dKE_dv',
              ('tensor', [(2, 'invariant')]),
              ('call',
               'grad',
               [('call', 'ke_wrt_vel', [('var', 'v')]), ('var', 'v')]),
              58),
             ('expr', ('var', 'dKE_dv'), 0),
             ('func_def', 'ke_vy'),
             ('decl', 'vy0', 'ℝ', ('num', 3.0), 68),
             ('expr', ('call', 'ke_vy', [('var', 'vy0')]), 0),
             ('expr',
              ('call',
               'grad',
               [('call', 'ke_vy', [('var', 'vy0')]), ('var', 'vy0')]),
              0),
             ('func_def', 'norm_sq_wrt_x'),
             ('decl', 'x0', 'ℝ', ('num', 3.0), 77),
             ('expr', ('call', 'norm_sq_wrt_x', [('var', 'x0')]), 0),
             ('expr',
              ('call',
               'grad',
               [('call', 'norm_sq_wrt_x', [('var', 'x0')]), ('var', 'x0')]),
              0),
             ('decl', 'x1', 'ℝ', ('num', 5.0), 82),
             ('decl',
              'vec',
              ('struct_type', 'Vec'),
              ('call', 'Vec', [('var', 'x1'), ('num', 4.0)]),
              83),
             ('expr',
              ('call',
               'grad',
               [('method_call', ('var', 'vec'), 'norm_sq', []), ('var', 'x1')]),
              0),
             ('decl', 'x1', 'ℝ', ('num', 5.0), 86),
             ('decl',
              'vec',
              ('struct_type', 'Vec'),
              ('call', 'Vec', [('var', 'x1'), ('num', 4.0)]),
              87),
             ('expr',
              ('call',
               'grad',
               [('field_access', ('var', 'vec'), 'x'), ('var', 'x1')]),
              0),
             ('class_def', 'A'),
             ('class_def', 'B'),
             ('decl',
              'obj_A',
              ('struct_type', 'A'),
              ('call', 'A', [('num', 1.0)]),
              110),
             ('decl',
              'obj_B',
              ('struct_type', 'B'),
              ('call', 'B', [('var', 'obj_A')]),
              111),
             ('expr',
              ('method_call', ('var', 'obj_B'), 'access_member', []),
              0),
             ('expr',
              ('method_call', ('var', 'obj_B'), 'access_memeber_in_loop', []),
              0)]}
