EXPECTED = {'functions': {'sample_normal1D': {'params': [('x', 'ℝ')],
                                   'return_type': ('tensor',
                                                   [('m', 'invariant')]),
                                   'body': ('var', 't'),
                                   'has_loop': False,
                                   'statements': [('sample',
                                                   't',
                                                   ('call',
                                                    'Normal',
                                                    [('num', 0),
                                                     ('num', 1),
                                                     ('var', 'x')]))]},
               'sample_normal2D': {'params': [('x', 'ℝ')],
                                   'return_type': ('tensor',
                                                   [('p', 'invariant'),
                                                    ('m', 'invariant')]),
                                   'body': ('var', 't'),
                                   'has_loop': False,
                                   'statements': [('body_decl',
                                                   't',
                                                   ('tensor',
                                                    [('x', 'invariant'),
                                                     (2, 'invariant')]),
                                                   ('for_expr',
                                                    'i',
                                                    ('var', 'x'),
                                                    ('typed_sample_expr',
                                                     'ε',
                                                     ('tensor',
                                                      [(2, 'invariant')]),
                                                     ('call',
                                                      'Normal',
                                                      [('var', 'μ'),
                                                       ('var', 'σ'),
                                                       ('num', 2)]))))]}},
 'classes': {},
 'program': [('decl', 'm_true', 'ℝ', ('num', 3.0), 4),
             ('decl', 'b_true', 'ℝ', ('num', 1.0), 5),
             ('decl', 'm_hat', 'ℝ', ('num', 2.0), 6),
             ('decl', 'b_hat', 'ℝ', ('num', 0.0), 7),
             ('decl', 'μ', 'ℝ', ('num', 2.0), 11),
             ('decl', 'σ', 'ℝ', ('num', 0.5), 12),
             ('decl', 'n', 'ℤ', ('num', 100), 15),
             ('typed_sample',
              'x',
              ('tensor', [('n', 'invariant')]),
              ('call', 'Normal', [('var', 'μ'), ('var', 'σ'), ('var', 'n')]),
              16),
             ('assign',
              'y_true',
              ('add',
               ('mul', ('var', 'm_true'), ('var', 'x')),
               ('var', 'b_true')),
              17),
             ('assign',
              'y_pred',
              ('add',
               ('mul', ('var', 'm_hat'), ('var', 'x')),
               ('var', 'b_hat')),
              18),
             ('decl',
              'loss',
              'ℝ',
              ('div',
               ('call',
                'sum',
                [('pow',
                  ('sub', ('var', 'y_pred'), ('var', 'y_true')),
                  ('num', 2))]),
               ('var', 'n')),
              19),
             ('expr', ('var', 'loss'), 0),
             ('decl',
              'grad_mu',
              'ℝ',
              ('call', 'grad', [('var', 'loss'), ('var', 'μ')]),
              22),
             ('decl',
              'grad_sigma',
              'ℝ',
              ('call', 'grad', [('var', 'loss'), ('var', 'σ')]),
              23),
             ('expr', ('var', 'grad_mu'), 0),
             ('expr', ('var', 'grad_sigma'), 0),
             ('decl', 'lr', 'ℝ', ('num', 0.01), 28),
             ('for_loop_range',
              'step',
              ('num', 0),
              ('num', 300),
              [('typed_sample',
                'x',
                ('tensor', [('n', 'invariant')]),
                ('call', 'Normal', [('var', 'μ'), ('var', 'σ'), ('var', 'n')])),
               ('for_assign',
                'y_true',
                ('add',
                 ('mul', ('var', 'm_true'), ('var', 'x')),
                 ('var', 'b_true'))),
               ('for_assign',
                'y_pred',
                ('add',
                 ('mul', ('var', 'm_hat'), ('var', 'x')),
                 ('var', 'b_hat'))),
               ('for_assign',
                'loss',
                ('div',
                 ('call',
                  'sum',
                  [('pow',
                    ('sub', ('var', 'y_pred'), ('var', 'y_true')),
                    ('num', 2))]),
                 ('var', 'n'))),
               ('for_assign',
                'grad_mu',
                ('call', 'grad', [('var', 'loss'), ('var', 'μ')])),
               ('for_assign',
                'grad_sigma',
                ('call', 'grad', [('var', 'loss'), ('var', 'σ')])),
               ('for_assign',
                'μ',
                ('sub',
                 ('var', 'μ'),
                 ('mul', ('var', 'lr'), ('var', 'grad_mu')))),
               ('for_assign',
                'σ',
                ('sub',
                 ('var', 'σ'),
                 ('mul', ('var', 'lr'), ('var', 'grad_sigma'))))],
              29),
             ('expr', ('var', 'μ'), 0),
             ('expr', ('var', 'σ'), 0),
             ('typed_sample',
              'x',
              ('tensor', [('n', 'invariant')]),
              ('call', 'Normal', [('var', 'μ'), ('var', 'σ'), ('var', 'n')]),
              43),
             ('assign',
              'y_true',
              ('add',
               ('mul', ('var', 'm_true'), ('var', 'x')),
               ('var', 'b_true')),
              44),
             ('assign',
              'y_pred',
              ('add',
               ('mul', ('var', 'm_hat'), ('var', 'x')),
               ('var', 'b_hat')),
              45),
             ('decl',
              'loss',
              'ℝ',
              ('div',
               ('call',
                'sum',
                [('pow',
                  ('sub', ('var', 'y_pred'), ('var', 'y_true')),
                  ('num', 2))]),
               ('var', 'n')),
              46),
             ('expr', ('var', 'loss'), 0),
             ('decl',
              'z',
              ('tensor', [(10, 'invariant'), (2, 'invariant')]),
              ('for_expr',
               'i',
               ('num', 10),
               ('typed_sample_expr',
                'ε',
                ('tensor', [(2, 'invariant')]),
                ('call', 'Normal', [('var', 'μ'), ('var', 'σ'), ('num', 2)]))),
              52),
             ('expr', ('var', 'z'), 0),
             ('decl',
              'z_3d',
              ('tensor',
               [(10, 'invariant'), (5, 'invariant'), (2, 'invariant')]),
              ('for_expr',
               'i',
               ('num', 10),
               ('for_expr',
                'j',
                ('num', 5),
                ('typed_sample_expr',
                 'ε',
                 ('tensor', [(2, 'invariant')]),
                 ('call',
                  'Normal',
                  [('var', 'μ'), ('var', 'σ'), ('num', 2)])))),
              57),
             ('expr', ('var', 'z_3d'), 0),
             ('func_def', 'sample_normal1D'),
             ('func_def', 'sample_normal2D'),
             ('decl', 'x', 'ℝ', ('num', 3), 69),
             ('decl',
              'y',
              ('tensor', [(3, 'invariant')]),
              ('call', 'sample_normal1D', [('var', 'x')]),
              70),
             ('expr', ('var', 'y'), 0),
             ('decl',
              'y',
              ('tensor', [(3, 'invariant'), (2, 'invariant')]),
              ('call', 'sample_normal2D', [('var', 'x')]),
              73),
             ('expr', ('var', 'y'), 0),
             ('typed_sample',
              'u',
              'ℝ',
              ('call', 'Normal', [('num', 0.0), ('num', 1.0)]),
              78),
             ('expr', ('var', 'u'), 0),
             ('typed_sample',
              'u_vec',
              ('tensor', [(5, 'invariant')]),
              ('call', 'Normal', [('num', 0.0), ('num', 1.0), ('num', 5)]),
              80),
             ('expr', ('var', 'u_vec'), 0),
             ('typed_sample',
              'v',
              'ℝ',
              ('call', 'Uniform', [('num', 0.0), ('num', 1.0)]),
              84),
             ('expr', ('var', 'v'), 0),
             ('typed_sample',
              'v_vec',
              ('tensor', [(5, 'invariant')]),
              ('call', 'Uniform', [('num', 0.0), ('num', 1.0), ('num', 5)]),
              86),
             ('expr', ('var', 'v_vec'), 0),
             ('decl', 'α', 'ℝ', ('num', 2.0), 90),
             ('decl', 'β_b', 'ℝ', ('num', 5.0), 91),
             ('typed_sample',
              'bs',
              'ℝ',
              ('call', 'Beta', [('var', 'α'), ('var', 'β_b')]),
              92),
             ('expr', ('var', 'bs'), 0),
             ('typed_sample',
              'bs_vec',
              ('tensor', [(5, 'invariant')]),
              ('call', 'Beta', [('var', 'α'), ('var', 'β_b'), ('num', 5)]),
              94),
             ('expr', ('var', 'bs_vec'), 0),
             ('decl', 'conc', 'ℝ', ('num', 2.0), 98),
             ('decl', 'rate', 'ℝ', ('num', 1.0), 99),
             ('typed_sample',
              'gs',
              'ℝ',
              ('call', 'Gamma', [('var', 'conc'), ('var', 'rate')]),
              100),
             ('expr', ('var', 'gs'), 0),
             ('typed_sample',
              'gs_vec',
              ('tensor', [(5, 'invariant')]),
              ('call', 'Gamma', [('var', 'conc'), ('var', 'rate'), ('num', 5)]),
              102),
             ('expr', ('var', 'gs_vec'), 0),
             ('decl', 'p', 'ℝ', ('num', 0.5), 106),
             ('typed_sample',
              'coin',
              'ℝ',
              ('call', 'Bernoulli', [('var', 'p')]),
              107),
             ('expr', ('var', 'coin'), 0),
             ('typed_sample',
              'coin_vec',
              ('tensor', [(10, 'invariant')]),
              ('call', 'Bernoulli', [('var', 'p'), ('num', 10)]),
              109),
             ('expr', ('var', 'coin_vec'), 0)]}