EXPECTED = {'functions': {'spring_pendulum': {'params': [('x',
                                               ('tensor', [(4, 'invariant')]))],
                                   'return_type': ('tensor',
                                                   [(4, 'invariant')]),
                                   'body': ('array',
                                            [('index', 'x', ('num', 2)),
                                             ('index', 'x', ('num', 3)),
                                             ('sub',
                                              ('sub',
                                               ('mul',
                                                ('mul',
                                                 ('index', 'x', ('num', 0)),
                                                 ('index', 'x', ('num', 3))),
                                                ('index', 'x', ('num', 3))),
                                               ('mul',
                                                ('num', 9.81),
                                                ('call',
                                                 'cos',
                                                 [('index',
                                                   'x',
                                                   ('num', 1))]))),
                                              ('mul',
                                               ('num', 50.0),
                                               ('sub',
                                                ('index', 'x', ('num', 0)),
                                                ('num', 1.0)))),
                                             ('div',
                                              ('sub',
                                               ('sub',
                                                ('num', 0.0),
                                                ('mul',
                                                 ('mul',
                                                  ('num', 2.0),
                                                  ('index', 'x', ('num', 2))),
                                                 ('index', 'x', ('num', 3)))),
                                               ('mul',
                                                ('num', 9.81),
                                                ('call',
                                                 'sin',
                                                 [('index',
                                                   'x',
                                                   ('num', 1))]))),
                                              ('index', 'x', ('num', 0)))]),
                                   'has_loop': False,
                                   'statements': []}},
 'classes': {'RK4': {'class_params': [('f', ('func_type', 'ℝ', 'ℝ')),
                                      ('dt', 'ℝ'),
                                      ('n', 'ℕ')],
                     'lambda_params': [('x', ('tensor', [(4, 'invariant')]))],
                     'return_type': ('tensor', [(4, 'invariant')]),
                     'body': ('var', 'x'),
                     'statements': [('body_for',
                                     'k',
                                     [('loop_assign',
                                       'k1',
                                       ('call', 'f', [('var', 'x')])),
                                      ('loop_assign',
                                       'k2',
                                       ('call',
                                        'f',
                                        [('add',
                                          ('var', 'x'),
                                          ('mul',
                                           ('mul', ('num', 0.5), ('var', 'dt')),
                                           ('var', 'k1')))])),
                                      ('loop_assign',
                                       'k3',
                                       ('call',
                                        'f',
                                        [('add',
                                          ('var', 'x'),
                                          ('mul',
                                           ('mul', ('num', 0.5), ('var', 'dt')),
                                           ('var', 'k2')))])),
                                      ('loop_assign',
                                       'k4',
                                       ('call',
                                        'f',
                                        [('add',
                                          ('var', 'x'),
                                          ('mul',
                                           ('var', 'dt'),
                                           ('var', 'k3')))])),
                                      ('loop_assign',
                                       'x',
                                       ('add',
                                        ('var', 'x'),
                                        ('mul',
                                         ('div', ('var', 'dt'), ('num', 6.0)),
                                         ('add',
                                          ('add',
                                           ('add',
                                            ('var', 'k1'),
                                            ('mul',
                                             ('num', 2.0),
                                             ('var', 'k2'))),
                                           ('mul',
                                            ('num', 2.0),
                                            ('var', 'k3'))),
                                          ('var', 'k4')))))],
                                     [])],
                     'has_loop': False,
                     'has_loss': False}},
 'program': [('func_def', 'spring_pendulum'),
             ('class_def', 'RK4'),
             ('assign', 'dt', ('num', 0.01), 34),
             ('assign',
              'solver',
              ('call',
               'RK4',
               [('var', 'spring_pendulum'), ('var', 'dt'), ('num', 10000)]),
              35),
             ('expr',
              ('call',
               'solver',
               [('array',
                 [('num', 1.2), ('num', 0.3), ('num', 0.0), ('num', 0.0)])]),
              0),
             ('expr',
              ('call',
               'solver',
               [('array',
                 [('num', 1.3), ('num', 0.8), ('num', 0.0), ('num', 0.0)])]),
              0),
             ('assign',
              'step',
              ('call',
               'RK4',
               [('var', 'spring_pendulum'), ('var', 'dt'), ('num', 1)]),
              46),
             ('expr',
              ('call',
               'simulate',
               [('var', 'step'),
                ('array',
                 [('num', 1.2), ('num', 0.3), ('num', 0.0), ('num', 0.0)]),
                ('num', 500),
                ('var', 'dt')]),
              0)]}
