EXPECTED = {'functions': {'spring_pendulum': {'params': [('x',
                                               ('tensor',
                                                'ℝ',
                                                [(4, 'invariant')]))],
                                   'return_type': ('tensor',
                                                   'ℝ',
                                                   [(4, 'invariant')]),
                                   'body': ('array',
                                            [('index', 'x', ('num', 2)),
                                             ('index', 'x', ('num', 3)),
                                             ('sub',
                                              ('sub',
                                               ('mul',
                                                ('mul',
                                                 ('index', 'x', ('num', 0)),
                                                 ('index', 'x', ('num', 3))),
                                                ('index', 'x', ('num', 3))),
                                               ('mul',
                                                ('num', 9.81),
                                                ('call',
                                                 'cos',
                                                 [('index',
                                                   'x',
                                                   ('num', 1))]))),
                                              ('mul',
                                               ('num', 50.0),
                                               ('sub',
                                                ('index', 'x', ('num', 0)),
                                                ('num', 1.0)))),
                                             ('div',
                                              ('sub',
                                               ('sub',
                                                ('num', 0.0),
                                                ('mul',
                                                 ('mul',
                                                  ('num', 2.0),
                                                  ('index', 'x', ('num', 2))),
                                                 ('index', 'x', ('num', 3)))),
                                               ('mul',
                                                ('num', 9.81),
                                                ('call',
                                                 'sin',
                                                 [('index',
                                                   'x',
                                                   ('num', 1))]))),
                                              ('index', 'x', ('num', 0)))]),
                                   'has_loop': False,
                                   'statements': []}},
 'classes': {'RK4': {'class_params': [('dt', 'ℝ')],
                     'fields': [],
                     'methods': [{'name': 'λ',
                                  'params': [('x',
                                              ('tensor',
                                               'ℝ',
                                               [(4, 'invariant')]))],
                                  'return_type': ('tensor',
                                                  'ℝ',
                                                  [(4, 'invariant')]),
                                  'statements': [('body_assign',
                                                  'k1',
                                                  ('call',
                                                   'spring_pendulum',
                                                   [('var', 'x')])),
                                                 ('body_assign',
                                                  'k2',
                                                  ('call',
                                                   'spring_pendulum',
                                                   [('add',
                                                     ('var', 'x'),
                                                     ('mul',
                                                      ('mul',
                                                       ('num', 0.5),
                                                       ('var', 'dt')),
                                                      ('var', 'k1')))])),
                                                 ('body_assign',
                                                  'k3',
                                                  ('call',
                                                   'spring_pendulum',
                                                   [('add',
                                                     ('var', 'x'),
                                                     ('mul',
                                                      ('mul',
                                                       ('num', 0.5),
                                                       ('var', 'dt')),
                                                      ('var', 'k2')))])),
                                                 ('body_assign',
                                                  'k4',
                                                  ('call',
                                                   'spring_pendulum',
                                                   [('add',
                                                     ('var', 'x'),
                                                     ('mul',
                                                      ('var', 'dt'),
                                                      ('var', 'k3')))])),
                                                 ('body_assign',
                                                  'x',
                                                  ('add',
                                                   ('var', 'x'),
                                                   ('mul',
                                                    ('div',
                                                     ('var', 'dt'),
                                                     ('num', 6.0)),
                                                    ('add',
                                                     ('add',
                                                      ('add',
                                                       ('var', 'k1'),
                                                       ('mul',
                                                        ('num', 2.0),
                                                        ('var', 'k2'))),
                                                      ('mul',
                                                       ('num', 2.0),
                                                       ('var', 'k3'))),
                                                     ('var', 'k4')))))],
                                  'body': ('var', 'x')}]}},
 'program': [('func_def', 'spring_pendulum'),
             ('class_def', 'RK4'),
             ('assign', 'dt', ('num', 0.01), 34),
             ('assign', 'solver', ('call', 'RK4', [('var', 'dt')]), 35),
             ('expr',
              ('call',
               'solver',
               [('array',
                 [('num', 1.2), ('num', 0.3), ('num', 0.0), ('num', 0.0)])]),
              0),
             ('expr',
              ('call',
               'solver',
               [('array',
                 [('num', 1.3), ('num', 0.8), ('num', 0.0), ('num', 0.0)])]),
              0),
             ('assign', 'step', ('call', 'RK4', [('var', 'dt')]), 46),
             ('expr',
              ('call',
               'simulate',
               [('var', 'step'),
                ('array',
                 [('num', 1.2), ('num', 0.3), ('num', 0.0), ('num', 0.0)]),
                ('num', 500),
                ('var', 'dt')]),
              0)]}
