EXPECTED = {'classes': {'FullyConnectedNetwork': {'body': ('add',
                                                ('matmul',
                                                 ('var', 'w'),
                                                 ('var', 'x')),
                                                ('var', 'b')),
                                       'class_params': [('f',
                                                         ('func_type',
                                                          'ℝ',
                                                          'ℝ')),
                                                        ('W',
                                                         ('tensor',
                                                          [(2, 'invariant'),
                                                           (3, 'invariant'),
                                                           (3, 'invariant')])),
                                                        ('B',
                                                         ('tensor',
                                                          [(2, 'invariant'),
                                                           (3, 'invariant')])),
                                                        ('w',
                                                         ('tensor',
                                                          [(3, 'invariant')])),
                                                        ('b', 'ℝ'),
                                                        ('n', 'ℕ')],
                                       'has_loop': False,
                                       'has_loss': True,
                                       'lambda_params': [('x',
                                                          ('tensor',
                                                           [(3,
                                                             'invariant')]))],
                                       'loss_body': ('pow',
                                                     ('sub',
                                                      ('var', 'y'),
                                                      ('var', 'target')),
                                                     ('num', 2.0)),
                                       'loss_params': [('y', 'ℝ'),
                                                       ('target', 'ℝ')],
                                       'return_type': 'ℝ',
                                       'statements': [('body_for',
                                                       'k',
                                                       [('loop_assign',
                                                         'x',
                                                         ('call',
                                                          'f',
                                                          [('add',
                                                            ('matmul',
                                                             ('index',
                                                              'W',
                                                              ('var', 'k')),
                                                             ('var', 'x')),
                                                            ('index',
                                                             'B',
                                                             ('var', 'k')))]))],
                                                       ['W', 'B'])]}},
 'functions': {'sigma': {'body': ('div',
                                  ('num', 1.0),
                                  ('add',
                                   ('num', 1.0),
                                   ('call',
                                    'exp',
                                    [('sub', ('num', 0.0), ('var', 'x'))]))),
                         'has_loop': False,
                         'params': [('x', 'ℝ')],
                         'return_type': 'ℝ',
                         'statements': []}},
 'program': [('func_def', 'sigma'),
             ('class_def', 'FullyConnectedNetwork'),
             ('decl',
              'X',
              ('tensor', [(4, 'invariant'), (3, 'invariant')]),
              ('array',
               [('array', [('num', 1.0), ('num', 0.0), ('num', 0.0)]),
                ('array', [('num', 0.0), ('num', 1.0), ('num', 0.0)]),
                ('array', [('num', 0.0), ('num', 0.0), ('num', 1.0)]),
                ('array', [('num', 1.0), ('num', 1.0), ('num', 1.0)])]),
              27),
             ('decl',
              'y',
              ('tensor', [(4, 'invariant')]),
              ('array',
               [('num', 0.2), ('num', 0.4), ('num', 0.6), ('num', 0.9)]),
              31),
             ('decl',
              'W',
              ('tensor',
               [(2, 'invariant'), (3, 'invariant'), (3, 'invariant')]),
              ('array',
               [('array',
                 [('array', [('num', 0.1), ('num', 0.2), ('num', 0.3)]),
                  ('array', [('num', 0.4), ('num', 0.5), ('num', 0.6)]),
                  ('array', [('num', 0.7), ('num', 0.8), ('num', 0.9)])]),
                ('array',
                 [('array', [('num', 0.2), ('num', 0.3), ('num', 0.4)]),
                  ('array', [('num', 0.5), ('num', 0.6), ('num', 0.7)]),
                  ('array', [('num', 0.8), ('num', 0.9), ('num', 0.1)])])]),
              36),
             ('decl',
              'B',
              ('tensor', [(2, 'invariant'), (3, 'invariant')]),
              ('array',
               [('array', [('num', 0.1), ('num', 0.2), ('num', 0.3)]),
                ('array', [('num', 0.1), ('num', 0.2), ('num', 0.3)])]),
              38),
             ('decl',
              'w',
              ('tensor', [(3, 'invariant')]),
              ('array', [('num', 0.5), ('num', 0.5), ('num', 0.5)]),
              39),
             ('decl', 'b', 'ℝ', ('num', 0.1), 40),
             ('assign',
              'net',
              ('call',
               'FullyConnectedNetwork',
               [('var', 'sigma'),
                ('var', 'W'),
                ('var', 'B'),
                ('var', 'w'),
                ('var', 'b'),
                ('num', 2)]),
              42),
             ('assign',
              'loss_before',
              ('call',
               'evaluate',
               [('var', 'net'), ('var', 'X'), ('var', 'y')]),
              47),
             ('expr', ('var', 'loss_before'), 0),
             ('decl', 'epochs', 'ℕ', ('num', 1000), 53),
             ('decl', 'lr', 'ℝ', ('num', 0.1), 54),
             ('assign',
              'net_trained',
              ('call',
               'train',
               [('var', 'net'),
                ('var', 'X'),
                ('var', 'y'),
                ('var', 'epochs'),
                ('var', 'lr')]),
              55),
             ('assign',
              'loss_after',
              ('call',
               'evaluate',
               [('var', 'net_trained'), ('var', 'X'), ('var', 'y')]),
              60),
             ('expr', ('var', 'loss_after'), 0),
             ('expr',
              ('call',
               'net_trained',
               [('array', [('num', 1.0), ('num', 0.0), ('num', 0.0)])]),
              0),
             ('expr',
              ('call',
               'net_trained',
               [('array', [('num', 0.0), ('num', 1.0), ('num', 0.0)])]),
              0),
             ('expr',
              ('call',
               'net_trained',
               [('array', [('num', 0.0), ('num', 0.0), ('num', 1.0)])]),
              0),
             ('expr',
              ('call',
               'net_trained',
               [('array', [('num', 1.0), ('num', 1.0), ('num', 1.0)])]),
              0)]}