EXPECTED = {'functions': {'get_1d_array_length': {'params': [('x',
                                                   ('tensor',
                                                    [('m', 'invariant')]))],
                                       'return_type': 'ℝ',
                                       'body': ('var', 'total'),
                                       'has_loop': False,
                                       'statements': [('body_decl',
                                                       'total',
                                                       'ℝ',
                                                       ('num', 0)),
                                                      ('body_decl',
                                                       'temp',
                                                       'ℝ',
                                                       ('num', 0)),
                                                      ('body_for',
                                                       'i',
                                                       [('loop_assign',
                                                         'temp',
                                                         ('index',
                                                          'x',
                                                          ('imaginary',))),
                                                        ('loop_pluseq',
                                                         'total',
                                                         ('num', 1))],
                                                       ['x'])]},
               'get_2d_array_num_rows': {'params': [('x',
                                                     ('tensor',
                                                      [('m', 'invariant'),
                                                       ('n', 'invariant')]))],
                                         'return_type': 'ℝ',
                                         'body': ('var', 'total'),
                                         'has_loop': False,
                                         'statements': [('body_decl',
                                                         'total',
                                                         'ℝ',
                                                         ('num', 0)),
                                                        ('body_decl',
                                                         'temp',
                                                         'ℝ',
                                                         ('num', 0)),
                                                        ('body_for',
                                                         'i',
                                                         [('loop_assign',
                                                           'temp',
                                                           ('index',
                                                            'x',
                                                            ('imaginary',))),
                                                          ('loop_pluseq',
                                                           'total',
                                                           ('num', 1))],
                                                         ['x'])]},
               'zero_2d_array': {'params': [('rows', 'ℝ'), ('cols', 'ℝ')],
                                 'return_type': ('tensor',
                                                 [('m', 'invariant'),
                                                  ('n', 'invariant')]),
                                 'body': ('var', 'results'),
                                 'has_loop': False,
                                 'statements': [('body_decl',
                                                 'results',
                                                 ('tensor',
                                                  [('rows', 'invariant'),
                                                   ('cols', 'invariant')]),
                                                 ('for_expr',
                                                  'i',
                                                  ('var', 'rows'),
                                                  ('for_expr',
                                                   'j',
                                                   ('var', 'cols'),
                                                   ('mul',
                                                    ('var', 'j'),
                                                    ('num', 0)))))]},
               'get_3d_array_depth': {'params': [('x',
                                                  ('tensor',
                                                   [('a', 'invariant'),
                                                    ('b', 'invariant'),
                                                    ('c', 'invariant')]))],
                                      'return_type': 'ℕ',
                                      'body': ('var', 'depth'),
                                      'has_loop': False,
                                      'statements': [('body_decl',
                                                      'depth',
                                                      'ℕ',
                                                      ('call',
                                                       'get_1d_array_length',
                                                       [('var', 'X')]))]},
               'sigma': {'params': [('x',
                                     ('tensor',
                                      [('a', 'invariant'),
                                       ('b', 'invariant')]))],
                         'return_type': ('tensor',
                                         [('a', 'invariant'),
                                          ('b', 'invariant')]),
                         'body': ('var', 'results'),
                         'has_loop': False,
                         'statements': [('body_decl',
                                         'rows',
                                         'ℝ',
                                         ('call',
                                          'get_2d_array_num_rows',
                                          [('var', 'x')])),
                                        ('body_decl',
                                         'cols',
                                         'ℝ',
                                         ('call',
                                          'get_1d_array_length',
                                          [('index', 'x', ('num', 0))])),
                                        ('body_decl',
                                         'results',
                                         ('tensor',
                                          [('cols', 'invariant'),
                                           ('rows', 'invariant')]),
                                         ('call',
                                          'zero_2d_array',
                                          [('var', 'rows'), ('var', 'cols')])),
                                        ('body_for_range',
                                         'i',
                                         ('num', 0),
                                         ('var', 'rows'),
                                         [('loop_for_range',
                                           'j',
                                           ('num', 0),
                                           ('var', 'cols'),
                                           [('loop_index_assign_nd',
                                             'results',
                                             [('imaginary',), ('var', 'j')],
                                             ('div',
                                              ('num', 1.0),
                                              ('add',
                                               ('num', 1.0),
                                               ('call',
                                                'exp',
                                                [('sub',
                                                  ('num', 0.0),
                                                  ('indexN',
                                                   'x',
                                                   [('imaginary',),
                                                    ('var', 'j')]))]))))])])]}},
 'classes': {'FullyConnectedNetwork': {'class_params': [('W',
                                                         ('tensor',
                                                          [(2, 'invariant'),
                                                           (3, 'invariant'),
                                                           (3, 'invariant')])),
                                                        ('B',
                                                         ('tensor',
                                                          [(2, 'invariant'),
                                                           (3, 'invariant'),
                                                           (1, 'invariant')])),
                                                        ('w',
                                                         ('tensor',
                                                          [(1, 'invariant'),
                                                           (3, 'invariant')])),
                                                        ('b', 'ℝ')],
                                       'fields': [],
                                       'methods': [{'name': 'λ',
                                                    'params': [('x',
                                                                ('tensor',
                                                                 [(3,
                                                                   'invariant'),
                                                                  (1,
                                                                   'invariant')]))],
                                                    'return_type': 'ℝ',
                                                    'statements': [('body_for_range',
                                                                    'k',
                                                                    ('num', 0),
                                                                    ('num', 2),
                                                                    [('loop_assign',
                                                                      'x',
                                                                      ('call',
                                                                       'sigma',
                                                                       [('add',
                                                                         ('matmul',
                                                                          ('chain_index',
                                                                           ('field_access',
                                                                            ('var',
                                                                             'this'),
                                                                            'W'),
                                                                           ('var',
                                                                            'k')),
                                                                          ('var',
                                                                           'x')),
                                                                         ('chain_index',
                                                                          ('field_access',
                                                                           ('var',
                                                                            'this'),
                                                                           'B'),
                                                                          ('var',
                                                                           'k')))]))]),
                                                                   ('body_decl',
                                                                    'results',
                                                                    ('tensor',
                                                                     [('m',
                                                                       'invariant'),
                                                                      ('n',
                                                                       'invariant')]),
                                                                    ('add',
                                                                     ('matmul',
                                                                      ('field_access',
                                                                       ('var',
                                                                        'this'),
                                                                       'w'),
                                                                      ('var',
                                                                       'x')),
                                                                     ('field_access',
                                                                      ('var',
                                                                       'this'),
                                                                      'b')))],
                                                    'body': ('indexN',
                                                             'results',
                                                             [('num', 0),
                                                              ('num', 0)])},
                                                   {'name': 'loss',
                                                    'params': [('y', 'ℝ'),
                                                               ('target', 'ℝ')],
                                                    'return_type': 'ℝ',
                                                    'statements': [],
                                                    'body': ('pow',
                                                             ('sub',
                                                              ('var', 'y'),
                                                              ('var',
                                                               'target')),
                                                             ('num', 2.0))},
                                                   {'name': 'train',
                                                    'params': [('X',
                                                                ('tensor',
                                                                 [(4,
                                                                   'invariant'),
                                                                  (3,
                                                                   'invariant'),
                                                                  (1,
                                                                   'invariant')])),
                                                               ('y',
                                                                ('tensor',
                                                                 [(4,
                                                                   'invariant')])),
                                                               ('epochs', 'ℕ'),
                                                               ('lr', 'ℝ')],
                                                    'return_type': 'ℝ',
                                                    'statements': [('body_assign',
                                                                    'len_dataset',
                                                                    ('call',
                                                                     'get_3d_array_depth',
                                                                     [('var',
                                                                       'X')])),
                                                                   ('body_decl',
                                                                    'last_loss',
                                                                    'ℝ',
                                                                    ('num', 0)),
                                                                   ('body_for_range',
                                                                    'i',
                                                                    ('num', 0),
                                                                    ('var',
                                                                     'epochs'),
                                                                    [('loop_assign',
                                                                      'epoch_loss',
                                                                      ('num',
                                                                       0)),
                                                                     ('loop_for_range',
                                                                      'j',
                                                                      ('num',
                                                                       0),
                                                                      ('var',
                                                                       'len_dataset'),
                                                                      [('loop_assign',
                                                                        'pred',
                                                                        ('call',
                                                                         'this',
                                                                         [('index',
                                                                           'X',
                                                                           ('var',
                                                                            'j'))])),
                                                                       ('loop_assign',
                                                                        'current_loss',
                                                                        ('method_call',
                                                                         ('var',
                                                                          'this'),
                                                                         'loss',
                                                                         [('var',
                                                                           'pred'),
                                                                          ('index',
                                                                           'y',
                                                                           ('var',
                                                                            'j'))])),
                                                                       ('loop_assign',
                                                                        'epoch_loss',
                                                                        ('add',
                                                                         ('var',
                                                                          'epoch_loss'),
                                                                         ('var',
                                                                          'current_loss'))),
                                                                       ('loop_assign',
                                                                        'learnable_grads',
                                                                        ('call',
                                                                         'grad',
                                                                         [('var',
                                                                           'current_loss'),
                                                                          ('field_access',
                                                                           ('var',
                                                                            'this'),
                                                                           'learnable_params')])),
                                                                       ('body_expr',
                                                                        ('method_call',
                                                                         ('var',
                                                                          'this'),
                                                                         'update_params',
                                                                         [('var',
                                                                           'lr'),
                                                                          ('var',
                                                                           'learnable_grads')]))]),
                                                                     ('loop_assign',
                                                                      'last_loss',
                                                                      ('div',
                                                                       ('var',
                                                                        'epoch_loss'),
                                                                       ('var',
                                                                        'len_dataset')))])],
                                                    'body': ('var',
                                                             'last_loss')},
                                                   {'name': 'evaluate',
                                                    'params': [('X',
                                                                ('tensor',
                                                                 [(4,
                                                                   'invariant'),
                                                                  (3,
                                                                   'invariant'),
                                                                  (1,
                                                                   'invariant')])),
                                                               ('y',
                                                                ('tensor',
                                                                 [(4,
                                                                   'invariant')]))],
                                                    'return_type': 'ℝ',
                                                    'statements': [('body_decl',
                                                                    'x',
                                                                    'ℝ',
                                                                    ('num',
                                                                     1.5)),
                                                                   ('body_assign',
                                                                    'len_dataset',
                                                                    ('call',
                                                                     'get_3d_array_depth',
                                                                     [('var',
                                                                       'X')])),
                                                                   ('body_assign',
                                                                    'total_loss',
                                                                    ('num', 0)),
                                                                   ('body_for_range',
                                                                    'j',
                                                                    ('num', 0),
                                                                    ('var',
                                                                     'len_dataset'),
                                                                    [('loop_assign',
                                                                      'pred',
                                                                      ('call',
                                                                       'this',
                                                                       [('index',
                                                                         'X',
                                                                         ('var',
                                                                          'j'))])),
                                                                     ('loop_assign',
                                                                      'current_loss',
                                                                      ('method_call',
                                                                       ('var',
                                                                        'this'),
                                                                       'loss',
                                                                       [('var',
                                                                         'pred'),
                                                                        ('index',
                                                                         'y',
                                                                         ('var',
                                                                          'j'))])),
                                                                     ('loop_assign',
                                                                      'total_loss',
                                                                      ('add',
                                                                       ('var',
                                                                        'total_loss'),
                                                                       ('var',
                                                                        'current_loss')))])],
                                                    'body': ('div',
                                                             ('var',
                                                              'total_loss'),
                                                             ('var',
                                                              'len_dataset'))},
                                                   {'name': 'update_params',
                                                    'params': [('lr', 'ℝ'),
                                                               ('learnable_grads',
                                                                ('tensor',
                                                                 [('m',
                                                                   'invariant')]))],
                                                    'return_type': None,
                                                    'statements': [('body_field_assign',
                                                                    ('var',
                                                                     'this'),
                                                                    'W',
                                                                    ('sub',
                                                                     ('field_access',
                                                                      ('var',
                                                                       'this'),
                                                                      'W'),
                                                                     ('mul',
                                                                      ('var',
                                                                       'lr'),
                                                                      ('index',
                                                                       'learnable_grads',
                                                                       ('num',
                                                                        0))))),
                                                                   ('body_field_assign',
                                                                    ('var',
                                                                     'this'),
                                                                    'B',
                                                                    ('sub',
                                                                     ('field_access',
                                                                      ('var',
                                                                       'this'),
                                                                      'B'),
                                                                     ('mul',
                                                                      ('var',
                                                                       'lr'),
                                                                      ('index',
                                                                       'learnable_grads',
                                                                       ('num',
                                                                        1))))),
                                                                   ('body_field_assign',
                                                                    ('var',
                                                                     'this'),
                                                                    'w',
                                                                    ('sub',
                                                                     ('field_access',
                                                                      ('var',
                                                                       'this'),
                                                                      'w'),
                                                                     ('mul',
                                                                      ('var',
                                                                       'lr'),
                                                                      ('index',
                                                                       'learnable_grads',
                                                                       ('num',
                                                                        2))))),
                                                                   ('body_field_assign',
                                                                    ('var',
                                                                     'this'),
                                                                    'b',
                                                                    ('sub',
                                                                     ('field_access',
                                                                      ('var',
                                                                       'this'),
                                                                      'b'),
                                                                     ('mul',
                                                                      ('var',
                                                                       'lr'),
                                                                      ('index',
                                                                       'learnable_grads',
                                                                       ('num',
                                                                        3)))))],
                                                    'body': None}]}},
 'program': [('func_def', 'get_1d_array_length'),
             ('func_def', 'get_2d_array_num_rows'),
             ('func_def', 'zero_2d_array'),
             ('func_def', 'get_3d_array_depth'),
             ('func_def', 'sigma'),
             ('class_def', 'FullyConnectedNetwork'),
             ('decl',
              'X',
              ('tensor',
               [(4, 'invariant'), (3, 'invariant'), (1, 'invariant')]),
              ('array',
               [('array',
                 [('array', [('num', 1.0)]),
                  ('array', [('num', 0.0)]),
                  ('array', [('num', 0.0)])]),
                ('array',
                 [('array', [('num', 0.0)]),
                  ('array', [('num', 1.0)]),
                  ('array', [('num', 0.0)])]),
                ('array',
                 [('array', [('num', 0.0)]),
                  ('array', [('num', 0.0)]),
                  ('array', [('num', 1.0)])]),
                ('array',
                 [('array', [('num', 1.0)]),
                  ('array', [('num', 1.0)]),
                  ('array', [('num', 1.0)])])]),
              93),
             ('decl',
              'y',
              ('tensor', [(4, 'invariant')]),
              ('array',
               [('num', 0.2), ('num', 0.4), ('num', 0.6), ('num', 0.9)]),
              99),
             ('decl',
              'W',
              ('tensor',
               [(2, 'invariant'), (3, 'invariant'), (3, 'invariant')]),
              ('array',
               [('array',
                 [('array', [('num', 0.1), ('num', 0.2), ('num', 0.3)]),
                  ('array', [('num', 0.4), ('num', 0.5), ('num', 0.6)]),
                  ('array', [('num', 0.7), ('num', 0.8), ('num', 0.9)])]),
                ('array',
                 [('array', [('num', 0.2), ('num', 0.3), ('num', 0.4)]),
                  ('array', [('num', 0.5), ('num', 0.6), ('num', 0.7)]),
                  ('array', [('num', 0.8), ('num', 0.9), ('num', 0.1)])])]),
              104),
             ('decl',
              'B',
              ('tensor',
               [(2, 'invariant'), (3, 'invariant'), (1, 'invariant')]),
              ('array',
               [('array',
                 [('array', [('num', 0.1)]),
                  ('array', [('num', 0.2)]),
                  ('array', [('num', 0.3)])]),
                ('array',
                 [('array', [('num', 0.1)]),
                  ('array', [('num', 0.2)]),
                  ('array', [('num', 0.3)])])]),
              106),
             ('decl',
              'w',
              ('tensor', [(1, 'invariant'), (3, 'invariant')]),
              ('array',
               [('array', [('num', 0.5), ('num', 0.5), ('num', 0.5)])]),
              110),
             ('decl', 'b', 'ℝ', ('num', 0.1), 111),
             ('assign',
              'net',
              ('call',
               'FullyConnectedNetwork',
               [('var', 'W'), ('var', 'B'), ('var', 'w'), ('var', 'b')]),
              113),
             ('assign',
              'loss_before',
              ('method_call',
               ('var', 'net'),
               'evaluate',
               [('var', 'X'), ('var', 'y')]),
              118),
             ('expr', ('var', 'loss_before'), 0),
             ('decl', 'epochs', 'ℕ', ('num', 1000), 124),
             ('decl', 'lr', 'ℝ', ('num', 0.1), 125),
             ('assign',
              'net_trained',
              ('method_call',
               ('var', 'net'),
               'train',
               [('var', 'X'), ('var', 'y'), ('var', 'epochs'), ('var', 'lr')]),
              126),
             ('expr', ('var', 'net_trained'), 0),
             ('assign',
              'loss_after',
              ('method_call',
               ('var', 'net'),
               'evaluate',
               [('var', 'X'), ('var', 'y')]),
              132),
             ('expr', ('var', 'loss_after'), 0),
             ('expr',
              ('call',
               'net',
               [('array', [('num', 1.0), ('num', 0.0), ('num', 0.0)])]),
              0),
             ('expr',
              ('call',
               'net',
               [('array', [('num', 0.0), ('num', 1.0), ('num', 0.0)])]),
              0),
             ('expr',
              ('call',
               'net',
               [('array', [('num', 0.0), ('num', 0.0), ('num', 1.0)])]),
              0),
             ('expr',
              ('call',
               'net',
               [('array', [('num', 1.0), ('num', 1.0), ('num', 1.0)])]),
              0)]}
