EXPECTED = {'functions': {'unpack_simple_array': {'params': [('arr',
                                                   ('tensor',
                                                    [(3, 'invariant')]))],
                                       'return_type': 'ℝ',
                                       'body': ('var', 'a'),
                                       'has_loop': False,
                                       'statements': [('body_tuple_unpack',
                                                       [('a', 'ℝ'),
                                                        ('b', 'ℝ'),
                                                        ('c', 'ℝ')],
                                                       ('var', 'arr'))]},
               'return_array': {'params': [('n', 'ℝ')],
                                'return_type': ('tensor', [('n', 'invariant')]),
                                'body': ('var', 'results'),
                                'has_loop': False,
                                'statements': [('body_decl',
                                                'results',
                                                ('tensor',
                                                 [('n', 'invariant')]),
                                                ('for_expr',
                                                 'i',
                                                 ('var', 'n'),
                                                 ('mul',
                                                  ('imaginary',),
                                                  ('num', 1))))]},
               'unpack_array_in_function_call': {'params': [('n', 'ℝ')],
                                                 'return_type': 'ℝ',
                                                 'body': ('var', 'c'),
                                                 'has_loop': False,
                                                 'statements': [('body_tuple_unpack',
                                                                 [('a', 'ℝ'),
                                                                  ('b', 'ℝ'),
                                                                  ('c', 'ℝ')],
                                                                 ('call',
                                                                  'return_array',
                                                                  [('var',
                                                                    'n')]))]}},
 'classes': {'Simple': {'class_params': [('v', 'ℝ')],
                        'fields': [],
                        'methods': [{'name': 'get',
                                     'params': [],
                                     'return_type': ('tuple_type', ['ℝ', 'ℝ']),
                                     'statements': [],
                                     'body': ('tuple_return',
                                              ('field_access',
                                               ('var', 'this'),
                                               'v'),
                                              ('field_access',
                                               ('var', 'this'),
                                               'v'))},
                                    {'name': 'sum_pairs',
                                     'params': [('n', 'ℕ')],
                                     'return_type': 'ℝ',
                                     'statements': [('body_decl',
                                                     'total',
                                                     'ℝ',
                                                     ('num', 0.0)),
                                                    ('body_for_range',
                                                     'k',
                                                     ('num', 0),
                                                     ('var', 'n'),
                                                     [('loop_tuple_unpack',
                                                       ['a', 'b'],
                                                       ('method_call',
                                                        ('var', 'this'),
                                                        'get',
                                                        [])),
                                                      ('loop_assign',
                                                       'total',
                                                       ('add',
                                                        ('add',
                                                         ('var', 'total'),
                                                         ('var', 'a')),
                                                        ('var', 'b')))])],
                                     'body': ('var', 'total')}]},
             'Pair': {'class_params': [('a', 'ℝ'), ('b', 'ℝ')],
                      'fields': [],
                      'methods': [{'name': 'get',
                                   'params': [],
                                   'return_type': ('tuple_type', ['ℝ', 'ℝ']),
                                   'statements': [],
                                   'body': ('tuple_return',
                                            ('field_access',
                                             ('var', 'this'),
                                             'a'),
                                            ('field_access',
                                             ('var', 'this'),
                                             'b'))},
                                  {'name': 'sum',
                                   'params': [],
                                   'return_type': 'ℝ',
                                   'statements': [('body_tuple_unpack',
                                                   ['x', 'y'],
                                                   ('method_call',
                                                    ('var', 'this'),
                                                    'get',
                                                    []))],
                                   'body': ('add',
                                            ('var', 'x'),
                                            ('var', 'y'))}]},
             'Model': {'class_params': [('a', 'ℝ'), ('b', 'ℝ')],
                       'fields': [],
                       'methods': [{'name': 'pair',
                                    'params': [],
                                    'return_type': ('tuple_type', ['ℝ', 'ℝ']),
                                    'statements': [],
                                    'body': ('tuple_return',
                                             ('field_access',
                                              ('var', 'this'),
                                              'a'),
                                             ('field_access',
                                              ('var', 'this'),
                                              'b'))},
                                   {'name': 'run',
                                    'params': [('steps', 'ℕ')],
                                    'return_type': 'ℝ',
                                    'statements': [('body_tuple_unpack',
                                                    ['x', 'y'],
                                                    ('method_call',
                                                     ('var', 'this'),
                                                     'pair',
                                                     [])),
                                                   ('body_decl',
                                                    'total',
                                                    'ℝ',
                                                    ('add',
                                                     ('var', 'x'),
                                                     ('var', 'y'))),
                                                   ('body_for_range',
                                                    'k',
                                                    ('num', 0),
                                                    ('var', 'steps'),
                                                    [('loop_tuple_unpack',
                                                      ['p', 'q'],
                                                      ('method_call',
                                                       ('var', 'this'),
                                                       'pair',
                                                       [])),
                                                     ('loop_assign',
                                                      'total',
                                                      ('add',
                                                       ('add',
                                                        ('var', 'total'),
                                                        ('var', 'p')),
                                                       ('var', 'q')))])],
                                    'body': ('var', 'total')}]},
             'Grid': {'class_params': [('v', 'ℝ')],
                      'fields': [],
                      'methods': [{'name': 'compute',
                                   'params': [('n', 'ℕ')],
                                   'return_type': 'ℝ',
                                   'statements': [('body_decl',
                                                   'arr',
                                                   ('tensor',
                                                    [(3, 'invariant')]),
                                                   ('for_expr',
                                                    'i',
                                                    ('num', 3),
                                                    ('field_access',
                                                     ('var', 'this'),
                                                     'v'))),
                                                  ('body_decl',
                                                   'total',
                                                   'ℝ',
                                                   ('num', 0.0)),
                                                  ('body_for_range',
                                                   'k',
                                                   ('num', 0),
                                                   ('var', 'n'),
                                                   [('loop_tuple_unpack',
                                                     [('a', 'ℝ'),
                                                      ('b', 'ℝ'),
                                                      ('c', 'ℝ')],
                                                     ('var', 'arr')),
                                                    ('loop_assign',
                                                     'total',
                                                     ('add',
                                                      ('add',
                                                       ('add',
                                                        ('var', 'total'),
                                                        ('var', 'a')),
                                                       ('var', 'b')),
                                                      ('var', 'c')))])],
                                   'body': ('var', 'total')}]},
             'Point': {'class_params': [('x', 'ℝ'), ('y', 'ℝ')],
                       'fields': [],
                       'methods': [{'name': 'get',
                                    'params': [],
                                    'return_type': ('tuple_type', ['ℝ', 'ℝ']),
                                    'statements': [],
                                    'body': ('tuple_return',
                                             ('field_access',
                                              ('var', 'this'),
                                              'x'),
                                             ('field_access',
                                              ('var', 'this'),
                                              'y'))}]},
             'Vec4': {'class_params': [('w', 'ℝ'),
                                       ('x', 'ℝ'),
                                       ('y', 'ℝ'),
                                       ('z', 'ℝ')],
                      'fields': [],
                      'methods': [{'name': 'f',
                                   'params': [],
                                   'return_type': ('tuple_type',
                                                   ['ℝ', 'ℝ', 'ℝ', 'ℝ']),
                                   'statements': [],
                                   'body': ('tuple_return',
                                            ('mul',
                                             ('field_access',
                                              ('var', 'this'),
                                              'w'),
                                             ('num', 10)),
                                            ('mul',
                                             ('field_access',
                                              ('var', 'this'),
                                              'x'),
                                             ('num', 10)),
                                            ('mul',
                                             ('field_access',
                                              ('var', 'this'),
                                              'y'),
                                             ('num', 10)),
                                            ('mul',
                                             ('field_access',
                                              ('var', 'this'),
                                              'z'),
                                             ('num', 10)))}]},
             'Tensors': {'class_params': [('a', ('tensor', [(3, 'invariant')])),
                                          ('b',
                                           ('tensor', [(3, 'invariant')]))],
                         'fields': [],
                         'methods': [{'name': 'sum_parts',
                                      'params': [],
                                      'return_type': ('tensor',
                                                      [(3, 'invariant')]),
                                      'statements': [('body_tuple_unpack',
                                                      [('x',
                                                        ('tensor',
                                                         [(3, 'invariant')])),
                                                       ('y',
                                                        ('tensor',
                                                         [(3, 'invariant')]))],
                                                      ('expr_list',
                                                       [('field_access',
                                                         ('var', 'this'),
                                                         'a'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'b')]))],
                                      'body': ('add',
                                               ('var', 'x'),
                                               ('var', 'y'))}]},
             'Vec2': {'class_params': [('x', 'ℝ'), ('y', 'ℝ')],
                      'fields': [],
                      'methods': [{'name': 'f',
                                   'params': [],
                                   'return_type': ('tuple_type', ['ℝ', 'ℝ']),
                                   'statements': [],
                                   'body': ('tuple_return',
                                            ('mul',
                                             ('field_access',
                                              ('var', 'this'),
                                              'x'),
                                             ('num', 10)),
                                            ('mul',
                                             ('field_access',
                                              ('var', 'this'),
                                              'y'),
                                             ('num', 10)))}]},
             'A': {'class_params': [('x', 'ℝ'),
                                    ('y', 'ℝ'),
                                    ('z', 'ℝ'),
                                    ('c1', 'ℂ'),
                                    ('c2', 'ℂ'),
                                    ('total1', 'ℕ'),
                                    ('total2', 'ℕ')],
                   'fields': [],
                   'methods': [{'name': 'return_Real_type',
                                'params': [],
                                'return_type': 'ℝ',
                                'statements': [],
                                'body': ('field_access', ('var', 'this'), 'x')},
                               {'name': 'return_Complex_type',
                                'params': [],
                                'return_type': 'ℂ',
                                'statements': [],
                                'body': ('field_access',
                                         ('var', 'this'),
                                         'c1')},
                               {'name': 'return_Natural_type',
                                'params': [],
                                'return_type': 'ℕ',
                                'statements': [],
                                'body': ('field_access',
                                         ('var', 'this'),
                                         'total1')}]}},
 'program': [('stmt_tuple_unpack',
              [('a', 'ℝ'), ('b', 'ℝ'), ('c', 'ℝ'), ('d', 'ℝ')],
              ('expr_list', [('num', 1), ('num', 2), ('num', 3), ('num', 4)])),
             ('expr', ('var', 'a'), 0),
             ('expr', ('var', 'b'), 0),
             ('expr', ('var', 'c'), 0),
             ('expr', ('var', 'd'), 0),
             ('stmt_tuple_unpack',
              [('a', 'ℝ'), ('b', 'ℝ')],
              ('expr_list', [('num', 7), ('num', 8)])),
             ('expr', ('var', 'a'), 0),
             ('expr', ('var', 'b'), 0),
             ('stmt_tuple_unpack',
              [('x_complex', 'ℂ'), ('y_complex', 'ℂ')],
              ('expr_list', [('complex', 1j), ('complex', 2j)])),
             ('expr', ('var', 'x_complex'), 0),
             ('expr', ('var', 'y_complex'), 0),
             ('stmt_tuple_unpack',
              [('x_arr', ('tensor', [(2, 'invariant'), (2, 'invariant')])),
               ('y_arr', ('tensor', [(2, 'invariant'), (2, 'invariant')]))],
              ('expr_list',
               [('array',
                 [('array', [('num', 1), ('num', 1)]),
                  ('array', [('num', 1), ('num', 1)])]),
                ('array',
                 [('array', [('num', 1), ('num', 1)]),
                  ('array', [('num', 1), ('num', 1)])])])),
             ('expr', ('var', 'x_arr'), 0),
             ('expr', ('var', 'y_arr'), 0),
             ('func_def', 'unpack_simple_array'),
             ('expr',
              ('call',
               'unpack_simple_array',
               [('array', [('num', 1), ('num', 2), ('num', 3)])]),
              0),
             ('func_def', 'return_array'),
             ('func_def', 'unpack_array_in_function_call'),
             ('expr',
              ('call', 'unpack_array_in_function_call', [('num', 3)]),
              0),
             ('decl',
              'sample_arr',
              ('tensor', [(3, 'invariant'), (3, 'invariant')]),
              ('array',
               [('array', [('num', 1), ('num', 2), ('num', 3)]),
                ('array', [('num', 4), ('num', 5), ('num', 6)]),
                ('array', [('num', 7), ('num', 8), ('num', 9)])]),
              65),
             ('for_loop_range',
              'i',
              ('num', 0),
              ('num', 3),
              [('stmt_tuple_unpack',
                [('a', 'ℝ'), ('b', 'ℝ'), ('c', 'ℝ')],
                ('index', 'sample_arr', ('imaginary',))),
               ('for_call', 'print', [('var', 'a')]),
               ('for_call', 'print', [('var', 'b')]),
               ('for_call', 'print', [('var', 'c')])],
              71),
             ('class_def', 'Simple'),
             ('class_def', 'Pair'),
             ('class_def', 'Model'),
             ('class_def', 'Grid'),
             ('class_def', 'Point'),
             ('decl',
              'p',
              ('struct_type', 'Point'),
              ('call', 'Point', [('num', 1.0), ('num', 2.0)]),
              124),
             ('stmt_tuple_unpack',
              [('a', 'ℝ'), ('b', 'ℝ')],
              ('method_call', ('var', 'p'), 'get', [])),
             ('decl', 'result', 'ℝ', ('add', ('var', 'a'), ('var', 'b')), 126),
             ('expr', ('var', 'a'), 0),
             ('expr', ('var', 'b'), 0),
             ('expr', ('var', 'result'), 0),
             ('class_def', 'Vec4'),
             ('decl',
              'v',
              ('struct_type', 'Vec4'),
              ('call',
               'Vec4',
               [('num', 0.5), ('num', 1.0), ('num', 2.0), ('num', 3.0)]),
              135),
             ('stmt_tuple_unpack',
              [('a', 'ℝ'), ('b', 'ℝ'), ('c', 'ℝ'), ('d', 'ℝ')],
              ('method_call', ('var', 'v'), 'f', [])),
             ('expr', ('var', 'a'), 0),
             ('expr', ('var', 'b'), 0),
             ('expr', ('var', 'c'), 0),
             ('expr', ('var', 'd'), 0),
             ('class_def', 'Tensors'),
             ('class_def', 'Vec2'),
             ('decl',
              'v',
              ('struct_type', 'Vec2'),
              ('call', 'Vec2', [('num', 0.5), ('num', 1.0)]),
              151),
             ('stmt_tuple_unpack',
              [('a', 'ℝ'), ('b', 'ℝ')],
              ('method_call', ('var', 'v'), 'f', [])),
             ('expr', ('var', 'a'), 0),
             ('expr', ('var', 'b'), 0),
             ('class_def', 'A'),
             ('decl',
              'obj_A',
              ('struct_type', 'A'),
              ('call',
               'A',
               [('num', 1.0),
                ('num', 2.0),
                ('num', 3.0),
                ('complex', 1j),
                ('complex', 2j),
                ('num', 10),
                ('num', 20)]),
              172),
             ('expr',
              ('method_call', ('var', 'obj_A'), 'return_Real_type', []),
              0),
             ('expr',
              ('method_call', ('var', 'obj_A'), 'return_Complex_type', []),
              0),
             ('expr',
              ('method_call', ('var', 'obj_A'), 'return_Natural_type', []),
              0)]}
