EXPECTED = {'functions': {},
 'classes': {'Simple': {'class_params': [('v', 'ℝ')],
                        'fields': [],
                        'methods': [{'name': 'get',
                                     'params': [],
                                     'return_type': ('tuple_type', ['ℝ', 'ℝ']),
                                     'statements': [],
                                     'body': ('tuple_return',
                                              ('field_access',
                                               ('var', 'this'),
                                               'v'),
                                              ('field_access',
                                               ('var', 'this'),
                                               'v'))},
                                    {'name': 'sum_pairs',
                                     'params': [('n', 'ℕ')],
                                     'return_type': 'ℝ',
                                     'statements': [('body_decl',
                                                     'total',
                                                     'ℝ',
                                                     ('num', 0.0)),
                                                    ('body_for_range',
                                                     'k',
                                                     ('num', 0),
                                                     ('var', 'n'),
                                                     [('loop_tuple_unpack',
                                                       ['a', 'b'],
                                                       ('method_call',
                                                        ('var', 'this'),
                                                        'get',
                                                        [])),
                                                      ('loop_assign',
                                                       'total',
                                                       ('add',
                                                        ('add',
                                                         ('var', 'total'),
                                                         ('var', 'a')),
                                                        ('var', 'b')))])],
                                     'body': ('var', 'total')}]},
             'Pair': {'class_params': [('a', 'ℝ'), ('b', 'ℝ')],
                      'fields': [],
                      'methods': [{'name': 'get',
                                   'params': [],
                                   'return_type': ('tuple_type', ['ℝ', 'ℝ']),
                                   'statements': [],
                                   'body': ('tuple_return',
                                            ('field_access',
                                             ('var', 'this'),
                                             'a'),
                                            ('field_access',
                                             ('var', 'this'),
                                             'b'))},
                                  {'name': 'sum',
                                   'params': [],
                                   'return_type': 'ℝ',
                                   'statements': [('body_tuple_unpack',
                                                   ['x', 'y'],
                                                   ('method_call',
                                                    ('var', 'this'),
                                                    'get',
                                                    []))],
                                   'body': ('add',
                                            ('var', 'x'),
                                            ('var', 'y'))}]},
             'Model': {'class_params': [('a', 'ℝ'), ('b', 'ℝ')],
                       'fields': [],
                       'methods': [{'name': 'pair',
                                    'params': [],
                                    'return_type': ('tuple_type', ['ℝ', 'ℝ']),
                                    'statements': [],
                                    'body': ('tuple_return',
                                             ('field_access',
                                              ('var', 'this'),
                                              'a'),
                                             ('field_access',
                                              ('var', 'this'),
                                              'b'))},
                                   {'name': 'run',
                                    'params': [('steps', 'ℕ')],
                                    'return_type': 'ℝ',
                                    'statements': [('body_tuple_unpack',
                                                    ['x', 'y'],
                                                    ('method_call',
                                                     ('var', 'this'),
                                                     'pair',
                                                     [])),
                                                   ('body_decl',
                                                    'total',
                                                    'ℝ',
                                                    ('add',
                                                     ('var', 'x'),
                                                     ('var', 'y'))),
                                                   ('body_for_range',
                                                    'k',
                                                    ('num', 0),
                                                    ('var', 'steps'),
                                                    [('loop_tuple_unpack',
                                                      ['p', 'q'],
                                                      ('method_call',
                                                       ('var', 'this'),
                                                       'pair',
                                                       [])),
                                                     ('loop_assign',
                                                      'total',
                                                      ('add',
                                                       ('add',
                                                        ('var', 'total'),
                                                        ('var', 'p')),
                                                       ('var', 'q')))])],
                                    'body': ('var', 'total')}]},
             'Grid': {'class_params': [('v', 'ℝ')],
                      'fields': [],
                      'methods': [{'name': 'compute',
                                   'params': [('n', 'ℕ')],
                                   'return_type': 'ℝ',
                                   'statements': [('body_decl',
                                                   'arr',
                                                   ('tensor',
                                                    [(3, 'invariant')]),
                                                   ('for_expr',
                                                    'i',
                                                    ('num', 3),
                                                    ('field_access',
                                                     ('var', 'this'),
                                                     'v'))),
                                                  ('body_decl',
                                                   'total',
                                                   'ℝ',
                                                   ('num', 0.0)),
                                                  ('body_for_range',
                                                   'k',
                                                   ('num', 0),
                                                   ('var', 'n'),
                                                   [('loop_tuple_unpack',
                                                     [('a', 'ℝ'),
                                                      ('b', 'ℝ'),
                                                      ('c', 'ℝ')],
                                                     ('var', 'arr')),
                                                    ('loop_assign',
                                                     'total',
                                                     ('add',
                                                      ('add',
                                                       ('add',
                                                        ('var', 'total'),
                                                        ('var', 'a')),
                                                       ('var', 'b')),
                                                      ('var', 'c')))])],
                                   'body': ('var', 'total')}]},
             'Point': {'class_params': [('x', 'ℝ'), ('y', 'ℝ')],
                       'fields': [],
                       'methods': [{'name': 'get',
                                    'params': [],
                                    'return_type': ('tuple_type', ['ℝ', 'ℝ']),
                                    'statements': [],
                                    'body': ('tuple_return',
                                             ('field_access',
                                              ('var', 'this'),
                                              'x'),
                                             ('field_access',
                                              ('var', 'this'),
                                              'y'))}]},
             'Vec4': {'class_params': [('w', 'ℝ'),
                                       ('x', 'ℝ'),
                                       ('y', 'ℝ'),
                                       ('z', 'ℝ')],
                      'fields': [],
                      'methods': [{'name': 'f',
                                   'params': [],
                                   'return_type': ('tuple_type',
                                                   ['ℝ', 'ℝ', 'ℝ', 'ℝ']),
                                   'statements': [],
                                   'body': ('tuple_return',
                                            ('mul',
                                             ('field_access',
                                              ('var', 'this'),
                                              'w'),
                                             ('num', 10)),
                                            ('mul',
                                             ('field_access',
                                              ('var', 'this'),
                                              'x'),
                                             ('num', 10)),
                                            ('mul',
                                             ('field_access',
                                              ('var', 'this'),
                                              'y'),
                                             ('num', 10)),
                                            ('mul',
                                             ('field_access',
                                              ('var', 'this'),
                                              'z'),
                                             ('num', 10)))}]},
             'Tensors': {'class_params': [('a', ('tensor', [(3, 'invariant')])),
                                          ('b',
                                           ('tensor', [(3, 'invariant')]))],
                         'fields': [],
                         'methods': [{'name': 'sum_parts',
                                      'params': [],
                                      'return_type': ('tensor',
                                                      [(3, 'invariant')]),
                                      'statements': [('body_tuple_unpack',
                                                      [('x',
                                                        ('tensor',
                                                         [(3, 'invariant')])),
                                                       ('y',
                                                        ('tensor',
                                                         [(3, 'invariant')]))],
                                                      ('expr_list',
                                                       [('field_access',
                                                         ('var', 'this'),
                                                         'a'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'b')]))],
                                      'body': ('add',
                                               ('var', 'x'),
                                               ('var', 'y'))}]},
             'Vec2': {'class_params': [('x', 'ℝ'), ('y', 'ℝ')],
                      'fields': [],
                      'methods': [{'name': 'f',
                                   'params': [],
                                   'return_type': ('tuple_type', ['ℝ', 'ℝ']),
                                   'statements': [],
                                   'body': ('tuple_return',
                                            ('mul',
                                             ('field_access',
                                              ('var', 'this'),
                                              'x'),
                                             ('num', 10)),
                                            ('mul',
                                             ('field_access',
                                              ('var', 'this'),
                                              'y'),
                                             ('num', 10)))}]}},
 'program': [('class_def', 'Simple'),
             ('class_def', 'Pair'),
             ('class_def', 'Model'),
             ('class_def', 'Grid'),
             ('class_def', 'Point'),
             ('decl',
              'p',
              ('struct_type', 'Point'),
              ('call', 'Point', [('num', 1.0), ('num', 2.0)]),
              42),
             ('stmt_tuple_unpack',
              [('a', 'ℝ'), ('b', 'ℝ')],
              ('method_call', ('var', 'p'), 'get', [])),
             ('decl', 'result', 'ℝ', ('add', ('var', 'a'), ('var', 'b')), 44),
             ('expr', ('var', 'a'), 0),
             ('expr', ('var', 'b'), 0),
             ('expr', ('var', 'result'), 0),
             ('class_def', 'Vec4'),
             ('decl',
              'v',
              ('struct_type', 'Vec4'),
              ('call',
               'Vec4',
               [('num', 0.5), ('num', 1.0), ('num', 2.0), ('num', 3.0)]),
              53),
             ('stmt_tuple_unpack',
              [('a', 'ℝ'), ('b', 'ℝ'), ('c', 'ℝ'), ('d', 'ℝ')],
              ('method_call', ('var', 'v'), 'f', [])),
             ('expr', ('var', 'a'), 0),
             ('expr', ('var', 'b'), 0),
             ('expr', ('var', 'c'), 0),
             ('expr', ('var', 'd'), 0),
             ('class_def', 'Tensors'),
             ('class_def', 'Vec2'),
             ('decl',
              'v',
              ('struct_type', 'Vec2'),
              ('call', 'Vec2', [('num', 0.5), ('num', 1.0)]),
              69),
             ('stmt_tuple_unpack',
              [('a', 'ℝ'), ('b', 'ℝ')],
              ('method_call', ('var', 'v'), 'f', [])),
             ('expr', ('var', 'a'), 0),
             ('expr', ('var', 'b'), 0),
             ('stmt_tuple_unpack',
              [('a', 'ℝ'), ('b', 'ℝ'), ('c', 'ℝ'), ('d', 'ℝ')],
              ('expr_list', [('num', 1), ('num', 2), ('num', 3), ('num', 4)])),
             ('expr', ('var', 'a'), 0),
             ('expr', ('var', 'b'), 0),
             ('expr', ('var', 'c'), 0),
             ('expr', ('var', 'd'), 0)]}
