EXPECTED = {'functions': {'modulo': {'params': [('s', 'ℝ'), ('m', 'ℝ')],
                          'return_type': 'ℝ',
                          'body': ('var', 'r'),
                          'has_loop': False,
                          'statements': [('body_decl', 'r', 'ℝ', ('var', 's')),
                                         ('body_decl',
                                          'd',
                                          'ℝ',
                                          ('mul',
                                           ('var', 'm'),
                                           ('pow',
                                            ('num', 2.0),
                                            ('sub', ('var', 'BITS'), ('num', 1))))),
                                         ('body_for_range',
                                          'k',
                                          ('num', 0),
                                          ('var', 'BITS'),
                                          [('loop_if',
                                            ('cond_geq', ('var', 'r'), ('var', 'd')),
                                            [('loop_assign',
                                              'r',
                                              ('sub', ('var', 'r'), ('var', 'd')))]),
                                           ('loop_assign',
                                            'd',
                                            ('div', ('var', 'd'), ('num', 2.0)))])]},
               'hash_list': {'params': [('xs', ('tensor', [('n', 'invariant')]))],
                             'return_type': 'ℝ',
                             'body': ('var', 'h'),
                             'has_loop': False,
                             'statements': [('body_decl', 'h', 'ℝ', ('num', 17.0)),
                                            ('body_for_range',
                                             'i',
                                             ('num', 0),
                                             ('call', 'len', [('var', 'xs')]),
                                             [('loop_assign',
                                               'h',
                                               ('call',
                                                'modulo',
                                                [('add',
                                                  ('mul', ('var', 'h'), ('num', 31.0)),
                                                  ('index', 'xs', ('imaginary',))),
                                                 ('var', 'M')]))])]},
               'hash_step': {'params': [('h', 'ℝ'), ('x', 'ℝ')],
                             'return_type': 'ℝ',
                             'body': ('call',
                                      'modulo',
                                      [('add',
                                        ('mul', ('var', 'h'), ('num', 31.0)),
                                        ('var', 'x')),
                                       ('var', 'M')]),
                             'has_loop': False,
                             'statements': []},
               'bubble_sort': {'params': [('xs', ('tensor', [('n', 'invariant')]))],
                               'return_type': ('tensor', [('n', 'invariant')]),
                               'body': ('var', 'ys'),
                               'has_loop': False,
                               'statements': [('body_decl',
                                               'k',
                                               'ℕ',
                                               ('call', 'len', [('var', 'xs')])),
                                              ('body_decl',
                                               'ys',
                                               ('tensor', [('k', 'invariant')]),
                                               ('for_expr',
                                                'a',
                                                ('var', 'k'),
                                                ('index', 'xs', ('var', 'a')))),
                                              ('body_for_range',
                                               'i',
                                               ('num', 0),
                                               ('var', 'k'),
                                               [('loop_for_range',
                                                 'j',
                                                 ('num', 0),
                                                 ('sub', ('var', 'k'), ('num', 1)),
                                                 [('loop_if',
                                                   ('cond_gt',
                                                    ('index', 'ys', ('var', 'j')),
                                                    ('index',
                                                     'ys',
                                                     ('add',
                                                      ('var', 'j'),
                                                      ('num', 1)))),
                                                   [('loop_tuple_unpack',
                                                     [('t', 'ℝ')],
                                                     ('add',
                                                      ('index', 'ys', ('var', 'j')),
                                                      ('num', 0.0))),
                                                    ('loop_index_assign_nd',
                                                     'ys',
                                                     [('index_item', ('var', 'j'))],
                                                     ('index',
                                                      'ys',
                                                      ('add',
                                                       ('var', 'j'),
                                                       ('num', 1)))),
                                                    ('loop_index_assign_nd',
                                                     'ys',
                                                     [('index_item',
                                                       ('add',
                                                        ('var', 'j'),
                                                        ('num', 1)))],
                                                     ('var', 't'))])])])]},
               'get_2d_array_num_rows': {'params': [('x',
                                                     ('tensor',
                                                      [('m', 'invariant'),
                                                       ('n', 'invariant')]))],
                                         'return_type': 'ℝ',
                                         'body': ('var', 'total'),
                                         'has_loop': False,
                                         'statements': [('body_decl',
                                                         'total',
                                                         'ℝ',
                                                         ('num', 0)),
                                                        ('body_decl',
                                                         'temp',
                                                         'ℝ',
                                                         ('num', 0)),
                                                        ('body_for',
                                                         'i',
                                                         [('loop_assign',
                                                           'temp',
                                                           ('index',
                                                            'x',
                                                            ('imaginary',))),
                                                          ('loop_pluseq',
                                                           'total',
                                                           ('num', 1))],
                                                         ['x'])]},
               'new_molecule': {'params': [('atomic_num',
                                            ('tensor', [('n', 'invariant')])),
                                           ('formal_charge',
                                            ('tensor', [('n', 'invariant')]))],
                                'return_type': ('struct_type', 'Molecule'),
                                'body': ('var', 'g'),
                                'has_loop': False,
                                'statements': [('body_decl',
                                                'n_atoms',
                                                'ℕ',
                                                ('call',
                                                 'len',
                                                 [('var', 'atomic_num')])),
                                               ('body_decl',
                                                'z',
                                                ('tensor',
                                                 [('n_atoms', 'invariant'),
                                                  ('n_atoms', 'invariant')]),
                                                ('for_expr',
                                                 'a',
                                                 ('var', 'n_atoms'),
                                                 ('for_expr',
                                                  'b',
                                                  ('var', 'n_atoms'),
                                                  ('mul',
                                                   ('add', ('var', 'a'), ('var', 'b')),
                                                   ('num', 0.0))))),
                                               ('body_decl',
                                                'g',
                                                ('struct_type', 'Molecule'),
                                                ('call', 'Molecule', [])),
                                               ('body_field_assign',
                                                ('var', 'g'),
                                                'adjacency',
                                                ('var', 'z')),
                                               ('body_field_assign',
                                                ('var', 'g'),
                                                'atomic_num',
                                                ('var', 'atomic_num')),
                                               ('body_field_assign',
                                                ('var', 'g'),
                                                'formal_charge',
                                                ('var', 'formal_charge'))]},
               'degree': {'params': [('g', ('struct_type', 'Molecule')), ('u', 'ℕ')],
                          'return_type': 'ℝ',
                          'body': ('var', 'd'),
                          'has_loop': False,
                          'statements': [('body_decl',
                                          'm',
                                          ('tensor',
                                           [('n', 'invariant'), ('n', 'invariant')]),
                                          ('field_access', ('var', 'g'), 'adjacency')),
                                         ('body_decl',
                                          'k',
                                          'ℝ',
                                          ('call',
                                           'get_2d_array_num_rows',
                                           [('var', 'm')])),
                                         ('body_decl', 'd', 'ℝ', ('num', 0)),
                                         ('body_for_range',
                                          'v',
                                          ('num', 0),
                                          ('var', 'k'),
                                          [('loop_if',
                                            ('cond_gt',
                                             ('indexN',
                                              'm',
                                              [('index_item', ('var', 'u')),
                                               ('index_item', ('var', 'v'))]),
                                             ('num', 0.0)),
                                            [('loop_pluseq', 'd', ('num', 1))])])]},
               'hydrogens': {'params': [('g', ('struct_type', 'Molecule')), ('u', 'ℕ')],
                             'return_type': 'ℝ',
                             'body': ('var', 'h'),
                             'has_loop': False,
                             'statements': [('body_decl',
                                             'm',
                                             ('tensor',
                                              [('n', 'invariant'), ('n', 'invariant')]),
                                             ('field_access',
                                              ('var', 'g'),
                                              'adjacency')),
                                            ('body_decl',
                                             'z',
                                             ('tensor', [('n', 'invariant')]),
                                             ('field_access',
                                              ('var', 'g'),
                                              'atomic_num')),
                                            ('body_decl',
                                             'k',
                                             'ℝ',
                                             ('call',
                                              'get_2d_array_num_rows',
                                              [('var', 'm')])),
                                            ('body_decl', 'h', 'ℝ', ('num', 0)),
                                            ('body_for_range',
                                             'v',
                                             ('num', 0),
                                             ('var', 'k'),
                                             [('loop_if',
                                               ('cond_gt',
                                                ('indexN',
                                                 'm',
                                                 [('index_item', ('var', 'u')),
                                                  ('index_item', ('var', 'v'))]),
                                                ('num', 0.0)),
                                               [('loop_if',
                                                 ('cond_eq',
                                                  ('index', 'z', ('var', 'v')),
                                                  ('num', 1.0)),
                                                 [('loop_pluseq',
                                                   'h',
                                                   ('num', 1))])])])]},
               'aromatic': {'params': [('g', ('struct_type', 'Molecule')), ('u', 'ℕ')],
                            'return_type': 'ℝ',
                            'body': ('var', 'r'),
                            'has_loop': False,
                            'statements': [('body_decl',
                                            'm',
                                            ('tensor',
                                             [('n', 'invariant'), ('n', 'invariant')]),
                                            ('field_access',
                                             ('var', 'g'),
                                             'adjacency')),
                                           ('body_decl',
                                            'k',
                                            'ℝ',
                                            ('call',
                                             'get_2d_array_num_rows',
                                             [('var', 'm')])),
                                           ('body_decl', 'r', 'ℝ', ('num', 0)),
                                           ('body_for_range',
                                            'v',
                                            ('num', 0),
                                            ('var', 'k'),
                                            [('loop_if',
                                              ('cond_eq',
                                               ('indexN',
                                                'm',
                                                [('index_item', ('var', 'u')),
                                                 ('index_item', ('var', 'v'))]),
                                               ('num', 1.5)),
                                              [('loop_assign', 'r', ('num', 1))])])]},
               'invariants': {'params': [('g', ('struct_type', 'Molecule'))],
                              'return_type': ('tensor',
                                              [(5, 'invariant'), ('n', 'invariant')]),
                              'body': ('var', 'inv'),
                              'has_loop': False,
                              'statements': [('body_decl',
                                              'm',
                                              ('tensor',
                                               [('n', 'invariant'),
                                                ('n', 'invariant')]),
                                              ('field_access',
                                               ('var', 'g'),
                                               'adjacency')),
                                             ('body_decl',
                                              'z',
                                              ('tensor', [('n', 'invariant')]),
                                              ('field_access',
                                               ('var', 'g'),
                                               'atomic_num')),
                                             ('body_decl',
                                              'c',
                                              ('tensor', [('n', 'invariant')]),
                                              ('field_access',
                                               ('var', 'g'),
                                               'formal_charge')),
                                             ('body_decl',
                                              'k',
                                              'ℝ',
                                              ('call',
                                               'get_2d_array_num_rows',
                                               [('var', 'm')])),
                                             ('body_decl',
                                              'inv',
                                              ('tensor',
                                               [(5, 'invariant'), ('k', 'invariant')]),
                                              ('for_expr',
                                               'i',
                                               ('num', 5),
                                               ('for_expr',
                                                'a',
                                                ('var', 'k'),
                                                ('mul', ('var', 'a'), ('num', 0.0))))),
                                             ('body_index_assign_nd',
                                              'inv',
                                              [('index_item', ('num', 0)),
                                               ('slice_item', None, None)],
                                              ('var', 'z')),
                                             ('body_index_assign_nd',
                                              'inv',
                                              [('index_item', ('num', 2)),
                                               ('slice_item', None, None)],
                                              ('var', 'c')),
                                             ('body_for_range',
                                              'a',
                                              ('num', 0),
                                              ('var', 'k'),
                                              [('loop_index_assign_nd',
                                                'inv',
                                                [('index_item', ('num', 1)),
                                                 ('index_item', ('var', 'a'))],
                                                ('call',
                                                 'degree',
                                                 [('var', 'g'), ('var', 'a')])),
                                               ('loop_index_assign_nd',
                                                'inv',
                                                [('index_item', ('num', 3)),
                                                 ('index_item', ('var', 'a'))],
                                                ('call',
                                                 'hydrogens',
                                                 [('var', 'g'), ('var', 'a')])),
                                               ('loop_index_assign_nd',
                                                'inv',
                                                [('index_item', ('num', 4)),
                                                 ('index_item', ('var', 'a'))],
                                                ('call',
                                                 'aromatic',
                                                 [('var', 'g'), ('var', 'a')]))])]},
               'initial_ids': {'params': [('g', ('struct_type', 'Molecule'))],
                               'return_type': ('tensor', [('n', 'invariant')]),
                               'body': ('var', 'new_ids'),
                               'has_loop': False,
                               'statements': [('body_decl',
                                               'inv',
                                               ('tensor',
                                                [(5, 'invariant'), ('n', 'invariant')]),
                                               ('call', 'invariants', [('var', 'g')])),
                                              ('body_decl',
                                               'k',
                                               'ℝ',
                                               ('call',
                                                'get_2d_array_num_rows',
                                                [('field_access',
                                                  ('var', 'g'),
                                                  'adjacency')])),
                                              ('body_decl',
                                               'new_ids',
                                               ('tensor', [('k', 'invariant')]),
                                               ('for_expr',
                                                'a',
                                                ('var', 'k'),
                                                ('mul', ('var', 'a'), ('num', 0.0)))),
                                              ('body_for_range',
                                               'a',
                                               ('num', 0),
                                               ('var', 'k'),
                                               [('loop_index_assign_nd',
                                                 'new_ids',
                                                 [('index_item', ('var', 'a'))],
                                                 ('call',
                                                  'hash_list',
                                                  [('indexN',
                                                    'inv',
                                                    [('slice_item', None, None),
                                                     ('index_item',
                                                      ('var', 'a'))])]))])]},
               'update_ids': {'params': [('g', ('struct_type', 'Molecule')),
                                         ('ids', ('tensor', [('n', 'invariant')])),
                                         ('r', 'ℝ')],
                              'return_type': ('tensor', [('n', 'invariant')]),
                              'body': ('var', 'new_ids'),
                              'has_loop': False,
                              'statements': [('body_decl',
                                              'm',
                                              ('tensor',
                                               [('n', 'invariant'),
                                                ('n', 'invariant')]),
                                              ('field_access',
                                               ('var', 'g'),
                                               'adjacency')),
                                             ('body_decl',
                                              'k',
                                              'ℝ',
                                              ('call',
                                               'get_2d_array_num_rows',
                                               [('var', 'm')])),
                                             ('body_decl',
                                              'new_ids',
                                              ('tensor', [('k', 'invariant')]),
                                              ('for_expr',
                                               'a',
                                               ('var', 'k'),
                                               ('mul', ('var', 'a'), ('num', 0.0)))),
                                             ('body_decl',
                                              'keys',
                                              ('tensor', [('k', 'invariant')]),
                                              ('for_expr',
                                               'a',
                                               ('var', 'k'),
                                               ('mul', ('var', 'a'), ('num', 0.0)))),
                                             ('body_for_range',
                                              'u',
                                              ('num', 0),
                                              ('var', 'k'),
                                              [('loop_for_range',
                                                'v',
                                                ('num', 0),
                                                ('var', 'k'),
                                                [('loop_index_assign_nd',
                                                  'keys',
                                                  [('index_item', ('var', 'v'))],
                                                  ('num', 0.0)),
                                                 ('loop_if',
                                                  ('cond_gt',
                                                   ('indexN',
                                                    'm',
                                                    [('index_item', ('var', 'u')),
                                                     ('index_item', ('var', 'v'))]),
                                                   ('num', 0.0)),
                                                  [('loop_index_assign_nd',
                                                    'keys',
                                                    [('index_item', ('var', 'v'))],
                                                    ('add',
                                                     ('mul',
                                                      ('mul',
                                                       ('num', 2.0),
                                                       ('indexN',
                                                        'm',
                                                        [('index_item', ('var', 'u')),
                                                         ('index_item',
                                                          ('var', 'v'))])),
                                                      ('var', 'M')),
                                                     ('index',
                                                      'ids',
                                                      ('var', 'v'))))])]),
                                               ('loop_assign',
                                                'keys',
                                                ('call',
                                                 'bubble_sort',
                                                 [('var', 'keys')])),
                                               ('loop_tuple_unpack',
                                                [('h', 'ℝ')],
                                                ('num', 17.0)),
                                               ('loop_assign',
                                                'h',
                                                ('call',
                                                 'hash_step',
                                                 [('var', 'h'), ('var', 'r')])),
                                               ('loop_assign',
                                                'h',
                                                ('call',
                                                 'hash_step',
                                                 [('var', 'h'),
                                                  ('index', 'ids', ('var', 'u'))])),
                                               ('loop_for_range',
                                                'i',
                                                ('num', 0),
                                                ('var', 'k'),
                                                [('loop_if',
                                                  ('cond_gt',
                                                   ('index', 'keys', ('imaginary',)),
                                                   ('num', 0.0)),
                                                  [('loop_assign',
                                                    'h',
                                                    ('call',
                                                     'hash_step',
                                                     [('var', 'h'),
                                                      ('index',
                                                       'keys',
                                                       ('imaginary',))]))])]),
                                               ('loop_index_assign_nd',
                                                'new_ids',
                                                [('index_item', ('var', 'u'))],
                                                ('var', 'h'))])]},
               'fingerprint': {'params': [('g', ('struct_type', 'Molecule')),
                                          ('radius', 'ℝ')],
                               'return_type': ('tensor', [('N_BITS', 'invariant')]),
                               'body': ('var', 'fp'),
                               'has_loop': False,
                               'statements': [('body_decl',
                                               'z',
                                               ('tensor', [('n', 'invariant')]),
                                               ('field_access',
                                                ('var', 'g'),
                                                'atomic_num')),
                                              ('body_decl',
                                               'k',
                                               'ℝ',
                                               ('call',
                                                'get_2d_array_num_rows',
                                                [('field_access',
                                                  ('var', 'g'),
                                                  'adjacency')])),
                                              ('body_decl',
                                               'fp',
                                               ('tensor', [('N_BITS', 'invariant')]),
                                               ('for_expr',
                                                'b',
                                                ('var', 'N_BITS'),
                                                ('mul', ('var', 'b'), ('num', 0.0)))),
                                              ('body_decl',
                                               'ids',
                                               ('tensor', [('n', 'invariant')]),
                                               ('call', 'initial_ids', [('var', 'g')])),
                                              ('body_for_range',
                                               'a',
                                               ('num', 0),
                                               ('var', 'k'),
                                               [('loop_if',
                                                 ('cond_gt',
                                                  ('index', 'z', ('var', 'a')),
                                                  ('num', 1.0)),
                                                 [('loop_index_assign_nd',
                                                   'fp',
                                                   [('index_item',
                                                     ('call',
                                                      'modulo',
                                                      [('index', 'ids', ('var', 'a')),
                                                       ('var', 'N_BITS')]))],
                                                   ('num', 1.0))])]),
                                              ('body_for_range',
                                               'r',
                                               ('num', 0),
                                               ('var', 'radius'),
                                               [('loop_assign',
                                                 'ids',
                                                 ('call',
                                                  'update_ids',
                                                  [('var', 'g'),
                                                   ('var', 'ids'),
                                                   ('add',
                                                    ('var', 'r'),
                                                    ('num', 1.0))])),
                                                ('loop_for_range',
                                                 'a',
                                                 ('num', 0),
                                                 ('var', 'k'),
                                                 [('loop_if',
                                                   ('cond_gt',
                                                    ('index', 'z', ('var', 'a')),
                                                    ('num', 1.0)),
                                                   [('loop_index_assign_nd',
                                                     'fp',
                                                     [('index_item',
                                                       ('call',
                                                        'modulo',
                                                        [('index', 'ids', ('var', 'a')),
                                                         ('var', 'N_BITS')]))],
                                                     ('num', 1.0))])])])]},
               'ecfp': {'params': [('g', ('struct_type', 'Molecule')),
                                   ('diameter', 'ℝ')],
                        'return_type': ('tensor', [('N_BITS', 'invariant')]),
                        'body': ('call',
                                 'fingerprint',
                                 [('var', 'g'),
                                  ('div', ('var', 'diameter'), ('num', 2.0))]),
                        'has_loop': False,
                        'statements': []},
               'get_sum_of_1d_array': {'params': [('x',
                                                   ('tensor', [('m', 'invariant')]))],
                                       'return_type': 'ℝ',
                                       'body': ('var', 'total'),
                                       'has_loop': False,
                                       'statements': [('body_decl',
                                                       'total',
                                                       'ℝ',
                                                       ('num', 0)),
                                                      ('body_for',
                                                       'i',
                                                       [('loop_pluseq',
                                                         'total',
                                                         ('index',
                                                          'x',
                                                          ('imaginary',)))],
                                                       ['x'])]},
               'tanimoto': {'params': [('a', ('tensor', [('n', 'invariant')])),
                                       ('b', ('tensor', [('n', 'invariant')]))],
                            'return_type': 'ℝ',
                            'body': ('div',
                                     ('var', 'both'),
                                     ('sub',
                                      ('add',
                                       ('call', 'get_sum_of_1d_array', [('var', 'a')]),
                                       ('call', 'get_sum_of_1d_array', [('var', 'b')])),
                                      ('var', 'both'))),
                            'has_loop': False,
                            'statements': [('body_decl',
                                            'both',
                                            'ℝ',
                                            ('call',
                                             'get_sum_of_1d_array',
                                             [('mul', ('var', 'a'), ('var', 'b'))]))]}},
 'classes': {'Molecule': {'class_params': [],
                          'fields': [('adjacency',
                                      ('tensor',
                                       [('n', 'invariant'), ('n', 'invariant')])),
                                     ('atomic_num', ('tensor', [('n', 'invariant')])),
                                     ('formal_charge',
                                      ('tensor', [('n', 'invariant')]))],
                          'methods': [{'name': 'num_atoms',
                                       'params': [],
                                       'return_type': 'ℝ',
                                       'statements': [],
                                       'body': ('mul',
                                                ('call',
                                                 'get_2d_array_num_rows',
                                                 [('field_access',
                                                   ('var', 'this'),
                                                   'adjacency')]),
                                                ('num', 1.0))},
                                      {'name': 'has_edge',
                                       'params': [('u', 'ℝ'), ('v', 'ℝ')],
                                       'return_type': 'ℝ',
                                       'statements': [('body_decl',
                                                       'm',
                                                       ('tensor',
                                                        [('n', 'invariant'),
                                                         ('n', 'invariant')]),
                                                       ('field_access',
                                                        ('var', 'this'),
                                                        'adjacency')),
                                                      ('body_decl',
                                                       'r',
                                                       ('tensor', [('n', 'invariant')]),
                                                       ('index', 'm', ('var', 'u')))],
                                       'body': ('index', 'r', ('var', 'v'))},
                                      {'name': 'neighbors',
                                       'params': [('u', 'ℝ')],
                                       'return_type': ('tensor', [('n', 'invariant')]),
                                       'statements': [('body_decl',
                                                       'm',
                                                       ('tensor',
                                                        [('n', 'invariant'),
                                                         ('n', 'invariant')]),
                                                       ('field_access',
                                                        ('var', 'this'),
                                                        'adjacency'))],
                                       'body': ('index', 'm', ('var', 'u'))},
                                      {'name': 'add_weighted_edge',
                                       'params': [('u', 'ℝ'), ('v', 'ℝ'), ('w', 'ℝ')],
                                       'return_type': None,
                                       'statements': [('body_decl',
                                                       'm',
                                                       ('tensor',
                                                        [('n', 'invariant'),
                                                         ('n', 'invariant')]),
                                                       ('field_access',
                                                        ('var', 'this'),
                                                        'adjacency')),
                                                      ('body_decl',
                                                       'k',
                                                       'ℝ',
                                                       ('call',
                                                        'get_2d_array_num_rows',
                                                        [('var', 'm')])),
                                                      ('body_decl',
                                                       'new_adj',
                                                       ('tensor',
                                                        [('n', 'invariant'),
                                                         ('n', 'invariant')]),
                                                       ('for_expr',
                                                        'a',
                                                        ('var', 'k'),
                                                        ('for_expr',
                                                         'b',
                                                         ('var', 'k'),
                                                         ('indexN',
                                                          'm',
                                                          [('index_item', ('var', 'a')),
                                                           ('index_item',
                                                            ('var', 'b'))])))),
                                                      ('body_index_assign_nd',
                                                       'new_adj',
                                                       [('index_item', ('var', 'u')),
                                                        ('index_item', ('var', 'v'))],
                                                       ('var', 'w')),
                                                      ('body_index_assign_nd',
                                                       'new_adj',
                                                       [('index_item', ('var', 'v')),
                                                        ('index_item', ('var', 'u'))],
                                                       ('var', 'w')),
                                                      ('body_field_assign',
                                                       ('var', 'this'),
                                                       'adjacency',
                                                       ('var', 'new_adj'))],
                                       'body': None},
                                      {'name': 'add_edge',
                                       'params': [('u', 'ℝ'), ('v', 'ℝ')],
                                       'return_type': None,
                                       'statements': [('body_expr',
                                                       ('method_call',
                                                        ('var', 'this'),
                                                        'add_weighted_edge',
                                                        [('var', 'u'),
                                                         ('var', 'v'),
                                                         ('num', 1.0)]))],
                                       'body': None}]}},
 'program': [('decl', 'BITS', 'ℕ', ('num', 32), 1),
             ('func_def', 'modulo'),
             ('decl', 'M', 'ℝ', ('num', 65521.0), 12),
             ('decl', 'N_BITS', 'ℕ', ('num', 2048), 14),
             ('func_def', 'hash_list'),
             ('func_def', 'hash_step'),
             ('func_def', 'bubble_sort'),
             ('func_def', 'get_2d_array_num_rows'),
             ('class_def', 'Molecule'),
             ('func_def', 'new_molecule'),
             ('func_def', 'degree'),
             ('func_def', 'hydrogens'),
             ('func_def', 'aromatic'),
             ('func_def', 'invariants'),
             ('func_def', 'initial_ids'),
             ('func_def', 'update_ids'),
             ('func_def', 'fingerprint'),
             ('func_def', 'ecfp'),
             ('func_def', 'get_sum_of_1d_array'),
             ('func_def', 'tanimoto'),
             ('decl',
              'CH4_atomic_num',
              ('tensor', [(5, 'invariant')]),
              ('array', [('num', 6), ('num', 1), ('num', 1), ('num', 1), ('num', 1)]),
              197),
             ('decl',
              'CH4_formal_charge',
              ('tensor', [(5, 'invariant')]),
              ('array', [('num', 0), ('num', 0), ('num', 0), ('num', 0), ('num', 0)]),
              198),
             ('decl',
              'CH4',
              ('struct_type', 'Molecule'),
              ('call',
               'new_molecule',
               [('var', 'CH4_atomic_num'), ('var', 'CH4_formal_charge')]),
              199),
             ('expr',
              ('method_call', ('var', 'CH4'), 'add_edge', [('num', 0.0), ('num', 1.0)]),
              0),
             ('expr',
              ('method_call', ('var', 'CH4'), 'add_edge', [('num', 0.0), ('num', 2.0)]),
              0),
             ('expr',
              ('method_call', ('var', 'CH4'), 'add_edge', [('num', 0.0), ('num', 3.0)]),
              0),
             ('expr',
              ('method_call', ('var', 'CH4'), 'add_edge', [('num', 0.0), ('num', 4.0)]),
              0),
             ('expr', ('call', 'invariants', [('var', 'CH4')]), 0),
             ('decl',
              'C6H6_atomic_num',
              ('tensor', [(12, 'invariant')]),
              ('array',
               [('num', 6),
                ('num', 6),
                ('num', 6),
                ('num', 6),
                ('num', 6),
                ('num', 6),
                ('num', 1),
                ('num', 1),
                ('num', 1),
                ('num', 1),
                ('num', 1),
                ('num', 1)]),
              212),
             ('decl',
              'C6H6_formal_charge',
              ('tensor', [(12, 'invariant')]),
              ('array',
               [('num', 0),
                ('num', 0),
                ('num', 0),
                ('num', 0),
                ('num', 0),
                ('num', 0),
                ('num', 0),
                ('num', 0),
                ('num', 0),
                ('num', 0),
                ('num', 0),
                ('num', 0)]),
              213),
             ('decl',
              'C6H6',
              ('struct_type', 'Molecule'),
              ('call',
               'new_molecule',
               [('var', 'C6H6_atomic_num'), ('var', 'C6H6_formal_charge')]),
              214),
             ('expr',
              ('method_call',
               ('var', 'C6H6'),
               'add_weighted_edge',
               [('num', 0.0), ('num', 1.0), ('num', 1.5)]),
              0),
             ('expr',
              ('method_call',
               ('var', 'C6H6'),
               'add_weighted_edge',
               [('num', 1.0), ('num', 2.0), ('num', 1.5)]),
              0),
             ('expr',
              ('method_call',
               ('var', 'C6H6'),
               'add_weighted_edge',
               [('num', 2.0), ('num', 3.0), ('num', 1.5)]),
              0),
             ('expr',
              ('method_call',
               ('var', 'C6H6'),
               'add_weighted_edge',
               [('num', 3.0), ('num', 4.0), ('num', 1.5)]),
              0),
             ('expr',
              ('method_call',
               ('var', 'C6H6'),
               'add_weighted_edge',
               [('num', 4.0), ('num', 5.0), ('num', 1.5)]),
              0),
             ('expr',
              ('method_call',
               ('var', 'C6H6'),
               'add_weighted_edge',
               [('num', 5.0), ('num', 0.0), ('num', 1.5)]),
              0),
             ('expr',
              ('method_call',
               ('var', 'C6H6'),
               'add_edge',
               [('num', 0.0), ('num', 6.0)]),
              0),
             ('expr',
              ('method_call',
               ('var', 'C6H6'),
               'add_edge',
               [('num', 1.0), ('num', 7.0)]),
              0),
             ('expr',
              ('method_call',
               ('var', 'C6H6'),
               'add_edge',
               [('num', 2.0), ('num', 8.0)]),
              0),
             ('expr',
              ('method_call',
               ('var', 'C6H6'),
               'add_edge',
               [('num', 3.0), ('num', 9.0)]),
              0),
             ('expr',
              ('method_call',
               ('var', 'C6H6'),
               'add_edge',
               [('num', 4.0), ('num', 10.0)]),
              0),
             ('expr',
              ('method_call',
               ('var', 'C6H6'),
               'add_edge',
               [('num', 5.0), ('num', 11.0)]),
              0),
             ('expr', ('call', 'invariants', [('var', 'C6H6')]), 0),
             ('decl',
              'C7H8_atomic_num',
              ('tensor', [(15, 'invariant')]),
              ('array',
               [('num', 6),
                ('num', 6),
                ('num', 6),
                ('num', 6),
                ('num', 6),
                ('num', 6),
                ('num', 6),
                ('num', 1),
                ('num', 1),
                ('num', 1),
                ('num', 1),
                ('num', 1),
                ('num', 1),
                ('num', 1),
                ('num', 1)]),
              234),
             ('decl',
              'C7H8_formal_charge',
              ('tensor', [(15, 'invariant')]),
              ('array',
               [('num', 0),
                ('num', 0),
                ('num', 0),
                ('num', 0),
                ('num', 0),
                ('num', 0),
                ('num', 0),
                ('num', 0),
                ('num', 0),
                ('num', 0),
                ('num', 0),
                ('num', 0),
                ('num', 0),
                ('num', 0),
                ('num', 0)]),
              235),
             ('decl',
              'C7H8',
              ('struct_type', 'Molecule'),
              ('call',
               'new_molecule',
               [('var', 'C7H8_atomic_num'), ('var', 'C7H8_formal_charge')]),
              236),
             ('expr',
              ('method_call',
               ('var', 'C7H8'),
               'add_weighted_edge',
               [('num', 0.0), ('num', 1.0), ('num', 1.5)]),
              0),
             ('expr',
              ('method_call',
               ('var', 'C7H8'),
               'add_weighted_edge',
               [('num', 1.0), ('num', 2.0), ('num', 1.5)]),
              0),
             ('expr',
              ('method_call',
               ('var', 'C7H8'),
               'add_weighted_edge',
               [('num', 2.0), ('num', 3.0), ('num', 1.5)]),
              0),
             ('expr',
              ('method_call',
               ('var', 'C7H8'),
               'add_weighted_edge',
               [('num', 3.0), ('num', 4.0), ('num', 1.5)]),
              0),
             ('expr',
              ('method_call',
               ('var', 'C7H8'),
               'add_weighted_edge',
               [('num', 4.0), ('num', 5.0), ('num', 1.5)]),
              0),
             ('expr',
              ('method_call',
               ('var', 'C7H8'),
               'add_weighted_edge',
               [('num', 5.0), ('num', 0.0), ('num', 1.5)]),
              0),
             ('expr',
              ('method_call',
               ('var', 'C7H8'),
               'add_edge',
               [('num', 0.0), ('num', 6.0)]),
              0),
             ('expr',
              ('method_call',
               ('var', 'C7H8'),
               'add_edge',
               [('num', 1.0), ('num', 7.0)]),
              0),
             ('expr',
              ('method_call',
               ('var', 'C7H8'),
               'add_edge',
               [('num', 2.0), ('num', 8.0)]),
              0),
             ('expr',
              ('method_call',
               ('var', 'C7H8'),
               'add_edge',
               [('num', 3.0), ('num', 9.0)]),
              0),
             ('expr',
              ('method_call',
               ('var', 'C7H8'),
               'add_edge',
               [('num', 4.0), ('num', 10.0)]),
              0),
             ('expr',
              ('method_call',
               ('var', 'C7H8'),
               'add_edge',
               [('num', 5.0), ('num', 11.0)]),
              0),
             ('expr',
              ('method_call',
               ('var', 'C7H8'),
               'add_edge',
               [('num', 6.0), ('num', 12.0)]),
              0),
             ('expr',
              ('method_call',
               ('var', 'C7H8'),
               'add_edge',
               [('num', 6.0), ('num', 13.0)]),
              0),
             ('expr',
              ('method_call',
               ('var', 'C7H8'),
               'add_edge',
               [('num', 6.0), ('num', 14.0)]),
              0),
             ('expr', ('call', 'invariants', [('var', 'C7H8')]), 0),
             ('decl',
              'CH4_ids0',
              ('tensor', [(5, 'invariant')]),
              ('call', 'initial_ids', [('var', 'CH4')]),
              262),
             ('decl',
              'CH4_ids1',
              ('tensor', [(5, 'invariant')]),
              ('call',
               'update_ids',
               [('var', 'CH4'), ('var', 'CH4_ids0'), ('num', 1.0)]),
              263),
             ('decl',
              'CH4_ids2',
              ('tensor', [(5, 'invariant')]),
              ('call',
               'update_ids',
               [('var', 'CH4'), ('var', 'CH4_ids1'), ('num', 2.0)]),
              264),
             ('expr', ('var', 'CH4_ids1'), 0),
             ('expr', ('var', 'CH4_ids2'), 0),
             ('decl',
              'C6H6_ids0',
              ('tensor', [(12, 'invariant')]),
              ('call', 'initial_ids', [('var', 'C6H6')]),
              268),
             ('decl',
              'C6H6_ids1',
              ('tensor', [(12, 'invariant')]),
              ('call',
               'update_ids',
               [('var', 'C6H6'), ('var', 'C6H6_ids0'), ('num', 1.0)]),
              269),
             ('decl',
              'C6H6_ids2',
              ('tensor', [(12, 'invariant')]),
              ('call',
               'update_ids',
               [('var', 'C6H6'), ('var', 'C6H6_ids1'), ('num', 2.0)]),
              270),
             ('expr', ('var', 'C6H6_ids1'), 0),
             ('expr', ('var', 'C6H6_ids2'), 0),
             ('decl',
              'CH4_ecfp4',
              ('tensor', [('N_BITS', 'invariant')]),
              ('call', 'ecfp', [('var', 'CH4'), ('num', 4)]),
              276),
             ('decl',
              'C6H6_ecfp4',
              ('tensor', [('N_BITS', 'invariant')]),
              ('call', 'ecfp', [('var', 'C6H6'), ('num', 4)]),
              277),
             ('decl',
              'C7H8_ecfp4',
              ('tensor', [('N_BITS', 'invariant')]),
              ('call', 'ecfp', [('var', 'C7H8'), ('num', 4)]),
              278),
             ('expr', ('call', 'get_sum_of_1d_array', [('var', 'CH4_ecfp4')]), 0),
             ('expr', ('call', 'get_sum_of_1d_array', [('var', 'C6H6_ecfp4')]), 0),
             ('expr', ('call', 'get_sum_of_1d_array', [('var', 'C7H8_ecfp4')]), 0),
             ('expr',
              ('call', 'tanimoto', [('var', 'C6H6_ecfp4'), ('var', 'C6H6_ecfp4')]),
              0),
             ('expr',
              ('call', 'tanimoto', [('var', 'C6H6_ecfp4'), ('var', 'C7H8_ecfp4')]),
              0),
             ('expr',
              ('call', 'tanimoto', [('var', 'CH4_ecfp4'), ('var', 'C6H6_ecfp4')]),
              0),
             ('expr',
              ('call', 'tanimoto', [('var', 'CH4_ecfp4'), ('var', 'C7H8_ecfp4')]),
              0)]}
