EXPECTED = {'functions': {'tanh': {'params': [('a',
                                    ('tensor',
                                     [('p', 'invariant'),
                                      ('q', 'invariant')]))],
                        'return_type': ('tensor',
                                        [('p', 'invariant'),
                                         ('q', 'invariant')]),
                        'body': ('div', ('var', 'num'), ('var', 'denom')),
                        'has_loop': False,
                        'statements': [('body_decl',
                                        'num',
                                        ('tensor',
                                         [('p', 'invariant'),
                                          ('q', 'invariant')]),
                                        ('sub',
                                         ('call', 'exp', [('var', 'a')]),
                                         ('call',
                                          'exp',
                                          [('neg', ('var', 'a'))]))),
                                       ('body_decl',
                                        'denom',
                                        ('tensor',
                                         [('p', 'invariant'),
                                          ('q', 'invariant')]),
                                        ('add',
                                         ('call', 'exp', [('var', 'a')]),
                                         ('call',
                                          'exp',
                                          [('neg', ('var', 'a'))])))]},
               'sum_2d': {'params': [('a',
                                      ('tensor',
                                       [('p', 'invariant'),
                                        ('q', 'invariant')])),
                                     ('p', 'ℕ'),
                                     ('q', 'ℕ')],
                          'return_type': 'ℝ',
                          'body': ('var', 's'),
                          'has_loop': False,
                          'statements': [('body_decl', 's', 'ℝ', ('num', 0.0)),
                                         ('body_for_range',
                                          'i',
                                          ('num', 0),
                                          ('var', 'p'),
                                          [('loop_for_range',
                                            'j',
                                            ('num', 0),
                                            ('var', 'q'),
                                            [('loop_pluseq',
                                              's',
                                              ('indexN',
                                               'a',
                                               [('index_item', ('imaginary',)),
                                                ('index_item',
                                                 ('var', 'j'))]))])])]},
               'rand_array': {'params': [('n', 'ℝ'), ('m', 'ℝ'), ('μ', 'ℝ')],
                              'return_type': ('tensor',
                                              [('n', 'invariant'),
                                               ('m', 'invariant')]),
                              'body': ('for_expr',
                                       'i',
                                       ('var', 'n'),
                                       ('typed_sample_expr',
                                        'ε',
                                        ('tensor', [('m', 'invariant')]),
                                        ('call',
                                         'Normal',
                                         [('num', 0.0),
                                          ('var', 'μ'),
                                          ('var', 'm')]))),
                              'has_loop': False,
                              'statements': []},
               'zeros2d': {'params': [('n', 'ℝ'), ('m', 'ℝ')],
                           'return_type': ('tensor',
                                           [('n', 'invariant'),
                                            ('m', 'invariant')]),
                           'body': ('for_expr',
                                    'i',
                                    ('var', 'n'),
                                    ('for_expr',
                                     'j',
                                     ('var', 'm'),
                                     ('mul', ('var', 'j'), ('num', 0.0)))),
                           'has_loop': False,
                           'statements': []},
               'zeros1d': {'params': [('k', 'ℝ')],
                           'return_type': ('tensor', [('k', 'invariant')]),
                           'body': ('for_expr',
                                    'i',
                                    ('var', 'k'),
                                    ('mul', ('imaginary',), ('num', 0.0))),
                           'has_loop': False,
                           'statements': []},
               'eye': {'params': [('n', 'ℝ')],
                       'return_type': ('tensor',
                                       [('n', 'invariant'),
                                        ('n', 'invariant')]),
                       'body': ('var', 'I'),
                       'has_loop': False,
                       'statements': [('body_decl',
                                       'I',
                                       ('tensor',
                                        [('n', 'invariant'),
                                         ('n', 'invariant')]),
                                       ('for_expr',
                                        'i',
                                        ('var', 'n'),
                                        ('for_expr',
                                         'j',
                                         ('var', 'n'),
                                         ('mul', ('var', 'j'), ('num', 0.0))))),
                                      ('body_for_range',
                                       'i',
                                       ('num', 0),
                                       ('var', 'n'),
                                       [('loop_index_assign_nd',
                                         'I',
                                         [('index_item', ('imaginary',)),
                                          ('index_item', ('imaginary',))],
                                         ('num', 1.0))])]},
               'df_dh': {'params': [('W',
                                     ('tensor',
                                      [('n', 'invariant'),
                                       ('n', 'invariant')])),
                                    ('tanh_prime',
                                     ('tensor',
                                      [(1, 'invariant'), ('n', 'invariant')]))],
                         'return_type': ('tensor',
                                         [('n', 'invariant'),
                                          ('n', 'invariant')]),
                         'body': ('for_expr',
                                  'r',
                                  ('var', 'n'),
                                  ('for_expr',
                                   'c',
                                   ('var', 'n'),
                                   ('mul',
                                    ('indexN',
                                     'W',
                                     [('index_item', ('var', 'r')),
                                      ('index_item', ('var', 'c'))]),
                                    ('indexN',
                                     'tanh_prime',
                                     [('index_item', ('num', 0)),
                                      ('index_item', ('var', 'c'))])))),
                         'has_loop': False,
                         'statements': []},
               'gaussian_solve': {'params': [('A',
                                              ('tensor',
                                               [('m', 'invariant'),
                                                ('n', 'invariant')])),
                                             ('b',
                                              ('tensor',
                                               [('n', 'invariant')]))],
                                  'return_type': ('tensor',
                                                  [('n', 'invariant')]),
                                  'body': ('var', 'x'),
                                  'has_loop': False,
                                  'statements': [('body_decl',
                                                  'a_row',
                                                  'ℝ',
                                                  ('call',
                                                   'get_2d_array_num_rows',
                                                   [('var', 'A')])),
                                                 ('body_decl',
                                                  'a_col',
                                                  'ℝ',
                                                  ('call',
                                                   'get_2d_array_num_cols',
                                                   [('var', 'A')])),
                                                 ('body_decl',
                                                  'new_col',
                                                  'ℝ',
                                                  ('add',
                                                   ('var', 'a_col'),
                                                   ('num', 1))),
                                                 ('body_decl',
                                                  'aug',
                                                  ('tensor',
                                                   [('a_row', 'invariant'),
                                                    ('new_col', 'invariant')]),
                                                  ('call',
                                                   'zeros',
                                                   [('var', 'a_row'),
                                                    ('var', 'new_col')])),
                                                 ('body_for_range',
                                                  'i',
                                                  ('num', 0),
                                                  ('var', 'a_row'),
                                                  [('loop_index_assign_nd',
                                                    'aug',
                                                    [('index_item',
                                                      ('imaginary',)),
                                                     ('slice_item',
                                                      None,
                                                      ('var', 'a_col'))],
                                                    ('indexN',
                                                     'A',
                                                     [('index_item',
                                                       ('imaginary',)),
                                                      ('slice_item',
                                                       None,
                                                       None)])),
                                                   ('loop_index_assign_nd',
                                                    'aug',
                                                    [('index_item',
                                                      ('imaginary',)),
                                                     ('index_item',
                                                      ('var', 'a_col'))],
                                                    ('index',
                                                     'b',
                                                     ('imaginary',)))]),
                                                 ('body_for_range',
                                                  'i',
                                                  ('num', 0),
                                                  ('var', 'a_row'),
                                                  [('loop_assign',
                                                    'max_row',
                                                    ('imaginary',)),
                                                   ('loop_for_range',
                                                    'k',
                                                    ('add',
                                                     ('imaginary',),
                                                     ('num', 1)),
                                                    ('var', 'a_row'),
                                                    [('loop_if',
                                                      ('cond_gt',
                                                       ('call',
                                                        'abs',
                                                        [('indexN',
                                                          'aug',
                                                          [('index_item',
                                                            ('var', 'k')),
                                                           ('index_item',
                                                            ('imaginary',))])]),
                                                       ('call',
                                                        'abs',
                                                        [('indexN',
                                                          'aug',
                                                          [('index_item',
                                                            ('var', 'max_row')),
                                                           ('index_item',
                                                            ('imaginary',))])])),
                                                      [('loop_assign',
                                                        'max_row',
                                                        ('var', 'k'))])]),
                                                   ('loop_if',
                                                    ('cond_neq',
                                                     ('var', 'max_row'),
                                                     ('imaginary',)),
                                                    [('loop_assign',
                                                      'lo',
                                                      ('call',
                                                       'min',
                                                       [('imaginary',),
                                                        ('var', 'max_row')])),
                                                     ('loop_assign',
                                                      'hi',
                                                      ('call',
                                                       'max',
                                                       [('imaginary',),
                                                        ('var', 'max_row')])),
                                                     ('loop_assign',
                                                      'rows_above',
                                                      ('indexN',
                                                       'aug',
                                                       [('slice_item',
                                                         None,
                                                         ('var', 'lo')),
                                                        ('slice_item',
                                                         None,
                                                         None)])),
                                                     ('loop_assign',
                                                      'pivot_row',
                                                      ('indexN',
                                                       'aug',
                                                       [('slice_item',
                                                         ('var', 'hi'),
                                                         ('add',
                                                          ('var', 'hi'),
                                                          ('num', 1))),
                                                        ('slice_item',
                                                         None,
                                                         None)])),
                                                     ('loop_assign',
                                                      'rows_between',
                                                      ('indexN',
                                                       'aug',
                                                       [('slice_item',
                                                         ('add',
                                                          ('var', 'lo'),
                                                          ('num', 1)),
                                                         ('var', 'hi')),
                                                        ('slice_item',
                                                         None,
                                                         None)])),
                                                     ('loop_assign',
                                                      'current_row',
                                                      ('indexN',
                                                       'aug',
                                                       [('slice_item',
                                                         ('var', 'lo'),
                                                         ('add',
                                                          ('var', 'lo'),
                                                          ('num', 1))),
                                                        ('slice_item',
                                                         None,
                                                         None)])),
                                                     ('loop_assign',
                                                      'rows_below',
                                                      ('indexN',
                                                       'aug',
                                                       [('slice_item',
                                                         ('add',
                                                          ('var', 'hi'),
                                                          ('num', 1)),
                                                         None),
                                                        ('slice_item',
                                                         None,
                                                         None)])),
                                                     ('loop_assign',
                                                      'aug',
                                                      ('call',
                                                       'concat',
                                                       [('var', 'rows_above'),
                                                        ('var', 'pivot_row'),
                                                        ('var', 'rows_between'),
                                                        ('var', 'current_row'),
                                                        ('var',
                                                         'rows_below')]))]),
                                                   ('loop_assign',
                                                    'pivot_row',
                                                    ('indexN',
                                                     'aug',
                                                     [('slice_item',
                                                       ('imaginary',),
                                                       ('add',
                                                        ('imaginary',),
                                                        ('num', 1))),
                                                      ('slice_item',
                                                       None,
                                                       None)])),
                                                   ('loop_assign',
                                                    'pivot_value',
                                                    ('indexN',
                                                     'aug',
                                                     [('index_item',
                                                       ('imaginary',)),
                                                      ('index_item',
                                                       ('imaginary',))])),
                                                   ('loop_assign',
                                                    'rows_below',
                                                    ('indexN',
                                                     'aug',
                                                     [('slice_item',
                                                       ('add',
                                                        ('imaginary',),
                                                        ('num', 1)),
                                                       None),
                                                      ('slice_item',
                                                       None,
                                                       None)])),
                                                   ('loop_assign',
                                                    'elimination_factors',
                                                    ('div',
                                                     ('indexN',
                                                      'rows_below',
                                                      [('slice_item',
                                                        None,
                                                        None),
                                                       ('slice_item',
                                                        ('imaginary',),
                                                        ('add',
                                                         ('imaginary',),
                                                         ('num', 1)))]),
                                                     ('var', 'pivot_value'))),
                                                   ('loop_assign',
                                                    'eliminated_rows',
                                                    ('sub',
                                                     ('var', 'rows_below'),
                                                     ('mul',
                                                      ('var',
                                                       'elimination_factors'),
                                                      ('var', 'pivot_row')))),
                                                   ('loop_assign',
                                                    'aug',
                                                    ('call',
                                                     'concat',
                                                     [('indexN',
                                                       'aug',
                                                       [('slice_item',
                                                         None,
                                                         ('add',
                                                          ('imaginary',),
                                                          ('num', 1))),
                                                        ('slice_item',
                                                         None,
                                                         None)]),
                                                      ('var',
                                                       'eliminated_rows')]))]),
                                                 ('body_assign',
                                                  'x',
                                                  ('call',
                                                   'zeros',
                                                   [('num', 0)])),
                                                 ('body_for_range',
                                                  'i',
                                                  ('num', 0),
                                                  ('var', 'a_row'),
                                                  [('loop_assign',
                                                    'idx',
                                                    ('sub',
                                                     ('sub',
                                                      ('var', 'a_col'),
                                                      ('num', 1)),
                                                     ('imaginary',))),
                                                   ('loop_assign',
                                                    'total',
                                                    ('indexN',
                                                     'aug',
                                                     [('index_item',
                                                       ('var', 'idx')),
                                                      ('index_item',
                                                       ('var', 'a_col'))])),
                                                   ('loop_for_range',
                                                    'j',
                                                    ('add',
                                                     ('var', 'idx'),
                                                     ('num', 1)),
                                                    ('var', 'a_row'),
                                                    [('loop_assign',
                                                      'total',
                                                      ('sub',
                                                       ('var', 'total'),
                                                       ('mul',
                                                        ('indexN',
                                                         'aug',
                                                         [('index_item',
                                                           ('var', 'idx')),
                                                          ('index_item',
                                                           ('var', 'j'))]),
                                                        ('index',
                                                         'x',
                                                         ('sub',
                                                          ('sub',
                                                           ('var', 'j'),
                                                           ('var', 'idx')),
                                                          ('num', 1))))))]),
                                                   ('loop_assign',
                                                    'val',
                                                    ('div',
                                                     ('var', 'total'),
                                                     ('indexN',
                                                      'aug',
                                                      [('index_item',
                                                        ('var', 'idx')),
                                                       ('index_item',
                                                        ('var', 'idx'))]))),
                                                   ('loop_assign',
                                                    'val',
                                                    ('call',
                                                     'reshape',
                                                     [('var', 'val'),
                                                      ('num', 1)])),
                                                   ('loop_assign',
                                                    'x',
                                                    ('call',
                                                     'concat',
                                                     [('var', 'val'),
                                                      ('var', 'x')]))])]},
               'get_2d_array_num_rows': {'params': [('x',
                                                     ('tensor',
                                                      [('m', 'invariant'),
                                                       ('n', 'invariant')]))],
                                         'return_type': 'ℝ',
                                         'body': ('var', 'total'),
                                         'has_loop': False,
                                         'statements': [('body_decl',
                                                         'total',
                                                         'ℝ',
                                                         ('num', 0)),
                                                        ('body_decl',
                                                         'temp',
                                                         'ℝ',
                                                         ('num', 0)),
                                                        ('body_for',
                                                         'i',
                                                         [('loop_assign',
                                                           'temp',
                                                           ('index',
                                                            'x',
                                                            ('imaginary',))),
                                                          ('loop_pluseq',
                                                           'total',
                                                           ('num', 1))],
                                                         ['x'])]},
               'get_2d_array_num_cols': {'params': [('x',
                                                     ('tensor',
                                                      [('m', 'invariant'),
                                                       ('n', 'invariant')]))],
                                         'return_type': 'ℝ',
                                         'body': ('call',
                                                  'get_1d_array_length',
                                                  [('index', 'x', ('num', 0))]),
                                         'has_loop': False,
                                         'statements': []},
               'get_1d_array_length': {'params': [('x',
                                                   ('tensor',
                                                    [('m', 'invariant')]))],
                                       'return_type': 'ℝ',
                                       'body': ('var', 'total'),
                                       'has_loop': False,
                                       'statements': [('body_decl',
                                                       'total',
                                                       'ℝ',
                                                       ('num', 0)),
                                                      ('body_decl',
                                                       'temp',
                                                       'ℝ',
                                                       ('num', 0)),
                                                      ('body_for',
                                                       'i',
                                                       [('loop_assign',
                                                         'temp',
                                                         ('index',
                                                          'x',
                                                          ('imaginary',))),
                                                        ('loop_pluseq',
                                                         'total',
                                                         ('num', 1))],
                                                       ['x'])]},
               'zero_2d_array': {'params': [('rows', 'ℝ'), ('cols', 'ℝ')],
                                 'return_type': ('tensor',
                                                 [('m', 'invariant'),
                                                  ('n', 'invariant')]),
                                 'body': ('var', 'results'),
                                 'has_loop': False,
                                 'statements': [('body_decl',
                                                 'results',
                                                 ('tensor',
                                                  [('rows', 'invariant'),
                                                   ('cols', 'invariant')]),
                                                 ('for_expr',
                                                  'i',
                                                  ('var', 'rows'),
                                                  ('for_expr',
                                                   'j',
                                                   ('var', 'cols'),
                                                   ('mul',
                                                    ('var', 'j'),
                                                    ('num', 0)))))]},
               'zero_1d_array': {'params': [('len', 'ℝ')],
                                 'return_type': ('tensor',
                                                 [('m', 'invariant')]),
                                 'body': ('var', 'results'),
                                 'has_loop': False,
                                 'statements': [('body_decl',
                                                 'results',
                                                 ('tensor',
                                                  [('len', 'invariant')]),
                                                 ('for_expr',
                                                  'i',
                                                  ('var', 'len'),
                                                  ('mul',
                                                   ('imaginary',),
                                                   ('num', 0))))]},
               'max': {'params': [('x', 'ℝ'), ('y', 'ℝ')],
                       'return_type': 'ℝ',
                       'body': None,
                       'has_loop': False,
                       'statements': [('body_if_else_return',
                                       ('cond_gt', ('var', 'x'), ('var', 'y')),
                                       ('var', 'x'),
                                       ('var', 'y'))]}},
 'classes': {'DEQ': {'class_params': [('W',
                                       ('tensor',
                                        [('n', 'invariant'),
                                         ('n', 'invariant')])),
                                      ('U',
                                       ('tensor',
                                        [('d', 'invariant'),
                                         ('n', 'invariant')])),
                                      ('b',
                                       ('tensor',
                                        [(1, 'invariant'),
                                         ('n', 'invariant')])),
                                      ('Wo',
                                       ('tensor',
                                        [('n', 'invariant'),
                                         ('d', 'invariant')])),
                                      ('bo',
                                       ('tensor',
                                        [(1, 'invariant'),
                                         ('d', 'invariant')])),
                                      ('n', 'ℕ'),
                                      ('d', 'ℕ'),
                                      ('solver_steps', 'ℕ')],
                     'fields': [('h_star',
                                 ('tensor',
                                  [(1, 'invariant'), ('n', 'invariant')]))],
                     'methods': [{'name': 'f',
                                  'params': [('h',
                                              ('tensor',
                                               [(1, 'invariant'),
                                                ('n', 'invariant')])),
                                             ('x',
                                              ('tensor',
                                               [(1, 'invariant'),
                                                ('d', 'invariant')]))],
                                  'return_type': ('tensor',
                                                  [(1, 'invariant'),
                                                   ('n', 'invariant')]),
                                  'statements': [],
                                  'body': ('call',
                                           'tanh',
                                           [('add',
                                             ('add',
                                              ('matmul',
                                               ('var', 'h'),
                                               ('var', 'W')),
                                              ('matmul',
                                               ('var', 'x'),
                                               ('var', 'U'))),
                                             ('var', 'b'))])},
                                 {'name': 'equilibrium',
                                  'params': [('x',
                                              ('tensor',
                                               [(1, 'invariant'),
                                                ('d', 'invariant')]))],
                                  'return_type': ('tensor',
                                                  [(1, 'invariant'),
                                                   ('n', 'invariant')]),
                                  'statements': [('body_field_assign',
                                                  ('var', 'this'),
                                                  'h_star',
                                                  ('call',
                                                   'zeros2d',
                                                   [('num', 1),
                                                    ('field_access',
                                                     ('var', 'this'),
                                                     'n')])),
                                                 ('body_decl',
                                                  'f_h',
                                                  ('tensor',
                                                   [(1, 'invariant'),
                                                    ('n', 'invariant')]),
                                                  ('method_call',
                                                   ('var', 'this'),
                                                   'f',
                                                   [('field_access',
                                                     ('var', 'this'),
                                                     'h_star'),
                                                    ('var', 'x')])),
                                                 ('body_decl',
                                                  'tanh_prime',
                                                  ('tensor',
                                                   [(1, 'invariant'),
                                                    ('n', 'invariant')]),
                                                  ('sub',
                                                   ('num', 1.0),
                                                   ('mul',
                                                    ('var', 'f_h'),
                                                    ('var', 'f_h')))),
                                                 ('body_decl',
                                                  'J',
                                                  ('tensor',
                                                   [('n', 'invariant'),
                                                    ('n', 'invariant')]),
                                                  ('sub',
                                                   ('call',
                                                    'df_dh',
                                                    [('var', 'W'),
                                                     ('var', 'tanh_prime')]),
                                                   ('call',
                                                    'eye',
                                                    [('field_access',
                                                      ('var', 'this'),
                                                      'n')]))),
                                                 ('body_for_range',
                                                  'k',
                                                  ('num', 0),
                                                  ('field_access',
                                                   ('var', 'this'),
                                                   'solver_steps'),
                                                  [('loop_assign',
                                                    'g',
                                                    ('sub',
                                                     ('method_call',
                                                      ('var', 'this'),
                                                      'f',
                                                      [('field_access',
                                                        ('var', 'this'),
                                                        'h_star'),
                                                       ('var', 'x')]),
                                                     ('field_access',
                                                      ('var', 'this'),
                                                      'h_star'))),
                                                   ('loop_assign',
                                                    'delta',
                                                    ('call',
                                                     'gaussian_solve',
                                                     [('var', 'J'),
                                                      ('index',
                                                       'g',
                                                       ('num', 0))])),
                                                   ('body_field_assign',
                                                    ('var', 'this'),
                                                    'h_star',
                                                    ('sub',
                                                     ('field_access',
                                                      ('var', 'this'),
                                                      'h_star'),
                                                     ('array',
                                                      [('var', 'delta')])))])],
                                  'body': ('field_access',
                                           ('var', 'this'),
                                           'h_star')},
                                 {'name': 'λ',
                                  'params': [('x',
                                              ('tensor',
                                               [(1, 'invariant'),
                                                ('d', 'invariant')]))],
                                  'return_type': ('tensor',
                                                  [(1, 'invariant'),
                                                   ('d', 'invariant')]),
                                  'statements': [('body_decl',
                                                  'h_star',
                                                  ('tensor',
                                                   [(1, 'invariant'),
                                                    ('n', 'invariant')]),
                                                  ('method_call',
                                                   ('var', 'this'),
                                                   'equilibrium',
                                                   [('var', 'x')]))],
                                  'body': ('add',
                                           ('matmul',
                                            ('var', 'h_star'),
                                            ('var', 'Wo')),
                                           ('var', 'bo'))},
                                 {'name': 'loss',
                                  'params': [('target',
                                              ('tensor',
                                               [(1, 'invariant'),
                                                ('d', 'invariant')])),
                                             ('x_hat',
                                              ('tensor',
                                               [(1, 'invariant'),
                                                ('d', 'invariant')]))],
                                  'return_type': 'ℝ',
                                  'statements': [('body_decl',
                                                  'err',
                                                  ('tensor',
                                                   [(1, 'invariant'),
                                                    ('d', 'invariant')]),
                                                  ('sub',
                                                   ('var', 'target'),
                                                   ('var', 'x_hat')))],
                                  'body': ('call',
                                           'sum_2d',
                                           [('mul',
                                             ('var', 'err'),
                                             ('var', 'err')),
                                            ('num', 1),
                                            ('var', 'd')])},
                                 {'name': 'train',
                                  'params': [('X',
                                              ('tensor',
                                               [(10, 'invariant'),
                                                (784, 'invariant')])),
                                             ('epochs', 'ℕ'),
                                             ('lr', 'ℝ'),
                                             ('images', 'ℝ')],
                                  'return_type': ('tensor',
                                                  [('epochs', 'invariant')]),
                                  'statements': [('body_decl',
                                                  'losses',
                                                  ('tensor',
                                                   [('epochs', 'invariant')]),
                                                  ('for_expr',
                                                   'i',
                                                   ('var', 'epochs'),
                                                   ('mul',
                                                    ('imaginary',),
                                                    ('num', 0)))),
                                                 ('body_for_range',
                                                  'epoch',
                                                  ('num', 0),
                                                  ('var', 'epochs'),
                                                  [('loop_assign',
                                                    'total',
                                                    ('num', 0)),
                                                   ('loop_for_range',
                                                    'i',
                                                    ('num', 0),
                                                    ('var', 'images'),
                                                    [('loop_tuple_unpack',
                                                      [('x',
                                                        ('tensor',
                                                         [(1, 'invariant'),
                                                          ('d',
                                                           'invariant')]))],
                                                      ('array',
                                                       [('index',
                                                         'X',
                                                         ('imaginary',))])),
                                                     ('loop_assign',
                                                      'preds',
                                                      ('call',
                                                       'this',
                                                       [('var', 'x')])),
                                                     ('loop_assign',
                                                      'L',
                                                      ('method_call',
                                                       ('var', 'this'),
                                                       'loss',
                                                       [('var', 'x'),
                                                        ('var', 'preds')])),
                                                     ('loop_assign',
                                                      'learnable_grads',
                                                      ('call',
                                                       'grad',
                                                       [('var', 'L'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'learnable_params')])),
                                                     ('body_expr',
                                                      ('method_call',
                                                       ('var', 'this'),
                                                       'update_params',
                                                       [('var', 'lr'),
                                                        ('var',
                                                         'learnable_grads')])),
                                                     ('loop_assign',
                                                      'new_preds',
                                                      ('call',
                                                       'this',
                                                       [('var', 'x')])),
                                                     ('loop_pluseq',
                                                      'total',
                                                      ('method_call',
                                                       ('var', 'this'),
                                                       'loss',
                                                       [('var', 'x'),
                                                        ('var',
                                                         'new_preds')]))]),
                                                   ('loop_assign',
                                                    'epoch_loss',
                                                    ('div',
                                                     ('var', 'total'),
                                                     ('var', 'images'))),
                                                   ('loop_index_assign_nd',
                                                    'losses',
                                                    [('index_item',
                                                      ('var', 'epoch'))],
                                                    ('var', 'epoch_loss')),
                                                   ('loop_call',
                                                    'print',
                                                    [('var', 'epoch_loss')])])],
                                  'body': ('var', 'losses')},
                                 {'name': 'update_params',
                                  'params': [('lr', 'ℝ'),
                                             ('learnable_grads',
                                              ('tensor',
                                               [('m', 'invariant')]))],
                                  'return_type': None,
                                  'statements': [('body_field_assign',
                                                  ('var', 'this'),
                                                  'W',
                                                  ('sub',
                                                   ('field_access',
                                                    ('var', 'this'),
                                                    'W'),
                                                   ('mul',
                                                    ('var', 'lr'),
                                                    ('index',
                                                     'learnable_grads',
                                                     ('num', 0))))),
                                                 ('body_field_assign',
                                                  ('var', 'this'),
                                                  'U',
                                                  ('sub',
                                                   ('field_access',
                                                    ('var', 'this'),
                                                    'U'),
                                                   ('mul',
                                                    ('var', 'lr'),
                                                    ('index',
                                                     'learnable_grads',
                                                     ('num', 1))))),
                                                 ('body_field_assign',
                                                  ('var', 'this'),
                                                  'b',
                                                  ('sub',
                                                   ('field_access',
                                                    ('var', 'this'),
                                                    'b'),
                                                   ('mul',
                                                    ('var', 'lr'),
                                                    ('index',
                                                     'learnable_grads',
                                                     ('num', 2))))),
                                                 ('body_field_assign',
                                                  ('var', 'this'),
                                                  'Wo',
                                                  ('sub',
                                                   ('field_access',
                                                    ('var', 'this'),
                                                    'Wo'),
                                                   ('mul',
                                                    ('var', 'lr'),
                                                    ('index',
                                                     'learnable_grads',
                                                     ('num', 3))))),
                                                 ('body_field_assign',
                                                  ('var', 'this'),
                                                  'bo',
                                                  ('sub',
                                                   ('field_access',
                                                    ('var', 'this'),
                                                    'bo'),
                                                   ('mul',
                                                    ('var', 'lr'),
                                                    ('index',
                                                     'learnable_grads',
                                                     ('num', 4)))))],
                                  'body': None}]}},
 'program': [('seed', ('num', 0)),
             ('func_def', 'gaussian_solve'),
             ('func_def', 'get_2d_array_num_rows'),
             ('func_def', 'get_2d_array_num_cols'),
             ('func_def', 'get_1d_array_length'),
             ('func_def', 'zero_2d_array'),
             ('func_def', 'zero_1d_array'),
             ('func_def', 'max'),
             ('func_def', 'tanh'),
             ('func_def', 'sum_2d'),
             ('func_def', 'rand_array'),
             ('func_def', 'zeros2d'),
             ('func_def', 'zeros1d'),
             ('func_def', 'eye'),
             ('func_def', 'df_dh'),
             ('class_def', 'DEQ'),
             ('expr', ('call', 'print', [('var', 'DEVICE')]), 0),
             ('stmt_tuple_unpack',
              [('d', 'ℝ'), ('n', 'ℝ'), ('solver_steps', 'ℝ')],
              ('expr_list', [('num', 784), ('num', 8), ('num', 3)])),
             ('decl',
              'W',
              ('tensor', [('n', 'invariant'), ('n', 'invariant')]),
              ('call',
               'rand_array',
               [('var', 'n'), ('var', 'n'), ('num', 0.01)]),
              81),
             ('decl',
              'U',
              ('tensor', [('d', 'invariant'), ('n', 'invariant')]),
              ('call',
               'rand_array',
               [('var', 'd'), ('var', 'n'), ('num', 0.02)]),
              82),
             ('decl',
              'b',
              ('tensor', [(1, 'invariant'), ('n', 'invariant')]),
              ('call', 'zeros2d', [('num', 1), ('var', 'n')]),
              83),
             ('decl',
              'Wo',
              ('tensor', [('n', 'invariant'), ('d', 'invariant')]),
              ('call',
               'rand_array',
               [('var', 'n'), ('var', 'd'), ('num', 0.05)]),
              84),
             ('decl',
              'bo',
              ('tensor', [(1, 'invariant'), ('d', 'invariant')]),
              ('call', 'zeros2d', [('num', 1), ('var', 'd')]),
              85),
             ('decl',
              'deq',
              ('struct_type', 'DEQ'),
              ('call',
               'DEQ',
               [('var', 'W'),
                ('var', 'U'),
                ('var', 'b'),
                ('var', 'Wo'),
                ('var', 'bo'),
                ('var', 'n'),
                ('var', 'd'),
                ('var', 'solver_steps')]),
              87),
             ('decl', 'images', 'ℝ', ('num', 10), 90),
             ('decl',
              'X',
              ('tensor', [(10, 'invariant'), (784, 'invariant')]),
              ('call', 'rand_array', [('num', 10), ('num', 784), ('num', 1.0)]),
              91),
             ('decl', 'epochs', 'ℕ', ('num', 1), 96),
             ('decl', 'lr', 'ℝ', ('num', 0.001), 97),
             ('decl',
              'losses',
              ('tensor', [('epochs', 'invariant')]),
              ('method_call',
               ('var', 'deq'),
               'train',
               [('var', 'X'),
                ('var', 'epochs'),
                ('var', 'lr'),
                ('var', 'images')]),
              98),
             ('stmt_tuple_unpack',
              [('loss_before', 'ℝ'), ('loss_after', 'ℝ')],
              ('expr_list',
               [('index', 'losses', ('num', 0)),
                ('indexN', 'losses', [('index_item', ('neg', ('num', 1)))])])),
             ('expr', ('call', 'print', [('var', 'loss_before')]), 0),
             ('expr', ('call', 'print', [('var', 'loss_after')]), 0)]}
