EXPECTED = {'functions': {'tanh': {'params': [('a',
                                    ('tensor',
                                     [('p', 'invariant'),
                                      ('q', 'invariant')]))],
                        'return_type': ('tensor',
                                        [('p', 'invariant'),
                                         ('q', 'invariant')]),
                        'body': ('div', ('var', 'num'), ('var', 'denom')),
                        'has_loop': False,
                        'statements': [('body_decl',
                                        'num',
                                        ('tensor',
                                         [('p', 'invariant'),
                                          ('q', 'invariant')]),
                                        ('sub',
                                         ('call', 'exp', [('var', 'a')]),
                                         ('call',
                                          'exp',
                                          [('neg', ('var', 'a'))]))),
                                       ('body_decl',
                                        'denom',
                                        ('tensor',
                                         [('p', 'invariant'),
                                          ('q', 'invariant')]),
                                        ('add',
                                         ('call', 'exp', [('var', 'a')]),
                                         ('call',
                                          'exp',
                                          [('neg', ('var', 'a'))])))]},
               'rand_array': {'params': [('n', 'ℝ'), ('m', 'ℝ'), ('μ', 'ℝ')],
                              'return_type': ('tensor',
                                              [('n', 'invariant'),
                                               ('m', 'invariant')]),
                              'body': ('for_expr',
                                       'i',
                                       ('var', 'n'),
                                       ('typed_sample_expr',
                                        'ε',
                                        ('tensor', [('m', 'invariant')]),
                                        ('call',
                                         'Normal',
                                         [('num', 0.0),
                                          ('var', 'μ'),
                                          ('var', 'm')]))),
                              'has_loop': False,
                              'statements': []},
               'zeros2d': {'params': [('n', 'ℝ'), ('m', 'ℝ')],
                           'return_type': ('tensor',
                                           [('n', 'invariant'),
                                            ('m', 'invariant')]),
                           'body': ('for_expr',
                                    'i',
                                    ('var', 'n'),
                                    ('for_expr',
                                     'j',
                                     ('var', 'm'),
                                     ('mul', ('var', 'j'), ('num', 0.0)))),
                           'has_loop': False,
                           'statements': []},
               'zeros1d': {'params': [('k', 'ℝ')],
                           'return_type': ('tensor', [('k', 'invariant')]),
                           'body': ('for_expr',
                                    'i',
                                    ('var', 'k'),
                                    ('mul', ('imaginary',), ('num', 0.0))),
                           'has_loop': False,
                           'statements': []},
               'eye': {'params': [('n', 'ℝ')],
                       'return_type': ('tensor',
                                       [('n', 'invariant'),
                                        ('n', 'invariant')]),
                       'body': ('var', 'I'),
                       'has_loop': False,
                       'statements': [('body_decl',
                                       'I',
                                       ('tensor',
                                        [('n', 'invariant'),
                                         ('n', 'invariant')]),
                                       ('for_expr',
                                        'i',
                                        ('var', 'n'),
                                        ('for_expr',
                                         'j',
                                         ('var', 'n'),
                                         ('mul', ('var', 'j'), ('num', 0.0))))),
                                      ('body_for_range',
                                       'i',
                                       ('num', 0),
                                       ('var', 'n'),
                                       [('loop_index_assign_nd',
                                         'I',
                                         [('index_item', ('imaginary',)),
                                          ('index_item', ('imaginary',))],
                                         ('num', 1.0))])]},
               'df_dh': {'params': [('W',
                                     ('tensor',
                                      [('n', 'invariant'),
                                       ('n', 'invariant')])),
                                    ('tanh_prime',
                                     ('tensor',
                                      [(1, 'invariant'), ('n', 'invariant')]))],
                         'return_type': ('tensor',
                                         [('n', 'invariant'),
                                          ('n', 'invariant')]),
                         'body': ('for_expr',
                                  'r',
                                  ('var', 'n'),
                                  ('for_expr',
                                   'c',
                                   ('var', 'n'),
                                   ('mul',
                                    ('indexN',
                                     'W',
                                     [('index_item', ('var', 'r')),
                                      ('index_item', ('var', 'c'))]),
                                    ('indexN',
                                     'tanh_prime',
                                     [('index_item', ('num', 0)),
                                      ('index_item', ('var', 'c'))])))),
                         'has_loop': False,
                         'statements': []},
               'linsolve': {'params': [('A',
                                        ('tensor',
                                         [(16, 'invariant'),
                                          (16, 'invariant')])),
                                       ('b', ('tensor', [(16, 'invariant')]))],
                            'return_type': ('tensor', [(16, 'invariant')]),
                            'body': ('var', 'x'),
                            'has_loop': False,
                            'statements': [('body_decl',
                                            'aug',
                                            ('tensor',
                                             [(16, 'invariant'),
                                              (17, 'invariant')]),
                                            ('call',
                                             'zeros2d',
                                             [('num', 16), ('num', 17)])),
                                           ('body_for_range',
                                            'i',
                                            ('num', 0),
                                            ('num', 16),
                                            [('loop_for_range',
                                              'c',
                                              ('num', 0),
                                              ('num', 16),
                                              [('loop_index_assign_nd',
                                                'aug',
                                                [('index_item', ('imaginary',)),
                                                 ('index_item', ('var', 'c'))],
                                                ('indexN',
                                                 'A',
                                                 [('index_item',
                                                   ('imaginary',)),
                                                  ('index_item',
                                                   ('var', 'c'))]))]),
                                             ('loop_index_assign_nd',
                                              'aug',
                                              [('index_item', ('imaginary',)),
                                               ('index_item', ('num', 16))],
                                              ('index', 'b', ('imaginary',)))]),
                                           ('body_for_range',
                                            'i',
                                            ('num', 0),
                                            ('num', 16),
                                            [('loop_assign',
                                              'piv',
                                              ('call',
                                               'zeros1d',
                                               [('num', 17)])),
                                             ('loop_for_range',
                                              'c',
                                              ('num', 0),
                                              ('num', 17),
                                              [('loop_index_assign_nd',
                                                'piv',
                                                [('index_item', ('var', 'c'))],
                                                ('indexN',
                                                 'aug',
                                                 [('index_item',
                                                   ('imaginary',)),
                                                  ('index_item',
                                                   ('var', 'c'))]))]),
                                             ('loop_assign',
                                              'aug_next',
                                              ('call',
                                               'zeros2d',
                                               [('num', 16), ('num', 17)])),
                                             ('loop_for_range',
                                              'r',
                                              ('num', 0),
                                              ('num', 16),
                                              [('loop_if_else',
                                                ('cond_eq',
                                                 ('var', 'r'),
                                                 ('imaginary',)),
                                                [('loop_for_range',
                                                  'c',
                                                  ('num', 0),
                                                  ('num', 17),
                                                  [('loop_index_assign_nd',
                                                    'aug_next',
                                                    [('index_item',
                                                      ('var', 'r')),
                                                     ('index_item',
                                                      ('var', 'c'))],
                                                    ('div',
                                                     ('index',
                                                      'piv',
                                                      ('var', 'c')),
                                                     ('index',
                                                      'piv',
                                                      ('imaginary',))))])],
                                                [('loop_assign',
                                                  'fac',
                                                  ('div',
                                                   ('indexN',
                                                    'aug',
                                                    [('index_item',
                                                      ('var', 'r')),
                                                     ('index_item',
                                                      ('imaginary',))]),
                                                   ('index',
                                                    'piv',
                                                    ('imaginary',)))),
                                                 ('loop_for_range',
                                                  'c',
                                                  ('num', 0),
                                                  ('num', 17),
                                                  [('loop_index_assign_nd',
                                                    'aug_next',
                                                    [('index_item',
                                                      ('var', 'r')),
                                                     ('index_item',
                                                      ('var', 'c'))],
                                                    ('sub',
                                                     ('indexN',
                                                      'aug',
                                                      [('index_item',
                                                        ('var', 'r')),
                                                       ('index_item',
                                                        ('var', 'c'))]),
                                                     ('mul',
                                                      ('var', 'fac'),
                                                      ('index',
                                                       'piv',
                                                       ('var', 'c')))))])])]),
                                             ('loop_assign',
                                              'aug',
                                              ('var', 'aug_next'))]),
                                           ('body_decl',
                                            'x',
                                            ('tensor', [(16, 'invariant')]),
                                            ('call', 'zeros1d', [('num', 16)])),
                                           ('body_for_range',
                                            'i',
                                            ('num', 0),
                                            ('num', 16),
                                            [('loop_assign',
                                              'idx',
                                              ('sub',
                                               ('num', 15),
                                               ('imaginary',))),
                                             ('loop_assign',
                                              'total',
                                              ('indexN',
                                               'aug',
                                               [('index_item', ('var', 'idx')),
                                                ('index_item', ('num', 16))])),
                                             ('loop_for_range',
                                              'j',
                                              ('add',
                                               ('var', 'idx'),
                                               ('num', 1)),
                                              ('num', 16),
                                              [('loop_assign',
                                                'total',
                                                ('sub',
                                                 ('var', 'total'),
                                                 ('mul',
                                                  ('indexN',
                                                   'aug',
                                                   [('index_item',
                                                     ('var', 'idx')),
                                                    ('index_item',
                                                     ('var', 'j'))]),
                                                  ('index',
                                                   'x',
                                                   ('var', 'j')))))]),
                                             ('loop_assign',
                                              'x_next',
                                              ('call',
                                               'zeros1d',
                                               [('num', 16)])),
                                             ('loop_for_range',
                                              'c',
                                              ('num', 0),
                                              ('num', 16),
                                              [('loop_if_else',
                                                ('cond_eq',
                                                 ('var', 'c'),
                                                 ('var', 'idx')),
                                                [('loop_index_assign_nd',
                                                  'x_next',
                                                  [('index_item',
                                                    ('var', 'c'))],
                                                  ('div',
                                                   ('var', 'total'),
                                                   ('indexN',
                                                    'aug',
                                                    [('index_item',
                                                      ('var', 'idx')),
                                                     ('index_item',
                                                      ('var', 'idx'))])))],
                                                [('loop_index_assign_nd',
                                                  'x_next',
                                                  [('index_item',
                                                    ('var', 'c'))],
                                                  ('index',
                                                   'x',
                                                   ('var', 'c')))])]),
                                             ('loop_assign',
                                              'x',
                                              ('var', 'x_next'))])]}},
 'classes': {'DEQ': {'class_params': [('W',
                                       ('tensor',
                                        [('n', 'invariant'),
                                         ('n', 'invariant')])),
                                      ('U',
                                       ('tensor',
                                        [('d', 'invariant'),
                                         ('n', 'invariant')])),
                                      ('b',
                                       ('tensor',
                                        [(1, 'invariant'),
                                         ('n', 'invariant')])),
                                      ('Wo',
                                       ('tensor',
                                        [('n', 'invariant'),
                                         ('d', 'invariant')])),
                                      ('bo',
                                       ('tensor',
                                        [(1, 'invariant'),
                                         ('d', 'invariant')]))],
                     'fields': [('h_star',
                                 ('tensor',
                                  [(1, 'invariant'), ('n', 'invariant')]))],
                     'methods': [{'name': 'f',
                                  'params': [('h',
                                              ('tensor',
                                               [(1, 'invariant'),
                                                ('n', 'invariant')])),
                                             ('x',
                                              ('tensor',
                                               [(1, 'invariant'),
                                                ('d', 'invariant')]))],
                                  'return_type': ('tensor',
                                                  [(1, 'invariant'),
                                                   ('n', 'invariant')]),
                                  'statements': [],
                                  'body': ('call',
                                           'tanh',
                                           [('add',
                                             ('add',
                                              ('matmul',
                                               ('var', 'h'),
                                               ('var', 'W')),
                                              ('matmul',
                                               ('var', 'x'),
                                               ('var', 'U'))),
                                             ('var', 'b'))])},
                                 {'name': 'equilibrium',
                                  'params': [('x',
                                              ('tensor',
                                               [(1, 'invariant'),
                                                ('d', 'invariant')]))],
                                  'return_type': ('tensor',
                                                  [(1, 'invariant'),
                                                   ('n', 'invariant')]),
                                  'statements': [('body_decl',
                                                  'num_solver_steps',
                                                  'ℕ',
                                                  ('num', 3)),
                                                 ('body_field_assign',
                                                  ('var', 'this'),
                                                  'h_star',
                                                  ('call',
                                                   'zeros2d',
                                                   [('num', 1), ('num', 16)])),
                                                 ('body_decl',
                                                  'f_h',
                                                  ('tensor',
                                                   [(1, 'invariant'),
                                                    ('n', 'invariant')]),
                                                  ('method_call',
                                                   ('var', 'this'),
                                                   'f',
                                                   [('field_access',
                                                     ('var', 'this'),
                                                     'h_star'),
                                                    ('var', 'x')])),
                                                 ('body_decl',
                                                  'tanh_prime',
                                                  ('tensor',
                                                   [(1, 'invariant'),
                                                    ('n', 'invariant')]),
                                                  ('sub',
                                                   ('num', 1.0),
                                                   ('mul',
                                                    ('var', 'f_h'),
                                                    ('var', 'f_h')))),
                                                 ('body_decl',
                                                  'J',
                                                  ('tensor',
                                                   [('n', 'invariant'),
                                                    ('n', 'invariant')]),
                                                  ('sub',
                                                   ('call',
                                                    'df_dh',
                                                    [('var', 'W'),
                                                     ('var', 'tanh_prime')]),
                                                   ('call',
                                                    'eye',
                                                    [('num', 16)]))),
                                                 ('body_for_range',
                                                  'k',
                                                  ('num', 0),
                                                  ('var', 'num_solver_steps'),
                                                  [('loop_assign',
                                                    'g',
                                                    ('sub',
                                                     ('method_call',
                                                      ('var', 'this'),
                                                      'f',
                                                      [('field_access',
                                                        ('var', 'this'),
                                                        'h_star'),
                                                       ('var', 'x')]),
                                                     ('field_access',
                                                      ('var', 'this'),
                                                      'h_star'))),
                                                   ('loop_assign',
                                                    'delta',
                                                    ('call',
                                                     'linsolve',
                                                     [('var', 'J'),
                                                      ('index',
                                                       'g',
                                                       ('num', 0))])),
                                                   ('body_field_assign',
                                                    ('var', 'this'),
                                                    'h_star',
                                                    ('sub',
                                                     ('field_access',
                                                      ('var', 'this'),
                                                      'h_star'),
                                                     ('array',
                                                      [('var', 'delta')])))])],
                                  'body': ('field_access',
                                           ('var', 'this'),
                                           'h_star')},
                                 {'name': 'λ',
                                  'params': [('x',
                                              ('tensor',
                                               [(1, 'invariant'),
                                                ('d', 'invariant')]))],
                                  'return_type': ('tensor',
                                                  [(1, 'invariant'),
                                                   ('d', 'invariant')]),
                                  'statements': [('body_decl',
                                                  'h_star',
                                                  ('tensor',
                                                   [(1, 'invariant'),
                                                    ('n', 'invariant')]),
                                                  ('method_call',
                                                   ('var', 'this'),
                                                   'equilibrium',
                                                   [('var', 'x')]))],
                                  'body': ('add',
                                           ('matmul',
                                            ('var', 'h_star'),
                                            ('var', 'Wo')),
                                           ('var', 'bo'))},
                                 {'name': 'loss',
                                  'params': [('target',
                                              ('tensor',
                                               [(1, 'invariant'),
                                                (784, 'invariant')])),
                                             ('x_hat',
                                              ('tensor',
                                               [(1, 'invariant'),
                                                (784, 'invariant')]))],
                                  'return_type': 'ℝ',
                                  'statements': [('body_decl',
                                                  'diff',
                                                  ('tensor',
                                                   [(1, 'invariant'),
                                                    (784, 'invariant')]),
                                                  ('sub',
                                                   ('var', 'target'),
                                                   ('var', 'x_hat')))],
                                  'body': ('call',
                                           'sum',
                                           [('mul',
                                             ('var', 'diff'),
                                             ('var', 'diff'))])},
                                 {'name': 'train',
                                  'params': [('X',
                                              ('tensor',
                                               [(50, 'invariant'),
                                                (784, 'invariant')])),
                                             ('epochs', 'ℕ'),
                                             ('lr', 'ℝ'),
                                             ('images', 'ℝ')],
                                  'return_type': None,
                                  'statements': [('body_for_range',
                                                  'epoch',
                                                  ('num', 0),
                                                  ('var', 'epochs'),
                                                  [('loop_for_range',
                                                    'i',
                                                    ('num', 0),
                                                    ('var', 'images'),
                                                    [('loop_tuple_unpack',
                                                      [('x',
                                                        ('tensor',
                                                         [(1, 'invariant'),
                                                          ('d',
                                                           'invariant')]))],
                                                      ('array',
                                                       [('index',
                                                         'X',
                                                         ('imaginary',))])),
                                                     ('loop_assign',
                                                      'preds',
                                                      ('call',
                                                       'this',
                                                       [('var', 'x')])),
                                                     ('loop_assign',
                                                      'L',
                                                      ('method_call',
                                                       ('var', 'this'),
                                                       'loss',
                                                       [('var', 'x'),
                                                        ('var', 'preds')])),
                                                     ('loop_assign',
                                                      'grads',
                                                      ('call',
                                                       'grad',
                                                       [('var', 'L'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'params')])),
                                                     ('body_expr',
                                                      ('method_call',
                                                       ('var', 'this'),
                                                       'update_params',
                                                       [('var', 'lr'),
                                                        ('var', 'grads')]))]),
                                                   ('loop_assign',
                                                    'total',
                                                    ('num', 0)),
                                                   ('loop_for_range',
                                                    'i',
                                                    ('num', 0),
                                                    ('var', 'images'),
                                                    [('loop_tuple_unpack',
                                                      [('x',
                                                        ('tensor',
                                                         [(1, 'invariant'),
                                                          ('d',
                                                           'invariant')]))],
                                                      ('array',
                                                       [('index',
                                                         'X',
                                                         ('imaginary',))])),
                                                     ('loop_assign',
                                                      'pred',
                                                      ('call',
                                                       'this',
                                                       [('var', 'x')])),
                                                     ('loop_pluseq',
                                                      'total',
                                                      ('method_call',
                                                       ('var', 'this'),
                                                       'loss',
                                                       [('var', 'x'),
                                                        ('var', 'pred')]))]),
                                                   ('loop_call',
                                                    'print',
                                                    [('div',
                                                      ('var', 'total'),
                                                      ('var', 'images'))])])],
                                  'body': None},
                                 {'name': 'update_params',
                                  'params': [('lr', 'ℝ'),
                                             ('learnable_grads',
                                              ('tensor',
                                               [('m', 'invariant')]))],
                                  'return_type': None,
                                  'statements': [('body_field_assign',
                                                  ('var', 'this'),
                                                  'W',
                                                  ('sub',
                                                   ('field_access',
                                                    ('var', 'this'),
                                                    'W'),
                                                   ('mul',
                                                    ('var', 'lr'),
                                                    ('index',
                                                     'learnable_grads',
                                                     ('num', 0))))),
                                                 ('body_field_assign',
                                                  ('var', 'this'),
                                                  'U',
                                                  ('sub',
                                                   ('field_access',
                                                    ('var', 'this'),
                                                    'U'),
                                                   ('mul',
                                                    ('var', 'lr'),
                                                    ('index',
                                                     'learnable_grads',
                                                     ('num', 1))))),
                                                 ('body_field_assign',
                                                  ('var', 'this'),
                                                  'b',
                                                  ('sub',
                                                   ('field_access',
                                                    ('var', 'this'),
                                                    'b'),
                                                   ('mul',
                                                    ('var', 'lr'),
                                                    ('index',
                                                     'learnable_grads',
                                                     ('num', 2))))),
                                                 ('body_field_assign',
                                                  ('var', 'this'),
                                                  'Wo',
                                                  ('sub',
                                                   ('field_access',
                                                    ('var', 'this'),
                                                    'Wo'),
                                                   ('mul',
                                                    ('var', 'lr'),
                                                    ('index',
                                                     'learnable_grads',
                                                     ('num', 3))))),
                                                 ('body_field_assign',
                                                  ('var', 'this'),
                                                  'bo',
                                                  ('sub',
                                                   ('field_access',
                                                    ('var', 'this'),
                                                    'bo'),
                                                   ('mul',
                                                    ('var', 'lr'),
                                                    ('index',
                                                     'learnable_grads',
                                                     ('num', 4)))))],
                                  'body': None}]}},
 'program': [('seed', ('num', 0)),
             ('func_def', 'tanh'),
             ('func_def', 'rand_array'),
             ('func_def', 'zeros2d'),
             ('func_def', 'zeros1d'),
             ('func_def', 'eye'),
             ('func_def', 'df_dh'),
             ('func_def', 'linsolve'),
             ('class_def', 'DEQ'),
             ('expr', ('call', 'print', [('var', 'DEVICE')]), 0),
             ('decl',
              'W',
              ('tensor', [(16, 'invariant'), (16, 'invariant')]),
              ('call', 'rand_array', [('num', 16), ('num', 16), ('num', 0.01)]),
              103),
             ('decl',
              'U',
              ('tensor', [(784, 'invariant'), (16, 'invariant')]),
              ('call',
               'rand_array',
               [('num', 784), ('num', 16), ('num', 0.02)]),
              104),
             ('decl',
              'b',
              ('tensor', [(1, 'invariant'), (16, 'invariant')]),
              ('call', 'zeros2d', [('num', 1), ('num', 16)]),
              105),
             ('decl',
              'Wo',
              ('tensor', [(16, 'invariant'), (784, 'invariant')]),
              ('call',
               'rand_array',
               [('num', 16), ('num', 784), ('num', 0.05)]),
              106),
             ('decl',
              'bo',
              ('tensor', [(1, 'invariant'), (784, 'invariant')]),
              ('call', 'zeros2d', [('num', 1), ('num', 784)]),
              107),
             ('decl',
              'deq',
              ('struct_type', 'DEQ'),
              ('call',
               'DEQ',
               [('var', 'W'),
                ('var', 'U'),
                ('var', 'b'),
                ('var', 'Wo'),
                ('var', 'bo')]),
              108),
             ('decl', 'images', 'ℝ', ('num', 50), 110),
             ('decl',
              'X',
              ('tensor', [(50, 'invariant'), (784, 'invariant')]),
              ('call', 'rand_array', [('num', 50), ('num', 784), ('num', 1.0)]),
              111),
             ('decl',
              'x0',
              ('tensor', [(1, 'invariant'), (784, 'invariant')]),
              ('array', [('index', 'X', ('num', 0))]),
              113),
             ('decl',
              'recon_before',
              ('tensor', [(1, 'invariant'), (784, 'invariant')]),
              ('call', 'deq', [('var', 'x0')]),
              114),
             ('decl',
              'loss_before',
              'ℝ',
              ('method_call',
               ('var', 'deq'),
               'loss',
               [('var', 'x0'), ('var', 'recon_before')]),
              115),
             ('expr', ('call', 'print', [('var', 'loss_before')]), 0),
             ('decl', 'epochs', 'ℕ', ('num', 1), 118),
             ('decl', 'lr', 'ℝ', ('num', 0.001), 119),
             ('expr',
              ('method_call',
               ('var', 'deq'),
               'train',
               [('var', 'X'),
                ('var', 'epochs'),
                ('var', 'lr'),
                ('var', 'images')]),
              0),
             ('decl',
              'recon_after',
              ('tensor', [(1, 'invariant'), (784, 'invariant')]),
              ('call', 'deq', [('var', 'x0')]),
              121),
             ('decl',
              'loss_after',
              'ℝ',
              ('method_call',
               ('var', 'deq'),
               'loss',
               [('var', 'x0'), ('var', 'recon_after')]),
              122),
             ('expr', ('call', 'print', [('var', 'loss_after')]), 0)]}
