EXPECTED = {'functions': {'dist_3d': {'params': [('p1', ('tensor', [(3, 'invariant')])),
                                      ('p2', ('tensor', [(3, 'invariant')]))],
                           'return_type': 'ℝ',
                           'body': ('pow',
                                    ('var', 'total'),
                                    ('div', ('num', 1), ('num', 2))),
                           'has_loop': False,
                           'statements': [('body_decl',
                                           'total',
                                           'ℝ',
                                           ('num', 0)),
                                          ('body_for_range',
                                           'i',
                                           ('num', 0),
                                           ('num', 3),
                                           [('loop_pluseq',
                                             'total',
                                             ('pow',
                                              ('sub',
                                               ('index', 'p1', ('imaginary',)),
                                               ('index', 'p2', ('imaginary',))),
                                              ('num', 2)))])]},
               'F': {'params': [('q1', 'ℝ'),
                                ('q2', 'ℝ'),
                                ('x1', ('tensor', [(3, 'invariant')])),
                                ('x2', ('tensor', [(3, 'invariant')]))],
                     'return_type': ('tensor', [(3, 'invariant')]),
                     'body': ('mul',
                              ('mul',
                               ('div',
                                ('num', 1),
                                ('mul',
                                 ('mul', ('num', 4), ('var', 'π')),
                                 ('var', 'ε0'))),
                               ('div',
                                ('mul', ('var', 'q1'), ('var', 'q2')),
                                ('pow',
                                 ('call',
                                  'dist_3d',
                                  [('var', 'x1'), ('var', 'x2')]),
                                 ('num', 2)))),
                              ('div',
                               ('sub', ('var', 'x2'), ('var', 'x1')),
                               ('call',
                                'dist_3d',
                                [('var', 'x1'), ('var', 'x2')]))),
                     'has_loop': False,
                     'statements': []},
               'E': {'params': [('q1', 'ℝ'),
                                ('x1', ('tensor', [(3, 'invariant')])),
                                ('x2', ('tensor', [(3, 'invariant')]))],
                     'return_type': ('tensor', [(3, 'invariant')]),
                     'body': ('mul',
                              ('mul',
                               ('div',
                                ('num', 1),
                                ('mul',
                                 ('mul', ('num', 4), ('var', 'π')),
                                 ('var', 'ε0'))),
                               ('div',
                                ('var', 'q1'),
                                ('pow',
                                 ('call',
                                  'dist_3d',
                                  [('var', 'x1'), ('var', 'x2')]),
                                 ('num', 2)))),
                              ('div',
                               ('sub', ('var', 'x2'), ('var', 'x1')),
                               ('call',
                                'dist_3d',
                                [('var', 'x1'), ('var', 'x2')]))),
                     'has_loop': False,
                     'statements': []},
               'dV_dt': {'params': [('V', 'ℝ'), ('Capa', 'ℝ'), ('Ress', 'ℝ')],
                         'return_type': 'ℝ',
                         'body': ('div',
                                  ('neg', ('var', 'V')),
                                  ('mul', ('var', 'Ress'), ('var', 'Capa'))),
                         'has_loop': False,
                         'statements': []},
               'rk4_step': {'params': [('V', 'ℝ'),
                                       ('Capa', 'ℝ'),
                                       ('Ress', 'ℝ'),
                                       ('dt', 'ℝ')],
                            'return_type': 'ℝ',
                            'body': ('add',
                                     ('var', 'V'),
                                     ('mul',
                                      ('div', ('var', 'dt'), ('num', 6.0)),
                                      ('add',
                                       ('add',
                                        ('add',
                                         ('var', 'k1'),
                                         ('mul', ('num', 2.0), ('var', 'k2'))),
                                        ('mul', ('num', 2.0), ('var', 'k3'))),
                                       ('var', 'k4')))),
                            'has_loop': False,
                            'statements': [('body_decl',
                                            'k1',
                                            'ℝ',
                                            ('call',
                                             'dV_dt',
                                             [('var', 'V'),
                                              ('var', 'Capa'),
                                              ('var', 'Ress')])),
                                           ('body_decl',
                                            'k2',
                                            'ℝ',
                                            ('call',
                                             'dV_dt',
                                             [('add',
                                               ('var', 'V'),
                                               ('mul',
                                                ('mul',
                                                 ('num', 0.5),
                                                 ('var', 'dt')),
                                                ('var', 'k1'))),
                                              ('var', 'Capa'),
                                              ('var', 'Ress')])),
                                           ('body_decl',
                                            'k3',
                                            'ℝ',
                                            ('call',
                                             'dV_dt',
                                             [('add',
                                               ('var', 'V'),
                                               ('mul',
                                                ('mul',
                                                 ('num', 0.5),
                                                 ('var', 'dt')),
                                                ('var', 'k2'))),
                                              ('var', 'Capa'),
                                              ('var', 'Ress')])),
                                           ('body_decl',
                                            'k4',
                                            'ℝ',
                                            ('call',
                                             'dV_dt',
                                             [('add',
                                               ('var', 'V'),
                                               ('mul',
                                                ('var', 'dt'),
                                                ('var', 'k3'))),
                                              ('var', 'Capa'),
                                              ('var', 'Ress')]))]},
               'voltage_at': {'params': [('V', 'ℝ'),
                                         ('Capa', 'ℝ'),
                                         ('Ress', 'ℝ'),
                                         ('dt', 'ℝ'),
                                         ('steps', 'ℕ')],
                              'return_type': 'ℝ',
                              'body': ('var', 'V'),
                              'has_loop': False,
                              'statements': [('body_for_range',
                                              'i',
                                              ('num', 0),
                                              ('var', 'steps'),
                                              [('loop_assign',
                                                'V',
                                                ('call',
                                                 'rk4_step',
                                                 [('var', 'V'),
                                                  ('var', 'Capa'),
                                                  ('var', 'Ress'),
                                                  ('var', 'dt')]))])]},
               'current_at': {'params': [('V', 'ℝ'),
                                         ('Capa', 'ℝ'),
                                         ('Ress', 'ℝ'),
                                         ('dt', 'ℝ'),
                                         ('steps', 'ℕ')],
                              'return_type': 'ℝ',
                              'body': ('div', ('var', 'V'), ('var', 'Ress')),
                              'has_loop': False,
                              'statements': [('body_decl',
                                              'V',
                                              'ℝ',
                                              ('call',
                                               'voltage_at',
                                               [('var', 'V'),
                                                ('var', 'Capa'),
                                                ('var', 'Ress'),
                                                ('var', 'dt'),
                                                ('var', 'steps')]))]}},
 'classes': {},
 'program': [('stmt_tuple_unpack',
              [('π', 'ℝ'), ('ε0', 'ℝ')],
              ('expr_list', [('num', 3.14159), ('num', 8.854e-12)])),
             ('func_def', 'dist_3d'),
             ('func_def', 'F'),
             ('assign',
              'coulomb_f',
              ('call',
               'F',
               [('num', 2),
                ('num', 2),
                ('array', [('num', 0), ('num', 0), ('num', 0)]),
                ('array', [('num', 1), ('num', 1), ('num', 1)])]),
              20),
             ('expr', ('call', 'print', [('var', 'coulomb_f')]), 0),
             ('func_def', 'E'),
             ('assign',
              'coulomb_e',
              ('call',
               'E',
               [('num', 2),
                ('array', [('num', 0), ('num', 0), ('num', 0)]),
                ('array', [('num', 1), ('num', 1), ('num', 1)])]),
              29),
             ('expr', ('call', 'print', [('var', 'coulomb_e')]), 0),
             ('func_def', 'dV_dt'),
             ('func_def', 'rk4_step'),
             ('func_def', 'voltage_at'),
             ('func_def', 'current_at'),
             ('stmt_tuple_unpack',
              [('Capa', 'ℝ'), ('Ress', 'ℝ'), ('V0', 'ℝ')],
              ('expr_list', [('num', 1.0), ('num', 10.0), ('num', 10.0)])),
             ('decl', 'dt', 'ℝ', ('num', 0.01), 59),
             ('decl', 'steps', 'ℕ', ('num', 200), 60),
             ('decl',
              'V_final',
              'ℝ',
              ('call',
               'voltage_at',
               [('var', 'V0'),
                ('var', 'Capa'),
                ('var', 'Ress'),
                ('var', 'dt'),
                ('var', 'steps')]),
              62),
             ('expr', ('call', 'print', [('var', 'V_final')]), 0),
             ('decl',
              'I_final',
              'ℝ',
              ('call',
               'current_at',
               [('var', 'V0'),
                ('var', 'Capa'),
                ('var', 'Ress'),
                ('var', 'dt'),
                ('var', 'steps')]),
              65),
             ('expr', ('call', 'print', [('var', 'I_final')]), 0),
             ('decl',
              'V_exact',
              'ℝ',
              ('mul',
               ('var', 'V0'),
               ('call',
                'exp',
                [('div',
                  ('mul', ('neg', ('var', 'dt')), ('var', 'steps')),
                  ('mul', ('var', 'Ress'), ('var', 'Capa')))])),
              69),
             ('expr', ('call', 'print', [('var', 'V_exact')]), 0)]}
