EXPECTED = {'functions': {'dist_3d': {'params': [('p1', ('tensor', [(3, 'invariant')])),
                                      ('p2', ('tensor', [(3, 'invariant')]))],
                           'return_type': 'ℝ',
                           'body': ('pow',
                                    ('add',
                                     ('add',
                                      ('pow',
                                       ('sub',
                                        ('index', 'p1', ('num', 0)),
                                        ('index', 'p2', ('num', 0))),
                                       ('num', 2)),
                                      ('pow',
                                       ('sub',
                                        ('index', 'p1', ('num', 1)),
                                        ('index', 'p2', ('num', 1))),
                                       ('num', 2))),
                                     ('pow',
                                      ('sub',
                                       ('index', 'p1', ('num', 2)),
                                       ('index', 'p2', ('num', 2))),
                                      ('num', 2))),
                                    ('div', ('num', 1), ('num', 2))),
                           'has_loop': False,
                           'statements': []},
               'F': {'params': [('q1', 'ℝ'),
                                ('q2', 'ℝ'),
                                ('x1', ('tensor', [(3, 'invariant')])),
                                ('x2', ('tensor', [(3, 'invariant')]))],
                     'return_type': ('tensor', [(3, 'invariant')]),
                     'body': ('mul',
                              ('mul',
                               ('div',
                                ('num', 1),
                                ('mul',
                                 ('mul', ('num', 4), ('var', 'π')),
                                 ('var', 'ε0'))),
                               ('div',
                                ('mul', ('var', 'q1'), ('var', 'q2')),
                                ('pow',
                                 ('call', 'dist_3d', [('var', 'x1'), ('var', 'x2')]),
                                 ('num', 2)))),
                              ('div',
                               ('sub', ('var', 'x2'), ('var', 'x1')),
                               ('call', 'dist_3d', [('var', 'x1'), ('var', 'x2')]))),
                     'has_loop': False,
                     'statements': []},
               'E': {'params': [('q1', 'ℝ'),
                                ('x1', ('tensor', [(3, 'invariant')])),
                                ('x2', ('tensor', [(3, 'invariant')]))],
                     'return_type': ('tensor', [(3, 'invariant')]),
                     'body': ('mul',
                              ('mul',
                               ('div',
                                ('num', 1),
                                ('mul',
                                 ('mul', ('num', 4), ('var', 'π')),
                                 ('var', 'ε0'))),
                               ('div',
                                ('var', 'q1'),
                                ('pow',
                                 ('call', 'dist_3d', [('var', 'x1'), ('var', 'x2')]),
                                 ('num', 2)))),
                              ('div',
                               ('sub', ('var', 'x2'), ('var', 'x1')),
                               ('call', 'dist_3d', [('var', 'x1'), ('var', 'x2')]))),
                     'has_loop': False,
                     'statements': []}},
 'classes': {'VoltageSource': {'class_params': [('Volt', 'ℝ')],
                               'fields': [],
                               'methods': [{'name': 'voltage',
                                            'params': [],
                                            'return_type': 'ℝ',
                                            'statements': [],
                                            'body': ('field_access',
                                                     ('var', 'this'),
                                                     'Volt')}]},
             'Resistor': {'class_params': [('Ress', 'ℝ')],
                          'fields': [],
                          'methods': [{'name': 'current',
                                       'params': [('V', 'ℝ')],
                                       'return_type': 'ℝ',
                                       'statements': [],
                                       'body': ('div',
                                                ('var', 'V'),
                                                ('field_access',
                                                 ('var', 'this'),
                                                 'Ress'))}]},
             'Capacitor': {'class_params': [('Capa', 'ℝ')],
                           'fields': [],
                           'methods': [{'name': 'dV_dt',
                                        'params': [('V', 'ℝ'), ('Ress', 'ℝ')],
                                        'return_type': 'ℝ',
                                        'statements': [],
                                        'body': ('div',
                                                 ('neg', ('var', 'V')),
                                                 ('mul',
                                                  ('var', 'Ress'),
                                                  ('field_access',
                                                   ('var', 'this'),
                                                   'Capa')))}]},
             'RCCircuit': {'class_params': [('source',
                                             ('struct_type', 'VoltageSource')),
                                            ('resistor', ('struct_type', 'Resistor')),
                                            ('capacitor',
                                             ('struct_type', 'Capacitor'))],
                           'fields': [],
                           'methods': [{'name': 'rk4_step',
                                        'params': [('V', 'ℝ'), ('dt', 'ℝ')],
                                        'return_type': 'ℝ',
                                        'statements': [('body_decl',
                                                        'k1',
                                                        'ℝ',
                                                        ('method_call',
                                                         ('field_access',
                                                          ('var', 'this'),
                                                          'capacitor'),
                                                         'dV_dt',
                                                         [('var', 'V'),
                                                          ('field_access',
                                                           ('field_access',
                                                            ('var', 'this'),
                                                            'resistor'),
                                                           'Ress')])),
                                                       ('body_decl',
                                                        'k2',
                                                        'ℝ',
                                                        ('method_call',
                                                         ('field_access',
                                                          ('var', 'this'),
                                                          'capacitor'),
                                                         'dV_dt',
                                                         [('add',
                                                           ('var', 'V'),
                                                           ('mul',
                                                            ('mul',
                                                             ('num', 0.5),
                                                             ('var', 'dt')),
                                                            ('var', 'k1'))),
                                                          ('field_access',
                                                           ('field_access',
                                                            ('var', 'this'),
                                                            'resistor'),
                                                           'Ress')])),
                                                       ('body_decl',
                                                        'k3',
                                                        'ℝ',
                                                        ('method_call',
                                                         ('field_access',
                                                          ('var', 'this'),
                                                          'capacitor'),
                                                         'dV_dt',
                                                         [('add',
                                                           ('var', 'V'),
                                                           ('mul',
                                                            ('mul',
                                                             ('num', 0.5),
                                                             ('var', 'dt')),
                                                            ('var', 'k2'))),
                                                          ('field_access',
                                                           ('field_access',
                                                            ('var', 'this'),
                                                            'resistor'),
                                                           'Ress')])),
                                                       ('body_decl',
                                                        'k4',
                                                        'ℝ',
                                                        ('method_call',
                                                         ('field_access',
                                                          ('var', 'this'),
                                                          'capacitor'),
                                                         'dV_dt',
                                                         [('add',
                                                           ('var', 'V'),
                                                           ('mul',
                                                            ('var', 'dt'),
                                                            ('var', 'k3'))),
                                                          ('field_access',
                                                           ('field_access',
                                                            ('var', 'this'),
                                                            'resistor'),
                                                           'Ress')]))],
                                        'body': ('add',
                                                 ('var', 'V'),
                                                 ('mul',
                                                  ('div', ('var', 'dt'), ('num', 6.0)),
                                                  ('add',
                                                   ('add',
                                                    ('add',
                                                     ('var', 'k1'),
                                                     ('mul',
                                                      ('num', 2.0),
                                                      ('var', 'k2'))),
                                                    ('mul',
                                                     ('num', 2.0),
                                                     ('var', 'k3'))),
                                                   ('var', 'k4'))))},
                                       {'name': 'voltage_at',
                                        'params': [('dt', 'ℝ'), ('steps', 'ℕ')],
                                        'return_type': 'ℝ',
                                        'statements': [('body_decl',
                                                        'V',
                                                        'ℝ',
                                                        ('method_call',
                                                         ('field_access',
                                                          ('var', 'this'),
                                                          'source'),
                                                         'voltage',
                                                         [])),
                                                       ('body_for_range',
                                                        'i',
                                                        ('num', 0),
                                                        ('var', 'steps'),
                                                        [('loop_assign',
                                                          'V',
                                                          ('method_call',
                                                           ('var', 'this'),
                                                           'rk4_step',
                                                           [('var', 'V'),
                                                            ('var', 'dt')]))])],
                                        'body': ('var', 'V')},
                                       {'name': 'current_at',
                                        'params': [('dt', 'ℝ'), ('steps', 'ℕ')],
                                        'return_type': 'ℝ',
                                        'statements': [('body_decl',
                                                        'V',
                                                        'ℝ',
                                                        ('method_call',
                                                         ('var', 'this'),
                                                         'voltage_at',
                                                         [('var', 'dt'),
                                                          ('var', 'steps')]))],
                                        'body': ('method_call',
                                                 ('field_access',
                                                  ('var', 'this'),
                                                  'resistor'),
                                                 'current',
                                                 [('var', 'V')])}]}},
 'program': [('stmt_tuple_unpack',
              [('π', 'ℝ'), ('ε0', 'ℝ')],
              ('expr_list', [('num', 3.14159), ('num', 8.854e-12)])),
             ('func_def', 'dist_3d'),
             ('func_def', 'F'),
             ('assign',
              'coulomb_f',
              ('call',
               'F',
               [('num', 1),
                ('num', 1),
                ('array', [('num', 0), ('num', 0), ('num', 0)]),
                ('array', [('num', 1), ('num', 1), ('num', 1)])]),
              13),
             ('expr', ('call', 'print', [('var', 'coulomb_f')]), 0),
             ('func_def', 'E'),
             ('assign',
              'coulomb_e',
              ('call',
               'E',
               [('num', 1),
                ('array', [('num', 0), ('num', 0), ('num', 0)]),
                ('array', [('num', 1), ('num', 1), ('num', 1)])]),
              19),
             ('expr', ('call', 'print', [('var', 'coulomb_e')]), 0),
             ('class_def', 'VoltageSource'),
             ('class_def', 'Resistor'),
             ('class_def', 'Capacitor'),
             ('class_def', 'RCCircuit'),
             ('stmt_tuple_unpack',
              [('Capa', 'ℝ'), ('Ress', 'ℝ'), ('V0', 'ℝ')],
              ('expr_list', [('num', 1.0), ('num', 10.0), ('num', 10.0)])),
             ('decl', 'dt', 'ℝ', ('num', 0.01), 63),
             ('decl', 'steps', 'ℕ', ('num', 200), 64),
             ('decl',
              'source',
              ('struct_type', 'VoltageSource'),
              ('call', 'VoltageSource', [('var', 'V0')]),
              66),
             ('decl',
              'resistor',
              ('struct_type', 'Resistor'),
              ('call', 'Resistor', [('var', 'Ress')]),
              67),
             ('decl',
              'capacitor',
              ('struct_type', 'Capacitor'),
              ('call', 'Capacitor', [('var', 'Capa')]),
              68),
             ('decl',
              'circuit',
              ('struct_type', 'RCCircuit'),
              ('call',
               'RCCircuit',
               [('var', 'source'), ('var', 'resistor'), ('var', 'capacitor')]),
              69),
             ('decl',
              'V_final',
              'ℝ',
              ('method_call',
               ('var', 'circuit'),
               'voltage_at',
               [('var', 'dt'), ('var', 'steps')]),
              71),
             ('expr', ('call', 'print', [('var', 'V_final')]), 0),
             ('decl',
              'I_final',
              'ℝ',
              ('method_call',
               ('var', 'circuit'),
               'current_at',
               [('var', 'dt'), ('var', 'steps')]),
              74),
             ('expr', ('call', 'print', [('var', 'I_final')]), 0)]}
