EXPECTED = {'functions': {'dist_3d': {'params': [('p1', ('tensor', [(3, 'invariant')])),
                                      ('p2', ('tensor', [(3, 'invariant')]))],
                           'return_type': 'ℝ',
                           'body': ('pow',
                                    ('add',
                                     ('add',
                                      ('pow',
                                       ('sub',
                                        ('index', 'p1', ('num', 0)),
                                        ('index', 'p2', ('num', 0))),
                                       ('num', 2)),
                                      ('pow',
                                       ('sub',
                                        ('index', 'p1', ('num', 1)),
                                        ('index', 'p2', ('num', 1))),
                                       ('num', 2))),
                                     ('pow',
                                      ('sub',
                                       ('index', 'p1', ('num', 2)),
                                       ('index', 'p2', ('num', 2))),
                                      ('num', 2))),
                                    ('div', ('num', 1), ('num', 2))),
                           'has_loop': False,
                           'statements': []},
               'F': {'params': [('q1', 'ℝ'),
                                ('q2', 'ℝ'),
                                ('x1', ('tensor', [(3, 'invariant')])),
                                ('x2', ('tensor', [(3, 'invariant')]))],
                     'return_type': ('tensor', [(3, 'invariant')]),
                     'body': ('mul',
                              ('mul',
                               ('div',
                                ('num', 1),
                                ('mul',
                                 ('mul', ('num', 4), ('var', 'π')),
                                 ('var', 'ε0'))),
                               ('div',
                                ('mul', ('var', 'q1'), ('var', 'q2')),
                                ('pow',
                                 ('call', 'dist_3d', [('var', 'x1'), ('var', 'x2')]),
                                 ('num', 2)))),
                              ('div',
                               ('sub', ('var', 'x2'), ('var', 'x1')),
                               ('call', 'dist_3d', [('var', 'x1'), ('var', 'x2')]))),
                     'has_loop': False,
                     'statements': []},
               'E': {'params': [('q1', 'ℝ'),
                                ('x1', ('tensor', [(3, 'invariant')])),
                                ('x2', ('tensor', [(3, 'invariant')]))],
                     'return_type': ('tensor', [(3, 'invariant')]),
                     'body': ('mul',
                              ('mul',
                               ('div',
                                ('num', 1),
                                ('mul',
                                 ('mul', ('num', 4), ('var', 'π')),
                                 ('var', 'ε0'))),
                               ('div',
                                ('var', 'q1'),
                                ('pow',
                                 ('call', 'dist_3d', [('var', 'x1'), ('var', 'x2')]),
                                 ('num', 2)))),
                              ('div',
                               ('sub', ('var', 'x2'), ('var', 'x1')),
                               ('call', 'dist_3d', [('var', 'x1'), ('var', 'x2')]))),
                     'has_loop': False,
                     'statements': []},
               'coulomb_graph': {'params': [('q', ('tensor', [('n', 'invariant')])),
                                            ('x',
                                             ('tensor',
                                              [('n', 'invariant'), (3, 'invariant')]))],
                                 'return_type': ('struct_type', 'UndirectedGraph'),
                                 'body': ('var', 'g'),
                                 'has_loop': False,
                                 'statements': [('body_decl',
                                                 'k',
                                                 'ℝ',
                                                 ('call',
                                                  'get_2d_array_num_rows',
                                                  [('var', 'x')])),
                                                ('body_decl',
                                                 'g',
                                                 ('struct_type', 'UndirectedGraph'),
                                                 ('call',
                                                  'empty_graph',
                                                  [('var', 'k')])),
                                                ('body_for_range',
                                                 'i',
                                                 ('num', 0),
                                                 ('var', 'k'),
                                                 [('loop_for_range',
                                                   'j',
                                                   ('num', 0),
                                                   ('var', 'k'),
                                                   [('loop_if',
                                                     ('cond_lt',
                                                      ('imaginary',),
                                                      ('var', 'j')),
                                                     [('body_expr',
                                                       ('method_call',
                                                        ('var', 'g'),
                                                        'add_weighted_edge',
                                                        [('mul',
                                                          ('imaginary',),
                                                          ('num', 1.0)),
                                                         ('mul',
                                                          ('var', 'j'),
                                                          ('num', 1.0)),
                                                         ('div',
                                                          ('mul',
                                                           ('mul',
                                                            ('div',
                                                             ('num', 1),
                                                             ('mul',
                                                              ('mul',
                                                               ('num', 4),
                                                               ('var', 'π')),
                                                              ('var', 'ε0'))),
                                                            ('index',
                                                             'q',
                                                             ('imaginary',))),
                                                           ('index',
                                                            'q',
                                                            ('var', 'j'))),
                                                          ('call',
                                                           'dist_3d',
                                                           [('index',
                                                             'x',
                                                             ('imaginary',)),
                                                            ('index',
                                                             'x',
                                                             ('var',
                                                              'j'))]))]))])])])]},
               'total_energy': {'params': [('g', ('struct_type', 'UndirectedGraph'))],
                                'return_type': 'ℝ',
                                'body': ('div', ('var', 'acc'), ('num', 2)),
                                'has_loop': False,
                                'statements': [('body_decl',
                                                'k',
                                                'ℝ',
                                                ('method_call',
                                                 ('var', 'g'),
                                                 'num_vertices',
                                                 [])),
                                               ('body_decl', 'acc', 'ℝ', ('num', 0)),
                                               ('body_for_range',
                                                'u',
                                                ('num', 0),
                                                ('var', 'k'),
                                                [('loop_pluseq',
                                                  'acc',
                                                  ('method_call',
                                                   ('var', 'g'),
                                                   'degree',
                                                   [('mul',
                                                     ('var', 'u'),
                                                     ('num', 1.0))]))])]},
               'kcl_current': {'params': [('g', ('struct_type', 'UndirectedGraph')),
                                          ('V', ('tensor', [('n', 'invariant')]))],
                               'return_type': ('tensor', [('n', 'invariant')]),
                               'body': ('var', 'I'),
                               'has_loop': False,
                               'statements': [('body_decl',
                                               'k',
                                               'ℝ',
                                               ('method_call',
                                                ('var', 'g'),
                                                'num_vertices',
                                                [])),
                                              ('body_decl',
                                               'I',
                                               ('tensor', [('n', 'invariant')]),
                                               ('mul', ('var', 'V'), ('num', 0.0))),
                                              ('body_for_range',
                                               'u',
                                               ('num', 0),
                                               ('var', 'k'),
                                               [('loop_index_assign_nd',
                                                 'I',
                                                 [('index_item', ('var', 'u'))],
                                                 ('call',
                                                  'get_sum_of_1d_array',
                                                  [('mul',
                                                    ('method_call',
                                                     ('var', 'g'),
                                                     'neighbors',
                                                     [('mul',
                                                       ('var', 'u'),
                                                       ('num', 1.0))]),
                                                    ('sub',
                                                     ('index', 'V', ('var', 'u')),
                                                     ('var', 'V')))]))])]},
               'dV_dt': {'params': [('net', ('struct_type', 'RCNetwork')),
                                    ('V', ('tensor', [('n', 'invariant')]))],
                         'return_type': ('tensor', [('n', 'invariant')]),
                         'body': ('mul',
                                  ('div',
                                   ('neg',
                                    ('call',
                                     'kcl_current',
                                     [('field_access', ('var', 'net'), 'wires'),
                                      ('var', 'V')])),
                                   ('field_access',
                                    ('field_access', ('var', 'net'), 'capacitor'),
                                    'Capa')),
                                  ('field_access', ('var', 'net'), 'free')),
                         'has_loop': False,
                         'statements': []},
               'rk4_step': {'params': [('net', ('struct_type', 'RCNetwork')),
                                       ('V', ('tensor', [('n', 'invariant')])),
                                       ('dt', 'ℝ')],
                            'return_type': ('tensor', [('n', 'invariant')]),
                            'body': ('add',
                                     ('var', 'V'),
                                     ('mul',
                                      ('div', ('var', 'dt'), ('num', 6.0)),
                                      ('add',
                                       ('add',
                                        ('add',
                                         ('var', 'k1'),
                                         ('mul', ('num', 2.0), ('var', 'k2'))),
                                        ('mul', ('num', 2.0), ('var', 'k3'))),
                                       ('var', 'k4')))),
                            'has_loop': False,
                            'statements': [('body_decl',
                                            'k1',
                                            ('tensor', [('n', 'invariant')]),
                                            ('call',
                                             'dV_dt',
                                             [('var', 'net'), ('var', 'V')])),
                                           ('body_decl',
                                            'k2',
                                            ('tensor', [('n', 'invariant')]),
                                            ('call',
                                             'dV_dt',
                                             [('var', 'net'),
                                              ('add',
                                               ('var', 'V'),
                                               ('mul',
                                                ('mul', ('num', 0.5), ('var', 'dt')),
                                                ('var', 'k1')))])),
                                           ('body_decl',
                                            'k3',
                                            ('tensor', [('n', 'invariant')]),
                                            ('call',
                                             'dV_dt',
                                             [('var', 'net'),
                                              ('add',
                                               ('var', 'V'),
                                               ('mul',
                                                ('mul', ('num', 0.5), ('var', 'dt')),
                                                ('var', 'k2')))])),
                                           ('body_decl',
                                            'k4',
                                            ('tensor', [('n', 'invariant')]),
                                            ('call',
                                             'dV_dt',
                                             [('var', 'net'),
                                              ('add',
                                               ('var', 'V'),
                                               ('mul',
                                                ('var', 'dt'),
                                                ('var', 'k3')))]))]},
               'voltage_at': {'params': [('net', ('struct_type', 'RCNetwork')),
                                         ('V0', ('tensor', [('n', 'invariant')])),
                                         ('dt', 'ℝ'),
                                         ('steps', 'ℕ')],
                              'return_type': ('tensor', [('n', 'invariant')]),
                              'body': ('var', 'V'),
                              'has_loop': False,
                              'statements': [('body_decl',
                                              'V',
                                              ('tensor', [('n', 'invariant')]),
                                              ('var', 'V0')),
                                             ('body_for_range',
                                              'i',
                                              ('num', 0),
                                              ('var', 'steps'),
                                              [('loop_assign',
                                                'V',
                                                ('call',
                                                 'rk4_step',
                                                 [('var', 'net'),
                                                  ('var', 'V'),
                                                  ('var', 'dt')]))])]},
               'joule_power': {'params': [('net', ('struct_type', 'RCNetwork')),
                                          ('V', ('tensor', [('n', 'invariant')]))],
                               'return_type': 'ℝ',
                               'body': ('call',
                                        'get_sum_of_1d_array',
                                        [('mul',
                                          ('var', 'V'),
                                          ('call',
                                           'kcl_current',
                                           [('field_access', ('var', 'net'), 'wires'),
                                            ('var', 'V')]))]),
                               'has_loop': False,
                               'statements': []},
               'V_after': {'params': [('R_', 'ℝ')],
                           'return_type': 'ℝ',
                           'body': ('index', 'V', ('num', 1)),
                           'has_loop': False,
                           'statements': [('body_decl',
                                           'wires',
                                           ('struct_type', 'UndirectedGraph'),
                                           ('call', 'empty_graph', [('num', 2)])),
                                          ('body_expr',
                                           ('method_call',
                                            ('var', 'wires'),
                                            'add_weighted_edge',
                                            [('num', 0.0),
                                             ('num', 1.0),
                                             ('div', ('num', 1), ('var', 'R_'))])),
                                          ('body_decl',
                                           'net',
                                           ('struct_type', 'RCNetwork'),
                                           ('call',
                                            'RCNetwork',
                                            [('var', 'wires'),
                                             ('var', 'capacitor'),
                                             ('array', [('num', 0.0), ('num', 1.0)])])),
                                          ('body_decl',
                                           'V',
                                           ('tensor', [(2, 'invariant')]),
                                           ('call',
                                            'voltage_at',
                                            [('var', 'net'),
                                             ('array', [('num', 0.0), ('var', 'V0')]),
                                             ('var', 'dt'),
                                             ('var', 'steps')]))]},
               'empty_graph': {'params': [('n_vertices', 'ℕ')],
                               'return_type': ('struct_type', 'UndirectedGraph'),
                               'body': ('var', 'g'),
                               'has_loop': False,
                               'statements': [('body_decl',
                                               'z',
                                               ('tensor',
                                                [('n_vertices', 'invariant'),
                                                 ('n_vertices', 'invariant')]),
                                               ('for_expr',
                                                'a',
                                                ('var', 'n_vertices'),
                                                ('for_expr',
                                                 'b',
                                                 ('var', 'n_vertices'),
                                                 ('mul',
                                                  ('add', ('var', 'a'), ('var', 'b')),
                                                  ('num', 0.0))))),
                                              ('body_decl',
                                               'g',
                                               ('struct_type', 'UndirectedGraph'),
                                               ('call', 'UndirectedGraph', [])),
                                              ('body_field_assign',
                                               ('var', 'g'),
                                               'adjacency',
                                               ('var', 'z'))]},
               'get_sum_of_1d_array': {'params': [('x',
                                                   ('tensor', [('m', 'invariant')]))],
                                       'return_type': 'ℝ',
                                       'body': ('var', 'total'),
                                       'has_loop': False,
                                       'statements': [('body_decl',
                                                       'total',
                                                       'ℝ',
                                                       ('num', 0)),
                                                      ('body_for',
                                                       'i',
                                                       [('loop_pluseq',
                                                         'total',
                                                         ('index',
                                                          'x',
                                                          ('imaginary',)))],
                                                       ['x'])]},
               'get_2d_array_num_rows': {'params': [('x',
                                                     ('tensor',
                                                      [('m', 'invariant'),
                                                       ('n', 'invariant')]))],
                                         'return_type': 'ℝ',
                                         'body': ('var', 'total'),
                                         'has_loop': False,
                                         'statements': [('body_decl',
                                                         'total',
                                                         'ℝ',
                                                         ('num', 0)),
                                                        ('body_decl',
                                                         'temp',
                                                         'ℝ',
                                                         ('num', 0)),
                                                        ('body_for',
                                                         'i',
                                                         [('loop_assign',
                                                           'temp',
                                                           ('index',
                                                            'x',
                                                            ('imaginary',))),
                                                          ('loop_pluseq',
                                                           'total',
                                                           ('num', 1))],
                                                         ['x'])]}},
 'classes': {'Resistor': {'class_params': [('Ress', 'ℝ')],
                          'fields': [],
                          'methods': [{'name': 'conductance',
                                       'params': [],
                                       'return_type': 'ℝ',
                                       'statements': [],
                                       'body': ('div',
                                                ('num', 1),
                                                ('field_access',
                                                 ('var', 'this'),
                                                 'Ress'))},
                                      {'name': 'current',
                                       'params': [('V', 'ℝ')],
                                       'return_type': 'ℝ',
                                       'statements': [],
                                       'body': ('div',
                                                ('var', 'V'),
                                                ('field_access',
                                                 ('var', 'this'),
                                                 'Ress'))}]},
             'Capacitor': {'class_params': [('Capa', 'ℝ')],
                           'fields': [],
                           'methods': []},
             'RCNetwork': {'class_params': [('wires',
                                             ('struct_type', 'UndirectedGraph')),
                                            ('capacitor', ('struct_type', 'Capacitor')),
                                            ('free', ('tensor', [('n', 'invariant')]))],
                           'fields': [],
                           'methods': []},
             'UndirectedGraph': {'class_params': [],
                                 'fields': [('adjacency',
                                             ('tensor',
                                              [('n', 'invariant'),
                                               ('n', 'invariant')]))],
                                 'methods': [{'name': 'num_vertices',
                                              'params': [],
                                              'return_type': 'ℝ',
                                              'statements': [],
                                              'body': ('mul',
                                                       ('call',
                                                        'get_2d_array_num_rows',
                                                        [('field_access',
                                                          ('var', 'this'),
                                                          'adjacency')]),
                                                       ('num', 1.0))},
                                             {'name': 'has_edge',
                                              'params': [('u', 'ℝ'), ('v', 'ℝ')],
                                              'return_type': 'ℝ',
                                              'statements': [('body_decl',
                                                              'm',
                                                              ('tensor',
                                                               [('n', 'invariant'),
                                                                ('n', 'invariant')]),
                                                              ('field_access',
                                                               ('var', 'this'),
                                                               'adjacency')),
                                                             ('body_decl',
                                                              'r',
                                                              ('tensor',
                                                               [('n', 'invariant')]),
                                                              ('index',
                                                               'm',
                                                               ('var', 'u')))],
                                              'body': ('index', 'r', ('var', 'v'))},
                                             {'name': 'degree',
                                              'params': [('u', 'ℝ')],
                                              'return_type': 'ℝ',
                                              'statements': [('body_decl',
                                                              'm',
                                                              ('tensor',
                                                               [('n', 'invariant'),
                                                                ('n', 'invariant')]),
                                                              ('field_access',
                                                               ('var', 'this'),
                                                               'adjacency')),
                                                             ('body_decl',
                                                              'r',
                                                              ('tensor',
                                                               [('n', 'invariant')]),
                                                              ('index',
                                                               'm',
                                                               ('var', 'u')))],
                                              'body': ('call',
                                                       'get_sum_of_1d_array',
                                                       [('var', 'r')])},
                                             {'name': 'sq_degree_sum',
                                              'params': [('s', 'ℝ')],
                                              'return_type': 'ℝ',
                                              'statements': [('body_decl',
                                                              'm',
                                                              ('tensor',
                                                               [('n', 'invariant'),
                                                                ('n', 'invariant')]),
                                                              ('field_access',
                                                               ('var', 'this'),
                                                               'adjacency')),
                                                             ('body_decl',
                                                              'k',
                                                              'ℝ',
                                                              ('call',
                                                               'get_2d_array_num_rows',
                                                               [('var', 'm')])),
                                                             ('body_decl',
                                                              'acc',
                                                              'ℝ',
                                                              ('num', 0)),
                                                             ('body_for_range',
                                                              'i',
                                                              ('num', 0),
                                                              ('var', 'k'),
                                                              [('loop_tuple_unpack',
                                                                [('d', 'ℝ')],
                                                                ('num', 0)),
                                                               ('loop_for_range',
                                                                'j',
                                                                ('num', 0),
                                                                ('var', 'k'),
                                                                [('loop_pluseq',
                                                                  'd',
                                                                  ('mul',
                                                                   ('var', 's'),
                                                                   ('indexN',
                                                                    'm',
                                                                    [('index_item',
                                                                      ('imaginary',)),
                                                                     ('index_item',
                                                                      ('var',
                                                                       'j'))])))]),
                                                               ('loop_pluseq',
                                                                'acc',
                                                                ('mul',
                                                                 ('var', 'd'),
                                                                 ('var', 'd')))])],
                                              'body': ('var', 'acc')},
                                             {'name': 'neighbors',
                                              'params': [('u', 'ℝ')],
                                              'return_type': ('tensor',
                                                              [('n', 'invariant')]),
                                              'statements': [('body_decl',
                                                              'm',
                                                              ('tensor',
                                                               [('n', 'invariant'),
                                                                ('n', 'invariant')]),
                                                              ('field_access',
                                                               ('var', 'this'),
                                                               'adjacency'))],
                                              'body': ('index', 'm', ('var', 'u'))},
                                             {'name': 'add_weighted_edge',
                                              'params': [('u', 'ℝ'),
                                                         ('v', 'ℝ'),
                                                         ('w', 'ℝ')],
                                              'return_type': None,
                                              'statements': [('body_decl',
                                                              'm',
                                                              ('tensor',
                                                               [('n', 'invariant'),
                                                                ('n', 'invariant')]),
                                                              ('field_access',
                                                               ('var', 'this'),
                                                               'adjacency')),
                                                             ('body_decl',
                                                              'k',
                                                              'ℝ',
                                                              ('call',
                                                               'get_2d_array_num_rows',
                                                               [('var', 'm')])),
                                                             ('body_decl',
                                                              'new_adj',
                                                              ('tensor',
                                                               [('n', 'invariant'),
                                                                ('n', 'invariant')]),
                                                              ('for_expr',
                                                               'a',
                                                               ('var', 'k'),
                                                               ('for_expr',
                                                                'b',
                                                                ('var', 'k'),
                                                                ('indexN',
                                                                 'm',
                                                                 [('index_item',
                                                                   ('var', 'a')),
                                                                  ('index_item',
                                                                   ('var', 'b'))])))),
                                                             ('body_index_assign_nd',
                                                              'new_adj',
                                                              [('index_item',
                                                                ('var', 'u')),
                                                               ('index_item',
                                                                ('var', 'v'))],
                                                              ('var', 'w')),
                                                             ('body_index_assign_nd',
                                                              'new_adj',
                                                              [('index_item',
                                                                ('var', 'v')),
                                                               ('index_item',
                                                                ('var', 'u'))],
                                                              ('var', 'w')),
                                                             ('body_field_assign',
                                                              ('var', 'this'),
                                                              'adjacency',
                                                              ('var', 'new_adj'))],
                                              'body': None},
                                             {'name': 'add_edge',
                                              'params': [('u', 'ℝ'), ('v', 'ℝ')],
                                              'return_type': None,
                                              'statements': [('body_expr',
                                                              ('method_call',
                                                               ('var', 'this'),
                                                               'add_weighted_edge',
                                                               [('var', 'u'),
                                                                ('var', 'v'),
                                                                ('num', 1.0)]))],
                                              'body': None},
                                             {'name': 'grow_adjacency',
                                              'params': [('new_n', 'ℕ')],
                                              'return_type': ('tensor',
                                                              [('new_n', 'invariant'),
                                                               ('new_n', 'invariant')]),
                                              'statements': [('body_decl',
                                                              'old',
                                                              ('tensor',
                                                               [('n', 'invariant'),
                                                                ('n', 'invariant')]),
                                                              ('field_access',
                                                               ('var', 'this'),
                                                               'adjacency')),
                                                             ('body_decl',
                                                              'result',
                                                              ('tensor',
                                                               [('new_n', 'invariant'),
                                                                ('new_n',
                                                                 'invariant')]),
                                                              ('for_expr',
                                                               'a',
                                                               ('var', 'new_n'),
                                                               ('for_expr',
                                                                'b',
                                                                ('var', 'new_n'),
                                                                ('mul',
                                                                 ('add',
                                                                  ('var', 'a'),
                                                                  ('var', 'b')),
                                                                 ('num', 0.0))))),
                                                             ('body_decl',
                                                              'm',
                                                              'ℝ',
                                                              ('call',
                                                               'get_2d_array_num_rows',
                                                               [('var', 'old')])),
                                                             ('body_for_range',
                                                              'a',
                                                              ('num', 0),
                                                              ('var', 'm'),
                                                              [('loop_for_range',
                                                                'b',
                                                                ('num', 0),
                                                                ('var', 'm'),
                                                                [('loop_index_assign_nd',
                                                                  'result',
                                                                  [('index_item',
                                                                    ('var', 'a')),
                                                                   ('index_item',
                                                                    ('var', 'b'))],
                                                                  ('indexN',
                                                                   'old',
                                                                   [('index_item',
                                                                     ('var', 'a')),
                                                                    ('index_item',
                                                                     ('var',
                                                                      'b'))]))])])],
                                              'body': ('var', 'result')},
                                             {'name': 'add_vertex',
                                              'params': [('new_n', 'ℕ')],
                                              'return_type': None,
                                              'statements': [('body_field_assign',
                                                              ('var', 'this'),
                                                              'adjacency',
                                                              ('method_call',
                                                               ('var', 'this'),
                                                               'grow_adjacency',
                                                               [('var', 'new_n')]))],
                                              'body': None}]}},
 'program': [('class_def', 'UndirectedGraph'),
             ('func_def', 'empty_graph'),
             ('func_def', 'get_sum_of_1d_array'),
             ('func_def', 'get_2d_array_num_rows'),
             ('stmt_tuple_unpack',
              [('π', 'ℝ'), ('ε0', 'ℝ')],
              ('expr_list', [('num', 3.14159), ('num', 8.854e-12)])),
             ('func_def', 'dist_3d'),
             ('func_def', 'F'),
             ('assign',
              'coulomb_f',
              ('call',
               'F',
               [('num', 1.0),
                ('num', 1.0),
                ('array', [('num', 0.0), ('num', 0.0), ('num', 0.0)]),
                ('array', [('num', 1.0), ('num', 1.0), ('num', 1.0)])]),
              28),
             ('expr', ('call', 'print', [('var', 'coulomb_f')]), 0),
             ('func_def', 'E'),
             ('assign',
              'coulomb_e',
              ('call',
               'E',
               [('num', 1.0),
                ('array', [('num', 0.0), ('num', 0.0), ('num', 0.0)]),
                ('array', [('num', 1.0), ('num', 1.0), ('num', 1.0)])]),
              34),
             ('expr', ('call', 'print', [('var', 'coulomb_e')]), 0),
             ('func_def', 'coulomb_graph'),
             ('func_def', 'total_energy'),
             ('decl',
              'q',
              ('tensor', [(3, 'invariant')]),
              ('array', [('num', 1.0), ('neg', ('num', 2.0)), ('num', 1.0)]),
              65),
             ('decl',
              'xs',
              ('tensor', [(3, 'invariant'), (3, 'invariant')]),
              ('array',
               [('array', [('neg', ('num', 1.0)), ('num', 0.0), ('num', 0.0)]),
                ('array', [('num', 0.0), ('num', 0.5), ('num', 0.0)]),
                ('array', [('num', 1.0), ('num', 0.0), ('num', 0.0)])]),
              66),
             ('decl',
              'cg',
              ('struct_type', 'UndirectedGraph'),
              ('call', 'coulomb_graph', [('var', 'q'), ('var', 'xs')]),
              67),
             ('decl',
              'U_O',
              'ℝ',
              ('method_call', ('var', 'cg'), 'degree', [('num', 1.0)]),
              69),
             ('expr', ('call', 'print', [('var', 'U_O')]), 0),
             ('decl', 'U', 'ℝ', ('call', 'total_energy', [('var', 'cg')]), 71),
             ('expr', ('call', 'print', [('var', 'U')]), 0),
             ('class_def', 'Resistor'),
             ('class_def', 'Capacitor'),
             ('func_def', 'kcl_current'),
             ('class_def', 'RCNetwork'),
             ('func_def', 'dV_dt'),
             ('func_def', 'rk4_step'),
             ('func_def', 'voltage_at'),
             ('func_def', 'joule_power'),
             ('stmt_tuple_unpack',
              [('Capa', 'ℝ'), ('Ress', 'ℝ'), ('V0', 'ℝ')],
              ('expr_list', [('num', 1.0), ('num', 10.0), ('num', 10.0)])),
             ('decl', 'dt', 'ℝ', ('num', 0.01), 142),
             ('decl', 'steps', 'ℕ', ('num', 200), 143),
             ('decl',
              'capacitor',
              ('struct_type', 'Capacitor'),
              ('call', 'Capacitor', [('var', 'Capa')]),
              144),
             ('decl',
              'resistor',
              ('struct_type', 'Resistor'),
              ('call', 'Resistor', [('var', 'Ress')]),
              145),
             ('decl',
              'rc_wires',
              ('struct_type', 'UndirectedGraph'),
              ('call', 'empty_graph', [('num', 2)]),
              149),
             ('expr',
              ('method_call',
               ('var', 'rc_wires'),
               'add_weighted_edge',
               [('num', 0.0),
                ('num', 1.0),
                ('method_call', ('var', 'resistor'), 'conductance', [])]),
              0),
             ('decl',
              'rc',
              ('struct_type', 'RCNetwork'),
              ('call',
               'RCNetwork',
               [('var', 'rc_wires'),
                ('var', 'capacitor'),
                ('array', [('num', 0.0), ('num', 1.0)])]),
              151),
             ('decl',
              'V_rc',
              ('tensor', [(2, 'invariant')]),
              ('call',
               'voltage_at',
               [('var', 'rc'),
                ('array', [('num', 0.0), ('var', 'V0')]),
                ('var', 'dt'),
                ('var', 'steps')]),
              153),
             ('expr', ('call', 'print', [('var', 'V_rc')]), 0),
             ('decl',
              'I_final',
              'ℝ',
              ('method_call',
               ('var', 'resistor'),
               'current',
               [('index', 'V_rc', ('num', 1))]),
              156),
             ('expr', ('call', 'print', [('var', 'I_final')]), 0),
             ('decl',
              'ladder_wires',
              ('struct_type', 'UndirectedGraph'),
              ('call', 'empty_graph', [('num', 4)]),
              161),
             ('expr',
              ('method_call',
               ('var', 'ladder_wires'),
               'add_weighted_edge',
               [('num', 0.0),
                ('num', 1.0),
                ('method_call', ('var', 'resistor'), 'conductance', [])]),
              0),
             ('expr',
              ('method_call',
               ('var', 'ladder_wires'),
               'add_weighted_edge',
               [('num', 1.0),
                ('num', 2.0),
                ('method_call', ('var', 'resistor'), 'conductance', [])]),
              0),
             ('expr',
              ('method_call',
               ('var', 'ladder_wires'),
               'add_weighted_edge',
               [('num', 2.0),
                ('num', 3.0),
                ('method_call', ('var', 'resistor'), 'conductance', [])]),
              0),
             ('decl',
              'ladder',
              ('struct_type', 'RCNetwork'),
              ('call',
               'RCNetwork',
               [('var', 'ladder_wires'),
                ('var', 'capacitor'),
                ('array', [('num', 0.0), ('num', 1.0), ('num', 1.0), ('num', 1.0)])]),
              165),
             ('decl',
              'V_ladder',
              ('tensor', [(4, 'invariant')]),
              ('call',
               'voltage_at',
               [('var', 'ladder'),
                ('array', [('num', 0.0), ('var', 'V0'), ('var', 'V0'), ('var', 'V0')]),
                ('var', 'dt'),
                ('var', 'steps')]),
              167),
             ('expr', ('call', 'print', [('var', 'V_ladder')]), 0),
             ('decl',
              'P_ladder',
              'ℝ',
              ('call', 'joule_power', [('var', 'ladder'), ('var', 'V_ladder')]),
              170),
             ('expr', ('call', 'print', [('var', 'P_ladder')]), 0),
             ('func_def', 'V_after'),
             ('decl', 'R0', 'ℝ', ('num', 10.0), 188),
             ('expr', ('call', 'print', [('call', 'V_after', [('var', 'R0')])]), 0),
             ('expr',
              ('call',
               'print',
               [('call',
                 'grad',
                 [('call', 'V_after', [('var', 'R0')]), ('var', 'R0')])]),
              0)]}
