EXPECTED = {'functions': {'dft': {'params': [('x', ('tensor', [('m', 'invariant')]))],
                       'return_type': ('tensor', [('m', 'invariant')]),
                       'body': ('var', 'coeffs'),
                       'has_loop': False,
                       'statements': [('body_decl',
                                       's',
                                       'ℝ',
                                       ('call', 'len', [('var', 'x')])),
                                      ('body_decl',
                                       'coeffs',
                                       ('tensor', [('s', 'invariant')]),
                                       ('for_expr',
                                        'k',
                                        ('var', 's'),
                                        ('call',
                                         'sum',
                                         [('for_expr',
                                           'n',
                                           ('var', 's'),
                                           ('mul',
                                            ('index', 'x', ('var', 'n')),
                                            ('sub',
                                             ('call',
                                              'cos',
                                              [('div',
                                                ('mul',
                                                 ('mul',
                                                  ('mul',
                                                   ('num', 2),
                                                   ('var', 'π')),
                                                  ('var', 'k')),
                                                 ('var', 'n')),
                                                ('var', 's'))]),
                                             ('mul',
                                              ('complex', 1j),
                                              ('call',
                                               'sin',
                                               [('div',
                                                 ('mul',
                                                  ('mul',
                                                   ('mul',
                                                    ('num', 2),
                                                    ('var', 'π')),
                                                   ('var', 'k')),
                                                  ('var', 'n')),
                                                 ('var', 's'))])))))])))]},
               'idft': {'params': [('X', ('tensor', [('m', 'invariant')]))],
                        'return_type': ('tensor', [('m', 'invariant')]),
                        'body': ('var', 'samples'),
                        'has_loop': False,
                        'statements': [('body_decl',
                                        's',
                                        'ℝ',
                                        ('call', 'len', [('var', 'X')])),
                                       ('body_decl',
                                        'samples',
                                        ('tensor', [('s', 'invariant')]),
                                        ('for_expr',
                                         'n',
                                         ('var', 's'),
                                         ('div',
                                          ('call',
                                           'sum',
                                           [('for_expr',
                                             'k',
                                             ('var', 's'),
                                             ('mul',
                                              ('index', 'X', ('var', 'k')),
                                              ('add',
                                               ('call',
                                                'cos',
                                                [('div',
                                                  ('mul',
                                                   ('mul',
                                                    ('mul',
                                                     ('num', 2),
                                                     ('var', 'π')),
                                                    ('var', 'k')),
                                                   ('var', 'n')),
                                                  ('var', 's'))]),
                                               ('mul',
                                                ('complex', 1j),
                                                ('call',
                                                 'sin',
                                                 [('div',
                                                   ('mul',
                                                    ('mul',
                                                     ('mul',
                                                      ('num', 2),
                                                      ('var', 'π')),
                                                     ('var', 'k')),
                                                    ('var', 'n')),
                                                   ('var', 's'))])))))]),
                                          ('var', 's'))))]},
               'ct_fft': {'params': [('x', ('tensor', [('m', 'invariant')])),
                                     ('s', 'ℝ')],
                          'return_type': ('tensor', [('m', 'invariant')]),
                          'body': ('call',
                                   'concat',
                                   [('var', 'first_half'),
                                    ('var', 'second_half')]),
                          'has_loop': False,
                          'statements': [('body_if_return',
                                          ('cond_eq',
                                           ('var', 's'),
                                           ('num', 1.0)),
                                          ('var', 'x')),
                                         ('body_decl',
                                          'half_size',
                                          'ℝ',
                                          ('div', ('var', 's'), ('num', 2))),
                                         ('body_decl',
                                          'even',
                                          ('tensor',
                                           [('half_size', 'invariant')]),
                                          ('for_expr',
                                           'a',
                                           ('var', 'half_size'),
                                           ('index',
                                            'x',
                                            ('mul',
                                             ('num', 2),
                                             ('var', 'a'))))),
                                         ('body_decl',
                                          'odd',
                                          ('tensor',
                                           [('half_size', 'invariant')]),
                                          ('for_expr',
                                           'a',
                                           ('var', 'half_size'),
                                           ('index',
                                            'x',
                                            ('add',
                                             ('mul', ('num', 2), ('var', 'a')),
                                             ('num', 1))))),
                                         ('body_decl',
                                          'E',
                                          ('tensor',
                                           [('half_size', 'invariant')]),
                                          ('call',
                                           'ct_fft',
                                           [('var', 'even'),
                                            ('var', 'half_size')])),
                                         ('body_decl',
                                          'O',
                                          ('tensor',
                                           [('half_size', 'invariant')]),
                                          ('call',
                                           'ct_fft',
                                           [('var', 'odd'),
                                            ('var', 'half_size')])),
                                         ('body_decl',
                                          'twiddle',
                                          ('tensor',
                                           [('half_size', 'invariant')]),
                                          ('for_expr',
                                           'k',
                                           ('var', 'half_size'),
                                           ('sub',
                                            ('call',
                                             'cos',
                                             [('div',
                                               ('mul',
                                                ('mul',
                                                 ('num', 2),
                                                 ('var', 'π')),
                                                ('var', 'k')),
                                               ('var', 's'))]),
                                            ('mul',
                                             ('complex', 1j),
                                             ('call',
                                              'sin',
                                              [('div',
                                                ('mul',
                                                 ('mul',
                                                  ('num', 2),
                                                  ('var', 'π')),
                                                 ('var', 'k')),
                                                ('var', 's'))]))))),
                                         ('body_decl',
                                          'first_half',
                                          ('tensor',
                                           [('half_size', 'invariant')]),
                                          ('for_expr',
                                           'k',
                                           ('var', 'half_size'),
                                           ('add',
                                            ('index', 'E', ('var', 'k')),
                                            ('mul',
                                             ('index',
                                              'twiddle',
                                              ('var', 'k')),
                                             ('index', 'O', ('var', 'k')))))),
                                         ('body_decl',
                                          'second_half',
                                          ('tensor',
                                           [('half_size', 'invariant')]),
                                          ('for_expr',
                                           'k',
                                           ('var', 'half_size'),
                                           ('sub',
                                            ('index', 'E', ('var', 'k')),
                                            ('mul',
                                             ('index',
                                              'twiddle',
                                              ('var', 'k')),
                                             ('index',
                                              'O',
                                              ('var', 'k'))))))]},
               'ict_fft': {'params': [('X', ('tensor', [('m', 'invariant')])),
                                      ('total_size', 'ℝ')],
                           'return_type': ('tensor', [('m', 'invariant')]),
                           'body': ('var', 'combined'),
                           'has_loop': False,
                           'statements': [('body_decl',
                                           's',
                                           'ℝ',
                                           ('call', 'len', [('var', 'X')])),
                                          ('body_if_return',
                                           ('cond_eq',
                                            ('var', 's'),
                                            ('num', 1.0)),
                                           ('var', 'X')),
                                          ('body_decl',
                                           'half_size',
                                           'ℝ',
                                           ('div', ('var', 's'), ('num', 2))),
                                          ('body_decl',
                                           'even',
                                           ('tensor',
                                            [('half_size', 'invariant')]),
                                           ('for_expr',
                                            'a',
                                            ('var', 'half_size'),
                                            ('index',
                                             'X',
                                             ('mul',
                                              ('num', 2),
                                              ('var', 'a'))))),
                                          ('body_decl',
                                           'odd',
                                           ('tensor',
                                            [('half_size', 'invariant')]),
                                           ('for_expr',
                                            'a',
                                            ('var', 'half_size'),
                                            ('index',
                                             'X',
                                             ('add',
                                              ('mul',
                                               ('num', 2),
                                               ('var', 'a')),
                                              ('num', 1))))),
                                          ('body_decl',
                                           'E',
                                           ('tensor',
                                            [('half_size', 'invariant')]),
                                           ('call',
                                            'ict_fft',
                                            [('var', 'even'),
                                             ('var', 'total_size')])),
                                          ('body_decl',
                                           'O',
                                           ('tensor',
                                            [('half_size', 'invariant')]),
                                           ('call',
                                            'ict_fft',
                                            [('var', 'odd'),
                                             ('var', 'total_size')])),
                                          ('body_decl',
                                           'inv_twiddle',
                                           ('tensor',
                                            [('half_size', 'invariant')]),
                                           ('for_expr',
                                            'k',
                                            ('var', 'half_size'),
                                            ('add',
                                             ('call',
                                              'cos',
                                              [('div',
                                                ('mul',
                                                 ('mul',
                                                  ('num', 2),
                                                  ('var', 'π')),
                                                 ('var', 'k')),
                                                ('var', 's'))]),
                                             ('mul',
                                              ('complex', 1j),
                                              ('call',
                                               'sin',
                                               [('div',
                                                 ('mul',
                                                  ('mul',
                                                   ('num', 2),
                                                   ('var', 'π')),
                                                  ('var', 'k')),
                                                 ('var', 's'))]))))),
                                          ('body_decl',
                                           'first_half',
                                           ('tensor',
                                            [('half_size', 'invariant')]),
                                           ('for_expr',
                                            'k',
                                            ('var', 'half_size'),
                                            ('add',
                                             ('index', 'E', ('var', 'k')),
                                             ('mul',
                                              ('index',
                                               'inv_twiddle',
                                               ('var', 'k')),
                                              ('index', 'O', ('var', 'k')))))),
                                          ('body_decl',
                                           'second_half',
                                           ('tensor',
                                            [('half_size', 'invariant')]),
                                           ('for_expr',
                                            'k',
                                            ('var', 'half_size'),
                                            ('sub',
                                             ('index', 'E', ('var', 'k')),
                                             ('mul',
                                              ('index',
                                               'inv_twiddle',
                                               ('var', 'k')),
                                              ('index', 'O', ('var', 'k')))))),
                                          ('body_decl',
                                           'combined',
                                           ('tensor', [('s', 'invariant')]),
                                           ('call',
                                            'concat',
                                            [('var', 'first_half'),
                                             ('var', 'second_half')])),
                                          ('body_if_return',
                                           ('cond_eq',
                                            ('var', 's'),
                                            ('var', 'total_size')),
                                           ('div',
                                            ('var', 'combined'),
                                            ('var', 'total_size')))]}},
 'classes': {},
 'program': [('decl', 'π', 'ℝ', ('num', 3.141592653589793), 9),
             ('func_def', 'dft'),
             ('func_def', 'idft'),
             ('func_def', 'ct_fft'),
             ('func_def', 'ict_fft'),
             ('decl',
              'signal',
              ('tensor', [(4, 'invariant')]),
              ('for_expr',
               'n',
               ('num', 4),
               ('call',
                'cos',
                [('div',
                  ('mul', ('mul', ('num', 2), ('var', 'π')), ('var', 'n')),
                  ('num', 4))])),
              80),
             ('decl',
              'dft_spectrum',
              ('tensor', [(4, 'invariant')]),
              ('call', 'dft', [('var', 'signal')]),
              82),
             ('expr', ('var', 'dft_spectrum'), 0),
             ('expr', ('call', 'abs', [('var', 'dft_spectrum')]), 0),
             ('expr', ('call', 'idft', [('var', 'dft_spectrum')]), 0),
             ('decl',
              'fft_spectrum',
              ('tensor', [(4, 'invariant')]),
              ('call', 'ct_fft', [('var', 'signal'), ('num', 4)]),
              87),
             ('expr', ('var', 'fft_spectrum'), 0),
             ('expr', ('call', 'abs', [('var', 'fft_spectrum')]), 0),
             ('expr',
              ('call', 'ict_fft', [('var', 'fft_spectrum'), ('num', 4)]),
              0),
             ('expr', ('call', 'dft', [('var', 'signal')]), 0),
             ('expr', ('call', 'ct_fft', [('var', 'signal'), ('num', 4)]), 0),
             ('expr', ('call', 'fft', [('var', 'signal')]), 0),
             ('decl', 'Ns', 'ℕ', ('num', 9), 103),
             ('decl', 'center', 'ℝ', ('num', 4.0), 104),
             ('decl',
              'signal_1d',
              ('tensor', [('Ns', 'invariant')]),
              ('for_expr',
               'n',
               ('var', 'Ns'),
               ('add',
                ('call',
                 'cos',
                 [('div',
                   ('mul',
                    ('mul', ('num', 2), ('var', 'π')),
                    ('sub', ('var', 'n'), ('var', 'center'))),
                   ('var', 'Ns'))]),
                ('mul',
                 ('num', 0.5),
                 ('call',
                  'cos',
                  [('div',
                    ('mul',
                     ('mul', ('mul', ('num', 2), ('var', 'π')), ('num', 3)),
                     ('sub', ('var', 'n'), ('var', 'center'))),
                    ('var', 'Ns'))])))),
              106),
             ('decl',
              'spectrum_1d',
              ('tensor', [('Ns', 'invariant')]),
              ('call', 'fft', [('var', 'signal_1d')]),
              107),
             ('expr', ('call', 'abs', [('var', 'spectrum_1d')]), 0),
             ('expr', ('call', 'ifft', [('var', 'spectrum_1d')]), 0),
             ('decl',
              'matrix',
              ('tensor', [(3, 'invariant'), (3, 'invariant')]),
              ('array',
               [('array', [('num', 1), ('num', 2), ('num', 3)]),
                ('array', [('num', 4), ('num', 5), ('num', 6)]),
                ('array', [('num', 7), ('num', 8), ('num', 9)])]),
              112),
             ('decl',
              'spectrum_2d',
              ('tensor', [(3, 'invariant'), (3, 'invariant')]),
              ('call', 'fft2', [('var', 'matrix')]),
              113),
             ('expr', ('var', 'spectrum_2d'), 0),
             ('expr', ('call', 'ifft2', [('var', 'spectrum_2d')]), 0),
             ('decl',
              'tensor',
              ('tensor',
               [(2, 'invariant'), (2, 'invariant'), (2, 'invariant')]),
              ('array',
               [('array',
                 [('array', [('num', 1), ('num', 2)]),
                  ('array', [('num', 3), ('num', 4)])]),
                ('array',
                 [('array', [('num', 5), ('num', 6)]),
                  ('array', [('num', 7), ('num', 8)])])]),
              118),
             ('decl',
              'spectrum_Nd',
              ('tensor',
               [(2, 'invariant'), (2, 'invariant'), (2, 'invariant')]),
              ('call', 'fftn', [('var', 'tensor')]),
              119),
             ('expr', ('var', 'spectrum_Nd'), 0),
             ('expr', ('call', 'ifftn', [('var', 'spectrum_Nd')]), 0),
             ('decl',
              'x',
              ('tensor', [(4, 'invariant')]),
              ('array',
               [('num', 1.0), ('num', 2.0), ('num', 3.0), ('num', 4.0)]),
              128),
             ('decl',
              'X',
              ('tensor', [(4, 'invariant')]),
              ('call', 'fft', [('var', 'x')]),
              130),
             ('expr', ('var', 'X'), 0),
             ('decl',
              'y',
              'ℝ',
              ('call', 'real', [('index', 'X', ('num', 1))]),
              133),
             ('expr', ('var', 'y'), 0),
             ('expr', ('call', 'grad', [('var', 'y'), ('var', 'x')]), 0),
             ('decl',
              'dft_spectrum',
              ('tensor', [(4, 'invariant')]),
              ('call', 'dft', [('var', 'x')]),
              138),
             ('decl',
              'dft_coeff',
              'ℝ',
              ('call', 'real', [('index', 'dft_spectrum', ('num', 1))]),
              139),
             ('expr',
              ('call', 'grad', [('var', 'dft_coeff'), ('var', 'x')]),
              0),
             ('decl',
              'ct_fft_spectrum',
              ('tensor', [(4, 'invariant')]),
              ('call', 'ct_fft', [('var', 'x'), ('num', 4)]),
              142),
             ('decl',
              'ct_fft_coeff',
              'ℝ',
              ('call', 'real', [('index', 'ct_fft_spectrum', ('num', 1))]),
              143),
             ('expr',
              ('call', 'grad', [('var', 'ct_fft_coeff'), ('var', 'x')]),
              0),
             ('decl',
              'inv_signal',
              ('tensor', [(4, 'invariant')]),
              ('call', 'ifft', [('var', 'X')]),
              147),
             ('decl',
              'inv_sample',
              'ℝ',
              ('call', 'real', [('index', 'inv_signal', ('num', 1))]),
              148),
             ('expr', ('var', 'inv_sample'), 0),
             ('expr',
              ('call', 'grad', [('var', 'inv_sample'), ('var', 'x')]),
              0),
             ('decl',
              'x2',
              ('tensor', [(8, 'invariant')]),
              ('array',
               [('num', 1.0),
                ('num', 2.0),
                ('num', 3.0),
                ('num', 4.0),
                ('num', 5.0),
                ('num', 6.0),
                ('num', 7.0),
                ('num', 8.0)]),
              154),
             ('decl',
              'X2',
              ('tensor', [(8, 'invariant')]),
              ('call', 'fft', [('var', 'x2')]),
              155),
             ('decl',
              'energy_time',
              'ℝ',
              ('call', 'sum', [('pow', ('var', 'x2'), ('num', 2))]),
              157),
             ('decl',
              'energy_freq',
              'ℝ',
              ('div',
               ('call',
                'sum',
                [('pow', ('call', 'abs', [('var', 'X2')]), ('num', 2))]),
               ('call', 'len', [('var', 'x2')])),
              158),
             ('expr', ('var', 'energy_time'), 0),
             ('expr', ('var', 'energy_freq'), 0),
             ('expr',
              ('call', 'grad', [('var', 'energy_time'), ('var', 'x2')]),
              0),
             ('expr',
              ('call', 'grad', [('var', 'energy_freq'), ('var', 'x2')]),
              0)]}
