EXPECTED = {'functions': {'zero_1d_array': {'params': [('len', 'ℝ')],
                                 'return_type': ('tensor',
                                                 [('m', 'invariant')]),
                                 'body': ('var', 'results'),
                                 'has_loop': False,
                                 'statements': [('body_decl',
                                                 'results',
                                                 ('tensor',
                                                  [('len', 'invariant')]),
                                                 ('for_expr',
                                                  'i',
                                                  ('var', 'len'),
                                                  ('mul',
                                                   ('imaginary',),
                                                   ('num', 0))))]},
               'get_1d_array_length': {'params': [('x',
                                                   ('tensor',
                                                    [('m', 'invariant')]))],
                                       'return_type': 'ℝ',
                                       'body': ('var', 'total'),
                                       'has_loop': False,
                                       'statements': [('body_decl',
                                                       'total',
                                                       'ℝ',
                                                       ('num', 0)),
                                                      ('body_decl',
                                                       'temp',
                                                       'ℝ',
                                                       ('num', 0)),
                                                      ('body_for',
                                                       'i',
                                                       [('loop_assign',
                                                         'temp',
                                                         ('index',
                                                          'x',
                                                          ('imaginary',))),
                                                        ('loop_pluseq',
                                                         'total',
                                                         ('num', 1))],
                                                       ['x'])]},
               'append': {'params': [('x', ('tensor', [('m', 'invariant')])),
                                     ('var', 'ℝ')],
                          'return_type': ('tensor', [('n', 'invariant')]),
                          'body': ('var', 'results'),
                          'has_loop': False,
                          'statements': [('body_decl',
                                          'new_length',
                                          'ℝ',
                                          ('add',
                                           ('call', 'len', [('var', 'x')]),
                                           ('num', 1))),
                                         ('body_decl',
                                          'results',
                                          ('tensor',
                                           [('new_length', 'invariant')]),
                                          ('call',
                                           'zero_1d_array',
                                           [('var', 'new_length')])),
                                         ('body_decl',
                                          'len_x',
                                          'ℕ',
                                          ('call',
                                           'get_1d_array_length',
                                           [('var', 'x')])),
                                         ('body_for_range',
                                          'i',
                                          ('num', 0),
                                          ('var', 'new_length'),
                                          [('loop_if_else',
                                            ('cond_lt',
                                             ('imaginary',),
                                             ('var', 'len_x')),
                                            [('loop_index_assign_nd',
                                              'results',
                                              [('index_item', ('imaginary',))],
                                              ('index', 'x', ('imaginary',)))],
                                            [('loop_index_assign_nd',
                                              'results',
                                              [('index_item', ('imaginary',))],
                                              ('var', 'var'))])])]},
               'f': {'params': [('state', ('tensor', [(2, 'invariant')])),
                                ('θ', ('tensor', [(4, 'invariant')]))],
                     'return_type': ('tensor', [(2, 'invariant')]),
                     'body': ('array', [('var', 'dv'), ('var', 'dw')]),
                     'has_loop': False,
                     'statements': [('body_decl',
                                     'v',
                                     'ℝ',
                                     ('index', 'state', ('num', 0))),
                                    ('body_decl',
                                     'w',
                                     'ℝ',
                                     ('index', 'state', ('num', 1))),
                                    ('body_decl',
                                     'a',
                                     'ℝ',
                                     ('index', 'θ', ('num', 0))),
                                    ('body_decl',
                                     'b',
                                     'ℝ',
                                     ('index', 'θ', ('num', 1))),
                                    ('body_decl',
                                     'eps',
                                     'ℝ',
                                     ('index', 'θ', ('num', 2))),
                                    ('body_decl',
                                     'Iext',
                                     'ℝ',
                                     ('index', 'θ', ('num', 3))),
                                    ('body_decl',
                                     'dv',
                                     'ℝ',
                                     ('add',
                                      ('sub',
                                       ('sub',
                                        ('var', 'v'),
                                        ('div',
                                         ('pow', ('var', 'v'), ('num', 3)),
                                         ('num', 3.0))),
                                       ('var', 'w')),
                                      ('var', 'Iext'))),
                                    ('body_decl',
                                     'dw',
                                     'ℝ',
                                     ('mul',
                                      ('var', 'eps'),
                                      ('sub',
                                       ('add', ('var', 'v'), ('var', 'a')),
                                       ('mul', ('var', 'b'), ('var', 'w')))))]},
               'rk4_step': {'params': [('state',
                                        ('tensor', [(2, 'invariant')])),
                                       ('θ', ('tensor', [(4, 'invariant')]))],
                            'return_type': ('tensor', [(2, 'invariant')]),
                            'body': ('add',
                                     ('var', 'state'),
                                     ('mul',
                                      ('div', ('var', 'dt'), ('num', 6.0)),
                                      ('add',
                                       ('add',
                                        ('add',
                                         ('var', 'k1'),
                                         ('mul', ('num', 2.0), ('var', 'k2'))),
                                        ('mul', ('num', 2.0), ('var', 'k3'))),
                                       ('var', 'k4')))),
                            'has_loop': False,
                            'statements': [('body_decl',
                                            'k1',
                                            ('tensor', [(2, 'invariant')]),
                                            ('call',
                                             'f',
                                             [('var', 'state'), ('var', 'θ')])),
                                           ('body_decl',
                                            'k2_state',
                                            ('tensor', [(2, 'invariant')]),
                                            ('add',
                                             ('var', 'state'),
                                             ('mul',
                                              ('mul',
                                               ('num', 0.5),
                                               ('var', 'dt')),
                                              ('var', 'k1')))),
                                           ('body_decl',
                                            'k2',
                                            ('tensor', [(2, 'invariant')]),
                                            ('call',
                                             'f',
                                             [('var', 'k2_state'),
                                              ('var', 'θ')])),
                                           ('body_decl',
                                            'k3_state',
                                            ('tensor', [(2, 'invariant')]),
                                            ('add',
                                             ('var', 'state'),
                                             ('mul',
                                              ('mul',
                                               ('num', 0.5),
                                               ('var', 'dt')),
                                              ('var', 'k2')))),
                                           ('body_decl',
                                            'k3',
                                            ('tensor', [(2, 'invariant')]),
                                            ('call',
                                             'f',
                                             [('var', 'k3_state'),
                                              ('var', 'θ')])),
                                           ('body_decl',
                                            'k4_state',
                                            ('tensor', [(2, 'invariant')]),
                                            ('add',
                                             ('var', 'state'),
                                             ('mul',
                                              ('var', 'dt'),
                                              ('var', 'k3')))),
                                           ('body_decl',
                                            'k4',
                                            ('tensor', [(2, 'invariant')]),
                                            ('call',
                                             'f',
                                             [('var', 'k4_state'),
                                              ('var', 'θ')]))]},
               'solver': {'params': [('θ', ('tensor', [(4, 'invariant')]))],
                          'return_type': ('tensor',
                                          [(2, 'invariant'),
                                           ('m', 'invariant')]),
                          'body': ('array',
                                   [('var', 'v_array'), ('var', 'w_array')]),
                          'has_loop': False,
                          'statements': [('body_decl',
                                          'state',
                                          ('tensor', [(2, 'invariant')]),
                                          ('array',
                                           [('neg', ('num', 1.0)),
                                            ('num', 1.0)])),
                                         ('body_decl',
                                          'v_array',
                                          ('tensor', [(1, 'invariant')]),
                                          ('array', [('neg', ('num', 1.0))])),
                                         ('body_decl',
                                          'w_array',
                                          ('tensor', [(1, 'invariant')]),
                                          ('array', [('num', 1.0)])),
                                         ('body_for_range',
                                          'i',
                                          ('num', 0),
                                          ('var', 'timesteps'),
                                          [('loop_assign',
                                            'results',
                                            ('call',
                                             'rk4_step',
                                             [('var', 'state'), ('var', 'θ')])),
                                           ('loop_assign',
                                            'v',
                                            ('index', 'results', ('num', 0))),
                                           ('loop_assign',
                                            'w',
                                            ('index', 'results', ('num', 1))),
                                           ('loop_assign',
                                            'v_array',
                                            ('call',
                                             'append',
                                             [('var', 'v_array'),
                                              ('var', 'v')])),
                                           ('loop_assign',
                                            'w_array',
                                            ('call',
                                             'append',
                                             [('var', 'w_array'),
                                              ('var', 'w')])),
                                           ('loop_assign',
                                            'state',
                                            ('var', 'results'))])]},
               'adjoint_grad': {'params': [('θ',
                                            ('tensor', [(4, 'invariant')]))],
                                'return_type': ('tensor', [('n', 'invariant')]),
                                'body': ('var', 'L'),
                                'has_loop': False,
                                'statements': [('body_decl',
                                                'states',
                                                ('tensor',
                                                 [(2, 'invariant'),
                                                  ('m', 'invariant')]),
                                                ('call',
                                                 'solver',
                                                 [('var', 'θ')])),
                                               ('body_decl',
                                                'v_array',
                                                ('tensor',
                                                 [('m', 'invariant')]),
                                                ('index',
                                                 'states',
                                                 ('num', 0))),
                                               ('body_decl',
                                                'w_array',
                                                ('tensor',
                                                 [('m', 'invariant')]),
                                                ('index',
                                                 'states',
                                                 ('num', 1))),
                                               ('body_decl',
                                                'm',
                                                'ℝ',
                                                ('call',
                                                 'get_1d_array_length',
                                                 [('var', 'v_array')])),
                                               ('body_decl',
                                                's',
                                                ('tensor', [(2, 'invariant')]),
                                                ('array',
                                                 [('div',
                                                   ('sub',
                                                    ('index',
                                                     'v_array',
                                                     ('sub',
                                                      ('var', 'm'),
                                                      ('num', 1))),
                                                    ('index',
                                                     'true_v',
                                                     ('sub',
                                                      ('var', 'm'),
                                                      ('num', 1)))),
                                                   ('var', 'm')),
                                                  ('div',
                                                   ('sub',
                                                    ('index',
                                                     'w_array',
                                                     ('sub',
                                                      ('var', 'm'),
                                                      ('num', 1))),
                                                    ('index',
                                                     'true_w',
                                                     ('sub',
                                                      ('var', 'm'),
                                                      ('num', 1)))),
                                                   ('var', 'm'))])),
                                               ('body_decl',
                                                'L',
                                                ('tensor', [(4, 'invariant')]),
                                                ('call',
                                                 'zero_1d_array',
                                                 [('num', 4)])),
                                               ('body_for_range',
                                                'i',
                                                ('num', 0),
                                                ('sub',
                                                 ('var', 'm'),
                                                 ('num', 1)),
                                                [('loop_assign',
                                                  'idx',
                                                  ('sub',
                                                   ('sub',
                                                    ('var', 'm'),
                                                    ('num', 2)),
                                                   ('imaginary',))),
                                                 ('loop_assign',
                                                  'v',
                                                  ('index',
                                                   'v_array',
                                                   ('var', 'idx'))),
                                                 ('loop_assign',
                                                  'w',
                                                  ('index',
                                                   'w_array',
                                                   ('var', 'idx'))),
                                                 ('loop_assign',
                                                  'state',
                                                  ('array',
                                                   [('var', 'v'),
                                                    ('var', 'w')])),
                                                 ('loop_assign',
                                                  'J_state',
                                                  ('call',
                                                   'grad',
                                                   [('call',
                                                     'rk4_step',
                                                     [('var', 'state'),
                                                      ('var', 'θ')]),
                                                    ('var', 'state')])),
                                                 ('loop_assign',
                                                  'J_theta',
                                                  ('call',
                                                   'grad',
                                                   [('call',
                                                     'rk4_step',
                                                     [('var', 'state'),
                                                      ('var', 'θ')]),
                                                    ('var', 'θ')])),
                                                 ('loop_pluseq',
                                                  'L',
                                                  ('matmul',
                                                   ('var', 's'),
                                                   ('var', 'J_theta'))),
                                                 ('loop_assign',
                                                  'rv',
                                                  ('div',
                                                   ('sub',
                                                    ('index',
                                                     'v_array',
                                                     ('var', 'idx')),
                                                    ('index',
                                                     'true_v',
                                                     ('var', 'idx'))),
                                                   ('var', 'm'))),
                                                 ('loop_assign',
                                                  'rw',
                                                  ('div',
                                                   ('sub',
                                                    ('index',
                                                     'w_array',
                                                     ('var', 'idx')),
                                                    ('index',
                                                     'true_w',
                                                     ('var', 'idx'))),
                                                   ('var', 'm'))),
                                                 ('loop_assign',
                                                  'residual',
                                                  ('array',
                                                   [('var', 'rv'),
                                                    ('var', 'rw')])),
                                                 ('loop_assign',
                                                  's',
                                                  ('add',
                                                   ('var', 'residual'),
                                                   ('matmul',
                                                    ('var', 's'),
                                                    ('var', 'J_state'))))])]}},
 'classes': {},
 'program': [('func_def', 'zero_1d_array'),
             ('func_def', 'get_1d_array_length'),
             ('func_def', 'append'),
             ('func_def', 'f'),
             ('func_def', 'rk4_step'),
             ('decl', 'dt', 'ℝ', ('num', 0.1), 63),
             ('decl', 'timesteps', 'ℝ', ('num', 200), 64),
             ('func_def', 'solver'),
             ('decl',
              'true_theta',
              ('tensor', [(4, 'invariant')]),
              ('array',
               [('num', 0.7), ('num', 0.8), ('num', 0.08), ('num', 0.5)]),
              79),
             ('decl',
              'true_results',
              ('tensor', [(2, 'invariant'), ('m', 'invariant')]),
              ('call', 'solver', [('var', 'true_theta')]),
              80),
             ('decl',
              'true_v',
              ('tensor', [('m', 'invariant')]),
              ('index', 'true_results', ('num', 0)),
              81),
             ('decl',
              'true_w',
              ('tensor', [('m', 'invariant')]),
              ('index', 'true_results', ('num', 1)),
              82),
             ('func_def', 'adjoint_grad'),
             ('decl',
              'θ',
              ('tensor', [(4, 'invariant')]),
              ('array',
               [('num', 0.6), ('num', 0.7), ('num', 0.1), ('num', 0.6)]),
              108),
             ('decl', 'learning_rate', 'ℝ', ('num', 0.003), 109),
             ('decl', 'epochs', 'ℕ', ('num', 1), 115),
             ('for_loop_range',
              'i',
              ('num', 0),
              ('var', 'epochs'),
              [('for_assign', 'g', ('call', 'adjoint_grad', [('var', 'θ')])),
               ('for_assign',
                'θ',
                ('sub',
                 ('var', 'θ'),
                 ('mul', ('var', 'learning_rate'), ('var', 'g'))))],
              117),
             ('assign',
              'pred_results',
              ('call', 'solver', [('var', 'θ')]),
              121)]}
