EXPECTED = {'functions': {'get_1d_array_length': {'params': [('x',
                                                   ('tensor',
                                                    [('m', 'invariant')]))],
                                       'return_type': 'ℝ',
                                       'body': ('var', 'total'),
                                       'has_loop': False,
                                       'statements': [('body_decl',
                                                       'total',
                                                       'ℝ',
                                                       ('num', 0)),
                                                      ('body_decl',
                                                       'temp',
                                                       'ℝ',
                                                       ('num', 0)),
                                                      ('body_for',
                                                       'i',
                                                       [('loop_assign',
                                                         'temp',
                                                         ('index',
                                                          'x',
                                                          ('imaginary',))),
                                                        ('loop_pluseq',
                                                         'total',
                                                         ('num', 1))],
                                                       ['x'])]},
               'get_2d_array_num_rows': {'params': [('x',
                                                     ('tensor',
                                                      [('m', 'invariant'),
                                                       ('n', 'invariant')]))],
                                         'return_type': 'ℝ',
                                         'body': ('var', 'total'),
                                         'has_loop': False,
                                         'statements': [('body_decl',
                                                         'total',
                                                         'ℝ',
                                                         ('num', 0)),
                                                        ('body_decl',
                                                         'temp',
                                                         'ℝ',
                                                         ('num', 0)),
                                                        ('body_for',
                                                         'i',
                                                         [('loop_assign',
                                                           'temp',
                                                           ('index',
                                                            'x',
                                                            ('imaginary',))),
                                                          ('loop_pluseq',
                                                           'total',
                                                           ('num', 1))],
                                                         ['x'])]},
               'zero_1d_array': {'params': [('len', 'ℝ')],
                                 'return_type': ('tensor',
                                                 [('m', 'invariant')]),
                                 'body': ('var', 'results'),
                                 'has_loop': False,
                                 'statements': [('body_decl',
                                                 'results',
                                                 ('tensor',
                                                  [('len', 'invariant')]),
                                                 ('for_expr',
                                                  'i',
                                                  ('var', 'len'),
                                                  ('mul',
                                                   ('imaginary',),
                                                   ('num', 0))))]},
               'zero_2d_array': {'params': [('rows', 'ℝ'), ('cols', 'ℝ')],
                                 'return_type': ('tensor',
                                                 [('m', 'invariant'),
                                                  ('n', 'invariant')]),
                                 'body': ('var', 'results'),
                                 'has_loop': False,
                                 'statements': [('body_decl',
                                                 'results',
                                                 ('tensor',
                                                  [('rows', 'invariant'),
                                                   ('cols', 'invariant')]),
                                                 ('for_expr',
                                                  'i',
                                                  ('var', 'rows'),
                                                  ('for_expr',
                                                   'j',
                                                   ('var', 'cols'),
                                                   ('mul',
                                                    ('var', 'j'),
                                                    ('num', 0)))))]},
               'zero_3d_A': {'params': [('n', 'ℝ')],
                             'return_type': ('tensor',
                                             [('m', 'invariant'),
                                              (44, 'invariant'),
                                              (44, 'invariant')]),
                             'body': ('var', 'results'),
                             'has_loop': False,
                             'statements': [('body_decl',
                                             'results',
                                             ('tensor',
                                              [('n', 'invariant'),
                                               (44, 'invariant'),
                                               (44, 'invariant')]),
                                             ('for_expr',
                                              'i',
                                              ('var', 'n'),
                                              ('for_expr',
                                               'j',
                                               ('num', 44),
                                               ('for_expr',
                                                'k',
                                                ('num', 44),
                                                ('mul',
                                                 ('var', 'k'),
                                                 ('num', 0))))))]},
               'zero_3d_H': {'params': [('n', 'ℝ')],
                             'return_type': ('tensor',
                                             [('m', 'invariant'),
                                              (44, 'invariant'),
                                              (30, 'invariant')]),
                             'body': ('var', 'results'),
                             'has_loop': False,
                             'statements': [('body_decl',
                                             'results',
                                             ('tensor',
                                              [('n', 'invariant'),
                                               (44, 'invariant'),
                                               (30, 'invariant')]),
                                             ('for_expr',
                                              'i',
                                              ('var', 'n'),
                                              ('for_expr',
                                               'j',
                                               ('num', 44),
                                               ('for_expr',
                                                'k',
                                                ('num', 30),
                                                ('mul',
                                                 ('var', 'k'),
                                                 ('num', 0))))))]},
               'get_sum_of_1d_array': {'params': [('x',
                                                   ('tensor',
                                                    [('m', 'invariant')]))],
                                       'return_type': 'ℝ',
                                       'body': ('var', 'total'),
                                       'has_loop': False,
                                       'statements': [('body_decl',
                                                       'total',
                                                       'ℝ',
                                                       ('num', 0)),
                                                      ('body_for',
                                                       'i',
                                                       [('loop_pluseq',
                                                         'total',
                                                         ('index',
                                                          'x',
                                                          ('imaginary',)))],
                                                       ['x'])]},
               'diag_matrix': {'params': [('d',
                                           ('tensor', [('n', 'invariant')]))],
                               'return_type': ('tensor',
                                               [('n', 'invariant'),
                                                ('n', 'invariant')]),
                               'body': ('var', 'result'),
                               'has_loop': False,
                               'statements': [('body_decl',
                                               'sz',
                                               'ℝ',
                                               ('call',
                                                'get_1d_array_length',
                                                [('var', 'd')])),
                                              ('body_decl',
                                               'result',
                                               ('tensor',
                                                [('sz', 'invariant'),
                                                 ('sz', 'invariant')]),
                                               ('call',
                                                'zero_2d_array',
                                                [('var', 'sz'),
                                                 ('var', 'sz')])),
                                              ('body_for',
                                               'i',
                                               [('loop_index_assign_nd',
                                                 'result',
                                                 [('index_item',
                                                   ('imaginary',)),
                                                  ('index_item',
                                                   ('imaginary',))],
                                                 ('index',
                                                  'd',
                                                  ('imaginary',)))],
                                               ['d'])]},
               'ones_vector': {'params': [('n', 'ℝ')],
                               'return_type': ('tensor', [('n', 'invariant')]),
                               'body': ('for_expr',
                                        'i',
                                        ('var', 'n'),
                                        ('add',
                                         ('mul', ('num', 0.0), ('imaginary',)),
                                         ('num', 1.0))),
                               'has_loop': False,
                               'statements': []},
               'sigma': {'params': [('x',
                                     ('tensor',
                                      [('a', 'invariant'),
                                       ('b', 'invariant')]))],
                         'return_type': ('tensor',
                                         [('a', 'invariant'),
                                          ('b', 'invariant')]),
                         'body': ('div',
                                  ('num', 1.0),
                                  ('add',
                                   ('num', 1.0),
                                   ('call',
                                    'exp',
                                    [('sub', ('num', 0.0), ('var', 'x'))]))),
                         'has_loop': False,
                         'statements': []},
               'normalize_adj': {'params': [('A',
                                             ('tensor',
                                              [('n', 'invariant'),
                                               ('n', 'invariant')]))],
                                 'return_type': ('tensor',
                                                 [('n', 'invariant'),
                                                  ('n', 'invariant')]),
                                 'body': ('matmul',
                                          ('matmul',
                                           ('var', 'D'),
                                           ('var', 'A_plus')),
                                          ('var', 'D')),
                                 'has_loop': False,
                                 'statements': [('body_decl',
                                                 'sz',
                                                 'ℝ',
                                                 ('call',
                                                  'get_2d_array_num_rows',
                                                  [('var', 'A')])),
                                                ('body_decl',
                                                 'I',
                                                 ('tensor',
                                                  [('sz', 'invariant'),
                                                   ('sz', 'invariant')]),
                                                 ('call',
                                                  'diag_matrix',
                                                  [('call',
                                                    'ones_vector',
                                                    [('var', 'sz')])])),
                                                ('body_decl',
                                                 'A_plus',
                                                 ('tensor',
                                                  [('sz', 'invariant'),
                                                   ('sz', 'invariant')]),
                                                 ('add',
                                                  ('var', 'A'),
                                                  ('var', 'I'))),
                                                ('body_decl',
                                                 'deg',
                                                 ('tensor',
                                                  [('sz', 'invariant')]),
                                                 ('for_expr',
                                                  'i',
                                                  ('var', 'sz'),
                                                  ('call',
                                                   'get_sum_of_1d_array',
                                                   [('index',
                                                     'A_plus',
                                                     ('imaginary',))]))),
                                                ('body_decl',
                                                 'd_inv_sqrt',
                                                 ('tensor',
                                                  [('sz', 'invariant')]),
                                                 ('for_expr',
                                                  'i',
                                                  ('var', 'sz'),
                                                  ('div',
                                                   ('num', 1.0),
                                                   ('call',
                                                    'sqrt',
                                                    [('index',
                                                      'deg',
                                                      ('imaginary',))])))),
                                                ('body_decl',
                                                 'D',
                                                 ('tensor',
                                                  [('sz', 'invariant'),
                                                   ('sz', 'invariant')]),
                                                 ('call',
                                                  'diag_matrix',
                                                  [('var', 'd_inv_sqrt')]))]},
               'masked_graph_sum_pool': {'params': [('H',
                                                     ('tensor',
                                                      [('n', 'invariant'),
                                                       ('d', 'invariant')])),
                                                    ('sz', 'ℝ')],
                                         'return_type': ('tensor',
                                                         [('d', 'invariant')]),
                                         'body': ('var', 'result'),
                                         'has_loop': False,
                                         'statements': [('body_decl',
                                                         'cols',
                                                         'ℝ',
                                                         ('call',
                                                          'get_1d_array_length',
                                                          [('index',
                                                            'H',
                                                            ('num', 0))])),
                                                        ('body_decl',
                                                         'result',
                                                         ('tensor',
                                                          [('cols',
                                                            'invariant')]),
                                                         ('call',
                                                          'zero_1d_array',
                                                          [('var', 'cols')])),
                                                        ('body_for_range',
                                                         'i',
                                                         ('num', 0),
                                                         ('var', 'sz'),
                                                         [('loop_assign',
                                                           'row',
                                                           ('index',
                                                            'H',
                                                            ('imaginary',))),
                                                          ('loop_for_range',
                                                           'j',
                                                           ('num', 0),
                                                           ('var', 'cols'),
                                                           [('loop_index_pluseq',
                                                             'result',
                                                             [('index_item',
                                                               ('var', 'j'))],
                                                             ('index',
                                                              'row',
                                                              ('var',
                                                               'j')))])])]},
               'mse': {'params': [('pred', 'ℝ'), ('target', 'ℝ')],
                       'return_type': 'ℝ',
                       'body': ('pow',
                                ('sub', ('var', 'pred'), ('var', 'target')),
                                ('num', 2.0)),
                       'has_loop': False,
                       'statements': []},
               'within_tolerance': {'params': [('pred', 'ℝ'),
                                               ('target', 'ℝ'),
                                               ('tol', 'ℝ')],
                                    'return_type': 'ℝ',
                                    'body': None,
                                    'has_loop': False,
                                    'statements': [('body_decl',
                                                    'diff',
                                                    'ℝ',
                                                    ('sub',
                                                     ('var', 'pred'),
                                                     ('var', 'target'))),
                                                   ('body_if',
                                                    ('cond_lt',
                                                     ('var', 'diff'),
                                                     ('num', 0.0)),
                                                    [('body_assign',
                                                      'diff',
                                                      ('sub',
                                                       ('num', 0.0),
                                                       ('var', 'diff')))]),
                                                   ('body_if_else_return',
                                                    ('cond_lt',
                                                     ('var', 'diff'),
                                                     ('var', 'tol')),
                                                    ('num', 1.0),
                                                    ('num', 0.0))]}},
 'classes': {'GCNModel': {'class_params': [('W1',
                                            ('tensor',
                                             [(30, 'invariant'),
                                              (4, 'invariant')])),
                                           ('W2',
                                            ('tensor', [(4, 'invariant')]))],
                          'fields': [],
                          'methods': [{'name': 'λ',
                                       'params': [('A',
                                                   ('tensor',
                                                    [('n', 'invariant'),
                                                     ('n', 'invariant')])),
                                                  ('H',
                                                   ('tensor',
                                                    [('n', 'invariant'),
                                                     (30, 'invariant')])),
                                                  ('sz', 'ℝ')],
                                       'return_type': 'ℝ',
                                       'statements': [('body_decl',
                                                       'A_hat',
                                                       ('tensor',
                                                        [('n', 'invariant'),
                                                         ('n', 'invariant')]),
                                                       ('call',
                                                        'normalize_adj',
                                                        [('var', 'A')])),
                                                      ('body_decl',
                                                       'H1',
                                                       ('tensor',
                                                        [('n', 'invariant'),
                                                         (4, 'invariant')]),
                                                       ('call',
                                                        'sigma',
                                                        [('matmul',
                                                          ('var', 'A_hat'),
                                                          ('matmul',
                                                           ('var', 'H'),
                                                           ('field_access',
                                                            ('var', 'this'),
                                                            'W1')))])),
                                                      ('body_decl',
                                                       'pooled',
                                                       ('tensor',
                                                        [(4, 'invariant')]),
                                                       ('call',
                                                        'masked_graph_sum_pool',
                                                        [('var', 'H1'),
                                                         ('var', 'sz')])),
                                                      ('body_decl',
                                                       'pred',
                                                       'ℝ',
                                                       ('matmul',
                                                        ('var', 'pooled'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'W2')))],
                                       'body': ('var', 'pred')},
                                      {'name': 'train',
                                       'params': [('epochs', 'ℕ'), ('lr', 'ℝ')],
                                       'return_type': 'ℝ',
                                       'statements': [('body_decl',
                                                       'len_train_X',
                                                       'ℝ',
                                                       ('call',
                                                        'get_1d_array_length',
                                                        [('var',
                                                          'train_sizes')])),
                                                      ('body_decl',
                                                       'loss',
                                                       'ℝ',
                                                       ('num', 0)),
                                                      ('body_for_range',
                                                       'i',
                                                       ('num', 0),
                                                       ('var', 'epochs'),
                                                       [('loop_assign',
                                                         'loss',
                                                         ('num', 0)),
                                                        ('loop_for_range',
                                                         'j',
                                                         ('num', 0),
                                                         ('var', 'len_train_X'),
                                                         [('loop_assign',
                                                           'A_j',
                                                           ('index',
                                                            'train_A',
                                                            ('var', 'j'))),
                                                          ('loop_assign',
                                                           'H_j',
                                                           ('index',
                                                            'train_H',
                                                            ('var', 'j'))),
                                                          ('loop_assign',
                                                           'sz_j',
                                                           ('index',
                                                            'train_sizes',
                                                            ('var', 'j'))),
                                                          ('loop_assign',
                                                           'label',
                                                           ('index',
                                                            'train_y',
                                                            ('var', 'j'))),
                                                          ('loop_assign',
                                                           'z',
                                                           ('call',
                                                            'this',
                                                            [('var', 'A_j'),
                                                             ('var', 'H_j'),
                                                             ('var', 'sz_j')])),
                                                          ('loop_assign',
                                                           'current_loss',
                                                           ('call',
                                                            'mse',
                                                            [('var', 'z'),
                                                             ('var',
                                                              'label')])),
                                                          ('loop_pluseq',
                                                           'loss',
                                                           ('var',
                                                            'current_loss')),
                                                          ('loop_assign',
                                                           'learnable_grads',
                                                           ('call',
                                                            'grad',
                                                            [('var',
                                                              'current_loss'),
                                                             ('field_access',
                                                              ('var', 'this'),
                                                              'learnable_params')])),
                                                          ('body_expr',
                                                           ('method_call',
                                                            ('var', 'this'),
                                                            'update_params',
                                                            [('var', 'lr'),
                                                             ('var',
                                                              'learnable_grads')]))]),
                                                        ('loop_assign',
                                                         'loss',
                                                         ('div',
                                                          ('var', 'loss'),
                                                          ('var',
                                                           'len_train_X')))])],
                                       'body': ('var', 'loss')},
                                      {'name': 'evaluate',
                                       'params': [],
                                       'return_type': 'ℝ',
                                       'statements': [('body_decl',
                                                       'len_test_X',
                                                       'ℝ',
                                                       ('call',
                                                        'get_1d_array_length',
                                                        [('var',
                                                          'test_sizes')])),
                                                      ('body_decl',
                                                       'correct',
                                                       'ℝ',
                                                       ('num', 0)),
                                                      ('body_for_range',
                                                       'i',
                                                       ('num', 0),
                                                       ('var', 'len_test_X'),
                                                       [('loop_assign',
                                                         'A_i',
                                                         ('index',
                                                          'test_A',
                                                          ('imaginary',))),
                                                        ('loop_assign',
                                                         'H_i',
                                                         ('index',
                                                          'test_H',
                                                          ('imaginary',))),
                                                        ('loop_assign',
                                                         'sz_i',
                                                         ('index',
                                                          'test_sizes',
                                                          ('imaginary',))),
                                                        ('loop_assign',
                                                         'y_pred',
                                                         ('call',
                                                          'this',
                                                          [('var', 'A_i'),
                                                           ('var', 'H_i'),
                                                           ('var', 'sz_i')])),
                                                        ('loop_pluseq',
                                                         'correct',
                                                         ('call',
                                                          'within_tolerance',
                                                          [('var', 'y_pred'),
                                                           ('index',
                                                            'test_y',
                                                            ('imaginary',)),
                                                           ('num', 1.0)]))])],
                                       'body': ('div',
                                                ('var', 'correct'),
                                                ('var', 'len_test_X'))},
                                      {'name': 'update_params',
                                       'params': [('lr', 'ℝ'),
                                                  ('learnable_grads',
                                                   ('tensor',
                                                    [('m', 'invariant')]))],
                                       'return_type': None,
                                       'statements': [('body_field_assign',
                                                       ('var', 'this'),
                                                       'W1',
                                                       ('sub',
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'W1'),
                                                        ('mul',
                                                         ('var', 'lr'),
                                                         ('index',
                                                          'learnable_grads',
                                                          ('num', 0))))),
                                                      ('body_field_assign',
                                                       ('var', 'this'),
                                                       'W2',
                                                       ('sub',
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'W2'),
                                                        ('mul',
                                                         ('var', 'lr'),
                                                         ('index',
                                                          'learnable_grads',
                                                          ('num', 1)))))],
                                       'body': None}]}},
 'program': [('func_def', 'get_1d_array_length'),
             ('func_def', 'get_2d_array_num_rows'),
             ('func_def', 'zero_1d_array'),
             ('func_def', 'zero_2d_array'),
             ('func_def', 'zero_3d_A'),
             ('func_def', 'zero_3d_H'),
             ('func_def', 'get_sum_of_1d_array'),
             ('func_def', 'diag_matrix'),
             ('func_def', 'ones_vector'),
             ('func_def', 'sigma'),
             ('func_def', 'normalize_adj'),
             ('func_def', 'masked_graph_sum_pool'),
             ('func_def', 'mse'),
             ('func_def', 'within_tolerance'),
             ('class_def', 'GCNModel'),
             ('decl', 'μ', 'ℝ', ('num', 0.0), 122),
             ('decl', 'σ', 'ℝ', ('num', 1.0), 123),
             ('decl',
              'W1',
              ('tensor', [(30, 'invariant'), (4, 'invariant')]),
              ('for_expr',
               'i',
               ('num', 30),
               ('typed_sample_expr',
                'row',
                ('tensor', [(4, 'invariant')]),
                ('call', 'Normal', [('var', 'μ'), ('var', 'σ'), ('num', 4)]))),
              125),
             ('typed_sample',
              'W2',
              ('tensor', [(4, 'invariant')]),
              ('call', 'Normal', [('var', 'μ'), ('var', 'σ'), ('num', 4)]),
              126),
             ('decl',
              'gcn_object',
              ('struct_type', 'GCNModel'),
              ('call', 'GCNModel', [('var', 'W1'), ('var', 'W2')]),
              128),
             ('decl',
              'train_A',
              ('tensor',
               [(513, 'invariant'), (44, 'invariant'), (44, 'invariant')]),
              ('call', 'zero_3d_A', [('num', 513)]),
              131),
             ('decl',
              'train_H',
              ('tensor',
               [(513, 'invariant'), (44, 'invariant'), (30, 'invariant')]),
              ('call', 'zero_3d_H', [('num', 513)]),
              132),
             ('decl',
              'train_sizes',
              ('tensor', [(513, 'invariant')]),
              ('call', 'zero_1d_array', [('num', 513)]),
              133),
             ('decl',
              'train_y',
              ('tensor', [(513, 'invariant')]),
              ('call', 'zero_1d_array', [('num', 513)]),
              134),
             ('decl',
              'test_A',
              ('tensor',
               [(65, 'invariant'), (44, 'invariant'), (44, 'invariant')]),
              ('call', 'zero_3d_A', [('num', 65)]),
              136),
             ('decl',
              'test_H',
              ('tensor',
               [(65, 'invariant'), (44, 'invariant'), (30, 'invariant')]),
              ('call', 'zero_3d_H', [('num', 65)]),
              137),
             ('decl',
              'test_sizes',
              ('tensor', [(65, 'invariant')]),
              ('call', 'zero_1d_array', [('num', 65)]),
              138),
             ('decl',
              'test_y',
              ('tensor', [(65, 'invariant')]),
              ('call', 'zero_1d_array', [('num', 65)]),
              139),
             ('decl', 'lr', 'ℝ', ('num', 0.0005), 141),
             ('decl', 'epochs', 'ℕ', ('num', 1), 146),
             ('decl',
              'final_loss',
              'ℝ',
              ('method_call',
               ('var', 'gcn_object'),
               'train',
               [('var', 'epochs'), ('var', 'lr')]),
              147),
             ('expr', ('call', 'print', [('var', 'final_loss')]), 0),
             ('decl',
              'accuracy',
              'ℝ',
              ('method_call', ('var', 'gcn_object'), 'evaluate', []),
              150),
             ('expr', ('call', 'print', [('var', 'accuracy')]), 0)]}