EXPECTED = {'classes': {},
 'functions': {'U': {'body': ('sub',
                              ('mul',
                               ('mul',
                                ('mul', ('num', 0.5), ('num', 4.0)),
                                ('var', 'x')),
                               ('var', 'x')),
                              ('mul',
                               ('mul', ('num', 2.0), ('num', 9.8)),
                               ('var', 'x'))),
                     'has_loop': False,
                     'params': [('x', 'ℝ')],
                     'return_type': 'ℝ',
                     'statements': []}},
 'program': [('func_def', 'U'),
             ('decl', 'x', 'ℝ', ('num', 0.0), 9),
             ('for_loop_range',
              'i',
              ('num', 0),
              ('num', 60),
              [('for_assign',
                'x',
                ('sub',
                 ('var', 'x'),
                 ('mul',
                  ('num', 0.05),
                  ('call', 'grad', [('call', 'U', [('var', 'x')]), ('var', 'x')]))))],
              10),
             ('expr', ('var', 'x'), 0)]}
