EXPECTED = {'functions': {'tanh': {'params': [('z', 'ℝ')],
                        'return_type': 'ℝ',
                        'body': ('var', 'res'),
                        'has_loop': False,
                        'statements': [('body_decl',
                                        'num',
                                        'ℝ',
                                        ('sub',
                                         ('call', 'exp', [('var', 'z')]),
                                         ('call',
                                          'exp',
                                          [('neg', ('var', 'z'))]))),
                                       ('body_decl',
                                        'denom',
                                        'ℝ',
                                        ('add',
                                         ('call', 'exp', [('var', 'z')]),
                                         ('call',
                                          'exp',
                                          [('neg', ('var', 'z'))]))),
                                       ('body_decl',
                                        'res',
                                        'ℝ',
                                        ('div',
                                         ('var', 'num'),
                                         ('var', 'denom')))]},
               'H': {'params': [('J', 'ℝ'),
                                ('h', 'ℝ'),
                                ('spins', ('tensor', [('m', 'invariant')])),
                                ('n', 'ℝ')],
                     'return_type': 'ℝ',
                     'body': ('sub',
                              ('mul', ('neg', ('var', 'J')), ('var', 'nn_sum')),
                              ('mul', ('var', 'h'), ('var', 'field_sum'))),
                     'has_loop': False,
                     'statements': [('body_decl',
                                     'n',
                                     'ℝ',
                                     ('sub', ('var', 'n'), ('num', 1))),
                                    ('body_decl',
                                     'nn_bulk',
                                     ('tensor', [('n', 'invariant')]),
                                     ('for_expr',
                                      'i',
                                      ('var', 'n'),
                                      ('mul',
                                       ('index', 'spins', ('imaginary',)),
                                       ('index',
                                        'spins',
                                        ('add', ('imaginary',), ('num', 1)))))),
                                    ('body_decl',
                                     'nn_sum',
                                     'ℝ',
                                     ('add',
                                      ('call', 'sum', [('var', 'nn_bulk')]),
                                      ('mul',
                                       ('index', 'spins', ('var', 'n')),
                                       ('index', 'spins', ('num', 0))))),
                                    ('body_decl',
                                     'field_sum',
                                     'ℝ',
                                     ('call', 'sum', [('var', 'spins')]))]},
               'neg_entropy_per_site': {'params': [('p', 'ℝ')],
                                        'return_type': 'ℝ',
                                        'body': ('add',
                                                 ('mul',
                                                  ('var', 'p'),
                                                  ('call',
                                                   'log',
                                                   [('var', 'p')])),
                                                 ('mul',
                                                  ('sub',
                                                   ('num', 1.0),
                                                   ('var', 'p')),
                                                  ('call',
                                                   'log',
                                                   [('sub',
                                                     ('num', 1.0),
                                                     ('var', 'p'))]))),
                                        'has_loop': False,
                                        'statements': []},
               'mean_field_reference': {'params': [('J', 'ℝ'),
                                                   ('h', 'ℝ'),
                                                   ('β', 'ℝ'),
                                                   ('iters', 'ℕ')],
                                        'return_type': 'ℝ',
                                        'body': ('mul',
                                                 ('add',
                                                  ('num', 1.0),
                                                  ('var', 'm')),
                                                 ('num', 0.5)),
                                        'has_loop': False,
                                        'statements': [('body_decl',
                                                        'm',
                                                        'ℝ',
                                                        ('num', 0.0)),
                                                       ('body_for_range',
                                                        'it',
                                                        ('num', 0),
                                                        ('var', 'iters'),
                                                        [('loop_assign',
                                                          'm',
                                                          ('call',
                                                           'tanh',
                                                           [('mul',
                                                             ('var', 'β'),
                                                             ('add',
                                                              ('mul',
                                                               ('mul',
                                                                ('num', 2.0),
                                                                ('var', 'J')),
                                                               ('var', 'm')),
                                                              ('var',
                                                               'h')))]))])]}},
 'classes': {'MeanFieldIsing': {'class_params': [('logit_p', 'ℝ')],
                                'fields': [('baseline', 'ℝ')],
                                'methods': [{'name': 'λ',
                                             'params': [('n', 'ℕ')],
                                             'return_type': ('tensor',
                                                             [('n',
                                                               'invariant')]),
                                             'statements': [('body_decl',
                                                             'p',
                                                             'ℝ',
                                                             ('div',
                                                              ('num', 1.0),
                                                              ('add',
                                                               ('num', 1.0),
                                                               ('call',
                                                                'exp',
                                                                [('neg',
                                                                  ('field_access',
                                                                   ('var',
                                                                    'this'),
                                                                   'logit_p'))])))),
                                                            ('typed_sample',
                                                             'b_s',
                                                             ('tensor',
                                                              [('n',
                                                                'invariant')]),
                                                             ('call',
                                                              'Bernoulli',
                                                              [('var', 'p'),
                                                               ('var', 'n')])),
                                                            ('body_decl',
                                                             'spins',
                                                             ('tensor',
                                                              [('n',
                                                                'invariant')]),
                                                             ('for_expr',
                                                              'i',
                                                              ('var', 'n'),
                                                              ('sub',
                                                               ('mul',
                                                                ('num', 2.0),
                                                                ('index',
                                                                 'b_s',
                                                                 ('imaginary',))),
                                                               ('num', 1.0))))],
                                             'body': ('var', 'spins')},
                                            {'name': 'loss',
                                             'params': [('spins',
                                                         ('tensor',
                                                          [('n',
                                                            'invariant')])),
                                                        ('J', 'ℝ'),
                                                        ('h', 'ℝ'),
                                                        ('β', 'ℝ'),
                                                        ('size', 'ℝ')],
                                             'return_type': 'ℝ',
                                             'statements': [('body_decl',
                                                             'p',
                                                             'ℝ',
                                                             ('div',
                                                              ('num', 1.0),
                                                              ('add',
                                                               ('num', 1.0),
                                                               ('call',
                                                                'exp',
                                                                [('neg',
                                                                  ('field_access',
                                                                   ('var',
                                                                    'this'),
                                                                   'logit_p'))])))),
                                                            ('body_decl',
                                                             'b',
                                                             ('tensor',
                                                              [('n',
                                                                'invariant')]),
                                                             ('for_expr',
                                                              'i',
                                                              ('var', 'n'),
                                                              ('mul',
                                                               ('add',
                                                                ('index',
                                                                 'spins',
                                                                 ('imaginary',)),
                                                                ('num', 1.0)),
                                                               ('num', 0.5)))),
                                                            ('body_decl',
                                                             'energy_ps',
                                                             'ℝ',
                                                             ('div',
                                                              ('call',
                                                               'H',
                                                               [('var', 'J'),
                                                                ('var', 'h'),
                                                                ('var',
                                                                 'spins'),
                                                                ('var',
                                                                 'size')]),
                                                              ('var', 'n'))),
                                                            ('body_decl',
                                                             'log_prob',
                                                             'ℝ',
                                                             ('call',
                                                              'sum',
                                                              [('for_expr',
                                                                'i',
                                                                ('var', 'n'),
                                                                ('add',
                                                                 ('mul',
                                                                  ('index',
                                                                   'b',
                                                                   ('imaginary',)),
                                                                  ('call',
                                                                   'log',
                                                                   [('var',
                                                                     'p')])),
                                                                 ('mul',
                                                                  ('sub',
                                                                   ('num', 1.0),
                                                                   ('index',
                                                                    'b',
                                                                    ('imaginary',))),
                                                                  ('call',
                                                                   'log',
                                                                   [('sub',
                                                                     ('num',
                                                                      1.0),
                                                                     ('var',
                                                                      'p'))]))))])),
                                                            ('body_decl',
                                                             'energy_term',
                                                             'ℝ',
                                                             ('mul',
                                                              ('mul',
                                                               ('var', 'β'),
                                                               ('sub',
                                                                ('var',
                                                                 'energy_ps'),
                                                                ('field_access',
                                                                 ('var',
                                                                  'this'),
                                                                 'baseline'))),
                                                              ('var',
                                                               'log_prob'))),
                                                            ('body_decl',
                                                             'entropy_term',
                                                             'ℝ',
                                                             ('call',
                                                              'neg_entropy_per_site',
                                                              [('var', 'p')]))],
                                             'body': ('add',
                                                      ('var', 'energy_term'),
                                                      ('var', 'entropy_term'))},
                                            {'name': 'train',
                                             'params': [('n', 'ℕ'),
                                                        ('n_steps', 'ℕ'),
                                                        ('n_batch', 'ℕ'),
                                                        ('lr', 'ℝ'),
                                                        ('J', 'ℝ'),
                                                        ('h', 'ℝ'),
                                                        ('β', 'ℝ'),
                                                        ('size', 'ℕ')],
                                             'return_type': None,
                                             'statements': [('body_assign',
                                                             'spins_0',
                                                             ('call',
                                                              'this',
                                                              [('var', 'n')])),
                                                            ('body_field_assign',
                                                             ('var', 'this'),
                                                             'baseline',
                                                             ('div',
                                                              ('call',
                                                               'H',
                                                               [('var', 'J'),
                                                                ('var', 'h'),
                                                                ('var',
                                                                 'spins_0'),
                                                                ('var',
                                                                 'size')]),
                                                              ('var', 'n'))),
                                                            ('body_for_range',
                                                             'step',
                                                             ('num', 0),
                                                             ('var', 'n_steps'),
                                                             [('loop_assign',
                                                               'batch_loss',
                                                               ('num', 0.0)),
                                                              ('loop_assign',
                                                               'mean_energy_ps',
                                                               ('num', 0.0)),
                                                              ('loop_for_range',
                                                               'k',
                                                               ('num', 0),
                                                               ('var',
                                                                'n_batch'),
                                                               [('loop_assign',
                                                                 'spins',
                                                                 ('call',
                                                                  'this',
                                                                  [('var',
                                                                    'n')])),
                                                                ('loop_assign',
                                                                 'mean_energy_ps',
                                                                 ('add',
                                                                  ('var',
                                                                   'mean_energy_ps'),
                                                                  ('div',
                                                                   ('div',
                                                                    ('call',
                                                                     'H',
                                                                     [('var',
                                                                       'J'),
                                                                      ('var',
                                                                       'h'),
                                                                      ('var',
                                                                       'spins'),
                                                                      ('var',
                                                                       'size')]),
                                                                    ('var',
                                                                     'n')),
                                                                   ('var',
                                                                    'n_batch')))),
                                                                ('loop_assign',
                                                                 'batch_loss',
                                                                 ('add',
                                                                  ('var',
                                                                   'batch_loss'),
                                                                  ('div',
                                                                   ('method_call',
                                                                    ('var',
                                                                     'this'),
                                                                    'loss',
                                                                    [('var',
                                                                      'spins'),
                                                                     ('var',
                                                                      'J'),
                                                                     ('var',
                                                                      'h'),
                                                                     ('var',
                                                                      'β'),
                                                                     ('var',
                                                                      'size')]),
                                                                   ('var',
                                                                    'n_batch'))))]),
                                                              ('loop_assign',
                                                               'grads',
                                                               ('call',
                                                                'grad',
                                                                [('var',
                                                                  'batch_loss'),
                                                                 ('field_access',
                                                                  ('var',
                                                                   'this'),
                                                                  'params')])),
                                                              ('body_field_assign',
                                                               ('var', 'this'),
                                                               'baseline',
                                                               ('add',
                                                                ('mul',
                                                                 ('num', 0.9),
                                                                 ('field_access',
                                                                  ('var',
                                                                   'this'),
                                                                  'baseline')),
                                                                ('mul',
                                                                 ('num', 0.1),
                                                                 ('var',
                                                                  'mean_energy_ps')))),
                                                              ('body_expr',
                                                               ('method_call',
                                                                ('var', 'this'),
                                                                'update',
                                                                [('var', 'lr'),
                                                                 ('var',
                                                                  'grads')]))])],
                                             'body': None}]}},
 'program': [('seed', ('num', 0)),
             ('func_def', 'tanh'),
             ('func_def', 'H'),
             ('func_def', 'neg_entropy_per_site'),
             ('func_def', 'mean_field_reference'),
             ('class_def', 'MeanFieldIsing'),
             ('decl', 'n', 'ℕ', ('num', 20), 59),
             ('decl', 'J', 'ℝ', ('num', 1.0), 60),
             ('decl', 'h', 'ℝ', ('num', 0.5), 61),
             ('decl', 'β', 'ℝ', ('num', 5.0), 62),
             ('decl', 'steps', 'ℕ', ('num', 100), 63),
             ('decl', 'batch', 'ℕ', ('num', 32), 64),
             ('decl', 'logit_init', 'ℝ', ('num', 0.0), 65),
             ('decl', 'lr', 'ℝ', ('num', 0.05), 66),
             ('decl',
              'ising',
              ('struct_type', 'MeanFieldIsing'),
              ('call', 'MeanFieldIsing', [('var', 'logit_init')]),
              69),
             ('decl',
              'p_before',
              'ℝ',
              ('div',
               ('num', 1.0),
               ('add',
                ('num', 1.0),
                ('call',
                 'exp',
                 [('sub',
                   ('num', 0.0),
                   ('field_access', ('var', 'ising'), 'logit_p'))]))),
              71),
             ('decl',
              'spins_before',
              ('tensor', [('n', 'invariant')]),
              ('call', 'ising', [('var', 'n')]),
              72),
             ('expr',
              ('method_call',
               ('var', 'ising'),
               'train',
               [('var', 'n'),
                ('var', 'steps'),
                ('var', 'batch'),
                ('var', 'lr'),
                ('var', 'J'),
                ('var', 'h'),
                ('var', 'β'),
                ('var', 'n')]),
              0),
             ('decl',
              'p_after',
              'ℝ',
              ('div',
               ('num', 1.0),
               ('add',
                ('num', 1.0),
                ('call',
                 'exp',
                 [('sub',
                   ('num', 0.0),
                   ('field_access', ('var', 'ising'), 'logit_p'))]))),
              76),
             ('decl',
              'p_ref',
              'ℝ',
              ('call',
               'mean_field_reference',
               [('var', 'J'), ('var', 'h'), ('var', 'β'), ('num', 200)]),
              77),
             ('decl',
              'spins_after',
              ('tensor', [('n', 'invariant')]),
              ('call', 'ising', [('var', 'n')]),
              78),
             ('expr', ('var', 'p_before'), 0),
             ('expr', ('var', 'p_after'), 0),
             ('expr', ('var', 'p_ref'), 0)]}