EXPECTED = {'functions': {'zero_1d_array': {'params': [('len', 'ℝ')],
                                 'return_type': ('tensor',
                                                 [('m', 'invariant')]),
                                 'body': ('var', 'results'),
                                 'has_loop': False,
                                 'statements': [('body_decl',
                                                 'results',
                                                 ('tensor',
                                                  [('len', 'invariant')]),
                                                 ('for_expr',
                                                  'i',
                                                  ('var', 'len'),
                                                  ('mul',
                                                   ('imaginary',),
                                                   ('num', 0))))]},
               'get_1d_array_length': {'params': [('x',
                                                   ('tensor',
                                                    [('m', 'invariant')]))],
                                       'return_type': 'ℝ',
                                       'body': ('var', 'total'),
                                       'has_loop': False,
                                       'statements': [('body_decl',
                                                       'total',
                                                       'ℝ',
                                                       ('num', 0)),
                                                      ('body_decl',
                                                       'temp',
                                                       'ℝ',
                                                       ('num', 0)),
                                                      ('body_for',
                                                       'i',
                                                       [('loop_assign',
                                                         'temp',
                                                         ('index',
                                                          'x',
                                                          ('imaginary',))),
                                                        ('loop_pluseq',
                                                         'total',
                                                         ('num', 1))],
                                                       ['x'])]},
               'append': {'params': [('x', ('tensor', [('m', 'invariant')])),
                                     ('var', 'ℝ')],
                          'return_type': ('tensor', [('n', 'invariant')]),
                          'body': ('var', 'results'),
                          'has_loop': False,
                          'statements': [('body_decl',
                                          'new_length',
                                          'ℝ',
                                          ('add',
                                           ('call',
                                            'get_1d_array_length',
                                            [('var', 'x')]),
                                           ('num', 1))),
                                         ('body_decl',
                                          'results',
                                          ('tensor',
                                           [('new_length', 'invariant')]),
                                          ('call',
                                           'zero_1d_array',
                                           [('var', 'new_length')])),
                                         ('body_decl',
                                          'len_x',
                                          'ℕ',
                                          ('call',
                                           'get_1d_array_length',
                                           [('var', 'x')])),
                                         ('body_for_range',
                                          'i',
                                          ('num', 0),
                                          ('var', 'new_length'),
                                          [('loop_if_else',
                                            ('cond_lt',
                                             ('imaginary',),
                                             ('var', 'len_x')),
                                            [('loop_index_assign_nd',
                                              'results',
                                              [('index_item', ('imaginary',))],
                                              ('index', 'x', ('imaginary',)))],
                                            [('loop_index_assign_nd',
                                              'results',
                                              [('index_item', ('imaginary',))],
                                              ('var', 'var'))])])]},
               'solver_hard': {'params': [('a', 'ℝ')],
                               'return_type': ('tensor', [('m', 'invariant')]),
                               'body': ('var', 'v_array'),
                               'has_loop': False,
                               'statements': [('body_decl',
                                               'v',
                                               'ℝ',
                                               ('neg', ('num', 65.0))),
                                              ('body_decl',
                                               'u',
                                               'ℝ',
                                               ('mul',
                                                ('var', 'b'),
                                                ('var', 'v'))),
                                              ('body_decl',
                                               'v_array',
                                               ('tensor', [(1, 'invariant')]),
                                               ('array',
                                                [('neg', ('num', 65.0))])),
                                              ('body_for_range',
                                               'i',
                                               ('num', 0),
                                               ('var', 'timesteps'),
                                               [('loop_pluseq',
                                                 'v',
                                                 ('mul',
                                                  ('mul',
                                                   ('num', 0.5),
                                                   ('var', 'dt')),
                                                  ('add',
                                                   ('sub',
                                                    ('add',
                                                     ('add',
                                                      ('mul',
                                                       ('mul',
                                                        ('num', 0.04),
                                                        ('var', 'v')),
                                                       ('var', 'v')),
                                                      ('mul',
                                                       ('num', 5.0),
                                                       ('var', 'v'))),
                                                     ('num', 140.0)),
                                                    ('var', 'u')),
                                                   ('var', 'I')))),
                                                ('loop_pluseq',
                                                 'v',
                                                 ('mul',
                                                  ('mul',
                                                   ('num', 0.5),
                                                   ('var', 'dt')),
                                                  ('add',
                                                   ('sub',
                                                    ('add',
                                                     ('add',
                                                      ('mul',
                                                       ('mul',
                                                        ('num', 0.04),
                                                        ('var', 'v')),
                                                       ('var', 'v')),
                                                      ('mul',
                                                       ('num', 5.0),
                                                       ('var', 'v'))),
                                                     ('num', 140.0)),
                                                    ('var', 'u')),
                                                   ('var', 'I')))),
                                                ('loop_pluseq',
                                                 'u',
                                                 ('mul',
                                                  ('var', 'dt'),
                                                  ('mul',
                                                   ('var', 'a'),
                                                   ('sub',
                                                    ('mul',
                                                     ('var', 'b'),
                                                     ('var', 'v')),
                                                    ('var', 'u'))))),
                                                ('loop_if',
                                                 ('cond_geq',
                                                  ('var', 'v'),
                                                  ('num', 30.0)),
                                                 [('loop_assign',
                                                   'v',
                                                   ('var', 'c')),
                                                  ('loop_assign',
                                                   'u',
                                                   ('add',
                                                    ('var', 'u'),
                                                    ('var', 'd')))]),
                                                ('loop_assign',
                                                 'v_array',
                                                 ('call',
                                                  'append',
                                                  [('var', 'v_array'),
                                                   ('var', 'v')]))])]},
               'solver_salt': {'params': [('a', 'ℝ')],
                               'return_type': ('tensor', [('m', 'invariant')]),
                               'body': ('var', 'v_array'),
                               'has_loop': False,
                               'statements': [('body_decl',
                                               'v',
                                               'ℝ',
                                               ('neg', ('num', 65.0))),
                                              ('body_decl',
                                               'u',
                                               'ℝ',
                                               ('mul',
                                                ('var', 'b'),
                                                ('var', 'v'))),
                                              ('body_decl',
                                               'vfull',
                                               'ℝ',
                                               ('num', 0.0)),
                                              ('body_decl',
                                               'ufull',
                                               'ℝ',
                                               ('num', 0.0)),
                                              ('body_decl',
                                               'frac',
                                               'ℝ',
                                               ('num', 0.0)),
                                              ('body_decl',
                                               'hf',
                                               'ℝ',
                                               ('num', 0.0)),
                                              ('body_decl',
                                               'vc',
                                               'ℝ',
                                               ('num', 0.0)),
                                              ('body_decl',
                                               'u_cross',
                                               'ℝ',
                                               ('num', 0.0)),
                                              ('body_decl',
                                               'hr',
                                               'ℝ',
                                               ('num', 0.0)),
                                              ('body_decl',
                                               'ur',
                                               'ℝ',
                                               ('num', 0.0)),
                                              ('body_decl',
                                               'vv',
                                               'ℝ',
                                               ('num', 0.0)),
                                              ('body_decl',
                                               'v_array',
                                               ('tensor', [(1, 'invariant')]),
                                               ('array',
                                                [('neg', ('num', 65.0))])),
                                              ('body_for_range',
                                               'i',
                                               ('num', 0),
                                               ('var', 'timesteps'),
                                               [('loop_assign',
                                                 'vfull',
                                                 ('add',
                                                  ('var', 'v'),
                                                  ('mul',
                                                   ('mul',
                                                    ('num', 0.5),
                                                    ('var', 'dt')),
                                                   ('add',
                                                    ('sub',
                                                     ('add',
                                                      ('add',
                                                       ('mul',
                                                        ('mul',
                                                         ('num', 0.04),
                                                         ('var', 'v')),
                                                        ('var', 'v')),
                                                       ('mul',
                                                        ('num', 5.0),
                                                        ('var', 'v'))),
                                                      ('num', 140.0)),
                                                     ('var', 'u')),
                                                    ('var', 'I'))))),
                                                ('loop_assign',
                                                 'vfull',
                                                 ('add',
                                                  ('var', 'vfull'),
                                                  ('mul',
                                                   ('mul',
                                                    ('num', 0.5),
                                                    ('var', 'dt')),
                                                   ('add',
                                                    ('sub',
                                                     ('add',
                                                      ('add',
                                                       ('mul',
                                                        ('mul',
                                                         ('num', 0.04),
                                                         ('var', 'vfull')),
                                                        ('var', 'vfull')),
                                                       ('mul',
                                                        ('num', 5.0),
                                                        ('var', 'vfull'))),
                                                      ('num', 140.0)),
                                                     ('var', 'u')),
                                                    ('var', 'I'))))),
                                                ('loop_assign',
                                                 'ufull',
                                                 ('add',
                                                  ('var', 'u'),
                                                  ('mul',
                                                   ('var', 'dt'),
                                                   ('mul',
                                                    ('var', 'a'),
                                                    ('sub',
                                                     ('mul',
                                                      ('var', 'b'),
                                                      ('var', 'vfull')),
                                                     ('var', 'u')))))),
                                                ('loop_if_else',
                                                 ('cond_geq',
                                                  ('var', 'vfull'),
                                                  ('num', 30.0)),
                                                 [('loop_assign',
                                                   'frac',
                                                   ('div',
                                                    ('sub',
                                                     ('num', 30.0),
                                                     ('var', 'v')),
                                                    ('sub',
                                                     ('var', 'vfull'),
                                                     ('var', 'v')))),
                                                  ('loop_assign',
                                                   'hf',
                                                   ('mul',
                                                    ('var', 'frac'),
                                                    ('var', 'dt'))),
                                                  ('loop_assign',
                                                   'vc',
                                                   ('add',
                                                    ('var', 'v'),
                                                    ('mul',
                                                     ('mul',
                                                      ('num', 0.5),
                                                      ('var', 'hf')),
                                                     ('add',
                                                      ('sub',
                                                       ('add',
                                                        ('add',
                                                         ('mul',
                                                          ('mul',
                                                           ('num', 0.04),
                                                           ('var', 'v')),
                                                          ('var', 'v')),
                                                         ('mul',
                                                          ('num', 5.0),
                                                          ('var', 'v'))),
                                                        ('num', 140.0)),
                                                       ('var', 'u')),
                                                      ('var', 'I'))))),
                                                  ('loop_assign',
                                                   'vc',
                                                   ('add',
                                                    ('var', 'vc'),
                                                    ('mul',
                                                     ('mul',
                                                      ('num', 0.5),
                                                      ('var', 'hf')),
                                                     ('add',
                                                      ('sub',
                                                       ('add',
                                                        ('add',
                                                         ('mul',
                                                          ('mul',
                                                           ('num', 0.04),
                                                           ('var', 'vc')),
                                                          ('var', 'vc')),
                                                         ('mul',
                                                          ('num', 5.0),
                                                          ('var', 'vc'))),
                                                        ('num', 140.0)),
                                                       ('var', 'u')),
                                                      ('var', 'I'))))),
                                                  ('loop_assign',
                                                   'u_cross',
                                                   ('add',
                                                    ('var', 'u'),
                                                    ('mul',
                                                     ('var', 'hf'),
                                                     ('mul',
                                                      ('var', 'a'),
                                                      ('sub',
                                                       ('mul',
                                                        ('var', 'b'),
                                                        ('var', 'vc')),
                                                       ('var', 'u')))))),
                                                  ('loop_assign',
                                                   'hr',
                                                   ('mul',
                                                    ('sub',
                                                     ('num', 1.0),
                                                     ('var', 'frac')),
                                                    ('var', 'dt'))),
                                                  ('loop_assign',
                                                   'ur',
                                                   ('add',
                                                    ('var', 'u_cross'),
                                                    ('var', 'd'))),
                                                  ('loop_assign',
                                                   'vv',
                                                   ('add',
                                                    ('var', 'c'),
                                                    ('mul',
                                                     ('mul',
                                                      ('num', 0.5),
                                                      ('var', 'hr')),
                                                     ('add',
                                                      ('sub',
                                                       ('add',
                                                        ('add',
                                                         ('mul',
                                                          ('mul',
                                                           ('num', 0.04),
                                                           ('var', 'c')),
                                                          ('var', 'c')),
                                                         ('mul',
                                                          ('num', 5.0),
                                                          ('var', 'c'))),
                                                        ('num', 140.0)),
                                                       ('var', 'ur')),
                                                      ('var', 'I'))))),
                                                  ('loop_assign',
                                                   'vv',
                                                   ('add',
                                                    ('var', 'vv'),
                                                    ('mul',
                                                     ('mul',
                                                      ('num', 0.5),
                                                      ('var', 'hr')),
                                                     ('add',
                                                      ('sub',
                                                       ('add',
                                                        ('add',
                                                         ('mul',
                                                          ('mul',
                                                           ('num', 0.04),
                                                           ('var', 'vv')),
                                                          ('var', 'vv')),
                                                         ('mul',
                                                          ('num', 5.0),
                                                          ('var', 'vv'))),
                                                        ('num', 140.0)),
                                                       ('var', 'ur')),
                                                      ('var', 'I'))))),
                                                  ('loop_assign',
                                                   'u',
                                                   ('add',
                                                    ('var', 'ur'),
                                                    ('mul',
                                                     ('var', 'hr'),
                                                     ('mul',
                                                      ('var', 'a'),
                                                      ('sub',
                                                       ('mul',
                                                        ('var', 'b'),
                                                        ('var', 'vv')),
                                                       ('var', 'ur')))))),
                                                  ('loop_assign',
                                                   'v',
                                                   ('var', 'vv'))],
                                                 [('loop_assign',
                                                   'v',
                                                   ('var', 'vfull')),
                                                  ('loop_assign',
                                                   'u',
                                                   ('var', 'ufull'))]),
                                                ('loop_assign',
                                                 'v_array',
                                                 ('call',
                                                  'append',
                                                  [('var', 'v_array'),
                                                   ('var', 'v')]))])]},
               'loss_hard': {'params': [('a', 'ℝ')],
                             'return_type': 'ℝ',
                             'body': ('div', ('var', 'L'), ('var', 'm')),
                             'has_loop': False,
                             'statements': [('body_decl',
                                             'v_pred',
                                             ('tensor', [('n', 'invariant')]),
                                             ('call',
                                              'solver_hard',
                                              [('var', 'a')])),
                                            ('body_decl',
                                             'L',
                                             'ℝ',
                                             ('num', 0.0)),
                                            ('body_decl',
                                             'm',
                                             'ℝ',
                                             ('call',
                                              'get_1d_array_length',
                                              [('var', 'v_pred')])),
                                            ('body_for_range',
                                             'i',
                                             ('num', 0),
                                             ('var', 'm'),
                                             [('loop_pluseq',
                                               'L',
                                               ('pow',
                                                ('sub',
                                                 ('index',
                                                  'v_pred',
                                                  ('imaginary',)),
                                                 ('index',
                                                  'v_data',
                                                  ('imaginary',))),
                                                ('num', 2)))])]},
               'loss_salt': {'params': [('a', 'ℝ')],
                             'return_type': 'ℝ',
                             'body': ('div', ('var', 'L'), ('var', 'm')),
                             'has_loop': False,
                             'statements': [('body_decl',
                                             'v_pred',
                                             ('tensor', [('n', 'invariant')]),
                                             ('call',
                                              'solver_salt',
                                              [('var', 'a')])),
                                            ('body_decl',
                                             'L',
                                             'ℝ',
                                             ('num', 0.0)),
                                            ('body_decl',
                                             'm',
                                             'ℝ',
                                             ('call',
                                              'get_1d_array_length',
                                              [('var', 'v_pred')])),
                                            ('body_for_range',
                                             'i',
                                             ('num', 0),
                                             ('var', 'm'),
                                             [('loop_pluseq',
                                               'L',
                                               ('pow',
                                                ('sub',
                                                 ('index',
                                                  'v_pred',
                                                  ('imaginary',)),
                                                 ('index',
                                                  'v_data',
                                                  ('imaginary',))),
                                                ('num', 2)))])]}},
 'classes': {},
 'program': [('func_def', 'zero_1d_array'),
             ('func_def', 'get_1d_array_length'),
             ('func_def', 'append'),
             ('decl', 'b', 'ℝ', ('num', 0.2), 49),
             ('decl', 'c', 'ℝ', ('neg', ('num', 65.0)), 50),
             ('decl', 'd', 'ℝ', ('num', 8.0), 51),
             ('decl', 'dt', 'ℝ', ('num', 0.5), 52),
             ('decl', 'timesteps', 'ℕ', ('num', 200), 53),
             ('decl', 'I', 'ℝ', ('num', 10.0), 54),
             ('func_def', 'solver_hard'),
             ('func_def', 'solver_salt'),
             ('decl', 'true_a', 'ℝ', ('num', 0.02), 114),
             ('decl',
              'v_data',
              ('tensor', [('m', 'invariant')]),
              ('call', 'solver_salt', [('var', 'true_a')]),
              115),
             ('func_def', 'loss_hard'),
             ('func_def', 'loss_salt'),
             ('decl', 'a_probe', 'ℝ', ('num', 0.025), 136),
             ('expr',
              ('call', 'grad', [('var', 'loss_hard'), ('var', 'a_probe')]),
              0),
             ('expr',
              ('call', 'grad', [('var', 'loss_salt'), ('var', 'a_probe')]),
              0),
             ('decl', 'a_log', 'ℝ', ('call', 'log', [('num', 0.04)]), 144),
             ('decl', 'learning_rate', 'ℝ', ('num', 0.004), 145),
             ('decl', 'beta1', 'ℝ', ('num', 0.9), 146),
             ('decl', 'beta2', 'ℝ', ('num', 0.999), 147),
             ('decl', 'eps_adam', 'ℝ', ('num', 1e-08), 148),
             ('decl', 'm_adam', 'ℝ', ('num', 0.0), 149),
             ('decl', 'v_adam', 'ℝ', ('num', 0.0), 150),
             ('decl', 't_adam', 'ℝ', ('num', 0.0), 151),
             ('decl', 'epochs', 'ℕ', ('num', 1), 152),
             ('for_loop_range',
              'i',
              ('num', 0),
              ('var', 'epochs'),
              [('for_assign', 'a_lin', ('call', 'exp', [('var', 'a_log')])),
               ('for_assign',
                'g',
                ('call', 'grad', [('var', 'loss_salt'), ('var', 'a_lin')])),
               ('for_assign', 'g_log', ('mul', ('var', 'g'), ('var', 'a_lin'))),
               ('for_assign',
                't_adam',
                ('add', ('var', 't_adam'), ('num', 1.0))),
               ('for_assign',
                'm_adam',
                ('add',
                 ('mul', ('var', 'beta1'), ('var', 'm_adam')),
                 ('mul',
                  ('sub', ('num', 1.0), ('var', 'beta1')),
                  ('var', 'g_log')))),
               ('for_assign',
                'v_adam',
                ('add',
                 ('mul', ('var', 'beta2'), ('var', 'v_adam')),
                 ('mul',
                  ('sub', ('num', 1.0), ('var', 'beta2')),
                  ('mul', ('var', 'g_log'), ('var', 'g_log'))))),
               ('for_assign',
                'mhat',
                ('div',
                 ('var', 'm_adam'),
                 ('sub',
                  ('num', 1.0),
                  ('pow', ('var', 'beta1'), ('var', 't_adam'))))),
               ('for_assign',
                'vhat',
                ('div',
                 ('var', 'v_adam'),
                 ('sub',
                  ('num', 1.0),
                  ('pow', ('var', 'beta2'), ('var', 't_adam'))))),
               ('for_assign',
                'a_log',
                ('sub',
                 ('var', 'a_log'),
                 ('div',
                  ('mul', ('var', 'learning_rate'), ('var', 'mhat')),
                  ('add',
                   ('call', 'sqrt', [('var', 'vhat')]),
                   ('var', 'eps_adam')))))],
              154),
             ('decl', 'a_final', 'ℝ', ('call', 'exp', [('var', 'a_log')]), 165),
             ('expr', ('call', 'print', [('var', 'a_final')]), 0)]}
