EXPECTED = {'functions': {'sq_dist': {'params': [('a', ('tensor', [(2, 'invariant')])),
                                      ('b', ('tensor', [(2, 'invariant')]))],
                           'return_type': 'ℝ',
                           'body': ('add',
                                    ('mul', ('var', 'e0'), ('var', 'e0')),
                                    ('mul', ('var', 'e1'), ('var', 'e1'))),
                           'has_loop': False,
                           'statements': [('body_decl',
                                           'e0',
                                           'ℝ',
                                           ('sub',
                                            ('index', 'a', ('num', 0)),
                                            ('index', 'b', ('num', 0)))),
                                          ('body_decl',
                                           'e1',
                                           'ℝ',
                                           ('sub',
                                            ('index', 'a', ('num', 1)),
                                            ('index', 'b', ('num', 1))))]},
               'nearest_of_two': {'params': [('point',
                                              ('tensor', [(2, 'invariant')])),
                                             ('C',
                                              ('tensor',
                                               [(2, 'invariant'),
                                                (2, 'invariant')]))],
                                  'return_type': 'ℝ',
                                  'body': ('var', 'label'),
                                  'has_loop': False,
                                  'statements': [('body_decl',
                                                  'd0',
                                                  'ℝ',
                                                  ('call',
                                                   'sq_dist',
                                                   [('var', 'point'),
                                                    ('index',
                                                     'C',
                                                     ('num', 0))])),
                                                 ('body_decl',
                                                  'd1',
                                                  'ℝ',
                                                  ('call',
                                                   'sq_dist',
                                                   [('var', 'point'),
                                                    ('index',
                                                     'C',
                                                     ('num', 1))])),
                                                 ('body_decl',
                                                  'label',
                                                  'ℝ',
                                                  ('num', 0.0)),
                                                 ('body_if',
                                                  ('cond_lt',
                                                   ('var', 'd1'),
                                                   ('var', 'd0')),
                                                  [('body_assign',
                                                    'label',
                                                    ('num', 1.0))])]},
               'assign_labels': {'params': [('X',
                                             ('tensor',
                                              [('n', 'invariant'),
                                               (2, 'invariant')])),
                                            ('C',
                                             ('tensor',
                                              [(2, 'invariant'),
                                               (2, 'invariant')]))],
                                 'return_type': ('tensor',
                                                 [('n', 'invariant')]),
                                 'body': ('for_expr',
                                          'i',
                                          ('var', 'n'),
                                          ('call',
                                           'nearest_of_two',
                                           [('index', 'X', ('imaginary',)),
                                            ('var', 'C')])),
                                 'has_loop': False,
                                 'statements': []},
               'cluster_mean': {'params': [('X',
                                            ('tensor',
                                             [('n', 'invariant'),
                                              (2, 'invariant')])),
                                           ('labels',
                                            ('tensor', [('n', 'invariant')])),
                                           ('target', 'ℝ'),
                                           ('fallback',
                                            ('tensor', [(2, 'invariant')]))],
                                'return_type': ('tensor', [(2, 'invariant')]),
                                'body': None,
                                'has_loop': False,
                                'statements': [('body_decl',
                                                's0',
                                                'ℝ',
                                                ('num', 0.0)),
                                               ('body_decl',
                                                's1',
                                                'ℝ',
                                                ('num', 0.0)),
                                               ('body_decl',
                                                'cnt',
                                                'ℝ',
                                                ('num', 0.0)),
                                               ('body_for_range',
                                                'i',
                                                ('num', 0),
                                                ('var', 'n'),
                                                [('loop_if',
                                                  ('cond_eq',
                                                   ('index',
                                                    'labels',
                                                    ('imaginary',)),
                                                   ('var', 'target')),
                                                  [('loop_pluseq',
                                                    's0',
                                                    ('indexN',
                                                     'X',
                                                     [('index_item',
                                                       ('imaginary',)),
                                                      ('index_item',
                                                       ('num', 0))])),
                                                   ('loop_pluseq',
                                                    's1',
                                                    ('indexN',
                                                     'X',
                                                     [('index_item',
                                                       ('imaginary',)),
                                                      ('index_item',
                                                       ('num', 1))])),
                                                   ('loop_pluseq',
                                                    'cnt',
                                                    ('num', 1.0))])]),
                                               ('body_if_else_return',
                                                ('cond_gt',
                                                 ('var', 'cnt'),
                                                 ('num', 0.0)),
                                                ('array',
                                                 [('div',
                                                   ('var', 's0'),
                                                   ('var', 'cnt')),
                                                  ('div',
                                                   ('var', 's1'),
                                                   ('var', 'cnt'))]),
                                                ('var', 'fallback'))]},
               'update_centroids': {'params': [('X',
                                                ('tensor',
                                                 [('n', 'invariant'),
                                                  (2, 'invariant')])),
                                               ('labels',
                                                ('tensor',
                                                 [('n', 'invariant')])),
                                               ('C_old',
                                                ('tensor',
                                                 [(2, 'invariant'),
                                                  (2, 'invariant')]))],
                                    'return_type': ('tensor',
                                                    [(2, 'invariant'),
                                                     (2, 'invariant')]),
                                    'body': ('array',
                                             [('var', 'c0'), ('var', 'c1')]),
                                    'has_loop': False,
                                    'statements': [('body_decl',
                                                    'c0',
                                                    ('tensor',
                                                     [(2, 'invariant')]),
                                                    ('call',
                                                     'cluster_mean',
                                                     [('var', 'X'),
                                                      ('var', 'labels'),
                                                      ('num', 0.0),
                                                      ('index',
                                                       'C_old',
                                                       ('num', 0))])),
                                                   ('body_decl',
                                                    'c1',
                                                    ('tensor',
                                                     [(2, 'invariant')]),
                                                    ('call',
                                                     'cluster_mean',
                                                     [('var', 'X'),
                                                      ('var', 'labels'),
                                                      ('num', 1.0),
                                                      ('index',
                                                       'C_old',
                                                       ('num', 1))]))]}},
 'classes': {},
 'program': [('decl', 'n', 'ℝ', ('num', 8), 22),
             ('decl', 'iters', 'ℕ', ('num', 10), 23),
             ('func_def', 'sq_dist'),
             ('func_def', 'nearest_of_two'),
             ('func_def', 'assign_labels'),
             ('func_def', 'cluster_mean'),
             ('func_def', 'update_centroids'),
             ('decl',
              'X',
              ('tensor', [(8, 'invariant'), (2, 'invariant')]),
              ('array',
               [('array', [('num', 1.0), ('num', 1.0)]),
                ('array', [('num', 1.5), ('num', 2.0)]),
                ('array', [('num', 1.0), ('num', 2.5)]),
                ('array', [('num', 2.0), ('num', 1.5)]),
                ('array', [('num', 8.0), ('num', 8.0)]),
                ('array', [('num', 8.5), ('num', 9.0)]),
                ('array', [('num', 9.0), ('num', 8.5)]),
                ('array', [('num', 7.5), ('num', 9.5)])]),
              70),
             ('decl',
              'C',
              ('tensor', [(2, 'invariant'), (2, 'invariant')]),
              ('array',
               [('array', [('num', 1.0), ('num', 1.0)]),
                ('array', [('num', 8.0), ('num', 8.0)])]),
              76),
             ('decl',
              'labels',
              ('tensor', [(8, 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'n'),
               ('mul', ('imaginary',), ('num', 0.0))),
              78),
             ('for_loop_range',
              'step',
              ('num', 0),
              ('var', 'iters'),
              [('for_assign',
                'labels',
                ('call', 'assign_labels', [('var', 'X'), ('var', 'C')])),
               ('for_assign',
                'C',
                ('call',
                 'update_centroids',
                 [('var', 'X'), ('var', 'labels'), ('var', 'C')]))],
              79),
             ('expr', ('call', 'print', [('var', 'labels')]), 0),
             ('expr', ('call', 'print', [('var', 'C')]), 0)]}
