EXPECTED = {'functions': {'absolute': {'params': [('a', ('tensor', [('m', 'invariant')]))],
                            'return_type': ('tensor', [('m', 'invariant')]),
                            'body': ('call',
                                     'sqrt',
                                     [('mul', ('var', 'a'), ('var', 'a'))]),
                            'has_loop': False,
                            'statements': []},
               'get_sum_of_1d_array': {'params': [('x',
                                                   ('tensor',
                                                    [('m', 'invariant')]))],
                                       'return_type': 'ℝ',
                                       'body': ('var', 'total'),
                                       'has_loop': False,
                                       'statements': [('body_decl',
                                                       'total',
                                                       'ℝ',
                                                       ('num', 0)),
                                                      ('body_for',
                                                       'i',
                                                       [('loop_pluseq',
                                                         'total',
                                                         ('index',
                                                          'x',
                                                          ('imaginary',)))],
                                                       ['x'])]},
               'sq_dist': {'params': [('a', ('tensor', [('DIM', 'invariant')])),
                                      ('b',
                                       ('tensor', [('DIM', 'invariant')]))],
                           'return_type': 'ℝ',
                           'body': ('var', 'acc'),
                           'has_loop': False,
                           'statements': [('body_decl',
                                           'acc',
                                           'ℝ',
                                           ('num', 0.0)),
                                          ('body_for_range',
                                           'c',
                                           ('num', 0),
                                           ('var', 'DIM'),
                                           [('loop_pluseq',
                                             'acc',
                                             ('mul',
                                              ('sub',
                                               ('index', 'a', ('var', 'c')),
                                               ('index', 'b', ('var', 'c'))),
                                              ('sub',
                                               ('index', 'a', ('var', 'c')),
                                               ('index',
                                                'b',
                                                ('var', 'c')))))])]},
               'argmin_vec': {'params': [('v',
                                          ('tensor', [('K', 'invariant')]))],
                              'return_type': 'ℝ',
                              'body': ('var', 'best_j'),
                              'has_loop': False,
                              'statements': [('body_decl',
                                              'av',
                                              ('tensor', [('K', 'invariant')]),
                                              ('call',
                                               'absolute',
                                               [('var', 'v')])),
                                             ('body_decl',
                                              'best_j',
                                              'ℝ',
                                              ('num', 0.0)),
                                             ('body_decl',
                                              'best_v',
                                              'ℝ',
                                              ('index', 'av', ('num', 0))),
                                             ('body_for_range',
                                              'j',
                                              ('num', 0),
                                              ('var', 'K'),
                                              [('loop_if',
                                                ('cond_lt',
                                                 ('index', 'av', ('var', 'j')),
                                                 ('var', 'best_v')),
                                                [('loop_assign',
                                                  'best_v',
                                                  ('index',
                                                   'av',
                                                   ('var', 'j'))),
                                                 ('loop_assign',
                                                  'best_j',
                                                  ('var', 'j'))])])]},
               'assign_one': {'params': [('point',
                                          ('tensor', [('DIM', 'invariant')])),
                                         ('C',
                                          ('tensor',
                                           [('K', 'invariant'),
                                            ('DIM', 'invariant')]))],
                              'return_type': 'ℝ',
                              'body': ('call',
                                       'argmin_vec',
                                       [('var', 'dists')]),
                              'has_loop': False,
                              'statements': [('body_decl',
                                              'dists',
                                              ('tensor', [('K', 'invariant')]),
                                              ('for_expr',
                                               'j',
                                               ('var', 'K'),
                                               ('call',
                                                'sq_dist',
                                                [('var', 'point'),
                                                 ('index',
                                                  'C',
                                                  ('var', 'j'))])))]},
               'assign_labels': {'params': [('X',
                                             ('tensor',
                                              [('NPTS', 'invariant'),
                                               ('DIM', 'invariant')])),
                                            ('C',
                                             ('tensor',
                                              [('K', 'invariant'),
                                               ('DIM', 'invariant')]))],
                                 'return_type': ('tensor',
                                                 [('NPTS', 'invariant')]),
                                 'body': ('for_expr',
                                          'i',
                                          ('var', 'NPTS'),
                                          ('call',
                                           'assign_one',
                                           [('index', 'X', ('imaginary',)),
                                            ('var', 'C')])),
                                 'has_loop': False,
                                 'statements': []},
               'new_centroid': {'params': [('X',
                                            ('tensor',
                                             [('NPTS', 'invariant'),
                                              ('DIM', 'invariant')])),
                                           ('labels',
                                            ('tensor',
                                             [('NPTS', 'invariant')])),
                                           ('target', 'ℝ'),
                                           ('fallback',
                                            ('tensor',
                                             [('DIM', 'invariant')]))],
                                'return_type': ('tensor',
                                                [('DIM', 'invariant')]),
                                'body': None,
                                'has_loop': False,
                                'statements': [('body_decl',
                                                'sums',
                                                ('tensor',
                                                 [('DIM', 'invariant')]),
                                                ('for_expr',
                                                 'c',
                                                 ('var', 'DIM'),
                                                 ('mul',
                                                  ('var', 'c'),
                                                  ('num', 0.0)))),
                                               ('body_decl',
                                                'cnt',
                                                'ℝ',
                                                ('num', 0.0)),
                                               ('body_for_range',
                                                'i',
                                                ('num', 0),
                                                ('var', 'NPTS'),
                                                [('loop_if',
                                                  ('cond_eq',
                                                   ('index',
                                                    'labels',
                                                    ('imaginary',)),
                                                   ('var', 'target')),
                                                  [('loop_assign',
                                                    'sums',
                                                    ('add',
                                                     ('var', 'sums'),
                                                     ('index',
                                                      'X',
                                                      ('imaginary',)))),
                                                   ('loop_pluseq',
                                                    'cnt',
                                                    ('num', 1.0))])]),
                                               ('body_if_else_return',
                                                ('cond_gt',
                                                 ('var', 'cnt'),
                                                 ('num', 0.0)),
                                                ('div',
                                                 ('var', 'sums'),
                                                 ('var', 'cnt')),
                                                ('var', 'fallback'))]},
               'update_centroids': {'params': [('X',
                                                ('tensor',
                                                 [('NPTS', 'invariant'),
                                                  ('DIM', 'invariant')])),
                                               ('labels',
                                                ('tensor',
                                                 [('NPTS', 'invariant')])),
                                               ('C_old',
                                                ('tensor',
                                                 [('K', 'invariant'),
                                                  ('DIM', 'invariant')]))],
                                    'return_type': ('tensor',
                                                    [('K', 'invariant'),
                                                     ('DIM', 'invariant')]),
                                    'body': ('for_expr',
                                             'j',
                                             ('var', 'K'),
                                             ('call',
                                              'new_centroid',
                                              [('var', 'X'),
                                               ('var', 'labels'),
                                               ('var', 'j'),
                                               ('index',
                                                'C_old',
                                                ('var', 'j'))])),
                                    'has_loop': False,
                                    'statements': []},
               'data_min': {'params': [('X',
                                        ('tensor',
                                         [('NPTS', 'invariant'),
                                          ('DIM', 'invariant')]))],
                            'return_type': ('tensor', [('DIM', 'invariant')]),
                            'body': ('var', 'm'),
                            'has_loop': False,
                            'statements': [('body_decl',
                                            'm',
                                            ('tensor', [('DIM', 'invariant')]),
                                            ('index', 'X', ('num', 0))),
                                           ('body_for_range',
                                            'i',
                                            ('num', 0),
                                            ('var', 'NPTS'),
                                            [('loop_assign',
                                              'm',
                                              ('mul',
                                               ('sub',
                                                ('add',
                                                 ('var', 'm'),
                                                 ('index',
                                                  'X',
                                                  ('imaginary',))),
                                                ('call',
                                                 'absolute',
                                                 [('sub',
                                                   ('var', 'm'),
                                                   ('index',
                                                    'X',
                                                    ('imaginary',)))])),
                                               ('num', 0.5)))])]},
               'data_max': {'params': [('X',
                                        ('tensor',
                                         [('NPTS', 'invariant'),
                                          ('DIM', 'invariant')]))],
                            'return_type': ('tensor', [('DIM', 'invariant')]),
                            'body': ('var', 'm'),
                            'has_loop': False,
                            'statements': [('body_decl',
                                            'm',
                                            ('tensor', [('DIM', 'invariant')]),
                                            ('index', 'X', ('num', 0))),
                                           ('body_for_range',
                                            'i',
                                            ('num', 0),
                                            ('var', 'NPTS'),
                                            [('loop_assign',
                                              'm',
                                              ('mul',
                                               ('add',
                                                ('add',
                                                 ('var', 'm'),
                                                 ('index',
                                                  'X',
                                                  ('imaginary',))),
                                                ('call',
                                                 'absolute',
                                                 [('sub',
                                                   ('var', 'm'),
                                                   ('index',
                                                    'X',
                                                    ('imaginary',)))])),
                                               ('num', 0.5)))])]},
               'rand_centroid': {'params': [('lo',
                                             ('tensor',
                                              [('DIM', 'invariant')])),
                                            ('hi',
                                             ('tensor',
                                              [('DIM', 'invariant')]))],
                                 'return_type': ('tensor',
                                                 [('DIM', 'invariant')]),
                                 'body': ('add',
                                          ('var', 'lo'),
                                          ('mul',
                                           ('var', 's'),
                                           ('sub',
                                            ('var', 'hi'),
                                            ('var', 'lo')))),
                                 'has_loop': False,
                                 'statements': [('typed_sample',
                                                 's',
                                                 ('tensor',
                                                  [('DIM', 'invariant')]),
                                                 ('call',
                                                  'Uniform',
                                                  [('num', 0.0),
                                                   ('num', 1.0),
                                                   ('var', 'DIM')]))]}},
 'classes': {},
 'program': [('decl', 'SEED', 'ℝ', ('num', 2), 19),
             ('decl', 'K', 'ℝ', ('num', 2), 20),
             ('decl', 'DIM', 'ℝ', ('num', 2), 21),
             ('decl', 'NPTS', 'ℝ', ('num', 15), 22),
             ('decl', 'ITERS', 'ℕ', ('num', 50), 23),
             ('seed', ('var', 'SEED')),
             ('func_def', 'absolute'),
             ('func_def', 'get_sum_of_1d_array'),
             ('func_def', 'sq_dist'),
             ('func_def', 'argmin_vec'),
             ('func_def', 'assign_one'),
             ('func_def', 'assign_labels'),
             ('func_def', 'new_centroid'),
             ('func_def', 'update_centroids'),
             ('func_def', 'data_min'),
             ('func_def', 'data_max'),
             ('func_def', 'rand_centroid'),
             ('decl',
              'X',
              ('tensor', [(15, 'invariant'), (2, 'invariant')]),
              ('array',
               [('array', [('num', 2.0), ('num', 2.2)]),
                ('array', [('num', 2.8), ('num', 2.9)]),
                ('array', [('num', 1.9), ('num', 3.1)]),
                ('array', [('num', 3.1), ('num', 2.0)]),
                ('array', [('num', 2.5), ('num', 2.6)]),
                ('array', [('num', 3.6), ('num', 3.1)]),
                ('array', [('num', 4.1), ('num', 2.7)]),
                ('array', [('num', 3.3), ('num', 3.4)]),
                ('array', [('num', 4.0), ('num', 3.6)]),
                ('array', [('num', 3.7), ('num', 2.9)]),
                ('array', [('num', 3.0), ('num', 4.0)]),
                ('array', [('num', 2.7), ('num', 3.9)]),
                ('array', [('num', 3.4), ('num', 4.2)]),
                ('array', [('num', 2.9), ('num', 3.5)]),
                ('array', [('num', 3.2), ('num', 3.7)])]),
              99),
             ('decl',
              'lo_box',
              ('tensor', [('DIM', 'invariant')]),
              ('call', 'data_min', [('var', 'X')]),
              106),
             ('decl',
              'hi_box',
              ('tensor', [('DIM', 'invariant')]),
              ('call', 'data_max', [('var', 'X')]),
              107),
             ('decl',
              'C',
              ('tensor', [('K', 'invariant'), ('DIM', 'invariant')]),
              ('for_expr',
               'j',
               ('var', 'K'),
               ('call',
                'rand_centroid',
                [('var', 'lo_box'), ('var', 'hi_box')])),
              108),
             ('decl',
              'prev_labels',
              ('tensor', [('NPTS', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'NPTS'),
               ('sub', ('mul', ('imaginary',), ('num', 0.0)), ('num', 1.0))),
              110),
             ('decl',
              'labels',
              ('tensor', [('NPTS', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'NPTS'),
               ('mul', ('imaginary',), ('num', 0.0))),
              111),
             ('decl',
              'converged_at',
              'ℝ',
              ('sub', ('num', 0.0), ('num', 1.0)),
              112),
             ('for_loop_range',
              'step',
              ('num', 0),
              ('var', 'ITERS'),
              [('for_assign',
                'labels',
                ('call', 'assign_labels', [('var', 'X'), ('var', 'C')])),
               ('for_assign',
                'moved',
                ('call',
                 'get_sum_of_1d_array',
                 [('call',
                   'absolute',
                   [('sub', ('var', 'labels'), ('var', 'prev_labels'))])])),
               ('for_if_else',
                ('cond_eq', ('var', 'moved'), ('num', 0.0)),
                [('for_if',
                  ('cond_lt', ('var', 'converged_at'), ('num', 0.0)),
                  [('for_assign', 'converged_at', ('var', 'step'))])],
                [('for_assign',
                  'C',
                  ('call',
                   'update_centroids',
                   [('var', 'X'), ('var', 'labels'), ('var', 'C')]))]),
               ('for_assign', 'prev_labels', ('var', 'labels'))],
              114),
             ('expr', ('call', 'print', [('var', 'converged_at')]), 0),
             ('expr', ('call', 'print', [('var', 'labels')]), 0),
             ('expr', ('call', 'print', [('var', 'C')]), 0)]}
