EXPECTED = {'functions': {'zero_1d_array': {'params': [('len', 'ℝ')],
                                 'return_type': ('tensor',
                                                 [('m', 'invariant')]),
                                 'body': ('var', 'results'),
                                 'has_loop': False,
                                 'statements': [('body_decl',
                                                 'results',
                                                 ('tensor',
                                                  [('len', 'invariant')]),
                                                 ('for_expr',
                                                  'i',
                                                  ('var', 'len'),
                                                  ('mul',
                                                   ('imaginary',),
                                                   ('num', 0))))]},
               'get_1d_array_length': {'params': [('x',
                                                   ('tensor',
                                                    [('m', 'invariant')]))],
                                       'return_type': 'ℝ',
                                       'body': ('var', 'total'),
                                       'has_loop': False,
                                       'statements': [('body_decl',
                                                       'total',
                                                       'ℝ',
                                                       ('num', 0)),
                                                      ('body_decl',
                                                       'temp',
                                                       'ℝ',
                                                       ('num', 0)),
                                                      ('body_for',
                                                       'i',
                                                       [('loop_assign',
                                                         'temp',
                                                         ('index',
                                                          'x',
                                                          ('imaginary',))),
                                                        ('loop_pluseq',
                                                         'total',
                                                         ('num', 1))],
                                                       ['x'])]},
               'append': {'params': [('x', ('tensor', [('m', 'invariant')])),
                                     ('var', 'ℝ')],
                          'return_type': ('tensor', [('n', 'invariant')]),
                          'body': ('var', 'results'),
                          'has_loop': False,
                          'statements': [('body_decl',
                                          'new_length',
                                          'ℝ',
                                          ('add',
                                           ('call',
                                            'get_1d_array_length',
                                            [('var', 'x')]),
                                           ('num', 1))),
                                         ('body_decl',
                                          'results',
                                          ('tensor',
                                           [('new_length', 'invariant')]),
                                          ('call',
                                           'zero_1d_array',
                                           [('var', 'new_length')])),
                                         ('body_decl',
                                          'len_x',
                                          'ℕ',
                                          ('call',
                                           'get_1d_array_length',
                                           [('var', 'x')])),
                                         ('body_for_range',
                                          'i',
                                          ('num', 0),
                                          ('var', 'new_length'),
                                          [('loop_if_else',
                                            ('cond_lt',
                                             ('imaginary',),
                                             ('var', 'len_x')),
                                            [('loop_index_assign_nd',
                                              'results',
                                              [('imaginary',)],
                                              ('index', 'x', ('imaginary',)))],
                                            [('loop_index_assign_nd',
                                              'results',
                                              [('imaginary',)],
                                              ('var', 'var'))])])]},
               'f': {'params': [('y', 'ℝ'), ('θ', 'ℝ')],
                     'return_type': 'ℝ',
                     'body': ('mul', ('neg', ('var', 'θ')), ('var', 'y')),
                     'has_loop': False,
                     'statements': []},
               'solver': {'params': [('θ', 'ℝ')],
                          'return_type': ('tensor', [('m', 'invariant')]),
                          'body': ('var', 'y_array'),
                          'has_loop': False,
                          'statements': [('body_decl', 'y', 'ℝ', ('num', 1.0)),
                                         ('body_decl',
                                          'y_array',
                                          ('tensor', [(1, 'invariant')]),
                                          ('array', [('num', 1.0)])),
                                         ('body_for_range',
                                          'i',
                                          ('num', 0),
                                          ('var', 'timesteps'),
                                          [('loop_assign',
                                            'dy',
                                            ('call',
                                             'f',
                                             [('var', 'y'), ('var', 'θ')])),
                                           ('loop_pluseq',
                                            'y',
                                            ('mul',
                                             ('var', 'dt'),
                                             ('var', 'dy'))),
                                           ('loop_assign',
                                            'y_array',
                                            ('call',
                                             'append',
                                             [('var', 'y_array'),
                                              ('var', 'y')]))])]},
               'calculate_loss': {'params': [('θ', 'ℝ')],
                                  'return_type': 'ℝ',
                                  'body': ('div', ('var', 'L'), ('var', 'm')),
                                  'has_loop': False,
                                  'statements': [('body_decl',
                                                  'y_predicted',
                                                  ('tensor',
                                                   [('n', 'invariant')]),
                                                  ('call',
                                                   'solver',
                                                   [('var', 'θ')])),
                                                 ('body_decl',
                                                  'L',
                                                  'ℝ',
                                                  ('num', 0.0)),
                                                 ('body_decl',
                                                  'm',
                                                  'ℝ',
                                                  ('call',
                                                   'get_1d_array_length',
                                                   [('var', 'y_predicted')])),
                                                 ('body_for_range',
                                                  'i',
                                                  ('num', 0),
                                                  ('var', 'm'),
                                                  [('loop_pluseq',
                                                    'L',
                                                    ('pow',
                                                     ('sub',
                                                      ('index',
                                                       'y_predicted',
                                                       ('imaginary',)),
                                                      ('index',
                                                       'y_true',
                                                       ('imaginary',))),
                                                     ('num', 2)))])]}},
 'classes': {},
 'program': [('func_def', 'zero_1d_array'),
             ('func_def', 'get_1d_array_length'),
             ('func_def', 'append'),
             ('func_def', 'f'),
             ('decl', 'timesteps', 'ℕ', ('num', 10), 31),
             ('decl', 'dt', 'ℝ', ('num', 0.1), 32),
             ('func_def', 'solver'),
             ('decl', 'true_theta', 'ℝ', ('num', 2.0), 43),
             ('decl',
              'y_true',
              ('tensor', [('m', 'invariant')]),
              ('call', 'solver', [('var', 'true_theta')]),
              44),
             ('func_def', 'calculate_loss'),
             ('decl', 'θ', 'ℝ', ('num', 1.0), 54),
             ('decl', 'learning_rate', 'ℝ', ('num', 0.1), 55),
             ('decl', 'epochs', 'ℝ', ('num', 1), 61),
             ('for_loop_range',
              'i',
              ('num', 0),
              ('var', 'epochs'),
              [('for_assign',
                'g',
                ('call', 'grad', [('var', 'calculate_loss'), ('var', 'θ')])),
               ('for_assign',
                'θ',
                ('sub',
                 ('var', 'θ'),
                 ('mul', ('var', 'learning_rate'), ('var', 'g'))))],
              63),
             ('decl',
              'y_predicted',
              ('tensor', [('m', 'invariant')]),
              ('call', 'solver', [('var', 'θ')]),
              67)]}
