EXPECTED = {'functions': {'zero_1d_array': {'params': [('len', 'ℝ')],
                                 'return_type': ('tensor',
                                                 [('m', 'invariant')]),
                                 'body': ('var', 'results'),
                                 'has_loop': False,
                                 'statements': [('body_decl',
                                                 'results',
                                                 ('tensor',
                                                  [('len', 'invariant')]),
                                                 ('for_expr',
                                                  'i',
                                                  ('var', 'len'),
                                                  ('mul',
                                                   ('imaginary',),
                                                   ('num', 0))))]},
               'linspace': {'params': [('start', 'ℝ'),
                                       ('end', 'ℝ'),
                                       ('n', 'ℕ')],
                            'return_type': ('tensor', [('n', 'invariant')]),
                            'body': ('var', 'x'),
                            'has_loop': False,
                            'statements': [('body_decl',
                                            'x',
                                            ('tensor', [('n', 'invariant')]),
                                            ('call',
                                             'zero_1d_array',
                                             [('var', 'n')])),
                                           ('body_decl',
                                            'Δx',
                                            'ℝ',
                                            ('div',
                                             ('sub',
                                              ('var', 'end'),
                                              ('var', 'start')),
                                             ('sub',
                                              ('var', 'n'),
                                              ('num', 1)))),
                                           ('body_for_range',
                                            'i',
                                            ('num', 0),
                                            ('var', 'n'),
                                            [('loop_index_assign_nd',
                                              'x',
                                              [('imaginary',)],
                                              ('add',
                                               ('var', 'start'),
                                               ('mul',
                                                ('imaginary',),
                                                ('var', 'Δx'))))])]},
               'get_1d_array_length': {'params': [('x',
                                                   ('tensor',
                                                    [('m', 'invariant')]))],
                                       'return_type': 'ℝ',
                                       'body': ('var', 'total'),
                                       'has_loop': False,
                                       'statements': [('body_decl',
                                                       'total',
                                                       'ℝ',
                                                       ('num', 0)),
                                                      ('body_decl',
                                                       'temp',
                                                       'ℝ',
                                                       ('num', 0)),
                                                      ('body_for',
                                                       'i',
                                                       [('loop_assign',
                                                         'temp',
                                                         ('index',
                                                          'x',
                                                          ('imaginary',))),
                                                        ('loop_pluseq',
                                                         'total',
                                                         ('num', 1))],
                                                       ['x'])]},
               'get_2d_array_num_rows': {'params': [('x',
                                                     ('tensor',
                                                      [('m', 'invariant'),
                                                       ('n', 'invariant')]))],
                                         'return_type': 'ℝ',
                                         'body': ('var', 'total'),
                                         'has_loop': False,
                                         'statements': [('body_decl',
                                                         'total',
                                                         'ℝ',
                                                         ('num', 0)),
                                                        ('body_decl',
                                                         'temp',
                                                         'ℝ',
                                                         ('num', 0)),
                                                        ('body_for',
                                                         'i',
                                                         [('loop_assign',
                                                           'temp',
                                                           ('index',
                                                            'x',
                                                            ('imaginary',))),
                                                          ('loop_pluseq',
                                                           'total',
                                                           ('num', 1))],
                                                         ['x'])]},
               'zero_complex_2d_array': {'params': [('rows', 'ℝ'),
                                                    ('cols', 'ℝ')],
                                         'return_type': ('tensor',
                                                         [('m', 'invariant'),
                                                          ('n', 'invariant')]),
                                         'body': ('var', 'results'),
                                         'has_loop': False,
                                         'statements': [('body_decl',
                                                         'results',
                                                         ('tensor',
                                                          [('rows',
                                                            'invariant'),
                                                           ('cols',
                                                            'invariant')]),
                                                         ('for_expr',
                                                          'i',
                                                          ('var', 'rows'),
                                                          ('for_expr',
                                                           'j',
                                                           ('var', 'cols'),
                                                           ('mul',
                                                            ('var', 'j'),
                                                            ('complex',
                                                             1j)))))]},
               'append_row': {'params': [('x',
                                          ('tensor',
                                           [('m', 'invariant'),
                                            ('n', 'invariant')])),
                                         ('row',
                                          ('tensor', [('n', 'invariant')]))],
                              'return_type': ('tensor',
                                              [('k', 'invariant'),
                                               ('n', 'invariant')]),
                              'body': ('var', 'new_array'),
                              'has_loop': False,
                              'statements': [('body_decl',
                                              'rows',
                                              'ℝ',
                                              ('call',
                                               'get_2d_array_num_rows',
                                               [('var', 'x')])),
                                             ('body_decl',
                                              'cols',
                                              'ℝ',
                                              ('call',
                                               'get_1d_array_length',
                                               [('index', 'x', ('num', 0))])),
                                             ('body_decl',
                                              'new_rows',
                                              'ℝ',
                                              ('add',
                                               ('var', 'rows'),
                                               ('num', 1))),
                                             ('body_decl',
                                              'new_array',
                                              ('tensor',
                                               [('new_rows', 'invariant'),
                                                ('cols', 'invariant')]),
                                              ('call',
                                               'zero_complex_2d_array',
                                               [('var', 'new_rows'),
                                                ('var', 'cols')])),
                                             ('body_for_range',
                                              'i',
                                              ('num', 0),
                                              ('var', 'rows'),
                                              [('loop_for_range',
                                                'j',
                                                ('num', 0),
                                                ('var', 'cols'),
                                                [('loop_index_assign_nd',
                                                  'new_array',
                                                  [('imaginary',),
                                                   ('var', 'j')],
                                                  ('indexN',
                                                   'x',
                                                   [('imaginary',),
                                                    ('var', 'j')]))])]),
                                             ('body_for_range',
                                              'j',
                                              ('num', 0),
                                              ('var', 'cols'),
                                              [('loop_index_assign_nd',
                                                'new_array',
                                                [('var', 'rows'), ('var', 'j')],
                                                ('index',
                                                 'row',
                                                 ('var', 'j')))])]},
               'schrodinger_rhs': {'params': [('ψ',
                                               ('tensor',
                                                [('m', 'invariant')])),
                                              ('V',
                                               ('tensor',
                                                [('n', 'invariant')])),
                                              ('Δx', 'ℝ'),
                                              ('ℏ', 'ℝ'),
                                              ('mass', 'ℝ')],
                                   'return_type': ('tensor',
                                                   [('o', 'invariant')]),
                                   'body': ('var', 'result'),
                                   'has_loop': False,
                                   'statements': [('body_decl',
                                                   'ψ_xx',
                                                   ('tensor',
                                                    [('Nx', 'invariant')]),
                                                   ('div',
                                                    ('add',
                                                     ('sub',
                                                      ('call',
                                                       'roll',
                                                       [('var', 'ψ'),
                                                        ('neg', ('num', 1))]),
                                                      ('mul',
                                                       ('num', 2),
                                                       ('var', 'ψ'))),
                                                     ('call',
                                                      'roll',
                                                      [('var', 'ψ'),
                                                       ('num', 1)])),
                                                    ('pow',
                                                     ('var', 'Δx'),
                                                     ('num', 2)))),
                                                  ('body_decl',
                                                   'H_ψ',
                                                   ('tensor',
                                                    [('Nx', 'invariant')]),
                                                   ('add',
                                                    ('mul',
                                                     ('neg',
                                                      ('div',
                                                       ('pow',
                                                        ('var', 'ℏ'),
                                                        ('num', 2)),
                                                       ('mul',
                                                        ('num', 2),
                                                        ('var', 'mass')))),
                                                     ('var', 'ψ')),
                                                    ('mul',
                                                     ('var', 'V'),
                                                     ('var', 'ψ')))),
                                                  ('body_decl',
                                                   'result',
                                                   ('tensor',
                                                    [('Nx', 'invariant')]),
                                                   ('mul',
                                                    ('div',
                                                     ('neg', ('complex', 1j)),
                                                     ('var', 'ℏ')),
                                                    ('var', 'H_ψ')))]},
               'make_potential': {'params': [('V_value', 'ℝ')],
                                  'return_type': ('tensor',
                                                  [('m', 'invariant')]),
                                  'body': ('var', 'V'),
                                  'has_loop': False,
                                  'statements': [('body_decl',
                                                  'V',
                                                  ('tensor',
                                                   [('Nx', 'invariant')]),
                                                  ('call',
                                                   'zero_1d_array',
                                                   [('var', 'Nx')])),
                                                 ('body_decl',
                                                  'x',
                                                  ('tensor',
                                                   [('Nx', 'invariant')]),
                                                  ('call',
                                                   'linspace',
                                                   [('neg', ('num', 200)),
                                                    ('num', 200),
                                                    ('var', 'Nx')])),
                                                 ('body_for_range',
                                                  'i',
                                                  ('num', 0),
                                                  ('var', 'Nx'),
                                                  [('loop_if',
                                                    ('cond_lt',
                                                     ('call',
                                                      'abs',
                                                      [('index',
                                                        'x',
                                                        ('imaginary',))]),
                                                     ('num', 15)),
                                                    [('loop_index_assign_nd',
                                                      'V',
                                                      [('imaginary',)],
                                                      ('var', 'V_value'))])])]},
               'RK4_step': {'params': [('ψ', ('tensor', [('m', 'invariant')])),
                                       ('dt', 'ℝ'),
                                       ('V', ('tensor', [('n', 'invariant')])),
                                       ('Δx', 'ℝ'),
                                       ('ℏ', 'ℝ'),
                                       ('mass', 'ℝ')],
                            'return_type': ('tensor', [('o', 'invariant')]),
                            'body': ('var', 'ψ_next'),
                            'has_loop': False,
                            'statements': [('body_decl',
                                            'k1',
                                            ('tensor', [('Nx', 'invariant')]),
                                            ('call',
                                             'schrodinger_rhs',
                                             [('var', 'ψ'),
                                              ('var', 'V'),
                                              ('var', 'Δx'),
                                              ('var', 'ℏ'),
                                              ('var', 'mass')])),
                                           ('body_decl',
                                            'k2',
                                            ('tensor', [('Nx', 'invariant')]),
                                            ('call',
                                             'schrodinger_rhs',
                                             [('add',
                                               ('var', 'ψ'),
                                               ('mul',
                                                ('mul',
                                                 ('num', 0.5),
                                                 ('var', 'dt')),
                                                ('var', 'k1'))),
                                              ('var', 'V'),
                                              ('var', 'Δx'),
                                              ('var', 'ℏ'),
                                              ('var', 'mass')])),
                                           ('body_decl',
                                            'k3',
                                            ('tensor', [('Nx', 'invariant')]),
                                            ('call',
                                             'schrodinger_rhs',
                                             [('add',
                                               ('var', 'ψ'),
                                               ('mul',
                                                ('mul',
                                                 ('num', 0.5),
                                                 ('var', 'dt')),
                                                ('var', 'k2'))),
                                              ('var', 'V'),
                                              ('var', 'Δx'),
                                              ('var', 'ℏ'),
                                              ('var', 'mass')])),
                                           ('body_decl',
                                            'k4',
                                            ('tensor', [('Nx', 'invariant')]),
                                            ('call',
                                             'schrodinger_rhs',
                                             [('add',
                                               ('var', 'ψ'),
                                               ('mul',
                                                ('var', 'dt'),
                                                ('var', 'k3'))),
                                              ('var', 'V'),
                                              ('var', 'Δx'),
                                              ('var', 'ℏ'),
                                              ('var', 'mass')])),
                                           ('body_decl',
                                            'ψ_next',
                                            ('tensor', [('Nx', 'invariant')]),
                                            ('add',
                                             ('var', 'ψ'),
                                             ('mul',
                                              ('div',
                                               ('var', 'dt'),
                                               ('num', 6.0)),
                                              ('add',
                                               ('add',
                                                ('add',
                                                 ('var', 'k1'),
                                                 ('mul',
                                                  ('num', 2),
                                                  ('var', 'k2'))),
                                                ('mul',
                                                 ('num', 2),
                                                 ('var', 'k3'))),
                                               ('var', 'k4')))))]},
               'solver': {'params': [('V', ('tensor', [('m', 'invariant')]))],
                          'return_type': ('tensor',
                                          [('m', 'invariant'),
                                           ('n', 'invariant')]),
                          'body': ('var', 'history'),
                          'has_loop': False,
                          'statements': [('body_decl',
                                          'x',
                                          ('tensor', [('Nx', 'invariant')]),
                                          ('call',
                                           'linspace',
                                           [('neg', ('num', 200)),
                                            ('num', 200),
                                            ('var', 'Nx')])),
                                         ('body_decl',
                                          'ψ0',
                                          ('tensor', [('Nx', 'invariant')]),
                                          ('mul',
                                           ('mul',
                                            ('pow',
                                             ('mul',
                                              ('div', ('num', 1), ('var', 'σ')),
                                              ('call',
                                               'sqrt',
                                               [('num', 3.14)])),
                                             ('num', 0.5)),
                                            ('call',
                                             'exp',
                                             [('mul',
                                               ('mul',
                                                ('complex', 1j),
                                                ('var', 'k0')),
                                               ('var', 'x'))])),
                                           ('call',
                                            'exp',
                                            [('div',
                                              ('neg',
                                               ('pow',
                                                ('sub',
                                                 ('var', 'x'),
                                                 ('var', 'x0')),
                                                ('num', 2))),
                                              ('mul',
                                               ('num', 2),
                                               ('pow',
                                                ('var', 'σ'),
                                                ('num', 2))))]))),
                                         ('body_decl',
                                          'history',
                                          ('tensor',
                                           [(1, 'invariant'),
                                            ('Nx', 'invariant')]),
                                          ('array', [('var', 'ψ0')])),
                                         ('body_decl',
                                          'counter',
                                          'ℕ',
                                          ('num', 0)),
                                         ('body_assign', 'ψ', ('var', 'ψ0')),
                                         ('body_for_range',
                                          'i',
                                          ('num', 0),
                                          ('var', 'Nt'),
                                          [('loop_assign',
                                            'ψ',
                                            ('call',
                                             'RK4_step',
                                             [('var', 'ψ'),
                                              ('var', 'dt'),
                                              ('var', 'V'),
                                              ('var', 'Δx'),
                                              ('var', 'ℏ'),
                                              ('var', 'mass')])),
                                           ('loop_assign',
                                            'counter',
                                            ('add',
                                             ('var', 'counter'),
                                             ('num', 1))),
                                           ('loop_if',
                                            ('cond_eq',
                                             ('var', 'counter'),
                                             ('num', 5)),
                                            [('loop_assign',
                                              'history',
                                              ('call',
                                               'append_row',
                                               [('var', 'history'),
                                                ('var', 'ψ')])),
                                             ('loop_assign',
                                              'counter',
                                              ('num', 0))])])]},
               'calculate_loss': {'params': [('barrier_height', 'ℝ')],
                                  'return_type': 'ℝ',
                                  'body': ('var', 'loss'),
                                  'has_loop': False,
                                  'statements': [('body_decl',
                                                  'V_current',
                                                  ('tensor',
                                                   [('Nx', 'invariant')]),
                                                  ('call',
                                                   'make_potential',
                                                   [('var',
                                                     'barrier_height')])),
                                                 ('body_decl',
                                                  'pred',
                                                  ('tensor',
                                                   [('m', 'invariant'),
                                                    ('n', 'invariant')]),
                                                  ('call',
                                                   'solver',
                                                   [('var', 'V_current')])),
                                                 ('body_decl',
                                                  'loss',
                                                  'ℝ',
                                                  ('call',
                                                   'mean',
                                                   [('pow',
                                                     ('call',
                                                      'abs',
                                                      [('sub',
                                                        ('var', 'pred'),
                                                        ('var',
                                                         'true_values'))]),
                                                     ('num', 2))]))]},
               'adam': {'params': [('bh', 'ℝ'),
                                   ('g', 'ℝ'),
                                   ('m', 'ℝ'),
                                   ('v', 'ℝ'),
                                   ('t', 'ℝ'),
                                   ('lr', 'ℝ')],
                        'return_type': ('tensor', [(4, 'invariant')]),
                        'body': ('array',
                                 [('var', 'bh_new'),
                                  ('var', 'm_new'),
                                  ('var', 'v_new'),
                                  ('add', ('var', 't'), ('num', 1.0))]),
                        'has_loop': False,
                        'statements': [('body_decl', 'β1', 'ℝ', ('num', 0.9)),
                                       ('body_decl', 'β2', 'ℝ', ('num', 0.999)),
                                       ('body_decl', 'ε', 'ℝ', ('num', 1e-08)),
                                       ('body_decl',
                                        'm_new',
                                        'ℝ',
                                        ('add',
                                         ('mul', ('var', 'β1'), ('var', 'm')),
                                         ('mul',
                                          ('sub', ('num', 1.0), ('var', 'β1')),
                                          ('var', 'g')))),
                                       ('body_decl',
                                        'v_new',
                                        'ℝ',
                                        ('add',
                                         ('mul', ('var', 'β2'), ('var', 'v')),
                                         ('mul',
                                          ('sub', ('num', 1.0), ('var', 'β2')),
                                          ('pow', ('var', 'g'), ('num', 2))))),
                                       ('body_decl',
                                        'm_hat',
                                        'ℝ',
                                        ('div',
                                         ('var', 'm_new'),
                                         ('sub',
                                          ('num', 1.0),
                                          ('pow',
                                           ('var', 'β1'),
                                           ('var', 't'))))),
                                       ('body_decl',
                                        'v_hat',
                                        'ℝ',
                                        ('div',
                                         ('var', 'v_new'),
                                         ('sub',
                                          ('num', 1.0),
                                          ('pow',
                                           ('var', 'β2'),
                                           ('var', 't'))))),
                                       ('body_decl',
                                        'bh_new',
                                        'ℝ',
                                        ('sub',
                                         ('var', 'bh'),
                                         ('div',
                                          ('mul',
                                           ('var', 'lr'),
                                           ('var', 'm_hat')),
                                          ('add',
                                           ('call', 'sqrt', [('var', 'v_hat')]),
                                           ('var', 'ε')))))]}},
 'classes': {},
 'program': [('func_def', 'zero_1d_array'),
             ('func_def', 'linspace'),
             ('func_def', 'get_1d_array_length'),
             ('func_def', 'get_2d_array_num_rows'),
             ('func_def', 'zero_complex_2d_array'),
             ('func_def', 'append_row'),
             ('decl', 'Nx', 'ℕ', ('num', 102), 49),
             ('decl', 'Nt', 'ℕ', ('num', 327), 51),
             ('decl',
              'x',
              ('tensor', [('Nx', 'invariant')]),
              ('call',
               'linspace',
               [('neg', ('num', 200)), ('num', 200), ('var', 'Nx')]),
              55),
             ('decl', 'Δx', 'ℝ', ('num', 0.391), 56),
             ('decl', 'ℏ', 'ℝ', ('num', 1.0), 58),
             ('decl', 'mass', 'ℝ', ('num', 1.0), 59),
             ('decl', 'cfl_factor', 'ℝ', ('num', 0.2), 61),
             ('decl',
              'dt',
              'ℝ',
              ('div',
               ('mul',
                ('var', 'cfl_factor'),
                ('pow', ('mul', ('var', 'mass'), ('var', 'Δx')), ('num', 2))),
               ('var', 'ℏ')),
              62),
             ('decl', 't_final', 'ℝ', ('num', 100.0), 63),
             ('decl', 'x0', 'ℝ', ('neg', ('num', 50.0)), 65),
             ('decl', 'k0', 'ℝ', ('num', 2.0), 66),
             ('decl', 'σ', 'ℝ', ('num', 10.0), 67),
             ('decl',
              'ψ0',
              ('tensor', [('Nx', 'invariant')]),
              ('mul',
               ('mul',
                ('pow',
                 ('mul',
                  ('div', ('num', 1), ('var', 'σ')),
                  ('call', 'sqrt', [('num', 3.14)])),
                 ('num', 0.5)),
                ('call',
                 'exp',
                 [('mul',
                   ('mul', ('complex', 1j), ('var', 'k0')),
                   ('var', 'x'))])),
               ('call',
                'exp',
                [('div',
                  ('neg',
                   ('pow', ('sub', ('var', 'x'), ('var', 'x0')), ('num', 2))),
                  ('pow', ('mul', ('num', 2), ('var', 'σ')), ('num', 2)))])),
              69),
             ('func_def', 'schrodinger_rhs'),
             ('func_def', 'make_potential'),
             ('func_def', 'RK4_step'),
             ('func_def', 'solver'),
             ('decl',
              'V',
              ('tensor', [('Nx', 'invariant')]),
              ('call', 'make_potential', [('num', 1.8)]),
              113),
             ('decl',
              'true_values',
              ('tensor', [('m', 'invariant'), ('n', 'invariant')]),
              ('call', 'solver', [('var', 'V')]),
              114),
             ('decl', 'guess_barrier_height', 'ℝ', ('num', 6.0), 117),
             ('decl',
              'guess_V',
              ('tensor', [('Nx', 'invariant')]),
              ('call', 'make_potential', [('var', 'guess_barrier_height')]),
              118),
             ('decl',
              'guess_values',
              ('tensor', [('m', 'invariant'), ('n', 'invariant')]),
              ('call', 'solver', [('var', 'guess_V')]),
              119),
             ('func_def', 'calculate_loss'),
             ('func_def', 'adam'),
             ('decl', 'm_adam', 'ℝ', ('num', 0.0), 141),
             ('decl', 'v_adam', 'ℝ', ('num', 0.0), 142),
             ('decl', 't_adam', 'ℝ', ('num', 1.0), 143),
             ('decl', 'lr', 'ℝ', ('num', 0.1), 144),
             ('decl', 'epochs', 'ℕ', ('num', 1), 146),
             ('for_loop_range',
              'i',
              ('num', 0),
              ('var', 'epochs'),
              [('for_call', 'physika_print', [('imaginary',)]),
               ('for_assign',
                'g',
                ('call',
                 'grad',
                 [('var', 'calculate_loss'), ('var', 'guess_barrier_height')])),
               ('for_assign',
                'result',
                ('call',
                 'adam',
                 [('var', 'guess_barrier_height'),
                  ('var', 'g'),
                  ('var', 'm_adam'),
                  ('var', 'v_adam'),
                  ('var', 't_adam'),
                  ('var', 'lr')])),
               ('for_assign',
                'guess_barrier_height',
                ('index', 'result', ('num', 0))),
               ('for_assign', 'm_adam', ('index', 'result', ('num', 1))),
               ('for_assign', 'v_adam', ('index', 'result', ('num', 2))),
               ('for_assign', 't_adam', ('index', 'result', ('num', 3)))],
              148),
             ('decl',
              'pred_V',
              ('tensor', [('Nx', 'invariant')]),
              ('call', 'make_potential', [('var', 'guess_barrier_height')]),
              157),
             ('decl',
              'pred_results',
              ('tensor', [('m', 'invariant'), ('n', 'invariant')]),
              ('call', 'solver', [('var', 'pred_V')]),
              158)]}
