EXPECTED = {'functions': {'get_1d_array_length': {'params': [('x',
                                                   ('tensor',
                                                    [('m', 'invariant')]))],
                                       'return_type': 'ℝ',
                                       'body': ('var', 'total'),
                                       'has_loop': False,
                                       'statements': [('body_decl',
                                                       'total',
                                                       'ℝ',
                                                       ('num', 0)),
                                                      ('body_decl',
                                                       'temp',
                                                       'ℝ',
                                                       ('num', 0)),
                                                      ('body_for',
                                                       'i',
                                                       [('loop_assign',
                                                         'temp',
                                                         ('index',
                                                          'x',
                                                          ('imaginary',))),
                                                        ('loop_pluseq',
                                                         'total',
                                                         ('num', 1))],
                                                       ['x'])]},
               'zero_1d_array': {'params': [('len', 'ℝ')],
                                 'return_type': ('tensor',
                                                 [('m', 'invariant')]),
                                 'body': ('var', 'results'),
                                 'has_loop': False,
                                 'statements': [('body_decl',
                                                 'results',
                                                 ('tensor',
                                                  [('len', 'invariant')]),
                                                 ('for_expr',
                                                  'i',
                                                  ('var', 'len'),
                                                  ('mul',
                                                   ('imaginary',),
                                                   ('num', 0))))]},
               'linspace': {'params': [('start', 'ℝ'),
                                       ('end', 'ℝ'),
                                       ('n', 'ℕ')],
                            'return_type': ('tensor', [('n', 'invariant')]),
                            'body': ('var', 'x'),
                            'has_loop': False,
                            'statements': [('body_decl',
                                            'x',
                                            ('tensor', [('n', 'invariant')]),
                                            ('call',
                                             'zero_1d_array',
                                             [('var', 'n')])),
                                           ('body_decl',
                                            'dx',
                                            'ℝ',
                                            ('div',
                                             ('sub',
                                              ('var', 'end'),
                                              ('var', 'start')),
                                             ('sub',
                                              ('var', 'n'),
                                              ('num', 1)))),
                                           ('body_for_range',
                                            'i',
                                            ('num', 0),
                                            ('var', 'n'),
                                            [('loop_index_assign_nd',
                                              'x',
                                              [('imaginary',)],
                                              ('add',
                                               ('var', 'start'),
                                               ('mul',
                                                ('imaginary',),
                                                ('var', 'dx'))))])]},
               'wave_equation': {'params': [('u',
                                             ('tensor', [('m', 'invariant')])),
                                            ('dx', 'ℝ'),
                                            ('c', 'ℝ')],
                                 'return_type': ('tensor',
                                                 [('m', 'invariant')]),
                                 'body': ('var', 'f'),
                                 'has_loop': False,
                                 'statements': [('body_decl',
                                                 'nx',
                                                 'ℕ',
                                                 ('call',
                                                  'get_1d_array_length',
                                                  [('var', 'u')])),
                                                ('body_decl',
                                                 'f',
                                                 ('tensor',
                                                  [('m', 'invariant')]),
                                                 ('call',
                                                  'zero_1d_array',
                                                  [('var', 'nx')])),
                                                ('body_for_range',
                                                 'i',
                                                 ('num', 1),
                                                 ('sub',
                                                  ('var', 'nx'),
                                                  ('num', 1)),
                                                 [('loop_index_assign_nd',
                                                   'f',
                                                   [('imaginary',)],
                                                   ('mul',
                                                    ('div',
                                                     ('pow',
                                                      ('var', 'c'),
                                                      ('num', 2)),
                                                     ('pow',
                                                      ('var', 'dx'),
                                                      ('num', 2))),
                                                    ('add',
                                                     ('sub',
                                                      ('index',
                                                       'u',
                                                       ('sub',
                                                        ('imaginary',),
                                                        ('num', 1))),
                                                      ('mul',
                                                       ('num', 2),
                                                       ('index',
                                                        'u',
                                                        ('imaginary',)))),
                                                     ('index',
                                                      'u',
                                                      ('add',
                                                       ('imaginary',),
                                                       ('num', 1))))))])]},
               'solver': {'params': [('c', 'ℝ'),
                                     ('u0', ('tensor', [('m', 'invariant')])),
                                     ('dx', 'ℝ'),
                                     ('dt', 'ℝ'),
                                     ('nt', 'ℝ')],
                          'return_type': ('tensor', [('m', 'invariant')]),
                          'body': ('var', 'u_curr'),
                          'has_loop': False,
                          'statements': [('body_decl',
                                          'u_prev',
                                          ('tensor', [('m', 'invariant')]),
                                          ('var', 'u0')),
                                         ('body_decl',
                                          'u_curr',
                                          ('tensor', [('m', 'invariant')]),
                                          ('var', 'u0')),
                                         ('body_decl',
                                          'nx',
                                          'ℕ',
                                          ('call',
                                           'get_1d_array_length',
                                           [('var', 'u0')])),
                                         ('body_for_range',
                                          'n',
                                          ('num', 0),
                                          ('var', 'nt'),
                                          [('loop_assign',
                                            'accel',
                                            ('call',
                                             'wave_equation',
                                             [('var', 'u_curr'),
                                              ('var', 'dx'),
                                              ('var', 'c')])),
                                           ('loop_assign',
                                            'u_next',
                                            ('add',
                                             ('sub',
                                              ('mul',
                                               ('num', 2),
                                               ('var', 'u_curr')),
                                              ('var', 'u_prev')),
                                             ('mul',
                                              ('pow',
                                               ('var', 'dt'),
                                               ('num', 2)),
                                              ('var', 'accel')))),
                                           ('loop_index_assign_nd',
                                            'u_next',
                                            [('num', 0)],
                                            ('num', 0)),
                                           ('loop_index_assign_nd',
                                            'u_next',
                                            [('sub',
                                              ('var', 'nx'),
                                              ('num', 1))],
                                            ('num', 0)),
                                           ('loop_assign',
                                            'u_prev',
                                            ('var', 'u_curr')),
                                           ('loop_assign',
                                            'u_curr',
                                            ('var', 'u_next'))])]},
               'calculate_loss': {'params': [('c', 'ℝ')],
                                  'return_type': 'ℝ',
                                  'body': ('div',
                                           ('var', 'loss'),
                                           ('var', 'nx')),
                                  'has_loop': False,
                                  'statements': [('body_decl',
                                                  'predictions',
                                                  ('tensor',
                                                   [('m', 'invariant')]),
                                                  ('call',
                                                   'solver',
                                                   [('var', 'c'),
                                                    ('var', 'u0'),
                                                    ('var', 'dx'),
                                                    ('var', 'dt'),
                                                    ('var', 'nt')])),
                                                 ('body_decl',
                                                  'loss',
                                                  'ℝ',
                                                  ('num', 0.0)),
                                                 ('body_for_range',
                                                  'i',
                                                  ('num', 0),
                                                  ('var', 'nx'),
                                                  [('loop_assign',
                                                    'diff',
                                                    ('sub',
                                                     ('index',
                                                      'predictions',
                                                      ('imaginary',)),
                                                     ('index',
                                                      'true_values',
                                                      ('imaginary',)))),
                                                   ('loop_pluseq',
                                                    'loss',
                                                    ('pow',
                                                     ('var', 'diff'),
                                                     ('num', 2)))])]}},
 'classes': {},
 'program': [('func_def', 'get_1d_array_length'),
             ('func_def', 'zero_1d_array'),
             ('func_def', 'linspace'),
             ('func_def', 'wave_equation'),
             ('func_def', 'solver'),
             ('decl', 'nx', 'ℝ', ('num', 30), 40),
             ('decl', 'nt', 'ℝ', ('num', 30), 41),
             ('decl', 'a', 'ℝ', ('num', 0), 43),
             ('decl', 'b', 'ℝ', ('num', 1), 44),
             ('decl', 't0', 'ℝ', ('num', 0), 45),
             ('decl', 'tf', 'ℝ', ('num', 1), 46),
             ('decl',
              'dx',
              'ℝ',
              ('div',
               ('sub', ('var', 'b'), ('var', 'a')),
               ('sub', ('var', 'nx'), ('num', 1))),
              48),
             ('decl',
              'dt',
              'ℝ',
              ('div',
               ('sub', ('var', 'tf'), ('var', 't0')),
               ('sub', ('var', 'nt'), ('num', 1))),
              49),
             ('decl', 'pi', 'ℝ', ('num', 3.14), 52),
             ('decl', 'true_c', 'ℝ', ('num', 0.5), 53),
             ('decl',
              'x',
              ('tensor', [('m', 'invariant')]),
              ('call', 'linspace', [('var', 'a'), ('var', 'b'), ('var', 'nx')]),
              55),
             ('decl',
              'u0',
              ('tensor', [('nx', 'invariant')]),
              ('call', 'zero_1d_array', [('var', 'nx')]),
              56),
             ('for_loop_range',
              'i',
              ('num', 0),
              ('var', 'nx'),
              [('for_index_assign_nd',
                'u0',
                [('imaginary',)],
                ('call',
                 'sin',
                 [('mul',
                   ('mul', ('num', 2), ('var', 'pi')),
                   ('index', 'x', ('imaginary',)))]))],
              57),
             ('decl',
              'true_values',
              ('tensor', [('m', 'invariant')]),
              ('call',
               'solver',
               [('var', 'true_c'),
                ('var', 'u0'),
                ('var', 'dx'),
                ('var', 'dt'),
                ('var', 'nt')]),
              61),
             ('func_def', 'calculate_loss'),
             ('decl', 'c', 'ℝ', ('num', 0.1), 73),
             ('decl', 'learning_rate', 'ℝ', ('num', 0.01), 74),
             ('decl', 'epochs', 'ℕ', ('num', 1), 75),
             ('for_loop_range',
              'i',
              ('num', 0),
              ('var', 'epochs'),
              [('for_call', 'physika_print', [('imaginary',)]),
               ('for_assign',
                'g',
                ('call', 'grad', [('var', 'calculate_loss'), ('var', 'c')])),
               ('for_assign',
                'c',
                ('sub',
                 ('var', 'c'),
                 ('mul', ('var', 'learning_rate'), ('var', 'g'))))],
              77),
             ('decl',
              'pred_values',
              ('tensor', [('m', 'invariant')]),
              ('call',
               'solver',
               [('var', 'c'),
                ('var', 'u0'),
                ('var', 'dx'),
                ('var', 'dt'),
                ('var', 'nt')]),
              82)]}
