EXPECTED = {'functions': {'get_1d_array_length': {'params': [('x',
                                                   ('tensor',
                                                    [('m', 'invariant')]))],
                                       'return_type': 'ℝ',
                                       'body': ('var', 'total'),
                                       'has_loop': False,
                                       'statements': [('body_decl',
                                                       'total',
                                                       'ℝ',
                                                       ('num', 0)),
                                                      ('body_decl',
                                                       'temp',
                                                       'ℝ',
                                                       ('num', 0)),
                                                      ('body_for',
                                                       'i',
                                                       [('loop_assign',
                                                         'temp',
                                                         ('index',
                                                          'x',
                                                          ('imaginary',))),
                                                        ('loop_pluseq',
                                                         'total',
                                                         ('num', 1))],
                                                       ['x'])]},
               'get_2d_array_num_rows': {'params': [('x',
                                                     ('tensor',
                                                      [('m', 'invariant'),
                                                       ('n', 'invariant')]))],
                                         'return_type': 'ℝ',
                                         'body': ('var', 'total'),
                                         'has_loop': False,
                                         'statements': [('body_decl',
                                                         'total',
                                                         'ℝ',
                                                         ('num', 0)),
                                                        ('body_decl',
                                                         'temp',
                                                         'ℝ',
                                                         ('num', 0)),
                                                        ('body_for',
                                                         'i',
                                                         [('loop_assign',
                                                           'temp',
                                                           ('index',
                                                            'x',
                                                            ('imaginary',))),
                                                          ('loop_pluseq',
                                                           'total',
                                                           ('num', 1))],
                                                         ['x'])]},
               'get_2d_array_num_cols': {'params': [('x',
                                                     ('tensor',
                                                      [('m', 'invariant'),
                                                       ('n', 'invariant')]))],
                                         'return_type': 'ℝ',
                                         'body': ('call',
                                                  'get_1d_array_length',
                                                  [('index', 'x', ('num', 0))]),
                                         'has_loop': False,
                                         'statements': []},
               'arange': {'params': [('n', 'ℕ')],
                          'return_type': ('tensor', [('n', 'invariant')]),
                          'body': ('var', 'arr'),
                          'has_loop': False,
                          'statements': [('body_decl',
                                          'arr',
                                          ('tensor', [('n', 'invariant')]),
                                          ('for_expr',
                                           'i',
                                           ('var', 'n'),
                                           ('imaginary',)))]},
               'gaussian_solve': {'params': [('A',
                                              ('tensor',
                                               [('m', 'invariant'),
                                                ('n', 'invariant')])),
                                             ('b',
                                              ('tensor',
                                               [('n', 'invariant')]))],
                                  'return_type': ('tensor',
                                                  [('m', 'invariant')]),
                                  'body': ('var', 'x'),
                                  'has_loop': False,
                                  'statements': [('body_decl',
                                                  'a_row',
                                                  'ℝ',
                                                  ('call',
                                                   'get_2d_array_num_rows',
                                                   [('var', 'A')])),
                                                 ('body_decl',
                                                  'a_col',
                                                  'ℝ',
                                                  ('call',
                                                   'get_2d_array_num_cols',
                                                   [('var', 'A')])),
                                                 ('body_decl',
                                                  'new_col',
                                                  'ℝ',
                                                  ('add',
                                                   ('var', 'a_col'),
                                                   ('num', 1))),
                                                 ('body_decl',
                                                  'aug',
                                                  ('tensor',
                                                   [('a_row', 'invariant'),
                                                    ('new_col', 'invariant')]),
                                                  ('call',
                                                   'zeros',
                                                   [('var', 'a_row'),
                                                    ('var', 'new_col')])),
                                                 ('body_for_range',
                                                  'i',
                                                  ('num', 0),
                                                  ('var', 'a_row'),
                                                  [('loop_index_assign_nd',
                                                    'aug',
                                                    [('index_item',
                                                      ('imaginary',)),
                                                     ('slice_item',
                                                      None,
                                                      ('var', 'a_col'))],
                                                    ('indexN',
                                                     'A',
                                                     [('index_item',
                                                       ('imaginary',)),
                                                      ('slice_item',
                                                       None,
                                                       None)])),
                                                   ('loop_index_assign_nd',
                                                    'aug',
                                                    [('index_item',
                                                      ('imaginary',)),
                                                     ('index_item',
                                                      ('var', 'a_col'))],
                                                    ('index',
                                                     'b',
                                                     ('imaginary',)))]),
                                                 ('body_decl',
                                                  'row_buffer',
                                                  ('tensor',
                                                   [('new_col', 'invariant')]),
                                                  ('call',
                                                   'zeros',
                                                   [('var', 'new_col')])),
                                                 ('body_for_range',
                                                  'i',
                                                  ('num', 0),
                                                  ('var', 'a_row'),
                                                  [('loop_assign',
                                                    'max_row',
                                                    ('imaginary',)),
                                                   ('loop_for_range',
                                                    'k',
                                                    ('add',
                                                     ('imaginary',),
                                                     ('num', 1)),
                                                    ('var', 'a_row'),
                                                    [('loop_if',
                                                      ('cond_gt',
                                                       ('call',
                                                        'abs',
                                                        [('indexN',
                                                          'aug',
                                                          [('index_item',
                                                            ('var', 'k')),
                                                           ('index_item',
                                                            ('imaginary',))])]),
                                                       ('call',
                                                        'abs',
                                                        [('indexN',
                                                          'aug',
                                                          [('index_item',
                                                            ('var', 'max_row')),
                                                           ('index_item',
                                                            ('imaginary',))])])),
                                                      [('loop_assign',
                                                        'max_row',
                                                        ('var', 'k'))])]),
                                                   ('loop_if',
                                                    ('cond_neq',
                                                     ('var', 'max_row'),
                                                     ('imaginary',)),
                                                    [('loop_for_range',
                                                      'k',
                                                      ('num', 0),
                                                      ('var', 'new_col'),
                                                      [('loop_index_assign_nd',
                                                        'row_buffer',
                                                        [('index_item',
                                                          ('var', 'k'))],
                                                        ('indexN',
                                                         'aug',
                                                         [('index_item',
                                                           ('imaginary',)),
                                                          ('index_item',
                                                           ('var', 'k'))]))]),
                                                     ('loop_for_range',
                                                      'k',
                                                      ('num', 0),
                                                      ('var', 'new_col'),
                                                      [('loop_index_assign_nd',
                                                        'aug',
                                                        [('index_item',
                                                          ('imaginary',)),
                                                         ('index_item',
                                                          ('var', 'k'))],
                                                        ('indexN',
                                                         'aug',
                                                         [('index_item',
                                                           ('var', 'max_row')),
                                                          ('index_item',
                                                           ('var', 'k'))]))]),
                                                     ('loop_for_range',
                                                      'k',
                                                      ('num', 0),
                                                      ('var', 'new_col'),
                                                      [('loop_index_assign_nd',
                                                        'aug',
                                                        [('index_item',
                                                          ('var', 'max_row')),
                                                         ('index_item',
                                                          ('var', 'k'))],
                                                        ('index',
                                                         'row_buffer',
                                                         ('var', 'k')))])]),
                                                   ('loop_for_range',
                                                    'j',
                                                    ('add',
                                                     ('imaginary',),
                                                     ('num', 1)),
                                                    ('var', 'a_row'),
                                                    [('loop_assign',
                                                      'factor',
                                                      ('div',
                                                       ('indexN',
                                                        'aug',
                                                        [('index_item',
                                                          ('var', 'j')),
                                                         ('index_item',
                                                          ('imaginary',))]),
                                                       ('indexN',
                                                        'aug',
                                                        [('index_item',
                                                          ('imaginary',)),
                                                         ('index_item',
                                                          ('imaginary',))]))),
                                                     ('loop_for_range',
                                                      'k',
                                                      ('imaginary',),
                                                      ('var', 'new_col'),
                                                      [('loop_index_assign_nd',
                                                        'aug',
                                                        [('index_item',
                                                          ('var', 'j')),
                                                         ('index_item',
                                                          ('var', 'k'))],
                                                        ('sub',
                                                         ('indexN',
                                                          'aug',
                                                          [('index_item',
                                                            ('var', 'j')),
                                                           ('index_item',
                                                            ('var', 'k'))]),
                                                         ('mul',
                                                          ('var', 'factor'),
                                                          ('indexN',
                                                           'aug',
                                                           [('index_item',
                                                             ('imaginary',)),
                                                            ('index_item',
                                                             ('var',
                                                              'k'))]))))])])]),
                                                 ('body_decl',
                                                  'x',
                                                  ('tensor',
                                                   [('a_col', 'invariant')]),
                                                  ('call',
                                                   'zeros',
                                                   [('var', 'a_col')])),
                                                 ('body_for_range',
                                                  'i',
                                                  ('num', 0),
                                                  ('var', 'a_col'),
                                                  [('loop_assign',
                                                    'idx',
                                                    ('sub',
                                                     ('sub',
                                                      ('var', 'a_col'),
                                                      ('num', 1)),
                                                     ('imaginary',))),
                                                   ('loop_assign',
                                                    'total',
                                                    ('indexN',
                                                     'aug',
                                                     [('index_item',
                                                       ('var', 'idx')),
                                                      ('index_item',
                                                       ('var', 'a_col'))])),
                                                   ('loop_for_range',
                                                    'j',
                                                    ('add',
                                                     ('var', 'idx'),
                                                     ('num', 1)),
                                                    ('var', 'a_row'),
                                                    [('loop_assign',
                                                      'total',
                                                      ('sub',
                                                       ('var', 'total'),
                                                       ('mul',
                                                        ('indexN',
                                                         'aug',
                                                         [('index_item',
                                                           ('var', 'idx')),
                                                          ('index_item',
                                                           ('var', 'j'))]),
                                                        ('index',
                                                         'x',
                                                         ('var', 'j')))))]),
                                                   ('loop_index_assign_nd',
                                                    'x',
                                                    [('index_item',
                                                      ('var', 'idx'))],
                                                    ('div',
                                                     ('var', 'total'),
                                                     ('indexN',
                                                      'aug',
                                                      [('index_item',
                                                        ('var', 'idx')),
                                                       ('index_item',
                                                        ('var',
                                                         'idx'))])))])]}},
 'classes': {},
 'program': [('func_def', 'get_1d_array_length'),
             ('func_def', 'get_2d_array_num_rows'),
             ('func_def', 'get_2d_array_num_cols'),
             ('func_def', 'arange'),
             ('func_def', 'gaussian_solve'),
             ('decl',
              'A',
              ('tensor', [(3, 'invariant'), (3, 'invariant')]),
              ('array',
               [('array', [('num', 1), ('num', 2), ('num', 1)]),
                ('array', [('num', 3), ('num', 1), ('neg', ('num', 1))]),
                ('array', [('num', 2), ('neg', ('num', 1)), ('num', 1)])]),
              85),
             ('decl',
              'b',
              ('tensor', [(3, 'invariant')]),
              ('array', [('num', 8), ('num', 2), ('num', 3)]),
              90),
             ('expr',
              ('call', 'gaussian_solve', [('var', 'A'), ('var', 'b')]),
              0)]}
