EXPECTED = {'functions': {'zero_1d_array': {'params': [('len', 'ℝ')],
                                 'return_type': ('tensor',
                                                 [('m', 'invariant')]),
                                 'body': ('var', 'results'),
                                 'has_loop': False,
                                 'statements': [('body_decl',
                                                 'results',
                                                 ('tensor',
                                                  [('len', 'invariant')]),
                                                 ('for_expr',
                                                  'i',
                                                  ('var', 'len'),
                                                  ('mul',
                                                   ('imaginary',),
                                                   ('num', 0))))]},
               'zero_2d_array': {'params': [('rows', 'ℝ'), ('cols', 'ℝ')],
                                 'return_type': ('tensor',
                                                 [('m', 'invariant'),
                                                  ('n', 'invariant')]),
                                 'body': ('var', 'results'),
                                 'has_loop': False,
                                 'statements': [('body_decl',
                                                 'results',
                                                 ('tensor',
                                                  [('rows', 'invariant'),
                                                   ('cols', 'invariant')]),
                                                 ('for_expr',
                                                  'i',
                                                  ('var', 'rows'),
                                                  ('for_expr',
                                                   'j',
                                                   ('var', 'cols'),
                                                   ('mul',
                                                    ('var', 'j'),
                                                    ('num', 0)))))]},
               'linspace': {'params': [('start', 'ℝ'),
                                       ('end', 'ℝ'),
                                       ('n', 'ℕ')],
                            'return_type': ('tensor', [('n', 'invariant')]),
                            'body': ('var', 'x'),
                            'has_loop': False,
                            'statements': [('body_decl',
                                            'x',
                                            ('tensor', [('n', 'invariant')]),
                                            ('call',
                                             'zero_1d_array',
                                             [('var', 'n')])),
                                           ('body_decl',
                                            'Δx',
                                            'ℝ',
                                            ('div',
                                             ('sub',
                                              ('var', 'end'),
                                              ('var', 'start')),
                                             ('sub',
                                              ('var', 'n'),
                                              ('num', 1)))),
                                           ('body_for_range',
                                            'i',
                                            ('num', 0),
                                            ('var', 'n'),
                                            [('loop_index_assign_nd',
                                              'x',
                                              [('index_item', ('imaginary',))],
                                              ('add',
                                               ('var', 'start'),
                                               ('mul',
                                                ('imaginary',),
                                                ('var', 'Δx'))))])]},
               'append': {'params': [('x', ('tensor', [(1, 'invariant')])),
                                     ('var', 'ℝ')],
                          'return_type': ('tensor', [('n', 'invariant')]),
                          'body': ('var', 'results'),
                          'has_loop': False,
                          'statements': [('body_decl',
                                          'new_length',
                                          'ℝ',
                                          ('add',
                                           ('call', 'len', [('var', 'x')]),
                                           ('num', 1))),
                                         ('body_decl',
                                          'results',
                                          ('tensor',
                                           [('new_length', 'invariant')]),
                                          ('call',
                                           'zero_1d_array',
                                           [('var', 'new_length')])),
                                         ('body_decl',
                                          'len_x',
                                          'ℕ',
                                          ('call',
                                           'get_1d_array_length',
                                           [('var', 'x')])),
                                         ('body_for_range',
                                          'i',
                                          ('num', 0),
                                          ('var', 'new_length'),
                                          [('loop_if_else',
                                            ('cond_lt',
                                             ('imaginary',),
                                             ('var', 'len_x')),
                                            [('loop_index_assign_nd',
                                              'results',
                                              [('index_item', ('imaginary',))],
                                              ('index', 'x', ('imaginary',)))],
                                            [('loop_index_assign_nd',
                                              'results',
                                              [('index_item', ('imaginary',))],
                                              ('var', 'var'))])])]},
               'central_difference': {'params': [('u',
                                                  ('tensor',
                                                   [('m', 'invariant')])),
                                                 ('j', 'ℕ')],
                                      'return_type': 'ℝ',
                                      'body': ('div',
                                               ('add',
                                                ('sub',
                                                 ('index',
                                                  'u',
                                                  ('sub',
                                                   ('var', 'j'),
                                                   ('num', 1))),
                                                 ('mul',
                                                  ('num', 2),
                                                  ('index',
                                                   'u',
                                                   ('var', 'j')))),
                                                ('index',
                                                 'u',
                                                 ('add',
                                                  ('var', 'j'),
                                                  ('num', 1)))),
                                               ('pow',
                                                ('var', 'Δx'),
                                                ('num', 2))),
                                      'has_loop': False,
                                      'statements': []},
               'helmholtz_equation': {'params': [('u',
                                                  ('tensor',
                                                   [('m', 'invariant')])),
                                                 ('j', 'ℕ'),
                                                 ('k', 'ℝ')],
                                      'return_type': 'ℝ',
                                      'body': ('add',
                                               ('call',
                                                'central_difference',
                                                [('var', 'u'), ('var', 'j')]),
                                               ('mul',
                                                ('pow',
                                                 ('var', 'k'),
                                                 ('num', 2)),
                                                ('index', 'u', ('var', 'j')))),
                                      'has_loop': False,
                                      'statements': []},
               'get_row_coeffs': {'params': [('j', 'ℕ'), ('k', 'ℝ')],
                                  'return_type': ('tensor', [(3, 'invariant')]),
                                  'body': ('array',
                                           [('var', 'a'),
                                            ('var', 'b'),
                                            ('var', 'c')]),
                                  'has_loop': False,
                                  'statements': [('body_decl',
                                                  'e_left',
                                                  ('tensor',
                                                   [('m', 'invariant')]),
                                                  ('call',
                                                   'zero_1d_array',
                                                   [('add',
                                                     ('var', 'n'),
                                                     ('num', 1))])),
                                                 ('body_index_assign',
                                                  'e_left',
                                                  ('sub',
                                                   ('var', 'j'),
                                                   ('num', 1)),
                                                  ('num', 1)),
                                                 ('body_decl',
                                                  'a',
                                                  'ℝ',
                                                  ('call',
                                                   'helmholtz_equation',
                                                   [('var', 'e_left'),
                                                    ('var', 'j'),
                                                    ('var', 'k')])),
                                                 ('body_decl',
                                                  'e_center',
                                                  ('tensor',
                                                   [('m', 'invariant')]),
                                                  ('call',
                                                   'zero_1d_array',
                                                   [('add',
                                                     ('var', 'n'),
                                                     ('num', 1))])),
                                                 ('body_index_assign',
                                                  'e_center',
                                                  ('var', 'j'),
                                                  ('num', 1)),
                                                 ('body_decl',
                                                  'b',
                                                  'ℝ',
                                                  ('call',
                                                   'helmholtz_equation',
                                                   [('var', 'e_center'),
                                                    ('var', 'j'),
                                                    ('var', 'k')])),
                                                 ('body_decl',
                                                  'e_right',
                                                  ('tensor',
                                                   [('m', 'invariant')]),
                                                  ('call',
                                                   'zero_1d_array',
                                                   [('add',
                                                     ('var', 'n'),
                                                     ('num', 1))])),
                                                 ('body_index_assign',
                                                  'e_right',
                                                  ('add',
                                                   ('var', 'j'),
                                                   ('num', 1)),
                                                  ('num', 1)),
                                                 ('body_decl',
                                                  'c',
                                                  'ℝ',
                                                  ('call',
                                                   'helmholtz_equation',
                                                   [('var', 'e_right'),
                                                    ('var', 'j'),
                                                    ('var', 'k')]))]},
               'assemble_matrix': {'params': [('k', 'ℝ'), ('n', 'ℕ')],
                                   'return_type': 'list',
                                   'body': ('var', 'results'),
                                   'has_loop': False,
                                   'statements': [('body_decl',
                                                   'n_size',
                                                   'ℝ',
                                                   ('add',
                                                    ('var', 'n'),
                                                    ('num', 1))),
                                                  ('body_decl',
                                                   'A',
                                                   ('tensor',
                                                    [('n_size', 'invariant'),
                                                     ('n_size', 'invariant')]),
                                                   ('call',
                                                    'zero_2d_array',
                                                    [('var', 'n_size'),
                                                     ('var', 'n_size')])),
                                                  ('body_decl',
                                                   'b',
                                                   ('tensor',
                                                    [('n_size', 'invariant')]),
                                                   ('call',
                                                    'zero_1d_array',
                                                    [('var', 'n_size')])),
                                                  ('body_for_range',
                                                   'j',
                                                   ('num', 1),
                                                   ('var', 'n'),
                                                   [('loop_tuple_unpack',
                                                     ['c1', 'c2', 'c3'],
                                                     ('call',
                                                      'get_row_coeffs',
                                                      [('var', 'j'),
                                                       ('var', 'k')])),
                                                    ('loop_if_else',
                                                     ('cond_eq',
                                                      ('sub',
                                                       ('var', 'j'),
                                                       ('num', 1)),
                                                      ('num', 0)),
                                                     [('loop_index_assign_nd',
                                                       'b',
                                                       [('index_item',
                                                         ('var', 'j'))],
                                                       ('sub',
                                                        ('index',
                                                         'b',
                                                         ('var', 'j')),
                                                        ('mul',
                                                         ('var', 'c1'),
                                                         ('var', 'u_x0'))))],
                                                     [('loop_index_assign_nd',
                                                       'A',
                                                       [('index_item',
                                                         ('var', 'j')),
                                                        ('index_item',
                                                         ('sub',
                                                          ('var', 'j'),
                                                          ('num', 1)))],
                                                       ('var', 'c1'))]),
                                                    ('loop_index_assign_nd',
                                                     'A',
                                                     [('index_item',
                                                       ('var', 'j')),
                                                      ('index_item',
                                                       ('var', 'j'))],
                                                     ('var', 'c2')),
                                                    ('loop_if_else',
                                                     ('cond_eq',
                                                      ('add',
                                                       ('var', 'j'),
                                                       ('num', 1)),
                                                      ('add',
                                                       ('var', 'n'),
                                                       ('num', 0))),
                                                     [('loop_index_assign_nd',
                                                       'b',
                                                       [('index_item',
                                                         ('var', 'j'))],
                                                       ('sub',
                                                        ('index',
                                                         'b',
                                                         ('var', 'j')),
                                                        ('mul',
                                                         ('var', 'c3'),
                                                         ('var', 'u_x1'))))],
                                                     [('loop_index_assign_nd',
                                                       'A',
                                                       [('index_item',
                                                         ('var', 'j')),
                                                        ('index_item',
                                                         ('add',
                                                          ('var', 'j'),
                                                          ('num', 1)))],
                                                       ('var', 'c3'))])]),
                                                  ('body_index_assign_nd',
                                                   'A',
                                                   [('index_item', ('num', 0)),
                                                    ('index_item', ('num', 0))],
                                                   ('num', 1)),
                                                  ('body_index_assign',
                                                   'b',
                                                   ('num', 0),
                                                   ('var', 'u_x0')),
                                                  ('body_index_assign_nd',
                                                   'A',
                                                   [('index_item',
                                                     ('var', 'n')),
                                                    ('index_item',
                                                     ('var', 'n'))],
                                                   ('num', 1)),
                                                  ('body_index_assign',
                                                   'b',
                                                   ('var', 'n'),
                                                   ('var', 'u_x1')),
                                                  ('body_decl',
                                                   'results',
                                                   'list',
                                                   ('array',
                                                    [('var', 'A'),
                                                     ('var', 'b')]))]},
               'solver': {'params': [('k', 'ℝ'), ('n', 'ℕ')],
                          'return_type': ('tensor', [('n', 'invariant')]),
                          'body': ('var', 'u'),
                          'has_loop': False,
                          'statements': [('body_decl',
                                          'results',
                                          'list',
                                          ('call',
                                           'assemble_matrix',
                                           [('var', 'k'), ('var', 'n')])),
                                         ('body_assign',
                                          'A',
                                          ('index', 'results', ('num', 0))),
                                         ('body_assign',
                                          'b',
                                          ('index', 'results', ('num', 1))),
                                         ('body_decl',
                                          'u',
                                          ('tensor', [('n', 'invariant')]),
                                          ('call',
                                           'gaussian_solve',
                                           [('var', 'A'), ('var', 'b')]))]},
               'mse_loss': {'params': [('true_u',
                                        ('tensor', [('m', 'invariant')])),
                                       ('pred_u',
                                        ('tensor', [('m', 'invariant')]))],
                            'return_type': 'ℝ',
                            'body': ('div',
                                     ('var', 'total'),
                                     ('var', 'total_len')),
                            'has_loop': False,
                            'statements': [('body_decl',
                                            'total_len',
                                            'ℝ',
                                            ('call',
                                             'get_1d_array_length',
                                             [('var', 'pred_u')])),
                                           ('body_decl',
                                            'square_diff',
                                            ('tensor', [(5, 'invariant')]),
                                            ('pow',
                                             ('sub',
                                              ('var', 'true_u'),
                                              ('var', 'pred_u')),
                                             ('num', 2))),
                                           ('body_decl',
                                            'total',
                                            'ℝ',
                                            ('num', 0)),
                                           ('body_for_range',
                                            'i',
                                            ('num', 0),
                                            ('var', 'total_len'),
                                            [('loop_assign',
                                              'total',
                                              ('add',
                                               ('var', 'total'),
                                               ('index',
                                                'square_diff',
                                                ('imaginary',))))])]}},
 'classes': {},
 'program': [('func_def', 'zero_1d_array'),
             ('func_def', 'zero_2d_array'),
             ('func_def', 'linspace'),
             ('func_def', 'append'),
             ('stmt_tuple_unpack',
              [('x0', 'ℝ'), ('x1', 'ℝ'), ('n', 'ℝ')],
              ('expr_list', [('num', 0), ('num', 1), ('num', 10)])),
             ('decl',
              'Δx',
              'ℝ',
              ('div', ('sub', ('var', 'x1'), ('var', 'x0')), ('var', 'n')),
              37),
             ('stmt_tuple_unpack',
              [('u_x0', 'ℝ'), ('u_x1', 'ℝ')],
              ('expr_list', [('num', 0), ('num', 1)])),
             ('decl', 'k', 'ℝ', ('num', 2), 40),
             ('assign',
              'X',
              ('call',
               'linspace',
               [('num', 0), ('num', 1), ('add', ('var', 'n'), ('num', 1))]),
              42),
             ('func_def', 'central_difference'),
             ('func_def', 'helmholtz_equation'),
             ('func_def', 'get_row_coeffs'),
             ('func_def', 'assemble_matrix'),
             ('import',
              'tutorials.linear_solve_gaussian_elimination',
              ['gaussian_solve',
               'get_2d_array_num_cols',
               'get_2d_array_num_rows',
               'get_1d_array_length']),
             ('func_def', 'solver'),
             ('assign',
              'true_u',
              ('call', 'solver', [('var', 'k'), ('var', 'n')]),
              113),
             ('func_def', 'mse_loss'),
             ('decl',
              'losses',
              ('tensor', [(1, 'invariant')]),
              ('array', [('num', 100)]),
              133),
             ('decl', 'guess_k', 'ℝ', ('num', 2.6), 134),
             ('decl', 'epochs', 'ℕ', ('num', 1), 140),
             ('decl', 'lr', 'ℝ', ('num', 0.01), 141),
             ('for_loop_range',
              'i',
              ('num', 0),
              ('var', 'epochs'),
              [('for_call', 'print', [('imaginary',)]),
               ('for_assign',
                'pred_u',
                ('call', 'solver', [('var', 'guess_k'), ('var', 'n')])),
               ('for_assign',
                'loss',
                ('call', 'mse_loss', [('var', 'true_u'), ('var', 'pred_u')])),
               ('for_assign',
                'losses',
                ('call', 'append', [('var', 'losses'), ('var', 'loss')])),
               ('for_assign',
                'grad',
                ('call', 'grad', [('var', 'loss'), ('var', 'guess_k')])),
               ('for_assign',
                'guess_k',
                ('sub',
                 ('var', 'guess_k'),
                 ('mul', ('var', 'lr'), ('var', 'grad')))),
               ('for_call', 'print', [('var', 'guess_k')])],
              143),
             ('expr', ('call', 'print', [('var', 'guess_k')]), 0),
             ('assign',
              'pred_traj',
              ('call', 'solver', [('var', 'guess_k'), ('var', 'n')]),
              154)]}
