EXPECTED = {'functions': {'zero_1d_array': {'params': [('len', 'ℝ')],
                                 'return_type': ('tensor',
                                                 [('m', 'invariant')]),
                                 'body': ('var', 'results'),
                                 'has_loop': False,
                                 'statements': [('body_decl',
                                                 'results',
                                                 ('tensor',
                                                  [('len', 'invariant')]),
                                                 ('for_expr',
                                                  'i',
                                                  ('var', 'len'),
                                                  ('mul',
                                                   ('imaginary',),
                                                   ('num', 0))))]},
               'zero_2d_array': {'params': [('rows', 'ℝ'), ('cols', 'ℝ')],
                                 'return_type': ('tensor',
                                                 [('m', 'invariant'),
                                                  ('n', 'invariant')]),
                                 'body': ('var', 'results'),
                                 'has_loop': False,
                                 'statements': [('body_decl',
                                                 'results',
                                                 ('tensor',
                                                  [('rows', 'invariant'),
                                                   ('cols', 'invariant')]),
                                                 ('for_expr',
                                                  'i',
                                                  ('var', 'rows'),
                                                  ('for_expr',
                                                   'j',
                                                   ('var', 'cols'),
                                                   ('mul',
                                                    ('var', 'j'),
                                                    ('num', 0)))))]},
               'get_1d_array_length': {'params': [('x',
                                                   ('tensor',
                                                    [('m', 'invariant')]))],
                                       'return_type': 'ℝ',
                                       'body': ('var', 'total'),
                                       'has_loop': False,
                                       'statements': [('body_decl',
                                                       'total',
                                                       'ℝ',
                                                       ('num', 0)),
                                                      ('body_decl',
                                                       'temp',
                                                       'ℝ',
                                                       ('num', 0)),
                                                      ('body_for',
                                                       'i',
                                                       [('loop_assign',
                                                         'temp',
                                                         ('index',
                                                          'x',
                                                          ('imaginary',))),
                                                        ('loop_pluseq',
                                                         'total',
                                                         ('num', 1))],
                                                       ['x'])]},
               'get_2d_array_num_rows': {'params': [('x',
                                                     ('tensor',
                                                      [('m', 'invariant'),
                                                       ('n', 'invariant')]))],
                                         'return_type': 'ℝ',
                                         'body': ('var', 'total'),
                                         'has_loop': False,
                                         'statements': [('body_decl',
                                                         'total',
                                                         'ℝ',
                                                         ('num', 0)),
                                                        ('body_decl',
                                                         'temp',
                                                         'ℝ',
                                                         ('num', 0)),
                                                        ('body_for',
                                                         'i',
                                                         [('loop_assign',
                                                           'temp',
                                                           ('index',
                                                            'x',
                                                            ('imaginary',))),
                                                          ('loop_pluseq',
                                                           'total',
                                                           ('num', 1))],
                                                         ['x'])]},
               'get_2d_array_num_cols': {'params': [('x',
                                                     ('tensor',
                                                      [('m', 'invariant'),
                                                       ('n', 'invariant')]))],
                                         'return_type': 'ℝ',
                                         'body': ('call',
                                                  'get_1d_array_length',
                                                  [('index', 'x', ('num', 0))]),
                                         'has_loop': False,
                                         'statements': []},
               'arange': {'params': [('n', 'ℕ')],
                          'return_type': ('tensor', [('n', 'invariant')]),
                          'body': ('var', 'arr'),
                          'has_loop': False,
                          'statements': [('body_decl',
                                          'arr',
                                          ('tensor', [('n', 'invariant')]),
                                          ('for_expr',
                                           'i',
                                           ('var', 'n'),
                                           ('imaginary',)))]},
               'max': {'params': [('x', 'ℝ'), ('y', 'ℝ')],
                       'return_type': 'ℝ',
                       'body': None,
                       'has_loop': False,
                       'statements': [('body_if_else_return',
                                       ('cond_gt', ('var', 'x'), ('var', 'y')),
                                       ('var', 'x'),
                                       ('var', 'y'))]},
               'min': {'params': [('x', 'ℝ'), ('y', 'ℝ')],
                       'return_type': 'ℝ',
                       'body': None,
                       'has_loop': False,
                       'statements': [('body_if_else_return',
                                       ('cond_lt', ('var', 'x'), ('var', 'y')),
                                       ('var', 'x'),
                                       ('var', 'y'))]},
               'gaussian_solve': {'params': [('A',
                                              ('tensor',
                                               [('m', 'invariant'),
                                                ('n', 'invariant')])),
                                             ('b',
                                              ('tensor',
                                               [('n', 'invariant')]))],
                                  'return_type': ('tensor',
                                                  [('n', 'invariant')]),
                                  'body': ('var', 'x'),
                                  'has_loop': False,
                                  'statements': [('body_decl',
                                                  'a_row',
                                                  'ℝ',
                                                  ('call',
                                                   'get_2d_array_num_rows',
                                                   [('var', 'A')])),
                                                 ('body_decl',
                                                  'a_col',
                                                  'ℝ',
                                                  ('call',
                                                   'get_2d_array_num_cols',
                                                   [('var', 'A')])),
                                                 ('body_decl',
                                                  'new_col',
                                                  'ℝ',
                                                  ('add',
                                                   ('var', 'a_col'),
                                                   ('num', 1))),
                                                 ('body_decl',
                                                  'aug',
                                                  ('tensor',
                                                   [('a_row', 'invariant'),
                                                    ('new_col', 'invariant')]),
                                                  ('call',
                                                   'zeros',
                                                   [('var', 'a_row'),
                                                    ('var', 'new_col')])),
                                                 ('body_for_range',
                                                  'i',
                                                  ('num', 0),
                                                  ('var', 'a_row'),
                                                  [('loop_index_assign_nd',
                                                    'aug',
                                                    [('index_item',
                                                      ('imaginary',)),
                                                     ('slice_item',
                                                      None,
                                                      ('var', 'a_col'))],
                                                    ('indexN',
                                                     'A',
                                                     [('index_item',
                                                       ('imaginary',)),
                                                      ('slice_item',
                                                       None,
                                                       None)])),
                                                   ('loop_index_assign_nd',
                                                    'aug',
                                                    [('index_item',
                                                      ('imaginary',)),
                                                     ('index_item',
                                                      ('var', 'a_col'))],
                                                    ('index',
                                                     'b',
                                                     ('imaginary',)))]),
                                                 ('body_for_range',
                                                  'i',
                                                  ('num', 0),
                                                  ('var', 'a_row'),
                                                  [('loop_assign',
                                                    'max_row',
                                                    ('imaginary',)),
                                                   ('loop_for_range',
                                                    'k',
                                                    ('add',
                                                     ('imaginary',),
                                                     ('num', 1)),
                                                    ('var', 'a_row'),
                                                    [('loop_if',
                                                      ('cond_gt',
                                                       ('call',
                                                        'abs',
                                                        [('indexN',
                                                          'aug',
                                                          [('index_item',
                                                            ('var', 'k')),
                                                           ('index_item',
                                                            ('imaginary',))])]),
                                                       ('call',
                                                        'abs',
                                                        [('indexN',
                                                          'aug',
                                                          [('index_item',
                                                            ('var', 'max_row')),
                                                           ('index_item',
                                                            ('imaginary',))])])),
                                                      [('loop_assign',
                                                        'max_row',
                                                        ('var', 'k'))])]),
                                                   ('loop_if',
                                                    ('cond_neq',
                                                     ('var', 'max_row'),
                                                     ('imaginary',)),
                                                    [('loop_assign',
                                                      'lo',
                                                      ('call',
                                                       'min',
                                                       [('imaginary',),
                                                        ('var', 'max_row')])),
                                                     ('loop_assign',
                                                      'hi',
                                                      ('call',
                                                       'max',
                                                       [('imaginary',),
                                                        ('var', 'max_row')])),
                                                     ('loop_assign',
                                                      'rows_above',
                                                      ('indexN',
                                                       'aug',
                                                       [('slice_item',
                                                         None,
                                                         ('var', 'lo')),
                                                        ('slice_item',
                                                         None,
                                                         None)])),
                                                     ('loop_assign',
                                                      'pivot_row',
                                                      ('indexN',
                                                       'aug',
                                                       [('slice_item',
                                                         ('var', 'hi'),
                                                         ('add',
                                                          ('var', 'hi'),
                                                          ('num', 1))),
                                                        ('slice_item',
                                                         None,
                                                         None)])),
                                                     ('loop_assign',
                                                      'rows_between',
                                                      ('indexN',
                                                       'aug',
                                                       [('slice_item',
                                                         ('add',
                                                          ('var', 'lo'),
                                                          ('num', 1)),
                                                         ('var', 'hi')),
                                                        ('slice_item',
                                                         None,
                                                         None)])),
                                                     ('loop_assign',
                                                      'current_row',
                                                      ('indexN',
                                                       'aug',
                                                       [('slice_item',
                                                         ('var', 'lo'),
                                                         ('add',
                                                          ('var', 'lo'),
                                                          ('num', 1))),
                                                        ('slice_item',
                                                         None,
                                                         None)])),
                                                     ('loop_assign',
                                                      'rows_below',
                                                      ('indexN',
                                                       'aug',
                                                       [('slice_item',
                                                         ('add',
                                                          ('var', 'hi'),
                                                          ('num', 1)),
                                                         None),
                                                        ('slice_item',
                                                         None,
                                                         None)])),
                                                     ('loop_assign',
                                                      'aug',
                                                      ('call',
                                                       'concat',
                                                       [('var', 'rows_above'),
                                                        ('var', 'pivot_row'),
                                                        ('var', 'rows_between'),
                                                        ('var', 'current_row'),
                                                        ('var',
                                                         'rows_below')]))]),
                                                   ('loop_assign',
                                                    'pivot_row',
                                                    ('indexN',
                                                     'aug',
                                                     [('slice_item',
                                                       ('imaginary',),
                                                       ('add',
                                                        ('imaginary',),
                                                        ('num', 1))),
                                                      ('slice_item',
                                                       None,
                                                       None)])),
                                                   ('loop_assign',
                                                    'pivot_value',
                                                    ('indexN',
                                                     'aug',
                                                     [('index_item',
                                                       ('imaginary',)),
                                                      ('index_item',
                                                       ('imaginary',))])),
                                                   ('loop_assign',
                                                    'rows_below',
                                                    ('indexN',
                                                     'aug',
                                                     [('slice_item',
                                                       ('add',
                                                        ('imaginary',),
                                                        ('num', 1)),
                                                       None),
                                                      ('slice_item',
                                                       None,
                                                       None)])),
                                                   ('loop_assign',
                                                    'elimination_factors',
                                                    ('div',
                                                     ('indexN',
                                                      'rows_below',
                                                      [('slice_item',
                                                        None,
                                                        None),
                                                       ('slice_item',
                                                        ('imaginary',),
                                                        ('add',
                                                         ('imaginary',),
                                                         ('num', 1)))]),
                                                     ('var', 'pivot_value'))),
                                                   ('loop_assign',
                                                    'eliminated_rows',
                                                    ('sub',
                                                     ('var', 'rows_below'),
                                                     ('mul',
                                                      ('var',
                                                       'elimination_factors'),
                                                      ('var', 'pivot_row')))),
                                                   ('loop_assign',
                                                    'aug',
                                                    ('call',
                                                     'concat',
                                                     [('indexN',
                                                       'aug',
                                                       [('slice_item',
                                                         None,
                                                         ('add',
                                                          ('imaginary',),
                                                          ('num', 1))),
                                                        ('slice_item',
                                                         None,
                                                         None)]),
                                                      ('var',
                                                       'eliminated_rows')]))]),
                                                 ('body_assign',
                                                  'x',
                                                  ('call',
                                                   'zeros',
                                                   [('num', 0)])),
                                                 ('body_for_range',
                                                  'i',
                                                  ('num', 0),
                                                  ('var', 'a_row'),
                                                  [('loop_assign',
                                                    'idx',
                                                    ('sub',
                                                     ('sub',
                                                      ('var', 'a_col'),
                                                      ('num', 1)),
                                                     ('imaginary',))),
                                                   ('loop_assign',
                                                    'total',
                                                    ('indexN',
                                                     'aug',
                                                     [('index_item',
                                                       ('var', 'idx')),
                                                      ('index_item',
                                                       ('var', 'a_col'))])),
                                                   ('loop_for_range',
                                                    'j',
                                                    ('add',
                                                     ('var', 'idx'),
                                                     ('num', 1)),
                                                    ('var', 'a_row'),
                                                    [('loop_assign',
                                                      'total',
                                                      ('sub',
                                                       ('var', 'total'),
                                                       ('mul',
                                                        ('indexN',
                                                         'aug',
                                                         [('index_item',
                                                           ('var', 'idx')),
                                                          ('index_item',
                                                           ('var', 'j'))]),
                                                        ('index',
                                                         'x',
                                                         ('sub',
                                                          ('sub',
                                                           ('var', 'j'),
                                                           ('var', 'idx')),
                                                          ('num', 1))))))]),
                                                   ('loop_assign',
                                                    'val',
                                                    ('div',
                                                     ('var', 'total'),
                                                     ('indexN',
                                                      'aug',
                                                      [('index_item',
                                                        ('var', 'idx')),
                                                       ('index_item',
                                                        ('var', 'idx'))]))),
                                                   ('loop_assign',
                                                    'val',
                                                    ('call',
                                                     'reshape',
                                                     [('var', 'val'),
                                                      ('num', 1)])),
                                                   ('loop_assign',
                                                    'x',
                                                    ('call',
                                                     'concat',
                                                     [('var', 'val'),
                                                      ('var', 'x')]))])]}},
 'classes': {},
 'program': [('func_def', 'zero_1d_array'),
             ('func_def', 'zero_2d_array'),
             ('func_def', 'get_1d_array_length'),
             ('func_def', 'get_2d_array_num_rows'),
             ('func_def', 'get_2d_array_num_cols'),
             ('func_def', 'arange'),
             ('func_def', 'max'),
             ('func_def', 'min'),
             ('func_def', 'gaussian_solve'),
             ('decl',
              'A',
              ('tensor', [(3, 'invariant'), (3, 'invariant')]),
              ('array',
               [('array', [('num', 1), ('num', 2), ('num', 1)]),
                ('array', [('num', 3), ('num', 1), ('neg', ('num', 1))]),
                ('array', [('num', 2), ('neg', ('num', 1)), ('num', 1)])]),
              118),
             ('decl',
              'b',
              ('tensor', [(3, 'invariant')]),
              ('array', [('num', 8), ('num', 2), ('num', 3)]),
              123),
             ('expr',
              ('call', 'gaussian_solve', [('var', 'A'), ('var', 'b')]),
              0)]}
