EXPECTED = {'functions': {'get_2d_array_num_rows': {'params': [('x',
                                                     ('tensor',
                                                      [('m', 'invariant'),
                                                       ('n', 'invariant')]))],
                                         'return_type': 'ℕ',
                                         'body': ('var', 'total'),
                                         'has_loop': False,
                                         'statements': [('body_decl',
                                                         'total',
                                                         'ℕ',
                                                         ('num', 0)),
                                                        ('body_decl',
                                                         'temp',
                                                         'ℝ',
                                                         ('num', 0)),
                                                        ('body_for',
                                                         'i',
                                                         [('loop_assign',
                                                           'temp',
                                                           ('index',
                                                            'x',
                                                            ('imaginary',))),
                                                          ('loop_pluseq',
                                                           'total',
                                                           ('num', 1))],
                                                         ['x'])]},
               'lu_decomposition': {'params': [('A',
                                                ('tensor',
                                                 [('n', 'invariant'),
                                                  ('n', 'invariant')]))],
                                    'return_type': ('tensor',
                                                    [(3, 'invariant'),
                                                     ('n', 'invariant'),
                                                     ('n', 'invariant')]),
                                    'body': ('array',
                                             [('var', 'P'),
                                              ('var', 'L'),
                                              ('var', 'U')]),
                                    'has_loop': False,
                                    'statements': [('body_decl',
                                                    'n_size',
                                                    'ℝ',
                                                    ('call',
                                                     'get_2d_array_num_rows',
                                                     [('var', 'A')])),
                                                   ('body_decl',
                                                    'L',
                                                    ('tensor',
                                                     [('n_size', 'invariant'),
                                                      ('n_size', 'invariant')]),
                                                    ('call',
                                                     'zeros',
                                                     [('var', 'n_size'),
                                                      ('var', 'n_size')])),
                                                   ('body_decl',
                                                    'U',
                                                    ('tensor',
                                                     [('n_size', 'invariant'),
                                                      ('n_size', 'invariant')]),
                                                    ('call',
                                                     'zeros',
                                                     [('var', 'n_size'),
                                                      ('var', 'n_size')])),
                                                   ('body_decl',
                                                    'P',
                                                    ('tensor',
                                                     [('n_size', 'invariant'),
                                                      ('n_size', 'invariant')]),
                                                    ('call',
                                                     'zeros',
                                                     [('var', 'n_size'),
                                                      ('var', 'n_size')])),
                                                   ('body_for_range',
                                                    'i',
                                                    ('num', 0),
                                                    ('var', 'n_size'),
                                                    [('loop_index_assign_nd',
                                                      'P',
                                                      [('index_item',
                                                        ('imaginary',)),
                                                       ('index_item',
                                                        ('imaginary',))],
                                                      ('num', 1.0))]),
                                                   ('body_decl',
                                                    'buf_a',
                                                    ('tensor',
                                                     [('n_size', 'invariant')]),
                                                    ('call',
                                                     'zeros',
                                                     [('var', 'n_size')])),
                                                   ('body_decl',
                                                    'buf_l',
                                                    ('tensor',
                                                     [('n_size', 'invariant')]),
                                                    ('call',
                                                     'zeros',
                                                     [('var', 'n_size')])),
                                                   ('body_decl',
                                                    'buf_p',
                                                    ('tensor',
                                                     [('n_size', 'invariant')]),
                                                    ('call',
                                                     'zeros',
                                                     [('var', 'n_size')])),
                                                   ('body_for_range',
                                                    'j',
                                                    ('num', 0),
                                                    ('var', 'n_size'),
                                                    [('loop_assign',
                                                      'max_row',
                                                      ('var', 'j')),
                                                     ('loop_for_range',
                                                      'i',
                                                      ('add',
                                                       ('var', 'j'),
                                                       ('num', 1)),
                                                      ('var', 'n_size'),
                                                      [('loop_if',
                                                        ('cond_gt',
                                                         ('call',
                                                          'abs',
                                                          [('indexN',
                                                            'A',
                                                            [('index_item',
                                                              ('imaginary',)),
                                                             ('index_item',
                                                              ('var', 'j'))])]),
                                                         ('call',
                                                          'abs',
                                                          [('indexN',
                                                            'A',
                                                            [('index_item',
                                                              ('var',
                                                               'max_row')),
                                                             ('index_item',
                                                              ('var',
                                                               'j'))])])),
                                                        [('loop_assign',
                                                          'max_row',
                                                          ('imaginary',))])]),
                                                     ('loop_if',
                                                      ('cond_neq',
                                                       ('var', 'max_row'),
                                                       ('var', 'j')),
                                                      [('loop_for_range',
                                                        'k',
                                                        ('num', 0),
                                                        ('var', 'n_size'),
                                                        [('loop_index_assign_nd',
                                                          'buf_a',
                                                          [('index_item',
                                                            ('var', 'k'))],
                                                          ('indexN',
                                                           'A',
                                                           [('index_item',
                                                             ('var', 'j')),
                                                            ('index_item',
                                                             ('var', 'k'))]))]),
                                                       ('loop_for_range',
                                                        'k',
                                                        ('num', 0),
                                                        ('var', 'n_size'),
                                                        [('loop_index_assign_nd',
                                                          'A',
                                                          [('index_item',
                                                            ('var', 'j')),
                                                           ('index_item',
                                                            ('var', 'k'))],
                                                          ('indexN',
                                                           'A',
                                                           [('index_item',
                                                             ('var',
                                                              'max_row')),
                                                            ('index_item',
                                                             ('var', 'k'))]))]),
                                                       ('loop_for_range',
                                                        'k',
                                                        ('num', 0),
                                                        ('var', 'n_size'),
                                                        [('loop_index_assign_nd',
                                                          'A',
                                                          [('index_item',
                                                            ('var', 'max_row')),
                                                           ('index_item',
                                                            ('var', 'k'))],
                                                          ('index',
                                                           'buf_a',
                                                           ('var', 'k')))]),
                                                       ('loop_for_range',
                                                        'k',
                                                        ('num', 0),
                                                        ('var', 'j'),
                                                        [('loop_index_assign_nd',
                                                          'buf_l',
                                                          [('index_item',
                                                            ('var', 'k'))],
                                                          ('indexN',
                                                           'L',
                                                           [('index_item',
                                                             ('var', 'j')),
                                                            ('index_item',
                                                             ('var', 'k'))]))]),
                                                       ('loop_for_range',
                                                        'k',
                                                        ('num', 0),
                                                        ('var', 'j'),
                                                        [('loop_index_assign_nd',
                                                          'L',
                                                          [('index_item',
                                                            ('var', 'j')),
                                                           ('index_item',
                                                            ('var', 'k'))],
                                                          ('indexN',
                                                           'L',
                                                           [('index_item',
                                                             ('var',
                                                              'max_row')),
                                                            ('index_item',
                                                             ('var', 'k'))]))]),
                                                       ('loop_for_range',
                                                        'k',
                                                        ('num', 0),
                                                        ('var', 'j'),
                                                        [('loop_index_assign_nd',
                                                          'L',
                                                          [('index_item',
                                                            ('var', 'max_row')),
                                                           ('index_item',
                                                            ('var', 'k'))],
                                                          ('index',
                                                           'buf_l',
                                                           ('var', 'k')))]),
                                                       ('loop_for_range',
                                                        'k',
                                                        ('num', 0),
                                                        ('var', 'n_size'),
                                                        [('loop_index_assign_nd',
                                                          'buf_p',
                                                          [('index_item',
                                                            ('var', 'k'))],
                                                          ('indexN',
                                                           'P',
                                                           [('index_item',
                                                             ('var', 'j')),
                                                            ('index_item',
                                                             ('var', 'k'))]))]),
                                                       ('loop_for_range',
                                                        'k',
                                                        ('num', 0),
                                                        ('var', 'n_size'),
                                                        [('loop_index_assign_nd',
                                                          'P',
                                                          [('index_item',
                                                            ('var', 'j')),
                                                           ('index_item',
                                                            ('var', 'k'))],
                                                          ('indexN',
                                                           'P',
                                                           [('index_item',
                                                             ('var',
                                                              'max_row')),
                                                            ('index_item',
                                                             ('var', 'k'))]))]),
                                                       ('loop_for_range',
                                                        'k',
                                                        ('num', 0),
                                                        ('var', 'n_size'),
                                                        [('loop_index_assign_nd',
                                                          'P',
                                                          [('index_item',
                                                            ('var', 'max_row')),
                                                           ('index_item',
                                                            ('var', 'k'))],
                                                          ('index',
                                                           'buf_p',
                                                           ('var', 'k')))])]),
                                                     ('loop_for_range',
                                                      'i',
                                                      ('num', 0),
                                                      ('add',
                                                       ('var', 'j'),
                                                       ('num', 1)),
                                                      [('loop_assign',
                                                        'partial',
                                                        ('num', 0.0)),
                                                       ('loop_for_range',
                                                        'k',
                                                        ('num', 0),
                                                        ('imaginary',),
                                                        [('loop_assign',
                                                          'partial',
                                                          ('add',
                                                           ('var', 'partial'),
                                                           ('mul',
                                                            ('indexN',
                                                             'U',
                                                             [('index_item',
                                                               ('var', 'k')),
                                                              ('index_item',
                                                               ('var', 'j'))]),
                                                            ('indexN',
                                                             'L',
                                                             [('index_item',
                                                               ('imaginary',)),
                                                              ('index_item',
                                                               ('var',
                                                                'k'))]))))]),
                                                       ('loop_index_assign_nd',
                                                        'U',
                                                        [('index_item',
                                                          ('imaginary',)),
                                                         ('index_item',
                                                          ('var', 'j'))],
                                                        ('sub',
                                                         ('indexN',
                                                          'A',
                                                          [('index_item',
                                                            ('imaginary',)),
                                                           ('index_item',
                                                            ('var', 'j'))]),
                                                         ('var', 'partial')))]),
                                                     ('loop_for_range',
                                                      'i',
                                                      ('var', 'j'),
                                                      ('var', 'n_size'),
                                                      [('loop_assign',
                                                        'partial',
                                                        ('num', 0.0)),
                                                       ('loop_for_range',
                                                        'k',
                                                        ('num', 0),
                                                        ('var', 'j'),
                                                        [('loop_assign',
                                                          'partial',
                                                          ('add',
                                                           ('var', 'partial'),
                                                           ('mul',
                                                            ('indexN',
                                                             'U',
                                                             [('index_item',
                                                               ('var', 'k')),
                                                              ('index_item',
                                                               ('var', 'j'))]),
                                                            ('indexN',
                                                             'L',
                                                             [('index_item',
                                                               ('imaginary',)),
                                                              ('index_item',
                                                               ('var',
                                                                'k'))]))))]),
                                                       ('loop_index_assign_nd',
                                                        'L',
                                                        [('index_item',
                                                          ('imaginary',)),
                                                         ('index_item',
                                                          ('var', 'j'))],
                                                        ('div',
                                                         ('sub',
                                                          ('indexN',
                                                           'A',
                                                           [('index_item',
                                                             ('imaginary',)),
                                                            ('index_item',
                                                             ('var', 'j'))]),
                                                          ('var', 'partial')),
                                                         ('indexN',
                                                          'U',
                                                          [('index_item',
                                                            ('var', 'j')),
                                                           ('index_item',
                                                            ('var',
                                                             'j'))])))])])]}},
 'classes': {},
 'program': [('func_def', 'get_2d_array_num_rows'),
             ('func_def', 'lu_decomposition'),
             ('decl',
              'A',
              ('tensor', [(3, 'invariant'), (3, 'invariant')]),
              ('array',
               [('array', [('neg', ('num', 1.0)), ('num', 0.0), ('num', 3.0)]),
                ('array', [('num', 2.0), ('num', 1.0), ('num', 3.0)]),
                ('array', [('num', 1.0), ('num', 1.0), ('num', 2.0)])]),
              69),
             ('decl',
              'A_original',
              ('tensor', [(3, 'invariant'), (3, 'invariant')]),
              ('for_expr',
               'i',
               ('num', 3),
               ('for_expr',
                'j',
                ('num', 3),
                ('indexN',
                 'A',
                 [('index_item', ('imaginary',)),
                  ('index_item', ('var', 'j'))]))),
              76),
             ('assign',
              'results',
              ('call', 'lu_decomposition', [('var', 'A')]),
              78),
             ('decl',
              'P_matrix',
              ('tensor', [(3, 'invariant'), (3, 'invariant')]),
              ('index', 'results', ('num', 0)),
              79),
             ('decl',
              'L_matrix',
              ('tensor', [(3, 'invariant'), (3, 'invariant')]),
              ('index', 'results', ('num', 1)),
              80),
             ('decl',
              'U_matrix',
              ('tensor', [(3, 'invariant'), (3, 'invariant')]),
              ('index', 'results', ('num', 2)),
              81),
             ('expr', ('call', 'print', [('var', 'P_matrix')]), 0),
             ('expr', ('call', 'print', [('var', 'L_matrix')]), 0),
             ('expr', ('call', 'print', [('var', 'U_matrix')]), 0),
             ('decl',
              'LU',
              ('tensor', [(3, 'invariant'), (3, 'invariant')]),
              ('matmul', ('var', 'L_matrix'), ('var', 'U_matrix')),
              87),
             ('decl',
              'PA',
              ('tensor', [(3, 'invariant'), (3, 'invariant')]),
              ('matmul', ('var', 'P_matrix'), ('var', 'A_original')),
              88),
             ('expr', ('call', 'print', [('var', 'LU')]), 0),
             ('expr', ('call', 'print', [('var', 'PA')]), 0)]}
