EXPECTED = {'functions': {'get_sum_of_1d_array': {'params': [('x',
                                                   ('tensor',
                                                    [('m', 'invariant')]))],
                                       'return_type': 'ℝ',
                                       'body': ('var', 'total'),
                                       'has_loop': False,
                                       'statements': [('body_decl',
                                                       'total',
                                                       'ℝ',
                                                       ('num', 0)),
                                                      ('body_for',
                                                       'i',
                                                       [('loop_pluseq',
                                                         'total',
                                                         ('index',
                                                          'x',
                                                          ('imaginary',)))],
                                                       ['x'])]},
               'get_1d_array_length': {'params': [('x',
                                                   ('tensor',
                                                    [('m', 'invariant')]))],
                                       'return_type': 'ℝ',
                                       'body': ('var', 'total'),
                                       'has_loop': False,
                                       'statements': [('body_decl',
                                                       'total',
                                                       'ℝ',
                                                       ('num', 0)),
                                                      ('body_decl',
                                                       'temp',
                                                       'ℝ',
                                                       ('num', 0)),
                                                      ('body_for',
                                                       'i',
                                                       [('loop_assign',
                                                         'temp',
                                                         ('index',
                                                          'x',
                                                          ('imaginary',))),
                                                        ('loop_pluseq',
                                                         'total',
                                                         ('num', 1))],
                                                       ['x'])]},
               'get_2d_array_num_rows': {'params': [('x',
                                                     ('tensor',
                                                      [('m', 'invariant'),
                                                       ('n', 'invariant')]))],
                                         'return_type': 'ℝ',
                                         'body': ('var', 'total'),
                                         'has_loop': False,
                                         'statements': [('body_decl',
                                                         'total',
                                                         'ℝ',
                                                         ('num', 0)),
                                                        ('body_decl',
                                                         'temp',
                                                         'ℝ',
                                                         ('num', 0)),
                                                        ('body_for',
                                                         'i',
                                                         [('loop_assign',
                                                           'temp',
                                                           ('index',
                                                            'x',
                                                            ('imaginary',))),
                                                          ('loop_pluseq',
                                                           'total',
                                                           ('num', 1))],
                                                         ['x'])]},
               'zero_1d_array': {'params': [('len', 'ℝ')],
                                 'return_type': ('tensor',
                                                 [('m', 'invariant')]),
                                 'body': ('var', 'results'),
                                 'has_loop': False,
                                 'statements': [('body_decl',
                                                 'results',
                                                 ('tensor',
                                                  [('len', 'invariant')]),
                                                 ('for_expr',
                                                  'i',
                                                  ('var', 'len'),
                                                  ('mul',
                                                   ('imaginary',),
                                                   ('num', 0))))]},
               'sigma': {'params': [('x',
                                     ('tensor',
                                      [('a', 'invariant'),
                                       ('b', 'invariant')]))],
                         'return_type': ('tensor',
                                         [('a', 'invariant'),
                                          ('b', 'invariant')]),
                         'body': ('div',
                                  ('num', 1.0),
                                  ('add',
                                   ('num', 1.0),
                                   ('call',
                                    'exp',
                                    [('sub', ('num', 0.0), ('var', 'x'))]))),
                         'has_loop': False,
                         'statements': []},
               'softmax_row': {'params': [('x',
                                           ('tensor', [('m', 'invariant')]))],
                               'return_type': ('tensor', [('m', 'invariant')]),
                               'body': ('for_expr',
                                        'i',
                                        ('var', 'sz'),
                                        ('div',
                                         ('index', 'e', ('imaginary',)),
                                         ('var', 'total'))),
                               'has_loop': False,
                               'statements': [('body_decl',
                                               'sz',
                                               'ℝ',
                                               ('call',
                                                'get_1d_array_length',
                                                [('var', 'x')])),
                                              ('body_decl',
                                               'e',
                                               ('tensor',
                                                [('sz', 'invariant')]),
                                               ('for_expr',
                                                'i',
                                                ('var', 'sz'),
                                                ('call',
                                                 'exp',
                                                 [('index',
                                                   'x',
                                                   ('imaginary',))]))),
                                              ('body_decl',
                                               'total',
                                               'ℝ',
                                               ('call',
                                                'get_sum_of_1d_array',
                                                [('var', 'e')]))]},
               'mse': {'params': [('pred', 'ℝ'), ('target', 'ℝ')],
                       'return_type': 'ℝ',
                       'body': ('pow',
                                ('sub', ('var', 'pred'), ('var', 'target')),
                                ('num', 2.0)),
                       'has_loop': False,
                       'statements': []},
               'empty_graph': {'params': [('n_vertices', 'ℕ')],
                               'return_type': ('struct_type',
                                               'UndirectedGraph'),
                               'body': ('var', 'g'),
                               'has_loop': False,
                               'statements': [('body_decl',
                                               'z',
                                               ('tensor',
                                                [('n_vertices', 'invariant'),
                                                 ('n_vertices', 'invariant')]),
                                               ('for_expr',
                                                'a',
                                                ('var', 'n_vertices'),
                                                ('for_expr',
                                                 'b',
                                                 ('var', 'n_vertices'),
                                                 ('mul',
                                                  ('add',
                                                   ('var', 'a'),
                                                   ('var', 'b')),
                                                  ('num', 0.0))))),
                                              ('body_decl',
                                               'g',
                                               ('struct_type',
                                                'UndirectedGraph'),
                                               ('call',
                                                'UndirectedGraph',
                                                [])),
                                              ('body_field_assign',
                                               ('var', 'g'),
                                               'adjacency',
                                               ('var', 'z'))]}},
 'classes': {'UndirectedGraph': {'class_params': [],
                                 'fields': [('adjacency',
                                             ('tensor',
                                              [('n', 'invariant'),
                                               ('n', 'invariant')]))],
                                 'methods': [{'name': 'num_vertices',
                                              'params': [],
                                              'return_type': 'ℝ',
                                              'statements': [],
                                              'body': ('mul',
                                                       ('call',
                                                        'get_2d_array_num_rows',
                                                        [('field_access',
                                                          ('var', 'this'),
                                                          'adjacency')]),
                                                       ('num', 1.0))},
                                             {'name': 'add_weighted_edge',
                                              'params': [('u', 'ℝ'),
                                                         ('v', 'ℝ'),
                                                         ('w', 'ℝ')],
                                              'return_type': None,
                                              'statements': [('body_decl',
                                                              'm',
                                                              ('tensor',
                                                               [('n',
                                                                 'invariant'),
                                                                ('n',
                                                                 'invariant')]),
                                                              ('field_access',
                                                               ('var', 'this'),
                                                               'adjacency')),
                                                             ('body_decl',
                                                              'k',
                                                              'ℝ',
                                                              ('call',
                                                               'get_2d_array_num_rows',
                                                               [('var',
                                                                 'm')])),
                                                             ('body_decl',
                                                              'new_adj',
                                                              ('tensor',
                                                               [('n',
                                                                 'invariant'),
                                                                ('n',
                                                                 'invariant')]),
                                                              ('for_expr',
                                                               'a',
                                                               ('var', 'k'),
                                                               ('for_expr',
                                                                'b',
                                                                ('var', 'k'),
                                                                ('indexN',
                                                                 'm',
                                                                 [('index_item',
                                                                   ('var',
                                                                    'a')),
                                                                  ('index_item',
                                                                   ('var',
                                                                    'b'))])))),
                                                             ('body_index_assign_nd',
                                                              'new_adj',
                                                              [('index_item',
                                                                ('var', 'u')),
                                                               ('index_item',
                                                                ('var', 'v'))],
                                                              ('var', 'w')),
                                                             ('body_index_assign_nd',
                                                              'new_adj',
                                                              [('index_item',
                                                                ('var', 'v')),
                                                               ('index_item',
                                                                ('var', 'u'))],
                                                              ('var', 'w')),
                                                             ('body_field_assign',
                                                              ('var', 'this'),
                                                              'adjacency',
                                                              ('var',
                                                               'new_adj'))],
                                              'body': None},
                                             {'name': 'add_edge',
                                              'params': [('u', 'ℝ'),
                                                         ('v', 'ℝ')],
                                              'return_type': None,
                                              'statements': [('body_expr',
                                                              ('method_call',
                                                               ('var', 'this'),
                                                               'add_weighted_edge',
                                                               [('var', 'u'),
                                                                ('var', 'v'),
                                                                ('num',
                                                                 1.0)]))],
                                              'body': None}]},
             'NeuralFingerprint': {'class_params': [('Hw',
                                                     ('tensor',
                                                      [(2, 'invariant'),
                                                       (4, 'invariant'),
                                                       (4, 'invariant')])),
                                                    ('Wout',
                                                     ('tensor',
                                                      [(2, 'invariant'),
                                                       (4, 'invariant'),
                                                       (8, 'invariant')])),
                                                    ('Wr',
                                                     ('tensor',
                                                      [(8, 'invariant')]))],
                                   'fields': [],
                                   'methods': [{'name': 'λ',
                                                'params': [('A',
                                                            ('tensor',
                                                             [('n',
                                                               'invariant'),
                                                              ('n',
                                                               'invariant')])),
                                                           ('H0',
                                                            ('tensor',
                                                             [('n',
                                                               'invariant'),
                                                              (4,
                                                               'invariant')]))],
                                                'return_type': ('tensor',
                                                                [(8,
                                                                  'invariant')]),
                                                'statements': [('body_decl',
                                                                'f',
                                                                ('tensor',
                                                                 [(8,
                                                                   'invariant')]),
                                                                ('call',
                                                                 'zero_1d_array',
                                                                 [('num',
                                                                   8.0)])),
                                                               ('body_decl',
                                                                'r',
                                                                ('tensor',
                                                                 [('n',
                                                                   'invariant'),
                                                                  (4,
                                                                   'invariant')]),
                                                                ('var', 'H0')),
                                                               ('body_decl',
                                                                'n_atoms',
                                                                'ℝ',
                                                                ('call',
                                                                 'get_2d_array_num_rows',
                                                                 [('var',
                                                                   'A')])),
                                                               ('body_for_range',
                                                                'L',
                                                                ('num', 0),
                                                                ('num', 2),
                                                                [('loop_assign',
                                                                  'nbr_sum',
                                                                  ('matmul',
                                                                   ('var',
                                                                    'A'),
                                                                   ('var',
                                                                    'r'))),
                                                                 ('loop_assign',
                                                                  'v',
                                                                  ('add',
                                                                   ('var',
                                                                    'r'),
                                                                   ('var',
                                                                    'nbr_sum'))),
                                                                 ('loop_assign',
                                                                  'HwL',
                                                                  ('chain_index',
                                                                   ('field_access',
                                                                    ('var',
                                                                     'this'),
                                                                    'Hw'),
                                                                   ('var',
                                                                    'L'))),
                                                                 ('loop_assign',
                                                                  'r',
                                                                  ('call',
                                                                   'sigma',
                                                                   [('matmul',
                                                                     ('var',
                                                                      'v'),
                                                                     ('var',
                                                                      'HwL'))])),
                                                                 ('loop_assign',
                                                                  'WoutL',
                                                                  ('chain_index',
                                                                   ('field_access',
                                                                    ('var',
                                                                     'this'),
                                                                    'Wout'),
                                                                   ('var',
                                                                    'L'))),
                                                                 ('loop_assign',
                                                                  'logits',
                                                                  ('matmul',
                                                                   ('var',
                                                                    'r'),
                                                                   ('var',
                                                                    'WoutL'))),
                                                                 ('loop_for_range',
                                                                  'a',
                                                                  ('num', 0),
                                                                  ('var',
                                                                   'n_atoms'),
                                                                  [('loop_pluseq',
                                                                    'f',
                                                                    ('call',
                                                                     'softmax_row',
                                                                     [('index',
                                                                       'logits',
                                                                       ('var',
                                                                        'a'))]))])])],
                                                'body': ('var', 'f')},
                                               {'name': 'train',
                                                'params': [('epochs', 'ℕ'),
                                                           ('lr', 'ℝ')],
                                                'return_type': 'ℝ',
                                                'statements': [('body_decl',
                                                                'loss',
                                                                'ℝ',
                                                                ('num', 0)),
                                                               ('body_for_range',
                                                                'step',
                                                                ('num', 0),
                                                                ('var',
                                                                 'epochs'),
                                                                [('loop_assign',
                                                                  'fp_h2o',
                                                                  ('call',
                                                                   'this',
                                                                   [('var',
                                                                     'A_h2o'),
                                                                    ('var',
                                                                     'H0_h2o')])),
                                                                 ('loop_assign',
                                                                  'fp_ch4',
                                                                  ('call',
                                                                   'this',
                                                                   [('var',
                                                                     'A_ch4'),
                                                                    ('var',
                                                                     'H0_ch4')])),
                                                                 ('loop_assign',
                                                                  'pred_h2o',
                                                                  ('call',
                                                                   'get_sum_of_1d_array',
                                                                   [('mul',
                                                                     ('var',
                                                                      'fp_h2o'),
                                                                     ('field_access',
                                                                      ('var',
                                                                       'this'),
                                                                      'Wr'))])),
                                                                 ('loop_assign',
                                                                  'pred_ch4',
                                                                  ('call',
                                                                   'get_sum_of_1d_array',
                                                                   [('mul',
                                                                     ('var',
                                                                      'fp_ch4'),
                                                                     ('field_access',
                                                                      ('var',
                                                                       'this'),
                                                                      'Wr'))])),
                                                                 ('loop_assign',
                                                                  'loss',
                                                                  ('add',
                                                                   ('call',
                                                                    'mse',
                                                                    [('var',
                                                                      'pred_h2o'),
                                                                     ('var',
                                                                      'target_h2o')]),
                                                                   ('call',
                                                                    'mse',
                                                                    [('var',
                                                                      'pred_ch4'),
                                                                     ('var',
                                                                      'target_ch4')]))),
                                                                 ('loop_assign',
                                                                  'g',
                                                                  ('call',
                                                                   'grad',
                                                                   [('var',
                                                                     'loss'),
                                                                    ('field_access',
                                                                     ('var',
                                                                      'this'),
                                                                     'learnable_params')])),
                                                                 ('body_field_assign',
                                                                  ('var',
                                                                   'this'),
                                                                  'Hw',
                                                                  ('sub',
                                                                   ('field_access',
                                                                    ('var',
                                                                     'this'),
                                                                    'Hw'),
                                                                   ('mul',
                                                                    ('var',
                                                                     'lr'),
                                                                    ('index',
                                                                     'g',
                                                                     ('num',
                                                                      0))))),
                                                                 ('body_field_assign',
                                                                  ('var',
                                                                   'this'),
                                                                  'Wout',
                                                                  ('sub',
                                                                   ('field_access',
                                                                    ('var',
                                                                     'this'),
                                                                    'Wout'),
                                                                   ('mul',
                                                                    ('var',
                                                                     'lr'),
                                                                    ('index',
                                                                     'g',
                                                                     ('num',
                                                                      1))))),
                                                                 ('body_field_assign',
                                                                  ('var',
                                                                   'this'),
                                                                  'Wr',
                                                                  ('sub',
                                                                   ('field_access',
                                                                    ('var',
                                                                     'this'),
                                                                    'Wr'),
                                                                   ('mul',
                                                                    ('var',
                                                                     'lr'),
                                                                    ('index',
                                                                     'g',
                                                                     ('num',
                                                                      2)))))])],
                                                'body': ('var', 'loss')}]}},
 'program': [('func_def', 'get_sum_of_1d_array'),
             ('func_def', 'get_1d_array_length'),
             ('func_def', 'get_2d_array_num_rows'),
             ('func_def', 'zero_1d_array'),
             ('func_def', 'sigma'),
             ('func_def', 'softmax_row'),
             ('func_def', 'mse'),
             ('class_def', 'UndirectedGraph'),
             ('func_def', 'empty_graph'),
             ('class_def', 'NeuralFingerprint'),
             ('decl', 'μ', 'ℝ', ('num', 0.0), 91),
             ('decl', 'σ', 'ℝ', ('num', 1.0), 92),
             ('decl',
              'Hw',
              ('tensor',
               [(2, 'invariant'), (4, 'invariant'), (4, 'invariant')]),
              ('for_expr',
               'i',
               ('num', 2),
               ('for_expr',
                'j',
                ('num', 4),
                ('typed_sample_expr',
                 'row',
                 ('tensor', [(4, 'invariant')]),
                 ('call',
                  'Normal',
                  [('var', 'μ'), ('var', 'σ'), ('num', 4)])))),
              94),
             ('decl',
              'Wout',
              ('tensor',
               [(2, 'invariant'), (4, 'invariant'), (8, 'invariant')]),
              ('for_expr',
               'i',
               ('num', 2),
               ('for_expr',
                'j',
                ('num', 4),
                ('typed_sample_expr',
                 'row',
                 ('tensor', [(8, 'invariant')]),
                 ('call',
                  'Normal',
                  [('var', 'μ'), ('var', 'σ'), ('num', 8)])))),
              95),
             ('typed_sample',
              'Wr',
              ('tensor', [(8, 'invariant')]),
              ('call', 'Normal', [('var', 'μ'), ('var', 'σ'), ('num', 8)]),
              96),
             ('decl',
              'fp_model',
              ('struct_type', 'NeuralFingerprint'),
              ('call',
               'NeuralFingerprint',
               [('var', 'Hw'), ('var', 'Wout'), ('var', 'Wr')]),
              98),
             ('decl', 'n0', 'ℕ', ('num', 3), 100),
             ('decl',
              'g',
              ('struct_type', 'UndirectedGraph'),
              ('call', 'empty_graph', [('var', 'n0')]),
              101),
             ('expr',
              ('method_call',
               ('var', 'g'),
               'add_edge',
               [('num', 0.0), ('num', 1.0)]),
              0),
             ('expr',
              ('method_call',
               ('var', 'g'),
               'add_edge',
               [('num', 1.0), ('num', 2.0)]),
              0),
             ('decl',
              'H0',
              ('tensor', [(3, 'invariant'), (4, 'invariant')]),
              ('for_expr',
               'i',
               ('num', 3),
               ('typed_sample_expr',
                'row',
                ('tensor', [(4, 'invariant')]),
                ('call', 'Normal', [('var', 'μ'), ('var', 'σ'), ('num', 4)]))),
              105),
             ('decl',
              'fingerprint',
              ('tensor', [(8, 'invariant')]),
              ('call',
               'fp_model',
               [('field_access', ('var', 'g'), 'adjacency'), ('var', 'H0')]),
              107),
             ('expr', ('var', 'fingerprint'), 0),
             ('decl',
              'fp_sum',
              'ℝ',
              ('call', 'get_sum_of_1d_array', [('var', 'fingerprint')]),
              110),
             ('expr', ('call', 'grad', [('var', 'fp_sum'), ('var', 'H0')]), 0),
             ('expr',
              ('call',
               'grad',
               [('var', 'fp_sum'),
                ('field_access', ('var', 'fp_model'), 'learnable_params')]),
              0),
             ('decl',
              'A_h2o',
              ('tensor', [(3, 'invariant'), (3, 'invariant')]),
              ('array',
               [('array', [('num', 0.0), ('num', 1.0), ('num', 1.0)]),
                ('array', [('num', 1.0), ('num', 0.0), ('num', 0.0)]),
                ('array', [('num', 1.0), ('num', 0.0), ('num', 0.0)])]),
              123),
             ('decl',
              'H0_h2o',
              ('tensor', [(3, 'invariant'), (4, 'invariant')]),
              ('array',
               [('array',
                 [('num', 0.0), ('num', 0.0), ('num', 1.0), ('num', 0.0)]),
                ('array',
                 [('num', 1.0), ('num', 0.0), ('num', 0.0), ('num', 0.0)]),
                ('array',
                 [('num', 1.0), ('num', 0.0), ('num', 0.0), ('num', 0.0)])]),
              128),
             ('decl',
              'A_ch4',
              ('tensor', [(5, 'invariant'), (5, 'invariant')]),
              ('array',
               [('array',
                 [('num', 0.0),
                  ('num', 1.0),
                  ('num', 1.0),
                  ('num', 1.0),
                  ('num', 1.0)]),
                ('array',
                 [('num', 1.0),
                  ('num', 0.0),
                  ('num', 0.0),
                  ('num', 0.0),
                  ('num', 0.0)]),
                ('array',
                 [('num', 1.0),
                  ('num', 0.0),
                  ('num', 0.0),
                  ('num', 0.0),
                  ('num', 0.0)]),
                ('array',
                 [('num', 1.0),
                  ('num', 0.0),
                  ('num', 0.0),
                  ('num', 0.0),
                  ('num', 0.0)]),
                ('array',
                 [('num', 1.0),
                  ('num', 0.0),
                  ('num', 0.0),
                  ('num', 0.0),
                  ('num', 0.0)])]),
              135),
             ('decl',
              'H0_ch4',
              ('tensor', [(5, 'invariant'), (4, 'invariant')]),
              ('array',
               [('array',
                 [('num', 0.0), ('num', 1.0), ('num', 0.0), ('num', 0.0)]),
                ('array',
                 [('num', 1.0), ('num', 0.0), ('num', 0.0), ('num', 0.0)]),
                ('array',
                 [('num', 1.0), ('num', 0.0), ('num', 0.0), ('num', 0.0)]),
                ('array',
                 [('num', 1.0), ('num', 0.0), ('num', 0.0), ('num', 0.0)]),
                ('array',
                 [('num', 1.0), ('num', 0.0), ('num', 0.0), ('num', 0.0)])]),
              142),
             ('decl',
              'fp_h2o',
              ('tensor', [(8, 'invariant')]),
              ('call', 'fp_model', [('var', 'A_h2o'), ('var', 'H0_h2o')]),
              150),
             ('decl',
              'fp_ch4',
              ('tensor', [(8, 'invariant')]),
              ('call', 'fp_model', [('var', 'A_ch4'), ('var', 'H0_ch4')]),
              151),
             ('expr', ('var', 'fp_h2o'), 0),
             ('expr', ('var', 'fp_ch4'), 0),
             ('decl', 'target_h2o', 'ℝ', ('num', 1.0), 165),
             ('decl', 'target_ch4', 'ℝ', ('num', 0.0), 166),
             ('decl',
              'pred_h2o_0',
              'ℝ',
              ('call',
               'get_sum_of_1d_array',
               [('mul',
                 ('var', 'fp_h2o'),
                 ('field_access', ('var', 'fp_model'), 'Wr'))]),
              168),
             ('decl',
              'pred_ch4_0',
              'ℝ',
              ('call',
               'get_sum_of_1d_array',
               [('mul',
                 ('var', 'fp_ch4'),
                 ('field_access', ('var', 'fp_model'), 'Wr'))]),
              169),
             ('decl',
              'loss0',
              'ℝ',
              ('add',
               ('call', 'mse', [('var', 'pred_h2o_0'), ('var', 'target_h2o')]),
               ('call',
                'mse',
                [('var', 'pred_ch4_0'), ('var', 'target_ch4')])),
              170),
             ('expr', ('var', 'pred_h2o_0'), 0),
             ('expr', ('var', 'pred_ch4_0'), 0),
             ('expr', ('var', 'loss0'), 0),
             ('decl', 'epochs', 'ℕ', ('num', 300), 176),
             ('decl', 'lr', 'ℝ', ('num', 0.01), 177),
             ('decl',
              'final_loss',
              'ℝ',
              ('method_call',
               ('var', 'fp_model'),
               'train',
               [('var', 'epochs'), ('var', 'lr')]),
              178),
             ('expr', ('var', 'final_loss'), 0),
             ('decl',
              'fp_h2o_trained',
              ('tensor', [(8, 'invariant')]),
              ('call', 'fp_model', [('var', 'A_h2o'), ('var', 'H0_h2o')]),
              181),
             ('decl',
              'fp_ch4_trained',
              ('tensor', [(8, 'invariant')]),
              ('call', 'fp_model', [('var', 'A_ch4'), ('var', 'H0_ch4')]),
              182),
             ('decl',
              'pred_h2o_1',
              'ℝ',
              ('call',
               'get_sum_of_1d_array',
               [('mul',
                 ('var', 'fp_h2o_trained'),
                 ('field_access', ('var', 'fp_model'), 'Wr'))]),
              183),
             ('decl',
              'pred_ch4_1',
              'ℝ',
              ('call',
               'get_sum_of_1d_array',
               [('mul',
                 ('var', 'fp_ch4_trained'),
                 ('field_access', ('var', 'fp_model'), 'Wr'))]),
              184),
             ('expr', ('var', 'pred_h2o_1'), 0),
             ('expr', ('var', 'pred_ch4_1'), 0)]}
