EXPECTED = {'functions': {'get_1d_array_length': {'params': [('x',
                                                   ('tensor',
                                                    [('m', 'invariant')]))],
                                       'return_type': 'ℝ',
                                       'body': ('var', 'total'),
                                       'has_loop': False,
                                       'statements': [('body_decl',
                                                       'total',
                                                       'ℝ',
                                                       ('num', 0)),
                                                      ('body_decl',
                                                       'temp',
                                                       'ℝ',
                                                       ('num', 0)),
                                                      ('body_for',
                                                       'i',
                                                       [('loop_assign',
                                                         'temp',
                                                         ('index',
                                                          'x',
                                                          ('imaginary',))),
                                                        ('loop_pluseq',
                                                         'total',
                                                         ('num', 1))],
                                                       ['x'])]},
               'get_2d_array_num_rows': {'params': [('x',
                                                     ('tensor',
                                                      [('m', 'invariant'),
                                                       ('n', 'invariant')]))],
                                         'return_type': 'ℝ',
                                         'body': ('var', 'total'),
                                         'has_loop': False,
                                         'statements': [('body_decl',
                                                         'total',
                                                         'ℝ',
                                                         ('num', 0)),
                                                        ('body_decl',
                                                         'temp',
                                                         'ℝ',
                                                         ('num', 0)),
                                                        ('body_for',
                                                         'i',
                                                         [('loop_assign',
                                                           'temp',
                                                           ('index',
                                                            'x',
                                                            ('imaginary',))),
                                                          ('loop_pluseq',
                                                           'total',
                                                           ('num', 1))],
                                                         ['x'])]},
               'zero_1d_array': {'params': [('len', 'ℝ')],
                                 'return_type': ('tensor',
                                                 [('m', 'invariant')]),
                                 'body': ('var', 'results'),
                                 'has_loop': False,
                                 'statements': [('body_decl',
                                                 'results',
                                                 ('tensor',
                                                  [('len', 'invariant')]),
                                                 ('for_expr',
                                                  'i',
                                                  ('var', 'len'),
                                                  ('mul',
                                                   ('imaginary',),
                                                   ('num', 0))))]},
               'zero_2d_array': {'params': [('rows', 'ℝ'), ('cols', 'ℝ')],
                                 'return_type': ('tensor',
                                                 [('m', 'invariant'),
                                                  ('n', 'invariant')]),
                                 'body': ('var', 'results'),
                                 'has_loop': False,
                                 'statements': [('body_decl',
                                                 'results',
                                                 ('tensor',
                                                  [('rows', 'invariant'),
                                                   ('cols', 'invariant')]),
                                                 ('for_expr',
                                                  'i',
                                                  ('var', 'rows'),
                                                  ('for_expr',
                                                   'j',
                                                   ('var', 'cols'),
                                                   ('mul',
                                                    ('var', 'j'),
                                                    ('num', 0)))))]},
               'relu': {'params': [('x', 'ℝ')],
                        'return_type': 'ℝ',
                        'body': None,
                        'has_loop': False,
                        'statements': [('body_if_else_return',
                                        ('cond_gt', ('var', 'x'), ('num', 0)),
                                        ('var', 'x'),
                                        ('num', 0.0))]},
               'relu1d': {'params': [('x', ('tensor', [('m', 'invariant')]))],
                          'return_type': ('tensor', [('m', 'invariant')]),
                          'body': ('var', 'results'),
                          'has_loop': False,
                          'statements': [('body_decl',
                                          'len_x',
                                          'ℝ',
                                          ('call',
                                           'get_1d_array_length',
                                           [('var', 'x')])),
                                         ('body_decl',
                                          'results',
                                          ('tensor', [('len_x', 'invariant')]),
                                          ('call',
                                           'zero_1d_array',
                                           [('var', 'len_x')])),
                                         ('body_for_range',
                                          'i',
                                          ('num', 0),
                                          ('var', 'len_x'),
                                          [('loop_index_assign_nd',
                                            'results',
                                            [('index_item', ('imaginary',))],
                                            ('call',
                                             'relu',
                                             [('index',
                                               'x',
                                               ('imaginary',))]))])]},
               'linear': {'params': [('x', ('tensor', [('n', 'invariant')])),
                                     ('weight',
                                      ('tensor',
                                       [('m', 'invariant'),
                                        ('n', 'invariant')])),
                                     ('bias',
                                      ('tensor', [('m', 'invariant')]))],
                          'return_type': ('tensor', [('m', 'invariant')]),
                          'body': ('var', 'results'),
                          'has_loop': False,
                          'statements': [('body_decl',
                                          'out',
                                          'ℝ',
                                          ('call',
                                           'get_1d_array_length',
                                           [('var', 'bias')])),
                                         ('body_decl',
                                          'inp',
                                          'ℝ',
                                          ('call',
                                           'get_1d_array_length',
                                           [('var', 'x')])),
                                         ('body_decl',
                                          'results',
                                          ('tensor', [('out', 'invariant')]),
                                          ('call',
                                           'zero_1d_array',
                                           [('var', 'out')])),
                                         ('body_for_range',
                                          'i',
                                          ('num', 0),
                                          ('var', 'out'),
                                          [('loop_assign', 'acc', ('num', 0)),
                                           ('loop_for_range',
                                            'j',
                                            ('num', 0),
                                            ('var', 'inp'),
                                            [('loop_pluseq',
                                              'acc',
                                              ('mul',
                                               ('indexN',
                                                'weight',
                                                [('index_item', ('imaginary',)),
                                                 ('index_item', ('var', 'j'))]),
                                               ('index', 'x', ('var', 'j'))))]),
                                           ('loop_index_assign_nd',
                                            'results',
                                            [('index_item', ('imaginary',))],
                                            ('add',
                                             ('var', 'acc'),
                                             ('index',
                                              'bias',
                                              ('imaginary',))))])]},
               'flatten_image': {'params': [('img',
                                             ('tensor',
                                              [('H', 'invariant'),
                                               ('W', 'invariant')]))],
                                 'return_type': ('tensor',
                                                 [('n', 'invariant')]),
                                 'body': ('var', 'results'),
                                 'has_loop': False,
                                 'statements': [('body_decl',
                                                 'rows',
                                                 'ℝ',
                                                 ('call',
                                                  'get_2d_array_num_rows',
                                                  [('var', 'img')])),
                                                ('body_decl',
                                                 'cols',
                                                 'ℝ',
                                                 ('call',
                                                  'get_1d_array_length',
                                                  [('index',
                                                    'img',
                                                    ('num', 0))])),
                                                ('body_decl',
                                                 'n',
                                                 'ℝ',
                                                 ('mul',
                                                  ('var', 'rows'),
                                                  ('var', 'cols'))),
                                                ('body_decl',
                                                 'results',
                                                 ('tensor',
                                                  [('n', 'invariant')]),
                                                 ('call',
                                                  'zero_1d_array',
                                                  [('var', 'n')])),
                                                ('body_for_range',
                                                 'i',
                                                 ('num', 0),
                                                 ('var', 'rows'),
                                                 [('loop_for_range',
                                                   'j',
                                                   ('num', 0),
                                                   ('var', 'cols'),
                                                   [('loop_index_assign_nd',
                                                     'results',
                                                     [('index_item',
                                                       ('add',
                                                        ('mul',
                                                         ('imaginary',),
                                                         ('var', 'cols')),
                                                        ('var', 'j')))],
                                                     ('add',
                                                      ('div',
                                                       ('indexN',
                                                        'img',
                                                        [('index_item',
                                                          ('imaginary',)),
                                                         ('index_item',
                                                          ('var', 'j'))]),
                                                       ('num', 256.0)),
                                                      ('div',
                                                       ('num', 0.5),
                                                       ('num', 256.0))))])])]},
               'first_half': {'params': [('x',
                                          ('tensor', [('m', 'invariant')]))],
                              'return_type': ('tensor', [('n', 'invariant')]),
                              'body': ('var', 'results'),
                              'has_loop': False,
                              'statements': [('body_decl',
                                              'half',
                                              'ℝ',
                                              ('div',
                                               ('call',
                                                'get_1d_array_length',
                                                [('var', 'x')]),
                                               ('num', 2))),
                                             ('body_decl',
                                              'results',
                                              ('tensor',
                                               [('half', 'invariant')]),
                                              ('call',
                                               'zero_1d_array',
                                               [('var', 'half')])),
                                             ('body_for_range',
                                              'i',
                                              ('num', 0),
                                              ('var', 'half'),
                                              [('loop_index_assign_nd',
                                                'results',
                                                [('index_item',
                                                  ('imaginary',))],
                                                ('index',
                                                 'x',
                                                 ('imaginary',)))])]},
               'second_half': {'params': [('x',
                                           ('tensor', [('m', 'invariant')]))],
                               'return_type': ('tensor', [('n', 'invariant')]),
                               'body': ('var', 'results'),
                               'has_loop': False,
                               'statements': [('body_decl',
                                               'len_x',
                                               'ℝ',
                                               ('call',
                                                'get_1d_array_length',
                                                [('var', 'x')])),
                                              ('body_decl',
                                               'half',
                                               'ℝ',
                                               ('div',
                                                ('var', 'len_x'),
                                                ('num', 2))),
                                              ('body_decl',
                                               'results',
                                               ('tensor',
                                                [('half', 'invariant')]),
                                               ('call',
                                                'zero_1d_array',
                                                [('var', 'half')])),
                                              ('body_for_range',
                                               'i',
                                               ('num', 0),
                                               ('var', 'half'),
                                               [('loop_index_assign_nd',
                                                 'results',
                                                 [('index_item',
                                                   ('imaginary',))],
                                                 ('index',
                                                  'x',
                                                  ('add',
                                                   ('imaginary',),
                                                   ('var', 'half'))))])]},
               'concat_1d_array': {'params': [('x1',
                                               ('tensor',
                                                [('m', 'invariant')])),
                                              ('x2',
                                               ('tensor',
                                                [('n', 'invariant')]))],
                                   'return_type': ('tensor',
                                                   [('p', 'invariant')]),
                                   'body': ('var', 'results'),
                                   'has_loop': False,
                                   'statements': [('body_decl',
                                                   'len1',
                                                   'ℝ',
                                                   ('call',
                                                    'get_1d_array_length',
                                                    [('var', 'x1')])),
                                                  ('body_decl',
                                                   'len2',
                                                   'ℝ',
                                                   ('call',
                                                    'get_1d_array_length',
                                                    [('var', 'x2')])),
                                                  ('body_decl',
                                                   'total',
                                                   'ℝ',
                                                   ('add',
                                                    ('var', 'len1'),
                                                    ('var', 'len2'))),
                                                  ('body_decl',
                                                   'results',
                                                   ('tensor',
                                                    [('total', 'invariant')]),
                                                   ('call',
                                                    'zero_1d_array',
                                                    [('var', 'total')])),
                                                  ('body_for_range',
                                                   'i',
                                                   ('num', 0),
                                                   ('var', 'len1'),
                                                   [('loop_index_assign_nd',
                                                     'results',
                                                     [('index_item',
                                                       ('imaginary',))],
                                                     ('index',
                                                      'x1',
                                                      ('imaginary',)))]),
                                                  ('body_for_range',
                                                   'i',
                                                   ('num', 0),
                                                   ('var', 'len2'),
                                                   [('loop_index_assign_nd',
                                                     'results',
                                                     [('index_item',
                                                       ('add',
                                                        ('imaginary',),
                                                        ('var', 'len1')))],
                                                     ('index',
                                                      'x2',
                                                      ('imaginary',)))])]},
               'swap_halves': {'params': [('x',
                                           ('tensor', [('m', 'invariant')]))],
                               'return_type': ('tensor', [('m', 'invariant')]),
                               'body': ('call',
                                        'concat_1d_array',
                                        [('var', 'x2'), ('var', 'x1')]),
                               'has_loop': False,
                               'statements': [('body_decl',
                                               'x1',
                                               ('tensor', [('n', 'invariant')]),
                                               ('call',
                                                'first_half',
                                                [('var', 'x')])),
                                              ('body_decl',
                                               'x2',
                                               ('tensor', [('n', 'invariant')]),
                                               ('call',
                                                'second_half',
                                                [('var', 'x')]))]},
               'gaussian_log_prob': {'params': [('x',
                                                 ('tensor',
                                                  [('m', 'invariant')]))],
                                     'return_type': 'ℝ',
                                     'body': ('var', 'total'),
                                     'has_loop': False,
                                     'statements': [('body_decl',
                                                     'len_x',
                                                     'ℝ',
                                                     ('call',
                                                      'get_1d_array_length',
                                                      [('var', 'x')])),
                                                    ('body_decl',
                                                     'total',
                                                     'ℝ',
                                                     ('num', 0)),
                                                    ('body_for_range',
                                                     'i',
                                                     ('num', 0),
                                                     ('var', 'len_x'),
                                                     [('loop_pluseq',
                                                       'total',
                                                       ('sub',
                                                        ('mul',
                                                         ('mul',
                                                          ('neg', ('num', 0.5)),
                                                          ('index',
                                                           'x',
                                                           ('imaginary',))),
                                                         ('index',
                                                          'x',
                                                          ('imaginary',))),
                                                        ('mul',
                                                         ('num', 0.5),
                                                         ('call',
                                                          'log',
                                                          [('mul',
                                                            ('num', 2),
                                                            ('num',
                                                             3.14159265))]))))])]},
               'neg_loglik': {'params': [('log_px', 'ℝ')],
                              'return_type': 'ℝ',
                              'body': ('neg', ('var', 'log_px')),
                              'has_loop': False,
                              'statements': []}},
 'classes': {'NICE': {'class_params': [('w1a',
                                        ('tensor',
                                         [('H', 'invariant'),
                                          ('n', 'invariant')])),
                                       ('b1a',
                                        ('tensor', [('H', 'invariant')])),
                                       ('w2a',
                                        ('tensor',
                                         [('n', 'invariant'),
                                          ('H', 'invariant')])),
                                       ('b2a',
                                        ('tensor', [('n', 'invariant')])),
                                       ('w1b',
                                        ('tensor',
                                         [('H', 'invariant'),
                                          ('n', 'invariant')])),
                                       ('b1b',
                                        ('tensor', [('H', 'invariant')])),
                                       ('w2b',
                                        ('tensor',
                                         [('n', 'invariant'),
                                          ('H', 'invariant')])),
                                       ('b2b',
                                        ('tensor', [('n', 'invariant')])),
                                       ('a', ('tensor', [('m', 'invariant')]))],
                      'fields': [],
                      'methods': [{'name': 'coupling',
                                   'params': [('x',
                                               ('tensor',
                                                [('m', 'invariant')])),
                                              ('w1',
                                               ('tensor',
                                                [('H', 'invariant'),
                                                 ('n', 'invariant')])),
                                              ('b1',
                                               ('tensor',
                                                [('H', 'invariant')])),
                                              ('w2',
                                               ('tensor',
                                                [('n', 'invariant'),
                                                 ('H', 'invariant')])),
                                              ('b2',
                                               ('tensor',
                                                [('n', 'invariant')]))],
                                   'return_type': ('tensor',
                                                   [('m', 'invariant')]),
                                   'statements': [('body_decl',
                                                   'x1',
                                                   ('tensor',
                                                    [('n', 'invariant')]),
                                                   ('call',
                                                    'first_half',
                                                    [('var', 'x')])),
                                                  ('body_decl',
                                                   'x2',
                                                   ('tensor',
                                                    [('n', 'invariant')]),
                                                   ('call',
                                                    'second_half',
                                                    [('var', 'x')])),
                                                  ('body_decl',
                                                   'shift',
                                                   ('tensor',
                                                    [('n', 'invariant')]),
                                                   ('call',
                                                    'linear',
                                                    [('call',
                                                      'relu1d',
                                                      [('call',
                                                        'linear',
                                                        [('var', 'x1'),
                                                         ('var', 'w1'),
                                                         ('var', 'b1')])]),
                                                     ('var', 'w2'),
                                                     ('var', 'b2')])),
                                                  ('body_decl',
                                                   'y2',
                                                   ('tensor',
                                                    [('n', 'invariant')]),
                                                   ('add',
                                                    ('var', 'x2'),
                                                    ('var', 'shift')))],
                                   'body': ('call',
                                            'concat_1d_array',
                                            [('var', 'x1'), ('var', 'y2')])},
                                  {'name': 'rescale',
                                   'params': [('x',
                                               ('tensor',
                                                [('m', 'invariant')]))],
                                   'return_type': ('tensor',
                                                   [('m', 'invariant')]),
                                   'statements': [('body_decl',
                                                   's',
                                                   ('tensor',
                                                    [('m', 'invariant')]),
                                                   ('call',
                                                    'exp',
                                                    [('field_access',
                                                      ('var', 'this'),
                                                      'a')]))],
                                   'body': ('mul', ('var', 'x'), ('var', 's'))},
                                  {'name': 'rescale_log_det',
                                   'params': [],
                                   'return_type': 'ℝ',
                                   'statements': [],
                                   'body': ('call',
                                            'sum',
                                            [('field_access',
                                              ('var', 'this'),
                                              'a')])},
                                  {'name': 'λ',
                                   'params': [('x',
                                               ('tensor',
                                                [('m', 'invariant')]))],
                                   'return_type': 'ℝ',
                                   'statements': [('body_decl',
                                                   'h',
                                                   ('tensor',
                                                    [('m', 'invariant')]),
                                                   ('var', 'x')),
                                                  ('body_assign',
                                                   'h',
                                                   ('method_call',
                                                    ('var', 'this'),
                                                    'coupling',
                                                    [('var', 'h'),
                                                     ('field_access',
                                                      ('var', 'this'),
                                                      'w1a'),
                                                     ('field_access',
                                                      ('var', 'this'),
                                                      'b1a'),
                                                     ('field_access',
                                                      ('var', 'this'),
                                                      'w2a'),
                                                     ('field_access',
                                                      ('var', 'this'),
                                                      'b2a')])),
                                                  ('body_assign',
                                                   'h',
                                                   ('call',
                                                    'swap_halves',
                                                    [('var', 'h')])),
                                                  ('body_assign',
                                                   'h',
                                                   ('method_call',
                                                    ('var', 'this'),
                                                    'coupling',
                                                    [('var', 'h'),
                                                     ('field_access',
                                                      ('var', 'this'),
                                                      'w1b'),
                                                     ('field_access',
                                                      ('var', 'this'),
                                                      'b1b'),
                                                     ('field_access',
                                                      ('var', 'this'),
                                                      'w2b'),
                                                     ('field_access',
                                                      ('var', 'this'),
                                                      'b2b')])),
                                                  ('body_assign',
                                                   'h',
                                                   ('call',
                                                    'swap_halves',
                                                    [('var', 'h')])),
                                                  ('body_decl',
                                                   'z',
                                                   ('tensor',
                                                    [('m', 'invariant')]),
                                                   ('method_call',
                                                    ('var', 'this'),
                                                    'rescale',
                                                    [('var', 'h')])),
                                                  ('body_decl',
                                                   'log_pz',
                                                   'ℝ',
                                                   ('call',
                                                    'gaussian_log_prob',
                                                    [('var', 'z')])),
                                                  ('body_decl',
                                                   'log_px',
                                                   'ℝ',
                                                   ('add',
                                                    ('var', 'log_pz'),
                                                    ('method_call',
                                                     ('var', 'this'),
                                                     'rescale_log_det',
                                                     [])))],
                                   'body': ('var', 'log_px')},
                                  {'name': 'loss',
                                   'params': [('pred', 'ℝ'), ('target', 'ℝ')],
                                   'return_type': 'ℝ',
                                   'statements': [],
                                   'body': ('neg', ('var', 'pred'))}]}},
 'program': [('func_def', 'get_1d_array_length'),
             ('func_def', 'get_2d_array_num_rows'),
             ('func_def', 'zero_1d_array'),
             ('func_def', 'zero_2d_array'),
             ('func_def', 'relu'),
             ('func_def', 'relu1d'),
             ('func_def', 'linear'),
             ('func_def', 'flatten_image'),
             ('func_def', 'first_half'),
             ('func_def', 'second_half'),
             ('func_def', 'concat_1d_array'),
             ('func_def', 'swap_halves'),
             ('func_def', 'gaussian_log_prob'),
             ('func_def', 'neg_loglik'),
             ('class_def', 'NICE'),
             ('assign',
              'dataset',
              ('call', 'create_dataset', [('num', 80), ('num', 100)]),
              147),
             ('assign', 'train_dataset', ('index', 'dataset', ('num', 0)), 148),
             ('assign', 'test_dataset', ('index', 'dataset', ('num', 1)), 149),
             ('assign', 'train_X', ('index', 'train_dataset', ('num', 0)), 151),
             ('assign', 'test_X', ('index', 'test_dataset', ('num', 0)), 152),
             ('decl',
              'len_train_X',
              'ℝ',
              ('call', 'get_1d_array_length', [('var', 'train_X')]),
              154),
             ('decl',
              'len_test_X',
              'ℝ',
              ('call', 'get_1d_array_length', [('var', 'test_X')]),
              155),
             ('decl', 'ndim', 'ℝ', ('num', 784), 159),
             ('decl', 'hidden', 'ℝ', ('num', 16), 160),
             ('decl', 'half', 'ℝ', ('div', ('var', 'ndim'), ('num', 2)), 161),
             ('decl',
              'w1a',
              ('tensor', [('hidden', 'invariant'), ('half', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'hidden'),
               ('for_expr',
                'j',
                ('var', 'half'),
                ('mul',
                 ('mul',
                  ('call',
                   'sin',
                   [('div',
                     ('mul', ('num', 3.14), ('imaginary',)),
                     ('var', 'hidden'))]),
                  ('call',
                   'cos',
                   [('div',
                     ('mul', ('num', 3.14), ('var', 'j')),
                     ('var', 'half'))])),
                 ('num', 0.01)))),
              163),
             ('decl',
              'b1a',
              ('tensor', [('hidden', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'hidden'),
               ('mul', ('imaginary',), ('num', 0))),
              164),
             ('decl',
              'w2a',
              ('tensor', [('half', 'invariant'), ('hidden', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'half'),
               ('for_expr',
                'j',
                ('var', 'hidden'),
                ('mul',
                 ('mul',
                  ('call',
                   'cos',
                   [('div',
                     ('mul', ('num', 3.14), ('imaginary',)),
                     ('var', 'half'))]),
                  ('call',
                   'sin',
                   [('div',
                     ('mul', ('num', 3.14), ('var', 'j')),
                     ('var', 'hidden'))])),
                 ('num', 0.01)))),
              165),
             ('decl',
              'b2a',
              ('tensor', [('half', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'half'),
               ('mul', ('imaginary',), ('num', 0))),
              166),
             ('decl',
              'w1b',
              ('tensor', [('hidden', 'invariant'), ('half', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'hidden'),
               ('for_expr',
                'j',
                ('var', 'half'),
                ('mul',
                 ('mul',
                  ('call',
                   'sin',
                   [('div',
                     ('mul', ('num', 3.14), ('imaginary',)),
                     ('var', 'hidden'))]),
                  ('call',
                   'cos',
                   [('div',
                     ('mul', ('num', 3.14), ('var', 'j')),
                     ('var', 'half'))])),
                 ('num', 0.01)))),
              168),
             ('decl',
              'b1b',
              ('tensor', [('hidden', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'hidden'),
               ('mul', ('imaginary',), ('num', 0))),
              169),
             ('decl',
              'w2b',
              ('tensor', [('half', 'invariant'), ('hidden', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'half'),
               ('for_expr',
                'j',
                ('var', 'hidden'),
                ('mul',
                 ('mul',
                  ('call',
                   'cos',
                   [('div',
                     ('mul', ('num', 3.14), ('imaginary',)),
                     ('var', 'half'))]),
                  ('call',
                   'sin',
                   [('div',
                     ('mul', ('num', 3.14), ('var', 'j')),
                     ('var', 'hidden'))])),
                 ('num', 0.01)))),
              170),
             ('decl',
              'b2b',
              ('tensor', [('half', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'half'),
               ('mul', ('imaginary',), ('num', 0))),
              171),
             ('decl',
              'a_init',
              ('tensor', [('ndim', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'ndim'),
               ('mul', ('imaginary',), ('num', 0))),
              173),
             ('decl',
              'nice_object',
              ('struct_type', 'NICE'),
              ('call',
               'NICE',
               [('var', 'w1a'),
                ('var', 'b1a'),
                ('var', 'w2a'),
                ('var', 'b2a'),
                ('var', 'w1b'),
                ('var', 'b1b'),
                ('var', 'w2b'),
                ('var', 'b2b'),
                ('var', 'a_init')]),
              175),
             ('assign',
              'debug_input',
              ('call', 'flatten_image', [('index', 'train_X', ('num', 0))]),
              179),
             ('assign',
              'debug_log_px',
              ('call', 'nice_object', [('var', 'debug_input')]),
              180),
             ('expr', ('call', 'print', [('var', 'debug_log_px')]), 0),
             ('expr', ('call', 'print', [('var', 'DEVICE')]), 0),
             ('decl',
              'train_X_flat',
              ('tensor', [('len_train_X', 'invariant'), ('ndim', 'invariant')]),
              ('call',
               'zero_2d_array',
               [('var', 'len_train_X'), ('var', 'ndim')]),
              186),
             ('for_loop_range',
              'i',
              ('num', 0),
              ('var', 'len_train_X'),
              [('for_assign',
                'flat',
                ('call',
                 'flatten_image',
                 [('index', 'train_X', ('imaginary',))])),
               ('for_loop_range',
                'j',
                ('num', 0),
                ('var', 'ndim'),
                [('for_index_assign_nd',
                  'train_X_flat',
                  [('index_item', ('imaginary',)),
                   ('index_item', ('var', 'j'))],
                  ('index', 'flat', ('var', 'j')))],
                189)],
              187),
             ('decl',
              'test_X_flat',
              ('tensor', [('len_test_X', 'invariant'), ('ndim', 'invariant')]),
              ('call',
               'zero_2d_array',
               [('var', 'len_test_X'), ('var', 'ndim')]),
              192),
             ('for_loop_range',
              'i',
              ('num', 0),
              ('var', 'len_test_X'),
              [('for_assign',
                'flat',
                ('call',
                 'flatten_image',
                 [('index', 'test_X', ('imaginary',))])),
               ('for_loop_range',
                'j',
                ('num', 0),
                ('var', 'ndim'),
                [('for_index_assign_nd',
                  'test_X_flat',
                  [('index_item', ('imaginary',)),
                   ('index_item', ('var', 'j'))],
                  ('index', 'flat', ('var', 'j')))],
                195)],
              193),
             ('decl',
              'dummy_y',
              ('tensor', [('len_train_X', 'invariant')]),
              ('call', 'zero_1d_array', [('var', 'len_train_X')]),
              199),
             ('decl', 'epochs', 'ℕ', ('num', 10), 204),
             ('decl', 'lr', 'ℝ', ('num', 0.005), 205),
             ('decl',
              'losses',
              ('tensor', [('epochs', 'invariant')]),
              ('call', 'zero_1d_array', [('var', 'epochs')]),
              207),
             ('for_loop_range',
              'i',
              ('num', 0),
              ('var', 'epochs'),
              [('for_assign',
                'nice_object',
                ('call',
                 'train',
                 [('var', 'nice_object'),
                  ('var', 'train_X_flat'),
                  ('var', 'dummy_y'),
                  ('num', 1),
                  ('var', 'lr')])),
               ('for_assign', 'epoch_loss', ('num', 0)),
               ('for_loop_range',
                'j',
                ('num', 0),
                ('var', 'len_train_X'),
                [('for_assign',
                  'log_px',
                  ('call',
                   'nice_object',
                   [('index', 'train_X_flat', ('var', 'j'))])),
                 ('for_pluseq',
                  'epoch_loss',
                  ('call', 'neg_loglik', [('var', 'log_px')]))],
                212),
               ('for_assign',
                'epoch_loss',
                ('div', ('var', 'epoch_loss'), ('var', 'len_train_X'))),
               ('for_index_assign_nd',
                'losses',
                [('index_item', ('imaginary',))],
                ('var', 'epoch_loss')),
               ('for_call', 'print', [('var', 'epoch_loss')])],
              209),
             ('decl', 'test_loss', 'ℝ', ('num', 0), 221),
             ('for_loop_range',
              'i',
              ('num', 0),
              ('var', 'len_test_X'),
              [('for_assign',
                'log_px',
                ('call',
                 'nice_object',
                 [('index', 'test_X_flat', ('imaginary',))])),
               ('for_pluseq',
                'test_loss',
                ('call', 'neg_loglik', [('var', 'log_px')]))],
              222),
             ('assign',
              'test_loss',
              ('div', ('var', 'test_loss'), ('var', 'len_test_X')),
              225),
             ('expr', ('call', 'print', [('var', 'test_loss')]), 0)]}
