EXPECTED = {'functions': {'len1d': {'params': [('x', ('tensor', [('n', 'invariant')]))],
                         'return_type': 'ℝ',
                         'body': ('var', 'total'),
                         'has_loop': False,
                         'statements': [('body_decl', 'total', 'ℝ', ('num', 0)),
                                        ('body_decl', 'temp', 'ℝ', ('num', 0)),
                                        ('body_for',
                                         'i',
                                         [('loop_assign',
                                           'temp',
                                           ('index', 'x', ('imaginary',))),
                                          ('loop_pluseq', 'total', ('num', 1))],
                                         ['x'])]},
               'relu': {'params': [('x', ('tensor', [('n', 'invariant')]))],
                        'return_type': ('tensor', [('n', 'invariant')]),
                        'body': ('mul',
                                 ('add',
                                  ('var', 'x'),
                                  ('call', 'abs', [('var', 'x')])),
                                 ('num', 0.5)),
                        'has_loop': False,
                        'statements': []},
               'linear': {'params': [('x', ('tensor', [('li', 'invariant')])),
                                     ('W',
                                      ('tensor',
                                       [('lo', 'invariant'),
                                        ('li', 'invariant')])),
                                     ('b', ('tensor', [('lo', 'invariant')]))],
                          'return_type': ('tensor', [('lo', 'invariant')]),
                          'body': ('add',
                                   ('indexN',
                                    'res',
                                    [('slice_item', None, None),
                                     ('index_item', ('num', 0))]),
                                   ('var', 'b')),
                          'has_loop': False,
                          'statements': [('body_decl',
                                          'in_dim',
                                          'ℝ',
                                          ('call', 'len1d', [('var', 'x')])),
                                         ('body_decl',
                                          'col',
                                          ('tensor',
                                           [('li', 'invariant'),
                                            (1, 'invariant')]),
                                          ('for_expr',
                                           'i',
                                           ('var', 'in_dim'),
                                           ('for_expr',
                                            'j',
                                            ('num', 1),
                                            ('mul',
                                             ('var', 'j'),
                                             ('num', 0))))),
                                         ('body_index_assign_nd',
                                          'col',
                                          [('slice_item', None, None),
                                           ('index_item', ('num', 0))],
                                          ('var', 'x')),
                                         ('body_decl',
                                          'res',
                                          ('tensor',
                                           [('lo', 'invariant'),
                                            (1, 'invariant')]),
                                          ('matmul',
                                           ('var', 'W'),
                                           ('var', 'col')))]},
               'flatten': {'params': [('img',
                                       ('tensor',
                                        [('H', 'invariant'),
                                         ('W', 'invariant')])),
                                      ('rows', 'ℝ'),
                                      ('cols', 'ℝ')],
                           'return_type': ('tensor', [('d', 'invariant')]),
                           'body': ('var', 'out'),
                           'has_loop': False,
                           'statements': [('body_decl',
                                           'd',
                                           'ℝ',
                                           ('mul',
                                            ('var', 'rows'),
                                            ('var', 'cols'))),
                                          ('body_decl',
                                           'out',
                                           ('tensor', [('d', 'invariant')]),
                                           ('for_expr',
                                            'i',
                                            ('var', 'd'),
                                            ('mul',
                                             ('imaginary',),
                                             ('num', 0)))),
                                          ('body_for_range',
                                           'i',
                                           ('num', 0),
                                           ('var', 'rows'),
                                           [('loop_index_assign_nd',
                                             'out',
                                             [('slice_item',
                                               ('mul',
                                                ('imaginary',),
                                                ('var', 'cols')),
                                               ('mul',
                                                ('add',
                                                 ('imaginary',),
                                                 ('num', 1)),
                                                ('var', 'cols')))],
                                             ('indexN',
                                              'img',
                                              [('index_item', ('imaginary',)),
                                               ('slice_item',
                                                None,
                                                None)]))])]},
               'unflatten': {'params': [('x', ('tensor', [('d', 'invariant')])),
                                        ('rows', 'ℝ'),
                                        ('cols', 'ℝ')],
                             'return_type': ('tensor',
                                             [('rows', 'invariant'),
                                              ('cols', 'invariant')]),
                             'body': ('var', 'img'),
                             'has_loop': False,
                             'statements': [('body_decl',
                                             'img',
                                             ('tensor',
                                              [('rows', 'invariant'),
                                               ('cols', 'invariant')]),
                                             ('for_expr',
                                              'i',
                                              ('var', 'rows'),
                                              ('for_expr',
                                               'j',
                                               ('var', 'cols'),
                                               ('mul',
                                                ('var', 'j'),
                                                ('num', 0))))),
                                            ('body_for_range',
                                             'i',
                                             ('num', 0),
                                             ('var', 'rows'),
                                             [('loop_index_assign_nd',
                                               'img',
                                               [('index_item', ('imaginary',)),
                                                ('slice_item', None, None)],
                                               ('indexN',
                                                'x',
                                                [('slice_item',
                                                  ('mul',
                                                   ('imaginary',),
                                                   ('var', 'cols')),
                                                  ('mul',
                                                   ('add',
                                                    ('imaginary',),
                                                    ('num', 1)),
                                                   ('var', 'cols')))]))])]},
               'dequantize': {'params': [('x',
                                          ('tensor', [('d', 'invariant')])),
                                         ('d', 'ℕ')],
                              'return_type': ('tensor', [('d', 'invariant')]),
                              'body': ('div',
                                       ('add', ('var', 'x'), ('var', 'u')),
                                       ('num', 256.0)),
                              'has_loop': False,
                              'statements': [('typed_sample',
                                              'u',
                                              ('tensor', [('d', 'invariant')]),
                                              ('call',
                                               'Uniform',
                                               [('num', 0.0),
                                                ('num', 1.0),
                                                ('var', 'd')]))]},
               'log_pz': {'params': [('x', ('tensor', [('d', 'invariant')])),
                                     ('d', 'ℕ')],
                          'return_type': 'ℝ',
                          'body': ('sub',
                                   ('call',
                                    'sum',
                                    [('mul',
                                      ('mul',
                                       ('neg', ('num', 0.5)),
                                       ('var', 'x')),
                                      ('var', 'x'))]),
                                   ('mul',
                                    ('mul', ('var', 'd'), ('num', 0.5)),
                                    ('call',
                                     'log',
                                     [('mul',
                                       ('num', 2.0),
                                       ('num', 3.14159265))]))),
                          'has_loop': False,
                          'statements': []},
               'neg_loglik': {'params': [('log_px', 'ℝ')],
                              'return_type': 'ℝ',
                              'body': ('neg', ('var', 'log_px')),
                              'has_loop': False,
                              'statements': []},
               'nll': {'params': [('model', ('struct_type', 'NICE')),
                                  ('X',
                                   ('tensor',
                                    [('k', 'invariant'), ('d', 'invariant')])),
                                  ('count', 'ℝ')],
                       'return_type': 'ℝ',
                       'body': ('div', ('var', 'total'), ('var', 'count')),
                       'has_loop': False,
                       'statements': [('body_decl', 'total', 'ℝ', ('num', 0)),
                                      ('body_for_range',
                                       'i',
                                       ('num', 0),
                                       ('var', 'count'),
                                       [('loop_pluseq',
                                         'total',
                                         ('call',
                                          'neg_loglik',
                                          [('call',
                                            'model',
                                            [('index',
                                              'X',
                                              ('imaginary',))])]))])]}},
 'classes': {'NICE': {'class_params': [('W1a',
                                        ('tensor',
                                         [('h', 'invariant'),
                                          ('n', 'invariant')])),
                                       ('b1a',
                                        ('tensor', [('h', 'invariant')])),
                                       ('W2a',
                                        ('tensor',
                                         [('n', 'invariant'),
                                          ('h', 'invariant')])),
                                       ('b2a',
                                        ('tensor', [('n', 'invariant')])),
                                       ('W1b',
                                        ('tensor',
                                         [('h', 'invariant'),
                                          ('n', 'invariant')])),
                                       ('b1b',
                                        ('tensor', [('h', 'invariant')])),
                                       ('W2b',
                                        ('tensor',
                                         [('n', 'invariant'),
                                          ('h', 'invariant')])),
                                       ('b2b',
                                        ('tensor', [('n', 'invariant')])),
                                       ('a', ('tensor', [('d', 'invariant')])),
                                       ('n', 'ℕ'),
                                       ('d', 'ℕ')],
                      'fields': [],
                      'methods': [{'name': 'coupling',
                                   'params': [('x',
                                               ('tensor',
                                                [('d', 'invariant')])),
                                              ('W1',
                                               ('tensor',
                                                [('h', 'invariant'),
                                                 ('n', 'invariant')])),
                                              ('b1',
                                               ('tensor',
                                                [('h', 'invariant')])),
                                              ('W2',
                                               ('tensor',
                                                [('n', 'invariant'),
                                                 ('h', 'invariant')])),
                                              ('b2',
                                               ('tensor',
                                                [('n', 'invariant')]))],
                                   'return_type': ('tensor',
                                                   [('d', 'invariant')]),
                                   'statements': [('body_decl',
                                                   'x1',
                                                   ('tensor',
                                                    [('n', 'invariant')]),
                                                   ('indexN',
                                                    'x',
                                                    [('slice_item',
                                                      None,
                                                      ('field_access',
                                                       ('var', 'this'),
                                                       'n'))])),
                                                  ('body_decl',
                                                   'x2',
                                                   ('tensor',
                                                    [('n', 'invariant')]),
                                                   ('indexN',
                                                    'x',
                                                    [('slice_item',
                                                      ('field_access',
                                                       ('var', 'this'),
                                                       'n'),
                                                      None)])),
                                                  ('body_decl',
                                                   'm',
                                                   ('tensor',
                                                    [('n', 'invariant')]),
                                                   ('call',
                                                    'linear',
                                                    [('call',
                                                      'relu',
                                                      [('call',
                                                        'linear',
                                                        [('var', 'x1'),
                                                         ('var', 'W1'),
                                                         ('var', 'b1')])]),
                                                     ('var', 'W2'),
                                                     ('var', 'b2')]))],
                                   'body': ('call',
                                            'concat',
                                            [('var', 'x1'),
                                             ('add',
                                              ('var', 'x2'),
                                              ('var', 'm'))])},
                                  {'name': 'coupling_inv',
                                   'params': [('y',
                                               ('tensor',
                                                [('d', 'invariant')])),
                                              ('W1',
                                               ('tensor',
                                                [('h', 'invariant'),
                                                 ('n', 'invariant')])),
                                              ('b1',
                                               ('tensor',
                                                [('h', 'invariant')])),
                                              ('W2',
                                               ('tensor',
                                                [('n', 'invariant'),
                                                 ('h', 'invariant')])),
                                              ('b2',
                                               ('tensor',
                                                [('n', 'invariant')]))],
                                   'return_type': ('tensor',
                                                   [('d', 'invariant')]),
                                   'statements': [('body_decl',
                                                   'y1',
                                                   ('tensor',
                                                    [('n', 'invariant')]),
                                                   ('indexN',
                                                    'y',
                                                    [('slice_item',
                                                      None,
                                                      ('field_access',
                                                       ('var', 'this'),
                                                       'n'))])),
                                                  ('body_decl',
                                                   'y2',
                                                   ('tensor',
                                                    [('n', 'invariant')]),
                                                   ('indexN',
                                                    'y',
                                                    [('slice_item',
                                                      ('field_access',
                                                       ('var', 'this'),
                                                       'n'),
                                                      None)])),
                                                  ('body_decl',
                                                   'm',
                                                   ('tensor',
                                                    [('n', 'invariant')]),
                                                   ('call',
                                                    'linear',
                                                    [('call',
                                                      'relu',
                                                      [('call',
                                                        'linear',
                                                        [('var', 'y1'),
                                                         ('var', 'W1'),
                                                         ('var', 'b1')])]),
                                                     ('var', 'W2'),
                                                     ('var', 'b2')]))],
                                   'body': ('call',
                                            'concat',
                                            [('var', 'y1'),
                                             ('sub',
                                              ('var', 'y2'),
                                              ('var', 'm'))])},
                                  {'name': 'swap',
                                   'params': [('x',
                                               ('tensor',
                                                [('d', 'invariant')]))],
                                   'return_type': ('tensor',
                                                   [('d', 'invariant')]),
                                   'statements': [],
                                   'body': ('call',
                                            'concat',
                                            [('indexN',
                                              'x',
                                              [('slice_item',
                                                ('field_access',
                                                 ('var', 'this'),
                                                 'n'),
                                                None)]),
                                             ('indexN',
                                              'x',
                                              [('slice_item',
                                                None,
                                                ('field_access',
                                                 ('var', 'this'),
                                                 'n'))])])},
                                  {'name': 'rescale',
                                   'params': [('h',
                                               ('tensor',
                                                [('d', 'invariant')]))],
                                   'return_type': ('tensor',
                                                   [('d', 'invariant')]),
                                   'statements': [],
                                   'body': ('mul',
                                            ('var', 'h'),
                                            ('call',
                                             'exp',
                                             [('field_access',
                                               ('var', 'this'),
                                               'a')]))},
                                  {'name': 'rescale_inv',
                                   'params': [('z',
                                               ('tensor',
                                                [('d', 'invariant')]))],
                                   'return_type': ('tensor',
                                                   [('d', 'invariant')]),
                                   'statements': [],
                                   'body': ('mul',
                                            ('var', 'z'),
                                            ('call',
                                             'exp',
                                             [('neg',
                                               ('field_access',
                                                ('var', 'this'),
                                                'a'))]))},
                                  {'name': 'log_det',
                                   'params': [],
                                   'return_type': 'ℝ',
                                   'statements': [],
                                   'body': ('call',
                                            'sum',
                                            [('field_access',
                                              ('var', 'this'),
                                              'a')])},
                                  {'name': 'forward_z',
                                   'params': [('x',
                                               ('tensor',
                                                [('d', 'invariant')]))],
                                   'return_type': ('tensor',
                                                   [('d', 'invariant')]),
                                   'statements': [('body_decl',
                                                   'h',
                                                   ('tensor',
                                                    [('d', 'invariant')]),
                                                   ('method_call',
                                                    ('var', 'this'),
                                                    'coupling',
                                                    [('var', 'x'),
                                                     ('field_access',
                                                      ('var', 'this'),
                                                      'W1a'),
                                                     ('field_access',
                                                      ('var', 'this'),
                                                      'b1a'),
                                                     ('field_access',
                                                      ('var', 'this'),
                                                      'W2a'),
                                                     ('field_access',
                                                      ('var', 'this'),
                                                      'b2a')])),
                                                  ('body_assign',
                                                   'h',
                                                   ('method_call',
                                                    ('var', 'this'),
                                                    'swap',
                                                    [('var', 'h')])),
                                                  ('body_assign',
                                                   'h',
                                                   ('method_call',
                                                    ('var', 'this'),
                                                    'coupling',
                                                    [('var', 'h'),
                                                     ('field_access',
                                                      ('var', 'this'),
                                                      'W1b'),
                                                     ('field_access',
                                                      ('var', 'this'),
                                                      'b1b'),
                                                     ('field_access',
                                                      ('var', 'this'),
                                                      'W2b'),
                                                     ('field_access',
                                                      ('var', 'this'),
                                                      'b2b')])),
                                                  ('body_assign',
                                                   'h',
                                                   ('method_call',
                                                    ('var', 'this'),
                                                    'swap',
                                                    [('var', 'h')]))],
                                   'body': ('method_call',
                                            ('var', 'this'),
                                            'rescale',
                                            [('var', 'h')])},
                                  {'name': 'λ',
                                   'params': [('x',
                                               ('tensor',
                                                [('d', 'invariant')]))],
                                   'return_type': 'ℝ',
                                   'statements': [('body_decl',
                                                   'z',
                                                   ('tensor',
                                                    [('d', 'invariant')]),
                                                   ('method_call',
                                                    ('var', 'this'),
                                                    'forward_z',
                                                    [('var', 'x')]))],
                                   'body': ('add',
                                            ('call',
                                             'log_pz',
                                             [('var', 'z'),
                                              ('field_access',
                                               ('var', 'this'),
                                               'd')]),
                                            ('method_call',
                                             ('var', 'this'),
                                             'log_det',
                                             []))},
                                  {'name': 'inverse',
                                   'params': [('z',
                                               ('tensor',
                                                [('d', 'invariant')]))],
                                   'return_type': ('tensor',
                                                   [('d', 'invariant')]),
                                   'statements': [('body_decl',
                                                   'h',
                                                   ('tensor',
                                                    [('d', 'invariant')]),
                                                   ('method_call',
                                                    ('var', 'this'),
                                                    'rescale_inv',
                                                    [('var', 'z')])),
                                                  ('body_assign',
                                                   'h',
                                                   ('method_call',
                                                    ('var', 'this'),
                                                    'swap',
                                                    [('var', 'h')])),
                                                  ('body_assign',
                                                   'h',
                                                   ('method_call',
                                                    ('var', 'this'),
                                                    'coupling_inv',
                                                    [('var', 'h'),
                                                     ('field_access',
                                                      ('var', 'this'),
                                                      'W1b'),
                                                     ('field_access',
                                                      ('var', 'this'),
                                                      'b1b'),
                                                     ('field_access',
                                                      ('var', 'this'),
                                                      'W2b'),
                                                     ('field_access',
                                                      ('var', 'this'),
                                                      'b2b')])),
                                                  ('body_assign',
                                                   'h',
                                                   ('method_call',
                                                    ('var', 'this'),
                                                    'swap',
                                                    [('var', 'h')]))],
                                   'body': ('method_call',
                                            ('var', 'this'),
                                            'coupling_inv',
                                            [('var', 'h'),
                                             ('field_access',
                                              ('var', 'this'),
                                              'W1a'),
                                             ('field_access',
                                              ('var', 'this'),
                                              'b1a'),
                                             ('field_access',
                                              ('var', 'this'),
                                              'W2a'),
                                             ('field_access',
                                              ('var', 'this'),
                                              'b2a')])},
                                  {'name': 'sample',
                                   'params': [],
                                   'return_type': ('tensor',
                                                   [('d', 'invariant')]),
                                   'statements': [('typed_sample',
                                                   'z',
                                                   ('tensor',
                                                    [('d', 'invariant')]),
                                                   ('call',
                                                    'Normal',
                                                    [('num', 0.0),
                                                     ('num', 1.0),
                                                     ('field_access',
                                                      ('var', 'this'),
                                                      'd')]))],
                                   'body': ('method_call',
                                            ('var', 'this'),
                                            'inverse',
                                            [('var', 'z')])}]}},
 'program': [('seed', ('num', 0)),
             ('func_def', 'len1d'),
             ('func_def', 'relu'),
             ('func_def', 'linear'),
             ('func_def', 'flatten'),
             ('func_def', 'unflatten'),
             ('func_def', 'dequantize'),
             ('func_def', 'log_pz'),
             ('class_def', 'NICE'),
             ('func_def', 'neg_loglik'),
             ('func_def', 'nll'),
             ('assign',
              'dataset',
              ('call', 'create_dataset', [('num', 80), ('num', 100)]),
              111),
             ('assign', 'train_dataset', ('index', 'dataset', ('num', 0)), 112),
             ('assign', 'test_dataset', ('index', 'dataset', ('num', 1)), 113),
             ('assign', 'train_X', ('index', 'train_dataset', ('num', 0)), 115),
             ('assign', 'test_X', ('index', 'test_dataset', ('num', 0)), 116),
             ('stmt_tuple_unpack',
              [('len_train', 'ℝ'), ('len_test', 'ℝ')],
              ('expr_list',
               [('call', 'len1d', [('var', 'train_X')]),
                ('call', 'len1d', [('var', 'test_X')])])),
             ('decl', 'd', 'ℕ', ('num', 784), 122),
             ('decl', 'h', 'ℕ', ('num', 128), 123),
             ('decl', 'n', 'ℕ', ('num', 392), 124),
             ('stmt_tuple_unpack',
              [('s1', 'ℝ'), ('s2', 'ℝ')],
              ('expr_list',
               [('call', 'sqrt', [('div', ('num', 2.0), ('var', 'n'))]),
                ('mul',
                 ('call', 'sqrt', [('div', ('num', 2.0), ('var', 'h'))]),
                 ('num', 0.01))])),
             ('decl',
              'W1a',
              ('tensor', [('h', 'invariant'), ('n', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'h'),
               ('typed_sample_expr',
                'ε',
                ('tensor', [('n', 'invariant')]),
                ('call',
                 'Normal',
                 [('num', 0.0), ('var', 's1'), ('var', 'n')]))),
              129),
             ('decl',
              'b1a',
              ('tensor', [('h', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'h'),
               ('mul', ('imaginary',), ('num', 0))),
              130),
             ('decl',
              'W2a',
              ('tensor', [('n', 'invariant'), ('h', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'n'),
               ('typed_sample_expr',
                'ε',
                ('tensor', [('h', 'invariant')]),
                ('call',
                 'Normal',
                 [('num', 0.0), ('var', 's2'), ('var', 'h')]))),
              131),
             ('decl',
              'b2a',
              ('tensor', [('n', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'n'),
               ('mul', ('imaginary',), ('num', 0))),
              132),
             ('decl',
              'W1b',
              ('tensor', [('h', 'invariant'), ('n', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'h'),
               ('typed_sample_expr',
                'ε',
                ('tensor', [('n', 'invariant')]),
                ('call',
                 'Normal',
                 [('num', 0.0), ('var', 's1'), ('var', 'n')]))),
              134),
             ('decl',
              'b1b',
              ('tensor', [('h', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'h'),
               ('mul', ('imaginary',), ('num', 0))),
              135),
             ('decl',
              'W2b',
              ('tensor', [('n', 'invariant'), ('h', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'n'),
               ('typed_sample_expr',
                'ε',
                ('tensor', [('h', 'invariant')]),
                ('call',
                 'Normal',
                 [('num', 0.0), ('var', 's2'), ('var', 'h')]))),
              136),
             ('decl',
              'b2b',
              ('tensor', [('n', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'n'),
               ('mul', ('imaginary',), ('num', 0))),
              137),
             ('decl',
              'a0',
              ('tensor', [('d', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'd'),
               ('mul', ('imaginary',), ('num', 0))),
              139),
             ('decl',
              'model',
              ('struct_type', 'NICE'),
              ('call',
               'NICE',
               [('var', 'W1a'),
                ('var', 'b1a'),
                ('var', 'W2a'),
                ('var', 'b2a'),
                ('var', 'W1b'),
                ('var', 'b1b'),
                ('var', 'W2b'),
                ('var', 'b2b'),
                ('var', 'a0'),
                ('var', 'n'),
                ('var', 'd')]),
              141),
             ('decl',
              'x0',
              ('tensor', [('d', 'invariant')]),
              ('call',
               'dequantize',
               [('call',
                 'flatten',
                 [('index', 'train_X', ('num', 0)), ('num', 28), ('num', 28)]),
                ('var', 'd')]),
              145),
             ('expr',
              ('call', 'print', [('call', 'model', [('var', 'x0')])]),
              0),
             ('expr', ('call', 'print', [('var', 'DEVICE')]), 0),
             ('decl',
              'train_flat',
              ('tensor', [('len_train', 'invariant'), ('d', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'len_train'),
               ('for_expr',
                'j',
                ('var', 'd'),
                ('mul', ('var', 'j'), ('num', 0)))),
              151),
             ('for_loop_range',
              'i',
              ('num', 0),
              ('var', 'len_train'),
              [('for_index_assign_nd',
                'train_flat',
                [('index_item', ('imaginary',)), ('slice_item', None, None)],
                ('call',
                 'dequantize',
                 [('call',
                   'flatten',
                   [('index', 'train_X', ('imaginary',)),
                    ('num', 28),
                    ('num', 28)]),
                  ('var', 'd')]))],
              152),
             ('decl',
              'test_flat',
              ('tensor', [('len_test', 'invariant'), ('d', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'len_test'),
               ('for_expr',
                'j',
                ('var', 'd'),
                ('mul', ('var', 'j'), ('num', 0)))),
              155),
             ('for_loop_range',
              'i',
              ('num', 0),
              ('var', 'len_test'),
              [('for_index_assign_nd',
                'test_flat',
                [('index_item', ('imaginary',)), ('slice_item', None, None)],
                ('call',
                 'dequantize',
                 [('call',
                   'flatten',
                   [('index', 'test_X', ('imaginary',)),
                    ('num', 28),
                    ('num', 28)]),
                  ('var', 'd')]))],
              156),
             ('decl', 'epochs', 'ℕ', ('num', 20), 161),
             ('decl', 'lr', 'ℝ', ('num', 0.001), 162),
             ('decl',
              'losses',
              ('tensor', [('epochs', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'epochs'),
               ('mul', ('imaginary',), ('num', 0))),
              164),
             ('for_loop_range',
              'i',
              ('num', 0),
              ('var', 'epochs'),
              [('for_loop_range',
                'j',
                ('num', 0),
                ('var', 'len_train'),
                [('for_assign',
                  'L',
                  ('call',
                   'neg_loglik',
                   [('call',
                     'model',
                     [('index', 'train_flat', ('var', 'j'))])])),
                 ('for_assign',
                  'nW1a',
                  ('sub',
                   ('field_access', ('var', 'model'), 'W1a'),
                   ('mul',
                    ('var', 'lr'),
                    ('call',
                     'grad',
                     [('var', 'L'),
                      ('field_access', ('var', 'model'), 'W1a')])))),
                 ('for_assign',
                  'nb1a',
                  ('sub',
                   ('field_access', ('var', 'model'), 'b1a'),
                   ('mul',
                    ('var', 'lr'),
                    ('call',
                     'grad',
                     [('var', 'L'),
                      ('field_access', ('var', 'model'), 'b1a')])))),
                 ('for_assign',
                  'nW2a',
                  ('sub',
                   ('field_access', ('var', 'model'), 'W2a'),
                   ('mul',
                    ('var', 'lr'),
                    ('call',
                     'grad',
                     [('var', 'L'),
                      ('field_access', ('var', 'model'), 'W2a')])))),
                 ('for_assign',
                  'nb2a',
                  ('sub',
                   ('field_access', ('var', 'model'), 'b2a'),
                   ('mul',
                    ('var', 'lr'),
                    ('call',
                     'grad',
                     [('var', 'L'),
                      ('field_access', ('var', 'model'), 'b2a')])))),
                 ('for_assign',
                  'nW1b',
                  ('sub',
                   ('field_access', ('var', 'model'), 'W1b'),
                   ('mul',
                    ('var', 'lr'),
                    ('call',
                     'grad',
                     [('var', 'L'),
                      ('field_access', ('var', 'model'), 'W1b')])))),
                 ('for_assign',
                  'nb1b',
                  ('sub',
                   ('field_access', ('var', 'model'), 'b1b'),
                   ('mul',
                    ('var', 'lr'),
                    ('call',
                     'grad',
                     [('var', 'L'),
                      ('field_access', ('var', 'model'), 'b1b')])))),
                 ('for_assign',
                  'nW2b',
                  ('sub',
                   ('field_access', ('var', 'model'), 'W2b'),
                   ('mul',
                    ('var', 'lr'),
                    ('call',
                     'grad',
                     [('var', 'L'),
                      ('field_access', ('var', 'model'), 'W2b')])))),
                 ('for_assign',
                  'nb2b',
                  ('sub',
                   ('field_access', ('var', 'model'), 'b2b'),
                   ('mul',
                    ('var', 'lr'),
                    ('call',
                     'grad',
                     [('var', 'L'),
                      ('field_access', ('var', 'model'), 'b2b')])))),
                 ('for_assign',
                  'na',
                  ('sub',
                   ('field_access', ('var', 'model'), 'a'),
                   ('mul',
                    ('var', 'lr'),
                    ('call',
                     'grad',
                     [('var', 'L'),
                      ('field_access', ('var', 'model'), 'a')])))),
                 ('for_assign',
                  'model',
                  ('call',
                   'NICE',
                   [('var', 'nW1a'),
                    ('var', 'nb1a'),
                    ('var', 'nW2a'),
                    ('var', 'nb2a'),
                    ('var', 'nW1b'),
                    ('var', 'nb1b'),
                    ('var', 'nW2b'),
                    ('var', 'nb2b'),
                    ('var', 'na'),
                    ('field_access', ('var', 'model'), 'n'),
                    ('field_access', ('var', 'model'), 'd')]))],
                167),
               ('for_assign',
                'epoch_loss',
                ('call',
                 'nll',
                 [('var', 'model'),
                  ('var', 'train_flat'),
                  ('var', 'len_train')])),
               ('for_index_assign_nd',
                'losses',
                [('index_item', ('imaginary',))],
                ('var', 'epoch_loss')),
               ('for_call', 'print', [('var', 'epoch_loss')]),
               ('for_assign',
                'bits',
                ('add',
                 ('div',
                  ('var', 'epoch_loss'),
                  ('mul', ('var', 'd'), ('call', 'log', [('num', 2.0)]))),
                 ('num', 8.0))),
               ('for_call', 'print', [('var', 'bits')])],
              166),
             ('decl',
              'test_loss',
              'ℝ',
              ('call',
               'nll',
               [('var', 'model'), ('var', 'test_flat'), ('var', 'len_test')]),
              187),
             ('expr', ('call', 'print', [('var', 'test_loss')]), 0),
             ('decl',
              'bits_per_dim',
              'ℝ',
              ('add',
               ('div',
                ('var', 'test_loss'),
                ('mul', ('var', 'd'), ('call', 'log', [('num', 2.0)]))),
               ('num', 8.0)),
              189),
             ('expr', ('call', 'print', [('var', 'bits_per_dim')]), 0),
             ('decl',
              'gen_flat',
              ('tensor', [('d', 'invariant')]),
              ('method_call', ('var', 'model'), 'sample', []),
              194),
             ('decl',
              'gen_img',
              ('tensor', [(28, 'invariant'), (28, 'invariant')]),
              ('call',
               'unflatten',
               [('var', 'gen_flat'), ('num', 28), ('num', 28)]),
              195),
             ('expr', ('call', 'print', [('var', 'gen_img')]), 0)]}
