EXPECTED = {'functions': {'len1d': {'params': [('x', ('tensor', [('n', 'invariant')]))],
                         'return_type': 'ℝ',
                         'body': ('var', 'total'),
                         'has_loop': False,
                         'statements': [('body_decl', 'total', 'ℝ', ('num', 0)),
                                        ('body_decl', 'temp', 'ℝ', ('num', 0)),
                                        ('body_for',
                                         'i',
                                         [('loop_assign',
                                           'temp',
                                           ('index', 'x', ('imaginary',))),
                                          ('loop_pluseq', 'total', ('num', 1))],
                                         ['x'])]},
               'relu': {'params': [('x', ('tensor', [('n', 'invariant')]))],
                        'return_type': ('tensor', [('n', 'invariant')]),
                        'body': ('mul',
                                 ('add',
                                  ('var', 'x'),
                                  ('call', 'abs', [('var', 'x')])),
                                 ('num', 0.5)),
                        'has_loop': False,
                        'statements': []},
               'linear': {'params': [('x', ('tensor', [('li', 'invariant')])),
                                     ('W',
                                      ('tensor',
                                       [('lo', 'invariant'),
                                        ('li', 'invariant')])),
                                     ('b', ('tensor', [('lo', 'invariant')]))],
                          'return_type': ('tensor', [('lo', 'invariant')]),
                          'body': ('add',
                                   ('indexN',
                                    'res',
                                    [('slice_item', None, None),
                                     ('index_item', ('num', 0))]),
                                   ('var', 'b')),
                          'has_loop': False,
                          'statements': [('body_decl',
                                          'in_dim',
                                          'ℝ',
                                          ('call', 'len1d', [('var', 'x')])),
                                         ('body_decl',
                                          'col',
                                          ('tensor',
                                           [('li', 'invariant'),
                                            (1, 'invariant')]),
                                          ('for_expr',
                                           'i',
                                           ('var', 'in_dim'),
                                           ('for_expr',
                                            'j',
                                            ('num', 1),
                                            ('mul',
                                             ('var', 'j'),
                                             ('num', 0))))),
                                         ('body_index_assign_nd',
                                          'col',
                                          [('slice_item', None, None),
                                           ('index_item', ('num', 0))],
                                          ('var', 'x')),
                                         ('body_decl',
                                          'res',
                                          ('tensor',
                                           [('lo', 'invariant'),
                                            (1, 'invariant')]),
                                          ('matmul',
                                           ('var', 'W'),
                                           ('var', 'col')))]},
               'flatten': {'params': [('img',
                                       ('tensor',
                                        [('H', 'invariant'),
                                         ('W', 'invariant')])),
                                      ('rows', 'ℝ'),
                                      ('cols', 'ℝ')],
                           'return_type': ('tensor', [('d', 'invariant')]),
                           'body': ('var', 'out'),
                           'has_loop': False,
                           'statements': [('body_decl',
                                           'd',
                                           'ℝ',
                                           ('mul',
                                            ('var', 'rows'),
                                            ('var', 'cols'))),
                                          ('body_decl',
                                           'out',
                                           ('tensor', [('d', 'invariant')]),
                                           ('for_expr',
                                            'i',
                                            ('var', 'd'),
                                            ('mul',
                                             ('imaginary',),
                                             ('num', 0)))),
                                          ('body_for_range',
                                           'i',
                                           ('num', 0),
                                           ('var', 'rows'),
                                           [('loop_index_assign_nd',
                                             'out',
                                             [('slice_item',
                                               ('mul',
                                                ('imaginary',),
                                                ('var', 'cols')),
                                               ('mul',
                                                ('add',
                                                 ('imaginary',),
                                                 ('num', 1)),
                                                ('var', 'cols')))],
                                             ('indexN',
                                              'img',
                                              [('index_item', ('imaginary',)),
                                               ('slice_item',
                                                None,
                                                None)]))])]},
               'unflatten': {'params': [('x', ('tensor', [('d', 'invariant')])),
                                        ('rows', 'ℝ'),
                                        ('cols', 'ℝ')],
                             'return_type': ('tensor',
                                             [('rows', 'invariant'),
                                              ('cols', 'invariant')]),
                             'body': ('var', 'img'),
                             'has_loop': False,
                             'statements': [('body_decl',
                                             'img',
                                             ('tensor',
                                              [('rows', 'invariant'),
                                               ('cols', 'invariant')]),
                                             ('for_expr',
                                              'i',
                                              ('var', 'rows'),
                                              ('for_expr',
                                               'j',
                                               ('var', 'cols'),
                                               ('mul',
                                                ('var', 'j'),
                                                ('num', 0))))),
                                            ('body_for_range',
                                             'i',
                                             ('num', 0),
                                             ('var', 'rows'),
                                             [('loop_index_assign_nd',
                                               'img',
                                               [('index_item', ('imaginary',)),
                                                ('slice_item', None, None)],
                                               ('indexN',
                                                'x',
                                                [('slice_item',
                                                  ('mul',
                                                   ('imaginary',),
                                                   ('var', 'cols')),
                                                  ('mul',
                                                   ('add',
                                                    ('imaginary',),
                                                    ('num', 1)),
                                                   ('var', 'cols')))]))])]},
               'dequantize': {'params': [('x',
                                          ('tensor', [('d', 'invariant')])),
                                         ('d', 'ℕ')],
                              'return_type': ('tensor', [('d', 'invariant')]),
                              'body': ('div',
                                       ('add', ('var', 'x'), ('var', 'u')),
                                       ('num', 256.0)),
                              'has_loop': False,
                              'statements': [('typed_sample',
                                              'u',
                                              ('tensor', [('d', 'invariant')]),
                                              ('call',
                                               'Uniform',
                                               [('num', 0.0),
                                                ('num', 1.0),
                                                ('var', 'd')]))]},
               'log_pz': {'params': [('x', ('tensor', [('d', 'invariant')])),
                                     ('d', 'ℕ')],
                          'return_type': 'ℝ',
                          'body': ('sub',
                                   ('call',
                                    'sum',
                                    [('mul',
                                      ('mul',
                                       ('neg', ('num', 0.5)),
                                       ('var', 'x')),
                                      ('var', 'x'))]),
                                   ('mul',
                                    ('mul', ('var', 'd'), ('num', 0.5)),
                                    ('call',
                                     'log',
                                     [('mul',
                                       ('num', 2.0),
                                       ('num', 3.14159265))]))),
                          'has_loop': False,
                          'statements': []},
               'neg_loglik': {'params': [('log_px', 'ℝ')],
                              'return_type': 'ℝ',
                              'body': ('neg', ('var', 'log_px')),
                              'has_loop': False,
                              'statements': []},
               'nll': {'params': [('model', ('struct_type', 'RealNVP')),
                                  ('X',
                                   ('tensor',
                                    [('k', 'invariant'), ('d', 'invariant')])),
                                  ('count', 'ℝ')],
                       'return_type': 'ℝ',
                       'body': ('div', ('var', 'total'), ('var', 'count')),
                       'has_loop': False,
                       'statements': [('body_decl', 'total', 'ℝ', ('num', 0)),
                                      ('body_for_range',
                                       'i',
                                       ('num', 0),
                                       ('var', 'count'),
                                       [('loop_pluseq',
                                         'total',
                                         ('call',
                                          'neg_loglik',
                                          [('call',
                                            'model',
                                            [('index',
                                              'X',
                                              ('imaginary',))])]))])]}},
 'classes': {'RealNVP': {'class_params': [('W1a_s',
                                           ('tensor',
                                            [('h', 'invariant'),
                                             ('n', 'invariant')])),
                                          ('b1a_s',
                                           ('tensor', [('h', 'invariant')])),
                                          ('W2a_s',
                                           ('tensor',
                                            [('n', 'invariant'),
                                             ('h', 'invariant')])),
                                          ('b2a_s',
                                           ('tensor', [('n', 'invariant')])),
                                          ('W1a_m',
                                           ('tensor',
                                            [('h', 'invariant'),
                                             ('n', 'invariant')])),
                                          ('b1a_m',
                                           ('tensor', [('h', 'invariant')])),
                                          ('W2a_m',
                                           ('tensor',
                                            [('n', 'invariant'),
                                             ('h', 'invariant')])),
                                          ('b2a_m',
                                           ('tensor', [('n', 'invariant')])),
                                          ('W1b_s',
                                           ('tensor',
                                            [('h', 'invariant'),
                                             ('n', 'invariant')])),
                                          ('b1b_s',
                                           ('tensor', [('h', 'invariant')])),
                                          ('W2b_s',
                                           ('tensor',
                                            [('n', 'invariant'),
                                             ('h', 'invariant')])),
                                          ('b2b_s',
                                           ('tensor', [('n', 'invariant')])),
                                          ('W1b_m',
                                           ('tensor',
                                            [('h', 'invariant'),
                                             ('n', 'invariant')])),
                                          ('b1b_m',
                                           ('tensor', [('h', 'invariant')])),
                                          ('W2b_m',
                                           ('tensor',
                                            [('n', 'invariant'),
                                             ('h', 'invariant')])),
                                          ('b2b_m',
                                           ('tensor', [('n', 'invariant')])),
                                          ('n', 'ℕ'),
                                          ('d', 'ℕ')],
                         'fields': [],
                         'methods': [{'name': 'coupling',
                                      'params': [('x',
                                                  ('tensor',
                                                   [('d', 'invariant')])),
                                                 ('W1s',
                                                  ('tensor',
                                                   [('h', 'invariant'),
                                                    ('n', 'invariant')])),
                                                 ('b1s',
                                                  ('tensor',
                                                   [('h', 'invariant')])),
                                                 ('W2s',
                                                  ('tensor',
                                                   [('n', 'invariant'),
                                                    ('h', 'invariant')])),
                                                 ('b2s',
                                                  ('tensor',
                                                   [('n', 'invariant')])),
                                                 ('W1m',
                                                  ('tensor',
                                                   [('h', 'invariant'),
                                                    ('n', 'invariant')])),
                                                 ('b1m',
                                                  ('tensor',
                                                   [('h', 'invariant')])),
                                                 ('W2m',
                                                  ('tensor',
                                                   [('n', 'invariant'),
                                                    ('h', 'invariant')])),
                                                 ('b2m',
                                                  ('tensor',
                                                   [('n', 'invariant')]))],
                                      'return_type': ('tensor',
                                                      [('d', 'invariant')]),
                                      'statements': [('body_decl',
                                                      'x1',
                                                      ('tensor',
                                                       [('n', 'invariant')]),
                                                      ('indexN',
                                                       'x',
                                                       [('slice_item',
                                                         None,
                                                         ('field_access',
                                                          ('var', 'this'),
                                                          'n'))])),
                                                     ('body_decl',
                                                      'x2',
                                                      ('tensor',
                                                       [('n', 'invariant')]),
                                                      ('indexN',
                                                       'x',
                                                       [('slice_item',
                                                         ('field_access',
                                                          ('var', 'this'),
                                                          'n'),
                                                         None)])),
                                                     ('body_decl',
                                                      's',
                                                      ('tensor',
                                                       [('n', 'invariant')]),
                                                      ('call',
                                                       'linear',
                                                       [('call',
                                                         'relu',
                                                         [('call',
                                                           'linear',
                                                           [('var', 'x1'),
                                                            ('var', 'W1s'),
                                                            ('var', 'b1s')])]),
                                                        ('var', 'W2s'),
                                                        ('var', 'b2s')])),
                                                     ('body_decl',
                                                      'm',
                                                      ('tensor',
                                                       [('n', 'invariant')]),
                                                      ('call',
                                                       'linear',
                                                       [('call',
                                                         'relu',
                                                         [('call',
                                                           'linear',
                                                           [('var', 'x1'),
                                                            ('var', 'W1m'),
                                                            ('var', 'b1m')])]),
                                                        ('var', 'W2m'),
                                                        ('var', 'b2m')]))],
                                      'body': ('call',
                                               'concat',
                                               [('var', 'x1'),
                                                ('add',
                                                 ('mul',
                                                  ('call',
                                                   'exp',
                                                   [('var', 's')]),
                                                  ('var', 'x2')),
                                                 ('var', 'm'))])},
                                     {'name': 'coupling_inv',
                                      'params': [('y',
                                                  ('tensor',
                                                   [('d', 'invariant')])),
                                                 ('W1s',
                                                  ('tensor',
                                                   [('h', 'invariant'),
                                                    ('n', 'invariant')])),
                                                 ('b1s',
                                                  ('tensor',
                                                   [('h', 'invariant')])),
                                                 ('W2s',
                                                  ('tensor',
                                                   [('n', 'invariant'),
                                                    ('h', 'invariant')])),
                                                 ('b2s',
                                                  ('tensor',
                                                   [('n', 'invariant')])),
                                                 ('W1m',
                                                  ('tensor',
                                                   [('h', 'invariant'),
                                                    ('n', 'invariant')])),
                                                 ('b1m',
                                                  ('tensor',
                                                   [('h', 'invariant')])),
                                                 ('W2m',
                                                  ('tensor',
                                                   [('n', 'invariant'),
                                                    ('h', 'invariant')])),
                                                 ('b2m',
                                                  ('tensor',
                                                   [('n', 'invariant')]))],
                                      'return_type': ('tensor',
                                                      [('d', 'invariant')]),
                                      'statements': [('body_decl',
                                                      'y1',
                                                      ('tensor',
                                                       [('n', 'invariant')]),
                                                      ('indexN',
                                                       'y',
                                                       [('slice_item',
                                                         None,
                                                         ('field_access',
                                                          ('var', 'this'),
                                                          'n'))])),
                                                     ('body_decl',
                                                      'y2',
                                                      ('tensor',
                                                       [('n', 'invariant')]),
                                                      ('indexN',
                                                       'y',
                                                       [('slice_item',
                                                         ('field_access',
                                                          ('var', 'this'),
                                                          'n'),
                                                         None)])),
                                                     ('body_decl',
                                                      's',
                                                      ('tensor',
                                                       [('n', 'invariant')]),
                                                      ('call',
                                                       'linear',
                                                       [('call',
                                                         'relu',
                                                         [('call',
                                                           'linear',
                                                           [('var', 'y1'),
                                                            ('var', 'W1s'),
                                                            ('var', 'b1s')])]),
                                                        ('var', 'W2s'),
                                                        ('var', 'b2s')])),
                                                     ('body_decl',
                                                      'm',
                                                      ('tensor',
                                                       [('n', 'invariant')]),
                                                      ('call',
                                                       'linear',
                                                       [('call',
                                                         'relu',
                                                         [('call',
                                                           'linear',
                                                           [('var', 'y1'),
                                                            ('var', 'W1m'),
                                                            ('var', 'b1m')])]),
                                                        ('var', 'W2m'),
                                                        ('var', 'b2m')]))],
                                      'body': ('call',
                                               'concat',
                                               [('var', 'y1'),
                                                ('mul',
                                                 ('sub',
                                                  ('var', 'y2'),
                                                  ('var', 'm')),
                                                 ('call',
                                                  'exp',
                                                  [('neg', ('var', 's'))]))])},
                                     {'name': 'coupling_log_det',
                                      'params': [('x',
                                                  ('tensor',
                                                   [('d', 'invariant')])),
                                                 ('W1s',
                                                  ('tensor',
                                                   [('h', 'invariant'),
                                                    ('n', 'invariant')])),
                                                 ('b1s',
                                                  ('tensor',
                                                   [('h', 'invariant')])),
                                                 ('W2s',
                                                  ('tensor',
                                                   [('n', 'invariant'),
                                                    ('h', 'invariant')])),
                                                 ('b2s',
                                                  ('tensor',
                                                   [('n', 'invariant')]))],
                                      'return_type': 'ℝ',
                                      'statements': [('body_decl',
                                                      'x1',
                                                      ('tensor',
                                                       [('n', 'invariant')]),
                                                      ('indexN',
                                                       'x',
                                                       [('slice_item',
                                                         None,
                                                         ('field_access',
                                                          ('var', 'this'),
                                                          'n'))])),
                                                     ('body_decl',
                                                      's',
                                                      ('tensor',
                                                       [('n', 'invariant')]),
                                                      ('call',
                                                       'linear',
                                                       [('call',
                                                         'relu',
                                                         [('call',
                                                           'linear',
                                                           [('var', 'x1'),
                                                            ('var', 'W1s'),
                                                            ('var', 'b1s')])]),
                                                        ('var', 'W2s'),
                                                        ('var', 'b2s')]))],
                                      'body': ('call', 'sum', [('var', 's')])},
                                     {'name': 'swap',
                                      'params': [('x',
                                                  ('tensor',
                                                   [('d', 'invariant')]))],
                                      'return_type': ('tensor',
                                                      [('d', 'invariant')]),
                                      'statements': [],
                                      'body': ('call',
                                               'concat',
                                               [('indexN',
                                                 'x',
                                                 [('slice_item',
                                                   ('field_access',
                                                    ('var', 'this'),
                                                    'n'),
                                                   None)]),
                                                ('indexN',
                                                 'x',
                                                 [('slice_item',
                                                   None,
                                                   ('field_access',
                                                    ('var', 'this'),
                                                    'n'))])])},
                                     {'name': 'forward_z',
                                      'params': [('x',
                                                  ('tensor',
                                                   [('d', 'invariant')]))],
                                      'return_type': ('tensor',
                                                      [('d', 'invariant')]),
                                      'statements': [('body_decl',
                                                      'h',
                                                      ('tensor',
                                                       [('d', 'invariant')]),
                                                      ('method_call',
                                                       ('var', 'this'),
                                                       'coupling',
                                                       [('var', 'x'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'W1a_s'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'b1a_s'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'W2a_s'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'b2a_s'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'W1a_m'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'b1a_m'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'W2a_m'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'b2a_m')])),
                                                     ('body_assign',
                                                      'h',
                                                      ('method_call',
                                                       ('var', 'this'),
                                                       'swap',
                                                       [('var', 'h')])),
                                                     ('body_assign',
                                                      'h',
                                                      ('method_call',
                                                       ('var', 'this'),
                                                       'coupling',
                                                       [('var', 'h'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'W1b_s'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'b1b_s'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'W2b_s'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'b2b_s'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'W1b_m'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'b1b_m'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'W2b_m'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'b2b_m')])),
                                                     ('body_assign',
                                                      'h',
                                                      ('method_call',
                                                       ('var', 'this'),
                                                       'swap',
                                                       [('var', 'h')]))],
                                      'body': ('var', 'h')},
                                     {'name': 'log_det',
                                      'params': [('x',
                                                  ('tensor',
                                                   [('d', 'invariant')]))],
                                      'return_type': 'ℝ',
                                      'statements': [('body_decl',
                                                      'ld_a',
                                                      'ℝ',
                                                      ('method_call',
                                                       ('var', 'this'),
                                                       'coupling_log_det',
                                                       [('var', 'x'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'W1a_s'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'b1a_s'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'W2a_s'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'b2a_s')])),
                                                     ('body_decl',
                                                      'h',
                                                      ('tensor',
                                                       [('d', 'invariant')]),
                                                      ('method_call',
                                                       ('var', 'this'),
                                                       'coupling',
                                                       [('var', 'x'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'W1a_s'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'b1a_s'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'W2a_s'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'b2a_s'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'W1a_m'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'b1a_m'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'W2a_m'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'b2a_m')])),
                                                     ('body_assign',
                                                      'h',
                                                      ('method_call',
                                                       ('var', 'this'),
                                                       'swap',
                                                       [('var', 'h')])),
                                                     ('body_decl',
                                                      'ld_b',
                                                      'ℝ',
                                                      ('method_call',
                                                       ('var', 'this'),
                                                       'coupling_log_det',
                                                       [('var', 'h'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'W1b_s'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'b1b_s'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'W2b_s'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'b2b_s')]))],
                                      'body': ('add',
                                               ('var', 'ld_a'),
                                               ('var', 'ld_b'))},
                                     {'name': 'λ',
                                      'params': [('x',
                                                  ('tensor',
                                                   [('d', 'invariant')]))],
                                      'return_type': 'ℝ',
                                      'statements': [('body_decl',
                                                      'z',
                                                      ('tensor',
                                                       [('d', 'invariant')]),
                                                      ('method_call',
                                                       ('var', 'this'),
                                                       'forward_z',
                                                       [('var', 'x')]))],
                                      'body': ('add',
                                               ('call',
                                                'log_pz',
                                                [('var', 'z'),
                                                 ('field_access',
                                                  ('var', 'this'),
                                                  'd')]),
                                               ('method_call',
                                                ('var', 'this'),
                                                'log_det',
                                                [('var', 'x')]))},
                                     {'name': 'inverse',
                                      'params': [('z',
                                                  ('tensor',
                                                   [('d', 'invariant')]))],
                                      'return_type': ('tensor',
                                                      [('d', 'invariant')]),
                                      'statements': [('body_decl',
                                                      'h',
                                                      ('tensor',
                                                       [('d', 'invariant')]),
                                                      ('method_call',
                                                       ('var', 'this'),
                                                       'swap',
                                                       [('var', 'z')])),
                                                     ('body_assign',
                                                      'h',
                                                      ('method_call',
                                                       ('var', 'this'),
                                                       'coupling_inv',
                                                       [('var', 'h'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'W1b_s'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'b1b_s'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'W2b_s'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'b2b_s'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'W1b_m'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'b1b_m'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'W2b_m'),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'b2b_m')])),
                                                     ('body_assign',
                                                      'h',
                                                      ('method_call',
                                                       ('var', 'this'),
                                                       'swap',
                                                       [('var', 'h')]))],
                                      'body': ('method_call',
                                               ('var', 'this'),
                                               'coupling_inv',
                                               [('var', 'h'),
                                                ('field_access',
                                                 ('var', 'this'),
                                                 'W1a_s'),
                                                ('field_access',
                                                 ('var', 'this'),
                                                 'b1a_s'),
                                                ('field_access',
                                                 ('var', 'this'),
                                                 'W2a_s'),
                                                ('field_access',
                                                 ('var', 'this'),
                                                 'b2a_s'),
                                                ('field_access',
                                                 ('var', 'this'),
                                                 'W1a_m'),
                                                ('field_access',
                                                 ('var', 'this'),
                                                 'b1a_m'),
                                                ('field_access',
                                                 ('var', 'this'),
                                                 'W2a_m'),
                                                ('field_access',
                                                 ('var', 'this'),
                                                 'b2a_m')])},
                                     {'name': 'sample',
                                      'params': [],
                                      'return_type': ('tensor',
                                                      [('d', 'invariant')]),
                                      'statements': [('typed_sample',
                                                      'z',
                                                      ('tensor',
                                                       [('d', 'invariant')]),
                                                      ('call',
                                                       'Normal',
                                                       [('num', 0.0),
                                                        ('num', 1.0),
                                                        ('field_access',
                                                         ('var', 'this'),
                                                         'd')]))],
                                      'body': ('method_call',
                                               ('var', 'this'),
                                               'inverse',
                                               [('var', 'z')])}]}},
 'program': [('seed', ('num', 0)),
             ('func_def', 'len1d'),
             ('func_def', 'relu'),
             ('func_def', 'linear'),
             ('func_def', 'flatten'),
             ('func_def', 'unflatten'),
             ('func_def', 'dequantize'),
             ('func_def', 'log_pz'),
             ('class_def', 'RealNVP'),
             ('func_def', 'neg_loglik'),
             ('func_def', 'nll'),
             ('assign',
              'dataset',
              ('call', 'create_dataset', [('num', 80), ('num', 200)]),
              118),
             ('assign', 'train_dataset', ('index', 'dataset', ('num', 0)), 119),
             ('assign', 'test_dataset', ('index', 'dataset', ('num', 1)), 120),
             ('assign', 'train_X', ('index', 'train_dataset', ('num', 0)), 122),
             ('assign', 'test_X', ('index', 'test_dataset', ('num', 0)), 123),
             ('stmt_tuple_unpack',
              [('len_train', 'ℝ'), ('len_test', 'ℝ')],
              ('expr_list',
               [('call', 'len1d', [('var', 'train_X')]),
                ('call', 'len1d', [('var', 'test_X')])])),
             ('decl', 'd', 'ℕ', ('num', 784), 129),
             ('decl', 'h', 'ℕ', ('num', 128), 130),
             ('decl', 'n', 'ℕ', ('num', 392), 131),
             ('stmt_tuple_unpack',
              [('s1', 'ℝ'), ('s2', 'ℝ')],
              ('expr_list',
               [('call', 'sqrt', [('div', ('num', 2.0), ('var', 'n'))]),
                ('mul',
                 ('call', 'sqrt', [('div', ('num', 2.0), ('var', 'h'))]),
                 ('num', 0.01))])),
             ('decl',
              'W1a_s',
              ('tensor', [('h', 'invariant'), ('n', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'h'),
               ('typed_sample_expr',
                'ε',
                ('tensor', [('n', 'invariant')]),
                ('call',
                 'Normal',
                 [('num', 0.0), ('var', 's1'), ('var', 'n')]))),
              136),
             ('decl',
              'b1a_s',
              ('tensor', [('h', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'h'),
               ('mul', ('imaginary',), ('num', 0))),
              137),
             ('decl',
              'W2a_s',
              ('tensor', [('n', 'invariant'), ('h', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'n'),
               ('typed_sample_expr',
                'ε',
                ('tensor', [('h', 'invariant')]),
                ('call',
                 'Normal',
                 [('num', 0.0), ('var', 's2'), ('var', 'h')]))),
              138),
             ('decl',
              'b2a_s',
              ('tensor', [('n', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'n'),
               ('mul', ('imaginary',), ('num', 0))),
              139),
             ('decl',
              'W1a_m',
              ('tensor', [('h', 'invariant'), ('n', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'h'),
               ('typed_sample_expr',
                'ε',
                ('tensor', [('n', 'invariant')]),
                ('call',
                 'Normal',
                 [('num', 0.0), ('var', 's1'), ('var', 'n')]))),
              141),
             ('decl',
              'b1a_m',
              ('tensor', [('h', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'h'),
               ('mul', ('imaginary',), ('num', 0))),
              142),
             ('decl',
              'W2a_m',
              ('tensor', [('n', 'invariant'), ('h', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'n'),
               ('typed_sample_expr',
                'ε',
                ('tensor', [('h', 'invariant')]),
                ('call',
                 'Normal',
                 [('num', 0.0), ('var', 's2'), ('var', 'h')]))),
              143),
             ('decl',
              'b2a_m',
              ('tensor', [('n', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'n'),
               ('mul', ('imaginary',), ('num', 0))),
              144),
             ('decl',
              'W1b_s',
              ('tensor', [('h', 'invariant'), ('n', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'h'),
               ('typed_sample_expr',
                'ε',
                ('tensor', [('n', 'invariant')]),
                ('call',
                 'Normal',
                 [('num', 0.0), ('var', 's1'), ('var', 'n')]))),
              146),
             ('decl',
              'b1b_s',
              ('tensor', [('h', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'h'),
               ('mul', ('imaginary',), ('num', 0))),
              147),
             ('decl',
              'W2b_s',
              ('tensor', [('n', 'invariant'), ('h', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'n'),
               ('typed_sample_expr',
                'ε',
                ('tensor', [('h', 'invariant')]),
                ('call',
                 'Normal',
                 [('num', 0.0), ('var', 's2'), ('var', 'h')]))),
              148),
             ('decl',
              'b2b_s',
              ('tensor', [('n', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'n'),
               ('mul', ('imaginary',), ('num', 0))),
              149),
             ('decl',
              'W1b_m',
              ('tensor', [('h', 'invariant'), ('n', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'h'),
               ('typed_sample_expr',
                'ε',
                ('tensor', [('n', 'invariant')]),
                ('call',
                 'Normal',
                 [('num', 0.0), ('var', 's1'), ('var', 'n')]))),
              151),
             ('decl',
              'b1b_m',
              ('tensor', [('h', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'h'),
               ('mul', ('imaginary',), ('num', 0))),
              152),
             ('decl',
              'W2b_m',
              ('tensor', [('n', 'invariant'), ('h', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'n'),
               ('typed_sample_expr',
                'ε',
                ('tensor', [('h', 'invariant')]),
                ('call',
                 'Normal',
                 [('num', 0.0), ('var', 's2'), ('var', 'h')]))),
              153),
             ('decl',
              'b2b_m',
              ('tensor', [('n', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'n'),
               ('mul', ('imaginary',), ('num', 0))),
              154),
             ('decl',
              'model',
              ('struct_type', 'RealNVP'),
              ('call',
               'RealNVP',
               [('var', 'W1a_s'),
                ('var', 'b1a_s'),
                ('var', 'W2a_s'),
                ('var', 'b2a_s'),
                ('var', 'W1a_m'),
                ('var', 'b1a_m'),
                ('var', 'W2a_m'),
                ('var', 'b2a_m'),
                ('var', 'W1b_s'),
                ('var', 'b1b_s'),
                ('var', 'W2b_s'),
                ('var', 'b2b_s'),
                ('var', 'W1b_m'),
                ('var', 'b1b_m'),
                ('var', 'W2b_m'),
                ('var', 'b2b_m'),
                ('var', 'n'),
                ('var', 'd')]),
              156),
             ('decl',
              'x0',
              ('tensor', [('d', 'invariant')]),
              ('call',
               'dequantize',
               [('call',
                 'flatten',
                 [('index', 'train_X', ('num', 0)), ('num', 28), ('num', 28)]),
                ('var', 'd')]),
              158),
             ('expr',
              ('call', 'print', [('call', 'model', [('var', 'x0')])]),
              0),
             ('expr', ('call', 'print', [('var', 'DEVICE')]), 0),
             ('decl',
              'train_flat',
              ('tensor', [('len_train', 'invariant'), ('d', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'len_train'),
               ('for_expr',
                'j',
                ('var', 'd'),
                ('mul', ('var', 'j'), ('num', 0)))),
              164),
             ('for_loop_range',
              'i',
              ('num', 0),
              ('var', 'len_train'),
              [('for_index_assign_nd',
                'train_flat',
                [('index_item', ('imaginary',)), ('slice_item', None, None)],
                ('call',
                 'dequantize',
                 [('call',
                   'flatten',
                   [('index', 'train_X', ('imaginary',)),
                    ('num', 28),
                    ('num', 28)]),
                  ('var', 'd')]))],
              165),
             ('decl',
              'test_flat',
              ('tensor', [('len_test', 'invariant'), ('d', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'len_test'),
               ('for_expr',
                'j',
                ('var', 'd'),
                ('mul', ('var', 'j'), ('num', 0)))),
              168),
             ('for_loop_range',
              'i',
              ('num', 0),
              ('var', 'len_test'),
              [('for_index_assign_nd',
                'test_flat',
                [('index_item', ('imaginary',)), ('slice_item', None, None)],
                ('call',
                 'dequantize',
                 [('call',
                   'flatten',
                   [('index', 'test_X', ('imaginary',)),
                    ('num', 28),
                    ('num', 28)]),
                  ('var', 'd')]))],
              169),
             ('decl', 'epochs', 'ℕ', ('num', 20), 174),
             ('decl', 'lr', 'ℝ', ('num', 0.0001), 175),
             ('decl',
              'losses',
              ('tensor', [('epochs', 'invariant')]),
              ('for_expr',
               'i',
               ('var', 'epochs'),
               ('mul', ('imaginary',), ('num', 0))),
              177),
             ('for_loop_range',
              'i',
              ('num', 0),
              ('var', 'epochs'),
              [('for_loop_range',
                'j',
                ('num', 0),
                ('var', 'len_train'),
                [('for_assign',
                  'L',
                  ('call',
                   'neg_loglik',
                   [('call',
                     'model',
                     [('index', 'train_flat', ('var', 'j'))])])),
                 ('for_assign',
                  'nW1a_s',
                  ('sub',
                   ('field_access', ('var', 'model'), 'W1a_s'),
                   ('mul',
                    ('var', 'lr'),
                    ('call',
                     'grad',
                     [('var', 'L'),
                      ('field_access', ('var', 'model'), 'W1a_s')])))),
                 ('for_assign',
                  'nb1a_s',
                  ('sub',
                   ('field_access', ('var', 'model'), 'b1a_s'),
                   ('mul',
                    ('var', 'lr'),
                    ('call',
                     'grad',
                     [('var', 'L'),
                      ('field_access', ('var', 'model'), 'b1a_s')])))),
                 ('for_assign',
                  'nW2a_s',
                  ('sub',
                   ('field_access', ('var', 'model'), 'W2a_s'),
                   ('mul',
                    ('var', 'lr'),
                    ('call',
                     'grad',
                     [('var', 'L'),
                      ('field_access', ('var', 'model'), 'W2a_s')])))),
                 ('for_assign',
                  'nb2a_s',
                  ('sub',
                   ('field_access', ('var', 'model'), 'b2a_s'),
                   ('mul',
                    ('var', 'lr'),
                    ('call',
                     'grad',
                     [('var', 'L'),
                      ('field_access', ('var', 'model'), 'b2a_s')])))),
                 ('for_assign',
                  'nW1a_m',
                  ('sub',
                   ('field_access', ('var', 'model'), 'W1a_m'),
                   ('mul',
                    ('var', 'lr'),
                    ('call',
                     'grad',
                     [('var', 'L'),
                      ('field_access', ('var', 'model'), 'W1a_m')])))),
                 ('for_assign',
                  'nb1a_m',
                  ('sub',
                   ('field_access', ('var', 'model'), 'b1a_m'),
                   ('mul',
                    ('var', 'lr'),
                    ('call',
                     'grad',
                     [('var', 'L'),
                      ('field_access', ('var', 'model'), 'b1a_m')])))),
                 ('for_assign',
                  'nW2a_m',
                  ('sub',
                   ('field_access', ('var', 'model'), 'W2a_m'),
                   ('mul',
                    ('var', 'lr'),
                    ('call',
                     'grad',
                     [('var', 'L'),
                      ('field_access', ('var', 'model'), 'W2a_m')])))),
                 ('for_assign',
                  'nb2a_m',
                  ('sub',
                   ('field_access', ('var', 'model'), 'b2a_m'),
                   ('mul',
                    ('var', 'lr'),
                    ('call',
                     'grad',
                     [('var', 'L'),
                      ('field_access', ('var', 'model'), 'b2a_m')])))),
                 ('for_assign',
                  'nW1b_s',
                  ('sub',
                   ('field_access', ('var', 'model'), 'W1b_s'),
                   ('mul',
                    ('var', 'lr'),
                    ('call',
                     'grad',
                     [('var', 'L'),
                      ('field_access', ('var', 'model'), 'W1b_s')])))),
                 ('for_assign',
                  'nb1b_s',
                  ('sub',
                   ('field_access', ('var', 'model'), 'b1b_s'),
                   ('mul',
                    ('var', 'lr'),
                    ('call',
                     'grad',
                     [('var', 'L'),
                      ('field_access', ('var', 'model'), 'b1b_s')])))),
                 ('for_assign',
                  'nW2b_s',
                  ('sub',
                   ('field_access', ('var', 'model'), 'W2b_s'),
                   ('mul',
                    ('var', 'lr'),
                    ('call',
                     'grad',
                     [('var', 'L'),
                      ('field_access', ('var', 'model'), 'W2b_s')])))),
                 ('for_assign',
                  'nb2b_s',
                  ('sub',
                   ('field_access', ('var', 'model'), 'b2b_s'),
                   ('mul',
                    ('var', 'lr'),
                    ('call',
                     'grad',
                     [('var', 'L'),
                      ('field_access', ('var', 'model'), 'b2b_s')])))),
                 ('for_assign',
                  'nW1b_m',
                  ('sub',
                   ('field_access', ('var', 'model'), 'W1b_m'),
                   ('mul',
                    ('var', 'lr'),
                    ('call',
                     'grad',
                     [('var', 'L'),
                      ('field_access', ('var', 'model'), 'W1b_m')])))),
                 ('for_assign',
                  'nb1b_m',
                  ('sub',
                   ('field_access', ('var', 'model'), 'b1b_m'),
                   ('mul',
                    ('var', 'lr'),
                    ('call',
                     'grad',
                     [('var', 'L'),
                      ('field_access', ('var', 'model'), 'b1b_m')])))),
                 ('for_assign',
                  'nW2b_m',
                  ('sub',
                   ('field_access', ('var', 'model'), 'W2b_m'),
                   ('mul',
                    ('var', 'lr'),
                    ('call',
                     'grad',
                     [('var', 'L'),
                      ('field_access', ('var', 'model'), 'W2b_m')])))),
                 ('for_assign',
                  'nb2b_m',
                  ('sub',
                   ('field_access', ('var', 'model'), 'b2b_m'),
                   ('mul',
                    ('var', 'lr'),
                    ('call',
                     'grad',
                     [('var', 'L'),
                      ('field_access', ('var', 'model'), 'b2b_m')])))),
                 ('for_assign',
                  'model',
                  ('call',
                   'RealNVP',
                   [('var', 'nW1a_s'),
                    ('var', 'nb1a_s'),
                    ('var', 'nW2a_s'),
                    ('var', 'nb2a_s'),
                    ('var', 'nW1a_m'),
                    ('var', 'nb1a_m'),
                    ('var', 'nW2a_m'),
                    ('var', 'nb2a_m'),
                    ('var', 'nW1b_s'),
                    ('var', 'nb1b_s'),
                    ('var', 'nW2b_s'),
                    ('var', 'nb2b_s'),
                    ('var', 'nW1b_m'),
                    ('var', 'nb1b_m'),
                    ('var', 'nW2b_m'),
                    ('var', 'nb2b_m'),
                    ('field_access', ('var', 'model'), 'n'),
                    ('field_access', ('var', 'model'), 'd')]))],
                180),
               ('for_assign',
                'epoch_loss',
                ('call',
                 'nll',
                 [('var', 'model'),
                  ('var', 'train_flat'),
                  ('var', 'len_train')])),
               ('for_index_assign_nd',
                'losses',
                [('index_item', ('imaginary',))],
                ('var', 'epoch_loss')),
               ('for_call', 'print', [('var', 'epoch_loss')]),
               ('for_assign',
                'bits',
                ('add',
                 ('div',
                  ('var', 'epoch_loss'),
                  ('mul', ('var', 'd'), ('call', 'log', [('num', 2.0)]))),
                 ('num', 8.0))),
               ('for_call', 'print', [('var', 'bits')])],
              179),
             ('decl',
              'test_loss',
              'ℝ',
              ('call',
               'nll',
               [('var', 'model'), ('var', 'test_flat'), ('var', 'len_test')]),
              207),
             ('expr', ('call', 'print', [('var', 'test_loss')]), 0),
             ('decl',
              'bits_per_dim',
              'ℝ',
              ('add',
               ('div',
                ('var', 'test_loss'),
                ('mul', ('var', 'd'), ('call', 'log', [('num', 2.0)]))),
               ('num', 8.0)),
              209),
             ('expr', ('call', 'print', [('var', 'bits_per_dim')]), 0),
             ('decl',
              'gen_flat',
              ('tensor', [('d', 'invariant')]),
              ('method_call', ('var', 'model'), 'sample', []),
              214),
             ('decl',
              'gen_img',
              ('tensor', [(28, 'invariant'), (28, 'invariant')]),
              ('call',
               'unflatten',
               [('var', 'gen_flat'), ('num', 28), ('num', 28)]),
              215),
             ('expr', ('call', 'print', [('var', 'gen_img')]), 0)]}
