EXPECTED = {'functions': {'zero_1d_array': {'params': [('len', 'ℝ')],
                                 'return_type': ('tensor',
                                                 [('m', 'invariant')]),
                                 'body': ('var', 'results'),
                                 'has_loop': False,
                                 'statements': [('body_decl',
                                                 'results',
                                                 ('tensor',
                                                  [('len', 'invariant')]),
                                                 ('for_expr',
                                                  'i',
                                                  ('var', 'len'),
                                                  ('mul',
                                                   ('imaginary',),
                                                   ('num', 0))))]},
               'get_1d_array_length': {'params': [('x',
                                                   ('tensor',
                                                    [('m', 'invariant')]))],
                                       'return_type': 'ℝ',
                                       'body': ('var', 'total'),
                                       'has_loop': False,
                                       'statements': [('body_decl',
                                                       'total',
                                                       'ℝ',
                                                       ('num', 0)),
                                                      ('body_decl',
                                                       'temp',
                                                       'ℝ',
                                                       ('num', 0)),
                                                      ('body_for',
                                                       'i',
                                                       [('loop_assign',
                                                         'temp',
                                                         ('index',
                                                          'x',
                                                          ('imaginary',))),
                                                        ('loop_pluseq',
                                                         'total',
                                                         ('num', 1))],
                                                       ['x'])]},
               'append': {'params': [('x', ('tensor', [('m', 'invariant')])),
                                     ('var', 'ℝ')],
                          'return_type': ('tensor', [('n', 'invariant')]),
                          'body': ('var', 'results'),
                          'has_loop': False,
                          'statements': [('body_decl',
                                          'new_length',
                                          'ℝ',
                                          ('add',
                                           ('call', 'len', [('var', 'x')]),
                                           ('num', 1))),
                                         ('body_decl',
                                          'results',
                                          ('tensor',
                                           [('new_length', 'invariant')]),
                                          ('call',
                                           'zero_1d_array',
                                           [('var', 'new_length')])),
                                         ('body_decl',
                                          'len_x',
                                          'ℕ',
                                          ('call',
                                           'get_1d_array_length',
                                           [('var', 'x')])),
                                         ('body_for_range',
                                          'i',
                                          ('num', 0),
                                          ('var', 'new_length'),
                                          [('loop_if_else',
                                            ('cond_lt',
                                             ('imaginary',),
                                             ('var', 'len_x')),
                                            [('loop_index_assign_nd',
                                              'results',
                                              [('index_item', ('imaginary',))],
                                              ('index', 'x', ('imaginary',)))],
                                            [('loop_index_assign_nd',
                                              'results',
                                              [('index_item', ('imaginary',))],
                                              ('var', 'var'))])])]},
               'f': {'params': [('state', ('tensor', [(2, 'invariant')])),
                                ('θ', ('tensor', [(2, 'invariant')]))],
                     'return_type': ('tensor', [(2, 'invariant')]),
                     'body': ('array', [('var', 'dx'), ('var', 'dy')]),
                     'has_loop': False,
                     'statements': [('body_decl',
                                     'x',
                                     'ℝ',
                                     ('index', 'state', ('num', 0))),
                                    ('body_decl',
                                     'y',
                                     'ℝ',
                                     ('index', 'state', ('num', 1))),
                                    ('body_decl',
                                     'a',
                                     'ℝ',
                                     ('index', 'θ', ('num', 0))),
                                    ('body_decl',
                                     'b',
                                     'ℝ',
                                     ('index', 'θ', ('num', 1))),
                                    ('body_decl',
                                     'dx',
                                     'ℝ',
                                     ('sub',
                                      ('add',
                                       ('mul', ('var', 'a'), ('var', 'y')),
                                       ('mul',
                                        ('pow', ('var', 'x'), ('num', 2)),
                                        ('var', 'y'))),
                                      ('var', 'x'))),
                                    ('body_decl',
                                     'dy',
                                     'ℝ',
                                     ('sub',
                                      ('sub',
                                       ('var', 'b'),
                                       ('mul', ('var', 'a'), ('var', 'y'))),
                                      ('mul',
                                       ('pow', ('var', 'x'), ('num', 2)),
                                       ('var', 'y'))))]},
               'rk4_step': {'params': [('state',
                                        ('tensor', [(2, 'invariant')])),
                                       ('θ', ('tensor', [(2, 'invariant')]))],
                            'return_type': ('tensor', [(2, 'invariant')]),
                            'body': ('add',
                                     ('var', 'state'),
                                     ('mul',
                                      ('div', ('var', 'dt'), ('num', 6.0)),
                                      ('add',
                                       ('add',
                                        ('add',
                                         ('var', 'k1'),
                                         ('mul', ('num', 2.0), ('var', 'k2'))),
                                        ('mul', ('num', 2.0), ('var', 'k3'))),
                                       ('var', 'k4')))),
                            'has_loop': False,
                            'statements': [('body_decl',
                                            'k1',
                                            ('tensor', [(2, 'invariant')]),
                                            ('call',
                                             'f',
                                             [('var', 'state'), ('var', 'θ')])),
                                           ('body_decl',
                                            'k2_state',
                                            ('tensor', [(2, 'invariant')]),
                                            ('add',
                                             ('var', 'state'),
                                             ('mul',
                                              ('mul',
                                               ('num', 0.5),
                                               ('var', 'dt')),
                                              ('var', 'k1')))),
                                           ('body_decl',
                                            'k2',
                                            ('tensor', [(2, 'invariant')]),
                                            ('call',
                                             'f',
                                             [('var', 'k2_state'),
                                              ('var', 'θ')])),
                                           ('body_decl',
                                            'k3_state',
                                            ('tensor', [(2, 'invariant')]),
                                            ('add',
                                             ('var', 'state'),
                                             ('mul',
                                              ('mul',
                                               ('num', 0.5),
                                               ('var', 'dt')),
                                              ('var', 'k2')))),
                                           ('body_decl',
                                            'k3',
                                            ('tensor', [(2, 'invariant')]),
                                            ('call',
                                             'f',
                                             [('var', 'k3_state'),
                                              ('var', 'θ')])),
                                           ('body_decl',
                                            'k4_state',
                                            ('tensor', [(2, 'invariant')]),
                                            ('add',
                                             ('var', 'state'),
                                             ('mul',
                                              ('var', 'dt'),
                                              ('var', 'k3')))),
                                           ('body_decl',
                                            'k4',
                                            ('tensor', [(2, 'invariant')]),
                                            ('call',
                                             'f',
                                             [('var', 'k4_state'),
                                              ('var', 'θ')]))]},
               'solver': {'params': [('θ', ('tensor', [(2, 'invariant')]))],
                          'return_type': ('tensor',
                                          [(2, 'invariant'),
                                           ('m', 'invariant')]),
                          'body': ('array',
                                   [('var', 'x_array'), ('var', 'y_array')]),
                          'has_loop': False,
                          'statements': [('body_decl',
                                          'state',
                                          ('tensor', [(2, 'invariant')]),
                                          ('array',
                                           [('num', 1.0), ('num', 1.0)])),
                                         ('body_decl',
                                          'x_array',
                                          ('tensor', [(1, 'invariant')]),
                                          ('array', [('num', 1.0)])),
                                         ('body_decl',
                                          'y_array',
                                          ('tensor', [(1, 'invariant')]),
                                          ('array', [('num', 1.0)])),
                                         ('body_for_range',
                                          'i',
                                          ('num', 0),
                                          ('var', 'timesteps'),
                                          [('loop_assign',
                                            'results',
                                            ('call',
                                             'rk4_step',
                                             [('var', 'state'), ('var', 'θ')])),
                                           ('loop_assign',
                                            'x',
                                            ('index', 'results', ('num', 0))),
                                           ('loop_assign',
                                            'y',
                                            ('index', 'results', ('num', 1))),
                                           ('loop_assign',
                                            'x_array',
                                            ('call',
                                             'append',
                                             [('var', 'x_array'),
                                              ('var', 'x')])),
                                           ('loop_assign',
                                            'y_array',
                                            ('call',
                                             'append',
                                             [('var', 'y_array'),
                                              ('var', 'y')])),
                                           ('loop_assign',
                                            'state',
                                            ('var', 'results'))])]},
               'adjoint_grad': {'params': [('θ',
                                            ('tensor', [(2, 'invariant')]))],
                                'return_type': ('tensor', [('n', 'invariant')]),
                                'body': ('var', 'L'),
                                'has_loop': False,
                                'statements': [('body_decl',
                                                'states',
                                                ('tensor',
                                                 [(2, 'invariant'),
                                                  ('m', 'invariant')]),
                                                ('call',
                                                 'solver',
                                                 [('var', 'θ')])),
                                               ('body_decl',
                                                'x_array',
                                                ('tensor',
                                                 [('m', 'invariant')]),
                                                ('index',
                                                 'states',
                                                 ('num', 0))),
                                               ('body_decl',
                                                'y_array',
                                                ('tensor',
                                                 [('m', 'invariant')]),
                                                ('index',
                                                 'states',
                                                 ('num', 1))),
                                               ('body_decl',
                                                'm',
                                                'ℝ',
                                                ('call',
                                                 'get_1d_array_length',
                                                 [('var', 'x_array')])),
                                               ('body_decl',
                                                's',
                                                ('tensor', [(2, 'invariant')]),
                                                ('array',
                                                 [('div',
                                                   ('sub',
                                                    ('index',
                                                     'x_array',
                                                     ('sub',
                                                      ('var', 'm'),
                                                      ('num', 1))),
                                                    ('index',
                                                     'true_x',
                                                     ('sub',
                                                      ('var', 'm'),
                                                      ('num', 1)))),
                                                   ('var', 'm')),
                                                  ('num', 0.0)])),
                                               ('body_decl',
                                                'L',
                                                ('tensor', [(2, 'invariant')]),
                                                ('call',
                                                 'zero_1d_array',
                                                 [('num', 2)])),
                                               ('body_for_range',
                                                'i',
                                                ('num', 0),
                                                ('sub',
                                                 ('var', 'm'),
                                                 ('num', 1)),
                                                [('loop_assign',
                                                  'idx',
                                                  ('sub',
                                                   ('sub',
                                                    ('var', 'm'),
                                                    ('num', 2)),
                                                   ('imaginary',))),
                                                 ('loop_assign',
                                                  'x',
                                                  ('index',
                                                   'x_array',
                                                   ('var', 'idx'))),
                                                 ('loop_assign',
                                                  'y',
                                                  ('index',
                                                   'y_array',
                                                   ('var', 'idx'))),
                                                 ('loop_assign',
                                                  'state',
                                                  ('array',
                                                   [('var', 'x'),
                                                    ('var', 'y')])),
                                                 ('loop_assign',
                                                  'J_state',
                                                  ('call',
                                                   'grad',
                                                   [('call',
                                                     'rk4_step',
                                                     [('var', 'state'),
                                                      ('var', 'θ')]),
                                                    ('var', 'state')])),
                                                 ('loop_assign',
                                                  'J_theta',
                                                  ('call',
                                                   'grad',
                                                   [('call',
                                                     'rk4_step',
                                                     [('var', 'state'),
                                                      ('var', 'θ')]),
                                                    ('var', 'θ')])),
                                                 ('loop_pluseq',
                                                  'L',
                                                  ('matmul',
                                                   ('var', 's'),
                                                   ('var', 'J_theta'))),
                                                 ('loop_assign',
                                                  'residual',
                                                  ('array',
                                                   [('div',
                                                     ('sub',
                                                      ('index',
                                                       'x_array',
                                                       ('var', 'idx')),
                                                      ('index',
                                                       'true_x',
                                                       ('var', 'idx'))),
                                                     ('var', 'm')),
                                                    ('num', 0.0)])),
                                                 ('loop_assign',
                                                  's',
                                                  ('add',
                                                   ('var', 'residual'),
                                                   ('matmul',
                                                    ('var', 's'),
                                                    ('var', 'J_state'))))])]}},
 'classes': {},
 'program': [('func_def', 'zero_1d_array'),
             ('func_def', 'get_1d_array_length'),
             ('func_def', 'append'),
             ('func_def', 'f'),
             ('func_def', 'rk4_step'),
             ('decl', 'dt', 'ℝ', ('num', 0.05), 72),
             ('decl', 'timesteps', 'ℝ', ('num', 600), 73),
             ('func_def', 'solver'),
             ('decl',
              'true_theta',
              ('tensor', [(2, 'invariant')]),
              ('array', [('num', 0.1), ('num', 0.6)]),
              88),
             ('decl',
              'true_results',
              ('tensor', [(2, 'invariant'), ('m', 'invariant')]),
              ('call', 'solver', [('var', 'true_theta')]),
              89),
             ('decl',
              'true_x',
              ('tensor', [('m', 'invariant')]),
              ('index', 'true_results', ('num', 0)),
              90),
             ('decl',
              'true_y',
              ('tensor', [('m', 'invariant')]),
              ('index', 'true_results', ('num', 1)),
              91),
             ('func_def', 'adjoint_grad'),
             ('decl',
              'θ',
              ('tensor', [(2, 'invariant')]),
              ('array', [('num', 0.2), ('num', 0.45)]),
              117),
             ('decl', 'learning_rate', 'ℝ', ('num', 0.01), 118),
             ('decl', 'beta1', 'ℝ', ('num', 0.9), 119),
             ('decl', 'beta2', 'ℝ', ('num', 0.999), 120),
             ('decl', 'eps_adam', 'ℝ', ('num', 1e-08), 121),
             ('decl',
              'm_adam',
              ('tensor', [(2, 'invariant')]),
              ('array', [('num', 0.0), ('num', 0.0)]),
              122),
             ('decl',
              'v_adam',
              ('tensor', [(2, 'invariant')]),
              ('array', [('num', 0.0), ('num', 0.0)]),
              123),
             ('decl', 't_adam', 'ℝ', ('num', 0.0), 124),
             ('decl', 'epochs', 'ℕ', ('num', 1), 130),
             ('for_loop_range',
              'i',
              ('num', 0),
              ('var', 'epochs'),
              [('for_assign', 'g', ('call', 'adjoint_grad', [('var', 'θ')])),
               ('for_assign',
                't_adam',
                ('add', ('var', 't_adam'), ('num', 1.0))),
               ('for_assign',
                'm_adam',
                ('add',
                 ('mul', ('var', 'beta1'), ('var', 'm_adam')),
                 ('mul',
                  ('sub', ('num', 1.0), ('var', 'beta1')),
                  ('var', 'g')))),
               ('for_assign',
                'v_adam',
                ('add',
                 ('mul', ('var', 'beta2'), ('var', 'v_adam')),
                 ('mul',
                  ('sub', ('num', 1.0), ('var', 'beta2')),
                  ('mul', ('var', 'g'), ('var', 'g'))))),
               ('for_assign',
                'mhat',
                ('div',
                 ('var', 'm_adam'),
                 ('sub',
                  ('num', 1.0),
                  ('pow', ('var', 'beta1'), ('var', 't_adam'))))),
               ('for_assign',
                'vhat',
                ('div',
                 ('var', 'v_adam'),
                 ('sub',
                  ('num', 1.0),
                  ('pow', ('var', 'beta2'), ('var', 't_adam'))))),
               ('for_assign',
                'θ',
                ('sub',
                 ('var', 'θ'),
                 ('div',
                  ('mul', ('var', 'learning_rate'), ('var', 'mhat')),
                  ('add',
                   ('call', 'sqrt', [('var', 'vhat')]),
                   ('var', 'eps_adam')))))],
              132),
             ('assign',
              'pred_results',
              ('call', 'solver', [('var', 'θ')]),
              141)]}
