EXPECTED = {'functions': {'zero_1d_array': {'params': [('len', 'ℝ')],
                                 'return_type': ('tensor',
                                                 [('m', 'invariant')]),
                                 'body': ('var', 'results'),
                                 'has_loop': False,
                                 'statements': [('body_decl',
                                                 'results',
                                                 ('tensor',
                                                  [('len', 'invariant')]),
                                                 ('for_expr',
                                                  'i',
                                                  ('var', 'len'),
                                                  ('mul',
                                                   ('imaginary',),
                                                   ('num', 0))))]},
               'get_1d_array_length': {'params': [('x',
                                                   ('tensor',
                                                    [('m', 'invariant')]))],
                                       'return_type': 'ℝ',
                                       'body': ('var', 'total'),
                                       'has_loop': False,
                                       'statements': [('body_decl',
                                                       'total',
                                                       'ℝ',
                                                       ('num', 0)),
                                                      ('body_decl',
                                                       'temp',
                                                       'ℝ',
                                                       ('num', 0)),
                                                      ('body_for',
                                                       'i',
                                                       [('loop_assign',
                                                         'temp',
                                                         ('index',
                                                          'x',
                                                          ('imaginary',))),
                                                        ('loop_pluseq',
                                                         'total',
                                                         ('num', 1))],
                                                       ['x'])]},
               'clip_stoichiometry': {'params': [('θ', 'ℝ')],
                                      'return_type': 'ℝ',
                                      'body': ('var', 'x'),
                                      'has_loop': False,
                                      'statements': [('body_decl',
                                                      'x',
                                                      'ℝ',
                                                      ('var', 'θ')),
                                                     ('body_if',
                                                      ('cond_lt',
                                                       ('var', 'x'),
                                                       ('num', 0.002)),
                                                      [('body_assign',
                                                        'x',
                                                        ('num', 0.002))]),
                                                     ('body_if',
                                                      ('cond_gt',
                                                       ('var', 'x'),
                                                       ('num', 0.995)),
                                                      [('body_assign',
                                                        'x',
                                                        ('num', 0.995))])]},
               'clip_concentration': {'params': [('c_s', 'ℝ'),
                                                 ('c_s_max', 'ℝ')],
                                      'return_type': 'ℝ',
                                      'body': ('var', 'c'),
                                      'has_loop': False,
                                      'statements': [('body_decl',
                                                      'c',
                                                      'ℝ',
                                                      ('var', 'c_s')),
                                                     ('body_if',
                                                      ('cond_lt',
                                                       ('var', 'c'),
                                                       ('num', 1.0)),
                                                      [('body_assign',
                                                        'c',
                                                        ('num', 1.0))]),
                                                     ('body_if',
                                                      ('cond_gt',
                                                       ('var', 'c'),
                                                       ('sub',
                                                        ('var', 'c_s_max'),
                                                        ('num', 1.0))),
                                                      [('body_assign',
                                                        'c',
                                                        ('sub',
                                                         ('var', 'c_s_max'),
                                                         ('num', 1.0)))])]},
               'tanh_scalar': {'params': [('z', 'ℝ')],
                               'return_type': 'ℝ',
                               'body': ('div',
                                        ('sub',
                                         ('call', 'exp', [('var', 'z')]),
                                         ('call',
                                          'exp',
                                          [('neg', ('var', 'z'))])),
                                        ('add',
                                         ('call', 'exp', [('var', 'z')]),
                                         ('call',
                                          'exp',
                                          [('neg', ('var', 'z'))]))),
                               'has_loop': False,
                               'statements': []},
               'ocp_negative': {'params': [('θ', 'ℝ')],
                                'return_type': 'ℝ',
                                'body': ('sub',
                                         ('sub',
                                          ('sub',
                                           ('add',
                                            ('mul',
                                             ('num', 1.9793),
                                             ('call',
                                              'exp',
                                              [('mul',
                                                ('neg', ('num', 39.3631)),
                                                ('var', 'x'))])),
                                            ('num', 0.2482)),
                                           ('mul',
                                            ('num', 0.0909),
                                            ('call',
                                             'tanh_scalar',
                                             [('mul',
                                               ('num', 29.8538),
                                               ('sub',
                                                ('var', 'x'),
                                                ('num', 0.1234)))]))),
                                          ('mul',
                                           ('num', 0.04478),
                                           ('call',
                                            'tanh_scalar',
                                            [('mul',
                                              ('num', 14.9159),
                                              ('sub',
                                               ('var', 'x'),
                                               ('num', 0.2769)))]))),
                                         ('mul',
                                          ('num', 0.0205),
                                          ('call',
                                           'tanh_scalar',
                                           [('mul',
                                             ('num', 30.4444),
                                             ('sub',
                                              ('var', 'x'),
                                              ('num', 0.6103)))]))),
                                'has_loop': False,
                                'statements': [('body_decl',
                                                'x',
                                                'ℝ',
                                                ('call',
                                                 'clip_stoichiometry',
                                                 [('var', 'θ')]))]},
               'ocp_positive': {'params': [('θ', 'ℝ')],
                                'return_type': 'ℝ',
                                'body': ('add',
                                         ('sub',
                                          ('sub',
                                           ('add',
                                            ('mul',
                                             ('neg', ('num', 0.809)),
                                             ('var', 'x')),
                                            ('num', 4.4875)),
                                           ('mul',
                                            ('num', 0.0428),
                                            ('call',
                                             'tanh_scalar',
                                             [('mul',
                                               ('num', 18.5138),
                                               ('sub',
                                                ('var', 'x'),
                                                ('num', 0.5542)))]))),
                                          ('mul',
                                           ('num', 17.7326),
                                           ('call',
                                            'tanh_scalar',
                                            [('mul',
                                              ('num', 15.789),
                                              ('sub',
                                               ('var', 'x'),
                                               ('num', 0.3117)))]))),
                                         ('mul',
                                          ('num', 17.5842),
                                          ('call',
                                           'tanh_scalar',
                                           [('mul',
                                             ('num', 15.9308),
                                             ('sub',
                                              ('var', 'x'),
                                              ('num', 0.312)))]))),
                                'has_loop': False,
                                'statements': [('body_decl',
                                                'x',
                                                'ℝ',
                                                ('call',
                                                 'clip_stoichiometry',
                                                 [('var', 'θ')]))]},
               'exchange_current': {'params': [('c_s_surface', 'ℝ'),
                                               ('c_s_max', 'ℝ'),
                                               ('k0', 'ℝ')],
                                    'return_type': 'ℝ',
                                    'body': ('mul',
                                             ('var', 'k0'),
                                             ('call',
                                              'sqrt',
                                              [('mul',
                                                ('mul',
                                                 ('var', 'c_e'),
                                                 ('var', 'c_s')),
                                                ('sub',
                                                 ('var', 'c_s_max'),
                                                 ('var', 'c_s')))])),
                                    'has_loop': False,
                                    'statements': [('body_decl',
                                                    'c_s',
                                                    'ℝ',
                                                    ('call',
                                                     'clip_concentration',
                                                     [('var', 'c_s_surface'),
                                                      ('var', 'c_s_max')]))]},
               'asinh_scalar': {'params': [('z', 'ℝ')],
                                'return_type': 'ℝ',
                                'body': ('call',
                                         'log',
                                         [('add',
                                           ('var', 'z'),
                                           ('call',
                                            'sqrt',
                                            [('add',
                                              ('pow', ('var', 'z'), ('num', 2)),
                                              ('num', 1.0))]))]),
                                'has_loop': False,
                                'statements': []},
               'bv_overpotential': {'params': [('reaction_current', 'ℝ'),
                                               ('i0', 'ℝ')],
                                    'return_type': 'ℝ',
                                    'body': ('mul',
                                             ('div',
                                              ('mul',
                                               ('mul',
                                                ('num', 2.0),
                                                ('var', 'gas_constant')),
                                               ('var', 'temperature')),
                                              ('var', 'faraday')),
                                             ('call',
                                              'asinh_scalar',
                                              [('var', 'z')])),
                                    'has_loop': False,
                                    'statements': [('body_decl',
                                                    'z',
                                                    'ℝ',
                                                    ('div',
                                                     ('var',
                                                      'reaction_current'),
                                                     ('mul',
                                                      ('num', 2.0),
                                                      ('var', 'i0'))))]},
               'negative_surface_flux': {'params': [('current', 'ℝ')],
                                         'return_type': 'ℝ',
                                         'body': ('div',
                                                  ('var', 'current'),
                                                  ('mul',
                                                   ('mul',
                                                    ('mul',
                                                     ('var', 'faraday'),
                                                     ('var', 'electrode_area')),
                                                    ('var', 'thickness_n')),
                                                   ('var', 'area_density'))),
                                         'has_loop': False,
                                         'statements': [('body_decl',
                                                         'area_density',
                                                         'ℝ',
                                                         ('div',
                                                          ('mul',
                                                           ('num', 3.0),
                                                           ('var', 'ε_s_n')),
                                                          ('var',
                                                           'radius_n')))]},
               'positive_surface_flux': {'params': [('current', 'ℝ'),
                                                    ('ε_s_p', 'ℝ')],
                                         'return_type': 'ℝ',
                                         'body': ('div',
                                                  ('neg', ('var', 'current')),
                                                  ('mul',
                                                   ('mul',
                                                    ('mul',
                                                     ('var', 'faraday'),
                                                     ('var', 'electrode_area')),
                                                    ('var', 'thickness_p')),
                                                   ('var', 'area_density'))),
                                         'has_loop': False,
                                         'statements': [('body_decl',
                                                         'area_density',
                                                         'ℝ',
                                                         ('div',
                                                          ('mul',
                                                           ('num', 3.0),
                                                           ('var', 'ε_s_p')),
                                                          ('var',
                                                           'radius_p')))]},
               'particle_rhs': {'params': [('c',
                                            ('tensor', [('m', 'invariant')])),
                                           ('radius', 'ℝ'),
                                           ('diffusivity', 'ℝ'),
                                           ('j_out', 'ℝ')],
                                'return_type': ('tensor', [('m', 'invariant')]),
                                'body': ('var', 'dc'),
                                'has_loop': False,
                                'statements': [('body_decl',
                                                'dc',
                                                ('tensor',
                                                 [('nr', 'invariant')]),
                                                ('call',
                                                 'zero_1d_array',
                                                 [('var', 'nr')])),
                                               ('body_decl',
                                                'dr',
                                                'ℝ',
                                                ('div',
                                                 ('var', 'radius'),
                                                 ('var', 'nr'))),
                                               ('body_decl',
                                                'shell_volume_factor',
                                                'ℝ',
                                                ('num', 0.0)),
                                               ('body_decl',
                                                'outward_gradient',
                                                'ℝ',
                                                ('num', 0.0)),
                                               ('body_decl',
                                                'inward_gradient',
                                                'ℝ',
                                                ('num', 0.0)),
                                               ('body_decl',
                                                'diffusion_in',
                                                'ℝ',
                                                ('num', 0.0)),
                                               ('body_decl',
                                                'first_cell',
                                                'ℕ',
                                                ('num', 0)),
                                               ('body_decl',
                                                'last_cell',
                                                'ℕ',
                                                ('sub',
                                                 ('var', 'nr'),
                                                 ('num', 1))),
                                               ('body_for_range',
                                                'i',
                                                ('num', 0),
                                                ('var', 'nr'),
                                                [('loop_assign',
                                                  'shell_volume_factor',
                                                  ('sub',
                                                   ('pow',
                                                    ('add',
                                                     ('imaginary',),
                                                     ('num', 1)),
                                                    ('num', 3)),
                                                   ('pow',
                                                    ('imaginary',),
                                                    ('num', 3)))),
                                                 ('loop_if_else',
                                                  ('cond_eq',
                                                   ('imaginary',),
                                                   ('var', 'first_cell')),
                                                  [('loop_index_assign_nd',
                                                    'dc',
                                                    [('imaginary',)],
                                                    ('div',
                                                     ('mul',
                                                      ('mul',
                                                       ('num', 3.0),
                                                       ('var', 'diffusivity')),
                                                      ('sub',
                                                       ('index',
                                                        'c',
                                                        ('num', 1)),
                                                       ('index',
                                                        'c',
                                                        ('num', 0)))),
                                                     ('pow',
                                                      ('var', 'dr'),
                                                      ('num', 2))))],
                                                  [('loop_if_else',
                                                    ('cond_lt',
                                                     ('imaginary',),
                                                     ('var', 'last_cell')),
                                                    [('loop_assign',
                                                      'outward_gradient',
                                                      ('mul',
                                                       ('pow',
                                                        ('add',
                                                         ('imaginary',),
                                                         ('num', 1)),
                                                        ('num', 2)),
                                                       ('sub',
                                                        ('index',
                                                         'c',
                                                         ('add',
                                                          ('imaginary',),
                                                          ('num', 1))),
                                                        ('index',
                                                         'c',
                                                         ('imaginary',))))),
                                                     ('loop_assign',
                                                      'inward_gradient',
                                                      ('mul',
                                                       ('pow',
                                                        ('imaginary',),
                                                        ('num', 2)),
                                                       ('sub',
                                                        ('index',
                                                         'c',
                                                         ('imaginary',)),
                                                        ('index',
                                                         'c',
                                                         ('sub',
                                                          ('imaginary',),
                                                          ('num', 1)))))),
                                                     ('loop_index_assign_nd',
                                                      'dc',
                                                      [('imaginary',)],
                                                      ('div',
                                                       ('mul',
                                                        ('mul',
                                                         ('num', 3.0),
                                                         ('var',
                                                          'diffusivity')),
                                                        ('sub',
                                                         ('var',
                                                          'outward_gradient'),
                                                         ('var',
                                                          'inward_gradient'))),
                                                       ('mul',
                                                        ('pow',
                                                         ('var', 'dr'),
                                                         ('num', 2)),
                                                        ('var',
                                                         'shell_volume_factor'))))],
                                                    [('loop_assign',
                                                      'diffusion_in',
                                                      ('div',
                                                       ('mul',
                                                        ('mul',
                                                         ('pow',
                                                          ('imaginary',),
                                                          ('num', 2)),
                                                         ('var',
                                                          'diffusivity')),
                                                        ('sub',
                                                         ('index',
                                                          'c',
                                                          ('imaginary',)),
                                                         ('index',
                                                          'c',
                                                          ('sub',
                                                           ('imaginary',),
                                                           ('num', 1))))),
                                                       ('var', 'dr'))),
                                                     ('loop_index_assign_nd',
                                                      'dc',
                                                      [('imaginary',)],
                                                      ('div',
                                                       ('mul',
                                                        ('num', 3.0),
                                                        ('sub',
                                                         ('mul',
                                                          ('neg',
                                                           ('pow',
                                                            ('add',
                                                             ('imaginary',),
                                                             ('num', 1)),
                                                            ('num', 2))),
                                                          ('var', 'j_out')),
                                                         ('var',
                                                          'diffusion_in'))),
                                                       ('mul',
                                                        ('var', 'dr'),
                                                        ('var',
                                                         'shell_volume_factor'))))])])])]},
               'rk4_particle': {'params': [('c',
                                            ('tensor', [('m', 'invariant')])),
                                           ('radius', 'ℝ'),
                                           ('diffusivity', 'ℝ'),
                                           ('j_out', 'ℝ'),
                                           ('Δt', 'ℝ')],
                                'return_type': ('tensor', [('m', 'invariant')]),
                                'body': ('add',
                                         ('var', 'c'),
                                         ('div',
                                          ('mul',
                                           ('var', 'Δt'),
                                           ('add',
                                            ('add',
                                             ('add',
                                              ('var', 'k1'),
                                              ('mul',
                                               ('num', 2.0),
                                               ('var', 'k2'))),
                                             ('mul',
                                              ('num', 2.0),
                                              ('var', 'k3'))),
                                            ('var', 'k4'))),
                                          ('num', 6.0))),
                                'has_loop': False,
                                'statements': [('body_decl',
                                                'k1',
                                                ('tensor',
                                                 [('nr', 'invariant')]),
                                                ('call',
                                                 'particle_rhs',
                                                 [('var', 'c'),
                                                  ('var', 'radius'),
                                                  ('var', 'diffusivity'),
                                                  ('var', 'j_out')])),
                                               ('body_decl',
                                                'k2',
                                                ('tensor',
                                                 [('nr', 'invariant')]),
                                                ('call',
                                                 'particle_rhs',
                                                 [('add',
                                                   ('var', 'c'),
                                                   ('mul',
                                                    ('mul',
                                                     ('num', 0.5),
                                                     ('var', 'Δt')),
                                                    ('var', 'k1'))),
                                                  ('var', 'radius'),
                                                  ('var', 'diffusivity'),
                                                  ('var', 'j_out')])),
                                               ('body_decl',
                                                'k3',
                                                ('tensor',
                                                 [('nr', 'invariant')]),
                                                ('call',
                                                 'particle_rhs',
                                                 [('add',
                                                   ('var', 'c'),
                                                   ('mul',
                                                    ('mul',
                                                     ('num', 0.5),
                                                     ('var', 'Δt')),
                                                    ('var', 'k2'))),
                                                  ('var', 'radius'),
                                                  ('var', 'diffusivity'),
                                                  ('var', 'j_out')])),
                                               ('body_decl',
                                                'k4',
                                                ('tensor',
                                                 [('nr', 'invariant')]),
                                                ('call',
                                                 'particle_rhs',
                                                 [('add',
                                                   ('var', 'c'),
                                                   ('mul',
                                                    ('var', 'Δt'),
                                                    ('var', 'k3'))),
                                                  ('var', 'radius'),
                                                  ('var', 'diffusivity'),
                                                  ('var', 'j_out')]))]},
               'terminal_voltage': {'params': [('c_n',
                                                ('tensor',
                                                 [('m', 'invariant')])),
                                               ('c_p',
                                                ('tensor',
                                                 [('m', 'invariant')])),
                                               ('ε_s_p', 'ℝ'),
                                               ('current', 'ℝ')],
                                    'return_type': 'ℝ',
                                    'body': ('sub',
                                             ('sub',
                                              ('add',
                                               ('sub',
                                                ('call',
                                                 'ocp_positive',
                                                 [('var', 'θ_p')]),
                                                ('call',
                                                 'ocp_negative',
                                                 [('var', 'θ_n')])),
                                               ('var', 'η_p')),
                                              ('var', 'η_n')),
                                             ('mul',
                                              ('var', 'current'),
                                              ('var', 'contact_resistance'))),
                                    'has_loop': False,
                                    'statements': [('body_decl',
                                                    'c_ns',
                                                    'ℝ',
                                                    ('call',
                                                     'clip_concentration',
                                                     [('index',
                                                       'c_n',
                                                       ('sub',
                                                        ('var', 'nr'),
                                                        ('num', 1))),
                                                      ('var', 'c_n_max')])),
                                                   ('body_decl',
                                                    'c_ps',
                                                    'ℝ',
                                                    ('call',
                                                     'clip_concentration',
                                                     [('index',
                                                       'c_p',
                                                       ('sub',
                                                        ('var', 'nr'),
                                                        ('num', 1))),
                                                      ('var', 'c_p_max')])),
                                                   ('body_decl',
                                                    'θ_n',
                                                    'ℝ',
                                                    ('div',
                                                     ('var', 'c_ns'),
                                                     ('var', 'c_n_max'))),
                                                   ('body_decl',
                                                    'θ_p',
                                                    'ℝ',
                                                    ('div',
                                                     ('var', 'c_ps'),
                                                     ('var', 'c_p_max'))),
                                                   ('body_decl',
                                                    'j_n',
                                                    'ℝ',
                                                    ('call',
                                                     'negative_surface_flux',
                                                     [('var', 'current')])),
                                                   ('body_decl',
                                                    'j_p',
                                                    'ℝ',
                                                    ('call',
                                                     'positive_surface_flux',
                                                     [('var', 'current'),
                                                      ('var', 'ε_s_p')])),
                                                   ('body_decl',
                                                    'i0_n',
                                                    'ℝ',
                                                    ('call',
                                                     'exchange_current',
                                                     [('var', 'c_ns'),
                                                      ('var', 'c_n_max'),
                                                      ('var', 'k0_n')])),
                                                   ('body_decl',
                                                    'i0_p',
                                                    'ℝ',
                                                    ('call',
                                                     'exchange_current',
                                                     [('var', 'c_ps'),
                                                      ('var', 'c_p_max'),
                                                      ('var', 'k0_p')])),
                                                   ('body_decl',
                                                    'η_n',
                                                    'ℝ',
                                                    ('call',
                                                     'bv_overpotential',
                                                     [('mul',
                                                       ('var', 'faraday'),
                                                       ('var', 'j_n')),
                                                      ('var', 'i0_n')])),
                                                   ('body_decl',
                                                    'η_p',
                                                    'ℝ',
                                                    ('call',
                                                     'bv_overpotential',
                                                     [('mul',
                                                       ('var', 'faraday'),
                                                       ('var', 'j_p')),
                                                      ('var', 'i0_p')]))]},
               'spm_solver': {'params': [('ε_s_p', 'ℝ'),
                                         ('c_rate', 'ℝ'),
                                         ('substeps_per_sample', 'ℕ'),
                                         ('Δt', 'ℝ')],
                              'return_type': ('tensor', [('m', 'invariant')]),
                              'body': ('var', 'voltage'),
                              'has_loop': False,
                              'statements': [('body_decl',
                                              'c_n',
                                              ('tensor', [('nr', 'invariant')]),
                                              ('array',
                                               [('var', 'c_n_initial'),
                                                ('var', 'c_n_initial'),
                                                ('var', 'c_n_initial'),
                                                ('var', 'c_n_initial'),
                                                ('var', 'c_n_initial')])),
                                             ('body_decl',
                                              'c_p',
                                              ('tensor', [('nr', 'invariant')]),
                                              ('array',
                                               [('var', 'c_p_initial'),
                                                ('var', 'c_p_initial'),
                                                ('var', 'c_p_initial'),
                                                ('var', 'c_p_initial'),
                                                ('var', 'c_p_initial')])),
                                             ('body_decl',
                                              'voltage',
                                              ('tensor',
                                               [('num_samples', 'invariant')]),
                                              ('call',
                                               'zero_1d_array',
                                               [('var', 'num_samples')])),
                                             ('body_decl',
                                              'current',
                                              'ℝ',
                                              ('mul',
                                               ('var', 'c_rate'),
                                               ('var', 'nominal_capacity_ah'))),
                                             ('body_decl',
                                              'j_n',
                                              'ℝ',
                                              ('call',
                                               'negative_surface_flux',
                                               [('var', 'current')])),
                                             ('body_decl',
                                              'j_p',
                                              'ℝ',
                                              ('call',
                                               'positive_surface_flux',
                                               [('var', 'current'),
                                                ('var', 'ε_s_p')])),
                                             ('body_index_assign',
                                              'voltage',
                                              ('num', 0),
                                              ('call',
                                               'terminal_voltage',
                                               [('var', 'c_n'),
                                                ('var', 'c_p'),
                                                ('var', 'ε_s_p'),
                                                ('var', 'current')])),
                                             ('body_for_range',
                                              'sample',
                                              ('num', 0),
                                              ('sub',
                                               ('var', 'num_samples'),
                                               ('num', 1)),
                                              [('loop_for_range',
                                                'substep',
                                                ('num', 0),
                                                ('var', 'substeps_per_sample'),
                                                [('loop_assign',
                                                  'c_n',
                                                  ('call',
                                                   'rk4_particle',
                                                   [('var', 'c_n'),
                                                    ('var', 'radius_n'),
                                                    ('var', 'diffusivity_n'),
                                                    ('var', 'j_n'),
                                                    ('var', 'Δt')])),
                                                 ('loop_assign',
                                                  'c_p',
                                                  ('call',
                                                   'rk4_particle',
                                                   [('var', 'c_p'),
                                                    ('var', 'radius_p'),
                                                    ('var', 'diffusivity_p'),
                                                    ('var', 'j_p'),
                                                    ('var', 'Δt')]))]),
                                               ('loop_index_assign_nd',
                                                'voltage',
                                                [('add',
                                                  ('var', 'sample'),
                                                  ('num', 1))],
                                                ('call',
                                                 'terminal_voltage',
                                                 [('var', 'c_n'),
                                                  ('var', 'c_p'),
                                                  ('var', 'ε_s_p'),
                                                  ('var', 'current')]))])]},
               'validation_protocol_solver': {'params': [('ε_s_p', 'ℝ'),
                                                         ('Δt', 'ℝ')],
                                              'return_type': ('tensor',
                                                              [('m',
                                                                'invariant')]),
                                              'body': ('var', 'voltage'),
                                              'has_loop': False,
                                              'statements': [('body_decl',
                                                              'c_n',
                                                              ('tensor',
                                                               [('nr',
                                                                 'invariant')]),
                                                              ('array',
                                                               [('var',
                                                                 'c_n_initial'),
                                                                ('var',
                                                                 'c_n_initial'),
                                                                ('var',
                                                                 'c_n_initial'),
                                                                ('var',
                                                                 'c_n_initial'),
                                                                ('var',
                                                                 'c_n_initial')])),
                                                             ('body_decl',
                                                              'c_p',
                                                              ('tensor',
                                                               [('nr',
                                                                 'invariant')]),
                                                              ('array',
                                                               [('var',
                                                                 'c_p_initial'),
                                                                ('var',
                                                                 'c_p_initial'),
                                                                ('var',
                                                                 'c_p_initial'),
                                                                ('var',
                                                                 'c_p_initial'),
                                                                ('var',
                                                                 'c_p_initial')])),
                                                             ('body_decl',
                                                              'voltage',
                                                              ('tensor',
                                                               [('validation_num_samples',
                                                                 'invariant')]),
                                                              ('call',
                                                               'zero_1d_array',
                                                               [('var',
                                                                 'validation_num_samples')])),
                                                             ('body_decl',
                                                              'current',
                                                              'ℝ',
                                                              ('index',
                                                               'validation_current_a',
                                                               ('num', 0))),
                                                             ('body_decl',
                                                              'j_n',
                                                              'ℝ',
                                                              ('call',
                                                               'negative_surface_flux',
                                                               [('var',
                                                                 'current')])),
                                                             ('body_decl',
                                                              'j_p',
                                                              'ℝ',
                                                              ('call',
                                                               'positive_surface_flux',
                                                               [('var',
                                                                 'current'),
                                                                ('var',
                                                                 'ε_s_p')])),
                                                             ('body_decl',
                                                              'first_transition',
                                                              'ℕ',
                                                              ('num', 8)),
                                                             ('body_decl',
                                                              'second_transition',
                                                              'ℕ',
                                                              ('num', 17)),
                                                             ('body_index_assign',
                                                              'voltage',
                                                              ('num', 0),
                                                              ('call',
                                                               'terminal_voltage',
                                                               [('var', 'c_n'),
                                                                ('var', 'c_p'),
                                                                ('var',
                                                                 'ε_s_p'),
                                                                ('var',
                                                                 'current')])),
                                                             ('body_for_range',
                                                              'sample',
                                                              ('num', 0),
                                                              ('sub',
                                                               ('var',
                                                                'validation_num_samples'),
                                                               ('num', 1)),
                                                              [('loop_assign',
                                                                'current',
                                                                ('index',
                                                                 'validation_current_a',
                                                                 ('add',
                                                                  ('var',
                                                                   'sample'),
                                                                  ('num', 1)))),
                                                               ('loop_assign',
                                                                'j_n',
                                                                ('call',
                                                                 'negative_surface_flux',
                                                                 [('var',
                                                                   'current')])),
                                                               ('loop_assign',
                                                                'j_p',
                                                                ('call',
                                                                 'positive_surface_flux',
                                                                 [('var',
                                                                   'current'),
                                                                  ('var',
                                                                   'ε_s_p')])),
                                                               ('loop_if',
                                                                ('cond_neq',
                                                                 ('var',
                                                                  'sample'),
                                                                 ('var',
                                                                  'first_transition')),
                                                                [('loop_if',
                                                                  ('cond_neq',
                                                                   ('var',
                                                                    'sample'),
                                                                   ('var',
                                                                    'second_transition')),
                                                                  [('loop_for_range',
                                                                    'substep',
                                                                    ('num', 0),
                                                                    ('var',
                                                                     'validation_substeps_per_sample'),
                                                                    [('loop_assign',
                                                                      'c_n',
                                                                      ('call',
                                                                       'rk4_particle',
                                                                       [('var',
                                                                         'c_n'),
                                                                        ('var',
                                                                         'radius_n'),
                                                                        ('var',
                                                                         'diffusivity_n'),
                                                                        ('var',
                                                                         'j_n'),
                                                                        ('var',
                                                                         'Δt')])),
                                                                     ('loop_assign',
                                                                      'c_p',
                                                                      ('call',
                                                                       'rk4_particle',
                                                                       [('var',
                                                                         'c_p'),
                                                                        ('var',
                                                                         'radius_p'),
                                                                        ('var',
                                                                         'diffusivity_p'),
                                                                        ('var',
                                                                         'j_p'),
                                                                        ('var',
                                                                         'Δt')]))])])]),
                                                               ('loop_index_assign_nd',
                                                                'voltage',
                                                                [('add',
                                                                  ('var',
                                                                   'sample'),
                                                                  ('num', 1))],
                                                                ('call',
                                                                 'terminal_voltage',
                                                                 [('var',
                                                                   'c_n'),
                                                                  ('var',
                                                                   'c_p'),
                                                                  ('var',
                                                                   'ε_s_p'),
                                                                  ('var',
                                                                   'current')]))])]},
               'rmse': {'params': [('a', ('tensor', [('m', 'invariant')])),
                                   ('b', ('tensor', [('n', 'invariant')]))],
                        'return_type': 'ℝ',
                        'body': ('call',
                                 'sqrt',
                                 [('div', ('var', 'loss'), ('var', 'n'))]),
                        'has_loop': False,
                        'statements': [('body_decl', 'loss', 'ℝ', ('num', 0.0)),
                                       ('body_decl',
                                        'n',
                                        'ℝ',
                                        ('call',
                                         'get_1d_array_length',
                                         [('var', 'a')])),
                                       ('body_for_range',
                                        'i',
                                        ('num', 0),
                                        ('var', 'n'),
                                        [('loop_pluseq',
                                          'loss',
                                          ('pow',
                                           ('sub',
                                            ('index', 'a', ('imaginary',)),
                                            ('index', 'b', ('imaginary',))),
                                           ('num', 2)))])]},
               'calculate_loss': {'params': [('ε_fit', 'ℝ')],
                                  'return_type': 'ℝ',
                                  'body': ('call',
                                           'mean',
                                           [('pow',
                                             ('sub',
                                              ('var', 'predicted'),
                                              ('var', 'dfn_train_voltage')),
                                             ('num', 2))]),
                                  'has_loop': False,
                                  'statements': [('body_decl',
                                                  'predicted',
                                                  ('tensor',
                                                   [('m', 'invariant')]),
                                                  ('call',
                                                   'spm_solver',
                                                   [('var', 'ε_fit'),
                                                    ('var', 'train_c_rate'),
                                                    ('var',
                                                     'train_substeps_per_sample'),
                                                    ('var', 'Δt')]))]}},
 'classes': {},
 'program': [('func_def', 'zero_1d_array'),
             ('func_def', 'get_1d_array_length'),
             ('func_def', 'clip_stoichiometry'),
             ('func_def', 'clip_concentration'),
             ('func_def', 'tanh_scalar'),
             ('func_def', 'ocp_negative'),
             ('func_def', 'ocp_positive'),
             ('func_def', 'exchange_current'),
             ('func_def', 'asinh_scalar'),
             ('func_def', 'bv_overpotential'),
             ('func_def', 'negative_surface_flux'),
             ('func_def', 'positive_surface_flux'),
             ('func_def', 'particle_rhs'),
             ('func_def', 'rk4_particle'),
             ('func_def', 'terminal_voltage'),
             ('func_def', 'spm_solver'),
             ('func_def', 'validation_protocol_solver'),
             ('func_def', 'rmse'),
             ('decl', 'faraday', 'ℝ', ('num', 96485.33212), 169),
             ('decl', 'gas_constant', 'ℝ', ('num', 8.31446261815324), 170),
             ('decl', 'temperature', 'ℝ', ('num', 298.15), 171),
             ('decl', 'c_e', 'ℝ', ('num', 1000.0), 172),
             ('decl', 'electrode_area', 'ℝ', ('num', 0.1027), 173),
             ('decl', 'nominal_capacity_ah', 'ℝ', ('num', 5.0), 174),
             ('decl', 'contact_resistance', 'ℝ', ('num', 0.0), 175),
             ('decl', 'thickness_n', 'ℝ', ('num', 8.52e-05), 177),
             ('decl', 'thickness_p', 'ℝ', ('num', 7.56e-05), 178),
             ('decl', 'radius_n', 'ℝ', ('num', 5.86e-06), 179),
             ('decl', 'radius_p', 'ℝ', ('num', 5.22e-06), 180),
             ('decl', 'diffusivity_n', 'ℝ', ('num', 3.3e-14), 181),
             ('decl', 'diffusivity_p', 'ℝ', ('num', 4e-15), 182),
             ('decl', 'ε_s_n', 'ℝ', ('num', 0.75), 183),
             ('decl', 'c_n_initial', 'ℝ', ('num', 29866.0), 184),
             ('decl', 'c_p_initial', 'ℝ', ('num', 17038.0), 185),
             ('decl', 'c_n_max', 'ℝ', ('num', 33133.0), 186),
             ('decl', 'c_p_max', 'ℝ', ('num', 63104.0), 187),
             ('decl', 'k0_n', 'ℝ', ('num', 6.48e-07), 188),
             ('decl', 'k0_p', 'ℝ', ('num', 3.42e-06), 189),
             ('decl', 'nr', 'ℕ', ('num', 5), 191),
             ('decl', 'num_samples', 'ℕ', ('num', 21), 192),
             ('decl', 'train_c_rate', 'ℝ', ('num', 0.1), 193),
             ('decl', 'train_substeps_per_sample', 'ℕ', ('num', 90), 194),
             ('decl', 'Δt', 'ℝ', ('num', 20.0), 195),
             ('decl', 'validation_num_samples', 'ℕ', ('num', 27), 200),
             ('decl', 'validation_substeps_per_sample', 'ℕ', ('num', 45), 201),
             ('decl',
              'validation_time_h',
              ('tensor', [(27, 'invariant')]),
              ('array',
               [('num', 0.0),
                ('num', 0.25),
                ('num', 0.5),
                ('num', 0.75),
                ('num', 1.0),
                ('num', 1.25),
                ('num', 1.5),
                ('num', 1.75),
                ('num', 2.0),
                ('num', 2.0),
                ('num', 2.25),
                ('num', 2.5),
                ('num', 2.75),
                ('num', 3.0),
                ('num', 3.25),
                ('num', 3.5),
                ('num', 3.75),
                ('num', 4.0),
                ('num', 4.0),
                ('num', 4.25),
                ('num', 4.5),
                ('num', 4.75),
                ('num', 5.0),
                ('num', 5.25),
                ('num', 5.5),
                ('num', 5.75),
                ('num', 6.0)]),
              202),
             ('decl',
              'validation_c_rate_profile',
              ('tensor', [(27, 'invariant')]),
              ('array',
               [('num', 0.2),
                ('num', 0.2),
                ('num', 0.2),
                ('num', 0.2),
                ('num', 0.2),
                ('num', 0.2),
                ('num', 0.2),
                ('num', 0.2),
                ('num', 0.2),
                ('num', 0.0),
                ('num', 0.0),
                ('num', 0.0),
                ('num', 0.0),
                ('num', 0.0),
                ('num', 0.0),
                ('num', 0.0),
                ('num', 0.0),
                ('num', 0.0),
                ('num', 0.05),
                ('num', 0.05),
                ('num', 0.05),
                ('num', 0.05),
                ('num', 0.05),
                ('num', 0.05),
                ('num', 0.05),
                ('num', 0.05),
                ('num', 0.05)]),
              203),
             ('decl',
              'validation_current_a',
              ('tensor', [(27, 'invariant')]),
              ('mul',
               ('var', 'validation_c_rate_profile'),
               ('var', 'nominal_capacity_ah')),
              204),
             ('decl',
              'dfn_train_voltage',
              ('tensor', [(21, 'invariant')]),
              ('array',
               [('num', 4.158395248),
                ('num', 4.084192602),
                ('num', 4.071392813),
                ('num', 4.049195473),
                ('num', 4.006860924),
                ('num', 3.961241395),
                ('num', 3.916527071),
                ('num', 3.86177453),
                ('num', 3.814408034),
                ('num', 3.772015162),
                ('num', 3.725484224),
                ('num', 3.682248062),
                ('num', 3.645685812),
                ('num', 3.609974847),
                ('num', 3.565901908),
                ('num', 3.513874271),
                ('num', 3.468832454),
                ('num', 3.424676253),
                ('num', 3.317194985),
                ('num', 3.146746296),
                ('num', 2.789451932)]),
              208),
             ('decl', 'initial_ε_s_p', 'ℝ', ('num', 0.3), 210),
             ('decl', 'chen2020_ε_s_p', 'ℝ', ('num', 0.665), 211),
             ('decl', 'ε_s_p', 'ℝ', ('var', 'initial_ε_s_p'), 212),
             ('func_def', 'calculate_loss'),
             ('decl', 'learning_rate', 'ℝ', ('num', 0.86), 219),
             ('decl', 'learning_rate_decay', 'ℝ', ('num', 0.25), 220),
             ('decl', 'epochs', 'ℕ', ('num', 5), 221),
             ('decl',
              'initial_train_voltage',
              ('tensor', [('m', 'invariant')]),
              ('call',
               'spm_solver',
               [('var', 'initial_ε_s_p'),
                ('var', 'train_c_rate'),
                ('var', 'train_substeps_per_sample'),
                ('var', 'Δt')]),
              223),
             ('decl',
              'initial_train_rmse',
              'ℝ',
              ('call',
               'rmse',
               [('var', 'initial_train_voltage'),
                ('var', 'dfn_train_voltage')]),
              224),
             ('decl',
              'loss_history',
              ('tensor', [(6, 'invariant')]),
              ('call',
               'zero_1d_array',
               [('add', ('var', 'epochs'), ('num', 1))]),
              225),
             ('index_assign',
              'loss_history',
              0,
              ('pow', ('var', 'initial_train_rmse'), ('num', 2)),
              226),
             ('for_loop_range',
              'epoch',
              ('num', 0),
              ('var', 'epochs'),
              [('for_assign',
                'g',
                ('call',
                 'grad',
                 [('var', 'calculate_loss'), ('var', 'ε_s_p')])),
               ('for_assign',
                'ε_s_p',
                ('sub',
                 ('var', 'ε_s_p'),
                 ('mul', ('var', 'learning_rate'), ('var', 'g')))),
               ('for_index_assign_nd',
                'loss_history',
                [('add', ('var', 'epoch'), ('num', 1))],
                ('call', 'calculate_loss', [('var', 'ε_s_p')])),
               ('for_assign',
                'learning_rate',
                ('mul',
                 ('var', 'learning_rate'),
                 ('var', 'learning_rate_decay')))],
              228),
             ('decl',
              'fitted_train_voltage',
              ('tensor', [('m', 'invariant')]),
              ('call',
               'spm_solver',
               [('var', 'ε_s_p'),
                ('var', 'train_c_rate'),
                ('var', 'train_substeps_per_sample'),
                ('var', 'Δt')]),
              234),
             ('decl',
              'fitted_train_rmse',
              'ℝ',
              ('call',
               'rmse',
               [('var', 'fitted_train_voltage'), ('var', 'dfn_train_voltage')]),
              235),
             ('decl',
              'pybamm_validation_ε_s_p',
              'ℝ',
              ('num', 0.6471111178398132),
              239),
             ('decl',
              'pybamm_validation_voltage',
              ('tensor', [(27, 'invariant')]),
              ('array',
               [('num', 4.142996394),
                ('num', 4.067772943),
                ('num', 4.057471567),
                ('num', 4.027229404),
                ('num', 3.981657244),
                ('num', 3.937880704),
                ('num', 3.895608468),
                ('num', 3.838549294),
                ('num', 3.788632364),
                ('num', 3.81322811),
                ('num', 3.833002643),
                ('num', 3.833640604),
                ('num', 3.833695039),
                ('num', 3.833696392),
                ('num', 3.833696305),
                ('num', 3.833696268),
                ('num', 3.833696266),
                ('num', 3.833696264),
                ('num', 3.827385441),
                ('num', 3.811877071),
                ('num', 3.800818412),
                ('num', 3.789583321),
                ('num', 3.778002657),
                ('num', 3.766121504),
                ('num', 3.754073902),
                ('num', 3.742039259),
                ('num', 3.730207631)]),
              240),
             ('decl',
              'validation_voltage',
              ('tensor', [('m', 'invariant')]),
              ('call',
               'validation_protocol_solver',
               [('var', 'ε_s_p'), ('var', 'Δt')]),
              241),
             ('decl',
              'validation_rmse',
              'ℝ',
              ('call',
               'rmse',
               [('var', 'validation_voltage'),
                ('var', 'pybamm_validation_voltage')]),
              242),
             ('expr', ('call', 'physika_print', [('var', 'ε_s_p')]), 0),
             ('expr',
              ('call', 'physika_print', [('var', 'initial_train_rmse')]),
              0),
             ('expr',
              ('call', 'physika_print', [('var', 'fitted_train_rmse')]),
              0),
             ('expr',
              ('call', 'physika_print', [('var', 'validation_rmse')]),
              0),
             ('expr',
              ('call', 'physika_print', [('var', 'fitted_train_voltage')]),
              0),
             ('expr',
              ('call', 'physika_print', [('var', 'validation_voltage')]),
              0),
             ('expr', ('call', 'physika_print', [('var', 'loss_history')]), 0)]}
