EXPECTED = {'functions': {'zero_1d_array': {'params': [('len', 'ℝ')],
                                 'return_type': ('tensor',
                                                 [('m', 'invariant')]),
                                 'body': ('var', 'results'),
                                 'has_loop': False,
                                 'statements': [('body_decl',
                                                 'results',
                                                 ('tensor',
                                                  [('len', 'invariant')]),
                                                 ('for_expr',
                                                  'i',
                                                  ('var', 'len'),
                                                  ('mul',
                                                   ('imaginary',),
                                                   ('num', 0))))]},
               'get_1d_array_length': {'params': [('x',
                                                   ('tensor',
                                                    [('m', 'invariant')]))],
                                       'return_type': 'ℝ',
                                       'body': ('var', 'total'),
                                       'has_loop': False,
                                       'statements': [('body_decl',
                                                       'total',
                                                       'ℝ',
                                                       ('num', 0)),
                                                      ('body_decl',
                                                       'temp',
                                                       'ℝ',
                                                       ('num', 0)),
                                                      ('body_for',
                                                       'i',
                                                       [('loop_assign',
                                                         'temp',
                                                         ('index',
                                                          'x',
                                                          ('imaginary',))),
                                                        ('loop_pluseq',
                                                         'total',
                                                         ('num', 1))],
                                                       ['x'])]},
               'append': {'params': [('x', ('tensor', [('m', 'invariant')])),
                                     ('var', 'ℝ')],
                          'return_type': ('tensor', [('n', 'invariant')]),
                          'body': ('var', 'results'),
                          'has_loop': False,
                          'statements': [('body_decl',
                                          'new_length',
                                          'ℝ',
                                          ('add',
                                           ('call', 'len', [('var', 'x')]),
                                           ('num', 1))),
                                         ('body_decl',
                                          'results',
                                          ('tensor',
                                           [('new_length', 'invariant')]),
                                          ('call',
                                           'zero_1d_array',
                                           [('var', 'new_length')])),
                                         ('body_decl',
                                          'len_x',
                                          'ℕ',
                                          ('call',
                                           'get_1d_array_length',
                                           [('var', 'x')])),
                                         ('body_for_range',
                                          'i',
                                          ('num', 0),
                                          ('var', 'new_length'),
                                          [('loop_if_else',
                                            ('cond_lt',
                                             ('imaginary',),
                                             ('var', 'len_x')),
                                            [('loop_index_assign_nd',
                                              'results',
                                              [('index_item', ('imaginary',))],
                                              ('index', 'x', ('imaginary',)))],
                                            [('loop_index_assign_nd',
                                              'results',
                                              [('index_item', ('imaginary',))],
                                              ('var', 'var'))])])]},
               'f': {'params': [('state', ('tensor', [(4, 'invariant')])),
                                ('θ', ('tensor', [(2, 'invariant')]))],
                     'return_type': ('tensor', [(4, 'invariant')]),
                     'body': ('array',
                              [('var', 'du1'),
                               ('var', 'dv1'),
                               ('var', 'du2'),
                               ('var', 'dv2')]),
                     'has_loop': False,
                     'statements': [('body_decl',
                                     'u1',
                                     'ℝ',
                                     ('index', 'state', ('num', 0))),
                                    ('body_decl',
                                     'v1',
                                     'ℝ',
                                     ('index', 'state', ('num', 1))),
                                    ('body_decl',
                                     'u2',
                                     'ℝ',
                                     ('index', 'state', ('num', 2))),
                                    ('body_decl',
                                     'v2',
                                     'ℝ',
                                     ('index', 'state', ('num', 3))),
                                    ('body_decl',
                                     'a1',
                                     'ℝ',
                                     ('index', 'θ', ('num', 0))),
                                    ('body_decl',
                                     'a2',
                                     'ℝ',
                                     ('index', 'θ', ('num', 1))),
                                    ('body_decl',
                                     'du1',
                                     'ℝ',
                                     ('sub',
                                      ('div',
                                       ('var', 'a1'),
                                       ('add',
                                        ('num', 1.0),
                                        ('pow', ('var', 'v1'), ('num', 2)))),
                                      ('var', 'u1'))),
                                    ('body_decl',
                                     'dv1',
                                     'ℝ',
                                     ('sub',
                                      ('div',
                                       ('var', 'a2'),
                                       ('add',
                                        ('num', 1.0),
                                        ('pow', ('var', 'u1'), ('num', 2)))),
                                      ('var', 'v1'))),
                                    ('body_decl',
                                     'du2',
                                     'ℝ',
                                     ('sub',
                                      ('div',
                                       ('var', 'a1'),
                                       ('add',
                                        ('num', 1.0),
                                        ('pow', ('var', 'v2'), ('num', 2)))),
                                      ('var', 'u2'))),
                                    ('body_decl',
                                     'dv2',
                                     'ℝ',
                                     ('sub',
                                      ('div',
                                       ('var', 'a2'),
                                       ('add',
                                        ('num', 1.0),
                                        ('pow', ('var', 'u2'), ('num', 2)))),
                                      ('var', 'v2')))]},
               'rk4_step': {'params': [('state',
                                        ('tensor', [(4, 'invariant')])),
                                       ('θ', ('tensor', [(2, 'invariant')]))],
                            'return_type': ('tensor', [(4, 'invariant')]),
                            'body': ('add',
                                     ('var', 'state'),
                                     ('mul',
                                      ('div', ('var', 'dt'), ('num', 6.0)),
                                      ('add',
                                       ('add',
                                        ('add',
                                         ('var', 'k1'),
                                         ('mul', ('num', 2.0), ('var', 'k2'))),
                                        ('mul', ('num', 2.0), ('var', 'k3'))),
                                       ('var', 'k4')))),
                            'has_loop': False,
                            'statements': [('body_decl',
                                            'k1',
                                            ('tensor', [(4, 'invariant')]),
                                            ('call',
                                             'f',
                                             [('var', 'state'), ('var', 'θ')])),
                                           ('body_decl',
                                            'k2_state',
                                            ('tensor', [(4, 'invariant')]),
                                            ('add',
                                             ('var', 'state'),
                                             ('mul',
                                              ('mul',
                                               ('num', 0.5),
                                               ('var', 'dt')),
                                              ('var', 'k1')))),
                                           ('body_decl',
                                            'k2',
                                            ('tensor', [(4, 'invariant')]),
                                            ('call',
                                             'f',
                                             [('var', 'k2_state'),
                                              ('var', 'θ')])),
                                           ('body_decl',
                                            'k3_state',
                                            ('tensor', [(4, 'invariant')]),
                                            ('add',
                                             ('var', 'state'),
                                             ('mul',
                                              ('mul',
                                               ('num', 0.5),
                                               ('var', 'dt')),
                                              ('var', 'k2')))),
                                           ('body_decl',
                                            'k3',
                                            ('tensor', [(4, 'invariant')]),
                                            ('call',
                                             'f',
                                             [('var', 'k3_state'),
                                              ('var', 'θ')])),
                                           ('body_decl',
                                            'k4_state',
                                            ('tensor', [(4, 'invariant')]),
                                            ('add',
                                             ('var', 'state'),
                                             ('mul',
                                              ('var', 'dt'),
                                              ('var', 'k3')))),
                                           ('body_decl',
                                            'k4',
                                            ('tensor', [(4, 'invariant')]),
                                            ('call',
                                             'f',
                                             [('var', 'k4_state'),
                                              ('var', 'θ')]))]},
               'solver': {'params': [('θ', ('tensor', [(2, 'invariant')]))],
                          'return_type': ('tensor',
                                          [(4, 'invariant'),
                                           ('m', 'invariant')]),
                          'body': ('array',
                                   [('var', 'u1_array'),
                                    ('var', 'v1_array'),
                                    ('var', 'u2_array'),
                                    ('var', 'v2_array')]),
                          'has_loop': False,
                          'statements': [('body_decl',
                                          'state',
                                          ('tensor', [(4, 'invariant')]),
                                          ('array',
                                           [('num', 2.0),
                                            ('num', 0.1),
                                            ('num', 0.1),
                                            ('num', 2.0)])),
                                         ('body_decl',
                                          'u1_array',
                                          ('tensor', [(1, 'invariant')]),
                                          ('array', [('num', 2.0)])),
                                         ('body_decl',
                                          'v1_array',
                                          ('tensor', [(1, 'invariant')]),
                                          ('array', [('num', 0.1)])),
                                         ('body_decl',
                                          'u2_array',
                                          ('tensor', [(1, 'invariant')]),
                                          ('array', [('num', 0.1)])),
                                         ('body_decl',
                                          'v2_array',
                                          ('tensor', [(1, 'invariant')]),
                                          ('array', [('num', 2.0)])),
                                         ('body_for_range',
                                          'i',
                                          ('num', 0),
                                          ('var', 'timesteps'),
                                          [('loop_assign',
                                            'results',
                                            ('call',
                                             'rk4_step',
                                             [('var', 'state'), ('var', 'θ')])),
                                           ('loop_assign',
                                            'u1',
                                            ('index', 'results', ('num', 0))),
                                           ('loop_assign',
                                            'v1',
                                            ('index', 'results', ('num', 1))),
                                           ('loop_assign',
                                            'u2',
                                            ('index', 'results', ('num', 2))),
                                           ('loop_assign',
                                            'v2',
                                            ('index', 'results', ('num', 3))),
                                           ('loop_assign',
                                            'u1_array',
                                            ('call',
                                             'append',
                                             [('var', 'u1_array'),
                                              ('var', 'u1')])),
                                           ('loop_assign',
                                            'v1_array',
                                            ('call',
                                             'append',
                                             [('var', 'v1_array'),
                                              ('var', 'v1')])),
                                           ('loop_assign',
                                            'u2_array',
                                            ('call',
                                             'append',
                                             [('var', 'u2_array'),
                                              ('var', 'u2')])),
                                           ('loop_assign',
                                            'v2_array',
                                            ('call',
                                             'append',
                                             [('var', 'v2_array'),
                                              ('var', 'v2')])),
                                           ('loop_assign',
                                            'state',
                                            ('var', 'results'))])]},
               'adjoint_grad': {'params': [('θ',
                                            ('tensor', [(2, 'invariant')]))],
                                'return_type': ('tensor', [('n', 'invariant')]),
                                'body': ('var', 'L'),
                                'has_loop': False,
                                'statements': [('body_decl',
                                                'states',
                                                ('tensor',
                                                 [(4, 'invariant'),
                                                  ('m', 'invariant')]),
                                                ('call',
                                                 'solver',
                                                 [('var', 'θ')])),
                                               ('body_decl',
                                                'u1_array',
                                                ('tensor',
                                                 [('m', 'invariant')]),
                                                ('index',
                                                 'states',
                                                 ('num', 0))),
                                               ('body_decl',
                                                'v1_array',
                                                ('tensor',
                                                 [('m', 'invariant')]),
                                                ('index',
                                                 'states',
                                                 ('num', 1))),
                                               ('body_decl',
                                                'u2_array',
                                                ('tensor',
                                                 [('m', 'invariant')]),
                                                ('index',
                                                 'states',
                                                 ('num', 2))),
                                               ('body_decl',
                                                'v2_array',
                                                ('tensor',
                                                 [('m', 'invariant')]),
                                                ('index',
                                                 'states',
                                                 ('num', 3))),
                                               ('body_decl',
                                                'm',
                                                'ℝ',
                                                ('call',
                                                 'get_1d_array_length',
                                                 [('var', 'u1_array')])),
                                               ('body_decl',
                                                's',
                                                ('tensor', [(4, 'invariant')]),
                                                ('array',
                                                 [('div',
                                                   ('sub',
                                                    ('index',
                                                     'u1_array',
                                                     ('sub',
                                                      ('var', 'm'),
                                                      ('num', 1))),
                                                    ('index',
                                                     'true_u1',
                                                     ('sub',
                                                      ('var', 'm'),
                                                      ('num', 1)))),
                                                   ('var', 'm')),
                                                  ('div',
                                                   ('sub',
                                                    ('index',
                                                     'v1_array',
                                                     ('sub',
                                                      ('var', 'm'),
                                                      ('num', 1))),
                                                    ('index',
                                                     'true_v1',
                                                     ('sub',
                                                      ('var', 'm'),
                                                      ('num', 1)))),
                                                   ('var', 'm')),
                                                  ('div',
                                                   ('sub',
                                                    ('index',
                                                     'u2_array',
                                                     ('sub',
                                                      ('var', 'm'),
                                                      ('num', 1))),
                                                    ('index',
                                                     'true_u2',
                                                     ('sub',
                                                      ('var', 'm'),
                                                      ('num', 1)))),
                                                   ('var', 'm')),
                                                  ('div',
                                                   ('sub',
                                                    ('index',
                                                     'v2_array',
                                                     ('sub',
                                                      ('var', 'm'),
                                                      ('num', 1))),
                                                    ('index',
                                                     'true_v2',
                                                     ('sub',
                                                      ('var', 'm'),
                                                      ('num', 1)))),
                                                   ('var', 'm'))])),
                                               ('body_decl',
                                                'L',
                                                ('tensor', [(2, 'invariant')]),
                                                ('call',
                                                 'zero_1d_array',
                                                 [('num', 2)])),
                                               ('body_for_range',
                                                'i',
                                                ('num', 0),
                                                ('sub',
                                                 ('var', 'm'),
                                                 ('num', 1)),
                                                [('loop_assign',
                                                  'idx',
                                                  ('sub',
                                                   ('sub',
                                                    ('var', 'm'),
                                                    ('num', 2)),
                                                   ('imaginary',))),
                                                 ('loop_assign',
                                                  'u1',
                                                  ('index',
                                                   'u1_array',
                                                   ('var', 'idx'))),
                                                 ('loop_assign',
                                                  'v1',
                                                  ('index',
                                                   'v1_array',
                                                   ('var', 'idx'))),
                                                 ('loop_assign',
                                                  'u2',
                                                  ('index',
                                                   'u2_array',
                                                   ('var', 'idx'))),
                                                 ('loop_assign',
                                                  'v2',
                                                  ('index',
                                                   'v2_array',
                                                   ('var', 'idx'))),
                                                 ('loop_assign',
                                                  'state',
                                                  ('array',
                                                   [('var', 'u1'),
                                                    ('var', 'v1'),
                                                    ('var', 'u2'),
                                                    ('var', 'v2')])),
                                                 ('loop_assign',
                                                  'J_state',
                                                  ('call',
                                                   'grad',
                                                   [('call',
                                                     'rk4_step',
                                                     [('var', 'state'),
                                                      ('var', 'θ')]),
                                                    ('var', 'state')])),
                                                 ('loop_assign',
                                                  'J_theta',
                                                  ('call',
                                                   'grad',
                                                   [('call',
                                                     'rk4_step',
                                                     [('var', 'state'),
                                                      ('var', 'θ')]),
                                                    ('var', 'θ')])),
                                                 ('loop_pluseq',
                                                  'L',
                                                  ('matmul',
                                                   ('var', 's'),
                                                   ('var', 'J_theta'))),
                                                 ('loop_assign',
                                                  'r1',
                                                  ('div',
                                                   ('sub',
                                                    ('index',
                                                     'u1_array',
                                                     ('var', 'idx')),
                                                    ('index',
                                                     'true_u1',
                                                     ('var', 'idx'))),
                                                   ('var', 'm'))),
                                                 ('loop_assign',
                                                  'r2',
                                                  ('div',
                                                   ('sub',
                                                    ('index',
                                                     'v1_array',
                                                     ('var', 'idx')),
                                                    ('index',
                                                     'true_v1',
                                                     ('var', 'idx'))),
                                                   ('var', 'm'))),
                                                 ('loop_assign',
                                                  'r3',
                                                  ('div',
                                                   ('sub',
                                                    ('index',
                                                     'u2_array',
                                                     ('var', 'idx')),
                                                    ('index',
                                                     'true_u2',
                                                     ('var', 'idx'))),
                                                   ('var', 'm'))),
                                                 ('loop_assign',
                                                  'r4',
                                                  ('div',
                                                   ('sub',
                                                    ('index',
                                                     'v2_array',
                                                     ('var', 'idx')),
                                                    ('index',
                                                     'true_v2',
                                                     ('var', 'idx'))),
                                                   ('var', 'm'))),
                                                 ('loop_assign',
                                                  'residual',
                                                  ('array',
                                                   [('var', 'r1'),
                                                    ('var', 'r2'),
                                                    ('var', 'r3'),
                                                    ('var', 'r4')])),
                                                 ('loop_assign',
                                                  's',
                                                  ('add',
                                                   ('var', 'residual'),
                                                   ('matmul',
                                                    ('var', 's'),
                                                    ('var', 'J_state'))))])]}},
 'classes': {},
 'program': [('func_def', 'zero_1d_array'),
             ('func_def', 'get_1d_array_length'),
             ('func_def', 'append'),
             ('func_def', 'f'),
             ('func_def', 'rk4_step'),
             ('decl', 'dt', 'ℝ', ('num', 0.1), 78),
             ('decl', 'timesteps', 'ℝ', ('num', 100), 79),
             ('func_def', 'solver'),
             ('decl',
              'true_theta',
              ('tensor', [(2, 'invariant')]),
              ('array', [('num', 3.0), ('num', 3.0)]),
              100),
             ('decl',
              'true_results',
              ('tensor', [(4, 'invariant'), ('m', 'invariant')]),
              ('call', 'solver', [('var', 'true_theta')]),
              101),
             ('decl',
              'true_u1',
              ('tensor', [('m', 'invariant')]),
              ('index', 'true_results', ('num', 0)),
              102),
             ('decl',
              'true_v1',
              ('tensor', [('m', 'invariant')]),
              ('index', 'true_results', ('num', 1)),
              103),
             ('decl',
              'true_u2',
              ('tensor', [('m', 'invariant')]),
              ('index', 'true_results', ('num', 2)),
              104),
             ('decl',
              'true_v2',
              ('tensor', [('m', 'invariant')]),
              ('index', 'true_results', ('num', 3)),
              105),
             ('func_def', 'adjoint_grad'),
             ('decl',
              'θ',
              ('tensor', [(2, 'invariant')]),
              ('array', [('num', 2.0), ('num', 2.0)]),
              139),
             ('decl', 'learning_rate', 'ℝ', ('num', 1.0), 140),
             ('decl', 'epochs', 'ℕ', ('num', 1), 146),
             ('for_loop_range',
              'i',
              ('num', 0),
              ('var', 'epochs'),
              [('for_assign', 'g', ('call', 'adjoint_grad', [('var', 'θ')])),
               ('for_assign',
                'θ',
                ('sub',
                 ('var', 'θ'),
                 ('mul', ('var', 'learning_rate'), ('var', 'g'))))],
              148),
             ('assign',
              'pred_results',
              ('call', 'solver', [('var', 'θ')]),
              152)]}
