EXPECTED = {'functions': {'tanh': {'params': [('z',
                                    ('tensor',
                                     [('k', 'invariant'),
                                      ('h', 'invariant')]))],
                        'return_type': ('tensor',
                                        [('k', 'invariant'),
                                         ('h', 'invariant')]),
                        'body': ('var', 'res'),
                        'has_loop': False,
                        'statements': [('body_decl',
                                        'num',
                                        ('tensor',
                                         [('k', 'invariant'),
                                          ('h', 'invariant')]),
                                        ('sub',
                                         ('call', 'exp', [('var', 'z')]),
                                         ('call',
                                          'exp',
                                          [('neg', ('var', 'z'))]))),
                                       ('body_decl',
                                        'denom',
                                        ('tensor',
                                         [('k', 'invariant'),
                                          ('h', 'invariant')]),
                                        ('add',
                                         ('call', 'exp', [('var', 'z')]),
                                         ('call',
                                          'exp',
                                          [('neg', ('var', 'z'))]))),
                                       ('body_decl',
                                        'res',
                                        ('tensor',
                                         [('k', 'invariant'),
                                          ('h', 'invariant')]),
                                        ('div',
                                         ('var', 'num'),
                                         ('var', 'denom')))]},
               'sigmoid': {'params': [('z',
                                       ('tensor',
                                        [('k', 'invariant'),
                                         ('h', 'invariant')]))],
                           'return_type': ('tensor',
                                           [('k', 'invariant'),
                                            ('h', 'invariant')]),
                           'body': ('var', 'res'),
                           'has_loop': False,
                           'statements': [('body_decl',
                                           'res',
                                           ('tensor',
                                            [('k', 'invariant'),
                                             ('h', 'invariant')]),
                                           ('div',
                                            ('num', 1.0),
                                            ('add',
                                             ('num', 1.0),
                                             ('call',
                                              'exp',
                                              [('neg', ('var', 'z'))]))))]},
               'rand_array': {'params': [('n', 'ℝ'), ('m', 'ℝ'), ('μ', 'ℝ')],
                              'return_type': ('tensor',
                                              [('n', 'invariant'),
                                               ('m', 'invariant')]),
                              'body': ('for_expr',
                                       'i',
                                       ('var', 'n'),
                                       ('for_expr',
                                        'j',
                                        ('var', 'm'),
                                        ('mul',
                                         ('var', 'μ'),
                                         ('sample_expr',
                                          'eps',
                                          ('call',
                                           'Normal',
                                           [('num', 0.0), ('num', 1.0)]))))),
                              'has_loop': False,
                              'statements': []},
               'zeros': {'params': [('n', 'ℝ'), ('m', 'ℝ')],
                         'return_type': ('tensor',
                                         [('n', 'invariant'),
                                          ('m', 'invariant')]),
                         'body': ('for_expr',
                                  'i',
                                  ('var', 'n'),
                                  ('for_expr',
                                   'j',
                                   ('var', 'm'),
                                   ('mul', ('var', 'j'), ('num', 0.0)))),
                         'has_loop': False,
                         'statements': []}},
 'classes': {'Encoder': {'class_params': [('We',
                                           ('tensor',
                                            [('m', 'invariant'),
                                             ('n', 'invariant')])),
                                          ('be',
                                           ('tensor',
                                            [(1, 'invariant'),
                                             ('n', 'invariant')])),
                                          ('Wu',
                                           ('tensor',
                                            [('n', 'invariant'),
                                             ('h', 'invariant')])),
                                          ('bu',
                                           ('tensor',
                                            [(1, 'invariant'),
                                             ('h', 'invariant')])),
                                          ('Wl',
                                           ('tensor',
                                            [('n', 'invariant'),
                                             ('h', 'invariant')])),
                                          ('bl',
                                           ('tensor',
                                            [(1, 'invariant'),
                                             ('h', 'invariant')]))],
                         'fields': [],
                         'methods': [{'name': 'λ',
                                      'params': [('x',
                                                  ('tensor',
                                                   [(1, 'invariant'),
                                                    ('m', 'invariant')]))],
                                      'return_type': ('tuple_type',
                                                      [('tensor',
                                                        [(1, 'invariant'),
                                                         ('h', 'invariant')]),
                                                       ('tensor',
                                                        [(1, 'invariant'),
                                                         ('h', 'invariant')])]),
                                      'statements': [('body_decl',
                                                      'he',
                                                      ('tensor',
                                                       [(1, 'invariant'),
                                                        ('n', 'invariant')]),
                                                      ('call',
                                                       'tanh',
                                                       [('add',
                                                         ('matmul',
                                                          ('var', 'x'),
                                                          ('var', 'We')),
                                                         ('var', 'be'))])),
                                                     ('body_decl',
                                                      'mu',
                                                      ('tensor',
                                                       [(1, 'invariant'),
                                                        ('h', 'invariant')]),
                                                      ('add',
                                                       ('matmul',
                                                        ('var', 'he'),
                                                        ('var', 'Wu')),
                                                       ('var', 'bu'))),
                                                     ('body_decl',
                                                      'lv',
                                                      ('tensor',
                                                       [(1, 'invariant'),
                                                        ('h', 'invariant')]),
                                                      ('add',
                                                       ('matmul',
                                                        ('var', 'he'),
                                                        ('var', 'Wl')),
                                                       ('var', 'bl')))],
                                      'body': ('tuple_return',
                                               ('var', 'mu'),
                                               ('var', 'lv'))}]},
             'Decoder': {'class_params': [('Wa',
                                           ('tensor',
                                            [('h', 'invariant'),
                                             ('n', 'invariant')])),
                                          ('ba',
                                           ('tensor',
                                            [(1, 'invariant'),
                                             ('n', 'invariant')])),
                                          ('Wo',
                                           ('tensor',
                                            [('n', 'invariant'),
                                             ('m', 'invariant')])),
                                          ('bo',
                                           ('tensor',
                                            [(1, 'invariant'),
                                             ('m', 'invariant')]))],
                         'fields': [],
                         'methods': [{'name': 'λ',
                                      'params': [('z',
                                                  ('tensor',
                                                   [(1, 'invariant'),
                                                    ('h', 'invariant')]))],
                                      'return_type': ('tensor',
                                                      [(1, 'invariant'),
                                                       ('m', 'invariant')]),
                                      'statements': [('body_decl',
                                                      'hid',
                                                      ('tensor',
                                                       [(1, 'invariant'),
                                                        ('n', 'invariant')]),
                                                      ('call',
                                                       'tanh',
                                                       [('add',
                                                         ('matmul',
                                                          ('var', 'z'),
                                                          ('var', 'Wa')),
                                                         ('var', 'ba'))]))],
                                      'body': ('call',
                                               'sigmoid',
                                               [('add',
                                                 ('matmul',
                                                  ('var', 'hid'),
                                                  ('var', 'Wo')),
                                                 ('var', 'bo'))])}]},
             'VariationalAutoEncoder': {'class_params': [('enc',
                                                          ('struct_type',
                                                           'Encoder')),
                                                         ('dec',
                                                          ('struct_type',
                                                           'Decoder')),
                                                         ('lat', 'ℝ')],
                                        'fields': [('mu',
                                                    ('tensor',
                                                     [(1, 'invariant'),
                                                      ('lat', 'invariant')])),
                                                   ('lv',
                                                    ('tensor',
                                                     [(1, 'invariant'),
                                                      ('lat', 'invariant')]))],
                                        'methods': [{'name': 'λ',
                                                     'params': [('x',
                                                                 ('tensor',
                                                                  [(1,
                                                                    'invariant'),
                                                                   ('n',
                                                                    'invariant')]))],
                                                     'return_type': ('tensor',
                                                                     [(1,
                                                                       'invariant'),
                                                                      ('n',
                                                                       'invariant')]),
                                                     'statements': [('body_tuple_unpack',
                                                                     ['this.mu',
                                                                      'this.lv'],
                                                                     ('call',
                                                                      'enc',
                                                                      [('var',
                                                                        'x')])),
                                                                    ('typed_sample',
                                                                     'eps',
                                                                     ('tensor',
                                                                      [(1,
                                                                        'invariant'),
                                                                       ('lat',
                                                                        'invariant')]),
                                                                     ('call',
                                                                      'Normal',
                                                                      [('num',
                                                                        0.0),
                                                                       ('num',
                                                                        1.0),
                                                                       ('num',
                                                                        1),
                                                                       ('var',
                                                                        'lat')])),
                                                                    ('body_decl',
                                                                     'sigma',
                                                                     ('tensor',
                                                                      [(1,
                                                                        'invariant'),
                                                                       ('lat',
                                                                        'invariant')]),
                                                                     ('call',
                                                                      'exp',
                                                                      [('mul',
                                                                        ('field_access',
                                                                         ('var',
                                                                          'this'),
                                                                         'lv'),
                                                                        ('num',
                                                                         0.5))])),
                                                                    ('body_decl',
                                                                     'z',
                                                                     ('tensor',
                                                                      [(1,
                                                                        'invariant'),
                                                                       ('lat',
                                                                        'invariant')]),
                                                                     ('add',
                                                                      ('field_access',
                                                                       ('var',
                                                                        'this'),
                                                                       'mu'),
                                                                      ('mul',
                                                                       ('var',
                                                                        'sigma'),
                                                                       ('var',
                                                                        'eps')))),
                                                                    ('body_decl',
                                                                     'x_hat',
                                                                     ('tensor',
                                                                      [(1,
                                                                        'invariant'),
                                                                       ('n',
                                                                        'invariant')]),
                                                                     ('call',
                                                                      'dec',
                                                                      [('var',
                                                                        'z')]))],
                                                     'body': ('var', 'x_hat')},
                                                    {'name': 'loss',
                                                     'params': [('target',
                                                                 ('tensor',
                                                                  [(1,
                                                                    'invariant'),
                                                                   (784,
                                                                    'invariant')])),
                                                                ('x_hat',
                                                                 ('tensor',
                                                                  [(1,
                                                                    'invariant'),
                                                                   (784,
                                                                    'invariant')]))],
                                                     'return_type': 'ℝ',
                                                     'statements': [('body_decl',
                                                                     'kl',
                                                                     'ℝ',
                                                                     ('mul',
                                                                      ('neg',
                                                                       ('num',
                                                                        0.5)),
                                                                      ('call',
                                                                       'sum',
                                                                       [('sub',
                                                                         ('sub',
                                                                          ('add',
                                                                           ('num',
                                                                            1.0),
                                                                           ('field_access',
                                                                            ('var',
                                                                             'this'),
                                                                            'lv')),
                                                                          ('pow',
                                                                           ('field_access',
                                                                            ('var',
                                                                             'this'),
                                                                            'mu'),
                                                                           ('num',
                                                                            2))),
                                                                         ('call',
                                                                          'exp',
                                                                          [('field_access',
                                                                            ('var',
                                                                             'this'),
                                                                            'lv')]))]))),
                                                                    ('body_decl',
                                                                     'recon',
                                                                     'ℝ',
                                                                     ('neg',
                                                                      ('call',
                                                                       'sum',
                                                                       [('add',
                                                                         ('mul',
                                                                          ('var',
                                                                           'target'),
                                                                          ('call',
                                                                           'log',
                                                                           [('add',
                                                                             ('var',
                                                                              'x_hat'),
                                                                             ('num',
                                                                              1e-07))])),
                                                                         ('mul',
                                                                          ('sub',
                                                                           ('num',
                                                                            1.0),
                                                                           ('var',
                                                                            'target')),
                                                                          ('call',
                                                                           'log',
                                                                           [('add',
                                                                             ('sub',
                                                                              ('num',
                                                                               1.0),
                                                                              ('var',
                                                                               'x_hat')),
                                                                             ('num',
                                                                              1e-07))])))])))],
                                                     'body': ('add',
                                                              ('var', 'kl'),
                                                              ('var',
                                                               'recon'))},
                                                    {'name': 'train',
                                                     'params': [('X',
                                                                 ('tensor',
                                                                  [(1000,
                                                                    'invariant'),
                                                                   (784,
                                                                    'invariant')])),
                                                                ('epochs', 'ℕ'),
                                                                ('lr', 'ℝ'),
                                                                ('images',
                                                                 'ℝ')],
                                                     'return_type': None,
                                                     'statements': [('body_for_range',
                                                                     'epoch',
                                                                     ('num', 0),
                                                                     ('var',
                                                                      'epochs'),
                                                                     [('loop_for_range',
                                                                       'i',
                                                                       ('num',
                                                                        0),
                                                                       ('var',
                                                                        'images'),
                                                                       [('loop_tuple_unpack',
                                                                         [('x',
                                                                           ('tensor',
                                                                            [(1,
                                                                              'invariant'),
                                                                             ('n',
                                                                              'invariant')]))],
                                                                         ('array',
                                                                          [('index',
                                                                            'X',
                                                                            ('imaginary',))])),
                                                                        ('loop_assign',
                                                                         'preds',
                                                                         ('call',
                                                                          'this',
                                                                          [('var',
                                                                            'x')])),
                                                                        ('loop_assign',
                                                                         'elbo',
                                                                         ('method_call',
                                                                          ('var',
                                                                           'this'),
                                                                          'loss',
                                                                          [('var',
                                                                            'x'),
                                                                           ('var',
                                                                            'preds')])),
                                                                        ('loop_assign',
                                                                         'grads',
                                                                         ('call',
                                                                          'grad',
                                                                          [('var',
                                                                            'elbo'),
                                                                           ('field_access',
                                                                            ('var',
                                                                             'this'),
                                                                            'params')])),
                                                                        ('body_expr',
                                                                         ('method_call',
                                                                          ('var',
                                                                           'this'),
                                                                          'update',
                                                                          [('var',
                                                                            'lr'),
                                                                           ('var',
                                                                            'grads')]))])])],
                                                     'body': None}]}},
 'program': [('seed', ('num', 42)),
             ('func_def', 'tanh'),
             ('func_def', 'sigmoid'),
             ('class_def', 'Encoder'),
             ('class_def', 'Decoder'),
             ('class_def', 'VariationalAutoEncoder'),
             ('func_def', 'rand_array'),
             ('func_def', 'zeros'),
             ('decl',
              'We',
              ('tensor', [(784, 'invariant'), (256, 'invariant')]),
              ('call',
               'rand_array',
               [('num', 784), ('num', 256), ('num', 0.05)]),
              56),
             ('decl',
              'be',
              ('tensor', [(1, 'invariant'), (256, 'invariant')]),
              ('call', 'zeros', [('num', 1), ('num', 256)]),
              57),
             ('decl',
              'Wu',
              ('tensor', [(256, 'invariant'), (20, 'invariant')]),
              ('call',
               'rand_array',
               [('num', 256), ('num', 20), ('num', 0.01)]),
              59),
             ('decl',
              'bu',
              ('tensor', [(1, 'invariant'), (20, 'invariant')]),
              ('call', 'zeros', [('num', 1), ('num', 20)]),
              60),
             ('decl',
              'Wl',
              ('tensor', [(256, 'invariant'), (20, 'invariant')]),
              ('call',
               'rand_array',
               [('num', 256), ('num', 20), ('num', 0.01)]),
              62),
             ('decl',
              'bl',
              ('tensor', [(1, 'invariant'), (20, 'invariant')]),
              ('call', 'zeros', [('num', 1), ('num', 20)]),
              63),
             ('decl',
              'Wa',
              ('tensor', [(20, 'invariant'), (256, 'invariant')]),
              ('call', 'rand_array', [('num', 20), ('num', 256), ('num', 0.2)]),
              65),
             ('decl',
              'ba',
              ('tensor', [(1, 'invariant'), (256, 'invariant')]),
              ('call', 'zeros', [('num', 1), ('num', 256)]),
              66),
             ('decl',
              'Wo',
              ('tensor', [(256, 'invariant'), (784, 'invariant')]),
              ('call',
               'rand_array',
               [('num', 256), ('num', 784), ('num', 0.05)]),
              68),
             ('decl',
              'bo',
              ('tensor', [(1, 'invariant'), (784, 'invariant')]),
              ('call', 'zeros', [('num', 1), ('num', 784)]),
              69),
             ('assign',
              'enc',
              ('call',
               'Encoder',
               [('var', 'We'),
                ('var', 'be'),
                ('var', 'Wu'),
                ('var', 'bu'),
                ('var', 'Wl'),
                ('var', 'bl')]),
              73),
             ('assign',
              'dec',
              ('call',
               'Decoder',
               [('var', 'Wa'), ('var', 'ba'), ('var', 'Wo'), ('var', 'bo')]),
              74),
             ('decl', 'lat', 'ℝ', ('num', 20.0), 75),
             ('assign',
              'vae',
              ('call',
               'VariationalAutoEncoder',
               [('var', 'enc'), ('var', 'dec'), ('var', 'lat')]),
              76),
             ('decl', 'images', 'ℝ', ('num', 1000), 80),
             ('decl',
              'X',
              ('tensor', [(1000, 'invariant'), (784, 'invariant')]),
              ('call',
               'rand_array',
               [('var', 'images'), ('num', 784), ('num', 0.1)]),
              81),
             ('decl',
              'x0',
              ('tensor', [(1, 'invariant'), (784, 'invariant')]),
              ('array', [('index', 'X', ('num', 0))]),
              84),
             ('decl',
              'recon_before',
              ('tensor', [(1, 'invariant'), (784, 'invariant')]),
              ('call', 'vae', [('var', 'x0')]),
              85),
             ('decl',
              'elbo_before',
              'ℝ',
              ('method_call',
               ('var', 'vae'),
               'loss',
               [('var', 'x0'), ('var', 'recon_before')]),
              86),
             ('expr', ('var', 'elbo_before'), 0),
             ('decl', 'epochs', 'ℕ', ('num', 10), 90),
             ('decl', 'lr', 'ℝ', ('num', 0.0002), 91),
             ('expr',
              ('method_call',
               ('var', 'vae'),
               'train',
               [('var', 'X'),
                ('var', 'epochs'),
                ('var', 'lr'),
                ('var', 'images')]),
              92),
             ('decl',
              'recon_after',
              ('tensor', [(1, 'invariant'), (784, 'invariant')]),
              ('call', 'vae', [('var', 'x0')]),
              95),
             ('decl',
              'elbo_after',
              'ℝ',
              ('method_call',
               ('var', 'vae'),
               'loss',
               [('var', 'x0'), ('var', 'recon_after')]),
              96),
             ('expr', ('var', 'elbo_after'), 0)]}
